In [53]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [54]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 500)

In [3]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [4]:
date = '20240501'

In [24]:
df = pd.read_clipboard()

In [25]:
df

                  appName                      package
0         IGNOU e-Content           ac.in.ignou.Viewer
1                     Aha                   ahaflix.tv
2    Grofers delivery app      com.grofers.customerapp
3          QR Code Reader                   app.qrcode
4                 Nishtha      ch.zhaw.nishtha_att_sys
..                    ...                          ...
428         YouCam Makeup   com.cyberlink.youcammakeup
429        YouCam Perfect     com.cyberlink.youperfect
430       Period Calendar      com.lbrc.PeriodCalendar
431                   Flo  org.iggymedia.periodtracker
432                  Yulu                app.yulu.bike

[433 rows x 2 columns]

In [32]:
df['app_name_space'] = ' ' + df['appName']

In [33]:
df

                  appName                      package         app_name_space
0         IGNOU e-Content           ac.in.ignou.Viewer        IGNOU e-Content
1                     Aha                   ahaflix.tv                    Aha
2    Grofers delivery app      com.grofers.customerapp   Grofers delivery app
3          QR Code Reader                   app.qrcode         QR Code Reader
4                 Nishtha      ch.zhaw.nishtha_att_sys                Nishtha
..                    ...                          ...                    ...
428         YouCam Makeup   com.cyberlink.youcammakeup          YouCam Makeup
429        YouCam Perfect     com.cyberlink.youperfect         YouCam Perfect
430       Period Calendar      com.lbrc.PeriodCalendar        Period Calendar
431                   Flo  org.iggymedia.periodtracker                    Flo
432                  Yulu                app.yulu.bike                   Yulu

[433 rows x 3 columns]

In [34]:
app_list_1 = df['appName'].to_list()
app_list_1

['IGNOU e-Content',
 'Aha',
 'Grofers delivery app',
 'QR Code Reader',
 'Nishtha',
 'Brainly',
 'Hinge',
 'Wunderlist',
 'Slack',
 'AajTak',
 'Aastha TV',
 'ABP Live',
 'AccuWeather',
 'Weather & Radar',
 'Mumbai Metro',
 'Adobe Lightroom',
 'Adobe Scan',
 'Afterlight',
 'Airbnb',
 'Airtel Thanks',
 'Aisle',
 'Weather Live',
 'Al Jazeera English',
 'AltBalaji',
 'Amazon Alexa',
 'Amazon Prime Video',
 'Amazon Shopping',
 'Amazon Music',
 'Calculator',
 'Clock',
 'Angel Broking',
 'Apollo 24/7',
 'Dream11',
 'Apple Music',
 'Zomato',
 'Arlo',
 'Asana',
 'Confluence',
 'JIRA',
 'Trello',
 'Mumbai Metro One',
 'August Home',
 'Axis Mobile',
 'Ayurveda Yoga',
 'MS Authenticator',
 'ALT Balaji',
 'MLB',
 'Bansal Classes',
 'BigBasket',
 'Bloomberg',
 'Blusmart',
 'Booking.com',
 'Hike',
 'Wynk Music',
 'Namma Metro',
 'BSNL My Circle',
 'BookMyShow',
 'Bumble',
 'Business Standard',
 'Aakash',
 'Byju',
 'Byte',
 'Chegg Study',
 'Chennai Metro',
 'Chingari',
 'Cisco',
 'Webex',
 'Cleartrip',
 'CNBC TV18',
 'Coffee Meets Bagel',
 'colegeduniya',
 'Course Hero',
 'Coursera',
 'Cricbuzz',
 'CricPlay',
 'Cure.fit',
 'Dainik Jagran',
 'Delhi Metro',
 'Feedly',
 'Quick Ride',
 'Quickride',
 "Domino's Pizza",
 'Doubtnut',
 'Dream11',
 'CRED',
 'DriveU Driver app',
 'Dropbox',
 'Moneycontrol',
 'Free Fire',
 'Dunzo',
 'Duolingo',
 'ecobee',
 'Eenadu',
 'Embibe',
 'Eros Now',
 'ESPNcricinfo',
 'ESPN',
 'Economic Times',
 'Evernote',
 'Expedia',
 'Facebook',
 'Messenger',
 'FanFight',
 'Fantasy Power 11',
 'Fitbit',
 'FitOn',
 'Fittr',
 'Flipkart',
 'Foodpanda',
 'Fossil Smartwatches',
 'FreeCharge',
 'Nykaa',
 'Happn',
 'Big Bazaar',
 'Gaana',
 'My11Circle',
 'Garmin Connect',
 'FIITJEE',
 'collegedekho',
 'Github',
 'Goibibo',
 'Goodreads',
 'Google Authenticator',
 'Google Classroom',
 'Google Sheets',
 'Google Slides',
 'Google Drive',
 'Google Home',
 'Google Analytics',
 'Google News',
 'Google Maps',
 'BHIM UPI',
 'Google Pay',
 'Google Photos',
 'Google Calendar',
 'Gmail',
 'Hangouts',
 'YouTube',
 'NFL',
 'ZEE5',
 'Grofers',
 'Happify',
 'HDFC Securities',
 'HealthifyMe',
 'Helo',
 'Hotstar',
 'Mint',
 'Hindustan Times',
 'Zepp (Amazfit)',
 'Huawei Health',
 'Hungama Music',
 'ICICI Direct',
 'Pocket',
 'IMD Weather',
 'The Indian Express',
 'Instagram',
 'Instacart delivery app',
 'caclubindia',
 'InVideo',
 'Sadhguru',
 'JioChat',
 'MX TakaTak',
 'JioSaavn',
 'Jio Cinema',
 'JioTV',
 'JioMart',
 'Kayak',
 'KFC India',
 'Kolkata Metro',
 'Koovs',
 'Kotak Stock Trader',
 'Likee',
 'Limeroad',
 'LinkedIn',
 'LinkedIn Learning',
 'Bangalore Metro',
 'Ludo King',
 'Dubsmash',
 'Camera MX',
 'MakeMyTrip',
 'Malayala Manorama',
 "McDonald's India",
 'Medlife',
 'Meesho',
 'Meetup',
 'meritnation',
 'mfine',
 'Bolo Indya',
 'Photomath',
 'MS Edge',
 'Microsoft Kaizala',
 'Microsoft Math Solver',
 'Microsoft Excel',
 'Microsoft Office Suite',
 'Microsoft 365',
 'Microsoft Lens',
 'Microsoft OneNote',
 'Outlook',
 'OneDrive',
 'Microsoft Teams',
 'Intune Company Portal',
 'MobiKwik',
 'Simplilearn',
 'File Commander',
 'Mobvoi',
 'Moj',
 'Moneycontrol',
 'Money Lover',
 'Moodle',
 'mParivahan',
 'Voonik',
 'Angel Broking',
 'MXTakaTak',
 'MX Player',
 'MyFitnessPal',
 'Myntra',
 'NBA',
 'NCERT Books',
 'NDTV News',
 'Netflix',
 'Netmeds',
 'InShorts',
 'Groww',
 'NHL',
 'Snapseed',
 'Shiksha Mitra',
 'Nike Training Club',
 'Retrica',
 'Walnut',
 'Nykaa',
 'OkCupid',
 'Ola',
 'Ola Driver app',
 '1mg',
 'Pocket',
 'OnePlus Health',
 '1Weather',
 'OYO',
 'Divya TV',
 'Paytm',
 'Paytm First Games',
 'Paytm Money',
 'Paytm Mall',
 'Pepperfry',
 'PharmEasy',
 'PhonePe',
 'PicsArt',
 'Pinterest',
 'Practo',
 'Delhi Metro Navigator',
 'Prisma',
 'Kolkata Metro Guide',
 'Purplle',
 'QuackQuack',
 'Quizlet',
 'Rapido Captain',
 'Miro',
 'Reddit',
 'Reuters',
 'Ajio',
 'Ring',
 'Rome2Rio',
 'Roposo',
 'Rosetta Stone',
 'Samsung Galaxy Wearable',
 'SmartThings',
 'Sharekhan',
 'Shein',
 'Shemaroo Bhakti',
 'ShemarooMe',
 'Shiksha.com',
 'Shiprocket driver app',
 'GroupMe',
 'Skype',
 'Skyscanner',
 'Slack',
 'Smule',
 'Snapchat',
 'HDFC Mobile Banking',
 'SonyLIV',
 'SoundCloud',
 'Spencers',
 'Splitwise',
 'Spotify',
 'Sri Ganesh Videos',
 'Sri Bhakti Channel',
 'Sri Chakra TV',
 'Star Sports',
 'Starbucks India',
 'StarMaker',
 'Strava',
 'Sun NXT',
 'WeChat',
 'PUBG Mobile',
 'The Athletic',
 'Porter Driver app',
 'ET Money',
 'News by Times of India',
 'ETMoney',
 'Tinder',
 'Todoist',
 'toppr',
 'Trello',
 'TripAdvisor',
 'Trivago',
 'Truecaller',
 'TrulyMadly',
 'Tumblr',
 'TuneIn Radio',
 'CNN',
 'Voot',
 'Twitter',
 'Woo',
 'Uber',
 'Uber Driver app',
 'Uber Eats',
 'Udemy',
 'Unacademy',
 'Upstox',
 'UrbanClap',
 'Vedantu',
 'Vero',
 'Voot',
 'Viber',
 'vidyakul',
 'My Study Life',
 'Vision11',
 'V-Health',
 'Vi (Vodafone Idea) App',
 'The Weather Channel',
 'WeatherBug',
 'WhatsApp',
 'Whitehat Jr',
 'Weather Underground',
 'Wyze',
 'Mi Fit',
 'Yahoo Finance',
 'Yahoo Fantasy Sports',
 'Yahoo Weather',
 'Yatra',
 'Zee5',
 'Zepto driver app',
 'Zerodha Kite',
 'Kite by Zerodha',
 'TikTok for Business',
 'TikTok',
 'Zivame',
 'Zoho Mail',
 'Zoho Meeting',
 'Zomato',
 'Zomato Driver app',
 'FirstCry',
 'Flipboard',
 'Geeks for geeks',
 'Borzo Driver app',
 'Air India',
 'IndiGo',
 'Diksha',
 'E-PG pathshala',
 'SWAYAM',
 'IRCTC Rail Connect',
 'Namma Yatri',
 'Namma Partner',
 'Josh',
 'ShareChat',
 'MyTeam11',
 'RedBus',
 'Shadowfax driver app',
 'Skymet Weather',
 'SpiceJet',
 'Disney+ Hotstar',
 'Sri Venkateswara Bhakti Channel',
 'Swiggy',
 'Swiggy Driver app',
 'myCBSEguide',
 'Triller',
 'SBI YONO',
 'Indian Railways',
 'Josh',
 'Line',
 'CBSE Saransh',
 'Stack overflow',
 'Paytm Money',
 'Notion',
 'NPS',
 'Coursera',
 'edX',
 'Khan Academy',
 'Sri Sankara TV',
 'Telegram',
 'Jugnoo',
 'Dunzo Driver app',
 'In Drive',
 'Club Factory',
 'BBC News',
 'BBC Sport',
 'Zoom',
 'Physics Wallah',
 'Cred',
 'T Savaari',
 'Abhibus',
 'Ixigo',
 'DriveU',
 'Urban Company',
 'Magicbricks',
 'NoBroker',
 '99acres',
 'HomeLane',
 'Livspace',
 'Nestaway',
 'Dailyhunt',
 'Calm',
 'Home Workout - No Equipment',
 'AliExpress',
 'eBay',
 'Tata CLiQ',
 'Lybrate',
 'MedPlus Mart',
 'PUBG MOBILE',
 'Free Fire',
 'Candy Crush Saga',
 'Clash of Clans',
 '8 Ball Pool',
 'Among Us',
 'Call of Duty: Mobile',
 'Free Fire MAX',
 'Asphalt 9: Legends',
 'VSCO',
 'YouCam Makeup',
 'YouCam Perfect',
 'Period Calendar',
 'Flo',
 'Yulu']

In [67]:
test = [
    # 'IGNOU e-Content',
 # 'Aha',
 # 'Grofers delivery app',
 # 'QR Code Reader',
 # 'Nishtha',
 # 'Brainly',
 # 'Hinge',
 # 'Wunderlist',
 # 'Slack',
 # 'AajTak',
 # 'Aastha TV',
 # 'ABP Live',
 # 'AccuWeather',
 # 'Weather & Radar',
 # 'Mumbai Metro',
 # 'Adobe Lightroom',
 # 'Adobe Scan',
 # 'Afterlight',
 # 'Airbnb',
 # 'Airtel Thanks',
 # 'Aisle',
 # 'Weather Live',
 # 'Al Jazeera English',
 # 'AltBalaji',
 # 'Amazon Alexa',
 # 'Amazon Prime Video',
 # 'Amazon Shopping',
 # 'Amazon Music',
 # 'Calculator',
 # 'Clock',
 # 'Angel Broking',
 # 'Apollo 24/7',
 # 'Dream11',
 # 'Apple Music',
 # 'Zomato',
 # 'Arlo',
 # 'Asana',
 # 'Confluence',
 # 'JIRA',
 # 'Trello',
 # 'Mumbai Metro One',
 # 'August Home',
 # 'Axis Mobile',
 # 'Ayurveda Yoga',
 # 'MS Authenticator',
 # 'ALT Balaji',
 # 'MLB',
 # 'Bansal Classes',
 # 'BigBasket',
 # 'Bloomberg',
 # 'Blusmart',
 # 'Booking.com',
 # 'Hike',
 # 'Wynk Music',
 # 'Namma Metro',
 # 'BSNL My Circle',
 # 'BookMyShow',
 # 'Bumble',
 # 'Business Standard',
 # 'Aakash',
 # 'Byju',
 # 'Byte',
 # 'Chegg Study',
 # 'Chennai Metro',
 # 'Chingari',
 # 'Cisco',
 # 'Webex',
 # 'Cleartrip',
 # 'CNBC TV18',
 # 'Coffee Meets Bagel',
 # 'colegeduniya',
 # 'Course Hero',
 # 'Coursera',
 # 'Cricbuzz',
 # 'CricPlay',
 # 'Cure.fit',
 # 'Dainik Jagran',
 # 'Delhi Metro',
 # 'Feedly',
 # 'Quick Ride',
 # 'Quickride',
 # # "Domino's Pizza",
 # 'Doubtnut',
 # 'Dream11',
 # 'CRED',
 # 'DriveU Driver app',
 # 'Dropbox',
 # 'Moneycontrol',
 # 'Free Fire',
 # 'Dunzo',
 # 'Duolingo',
 # 'ecobee',
 # 'Eenadu',
 # 'Embibe',
 # 'Eros Now',
 # 'ESPNcricinfo',
 # 'ESPN',
 # 'Economic Times',
 # 'Evernote',
 # 'Expedia',
 # 'Facebook',
 # 'Messenger',
 # 'FanFight',
 # 'Fantasy Power 11',
 # 'Fitbit',
 # 'FitOn',
 # 'Fittr',
 # 'Flipkart',
 # 'Foodpanda',
 # 'Fossil Smartwatches',
 # 'FreeCharge',
 # 'Nykaa',
 # 'Happn',
 # 'Big Bazaar',
 # 'Gaana',
 # 'My11Circle',
 # 'Garmin Connect',
 # 'FIITJEE',
 # 'collegedekho',
 # 'Github',
 # 'Goibibo',
 # 'Goodreads',
 # 'Google Authenticator',
 # 'Google Classroom',
 # 'Google Sheets',
 # 'Google Slides',
 # 'Google Drive',
 # 'Google Home',
 # 'Google Analytics',
 # 'Google News',
 # 'Google Maps',
 # 'BHIM UPI',
 # 'Google Pay',
 # 'Google Photos',
 # 'Google Calendar',
 # 'Gmail',
 # 'Hangouts',
 # 'YouTube',
 # 'NFL',
 # 'ZEE5',
 # 'Grofers',
 # 'Happify',
 # 'HDFC Securities',
 # 'HealthifyMe',
 # 'Helo',
 # 'Hotstar',
 # 'Mint',
 # 'Hindustan Times',
 # # 'Zepp (Amazfit)',
 # 'Huawei Health',
 # 'Hungama Music',
 # 'ICICI Direct',
 # 'Pocket',
 # 'IMD Weather',
 # 'The Indian Express',
 # 'Instagram',
 # 'Instacart delivery app',
 # 'caclubindia',
 # 'InVideo',
 # 'Sadhguru',
 # 'JioChat',
 # 'MX TakaTak',
 # 'JioSaavn',
 # 'Jio Cinema',
 # 'JioTV',
 # 'JioMart',
 # 'Kayak',
 # 'KFC India',
 # 'Kolkata Metro',
 # 'Koovs',
 # 'Kotak Stock Trader',
 # 'Likee',
 # 'Limeroad',
 # 'LinkedIn',
 # 'LinkedIn Learning',
 # 'Bangalore Metro',
 # 'Ludo King',
 # 'Dubsmash',
 # 'Camera MX',
 # 'MakeMyTrip',
 # 'Malayala Manorama',
 # "McDonald's India",
 'Medlife',
 'Meesho',
 'Meetup',
 'meritnation',
 'mfine',
 'Bolo Indya',
 'Photomath',
 'MS Edge',
 'Microsoft Kaizala',
 'Microsoft Math Solver',
 'Microsoft Excel',
 'Microsoft Office Suite',
 'Microsoft 365',
 'Microsoft Lens',
 'Microsoft OneNote',
 'Outlook',
 'OneDrive',
 'Microsoft Teams',
 'Intune Company Portal',
 'MobiKwik',
 'Simplilearn',
 'File Commander',
 'Mobvoi',
 'Moj',
 'Moneycontrol',
 'Money Lover',
 'Moodle',
 'mParivahan',
 'Voonik',
 'Angel Broking',
 'MXTakaTak',
 'MX Player',
 'MyFitnessPal',
 'Myntra',
 'NBA',
 'NCERT Books',
 'NDTV News',
 'Netflix',
 'Netmeds',
 'InShorts',
 'Groww',
 'NHL',
 'Snapseed',
 'Shiksha Mitra',
 'Nike Training Club',
 'Retrica',
 'Walnut',
 'Nykaa',
 'OkCupid',
 'Ola',
 'Ola Driver app',
 '1mg',
 'Pocket',
 'OnePlus Health',
 '1Weather',
 'OYO',
 'Divya TV',
 'Paytm',
 'Paytm First Games',
 'Paytm Money',
 'Paytm Mall',
 'Pepperfry',
 'PharmEasy',
 'PhonePe',
 'PicsArt',
 'Pinterest',
 'Practo',
 'Delhi Metro Navigator',
 'Prisma',
 'Kolkata Metro Guide',
 'Purplle',
 'QuackQuack',
 'Quizlet',
 'Rapido Captain',
 'Miro',
 'Reddit',
 'Reuters',
 'Ajio',
 'Ring',
 'Rome2Rio',
 'Roposo',
 'Rosetta Stone',
 'Samsung Galaxy Wearable',
 'SmartThings',
 'Sharekhan',
 'Shein',
 'Shemaroo Bhakti',
 'ShemarooMe',
 'Shiksha.com',
 'Shiprocket driver app',
 'GroupMe',
 'Skype',
 'Skyscanner',
 'Slack',
 'Smule',
 'Snapchat',
 'HDFC Mobile Banking',
 'SonyLIV',
 'SoundCloud',
 'Spencers',
 'Splitwise',
 'Spotify',
 'Sri Ganesh Videos',
 'Sri Bhakti Channel',
 'Sri Chakra TV',
 'Star Sports',
 'Starbucks India',
 'StarMaker',
 'Strava',
 'Sun NXT',
 'WeChat',
 'PUBG Mobile',
 'The Athletic',
 'Porter Driver app',
 'ET Money',
 'News by Times of India',
 'ETMoney',
 'Tinder',
 'Todoist',
 'toppr',
 'Trello',
 'TripAdvisor',
 'Trivago',
 'Truecaller',
 'TrulyMadly',
 'Tumblr',
 'TuneIn Radio',
 'CNN',
 'Voot',
 'Twitter',
 'Woo',
 'Uber',
 'Uber Driver app',
 'Uber Eats',
 'Udemy',
 'Unacademy',
 'Upstox',
 'UrbanClap',
 'Vedantu',
 'Vero',
 'Voot',
 'Viber',
 'vidyakul',
 'My Study Life',
 'Vision11',
 'V-Health',
 # 'Vi (Vodafone Idea) App',
 'The Weather Channel',
 'WeatherBug',
 'WhatsApp',
 'Whitehat Jr',
 'Weather Underground',
 'Wyze',
 'Mi Fit',
 'Yahoo Finance',
 'Yahoo Fantasy Sports',
 'Yahoo Weather',
 'Yatra',
 'Zee5',
 'Zepto driver app',
 'Zerodha Kite',
 'Kite by Zerodha',
 'TikTok for Business',
 'TikTok',
 'Zivame',
 'Zoho Mail',
 'Zoho Meeting',
 'Zomato',
 'Zomato Driver app',
 'FirstCry',
 'Flipboard',
 'Geeks for geeks',
 'Borzo Driver app',
 'Air India',
 'IndiGo',
 'Diksha',
 'E-PG pathshala',
 'SWAYAM',
 'IRCTC Rail Connect',
 'Namma Yatri',
 'Namma Partner',
 'Josh',
 'ShareChat',
 'MyTeam11',
 'RedBus',
 'Shadowfax driver app',
 'Skymet Weather',
 'SpiceJet',
 'Disney+ Hotstar',
 'Sri Venkateswara Bhakti Channel',
 'Swiggy',
 'Swiggy Driver app',
 'myCBSEguide',
 'Triller',
 'SBI YONO',
 'Indian Railways',
 'Josh',
 'Line',
 'CBSE Saransh',
 'Stack overflow',
 'Paytm Money',
 'Notion',
 'NPS',
 'Coursera',
 'edX',
 'Khan Academy',
 'Sri Sankara TV',
 'Telegram',
 'Jugnoo',
 'Dunzo Driver app',
 'In Drive',
 'Club Factory',
 'BBC News',
 'BBC Sport',
 'Zoom',
 'Physics Wallah',
 'Cred',
 'T Savaari',
 'Abhibus',
 'Ixigo',
 'DriveU',
 'Urban Company',
 'Magicbricks',
 'NoBroker',
 '99acres',
 'HomeLane',
 'Livspace',
 'Nestaway',
 'Dailyhunt',
 'Calm',
 'Home Workout - No Equipment',
 'AliExpress',
 'eBay',
 'Tata CLiQ',
 'Lybrate',
 'MedPlus Mart',
 'PUBG MOBILE',
 'Free Fire',
 'Candy Crush Saga',
 'Clash of Clans',
 '8 Ball Pool',
 'Among Us',
 'Call of Duty: Mobile',
 'Free Fire MAX',
 'Asphalt 9: Legends',
 'VSCO',
 'YouCam Makeup',
 'YouCam Perfect',
 'Period Calendar',
 'Flo',
 'Yulu']

In [68]:
## base

for i in test:
    
    var = i
    var_space = ' ' + var
    # print(var)
    # print(var_space)
    base_query = f"""
        
        SELECT
            yyyymmdd,
            app_list
        FROM
            (
            SELECT
                id user, 
                yyyymmdd,
                json_extract(data, '$.appographyData') as app_list
            FROM 
                raw_internal.kafka_info_customer_installed_apps_v1
            WHERE 
                yyyymmdd >= '{date}'
            )
        WHERE 
            json_array_contains(CAST(app_list AS JSON), '{var}') 
            OR 
            json_array_contains(CAST(app_list AS JSON), '{var_space}') 
        LIMIT 1
    """

    df_base_query = pd.read_sql(base_query, connection)
    
    if df_base_query.empty:
      print(var,"---------Empty----------!!!!!!!!!!!")

Medlife ---------Empty----------!!!!!!!!!!!
Meetup ---------Empty----------!!!!!!!!!!!
mfine ---------Empty----------!!!!!!!!!!!
Bolo Indya ---------Empty----------!!!!!!!!!!!
Microsoft Kaizala ---------Empty----------!!!!!!!!!!!
Microsoft Office Suite ---------Empty----------!!!!!!!!!!!
Intune Company Portal ---------Empty----------!!!!!!!!!!!
Mobvoi ---------Empty----------!!!!!!!!!!!
Moj ---------Empty----------!!!!!!!!!!!
Money Lover ---------Empty----------!!!!!!!!!!!
mParivahan ---------Empty----------!!!!!!!!!!!
MXTakaTak ---------Empty----------!!!!!!!!!!!
MX Player ---------Empty----------!!!!!!!!!!!
NDTV News ---------Empty----------!!!!!!!!!!!
Netmeds ---------Empty----------!!!!!!!!!!!
InShorts ---------Empty----------!!!!!!!!!!!
Snapseed ---------Empty----------!!!!!!!!!!!
Retrica ---------Empty----------!!!!!!!!!!!
Walnut ---------Empty----------!!!!!!!!!!!
1mg ---------Empty----------!!!!!!!!!!!
OnePlus Health ---------Empty----------!!!!!!!!!!!
1Weather ---------Empty----------!!!!!!!!!!!
OYO ---------Empty----------!!!!!!!!!!!
Divya TV ---------Empty----------!!!!!!!!!!!
Paytm ---------Empty----------!!!!!!!!!!!
Paytm First Games ---------Empty----------!!!!!!!!!!!
Pepperfry ---------Empty----------!!!!!!!!!!!
PhonePe ---------Empty----------!!!!!!!!!!!
Practo ---------Empty----------!!!!!!!!!!!
Delhi Metro Navigator ---------Empty----------!!!!!!!!!!!
Prisma ---------Empty----------!!!!!!!!!!!
Kolkata Metro Guide ---------Empty----------!!!!!!!!!!!
Purplle ---------Empty----------!!!!!!!!!!!
Quizlet ---------Empty----------!!!!!!!!!!!
Reddit ---------Empty----------!!!!!!!!!!!
Reuters ---------Empty----------!!!!!!!!!!!
Ring ---------Empty----------!!!!!!!!!!!
Rome2Rio ---------Empty----------!!!!!!!!!!!
Rosetta Stone ---------Empty----------!!!!!!!!!!!
SmartThings ---------Empty----------!!!!!!!!!!!
Sharekhan ---------Empty----------!!!!!!!!!!!
Shein ---------Empty----------!!!!!!!!!!!
Shemaroo Bhakti ---------Empty----------!!!!!!!!!!!
ShemarooMe ---------Empty----------!!!!!!!!!!!
GroupMe ---------Empty----------!!!!!!!!!!!
Skyscanner ---------Empty----------!!!!!!!!!!!
Smule ---------Empty----------!!!!!!!!!!!
Spencers ---------Empty----------!!!!!!!!!!!
Splitwise ---------Empty----------!!!!!!!!!!!
Sri Ganesh Videos ---------Empty----------!!!!!!!!!!!
Sri Bhakti Channel ---------Empty----------!!!!!!!!!!!
Sri Chakra TV ---------Empty----------!!!!!!!!!!!
Star Sports ---------Empty----------!!!!!!!!!!!
Starbucks India ---------Empty----------!!!!!!!!!!!
StarMaker ---------Empty----------!!!!!!!!!!!
Sun NXT ---------Empty----------!!!!!!!!!!!
PUBG Mobile ---------Empty----------!!!!!!!!!!!
The Athletic ---------Empty----------!!!!!!!!!!!
ET Money ---------Empty----------!!!!!!!!!!!
News by Times of India ---------Empty----------!!!!!!!!!!!
ETMoney ---------Empty----------!!!!!!!!!!!
Todoist ---------Empty----------!!!!!!!!!!!
TuneIn Radio ---------Empty----------!!!!!!!!!!!
CNN ---------Empty----------!!!!!!!!!!!
Woo ---------Empty----------!!!!!!!!!!!
Upstox ---------Empty----------!!!!!!!!!!!
UrbanClap ---------Empty----------!!!!!!!!!!!
Vero ---------Empty----------!!!!!!!!!!!
V-Health ---------Empty----------!!!!!!!!!!!
The Weather Channel ---------Empty----------!!!!!!!!!!!
WeatherBug ---------Empty----------!!!!!!!!!!!
Weather Underground ---------Empty----------!!!!!!!!!!!
Wyze ---------Empty----------!!!!!!!!!!!
Yahoo Finance ---------Empty----------!!!!!!!!!!!
Yahoo Weather ---------Empty----------!!!!!!!!!!!
Zee5 ---------Empty----------!!!!!!!!!!!
Zerodha Kite ---------Empty----------!!!!!!!!!!!
TikTok for Business ---------Empty----------!!!!!!!!!!!
TikTok ---------Empty----------!!!!!!!!!!!
Air India ---------Empty----------!!!!!!!!!!!
IRCTC Rail Connect ---------Empty----------!!!!!!!!!!!
Josh ---------Empty----------!!!!!!!!!!!
Skymet Weather ---------Empty----------!!!!!!!!!!!
SpiceJet ---------Empty----------!!!!!!!!!!!
Sri Venkateswara Bhakti Channel ---------Empty----------!!!!!!!!!!!
Triller ---------Empty----------!!!!!!!!!!!
SBI YONO ---------Empty----------!!!!!!!!!!!
Indian Railways ---------Empty----------!!!!!!!!!!!
Josh ---------Empty----------!!!!!!!!!!!
CBSE Saransh ---------Empty----------!!!!!!!!!!!
Sri Sankara TV ---------Empty----------!!!!!!!!!!!
BBC News ---------Empty----------!!!!!!!!!!!
BBC Sport ---------Empty----------!!!!!!!!!!!
Calm ---------Empty----------!!!!!!!!!!!

In [ ]:
46 - Remove
117 - Update package id's
49 - Newly requested apps