In [1]:
import os
import re
import time

import numpy as np
import pandas as pd
import hiplot as hip
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
os.environ['PYDEVD_DISABLE_FILE_VALIDATION'] = '1'

In [2]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [3]:
# Get the current working directory
cwd = os.getcwd()
print(cwd)

/Users/E2074/analytics/customer/appography/cleanup_activity

In [9]:
start_date = '20240715' 
end_date = '20240724'

In [10]:
#regular-exp 
def extract_and_trim(text):
    return [val.strip() for val in re.findall(r'"(.*?)"', text)]

In [11]:
query = f"""

    select 
        id,
        apps_list
    from 
        (
        select
            id, yyyymmdd,
            json_extract(data, '$.appographyData') as apps_list
            -- row_number() over(partition by id order by updated_epoch desc) updated_seq
        from 
            raw_internal.kafka_info_customer_installed_apps_v1
        where 
            yyyymmdd BETWEEN '{start_date}'
            AND '{end_date}'
        )
    -- where
       -- updated_seq = 1
"""

df_data_raw = pd.read_sql(query, connection)

In [12]:
df_data_raw.head(5)

                         id                                          apps_list
0  6614248da2e3de5a4166ccac  ["Duolingo"," Messenger"," Google Drive"," Goo...
1  62c9a660551cdb02f8c0d2ee  ["Zomato"," BigBasket"," Wynk Music"," Domino'...
2  6362bac785b399b62658418c  ["Grofers delivery app"," Zomato"," Domino's P...
3  627d8decc75b905bb908d3a5  ["Facebook"," Flipkart"," Google Drive"," Goog...
4  623ac521b9a21e697dcbde95  ["Airtel Thanks"," Amazon Prime Video"," Clock...

In [13]:
df_data = df_data_raw.copy()

In [14]:
df_data['app_list_set'] = df_data['apps_list'].apply(lambda x: extract_and_trim(x))
df_data = df_data[['id', 'app_list_set']]

In [15]:
df_data.head(5)

                         id                                       app_list_set
0  6614248da2e3de5a4166ccac  [Duolingo, Messenger, Google Drive, Google Hom...
1  62c9a660551cdb02f8c0d2ee  [Zomato, BigBasket, Wynk Music, Domino's Pizza...
2  6362bac785b399b62658418c  [Grofers delivery app, Zomato, Domino's Pizza,...
3  627d8decc75b905bb908d3a5  [Facebook, Flipkart, Google Drive, Google Maps...
4  623ac521b9a21e697dcbde95  [Airtel Thanks, Amazon Prime Video, Clock, Ang...

In [16]:
## Explode list into individual rows

df_data_explode = df_data.explode('app_list_set')
df_data_explode['app_list_set'] = df_data_explode['app_list_set'].str.lower()

df_data_explode.head(4)

                         id  app_list_set
0  6614248da2e3de5a4166ccac      duolingo
0  6614248da2e3de5a4166ccac     messenger
0  6614248da2e3de5a4166ccac  google drive
0  6614248da2e3de5a4166ccac   google home

In [17]:
total_customers = df_data_explode.id.nunique()
total_customers

10311348

In [18]:
df_temp = df_data_explode\
            .groupby(['app_list_set'])\
            .agg(customers = ('id','nunique'))\
            .sort_values(['customers'],ascending=False)\
            .reset_index()
df_temp['%'] =  (df_temp['customers']*100.00/total_customers).round(2)
df_temp

                    app_list_set  customers      %
0                    google maps   10307688  99.96
1                        youtube   10270401  99.60
2                          gmail   10269261  99.59
3                       whatsapp   10021891  97.19
4                  google photos    9724178  94.31
5                      instagram    8266859  80.17
6                   google drive    7665706  74.34
7                     google pay    7515895  72.89
8                       facebook    7216195  69.98
9                     truecaller    6911825  67.03
10                      flipkart    6513104  63.16
11                       phonepe    6468711  62.73
12               google calendar    6444712  62.50
13                   paytm money    5990864  58.10
14               disney+ hotstar    5685274  55.14
15                      snapchat    5393823  52.31
16                      telegram    5134587  49.80
17                         paytm    4915378  47.67
18                        zomato    4891104  47.43
19                       spotify    4890288  47.43
20                    jio cinema    4694199  45.52
21                           ola    4645595  45.05
22                       hotstar    4613446  44.74
23                      linkedin    4598234  44.59
24                       netflix    4588004  44.49
25                          uber    4391428  42.59
26                        swiggy    4338038  42.07
27                 airtel thanks    3959077  38.40
28                        meesho    3783916  36.70
29                     messenger    3645942  35.36
30                         clock    3514461  34.08
31                        myntra    3423479  33.20
32            amazon prime video    3404513  33.02
33             where is my train    3264129  31.66
34                   google news    3146358  30.51
35                     mx player    2846138  27.60
36                   google home    2742219  26.59
37                          zoom    2399014  23.27
38                 google sheets    2356882  22.86
39                    wynk music    2308509  22.39
40                    bookmyshow    2281318  22.12
41                          ajio    2248795  21.81
42                      onedrive    2235901  21.68
43                       grofers    2233444  21.66
44            irctc rail connect    2169414  21.04
45                     ludo king    2002528  19.42
46                       outlook    1918997  18.61
47                 microsoft 365    1875169  18.19
48          grofers delivery app    1873592  18.17
49                       blinkit    1867971  18.12
50                      sbi yono    1811057  17.56
51                     dailyhunt    1702954  16.52
52               microsoft teams    1691329  16.40
53                      jiosaavn    1614436  15.66
54                       twitter    1519209  14.73
55           hdfc mobile banking    1519094  14.73
56                         zepto    1499435  14.54
57                          cred    1450431  14.07
58                        redbus    1440638  13.97
59                 google slides    1428530  13.85
60                         groww    1413353  13.71
61                     pinterest    1378900  13.37
62                          zee5    1356928  13.16
63                    adobe scan    1278458  12.40
64                     sharechat    1233694  11.96
65              candy crush saga    1226156  11.89
66                     bigbasket    1223358  11.86
67                         jiotv    1208737  11.72
68                       sonyliv    1180661  11.45
69                domino's pizza    1171361  11.36
70                   axis mobile    1124481  10.91
71                    makemytrip    1049373  10.18
72                         ixigo    1025695   9.95
73                       picsart     995869   9.66
74                        shopsy     993334   9.63
75                   imobile pay     991831   9.62
76                       jiomart     933557   9.05
77              ms authenticator     924572   8.97
78                   pubg mobile     911351   8.84
79                           uts     906833   8.79
80       samsung galaxy wearable     891363   8.64
81                 free fire max     873453   8.47
82               microsoft excel     837669   8.12
83                 urban company     834356   8.09
84                   smartthings     832891   8.08
85                      in drive     767960   7.45
86                         nykaa     756695   7.34
87                rapido captain     707078   6.86
88                      cricbuzz     659997   6.40
89                      mobikwik     654338   6.35
90                      nobroker     620621   6.02
91                           aha     611124   5.93
92                  amazon music     587337   5.70
93                 angel broking     584837   5.67
94                    mparivahan     584312   5.67
95                       dream11     581130   5.64
96                      snapseed     569723   5.53
97                  zerodha kite     556415   5.40
98                           moj     553169   5.36
99                     pocket fm     551498   5.35
100        intune company portal     549832   5.33
101                      goibibo     546686   5.30
102                     firstcry     486128   4.71
103                     lenskart     484420   4.70
104             google classroom     476477   4.62
105         google authenticator     463273   4.49
106                      abhibus     459272   4.45
107              adobe lightroom     446045   4.33
108                          oyo     429726   4.17
109                     bhim upi     424185   4.11
110                  namma yatri     418986   4.06
111                  booking.com     417389   4.05
112                      purplle     412566   4.00
113                   apollo 247     405481   3.93
114                        dunzo     400622   3.89
115                   my11circle     394603   3.83
116                   mx takatak     383939   3.72
117                    splitwise     383898   3.72
118              uber driver app     377843   3.66
119                     duolingo     363649   3.53
120                        gaana     357282   3.46
121                      ms edge     342960   3.33
122                        udemy     331685   3.22
123               ola driver app     324294   3.15
124                 amazon alexa     320327   3.11
125                  8 ball pool     318068   3.08
126                          1mg     313165   3.04
127                    tata cliq     293311   2.84
128                         josh     291817   2.83
129               subway surfers     287968   2.79
130                     inshorts     281288   2.73
131                    pharmeasy     277559   2.69
132                        webex     276380   2.68
133                       upstox     275505   2.67
134                        skype     272138   2.64
135                  carrom pool     265330   2.57
136                 moneycontrol     260428   2.53
137                      sun nxt     254732   2.47
138                      brainly     245560   2.38
139               clash of clans     241064   2.34
140                    kfc india     240612   2.33
141                       indigo     227190   2.20
142               physics wallah     217965   2.11
143                         voot     214473   2.08
144                       reddit     208753   2.02
145                      99acres     208367   2.02
146                         byju     204020   1.98
147                  magicbricks     199933   1.94
148                    unacademy     194647   1.89
149                          nps     191187   1.85
150            swiggy driver app     190918   1.85
151                  healthifyme     190746   1.85
152                dmrc momentum     188676   1.83
153                 policybazaar     187395   1.82
154                       airbnb     184549   1.79
155                       tinder     170702   1.66
156                   skyscanner     169699   1.65
157                        slack     166170   1.61
158                          h&m     165771   1.61
159               ttdevasthanams     165657   1.61
160                     cult.fit     160865   1.56
161                       bumble     154026   1.49
162                     moj lite     151142   1.47
163                    cleartrip     148057   1.44
164               microsoft lens     145965   1.42
165                fresh to home     144165   1.40
166                     blusmart     140961   1.37
167               acko insurance     140813   1.37
168        delhi metro navigator     138220   1.34
169              kite by zerodha     135113   1.31
170                       practo     134563   1.30
171         call of duty: mobile     127895   1.24
172                       fitbit     125451   1.22
173                     coursera     124690   1.21
174                amazon minitv     124602   1.21
175                         yulu     119568   1.16
176       intune  company portal     119121   1.16
177  home workout - no equipment     118180   1.15
178                       zivame     117958   1.14
179               cricket league     117214   1.14
180                    lifestyle     116837   1.13
181                bsnl selfcare     116414   1.13
182            porter driver app     116365   1.13
183                     limeroad     116339   1.13
184             the souled store     114550   1.11
185                  namma metro     114149   1.11
186                      fancode     114078   1.11
187                    starmaker     113228   1.10
188              pizza hut india     112703   1.09
189                   easemytrip     110417   1.07
190            microsoft onenote     106285   1.03
191                   freecharge     105884   1.03
192                 rummy circle     102398   0.99
193                     among us     100783   0.98
194                      netmeds      99959   0.97
195                  google chat      99741   0.97
196                 medplus mart      99666   0.97
197            zomato driver app      98777   0.96
198                          flo      95550   0.93
199                hungama music      94690   0.92
200                       swayam      92727   0.90
201                       signal      92340   0.90
202               youcam perfect      90062   0.87
203                        yatra      86301   0.84
204               economic times      85099   0.83
205            hill climb racing      85016   0.82
206                flightradar24      83589   0.81
207                   calculator      79903   0.77
208                         ring      79399   0.77
209             mcdonald's india      75856   0.74
210                      dropbox      74188   0.72
211                       tummoc      73889   0.72
212                   quick ride      73397   0.71
213                    nykaa man      73268   0.71
214                 temple run 2      71553   0.69
215            linkedin learning      70303   0.68
216                         zara      67911   0.66
217                     et money      64846   0.63
218                       notion      63827   0.62
219               zepp (amazfit)      63112   0.61
220                       aajtak      62609   0.61
221          icicidirect: stocks      62503   0.61
222                   alt balaji      62406   0.61
223                     doubtnut      61715   0.60
224                    altbalaji      60690   0.59
225                        hinge      60610   0.59
226                    kotak neo      59547   0.58
227                    pepperfry      58746   0.57
228                       strava      57407   0.56
229                       mi fit      57121   0.55
230           chennai metro rail      56442   0.55
231                   soundcloud      56263   0.55
232         train ticket booking      55664   0.54
233                       github      55497   0.54
234                     westside      53028   0.51
235                       diksha      51141   0.50
236                 mini militia      51060   0.50
237                        happn      50817   0.49
238             zepto driver app      49747   0.48
239                    t savaari      47851   0.46
240              starbucks india      47747   0.46
241                     sadhguru      47675   0.46
242                       driveu      47228   0.46
243              weather & radar      46710   0.45
244           asphalt 9: legends      46330   0.45
245                       jugnoo      44360   0.43
246         shadowfax driver app      44286   0.43
247                huawei health      41034   0.40
248                    zoho mail      40289   0.39
249                      trivago      39562   0.38
250                 myfitnesspal      39314   0.38
251              amazon shopping      39199   0.38
252                         mint      37876   0.37
253                  my bsnl app      37687   0.37
254      icicidirect markets app      37265   0.36
255                  simplilearn      35941   0.35
256                    sharekhan      34951   0.34
257                namma partner      34233   0.33
258                        aisle      33807   0.33
259                         wego      32326   0.31
260              geeks for geeks      31556   0.31
261                    a23 rummy      31209   0.30
262                    uber eats      31030   0.30
263                     evernote      30486   0.30
264                   quackquack      30315   0.29
265                  apple music      30165   0.29
266                     spencers      29431   0.29
267             borzo driver app      29187   0.28
268                    air india      28785   0.28
269                        smule      28778   0.28
270                        viber      28026   0.27
271                       moodle      27640   0.27
272            shemaroome livetv      27173   0.26
273     blinkit delivery partner      27053   0.26
274        shiprocket driver app      25995   0.25
275                 espncricinfo      25598   0.25
276                        mfine      24467   0.24
277                  ncert books      23673   0.23
278                     icai bos      23423   0.23
279                     hangouts      23314   0.23
280        money manager expense      23059   0.22
281                      vistara      22546   0.22
282                  tripadvisor      22380   0.22
283              hdfc securities      22023   0.21
284                         jira      21252   0.21
285                         vsco      21229   0.21
286                          edx      21060   0.20
287                    goodreads      19641   0.19
288           the indian express      19263   0.19
289                 zoho meeting      19208   0.19
290              period calendar      18979   0.18
291             dunzo driver app      18870   0.18
292               oneplus health      18847   0.18
293                         line      18594   0.18
294                    free fire      17572   0.17
295           metro ride kolkata      17538   0.17
296                     nestaway      17390   0.17
297                  officesuite      17143   0.17
298                         ebay      16844   0.16
299           dream cricket 2024      16489   0.16
300                     vision11      16228   0.16
301                  accuweather      16039   0.16
302                    photomath      15719   0.15
303                       meetup      15377   0.15
304              ignou e-content      14702   0.14
305            driveu driver app      14443   0.14
306                      vedantu      14313   0.14
307                      jiochat      14201   0.14
308                       roposo      13809   0.13
309                     abp live      13804   0.13
310                     chingari      13192   0.13
311                  mycbseguide      12141   0.12
312                     spicejet      11894   0.12
313               e-pg pathshala      11556   0.11
314                       tumblr      11498   0.11
315          fossil smartwatches      11353   0.11
316             google analytics      10828   0.11
317                    ndtv news      10755   0.10
318                       wechat      10731   0.10
319                  eenadu news      10682   0.10
320                       trello      10471   0.10
321                      okcupid      10342   0.10
322                 khan academy      10320   0.10
323               track my train       9905   0.10
324              hindustan times       9749   0.09
325                        fittr       9634   0.09
326                      todoist       8795   0.09
327                   paytm mall       8626   0.08
328                         calm       8529   0.08
329                     bbc news       8342   0.08
330               garmin connect       8174   0.08
331                   trulymadly       8166   0.08
332                  shiksha.com       7906   0.08
333        microsoft math solver       7543   0.07
334                       aakash       7200   0.07
335          the weather channel       6399   0.06
336                        asana       6364   0.06
337                 mumbai metro       6298   0.06
338                       embibe       6044   0.06
339           nike training club       5819   0.06
340            business standard       5816   0.06
341                  chegg study       5777   0.06
342                    flipboard       5545   0.05
343                        kayak       5542   0.05
344               file commander       5342   0.05
345                     eros now       4997   0.05
346                yahoo finance       4928   0.05
347                   aliexpress       4900   0.05
348                    bloomberg       4866   0.05
349              football strike       4769   0.05
350                        cisco       4596   0.04
351                  whitehat jr       4594   0.04
352                    quickride       4576   0.04
353                      expedia       4565   0.04
354                   confluence       4495   0.04
355                      quizlet       4098   0.04
356                          nba       3745   0.04
357                    foodpanda       3584   0.03
358                      lybrate       3543   0.03
359                      invideo       3337   0.03
360                     livspace       3076   0.03
361                shiksha mitra       3067   0.03
362                         miro       2953   0.03
363            paytm first games       2682   0.03
364                 colegeduniya       2563   0.02
365                youcam makeup       2397   0.02
366                     1weather       2330   0.02
367                       prisma       2283   0.02
368                          cnn       2278   0.02
369                  flightaware       2258   0.02
370            medibuddy vhealth       2228   0.02
371                    cnbc tv18       2225   0.02
372                         hike       2151   0.02
373           al jazeera english       2079   0.02
374                         espn       1992   0.02
375                     myteam11       1990   0.02
376                       feedly       1944   0.02
377                      reuters       1941   0.02
378            malayala manorama       1871   0.02
379                yahoo weather       1833   0.02
380                     vidyakul       1745   0.02
381                      triller       1536   0.01
382                      myfab11       1450   0.01
383                       pocket       1382   0.01
384               qr code reader       1281   0.01
385                   big bazaar       1216   0.01
386                         wyze       1155   0.01
387                 tunein radio       1139   0.01
388                        fiton       1128   0.01
389                rosetta stone       1118   0.01
390               skymet weather       1060   0.01

In [19]:
query_cat = f"""

SELECT 
    lower(app_name) app_name, 
    lower(category) category 
FROM 
    experiments_internal.customer_app_category_mapping
"""

df_data_cat = pd.read_sql(query_cat, connection)

In [20]:
df_data_cat.head(5)

               app_name          category
0       ignou e-content       educational
1                   aha               ott
2  grofers delivery app  delivery_grocery
3        qr code reader             tools
4               nishtha            office

In [21]:
df_merge = pd.merge(df_temp,df_data_cat,how='left', left_on='app_list_set', right_on='app_name')

In [22]:
df_merge[['category', 'app_list_set', 'customers', '%']]

                 category                 app_list_set  customers      %
0                   tools                  google maps   10307688  99.96
1                   tools                      youtube   10270401  99.60
2                   tools                        gmail   10269261  99.59
3                  social                     whatsapp   10021891  97.19
4                   tools                google photos    9724178  94.31
5                  social                    instagram    8266859  80.17
6                   tools                 google drive    7665706  74.34
7    finance_transactions                   google pay    7515895  72.89
8                  social                     facebook    7216195  69.98
9                   tools                   truecaller    6911825  67.03
10              ecommerce                     flipkart    6513104  63.16
11   finance_transactions                      phonepe    6468711  62.73
12                  tools              google calendar    6444712  62.50
13   finance_transactions                  paytm money    5990864  58.10
14   finance_transactions                  paytm money    5990864  58.10
15                    ott              disney+ hotstar    5685274  55.14
16                 social                     snapchat    5393823  52.31
17                 social                     telegram    5134587  49.80
18   finance_transactions                        paytm    4915378  47.67
19          delivery_food                       zomato    4891104  47.43
20          delivery_food                       zomato    4891104  47.43
21        streaming_music                      spotify    4890288  47.43
22                    ott                   jio cinema    4694199  45.52
23     travel_ridehailing                          ola    4645595  45.05
24                    ott                      hotstar    4613446  44.74
25                 social                     linkedin    4598234  44.59
26                    ott                      netflix    4588004  44.49
27     travel_ridehailing                         uber    4391428  42.59
28          delivery_food                       swiggy    4338038  42.07
29   finance_transactions                airtel thanks    3959077  38.40
30              ecommerce                       meesho    3783916  36.70
31                 social                    messenger    3645942  35.36
32                  tools                        clock    3514461  34.08
33              ecommerce                       myntra    3423479  33.20
34                    ott           amazon prime video    3404513  33.02
35        travel_bookings            where is my train    3264129  31.66
36                   news                  google news    3146358  30.51
37                  tools                    mx player    2846138  27.60
38                  tools                  google home    2742219  26.59
39                 office                         zoom    2399014  23.27
40                  tools                google sheets    2356882  22.86
41        streaming_music                   wynk music    2308509  22.39
42          entertainment                   bookmyshow    2281318  22.12
43              ecommerce                         ajio    2248795  21.81
44                 office                     onedrive    2235901  21.68
45       delivery_grocery                      grofers    2233444  21.66
46        travel_bookings           irctc rail connect    2169414  21.04
47                 gaming                    ludo king    2002528  19.42
48                 office                      outlook    1918997  18.61
49                 office                microsoft 365    1875169  18.19
50       delivery_grocery         grofers delivery app    1873592  18.17
51       delivery_grocery                      blinkit    1867971  18.12
52     finance_investment                     sbi yono    1811057  17.56
53                   news                    dailyhunt    1702954  16.52
54                 office              microsoft teams    1691329  16.40
55        streaming_music                     jiosaavn    1614436  15.66
56                 social                      twitter    1519209  14.73
57     finance_investment          hdfc mobile banking    1519094  14.73
58       delivery_grocery                        zepto    1499435  14.54
59   finance_transactions                         cred    1450431  14.07
60        travel_bookings                       redbus    1440638  13.97
61                  tools                google slides    1428530  13.85
62     finance_investment                        groww    1413353  13.71
63                 social                    pinterest    1378900  13.37
64                    ott                         zee5    1356928  13.16
65                    ott                         zee5    1356928  13.16
66                  tools                   adobe scan    1278458  12.40
67                 social                    sharechat    1233694  11.96
68                 gaming             candy crush saga    1226156  11.89
69       delivery_grocery                    bigbasket    1223358  11.86
70                    ott                        jiotv    1208737  11.72
71                    ott                      sonyliv    1180661  11.45
72          delivery_food               domino's pizza    1171361  11.36
73   finance_transactions                  axis mobile    1124481  10.91
74        travel_bookings                   makemytrip    1049373  10.18
75        travel_bookings                        ixigo    1025695   9.95
76                  tools                      picsart     995869   9.66
77              ecommerce                       shopsy     993334   9.63
78   finance_transactions                  imobile pay     991831   9.62
79              ecommerce                      jiomart     933557   9.05
80                 office             ms authenticator     924572   8.97
81                 gaming                  pubg mobile     911351   8.84
82                 gaming                  pubg mobile     911351   8.84
83     travel_ridehailing                          uts     906833   8.79
84               wearable      samsung galaxy wearable     891363   8.64
85                 gaming                free fire max     873453   8.47
86                  tools              microsoft excel     837669   8.12
87           home_service                urban company     834356   8.09
88                  tools                  smartthings     832891   8.08
89     travel_ridehailing                     in drive     767960   7.45
90              ecommerce                        nykaa     756695   7.34
91              ecommerce                        nykaa     756695   7.34
92             driver_app               rapido captain     707078   6.86
93         fantasy_sports                     cricbuzz     659997   6.40
94   finance_transactions                     mobikwik     654338   6.35
95           home_service                     nobroker     620621   6.02
96                    ott                          aha     611124   5.93
97        streaming_music                 amazon music     587337   5.70
98     finance_investment                angel broking     584837   5.67
99     finance_investment                angel broking     584837   5.67
100       travel_bookings                   mparivahan     584312   5.67
101        fantasy_sports                      dream11     581130   5.64
102        fantasy_sports                      dream11     581130   5.64
103                 tools                     snapseed     569723   5.53
104    finance_investment                 zerodha kite     556415   5.40
105                social                          moj     553169   5.36
106             ecommerce                    pocket fm     551498   5.35
107                   NaN        intune company portal     549832   5.33
108       travel_bookings                      goibibo     546686   5.30
109             ecommerce                     firstcry     486128   4.71
110             ecommerce                     lenskart     484420   4.70
111           educational             google classroom     476477   4.62
112                office         google authenticator     463273   4.49
113       travel_bookings                      abhibus     459272   4.45
114                 tools              adobe lightroom     446045   4.33
115       travel_bookings                          oyo     429726   4.17
116  finance_transactions                     bhim upi     424185   4.11
117    travel_ridehailing                  namma yatri     418986   4.06
118       travel_bookings                  booking.com     417389   4.05
119             ecommerce                      purplle     412566   4.00
120                   NaN                   apollo 247     405481   3.93
121         delivery_food                        dunzo     400622   3.89
122        fantasy_sports                   my11circle     394603   3.83
123                social                   mx takatak     383939   3.72
124                 tools                    splitwise     383898   3.72
125            driver_app              uber driver app     377843   3.66
126           educational                     duolingo     363649   3.53
127       streaming_music                        gaana     357282   3.46
128                 tools                      ms edge     342960   3.33
129           educational                        udemy     331685   3.22
130            driver_app               ola driver app     324294   3.15
131                 tools                 amazon alexa     320327   3.11
132                gaming                  8 ball pool     318068   3.08
133             ecommerce                          1mg     313165   3.04
134             ecommerce                    tata cliq     293311   2.84
135                social                         josh     291817   2.83
136                social                         josh     291817   2.83
137                gaming               subway surfers     287968   2.79
138                  news                     inshorts     281288   2.73
139             ecommerce                    pharmeasy     277559   2.69
140                office                        webex     276380   2.68
141    finance_investment                       upstox     275505   2.67
142                social                        skype     272138   2.64
143                gaming                  carrom pool     265330   2.57
144          news_finance                 moneycontrol     260428   2.53
145          finance_news                 moneycontrol     260428   2.53
146                   ott                      sun nxt     254732   2.47
147           educational                      brainly     245560   2.38
148                gaming               clash of clans     241064   2.34
149         delivery_food                    kfc india     240612   2.33
150       travel_bookings                       indigo     227190   2.20
151           educational               physics wallah     217965   2.11
152                   ott                         voot     214473   2.08
153                   ott                         voot     214473   2.08
154           educational                       reddit     208753   2.02
155          home_service                      99acres     208367   2.02
156           educational                         byju     204020   1.98
157          home_service                  magicbricks     199933   1.94
158           educational                    unacademy     194647   1.89
159    finance_investment                          nps     191187   1.85
160            driver_app            swiggy driver app     190918   1.85
161                health                  healthifyme     190746   1.85
162          travel_metro                dmrc momentum     188676   1.83
163             insurance                 policybazaar     187395   1.82
164       travel_bookings                       airbnb     184549   1.79
165                dating                       tinder     170702   1.66
166       travel_bookings                   skyscanner     169699   1.65
167                office                        slack     166170   1.61
168                office                        slack     166170   1.61
169             ecommerce                          h&m     165771   1.61
170            devotional               ttdevasthanams     165657   1.61
171                   NaN                     cult.fit     160865   1.56
172                dating                       bumble     154026   1.49
173                social                     moj lite     151142   1.47
174       travel_bookings                    cleartrip     148057   1.44
175                 tools               microsoft lens     145965   1.42
176         delivery_food                fresh to home     144165   1.40
177    travel_ridehailing                     blusmart     140961   1.37
178             insurance               acko insurance     140813   1.37
179          travel_metro        delhi metro navigator     138220   1.34
180    finance_investment              kite by zerodha     135113   1.31
181                health                       practo     134563   1.30
182                gaming         call of duty: mobile     127895   1.24
183                health                       fitbit     125451   1.22
184           educational                     coursera     124690   1.21
185           educational                     coursera     124690   1.21
186                   ott                amazon minitv     124602   1.21
187    travel_ridehailing                         yulu     119568   1.16
188                office       intune  company portal     119121   1.16
189                health  home workout - no equipment     118180   1.15
190             ecommerce                       zivame     117958   1.14
191                gaming               cricket league     117214   1.14
192             ecommerce                    lifestyle     116837   1.13
193               telecom                bsnl selfcare     116414   1.13
194            driver_app            porter driver app     116365   1.13
195             ecommerce                     limeroad     116339   1.13
196             ecommerce             the souled store     114550   1.11
197          travel_metro                  namma metro     114149   1.11
198        fantasy_sports                      fancode     114078   1.11
199                social                    starmaker     113228   1.10
200         delivery_food              pizza hut india     112703   1.09
201       travel_bookings                   easemytrip     110417   1.07
202                 tools            microsoft onenote     106285   1.03
203  finance_transactions                   freecharge     105884   1.03
204        fantasy_sports                 rummy circle     102398   0.99
205                gaming                     among us     100783   0.98
206             ecommerce                      netmeds      99959   0.97
207                social                  google chat      99741   0.97
208                health                 medplus mart      99666   0.97
209            driver_app            zomato driver app      98777   0.96
210                health                          flo      95550   0.93
211       streaming_music                hungama music      94690   0.92
212           educational                       swayam      92727   0.90
213                social                       signal      92340   0.90
214                 tools               youcam perfect      90062   0.87
215       travel_bookings                        yatra      86301   0.84
216          finance_news               economic times      85099   0.83
217                gaming            hill climb racing      85016   0.82
218       travel_bookings                flightradar24      83589   0.81
219                 tools                   calculator      79903   0.77
220  finance_transactions                         ring      79399   0.77
221         delivery_food             mcdonald's india      75856   0.74
222                office                      dropbox      74188   0.72
223    travel_ridehailing                       tummoc      73889   0.72
224    travel_ridehailing                   quick ride      73397   0.71
225             ecommerce                    nykaa man      73268   0.71
226                gaming                 temple run 2      71553   0.69
227           educational            linkedin learning      70303   0.68
228             ecommerce                         zara      67911   0.66
229    finance_investment                     et money      64846   0.63
230                 tools                       notion      63827   0.62
231              wearable               zepp (amazfit)      63112   0.61
232                  news                       aajtak      62609   0.61
233    finance_investment          icicidirect: stocks      62503   0.61
234                   ott                   alt balaji      62406   0.61
235           educational                     doubtnut      61715   0.60
236                   ott                    altbalaji      60690   0.59
237                dating                        hinge      60610   0.59
238    finance_investment                    kotak neo      59547   0.58
239             ecommerce                    pepperfry      58746   0.57
240                health                       strava      57407   0.56
241              wearable                       mi fit      57121   0.55
242                   NaN           chennai metro rail      56442   0.55
243       streaming_music                   soundcloud      56263   0.55
244       travel_bookings         train ticket booking      55664   0.54
245                office                       github      55497   0.54
246             ecommerce                     westside      53028   0.51
247           educational                       diksha      51141   0.50
248                gaming                 mini militia      51060   0.50
249                dating                        happn      50817   0.49
250            driver_app             zepto driver app      49747   0.48
251          travel_metro                    t savaari      47851   0.46
252         delivery_food              starbucks india      47747   0.46
253            devotional                     sadhguru      47675   0.46
254    travel_ridehailing                       driveu      47228   0.46
255                 tools              weather & radar      46710   0.45
256                gaming           asphalt 9: legends      46330   0.45
257    travel_ridehailing                       jugnoo      44360   0.43
258            driver_app         shadowfax driver app      44286   0.43
259              wearable                huawei health      41034   0.40
260                office                    zoho mail      40289   0.39
261       travel_bookings                      trivago      39562   0.38
262                health                 myfitnesspal      39314   0.38
263             ecommerce              amazon shopping      39199   0.38
264          finance_news                         mint      37876   0.37
265               telecom                  my bsnl app      37687   0.37
266    finance_investment      icicidirect markets app      37265   0.36
267           educational                  simplilearn      35941   0.35
268    finance_investment                    sharekhan      34951   0.34
269    finance_investment                namma partner      34233   0.33
270                dating                        aisle      33807   0.33
271       travel_bookings                         wego      32326   0.31

In [23]:
df_temp.to_clipboard(index=False)