In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [33]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [3]:
start_date = '20241001'
end_date = '20241031'
retention_start_date = '20241101'
retention_end_date = '20241231'

In [4]:
query_data = f'''

    WITH customer_base AS (
    
    SELECT 
        distinct
        -- yyyymmdd,
        city_name,
        -- service_obj_service_name,
        customer_id
        -- order_id
    FROM 
        orders.order_logs_fact
    WHERE 
        yyyymmdd >= '{start_date}' 
        AND yyyymmdd <= '{end_date}'
        AND city_name IN ('Bangalore', 'Chennai', 'Hyderabad')
        AND order_status = 'dropped'
        AND service_obj_service_name in ('Auto','Auto Pool','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
    ),
    
    
    unlocked AS (

    SELECT 
        distinct
        -- kpsi.yyyymmdd,
        kpsi.userid as user_id,
        kpsi.rewards__transactionid as rewards_transaction_id
    FROM 
        hive.canonical.iceberg_domain_pricing_scratchcards_immutable kpsi
    WHERE 
        yyyymmdd >= '{start_date}' 
        AND yyyymmdd <= '{end_date}'
        AND rewards__type = 'EXTERNAL_REWARD'
        AND rewards__state = 'UNLOCKED'
    ),
    
    scratched AS (

    SELECT 
        distinct
        -- kpsi.yyyymmdd,
        date_format(date_parse(kpsi.yyyymmdd, '%Y%m%d')  + interval '7' day, '%Y%m%d') scratch_window,
        kpsi.userid as user_id,
        kpsi.rewards__transactionid as rewards_transaction_id
    FROM 
        hive.canonical.iceberg_domain_pricing_scratchcards_immutable kpsi
    WHERE 
        yyyymmdd >= '{start_date}' 
        AND yyyymmdd <= '{end_date}'
        AND rewards__type = 'EXTERNAL_REWARD'
        AND rewards__state = 'SCRATCHED'
    ),
    
    redeemed AS (
    
    SELECT 
        distinct
        event_props_user_id redeem_user_id
    FROM 
        clevertap.customer_rewards_immutable 
    WHERE 
       yyyymmdd >= '{start_date}' 
        AND yyyymmdd <= '{end_date}'
        AND event_props_action NOT IN ('ctaClicked', 'copyCodeClicked')
    
    ),
    
    merge AS (
    
    SELECT 
        customer_base.*,
        unlocked.rewards_transaction_id unlocked,
        scratched.rewards_transaction_id scratched,
        redeem_user_id
    FROM 
        customer_base
    LEFT JOIN 
        unlocked
        -- ON customer_base.yyyymmdd = unlocked.yyyymmdd
        ON customer_base.customer_id = unlocked.user_id
        -- AND customer_base.order_id = unlocked.rewards_transaction_id
    LEFT JOIN 
        scratched
        -- ON unlocked.yyyymmdd <= scratched.scratch_window
        ON unlocked.user_id = scratched.user_id
        -- AND unlocked.rewards_transaction_id = scratched.rewards_transaction_id
    LEFT JOIN 
        redeemed
        ON scratched.user_id = redeemed.redeem_user_id
    ),
    
    view AS (
    
    SELECT
        city_name,
        CASE 
        WHEN unlocked = 0 THEN 'Deals Not Issued'
        WHEN unlocked > 0 THEN 'Deals issused'
        -- WHEN unlocked > 0 AND scratched = 0 THEN 'Deals issused'
        -- WHEN unlocked > 0 AND scratched > 0 THEN 'GROUP-B'
        ELSE 'Check'
        END isIssued,
        CASE 
        WHEN unlocked = 0 THEN 'Deals Not Issued'
        WHEN unlocked > 0 AND scratched = 0 THEN 'Deals issused, not scratched'
        WHEN unlocked > 0 AND scratched > 0 THEN 'Deals issused, scratched'
        ELSE 'Check'
        END isScratched,
        CASE 
        WHEN unlocked = 0 THEN 'Deals Not Issued'
        WHEN unlocked > 0 AND scratched = 0 THEN 'Deals issused, not scratched'
        WHEN unlocked > 0 AND scratched > 0 AND redeemed = 0  THEN 'Deals issused, scratched not redeemed'
        WHEN unlocked > 0 AND scratched > 0 AND redeemed > 0  THEN 'Deals issused, redeemed'
        ELSE 'Check'
        END isredeemed,
        customer_id,
        unlocked,
        scratched,
        redeemed
    FROM
        (
        SELECT 
            city_name,
            customer_id,
            count(distinct unlocked) unlocked,
            count(distinct scratched) scratched,
            COUNT(distinct redeem_user_id) redeemed
        FROM 
            merge
        GROUP BY 1,2
        )
    ),
    
    customer_retention AS (
    
    SELECT 
        customer_id,
        MAX(CASE WHEN DATE_FORMAT(DATE_TRUNC('MONTH', DATE_PARSE(yyyymmdd, '%Y%m%d')), '%Y%m%d') = '20241101' THEN 1 ELSE 0 END) nov_retention,
        MAX(CASE WHEN DATE_FORMAT(DATE_TRUNC('MONTH', DATE_PARSE(yyyymmdd, '%Y%m%d')), '%Y%m%d') = '20241201' THEN 1 ELSE 0 END) dec_retention
    FROM 
        orders.order_logs_fact
    WHERE 
        yyyymmdd >= '{retention_start_date}' 
        AND yyyymmdd <= '{retention_end_date}'
        AND city_name IN ('Bangalore', 'Chennai', 'Hyderabad')
        AND order_status = 'dropped'
        AND service_obj_service_name in ('Auto','Auto Pool','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
    GROUP BY 1
    ),
    
    segment AS (
    
    SELECT  
        customer_id,
        taxi_ltr_segment,
        taxi_retention_segments,
        taxi_regularity_segment,
        taxi_fe_regularity_segment,
        taxi_recency_segment
    FROM 
        datasets.iallocator_customer_segments
    WHERE
        run_date =  '2024-10-31' 
        AND taxi_recency_segment != 'INACTIVE'
    )
    
    SELECT 
        view.*,
        coalesce(nov_retention, 0) nov_retention,
        coalesce(dec_retention, 0) dec_retention,
        taxi_ltr_segment,
        taxi_retention_segments,
        taxi_regularity_segment,
        taxi_fe_regularity_segment,
        taxi_recency_segment
    FROM 
        view
    LEFT JOIN 
        customer_retention
        ON view.customer_id = customer_retention.customer_id
    LEFT JOIN 
        segment
        ON view.customer_id = segment.customer_id
'''

df = pd.read_sql(query_data, connection)

In [5]:
df.head(5)

,city_name,isIssued,isScratched,isredeemed,customer_id,unlocked,scratched,redeemed,nov_retention,dec_retention,taxi_ltr_segment,taxi_retention_segments,taxi_regularity_segment,taxi_fe_regularity_segment,taxi_recency_segment
0,Hyderabad,Deals issused,"Deals issused, not scratched","Deals issused, not scratched",6718ee679f872a0216b733ff,1,0,0,0,0,HH,HH,UNKNOWN,MONTHLY,STATIONARY
1,Hyderabad,Deals issused,"Deals issused, not scratched","Deals issused, not scratched",603fa2dc44b59ebb30d89308,1,0,0,1,1,PHH,PLATINUM,WEEKLY,WEEKLY,STATIONARY
2,Hyderabad,Deals Not Issued,Deals Not Issued,Deals Not Issued,5ded507d1a882e3354b957a8,0,0,0,0,0,PHH,DORMANT,BI_WEEKLY,MONTHLY,DORMANT
3,Hyderabad,Deals Not Issued,Deals Not Issued,Deals Not Issued,62033923725c4c4025b05f33,0,0,0,1,1,PHH,GOLD,WEEKLY,BI_WEEKLY,STATIONARY
4,Hyderabad,Deals issused,"Deals issused, not scratched","Deals issused, not scratched",5c2b81f04a267149c762c9a0,1,0,0,0,0,PHH,GOLD,BI_WEEKLY,BI_WEEKLY,STATIONARY

In [6]:
df.to_parquet('/Users/E2074/local-datasets/customer/ads-monetisation/deals-impact/data.parquet', index=False)

### Analysis

In [7]:
df_analysis1 = df\
                .groupby(['city_name'])\
                .agg(
                    customers = ('customer_id', 'nunique'),
                    nov_retention = ('customer_id', lambda x: x[df['nov_retention'] == 1].nunique()),
                    dec_retention = ('customer_id', lambda x: x[df['dec_retention'] == 1].nunique())
                    )\
                .reset_index()

df_analysis1['nov retention %'] = round(df_analysis1['nov_retention']*100.00/df_analysis1['customers'])
df_analysis1['dec retention %'] = round(df_analysis1['dec_retention']*100.00/df_analysis1['customers'])
df_analysis1

,city_name,customers,nov_retention,dec_retention,nov retention %,dec retention %
0,Bangalore,2637619,1665721,1611666,63.0,61.0
1,Chennai,1787845,1130271,1079362,63.0,60.0
2,Hyderabad,3478486,2211408,2159751,64.0,62.0

In [26]:
df_analysis2 = df\
                .groupby(['city_name','isIssued'])\
                .agg(
                    customers = ('customer_id', 'nunique'),
                    nov_retention = ('customer_id', lambda x: x[df['nov_retention'] == 1].nunique()),
                    dec_retention = ('customer_id', lambda x: x[df['dec_retention'] == 1].nunique())
                    )\
                .reset_index()

df_analysis2['customers distr %'] = round(df_analysis2['customers']*100.00/df_analysis2.groupby(['city_name'])['customers'].transform('sum'), 2)
df_analysis2['nov retention %'] = round(df_analysis2['nov_retention']*100.00/df_analysis2['customers'])
df_analysis2['dec retention %'] = round(df_analysis2['dec_retention']*100.00/df_analysis2['customers'])
df_analysis2

,city_name,isIssued,customers,nov_retention,dec_retention,customers distr %,nov retention %,dec retention %
0,Bangalore,Deals Not Issued,522616,254753,251422,19.81,49.0,48.0
1,Bangalore,Deals issused,2115003,1410968,1360244,80.19,67.0,64.0
2,Chennai,Deals Not Issued,371316,175810,173183,20.77,47.0,47.0
3,Chennai,Deals issused,1416529,954461,906179,79.23,67.0,64.0
4,Hyderabad,Deals Not Issued,1414226,740871,745877,40.66,52.0,53.0
5,Hyderabad,Deals issused,2064260,1470537,1413874,59.34,71.0,68.0

In [37]:
df_analysis2v1 = df\
                .groupby(['city_name', 'taxi_retention_segments', 'isIssued'])\
                .agg(
                    customers = ('customer_id', 'nunique'),
                    nov_retention = ('customer_id', lambda x: x[df['nov_retention'] == 1].nunique()),
                    dec_retention = ('customer_id', lambda x: x[df['dec_retention'] == 1].nunique())
                    )\
                .reset_index()

df_analysis2v1['customers distr %'] = round(df_analysis2v1['customers']*100.00/df_analysis2v1.groupby(['city_name', 'isIssued'])['customers'].transform('sum'), 2)
df_analysis2v1['nov retention %'] = round(df_analysis2v1['nov_retention']*100.00/df_analysis2v1['customers'])
df_analysis2v1['dec retention %'] = round(df_analysis2v1['dec_retention']*100.00/df_analysis2v1['customers'])
df_analysis2v1

,city_name,taxi_retention_segments,isIssued,customers,nov_retention,dec_retention,customers distr %,nov retention %,dec retention %
0,Bangalore,DORMANT,Deals Not Issued,311821,131807,135329,59.71,42.0,43.0
1,Bangalore,DORMANT,Deals issused,108219,50747,51545,5.12,47.0,48.0
2,Bangalore,ELITE,Deals Not Issued,4202,3614,3477,0.80,86.0,83.0
3,Bangalore,ELITE,Deals issused,293510,271971,263684,13.88,93.0,90.0
4,Bangalore,GOLD,Deals Not Issued,56304,39359,37501,10.78,70.0,67.0
5,Bangalore,GOLD,Deals issused,533408,372220,356720,25.23,70.0,67.0
6,Bangalore,HH,Deals Not Issued,37389,14343,12654,7.16,38.0,34.0
7,Bangalore,HH,Deals issused,299326,114409,103778,14.16,38.0,35.0
8,Bangalore,PLATINUM,Deals Not Issued,22824,18621,17737,4.37,82.0,78.0
9,Bangalore,PLATINUM,Deals issused,465606,392405,378114,22.02,84.0,81.0
10,Bangalore,PRIME,Deals Not Issued,118,98,81,0.02,83.0,69.0
11,Bangalore,PRIME,Deals issused,7390,6527,6185,0.35,88.0,84.0
12,Bangalore,SILVER,Deals Not Issued,89516,46801,44517,17.14,52.0,50.0
13,Bangalore,SILVER,Deals issused,406816,202480,200003,19.24,50.0,49.0
14,Bangalore,UNKNOWN,Deals Not Issued,77,12,15,0.01,16.0,19.0
15,Bangalore,UNKNOWN,Deals issused,177,46,45,0.01,26.0,25.0
16,Chennai,DORMANT,Deals Not Issued,239415,100250,102049,64.54,42.0,43.0
17,Chennai,DORMANT,Deals issused,79990,37757,37605,5.65,47.0,47.0
18,Chennai,ELITE,Deals Not Issued,3026,2685,2591,0.82,89.0,86.0
19,Chennai,ELITE,Deals issused,196550,185386,178565,13.88,94.0,91.0
20,Chennai,GOLD,Deals Not Issued,34660,23932,22786,9.34,69.0,66.0
21,Chennai,GOLD,Deals issused,364297,253975,239687,25.73,70.0,66.0
22,Chennai,HH,Deals Not Issued,22020,7690,6835,5.94,35.0,31.0
23,Chennai,HH,Deals issused,186116,67708,59741,13.14,36.0,32.0
24,Chennai,PLATINUM,Deals Not Issued,15263,12503,11951,4.11,82.0,78.0
25,Chennai,PLATINUM,Deals issused,321525,275222,261540,22.71,86.0,81.0
26,Chennai,PRIME,Deals Not Issued,64,53,49,0.02,83.0,77.0
27,Chennai,PRIME,Deals issused,5414,4890,4559,0.38,90.0,84.0
28,Chennai,SILVER,Deals Not Issued,56452,28589,26815,15.22,51.0,48.0
29,Chennai,SILVER,Deals issused,261984,129350,124321,18.50,49.0,47.0
30,Chennai,UNKNOWN,Deals Not Issued,47,13,15,0.01,28.0,32.0
31,Chennai,UNKNOWN,Deals issused,109,29,23,0.01,27.0,21.0
32,Hyderabad,DORMANT,Deals Not Issued,574183,256829,267100,40.64,45.0,47.0
33,Hyderabad,DORMANT,Deals issused,18818,10491,10827,0.91,56.0,58.0
34,Hyderabad,ELITE,Deals Not Issued,21378,18197,17845,1.51,85.0,83.0
35,Hyderabad,ELITE,Deals issused,311669,292153,282811,15.10,94.0,91.0
36,Hyderabad,GOLD,Deals Not Issued,246854,168945,166708,17.47,68.0,68.0
37,Hyderabad,GOLD,Deals issused,566214,404431,388208,27.44,71.0,69.0
38,Hyderabad,HH,Deals Not Issued,129684,40924,39478,9.18,32.0,30.0
39,Hyderabad,HH,Deals issused,225992,88595,79269,10.95,39.0,35.0
40,Hyderabad,PLATINUM,Deals Not Issued,117413,95760,93747,8.31,82.0,80.0
41,Hyderabad,PLATINUM,Deals issused,533493,458374,440591,25.85,86.0,83.0
42,Hyderabad,PRIME,Deals Not Issued,635,480,467,0.04,76.0,74.0
43,Hyderabad,PRIME,Deals issused,10094,9131,8609,0.49,90.0,85.0
44,Hyderabad,SILVER,Deals Not Issued,322353,159261,160036,22.82,49.0,50.0
45,Hyderabad,SILVER,Deals issused,397200,207119,203335,19.25,52.0,51.0
46,Hyderabad,UNKNOWN,Deals Not Issued,231,59,49,0.02,26.0,21.0
47,Hyderabad,UNKNOWN,Deals issused,124,33,23,0.01,27.0,19.0

In [36]:
df_analysis2v2 = df\
                .groupby(['city_name', 'taxi_regularity_segment', 'isIssued'])\
                .agg(
                    customers = ('customer_id', 'nunique'),
                    nov_retention = ('customer_id', lambda x: x[df['nov_retention'] == 1].nunique()),
                    dec_retention = ('customer_id', lambda x: x[df['dec_retention'] == 1].nunique())
                    )\
                .reset_index()

df_analysis2v2['customers distr %'] = round(df_analysis2v2['customers']*100.00/df_analysis2v2.groupby(['city_name', 'isIssued'])['customers'].transform('sum'), 2)
df_analysis2v2['nov retention %'] = round(df_analysis2v2['nov_retention']*100.00/df_analysis2v2['customers'])
df_analysis2v2['dec retention %'] = round(df_analysis2v2['dec_retention']*100.00/df_analysis2v2['customers'])
df_analysis2v2

,city_name,taxi_regularity_segment,isIssued,customers,nov_retention,dec_retention,customers distr %,nov retention %,dec retention %
0,Bangalore,BI_WEEKLY,Deals Not Issued,145201,86330,85656,27.80,59.0,59.0
1,Bangalore,BI_WEEKLY,Deals issused,535336,354440,341884,25.32,66.0,64.0
2,Bangalore,DAILY,Deals Not Issued,8536,5907,5949,1.63,69.0,70.0
3,Bangalore,DAILY,Deals issused,230999,213212,206755,10.92,92.0,90.0
4,Bangalore,MONTHLY,Deals Not Issued,117422,54125,53985,22.48,46.0,46.0
5,Bangalore,MONTHLY,Deals issused,259900,130061,127154,12.29,50.0,49.0
6,Bangalore,RARE_NEED,Deals Not Issued,68368,26863,26362,13.09,39.0,39.0
7,Bangalore,RARE_NEED,Deals issused,152041,76647,74307,7.19,50.0,49.0
8,Bangalore,UNKNOWN,Deals Not Issued,119619,34550,33024,22.90,29.0,28.0
9,Bangalore,UNKNOWN,Deals issused,324999,121332,110679,15.37,37.0,34.0
10,Bangalore,WEEKLY,Deals Not Issued,63105,46880,46335,12.08,74.0,73.0
11,Bangalore,WEEKLY,Deals issused,611177,515113,499295,28.90,84.0,82.0
12,Chennai,BI_WEEKLY,Deals Not Issued,99700,60565,59437,26.88,61.0,60.0
13,Chennai,BI_WEEKLY,Deals issused,378313,255994,243017,26.72,68.0,64.0
14,Chennai,DAILY,Deals Not Issued,3981,2769,2683,1.07,70.0,67.0
15,Chennai,DAILY,Deals issused,125306,118195,113551,8.85,94.0,91.0
16,Chennai,MONTHLY,Deals Not Issued,91523,42186,42361,24.67,46.0,46.0
17,Chennai,MONTHLY,Deals issused,188561,96010,91975,13.32,51.0,49.0
18,Chennai,RARE_NEED,Deals Not Issued,55277,20986,20856,14.90,38.0,38.0
19,Chennai,RARE_NEED,Deals issused,105825,53034,50582,7.47,50.0,48.0
20,Chennai,UNKNOWN,Deals Not Issued,85419,22472,21695,23.03,26.0,25.0
21,Chennai,UNKNOWN,Deals issused,204540,72595,64451,14.45,35.0,32.0
22,Chennai,WEEKLY,Deals Not Issued,35047,26737,26059,9.45,76.0,74.0
23,Chennai,WEEKLY,Deals issused,413440,358489,342465,29.20,87.0,83.0
24,Hyderabad,BI_WEEKLY,Deals Not Issued,417475,264817,265389,29.55,63.0,64.0
25,Hyderabad,BI_WEEKLY,Deals issused,556051,387491,373181,26.95,70.0,67.0
26,Hyderabad,DAILY,Deals Not Issued,17725,13170,13078,1.25,74.0,74.0
27,Hyderabad,DAILY,Deals issused,200476,188293,181694,9.71,94.0,91.0
28,Hyderabad,MONTHLY,Deals Not Issued,342827,164679,169301,24.27,48.0,49.0
29,Hyderabad,MONTHLY,Deals issused,261077,140072,136471,12.65,54.0,52.0
30,Hyderabad,RARE_NEED,Deals Not Issued,192274,77449,79461,13.61,40.0,41.0
31,Hyderabad,RARE_NEED,Deals issused,147062,80050,76438,7.13,54.0,52.0
32,Hyderabad,UNKNOWN,Deals Not Issued,256208,71683,71728,18.14,28.0,28.0
33,Hyderabad,UNKNOWN,Deals issused,227319,89021,79663,11.02,39.0,35.0
34,Hyderabad,WEEKLY,Deals Not Issued,186222,148657,146473,13.18,80.0,79.0
35,Hyderabad,WEEKLY,Deals issused,671619,585400,566226,32.55,87.0,84.0

In [30]:
df_analysis3 = df\
                .groupby(['city_name','isScratched'])\
                .agg(
                    customers = ('customer_id', 'nunique'),
                    nov_retention = ('customer_id', lambda x: x[df['nov_retention'] == 1].nunique()),
                    dec_retention = ('customer_id', lambda x: x[df['dec_retention'] == 1].nunique())
                    )\
                .reset_index()

df_analysis3['customers distr %'] = round(df_analysis3['customers']*100.00/df_analysis3.groupby(['city_name'])['customers'].transform('sum'), 2)
df_analysis3['nov retention %'] = round(df_analysis3['nov_retention']*100.00/df_analysis3['customers'])
df_analysis3['dec retention %'] = round(df_analysis3['dec_retention']*100.00/df_analysis3['customers'])
df_analysis3

,city_name,isScratched,customers,nov_retention,dec_retention,customers distr %,nov retention %,dec retention %
0,Bangalore,Deals Not Issued,522616,254753,251422,19.81,49.0,48.0
1,Bangalore,"Deals issused, not scratched",1990881,1313174,1265517,75.48,66.0,64.0
2,Bangalore,"Deals issused, scratched",124122,97794,94727,4.71,79.0,76.0
3,Chennai,Deals Not Issued,371316,175810,173183,20.77,47.0,47.0
4,Chennai,"Deals issused, not scratched",1355884,905253,859528,75.84,67.0,63.0
5,Chennai,"Deals issused, scratched",60645,49208,46651,3.39,81.0,77.0
6,Hyderabad,Deals Not Issued,1414226,740871,745877,40.66,52.0,53.0
7,Hyderabad,"Deals issused, not scratched",1988710,1409475,1355358,57.17,71.0,68.0
8,Hyderabad,"Deals issused, scratched",75550,61062,58516,2.17,81.0,77.0

In [35]:
df_analysis3v1 = df\
                .groupby(['city_name', 'taxi_retention_segments', 'isScratched'])\
                .agg(
                    customers = ('customer_id', 'nunique'),
                    nov_retention = ('customer_id', lambda x: x[df['nov_retention'] == 1].nunique()),
                    dec_retention = ('customer_id', lambda x: x[df['dec_retention'] == 1].nunique())
                    )\
                .reset_index()

df_analysis3v1['customers distr %'] = round(df_analysis3v1['customers']*100.00/df_analysis3v1.groupby(['city_name', 'isScratched'])['customers'].transform('sum'), 2)
df_analysis3v1['nov retention %'] = round(df_analysis3v1['nov_retention']*100.00/df_analysis3v1['customers'])
df_analysis3v1['dec retention %'] = round(df_analysis3v1['dec_retention']*100.00/df_analysis3v1['customers'])
df_analysis3v1

,city_name,taxi_retention_segments,isScratched,customers,nov_retention,dec_retention,customers distr %,nov retention %,dec retention %
0,Bangalore,DORMANT,Deals Not Issued,311821,131807,135329,59.71,42.0,43.0
1,Bangalore,DORMANT,"Deals issused, not scratched",104968,49038,49792,5.27,47.0,47.0
2,Bangalore,DORMANT,"Deals issused, scratched",3251,1709,1753,2.62,53.0,54.0
3,Bangalore,ELITE,Deals Not Issued,4202,3614,3477,0.80,86.0,83.0
4,Bangalore,ELITE,"Deals issused, not scratched",254875,235696,228423,12.81,92.0,90.0
5,Bangalore,ELITE,"Deals issused, scratched",38635,36275,35261,31.13,94.0,91.0
6,Bangalore,GOLD,Deals Not Issued,56304,39359,37501,10.78,70.0,67.0
7,Bangalore,GOLD,"Deals issused, not scratched",507486,353911,339027,25.50,70.0,67.0
8,Bangalore,GOLD,"Deals issused, scratched",25922,18309,17693,20.89,71.0,68.0
9,Bangalore,HH,Deals Not Issued,37389,14343,12654,7.16,38.0,34.0
10,Bangalore,HH,"Deals issused, not scratched",293981,112416,101948,14.77,38.0,35.0
11,Bangalore,HH,"Deals issused, scratched",5345,1993,1830,4.31,37.0,34.0
12,Bangalore,PLATINUM,Deals Not Issued,22824,18621,17737,4.37,82.0,78.0
13,Bangalore,PLATINUM,"Deals issused, not scratched",429319,361381,348288,21.57,84.0,81.0
14,Bangalore,PLATINUM,"Deals issused, scratched",36287,31024,29826,29.24,85.0,82.0
15,Bangalore,PRIME,Deals Not Issued,118,98,81,0.02,83.0,69.0
16,Bangalore,PRIME,"Deals issused, not scratched",5101,4423,4180,0.26,87.0,82.0
17,Bangalore,PRIME,"Deals issused, scratched",2289,2104,2005,1.84,92.0,88.0
18,Bangalore,SILVER,Deals Not Issued,89516,46801,44517,17.14,52.0,50.0
19,Bangalore,SILVER,"Deals issused, not scratched",394430,196102,193647,19.82,50.0,49.0
20,Bangalore,SILVER,"Deals issused, scratched",12386,6378,6356,9.98,51.0,51.0
21,Bangalore,UNKNOWN,Deals Not Issued,77,12,15,0.01,16.0,19.0
22,Bangalore,UNKNOWN,"Deals issused, not scratched",175,45,44,0.01,26.0,25.0
23,Bangalore,UNKNOWN,"Deals issused, scratched",2,1,1,0.00,50.0,50.0
24,Chennai,DORMANT,Deals Not Issued,239415,100250,102049,64.54,42.0,43.0
25,Chennai,DORMANT,"Deals issused, not scratched",78386,36908,36786,5.78,47.0,47.0
26,Chennai,DORMANT,"Deals issused, scratched",1604,849,819,2.65,53.0,51.0
27,Chennai,ELITE,Deals Not Issued,3026,2685,2591,0.82,89.0,86.0
28,Chennai,ELITE,"Deals issused, not scratched",176695,166368,160338,13.04,94.0,91.0
29,Chennai,ELITE,"Deals issused, scratched",19855,19018,18227,32.74,96.0,92.0
30,Chennai,GOLD,Deals Not Issued,34660,23932,22786,9.34,69.0,66.0
31,Chennai,GOLD,"Deals issused, not scratched",352192,245420,231636,25.99,70.0,66.0
32,Chennai,GOLD,"Deals issused, scratched",12105,8555,8051,19.96,71.0,67.0
33,Chennai,HH,Deals Not Issued,22020,7690,6835,5.94,35.0,31.0
34,Chennai,HH,"Deals issused, not scratched",183892,66918,59056,13.57,36.0,32.0
35,Chennai,HH,"Deals issused, scratched",2224,790,685,3.67,36.0,31.0
36,Chennai,PLATINUM,Deals Not Issued,15263,12503,11951,4.11,82.0,78.0
37,Chennai,PLATINUM,"Deals issused, not scratched",303582,259502,246704,22.40,85.0,81.0
38,Chennai,PLATINUM,"Deals issused, scratched",17943,15720,14836,29.59,88.0,83.0
39,Chennai,PRIME,Deals Not Issued,64,53,49,0.02,83.0,77.0
40,Chennai,PRIME,"Deals issused, not scratched",3823,3391,3155,0.28,89.0,83.0
41,Chennai,PRIME,"Deals issused, scratched",1591,1499,1404,2.62,94.0,88.0
42,Chennai,SILVER,Deals Not Issued,56452,28589,26815,15.22,51.0,48.0
43,Chennai,SILVER,"Deals issused, not scratched",256665,126576,121693,18.94,49.0,47.0
44,Chennai,SILVER,"Deals issused, scratched",5319,2774,2628,8.77,52.0,49.0
45,Chennai,UNKNOWN,Deals Not Issued,47,13,15,0.01,28.0,32.0
46,Chennai,UNKNOWN,"Deals issused, not scratched",109,29,23,0.01,27.0,21.0
47,Hyderabad,DORMANT,Deals Not Issued,574183,256829,267100,40.64,45.0,47.0
48,Hyderabad,DORMANT,"Deals issused, not scratched",18138,10101,10422,0.91,56.0,57.0
49,Hyderabad,DORMANT,"Deals issused, scratched",680,390,405,0.90,57.0,60.0
50,Hyderabad,ELITE,Deals Not Issued,21378,18197,17845,1.51,85.0,83.0
51,Hyderabad,ELITE,"Deals issused, not scratched",285919,267691,259106,14.38,94.0,91.0
52,Hyderabad,ELITE,"Deals issused, scratched",25750,24462,23705,34.09,95.0,92.0
53,Hyderabad,GOLD,Deals Not Issued,246854,168945,166708,17.47,68.0,68.0
54,Hyderabad,GOLD,"Deals issused, not scratched",551479,394090,378393,27.74,71.0,69.0
55,Hyderabad,GOLD,"Deals issused, scratched",14735,10341,9815,19.51,70.0,67.0
56,Hyderabad,HH,Deals Not Issued,129684,40924,39478,9.18,32.0,30.0
57,Hyderabad,HH,"Deals issused, not scratched",222689,87281,78156,11.20,39.0,35.0
58,Hyderabad,HH,"Deals issused, scratched",3303,1314,1113,4.37,40.0,34.0
59,Hyderabad,PLATINUM,Deals Not Issued,117413,95760,93747,8.31,82.0,80.0
60,Hyderabad,PLATINUM,"Deals issused, not scratched",511648,439607,422664,25.74,86.0,83.0
61,Hyderabad,PLATINUM,"Deals issused, scratched",21845,18767,17927,28.92,86.0,82.0
62,Hyderabad,PRIME,Deals Not Issued,635,480,467,0.04,76.0,74.0
63,Hyderabad,PRIME,"Deals issused, not scratched",7567,6776,6379,0.38,90.0,84.0
64,Hyderabad,PRIME,"Deals issused, scratched",2527,2355,2230,3.35,93.0,88.0
65,Hyderabad,SILVER,Deals Not Issued,322353,159261,160036,22.82,49.0,50.0
66,Hyderabad,SILVER,"Deals issused, not scratched",390501,203690,200017,19.64,52.0,51.0
67,Hyderabad,SILVER,"Deals issused, scratched",6699,3429,3318,8.87,51.0,50.0
68,Hyderabad,UNKNOWN,Deals Not Issued,231,59,49,0.02,26.0,21.0
69,Hyderabad,UNKNOWN,"Deals issused, not scratched",124,33,23,0.01,27.0,19.0

In [42]:
def resample(df):

    # Group by city_name and isScratched
    grouped = df.groupby(['city_name', 'isScratched'])
    
    # Function to resample within each group while maintaining stratification on segments
    def stratified_resample(group):
        # Stratify based on taxi_retention_segments and taxi_regularity_segment
        return group.groupby(['taxi_retention_segments', 'taxi_regularity_segment'], group_keys=False).apply(lambda x: x.sample(frac=1, random_state=42))
    
    # Apply the stratified resampling function to each group
    resampled_df = grouped.apply(stratified_resample)
    
    # Reset index to clean up the multi-level index from groupby
    resampled_df = resampled_df.reset_index(drop=True)

    return resampled_df

In [ ]:
resampled_df = resample(df)

In [44]:
resampled_analysisv1 = resampled_df\
                .groupby(['city_name', 'taxi_retention_segments', 'isScratched'])\
                .agg(
                    customers = ('customer_id', 'nunique'),
                    nov_retention = ('customer_id', lambda x: x[df['nov_retention'] == 1].nunique()),
                    dec_retention = ('customer_id', lambda x: x[df['dec_retention'] == 1].nunique())
                    )\
                .reset_index()

resampled_analysisv1['customers distr %'] = round(resampled_analysisv1['customers']*100.00/resampled_analysisv1.groupby(['city_name', 'isScratched'])['customers'].transform('sum'), 2)
resampled_analysisv1['nov retention %'] = round(resampled_analysisv1['nov_retention']*100.00/resampled_analysisv1['customers'])
resampled_analysisv1['dec retention %'] = round(resampled_analysisv1['dec_retention']*100.00/resampled_analysisv1['customers'])
resampled_analysisv1

,city_name,taxi_retention_segments,isScratched,customers,nov_retention,dec_retention,customers distr %,nov retention %,dec retention %
0,Bangalore,DORMANT,Deals Not Issued,311821,197213,190990,59.71,63.0,61.0
1,Bangalore,DORMANT,"Deals issused, not scratched",104968,66658,64743,5.27,64.0,62.0
2,Bangalore,DORMANT,"Deals issused, scratched",3251,2037,2018,2.62,63.0,62.0
3,Bangalore,ELITE,Deals Not Issued,4202,2704,2619,0.80,64.0,62.0
4,Bangalore,ELITE,"Deals issused, not scratched",254875,161484,156713,12.81,63.0,61.0
5,Bangalore,ELITE,"Deals issused, scratched",38635,24350,23601,31.13,63.0,61.0
6,Bangalore,GOLD,Deals Not Issued,56304,35618,34534,10.78,63.0,61.0
7,Bangalore,GOLD,"Deals issused, not scratched",507486,320953,310863,25.50,63.0,61.0
8,Bangalore,GOLD,"Deals issused, scratched",25922,16492,15923,20.89,64.0,61.0
9,Bangalore,HH,Deals Not Issued,37389,23609,22929,7.16,63.0,61.0
10,Bangalore,HH,"Deals issused, not scratched",293981,186353,180055,14.77,63.0,61.0
11,Bangalore,HH,"Deals issused, scratched",5345,3337,3258,4.31,62.0,61.0
12,Bangalore,PLATINUM,Deals Not Issued,22824,14395,13947,4.37,63.0,61.0
13,Bangalore,PLATINUM,"Deals issused, not scratched",429319,271905,264077,21.57,63.0,62.0
14,Bangalore,PLATINUM,"Deals issused, scratched",36287,22898,22385,29.24,63.0,62.0
15,Bangalore,PRIME,Deals Not Issued,118,73,72,0.02,62.0,61.0
16,Bangalore,PRIME,"Deals issused, not scratched",5101,3250,3157,0.26,64.0,62.0
17,Bangalore,PRIME,"Deals issused, scratched",2289,1449,1430,1.84,63.0,62.0
18,Bangalore,SILVER,Deals Not Issued,89516,56820,55312,17.14,63.0,62.0
19,Bangalore,SILVER,"Deals issused, not scratched",394430,250108,242169,19.82,63.0,61.0
20,Bangalore,SILVER,"Deals issused, scratched",12386,7875,7578,9.98,64.0,61.0
21,Bangalore,UNKNOWN,Deals Not Issued,77,47,49,0.01,61.0,64.0
22,Bangalore,UNKNOWN,"Deals issused, not scratched",175,107,121,0.01,61.0,69.0
23,Bangalore,UNKNOWN,"Deals issused, scratched",2,2,2,0.00,100.0,100.0
24,Chennai,DORMANT,Deals Not Issued,239415,151735,147348,64.54,63.0,62.0
25,Chennai,DORMANT,"Deals issused, not scratched",78386,49669,48086,5.78,63.0,61.0
26,Chennai,DORMANT,"Deals issused, scratched",1604,1044,973,2.65,65.0,61.0
27,Chennai,ELITE,Deals Not Issued,3026,1925,1856,0.82,64.0,61.0
28,Chennai,ELITE,"Deals issused, not scratched",176695,111923,108316,13.04,63.0,61.0
29,Chennai,ELITE,"Deals issused, scratched",19855,12607,12126,32.74,63.0,61.0
30,Chennai,GOLD,Deals Not Issued,34660,21886,21256,9.34,63.0,61.0
31,Chennai,GOLD,"Deals issused, not scratched",352192,223053,215550,25.99,63.0,61.0
32,Chennai,GOLD,"Deals issused, scratched",12105,7737,7397,19.96,64.0,61.0
33,Chennai,HH,Deals Not Issued,22020,13975,13617,5.94,63.0,62.0
34,Chennai,HH,"Deals issused, not scratched",183892,116769,113268,13.57,63.0,62.0
35,Chennai,HH,"Deals issused, scratched",2224,1402,1379,3.67,63.0,62.0
36,Chennai,PLATINUM,Deals Not Issued,15263,9746,9410,4.11,64.0,62.0
37,Chennai,PLATINUM,"Deals issused, not scratched",303582,192170,186218,22.40,63.0,61.0
38,Chennai,PLATINUM,"Deals issused, scratched",17943,11360,10929,29.59,63.0,61.0
39,Chennai,PRIME,Deals Not Issued,64,40,48,0.02,62.0,75.0
40,Chennai,PRIME,"Deals issused, not scratched",3823,2374,2345,0.28,62.0,61.0
41,Chennai,PRIME,"Deals issused, scratched",1591,1022,981,2.62,64.0,62.0
42,Chennai,SILVER,Deals Not Issued,56452,35646,34675,15.22,63.0,61.0
43,Chennai,SILVER,"Deals issused, not scratched",256665,162608,157678,18.94,63.0,61.0
44,Chennai,SILVER,"Deals issused, scratched",5319,3384,3240,8.77,64.0,61.0
45,Chennai,UNKNOWN,Deals Not Issued,47,27,25,0.01,57.0,53.0
46,Chennai,UNKNOWN,"Deals issused, not scratched",109,83,75,0.01,76.0,69.0
47,Hyderabad,DORMANT,Deals Not Issued,574183,363912,352743,40.64,63.0,61.0
48,Hyderabad,DORMANT,"Deals issused, not scratched",18138,11487,11038,0.91,63.0,61.0
49,Hyderabad,DORMANT,"Deals issused, scratched",680,423,421,0.90,62.0,62.0
50,Hyderabad,ELITE,Deals Not Issued,21378,13561,13181,1.51,63.0,62.0
51,Hyderabad,ELITE,"Deals issused, not scratched",285919,181514,176039,14.38,63.0,62.0
52,Hyderabad,ELITE,"Deals issused, scratched",25750,16192,15724,34.09,63.0,61.0
53,Hyderabad,GOLD,Deals Not Issued,246854,156619,151454,17.47,63.0,61.0
54,Hyderabad,GOLD,"Deals issused, not scratched",551479,349604,338385,27.74,63.0,61.0
55,Hyderabad,GOLD,"Deals issused, scratched",14735,9382,8995,19.51,64.0,61.0
56,Hyderabad,HH,Deals Not Issued,129684,81972,79572,9.18,63.0,61.0
57,Hyderabad,HH,"Deals issused, not scratched",222689,141220,136727,11.20,63.0,61.0
58,Hyderabad,HH,"Deals issused, scratched",3303,2136,2048,4.37,65.0,62.0
59,Hyderabad,PLATINUM,Deals Not Issued,117413,74425,72095,8.31,63.0,61.0
60,Hyderabad,PLATINUM,"Deals issused, not scratched",511648,323912,313289,25.74,63.0,61.0
61,Hyderabad,PLATINUM,"Deals issused, scratched",21845,13814,13329,28.92,63.0,61.0
62,Hyderabad,PRIME,Deals Not Issued,635,398,404,0.04,63.0,64.0
63,Hyderabad,PRIME,"Deals issused, not scratched",7567,4756,4671,0.38,63.0,62.0
64,Hyderabad,PRIME,"Deals issused, scratched",2527,1625,1541,3.35,64.0,61.0
65,Hyderabad,SILVER,Deals Not Issued,322353,203998,197725,22.82,63.0,61.0
66,Hyderabad,SILVER,"Deals issused, not scratched",390501,247517,239341,19.64,63.0,61.0
67,Hyderabad,SILVER,"Deals issused, scratched",6699,4294,4090,8.87,64.0,61.0
68,Hyderabad,UNKNOWN,Deals Not Issued,231,157,149,0.02,68.0,65.0
69,Hyderabad,UNKNOWN,"Deals issused, not scratched",124,72,76,0.01,58.0,61.0

In [ ]:
resampled_df.to_parquet('/Users/E2074/local-datasets/customer/ads-monetisation/deals-impact/resampled_data.parquet', index=False)