In [10]:
import os
import time
import pandas as pd

In [11]:
directory = "/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/"

In [12]:
columns = ['customer_id', 'age_group', 'confidence_tag', 'run_date']

In [13]:
csv_files = [f for f in os.listdir(directory) if f.endswith(".csv")]

In [14]:
final_df = pd.DataFrame(columns=columns)

In [19]:
start = time.time()
for csv_file in csv_files:
    start_time = time.time()
    
    file_path = os.path.join(directory, csv_file)
    df = pd.read_csv(file_path, names=columns)
    final_df = pd.concat([final_df, df]).drop_duplicates(subset=['customer_id'], keep="first")

    end_time = time.time()
    execution_time = round(((end_time - start_time)*1.00/60.00), 2)
    print("Execution time:", execution_time, "mins")

end = time.time()
execution = round(((end - start)*1.00/60.00), 2)
print("Execution time:", execution, "mins")

Execution time: 0.76 mins
Execution time: 0.51 mins
Execution time: 0.66 mins
Execution time: 0.5 mins
Execution time: 0.59 mins
Execution time: 0.61 mins
Execution time: 0.5 mins
Execution time: 0.49 mins
Execution time: 0.59 mins
Execution time: 0.57 mins
Execution time: 0.54 mins
Execution time: 0.57 mins
Execution time: 0.54 mins
Execution time: 0.54 mins
Execution time: 0.48 mins
Execution time: 0.52 mins
Execution time: 0.52 mins
Execution time: 0.55 mins
Execution time: 0.64 mins
Execution time: 0.58 mins
Execution time: 0.51 mins
Execution time: 0.54 mins
Execution time: 0.54 mins
Execution time: 0.54 mins
Execution time: 13.4 mins

In [35]:
df_test = pd.read_csv('/Users/E2074/Downloads/query_result_2025-02-11T17_04_05.390068+05_30.csv')

In [36]:
df_test.shape

(1048575, 4)

In [28]:
df_old.shape

(13715639, 4)

In [29]:
final_df.shape

(36305144, 4)

In [30]:
overall_df = pd.concat([final_df, df_old]).drop_duplicates(subset=['customer_id'], keep="first")

In [32]:
overall_df.shape

(45282550, 4)

In [31]:
overall_df.customer_id.nunique()

45282550

In [34]:
overall_df.to_csv("/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_oct_nov_dec_jan.csv", header=False, index=False)

In [ ]:
# 45,282,550

In [ ]:
# 36305144
# 37933837

In [18]:
37933837 - 36305144

1628693

In [21]:
final_df.reset_index(drop=True, inplace=True)

In [17]:
final_df.shape

(37933837, 4)

In [22]:
final_df.shape

(36305144, 4)

In [23]:
final_df.customer_id.nunique()

36305144

In [24]:
final_df.head()

                customer_id age_group confidence_tag    run_date
0  5e10aa26715b3f22b9661424     36-45      VERY_HIGH  2025-02-10
1  5c890ed18c352421eae85677     36-45      VERY_HIGH  2025-02-10
2  6718b40c6bd8d114a39ed1a5     26-30      VERY_HIGH  2025-02-10
3  5fc07efe014147c6d60a55cb     21-25      VERY_HIGH  2025-02-10
4  5c8695f58c352421eae5219c     36-45      VERY_HIGH  2025-02-10

In [25]:
final_df.customer_id.nunique()

36305144

In [26]:
final_df\
.to_csv("/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_nov_dec_jan.csv", 
        header=False,
        index=False)

In [ ]:

# Define the directory containing the CSV files
directory = "/path/to/csv/files"

# Define the column headers (since CSVs don't have headers)
columns = ["col1", "col2", "col3", "col4"]  # Replace with actual column names

# Get a list of all CSV files in the directory
csv_files = [f for f in os.listdir(directory) if f.endswith(".csv")]

# Initialize an empty DataFrame
final_df = pd.DataFrame(columns=columns)

# Iterate through each CSV file, read, concatenate, and remove duplicates
for csv_file in csv_files:
    file_path = os.path.join(directory, csv_file)
    df = pd.read_csv(file_path, names=columns)  # Read CSV without header
    final_df = pd.concat([final_df, df]).drop_duplicates(keep="first")

# Reset index after processing
final_df.reset_index(drop=True, inplace=True)

# Print final DataFrame
print(final_df)

# Optionally, save the final DataFrame
final_df.to_csv("merged_output.csv", index=False)

In [1]:
import os
import pandas as pd

In [2]:
local_extract = '/Users/E2074/local-datasets/customer/age-prediction/local_extract/'
path = local_extract + 'final/'
path

'/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/'

In [3]:
parquet_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.csv')]
parquet_files

['/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_5.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_oct_nov_1.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_feb_4.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_oct_nov_0.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_4.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_6.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_oct_nov_2.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_oct_nov_3.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_7.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_3.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_feb_2.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_feb_3.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_2.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_0.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_oct_nov_4.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_feb_1.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_feb_0.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_oct_nov_5.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_1.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_10.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_11.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_12.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_9.csv',
 '/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_dec_jan_8.csv']

In [4]:
# parquet_files = [
 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20241012_customer_demo_data.parquet',
 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20241027_customer_demo_data.parquet',

 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20241211_customer_demo_data.parquet',
 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20241126_customer_demo_data.parquet'

 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20241211_customer_demo_data.parquet',
 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20241226_customer_demo_data.parquet',

 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20250110_customer_demo_data.parquet',
 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20250125_customer_demo_data.parquet'
    
 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20250201_customer_demo_data.parquet',
 # '/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/20250206_customer_demo_data.parquet'
# ]

In [37]:
column_names = ['customer_id', 'age_group', 'confidence_tag', 'run_date']  # Replace with actual names

df_test = pd.read_csv('/Users/E2074/local-datasets/customer/age-prediction/local_extract/final/customer_predicted_age_oct_nov_0.csv',
                     header=None,
                     names=column_names)

In [38]:
df_test

                      customer_id age_group confidence_tag    run_date
0        631adfa7e21090bc7c10d9c6     31-35      VERY_HIGH  2025-02-10
1        5fbe43b790d77976c3be70be     26-30      VERY_HIGH  2025-02-10
2        5de10264ac56a62ec5e11358     36-45      VERY_HIGH  2025-02-10
3        6119e9f6d8ec8e9dfa0cc539     21-25      VERY_HIGH  2025-02-10
4        64fdbf751ce35a1634001fae  Above-45      VERY_HIGH  2025-02-10
...                           ...       ...            ...         ...
1633755  62178307d6e80d5e752d91f9     21-25           HIGH  2025-02-10
1633756  666569a58eeaea13968977e6     21-25           HIGH  2025-02-10
1633757  6730f0b87ab2880ffb10df15     21-25           HIGH  2025-02-10
1633758  6403284f8e212cd3184dda7d     21-25           HIGH  2025-02-10
1633759  65e97fc91444ce461a092a21     21-25         MEDIUM  2025-02-10

[1633760 rows x 4 columns]

In [28]:
df_test[~df_test['6015683171432337fec53bda'].isna()].shape

(1026733, 4)

In [ ]:
1089174

In [5]:
# parquet_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.parquet')]
df_list = [pd.read_parquet(file) for file in parquet_files]
print('customer demo')
df_customer_demo_data = pd.concat(df_list, ignore_index=True)

customer demo

In [6]:
print(df_customer_demo_data.shape)
print(df_customer_demo_data.userid.nunique())

(39874785, 42)
36305144

In [7]:
df_customer_demo_data = df_customer_demo_data.drop_duplicates(subset=['userid'], keep='first', inplace=False)

In [8]:
print(df_customer_demo_data.shape)
print(df_customer_demo_data.userid.nunique())

(36305144, 42)
36305144

In [9]:
df1 = df_customer_demo_data

In [15]:
df2 = df_customer_demo_data

In [23]:
df3 = df_customer_demo_data

In [16]:
df1.to_parquet('/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/oct_nov_customer_demo_data.parquet', index=False)

In [17]:
df2.to_parquet('/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/dec_jan_customer_demo_data.parquet', index=False)

In [24]:
df3.to_parquet('/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/feb_customer_demo_data.parquet', index=False)

In [9]:
df_customer_demo_data.to_parquet('/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/customer_demo_data.parquet', index=False)

In [ ]:
df_list = [df1, df2]
dfv1 = pd.concat(df_list, ignore_index=True)
dfv1 = dfv1.drop_duplicates(subset=['userid'], keep='first', inplace=False)

In [ ]:
print(dfv1.shape)
print(dfv1.userid.nunique())

In [27]:
df3 = df_customer_demo_data

In [33]:
df4 = df_customer_demo_data

In [ ]:
df1.head(1)

In [ ]:
df2.head(1)

In [ ]:
df3.head(1)

In [ ]:
df4.head(1)

In [ ]:
df_list = [df1, df2, df3, df4]
df_customer_demo_data = pd.concat(df_list, ignore_index=True)
df_customer_demo_data = df_customer_demo_data.drop_duplicates(subset=['userid'], keep='first', inplace=False)

In [ ]:
print(df_customer_demo_data.shape)
print(df_customer_demo_data.userid.nunique())

In [ ]:
df_customer_demo_data = pd.to_parquet('/Users/E2074/local-datasets/customer/age-prediction/local_extract/demo/customer_demo_data.parquet', index=False)

In [2]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9