## Import

In [2]:
import re
import os 
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from pyhive import presto
from datetime import date
from collections import Counter

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'

conn=presto.connect('presto-gateway.processing.data.production.internal',presto_port,username)

connection1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
connection2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
connection3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
connection4= presto.connect('processing.processing.data.production.internal',presto_port,username)


pd.set_option('display.max_columns', None)

In [8]:
pd.set_option('display.max_rows', None)

In [35]:
curr_overall_query1=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        --user_type,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            --user_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1
        )
    ORDER BY 1


"""
curr_overall_df1=pd.read_sql(curr_overall_query1,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/1418172729.py:222: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_overall_df1=pd.read_sql(curr_overall_query1,conn)

In [36]:
curr_overall_df1

,sample_category,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,504812,3089512,1083433,600497,35.07,55.43,19.44,74.17,194251,3543,1.82,108,128,297,171,14,1.02,16.21,18.37,8.59,11019,175669,199042,93025
1,test,493942,3011917,1057775,586378,35.12,55.44,19.47,74.21,107238,3066,2.86,107,128,302,172,14,0.98,16.21,18.40,8.58,10401,171455,194645,90715

In [37]:
curr_overall_df1.to_csv('curr_overall_df1.csv',index=False)

In [17]:
curr_overall_df1

,sample_category,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,504812,3089512,1083433,600497,35.07,55.43,19.44,74.17,109,128,295,171,13,1.02,16.21,18.37,8.59,11019,175669,199042,93025
1,test,493942,3011917,1057775,586378,35.12,55.44,19.47,74.21,107,128,300,172,14,0.98,16.21,18.40,8.58,10401,171455,194645,90715

In [ ]:
curr_overall_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2
        )
    ORDER BY 1,2


"""
curr_overall_df=pd.read_sql(curr_overall_query,conn)

In [11]:
pd.set_option('display.max_columns', None)

In [12]:
curr_overall_df

,sample_category,user_type,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,3523,24983,12010,2510,48.07,20.90,10.05,34.88,173,157,343,181,38,1.88,31.87,13.83,31.34,226,3827,1661,3764
1,control,None,503398,3064529,1071423,597987,34.96,55.81,19.51,74.61,108,127,298,170,14,1.01,16.04,18.42,8.33,10793,171842,197381,89261
2,test,clicked_users,3041,23245,11735,2249,50.48,19.16,9.68,31.80,127,156,381,180,36,1.96,34.67,12.50,31.56,230,4069,1467,3704
3,test,None,492990,2988672,1046040,584129,35.00,55.84,19.54,74.69,106,127,298,172,14,0.97,16.00,18.47,8.32,10171,167386,193178,87011

In [34]:
curr_session_query1=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        --user_type,
        time_period,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            --user_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2
        )
    ORDER BY 1,2


"""
curr_session_df1=pd.read_sql(curr_session_query1,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/1120065599.py:230: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_session_df1=pd.read_sql(curr_session_query1,conn)

KeyboardInterrupt:

In [19]:
curr_session_df1

,sample_category,time_period,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,afternoon,257219,963651,323284,207470,33.55,64.18,21.53,83.41,110,119,295,179,11,0.79,10.54,18.84,5.26,2567,34070,60906,16997
1,control,evening,231767,901414,318271,159062,35.31,49.98,17.65,69.80,105,127,309,169,18,0.79,19.55,19.46,9.83,2516,62219,61945,31290
2,control,morning,173623,682231,252696,126095,37.04,49.90,18.48,64.92,112,137,287,163,17,0.80,21.46,14.79,12.81,2033,54240,37365,32375
3,control,rest_evening,97627,274962,95083,56459,34.58,59.38,20.53,81.10,106,116,300,180,15,1.19,12.23,21.11,5.38,1135,11630,20069,5116
4,control,rest_morning,84986,267254,94099,51411,35.21,54.64,19.24,75.00,108,130,261,160,11,2.94,14.36,19.93,7.70,2768,13510,18757,7247
5,test,afternoon,252139,942152,316307,203245,33.57,64.26,21.57,83.54,109,119,296,181,11,0.80,10.41,18.87,5.24,2546,32942,59698,16575
6,test,evening,226505,879927,312204,155645,35.48,49.85,17.69,69.78,104,125,311,170,17,0.76,19.53,19.56,9.91,2364,60979,61054,30924
7,test,morning,169819,662030,244649,122377,36.95,50.02,18.49,64.91,104,137,292,164,16,0.78,21.60,14.64,12.70,1912,52848,35809,31077
8,test,rest_evening,95470,268686,93204,55396,34.69,59.44,20.62,81.22,98,115,301,180,14,1.13,12.14,21.21,5.39,1057,11316,19766,5025
9,test,rest_morning,82786,259122,91411,49715,35.28,54.39,19.19,74.83,111,134,283,170,11,2.76,14.63,20.04,7.78,2522,13370,18318,7114

In [40]:
curr_session_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        time_period,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
curr_session_df=pd.read_sql(curr_session_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/4216387126.py:230: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_session_df=pd.read_sql(curr_session_query,conn)

KeyboardInterrupt:

In [14]:
curr_session_df

,sample_category,user_type,time_period,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,afternoon,1332,5781,2602,772,45.01,29.67,13.35,45.73,148,147,335,185,25,2.50,24.83,15.95,26.94,65,646,415,701
1,control,clicked_users,evening,1785,8426,3989,783,47.34,19.63,9.29,35.07,173,161,388,189,43,0.98,33.54,15.27,30.31,39,1338,609,1209
2,control,clicked_users,morning,1415,7342,3745,543,51.01,14.50,7.40,24.01,220,156,325,172,67,1.20,38.32,9.48,36.48,45,1435,355,1366
3,control,clicked_users,rest_evening,459,1586,750,235,47.29,31.33,14.82,50.00,146,152,202,163,26,2.40,24.27,18.13,23.33,18,182,136,175
4,control,clicked_users,rest_morning,507,1848,924,177,50.00,19.16,9.58,35.28,187,170,348,197,25,6.39,24.46,15.80,33.87,59,226,146,313
5,control,None,afternoon,256397,957870,320682,206698,33.48,64.46,21.58,83.71,109,119,295,179,11,0.78,10.42,18.86,5.08,2502,33424,60491,16296
6,control,None,evening,230761,892988,314282,158279,35.19,50.36,17.72,70.24,104,126,309,170,17,0.79,19.37,19.52,9.57,2477,60881,61336,30081
7,control,None,morning,172890,674889,248951,125552,36.89,50.43,18.60,65.53,111,136,288,162,17,0.80,21.21,14.87,12.46,1988,52805,37010,31009
8,control,None,rest_evening,97291,273376,94333,56224,34.51,59.60,20.57,81.35,105,116,301,180,14,1.18,12.14,21.13,5.24,1117,11448,19933,4941
9,control,None,rest_morning,84622,265406,93175,51234,35.11,54.99,19.30,75.39,107,130,259,159,12,2.91,14.26,19.97,7.44,2709,13284,18611,6934
10,test,clicked_users,afternoon,1058,4704,2246,644,47.75,28.67,13.69,44.39,130,146,385,174,18,2.98,27.87,15.67,24.76,67,626,352,556
11,test,clicked_users,evening,1538,7631,3748,690,49.12,18.41,9.04,33.27,125,151,379,181,49,0.93,37.14,14.67,28.66,35,1392,550,1074
12,test,clicked_users,morning,1505,8200,4338,567,52.90,13.07,6.91,21.37,158,164,352,178,68,0.99,38.96,8.23,38.68,43,1690,357,1678
13,test,clicked_users,rest_evening,343,1009,485,179,48.07,36.91,17.74,55.46,145,165,177,159,14,4.95,20.41,18.35,19.18,24,99,89,93
14,test,clicked_users,rest_morning,443,1701,918,169,53.97,18.41,9.94,31.81,111,153,692,197,22,6.64,28.54,12.96,33.01,61,262,119,303
15,test,None,afternoon,251608,937448,314061,202601,33.50,64.51,21.61,83.82,107,118,295,182,11,0.79,10.29,18.90,5.10,2479,32316,59346,16019
16,test,None,evening,225780,872296,308456,154955,35.36,50.24,17.76,70.22,104,125,309,171,16,0.76,19.32,19.62,9.68,2329,59587,60504,29850
17,test,None,morning,169134,653830,240311,121810,36.75,50.69,18.63,65.70,104,136,290,163,16,0.78,21.29,14.75,12.23,1869,51158,35452,29399
18,test,None,rest_evening,95247,267677,92719,55217,34.64,59.55,20.63,81.36,97,114,301,181,14,1.11,12.10,21.22,5.32,1033,11217,19677,4932
19,test,None,rest_morning,82497,257421,90493,49546,35.15,54.75,19.25,75.27,110,133,279,170,11,2.72,14.49,20.11,7.53,2461,13108,18199,6811

In [41]:
curr_session_cluseter_query1=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN pickup_cluster = 'NCR N Gharoli' THEN 'NCR N Gharoli'
            WHEN pickup_cluster = 'Dashrathpuri_Del_East' THEN 'Dashrathpuri_Del_East'
            WHEN pickup_cluster = 'Sec-57' THEN 'Sec-57'
            WHEN pickup_cluster = 'Sector 45-46' THEN 'Sector 45-46'
            WHEN pickup_cluster = 'NCR N sec 22/62' THEN 'NCR N sec 22/62'
            WHEN pickup_cluster = 'G Sadar Bazar' THEN 'G Sadar Bazar'
            WHEN pickup_cluster = 'Sec-39' THEN 'Sec-39'
            WHEN pickup_cluster = 'NCR N Sharda University 2' THEN 'NCR N Sharda University 2'
            WHEN pickup_cluster = 'Gurgaon Rural' THEN 'Gurgaon Rural'
            WHEN pickup_cluster = 'NCR N Venice Mall' THEN 'NCR N Venice Mall'
            WHEN pickup_cluster = 'NCR G Vijay Nagar 2' THEN 'NCR G Vijay Nagar 2'
            ELSE 'Other_clusters'
        END AS cluster_name
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        rr_net.cluster_name,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        --user_type,
        time_period,
        cluster_name,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            --user_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            cluster_name,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
curr_session_cluseter_df1=pd.read_sql(curr_session_cluseter_query1,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/1205394103.py:247: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_session_cluseter_df1=pd.read_sql(curr_session_cluseter_query1,conn)

KeyboardInterrupt:

In [32]:
curr_session_cluseter_df

,sample_category,time_period,cluster_name,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,afternoon,Dashrathpuri_Del_East,3680,5684,5761,3771,101.35,65.46,66.34,84.33,118.0,116.0,325.0,176.0,15.0,0.28,11.27,18.57,4.13,16,649,1070,238
1,control,afternoon,Gurgaon Rural,1926,3429,3579,1634,104.37,45.66,47.65,61.78,92.0,131.0,312.0,162.0,23.0,0.22,24.03,15.93,13.97,8,860,570,500
2,control,afternoon,NCR G Vijay Nagar 2,2562,3551,3556,2830,100.14,79.58,79.70,96.40,123.0,118.0,262.0,217.0,9.0,0.11,2.67,16.39,0.82,4,95,583,29
3,control,afternoon,NCR N Gharoli,3318,4821,4853,3556,100.66,73.27,73.76,92.71,90.0,110.0,297.0,217.0,10.0,0.10,4.55,18.98,2.64,5,221,921,128
4,control,afternoon,NCR N Sharda University 2,3301,5948,6077,3042,102.17,50.06,51.14,65.85,73.0,111.0,237.0,132.0,9.0,0.41,25.56,15.16,8.18,25,1553,921,497
5,control,afternoon,NCR N Venice Mall,1993,3343,3402,2067,101.76,60.76,61.83,79.19,89.0,117.0,269.0,158.0,7.0,2.47,12.46,17.58,5.85,84,424,598,199
6,control,afternoon,NCR N sec 22/62,2213,3138,3155,2434,100.54,77.15,77.57,92.33,89.0,95.0,269.0,178.0,10.0,0.03,5.96,14.77,1.68,1,188,466,53
7,control,afternoon,Other_clusters,152536,279131,283369,181840,101.52,64.17,65.15,83.61,112.0,119.0,298.0,180.0,11.0,0.85,10.27,19.05,5.27,2398,29110,53970,14936
8,control,afternoon,Sec-39,1843,2834,2899,1831,102.29,63.16,64.61,82.96,152.0,116.0,314.0,190.0,14.0,0.07,11.35,19.70,5.62,2,329,571,163
9,control,afternoon,Sec-57,2294,3634,3688,2391,101.49,64.83,65.80,84.11,123.0,125.0,268.0,174.0,11.0,0.46,10.87,19.03,4.56,17,401,702,168
10,control,afternoon,Sector 45-46,2001,2920,2945,2074,100.86,70.42,71.03,88.69,109.0,93.0,232.0,154.0,12.0,0.24,8.15,18.13,2.92,7,240,534,86
11,control,afternoon,None,221334,645218,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
12,control,evening,Dashrathpuri_Del_East,2704,4295,4402,2320,102.49,52.70,54.02,73.92,132.0,116.0,342.0,165.0,17.0,0.30,17.24,20.97,8.45,13,759,923,372
13,control,evening,Gurgaon Rural,1214,1944,1998,1117,102.78,55.91,57.46,74.92,22.0,132.0,276.0,173.0,11.0,0.05,16.32,18.42,8.61,1,326,368,172
14,control,evening,NCR G Vijay Nagar 2,1822,2564,2578,1870,100.55,72.54,72.93,91.74,44.0,106.0,339.0,215.0,10.0,0.12,6.48,18.62,1.67,3,167,480,43
15,control,evening,NCR N Gharoli,3172,5789,6049,2545,104.49,42.07,43.96,62.03,90.0,132.0,368.0,175.0,24.0,0.17,24.73,19.69,13.01,10,1496,1191,787
16,control,evening,NCR N Sharda University 2,2343,4972,5137,1717,103.32,33.42,34.53,46.00,90.0,119.0,317.0,137.0,12.0,0.76,40.00,12.19,13.24,39,2055,626,680
17,control,evening,NCR N Venice Mall,1808,3082,3155,1640,102.37,51.98,53.21,71.79,99.0,109.0,270.0,156.0,10.0,2.28,18.35,18.92,7.58,72,579,597,239
18,control,evening,NCR N sec 22/62,3008,6619,6968,2333,105.27,33.48,35.25,49.73,124.0,136.0,382.0,168.0,34.0,0.07,33.81,15.87,16.33,5,2356,1106,1138
19,control,evening,Other_clusters,139009,269580,277143,139676,102.81,50.40,51.81,70.49,106.0,127.0,309.0,172.0,17.0,0.85,18.91,19.73,9.73,2349,52412,54668,26959
20,control,evening,Sec-39,1770,3197,3272,1659,102.35,50.70,51.89,71.36,22.0,120.0,294.0,165.0,18.0,0.28,20.54,20.32,7.82,9,672,665,256
21,control,evening,Sec-57,1991,3437,3565,1916,103.72,53.74,55.75,70.52,66.0,129.0,292.0,167.0,16.0,0.25,18.51,16.69,10.72,9,660,595,382
22,control,evening,Sector 45-46,2288,3919,4004,2269,102.17,56.67,57.90,74.90,218.0,116.0,274.0,165.0,23.0,0.15,18.41,18.13,6.54,6,737,726,262
23,control,evening,None,200751,592016,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
24,control,morning,Dashrathpuri_Del_East,2222,3889,3961,2318,101.85,58.52,59.60,74.12,114.0,137.0,331.0,182.0,22.0,0.48,18.91,15.37,6.49,19,749,609,257
25,control,morning,Gurgaon Rural,1554,3868,4314,924,111.53,21.42,23.89,28.98,84.0,138.0,322.0,148.0,42.0,0.05,39.11,7.46,31.87,2,1687,322,1375
26,control,morning,NCR G Vijay Nagar 2,1911,3299,3331,2291,100.97,68.78,69.45,84.36,NaN,133.0,238.0,164.0,18.0,0.00,12.07,15.28,3.57,0,402,509,119
27,control,morning,NCR N Gharoli,2215,3769,3799,2642,100.80,69.54,70.10,87.97,76.0,117.0,349.0,200.0,16.0,0.05,9.40,18.08,2.58,2,357,687,98
28,control,morning,NCR N Sharda University 2,1009,1526,1531,1076,100.33,70.28,70.51,90.92,43.0,108.0,214.0,157.0,6.0,0.46,7.32,19.92,1.31,7,112,305,20
29,control,morning,NCR N Venice Mall,1355,3187,3290,1304,103.23,39.64,40.92,53.04,80.0,113.0,227.0,126.0,12.0,3.07,31.58,12.71,12.31,101,1039,418,405
30,control,morning,NCR N sec 22/62,1343,2442,2454,1889,100.49,76.98,77.35,91.61,NaN,121.0,288.0,202.0,11.0,0.00,7.46,13.98,0.94,0,183,343,23
31,control,morning,Other_clusters,100845,203287,211033,107809,103.81,51.09,53.03,66.54,114.0,137.0,287.0,163.0,16.0,0.89,20.67,15.23,11.89,1883,43616,32134,25101
32,control,morning,Sec-39,2057,5322,5805,1772,109.08,30.53,33.30,41.07,98.0,151.0,337.0,169.0,40.0,0.14,32.47,10.46,26.32,8,1885,607,1528
33,control,morning,Sec-57,2187,6054,6623,1880,109.40,28.39,31.05,39.12,114.0,145.0,314.0,162.0,35.0,0.08,33.08,10.66,27.72,5,2191,706,1836
34,control,morning,Sector 45-46,2305,6050,6555,2190,108.35,33.41,36.20,44.50,92.0,134.0,289.0,151.0,39.0,0.09,30.80,11.06,24.61,6,2019,725,1613
35,control,morning,None,148083,439538,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
36,control,rest_evening,Dashrathpuri_Del_East,1066,1580,1597,971,101.08,60.80,61.46,85.10,162.0,105.0,399.0,217.0,18.0,1.19,9.77,23.92,3.88,19,156,382,62
37,control,rest_evening,Gurgaon Rural,338,486,501,276,103.09,55.09,56.79,72.06,6.0,120.0,304.0,157.0,14.0,0.20,17.56,16.37,10.18,1,88,82,51
38,control,rest_evening,NCR G Vijay Nagar 2,678,904,909,635,100.55,69.86,70.24,89.33,177.0,107.0,236.0,162.0,10.0,1.10,6.93,19.03,2.64,10,63,173,24
39,control,rest_evening,NCR N Gharoli,901,1243,1255,841,100.97,67.01,67.66,90.76,71.0,95.0,292.0,227.0,13.0,0.32,5.34,22.87,3.51,4,67,287,44
40,control,rest_evening,NCR N Sharda University 2,328,468,469,296,100.21,63.11,63.25,82.73,115.0,92.0,228.0,140.0,7.0,2.13,11.51,17.70,3.41,10,54,83,16
41,control,rest_evening,NCR N Venice Mall,429,633,644,334,101.74,51.86,52.76,76.24,91.0,129.0,254.0,171.0,8.0,4.97,11.34,23.60,7.45,32,73,152,48
42,control,rest_evening,NCR N sec 22/62,576,785,789,573,100.51,72.62,72.99,91.25,36.0,126.0,290.0,196.0,13.0,0.25,6.72,17.74,1.77,2,53,140,14
43,control,rest_evening,Other_clusters,54340,85154,86346,50978,101.40,59.04,59.87,80.81,107.0,117.0,300.0,179.0,14.0,1.20,12.41,21.16,5.49,1038,10713,18267,4737
44,control,rest_evening,Sec-39,473,703,713,432,101.42,60.59,61.45,83.17,59.0,123.0,325.0,179.0,12.0,0.56,12.06,22.02,4.07,4,86,157,29
45,control,rest_evening,Sec-57,559,797,811,484,101.76,59.68,60.73,77.19,69.0,107.0,355.0,153.0,11.0,1.36,15.17,16.77,6.04,11,123,136,49
46,control,rest_evening,Sector 45-46,644,1040,1049,639,100.87,60.92,61.44,80.93,85.0,116.0,236.0,171.0,13.0,0.38,14.68,20.02,4.00,4,154,210,42
47,control,rest_evening,None,79000,181169,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
48,control,rest_morning,Dashrathpuri_Del_East,1212,2014,2036,1079,101.09,53.00,53.57,74.26,110.0,131.0,403.0,186.0,21.0,1.18,19.11,20.92,5.45,24,389,426,111
49,control,rest_morning,Gurgaon Rural,476,851,911,360,107.05,39.52,42.30,54.34,98.0,154.0,293.0,183.0,14.0,0.33,26.23,14.49,19.10,3,239,132,174
50,control,rest_morning,NCR G Vijay Nagar 2,726,1091,1093,816,100.18,74.66,74.79,92.31,109.0,118.0,179.0,153.0,8.0,1.10,5.12,17.02,1.46,12,56,186,16
51,control,rest_morning,NCR N Gharoli,900,1315,1320,916,100.38,69.39,69.66,92.20,127.0,135.0,308.0,206.0,9.0,1.29,4.55,22.05,1.97,17,60,291,26
52,control,rest_morning,NCR N Sharda University 2,163,233,239,135,102.58,56.49,57.94,75.31,99.0,123.0,275.0,150.0,6.0,8.79,8.37,17.57,7.53,21,20,42,18
53,control,rest_morning,NCR N Venice Mall,569,1093,1125,413,102.93,36.71,37.79,51.20,117.0,99.0,250.0,125.0,10.0,14.76,20.98,14.04,13.07,166,236,158,147
54,control,rest_morning,NCR N sec 22/62,462,663,665,505,100.30,75.94,76.17,94.14,72.0,137.0,219.0,194.0,7.0,0.90,3.46,17.74,1.50,6,23,118,10
55,control,rest_morning,Other_clusters,47690,81770,83514,45704,102.13,54.73,55.89,75.44,108.0,130.0,256.0,160.0,11.0,2.95,14.17,20.29,7.43,2466,11836,16942,6209
56,control,rest_morning,Sec-39,572,955,1032,487,108.06,47.19,50.99,62.31,97.0,148.0,267.0,166.0,12.0,0.87,18.12,14.92,18.70,9,187,154,193
57,control,rest_morning,Sec-57,586,1052,1120,474,106.46,42.32,45.06,56.07,135.0,116.0,302.0,137.0,11.0,3.04,24.11,13.13,16.79,34,270,147,188
58,control,rest_morning,Sector 45-46,610,1003,1044,522,104.09,50.00,52.04,65.61,127.0,137.0,288.0,159.0,11.0,0.96,18.58,15.42,14.85,10,194,161,155
59,control,rest_morning,None,70505,175214,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
60,test,afternoon,Dashrathpuri_Del_East,3592,5479,5542,3495,101.15,63.06,63.79,84.18,90.0,124.0,324.0,198.0,15.0,0.14,11.48,20.84,4.20,8,636,1155,233
61,test,afternoon,Gurgaon Rural,1830,3392,3579,1560,105.51,43.59,45.99,59.96,124.0,120.0,369.0,156.0,20.0,0.45,26.15,16.01,13.41,16,936,573,480
62,test,afternoon,NCR G Vijay Nagar 2,2442,3408,3418,2723,100.29,79.67,79.90,95.23,29.0,102.0,263.0,205.0,9.0,0.29,3.31,15.30,1.17,10,113,523,40
63,test,afternoon,NCR N Gharoli,3257,4571,4599,3426,100.61,74.49,74.95,92.93,94.0,115.0,295.0,214.0,10.0,0.13,4.52,17.90,2.41,6,208,823,111
64,test,afternoon,NCR N Sharda University 2,3200,5716,5838,2924,102.13,50.09,51.15,65.14,78.0,108.0,245.0,130.0,9.0,0.53,26.36,14.41,7.97,31,1539,841,465
65,test,afternoon,NCR N Venice Mall,2093,3516,3582,2156,101.88,60.19,61.32,77.19,111.0,121.0,272.0,156.0,7.0,2.79,13.96,16.19,6.06,100,500,580,217
66,test,afternoon,NCR N sec 22/62,2319,3202,3222,2500,100.62,77.59,78.08,92.74,23.0,114.0,282.0,205.0,10.0,0.03,5.12,14.65,2.11,1,165,472,68
67,test,afternoon,Other_clusters,149783,273246,277346,178379,101.50,64.32,65.28,83.83,110.0,119.0,296.0,183.0,11.0,0.85,10.07,19.10,5.25,2362,27921,52981,14567
68,test,afternoon,Sec-39,1733,2631,2685,1753,102.05,65.29,66.63,84.58,100.0,114.0,273.0,167.0,13.0,0.07,9.94,18.92,5.40,2,267,508,145
69,test,afternoon,Sec-57,2248,3516,3572,2280,101.59,63.83,64.85,83.96,162.0,109.0,315.0,180.0,12.0,0.20,10.86,19.99,4.98,7,388,714,178
70,test,afternoon,Sector 45-46,1917,2901,2924,2049,100.79,70.08,70.63,88.27,80.0,95.0,299.0,183.0,12.0,0.10,9.20,18.06,2.43,3,269,528,71
71,test,afternoon,None,216734,630574,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
72,test,evening,Dashrathpuri_Del_East,2608,4198,4305,2262,102.55,52.54,53.88,72.06,29.0,126.0,329.0,176.0,16.0,0.09,18.30,19.09,9.52,4,788,822,410
73,test,evening,Gurgaon Rural,1195,1892,1956,1091,103.38,55.78,57.66,74.44,109.0,114.0,286.0,166.0,11.0,0.56,14.67,18.20,10.33,11,287,356,202
74,test,evening,NCR G Vijay Nagar 2,1727,2479,2486,1800,100.28,72.41,72.61,91.39,127.0,115.0,258.0,195.0,10.0,0.48,6.56,18.54,1.57,12,163,461,39
75,test,evening,NCR N Gharoli,3230,5978,6205,2647,103.80,42.66,44.28,62.72,40.0,129.0,348.0,169.0,24.0,0.29,24.63,19.71,12.31,18,1528,1223,764
76,test,evening,NCR N Sharda University 2,2287,4721,4880,1715,103.37,35.14,36.33,48.03,84.0,109.0,261.0,125.0,11.0,0.31,39.49,12.48,12.17,15,1927,609,594
77,test,evening,NCR N Venice Mall,1745,2899,2949,1591,101.72,53.95,54.88,71.48,105.0,117.0,278.0,149.0,9.0,3.15,18.31,16.79,7.05,93,540,495,208
78,test,evening,NCR N sec 22/62,3033,6835,7230,2215,105.78,30.64,32.41,47.16,37.0,139.0,379.0,172.0,37.0,0.04,35.03,16.20,17.70,3,2533,1171,1280
79,test,evening,Other_clusters,135448,264244,271608,136661,102.79,50.32,51.72,70.57,105.0,126.0,311.0,173.0,17.0,0.81,18.86,19.89,9.74,2188,51212,54011,26452
80,test,evening,Sec-39,1645,2901,2982,1578,102.79,52.92,54.40,71.83,73.0,123.0,277.0,163.0,18.0,0.13,18.95,18.68,9.05,4,565,557,270
81,test,evening,Sec-57,1980,3471,3614,1875,104.12,51.88,54.02,69.12,54.0,131.0,294.0,166.0,15.0,0.30,18.54,17.04,12.04,11,670,616,435
82,test,evening,Sector 45-46,2208,3906,3989,2210,102.12,55.40,56.58,73.90,133.0,114.0,261.0,149.0,20.0,0.13,19.20,18.38,6.77,5,766,733,270
83,test,evening,None,196229,576403,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
84,test,morning,Dashrathpuri_Del_East,2037,3523,3607,2059,102.38,57.08,58.44,72.91,88.0,136.0,329.0,175.0,24.0,0.47,19.71,15.47,6.90,17,711,558,249
85,test,morning,Gurgaon Rural,1446,3438,3871,859,112.59,22.19,24.99,30.10,207.0,141.0,266.0,152.0,35.0,0.03,37.90,7.88,31.98,1,1467,305,1238
86,test,morning,NCR G Vijay Nagar 2,1845,3259,3295,2278,101.10,69.14,69.90,84.07,NaN,117.0,257.0,154.0,16.0,0.00,13.14,14.57,2.76,0,433,480,91
87,test,morning,NCR N Gharoli,2142,3713,3738,2544,100.67,68.06,68.52,87.64,172.0,134.0,339.0,206.0,18.0,0.08,10.09,19.21,2.19,3,377,718,82
88,test,morning,NCR N Sharda University 2,1047,1549,1563,1070,100.90,68.46,69.08,90.72,91.0,113.0,257.0,177.0,6.0,0.64,6.33,21.43,2.30,10,99,335,36
89,test,morning,NCR N Venice Mall,1321,2938,3053,1292,103.91,42.32,43.98,55.16,93.0,115.0,250.0,132.0,11.0,3.21,28.76,12.48,12.87,98,878,381,393
90,test,morning,NCR N sec 22/62,1304,2381,2388,1869,100.29,78.27,78.50,92.71,NaN,120.0,221.0,172.0,10.0,0.00,6.41,14.20,0.88,0,153,339,21
91,test,morning,Other_clusters,98473,197550,205099,104951,103.82,51.17,53.13,66.47,106.0,137.0,293.0,164.0,17.0,0.85,20.86,15.03,11.82,1753,42781,30833,24241
92,test,morning,Sec-39,1902,5006,5454,1658,108.95,30.40,33.12,40.47,76.0,146.0,289.0,158.0,33.0,0.09,33.44,9.97,26.00,5,1824,544,1418
93,test,morning,Sec-57,2099,5751,6304,1728,109.62,27.41,30.05,37.50,112.0,145.0,296.0,157.0,37.0,0.25,34.07,10.03,28.17,16,2148,632,1776
94,test,morning,Sector 45-46,2262,5757,6277,2069,109.03,32.96,35.94,43.95,78.0,145.0,283.0,159.0,32.0,0.14,31.50,10.90,24.41,9,1977,684,1532
95,test,morning,None,145047,427165,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
96,test,rest_evening,Dashrathpuri_Del_East,1126,1672,1693,1032,101.26,60.96,61.72,82.75,71.0,112.0,324.0,181.0,18.0,0.71,12.88,21.03,3.54,12,218,356,60
97,test,rest_evening,Gurgaon Rural,307,456,474,251,103.95,52.95,55.04,71.73,21.0,98.0,318.0,147.0,13.0,1.05,18.57,18.35,8.65,5,88,87,41
98,test,rest_evening,NCR G Vijay Nagar 2,681,887,893,647,100.68,72.45,72.94,93.95,238.0,144.0,269.0,222.0,10.0,0.11,3.70,20.60,2.24,1,33,184,20
99,test,rest_evening,NCR N Gharoli,929,1242,1252,860,100.81,68.69,69.24,92.17,334.0,113.0,300.0,239.0,13.0,0.16,4.87,22.76,2.72,2,61,285,34
100,test,rest_evening,NCR N Sharda University 2,331,453,461,295,101.77,63.99,65.12,81.34,97.0,98.0,263.0,146.0,7.0,1.95,11.06,16.05,5.64,9,51,74,26
101,test,rest_evening,NCR N Venice Mall,379,577,588,304,101.91,51.70,52.69,73.30,71.0,102.0,225.0,122.0,8.0,6.46,14.46,20.41,5.44,38,85,120,32
102,test,rest_evening,NCR N sec 22/62,555,738,743,541,100.68,72.81,73.31,89.64,NaN,99.0,362.0,190.0,12.0,0.00,7.67,16.15,2.69,0,57,120,20
103,test,rest_evening,Other_clusters,52939,83586,84672,49969,101.30,59.01,59.78,80.97,100.0,115.0,300.0,180.0,14.0,1.15,12.27,21.38,5.49,974,10390,18107,4650
104,test,rest_evening,Sec-39,465,627,636,412,101.44,64.78,65.71,83.96,32.0,122.0,327.0,173.0,11.0,0.31,11.64,18.71,4.09,2,74,119,26
105,test,rest_evening,Sec-57,525,799,816,480,102.13,58.82,60.08,75.61,78.0,135.0,358.0,178.0,10.0,1.23,14.83,16.54,8.33,10,121,135,68
106,test,rest_evening,Sector 45-46,607,964,976,605,101.24,61.99,62.76,80.53,37.0,111.0,281.0,154.0,11.0,0.41,14.14,18.34,4.92,4,138,179,48
107,test,rest_evening,None,77267,176685,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
108,test,rest_morning,Dashrathpuri_Del_East,1157,1846,1871,1016,101.35,54.30,55.04,76.22,195.0,119.0,319.0,172.0,20.0,0.86,17.42,21.65,5.51,16,326,405,103
109,test,rest_morning,Gurgaon Rural,452,821,869,338,105.85,38.90,41.17,53.62,77.0,130.0,226.0,141.0,14.0,1.27,27.50,14.50,17.61,11,239,126,153
110,test,rest_morning,NCR G Vijay Nagar 2,757,1178,1181,846,100.25,71.63,71.82,90.86,145.0,143.0,123.0,137.0,8.0,2.12,5.00,18.46,2.03,25,59,218,24
111,test,rest_morning,NCR N Gharoli,910,1338,1344,967,100.45,71.95,72.27,93.45,152.0,119.0,281.0,205.0,9.0,1.19,3.94,21.13,1.41,16,53,284,19
112,test,rest_morning,NCR N Sharda University 2,174,284,291,126,102.46,43.30,44.37,56.01,108.0,101.0,212.0,115.0,6.0,19.24,16.15,12.03,8.59,56,47,35,25
113,test,rest_morning,NCR N Venice Mall,527,979,1007,376,102.86,37.34,38.41,53.33,107.0,111.0,290.0,137.0,14.0,11.82,22.44,15.59,12.41,119,226,157,125
114,test,rest_morning,NCR N sec 22/62,415,631,633,487,100.32,76.94,77.18,95.10,181.0,111.0,192.0,166.0,7.0,0.32,3.00,17.85,1.58,2,19,113,10
115,test,rest_morning,Other_clusters,46529,79319,81041,44106,102.17,54.42,55.61,75.18,110.0,134.0,286.0,172.0,11.0,2.79,14.40,20.34,7.63,2259,11669,16483,6186
116,test,rest_morning,Sec-39,478,773,816,422,105.56,51.72,54.59,64.83,146.0,136.0,291.0,162.0,11.0,0.12,19.98,13.11,15.07,1,163,107,123
117,test,rest_morning,Sec-57,592,1145,1213,482,105.94,39.74,42.10,54.41,163.0,145.0,260.0,161.0,11.0,1.15,27.04,14.59,17.39,14,328,177,211
118,test,rest_morning,Sector 45-46,622,1099,1145,549,104.19,47.95,49.95,66.90,118.0,146.0,284.0,175.0,11.0,0.26,21.05,18.60,11.79,3,241,213,135
119,test,rest_morning,None,68609,169709,0,0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0

In [48]:
curr_session_cluseter_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour,
        CASE 
            WHEN pickup_cluster = 'NCR N Gharoli' THEN 'NCR N Gharoli'
            WHEN pickup_cluster = 'Dashrathpuri_Del_East' THEN 'Dashrathpuri_Del_East'
            WHEN pickup_cluster = 'Sec-57' THEN 'Sec-57'
            WHEN pickup_cluster = 'Sector 45-46' THEN 'Sector 45-46'
            WHEN pickup_cluster = 'NCR N sec 22/62' THEN 'NCR N sec 22/62'
            WHEN pickup_cluster = 'G Sadar Bazar' THEN 'G Sadar Bazar'
            WHEN pickup_cluster = 'Sec-39' THEN 'Sec-39'
            WHEN pickup_cluster = 'NCR N Sharda University 2' THEN 'NCR N Sharda University 2'
            WHEN pickup_cluster = 'Gurgaon Rural' THEN 'Gurgaon Rural'
            WHEN pickup_cluster = 'NCR N Venice Mall' THEN 'NCR N Venice Mall'
            WHEN pickup_cluster = 'NCR G Vijay Nagar 2' THEN 'NCR G Vijay Nagar 2'
            ELSE 'Other_clusters'
        END AS cluster_name
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        time_period,
        cluster_name,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            cluster_name,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
            and cluster_name is not null
        
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4


"""
curr_session_cluseter_df=pd.read_sql(curr_session_cluseter_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/3332967694.py:249: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_session_cluseter_df=pd.read_sql(curr_session_cluseter_query,conn)

In [49]:
curr_session_cluseter_df

,sample_category,user_type,time_period,cluster_name,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,afternoon,Dashrathpuri_Del_East,37,95,39,23,41.05,58.97,24.21,79.49,41,37,90.24,NaN,88.0,304.0,280.0,133.0,0.00,7.69,20.51,12.82,0,3,8,5
1,control,clicked_users,afternoon,Gurgaon Rural,41,142,70,21,49.30,30.00,14.79,40.00,48,41,85.42,NaN,148.0,817.0,181.0,15.0,0.00,32.86,10.00,27.14,0,23,7,19
2,control,clicked_users,afternoon,NCR G Vijay Nagar 2,9,25,11,6,44.00,54.55,24.00,81.82,12,9,75.00,NaN,92.0,440.0,338.0,19.0,0.00,9.09,27.27,9.09,0,1,3,1
3,control,clicked_users,afternoon,NCR N Gharoli,17,44,14,7,31.82,50.00,15.91,64.29,18,17,94.44,NaN,234.0,617.0,245.0,8.0,0.00,21.43,14.29,14.29,0,3,2,2
4,control,clicked_users,afternoon,NCR N Sharda University 2,54,241,136,16,56.43,11.76,6.64,19.85,60,54,90.00,134.0,114.0,174.0,123.0,29.0,1.47,51.47,8.09,27.21,2,70,11,37
5,control,clicked_users,afternoon,NCR N Venice Mall,23,86,36,11,41.86,30.56,12.79,38.89,30,23,76.67,101.0,249.0,428.0,201.0,24.0,11.11,16.67,8.33,33.33,4,6,3,12
6,control,clicked_users,afternoon,NCR N sec 22/62,16,43,13,6,30.23,46.15,13.95,61.54,18,16,88.89,NaN,71.0,4969.0,88.0,12.0,0.00,15.38,15.38,23.08,0,2,2,3
7,control,clicked_users,afternoon,Other_clusters,1190,4927,2205,654,44.75,29.66,13.27,46.12,1313,1197,91.17,166.0,157.0,331.0,195.0,23.0,2.68,23.85,16.33,27.35,59,526,360,603
8,control,clicked_users,afternoon,Sec-39,19,67,32,11,47.76,34.38,16.42,68.75,21,19,90.48,NaN,189.0,708.0,343.0,33.0,0.00,12.50,34.38,18.75,0,4,11,6
9,control,clicked_users,afternoon,Sec-57,22,49,26,9,53.06,34.62,18.37,57.69,26,22,84.62,NaN,108.0,618.0,491.0,20.0,0.00,11.54,23.08,30.77,0,3,6,8
10,control,clicked_users,afternoon,Sector 45-46,23,62,20,8,32.26,40.00,12.90,50.00,26,23,88.46,NaN,86.0,492.0,183.0,20.0,0.00,25.00,10.00,25.00,0,5,2,5
11,control,clicked_users,evening,Dashrathpuri_Del_East,37,137,54,10,39.42,18.52,7.30,37.04,41,37,90.24,NaN,204.0,670.0,253.0,37.0,0.00,37.04,18.52,25.93,0,20,10,14
12,control,clicked_users,evening,Gurgaon Rural,26,97,38,14,39.18,36.84,14.43,60.53,27,26,96.30,NaN,142.0,198.0,189.0,22.0,0.00,23.68,23.68,15.79,0,9,9,6
13,control,clicked_users,evening,NCR G Vijay Nagar 2,5,15,4,2,26.67,50.00,13.33,50.00,6,5,83.33,44.0,132.0,NaN,112.0,390.0,25.00,25.00,0.00,0.00,1,1,0,0
14,control,clicked_users,evening,NCR N Gharoli,51,274,122,13,44.53,10.66,4.74,27.87,59,52,88.14,NaN,173.0,533.0,210.0,189.0,0.00,38.52,17.21,33.61,0,47,21,41
15,control,clicked_users,evening,NCR N Sharda University 2,51,274,131,12,47.81,9.16,4.38,16.03,61,51,83.61,76.0,135.0,444.0,148.0,87.0,0.76,51.91,6.87,31.30,1,68,9,41
16,control,clicked_users,evening,NCR N Venice Mall,26,77,30,6,38.96,20.00,7.79,56.67,28,26,92.86,NaN,99.0,188.0,177.0,10.0,0.00,26.67,36.67,16.67,0,8,11,5
17,control,clicked_users,evening,NCR N sec 22/62,69,396,186,16,46.97,8.60,4.04,21.51,80,69,86.25,NaN,103.0,245.0,121.0,51.0,0.00,54.84,12.90,23.66,0,102,24,44
18,control,clicked_users,evening,Other_clusters,1577,6949,3316,667,47.72,20.11,9.60,35.80,1775,1585,89.30,190.0,167.0,395.0,194.0,41.0,1.12,31.94,15.50,31.03,37,1059,514,1029
19,control,clicked_users,evening,Sec-39,20,61,36,18,59.02,50.00,29.51,63.89,22,20,90.91,NaN,210.0,363.0,215.0,37.0,0.00,22.22,11.11,13.89,0,8,4,5
20,control,clicked_users,evening,Sec-57,22,65,32,12,49.23,37.50,18.46,46.88,26,22,84.62,NaN,216.0,485.0,246.0,37.0,0.00,21.88,9.38,31.25,0,7,3,10
21,control,clicked_users,evening,Sector 45-46,27,81,40,13,49.38,32.50,16.05,42.50,34,27,79.41,NaN,195.0,918.0,340.0,34.0,0.00,22.50,10.00,35.00,0,9,4,14
22,control,clicked_users,morning,Dashrathpuri_Del_East,29,104,45,17,43.27,37.78,16.35,48.89,32,29,90.63,NaN,177.0,721.0,248.0,53.0,0.00,28.89,11.11,22.22,0,13,5,10
23,control,clicked_users,morning,Gurgaon Rural,46,231,128,6,55.41,4.69,2.60,12.50,54,46,85.19,NaN,192.0,511.0,215.0,105.0,0.00,40.63,7.81,46.88,0,52,10,60
24,control,clicked_users,morning,NCR G Vijay Nagar 2,15,35,19,11,54.29,57.89,31.43,73.68,15,15,100.00,NaN,256.0,643.0,268.0,7.0,0.00,15.79,15.79,10.53,0,3,3,2
25,control,clicked_users,morning,NCR N Gharoli,23,76,34,14,44.74,41.18,18.42,55.88,28,23,82.14,NaN,145.0,347.0,148.0,19.0,0.00,32.35,14.71,11.76,0,11,5,4
26,control,clicked_users,morning,NCR N Sharda University 2,7,18,9,1,50.00,11.11,5.56,66.67,7,7,100.00,NaN,134.0,446.0,299.0,110.0,0.00,22.22,55.56,11.11,0,2,5,1
27,control,clicked_users,morning,NCR N Venice Mall,34,198,110,12,55.56,10.91,6.06,17.27,40,34,85.00,194.0,136.0,458.0,154.0,141.0,8.18,47.27,6.36,27.27,9,52,7,30
28,control,clicked_users,morning,NCR N sec 22/62,20,47,22,13,46.81,59.09,27.66,68.18,22,20,90.91,NaN,182.0,86.0,179.0,12.0,0.00,27.27,9.09,4.55,0,6,2,1
29,control,clicked_users,morning,Other_clusters,1140,5689,2809,431,49.38,15.34,7.58,25.60,1318,1153,87.48,235.0,155.0,336.0,174.0,63.0,1.28,38.45,10.22,34.67,36,1080,287,974
30,control,clicked_users,morning,Sec-39,40,272,156,12,57.35,7.69,4.41,16.03,45,40,88.89,NaN,182.0,294.0,189.0,176.0,0.00,48.08,8.33,35.90,0,75,13,56
31,control,clicked_users,morning,Sec-57,67,381,244,15,64.04,6.15,3.94,9.02,88,70,79.55,NaN,129.0,321.0,134.0,98.0,0.00,31.97,2.87,59.02,0,78,7,144
32,control,clicked_users,morning,Sector 45-46,51,291,169,11,58.08,6.51,3.78,13.02,60,51,85.00,NaN,138.0,190.0,143.0,92.0,0.00,37.28,6.51,49.70,0,63,11,84
33,control,clicked_users,rest_evening,Dashrathpuri_Del_East,15,39,15,4,38.46,26.67,10.26,53.33,17,15,88.24,227.0,225.0,146.0,193.0,48.0,20.00,6.67,26.67,20.00,3,1,4,3
34,control,clicked_users,rest_evening,Gurgaon Rural,3,6,6,3,100.00,50.00,50.00,50.00,3,3,100.00,NaN,NaN,NaN,NaN,10.0,0.00,0.00,0.00,50.00,0,0,0,3
35,control,clicked_users,rest_evening,NCR G Vijay Nagar 2,5,11,4,0,36.36,0.00,0.00,75.00,5,5,100.00,NaN,93.0,335.0,222.0,74.0,0.00,25.00,75.00,0.00,0,1,3,0
36,control,clicked_users,rest_evening,NCR N Gharoli,7,16,9,5,56.25,55.56,31.25,77.78,8,7,87.50,NaN,26.0,321.0,216.0,41.0,0.00,22.22,22.22,0.00,0,2,2,0
37,control,clicked_users,rest_evening,NCR N Sharda University 2,1,1,0,0,0.00,0.00,0.00,0.00,1,1,100.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
38,control,clicked_users,rest_evening,NCR N Venice Mall,5,8,5,3,62.50,60.00,37.50,60.00,5,5,100.00,NaN,200.0,NaN,200.0,9.0,0.00,20.00,0.00,20.00,0,1,0,1
39,control,clicked_users,rest_evening,NCR N sec 22/62,5,11,4,3,36.36,75.00,27.27,75.00,5,5,100.00,NaN,312.0,NaN,312.0,448.0,0.00,25.00,0.00,0.00,0,1,0,0
40,control,clicked_users,rest_evening,Other_clusters,419,1470,692,209,47.07,30.20,14.22,49.13,472,420,88.98,88.0,149.0,214.0,158.0,24.0,2.17,25.29,18.35,23.41,15,175,127,162
41,control,clicked_users,rest_evening,Sec-39,4,9,7,3,77.78,42.86,33.33,42.86,5,4,80.00,NaN,173.0,NaN,173.0,62.0,0.00,14.29,0.00,42.86,0,1,0,3
42,control,clicked_users,rest_evening,Sec-57,5,9,4,3,44.44,75.00,33.33,75.00,5,5,100.00,NaN,NaN,NaN,NaN,36.0,0.00,0.00,0.00,25.00,0,0,0,1
43,control,clicked_users,rest_evening,Sector 45-46,5,6,4,2,66.67,50.00,33.33,50.00,6,5,83.33,NaN,NaN,NaN,NaN,67.0,0.00,0.00,0.00,50.00,0,0,0,2
44,control,clicked_users,rest_morning,Dashrathpuri_Del_East,10,36,13,2,36.11,15.38,5.56,53.85,12,10,83.33,NaN,128.0,643.0,639.0,310.0,0.00,7.69,38.46,38.46,0,1,5,5
45,control,clicked_users,rest_morning,Gurgaon Rural,9,22,11,4,50.00,36.36,18.18,45.45,10,9,90.00,NaN,169.0,429.0,242.0,210.0,0.00,36.36,9.09,18.18,0,4,1,2
46,control,clicked_users,rest_morning,NCR G Vijay Nagar 2,8,26,17,6,65.38,35.29,23.08,52.94,10,8,80.00,182.0,178.0,676.0,258.0,9.0,23.53,17.65,17.65,5.88,4,3,3,1
47,control,clicked_users,rest_morning,NCR N Gharoli,6,16,3,1,18.75,33.33,6.25,100.00,6,6,100.00,NaN,NaN,629.0,629.0,251.0,0.00,0.00,66.67,0.00,0,0,2,0
48,control,clicked_users,rest_morning,NCR N Sharda University 2,3,7,3,0,42.86,0.00,0.00,0.00,4,3,75.00,NaN,104.0,NaN,104.0,NaN,0.00,66.67,0.00,33.33,0,2,0,1
49,control,clicked_users,rest_morning,NCR N Venice Mall,14,53,21,4,39.62,19.05,7.55,47.62,17,14,82.35,226.0,11.0,440.0,226.0,6.0,14.29,9.52,28.57,28.57,3,2,6,6
50,control,clicked_users,rest_morning,NCR N sec 22/62,2,5,2,0,40.00,0.00,0.00,50.00,2,2,100.00,NaN,NaN,763.0,763.0,23.0,0.00,0.00,50.00,50.00,0,0,1,1
51,control,clicked_users,rest_morning,Other_clusters,443,1600,801,157,50.06,19.60,9.81,35.08,504,447,88.69,180.0,173.0,322.0,193.0,25.0,5.62,25.22,15.23,34.08,45,202,122,273
52,control,clicked_users,rest_morning,Sec-39,9,23,16,0,69.57,0.00,0.00,6.25,9,9,100.00,NaN,180.0,208.0,193.0,4.0,0.00,18.75,6.25,75.00,0,3,1,12
53,control,clicked_users,rest_morning,Sec-57,13,44,27,3,61.36,11.11,6.82,18.52,14,13,92.86,147.0,127.0,108.0,128.0,16.0,14.81,33.33,7.41,33.33,4,9,2,9
54,control,clicked_users,rest_morning,Sector 45-46,5,16,10,0,62.50,0.00,0.00,40.00,6,5,83.33,171.0,NaN,38.0,138.0,9.0,30.00,0.00,30.00,30.00,3,0,3,3
55,control,None,afternoon,Dashrathpuri_Del_East,6397,18406,5748,3767,31.23,65.54,20.47,84.39,2378,0,0.00,118.0,118.0,326.0,176.0,14.0,0.28,11.24,18.56,4.09,16,646,1067,235
56,control,None,afternoon,Gurgaon Rural,2843,8812,3503,1608,39.75,45.90,18.25,62.23,1509,0,0.00,92.0,130.0,310.0,162.0,23.0,0.23,23.84,16.13,13.70,8,835,565,480
57,control,None,afternoon,NCR G Vijay Nagar 2,4299,10565,3537,2825,33.48,79.87,26.74,96.52,994,0,0.00,118.0,117.0,265.0,221.0,8.0,0.08,2.63,16.23,0.76,3,93,574,27
58,control,None,afternoon,NCR N Gharoli,5810,14949,4834,3544,32.34,73.31,23.71,92.80,1444,0,0.00,90.0,111.0,294.0,218.0,10.0,0.10,4.49,19.03,2.61,5,217,920,126
59,control,None,afternoon,NCR N Sharda University 2,4578,14503,5901,3010,40.69,51.01,20.75,66.90,1804,0,0.00,70.0,111.0,238.0,133.0,9.0,0.39,24.96,15.23,7.74,23,1473,899,457
60,control,None,afternoon,NCR N Venice Mall,3046,8745,3372,2062,38.56,61.15,23.58,79.69,1000,0,0.00,87.0,113.0,267.0,156.0,7.0,2.37,12.37,17.67,5.55,80,417,596,187
61,control,None,afternoon,NCR N sec 22/62,3587,8709,3152,2435,36.19,77.25,27.96,92.45,1025,0,0.00,89.0,96.0,267.0,177.0,10.0,0.03,5.93,14.78,1.59,1,187,466,50
62,control,None,afternoon,Other_clusters,235111,849153,281183,181180,33.11,64.43,21.34,83.90,73708,0,0.00,111.0,119.0,296.0,181.0,11.0,0.83,10.17,19.07,5.10,2340,28605,53613,14332
63,control,None,afternoon,Sec-39,2666,7124,2876,1825,40.37,63.46,25.62,83.21,1157,0,0.00,152.0,115.0,310.0,189.0,13.0,0.07,11.23,19.65,5.49,2,323,565,158
64,control,None,afternoon,Sec-57,3316,9391,3667,2386,39.05,65.07,25.41,84.32,1488,0,0.00,123.0,125.0,263.0,170.0,11.0,0.46,10.77,19.01,4.45,17,395,697,163
65,control,None,afternoon,Sector 45-46,2919,7513,2909,2056,38.72,70.68,27.37,88.97,1252,0,0.00,109.0,94.0,227.0,153.0,12.0,0.24,8.01,18.18,2.78,7,233,529,81
66,control,None,evening,Dashrathpuri_Del_East,4880,14255,4372,2314,30.67,52.93,16.23,74.34,1988,0,0.00,135.0,113.0,337.0,163.0,17.0,0.30,17.06,21.16,8.21,13,746,925,359
67,control,None,evening,Gurgaon Rural,1918,5166,1964,1107,38.02,56.36,21.43,75.25,832,0,0.00,22.0,131.0,277.0,171.0,11.0,0.05,16.09,18.28,8.50,1,316,359,167
68,control,None,evening,NCR G Vijay Nagar 2,3241,8059,2572,1867,31.91,72.59,23.17,91.84,857,0,0.00,73.0,106.0,341.0,219.0,10.0,0.08,6.42,18.66,1.67,2,165,480,43
69,control,None,evening,NCR N Gharoli,5422,16912,5916,2524,34.98,42.66,14.92,62.68,2199,0,0.00,90.0,131.0,367.0,174.0,24.0,0.17,24.48,19.74,12.61,10,1448,1168,746
70,control,None,evening,NCR N Sharda University 2,3233,11675,4979,1699,42.65,34.12,14.55,46.76,1531,0,0.00,91.0,117.0,306.0,136.0,12.0,0.76,39.77,12.21,12.71,38,1980,608,633
71,control,None,evening,NCR N Venice Mall,2737,8086,3129,1638,38.70,52.35,20.26,71.97,1033,0,0.00,99.0,108.0,276.0,155.0,10.0,2.30,18.25,18.73,7.48,72,571,586,234
72,control,None,evening,NCR N sec 22/62,4452,16729,6770,2313,40.47,34.17,13.83,50.58,2396,0,0.00,124.0,137.0,387.0,171.0,33.0,0.07,33.25,16.03,16.04,5,2251,1085,1086
73,control,None,evening,Other_clusters,211062,785791,273856,139029,34.85,50.77,17.69,70.91,85240,0,0.00,105.0,126.0,307.0,170.0,17.0,0.84,18.75,19.78,9.47,2312,51353,54158,25936
74,control,None,evening,Sec-39,2597,8000,3261,1659,40.76,50.87,20.74,71.45,1424,0,0.00,22.0,120.0,291.0,164.0,18.0,0.28,20.55,20.27,7.73,9,670,661,252
75,control,None,evening,Sec-57,2817,8814,3548,1904,40.25,53.66,21.60,70.41,1502,0,0.00,66.0,129.0,289.0,167.0,16.0,0.25,18.52,16.66,10.82,9,657,591,384
76,control,None,evening,Sector 45-46,3159,9501,3915,2225,41.21,56.83,23.42,75.20,1783,0,0.00,218.0,115.0,274.0,163.0,23.0,0.15,18.49,18.26,6.16,6,724,715,241
77,control,None,morning,Dashrathpuri_Del_East,3758,11908,3930,2308,33.00,58.73,19.38,74.43,1703,0,0.00,114.0,137.0,324.0,180.0,21.0,0.48,18.80,15.47,6.28,19,739,608,247
78,control,None,morning,Gurgaon Rural,2222,9505,4177,915,43.95,21.91,9.63,29.54,1569,0,0.00,84.0,136.0,319.0,146.0,41.0,0.05,39.07,7.54,31.34,2,1632,315,1309
79,control,None,morning,NCR G Vijay Nagar 2,2942,9183,3307,2276,36.01,68.82,24.78,84.37,1193,0,0.00,NaN,133.0,232.0,164.0,17.0,0.00,12.10,15.27,3.54,0,400,505,117
80,control,None,morning,NCR N Gharoli,3708,10632,3766,2630,35.42,69.84,24.74,88.34,1270,0,0.00,76.0,113.0,347.0,204.0,16.0,0.05,9.11,18.16,2.50,2,343,684,94
81,control,None,morning,NCR N Sharda University 2,1613,3987,1537,1077,38.55,70.07,27.01,90.44,480,0,0.00,43.0,95.0,219.0,143.0,6.0,0.46,7.81,19.65,1.30,7,120,302,20
82,control,None,morning,NCR N Venice Mall,1926,7541,3184,1295,42.22,40.67,17.17,54.30,955,0,0.00,71.0,112.0,220.0,125.0,11.0,2.89,31.03,12.91,11.78,92,988,411,375
83,control,None,morning,NCR N sec 22/62,1983,5721,2432,1875,42.51,77.10,32.77,91.65,796,0,0.00,NaN,120.0,288.0,198.0,11.0,0.00,7.44,13.90,0.90,0,181,338,22
84,control,None,morning,Other_clusters,152911,576050,208189,107365,36.14,51.57,18.64,67.10,66583,0,0.00,113.0,136.0,287.0,162.0,16.0,0.89,20.43,15.29,11.59,1846,42527,31832,24129
85,control,None,morning,Sec-39,2737,12358,5646,1752,45.69,31.03,14.18,41.66,1963,0,0.00,98.0,147.0,346.0,166.0,37.0,0.14,32.02,10.54,26.18,8,1808,595,1478
86,control,None,morning,Sec-57,2830,13731,6390,1871,46.54,29.28,13.63,40.36,2150,0,0.00,114.0,147.0,314.0,165.0,35.0,0.08,33.02,11.00,26.54,5,2110,703,1696
87,control,None,morning,Sector 45-46,3080,14273,6393,2188,44.79,34.22,15.33,45.47,2208,0,0.00,158.0,135.0,297.0,151.0,38.0,0.11,30.61,11.22,23.81,7,1957,717,1522
88,control,None,rest_evening,Dashrathpuri_Del_East,2095,5048,1599,973,31.68,60.85,19.27,85.12,718,0,0.00,154.0,110.0,414.0,227.0,18.0,0.94,10.13,23.89,3.75,15,162,382,60
89,control,None,rest_evening,Gurgaon Rural,587,1312,495,273,37.73,55.15,20.81,72.53,235,0,0.00,6.0,121.0,308.0,159.0,14.0,0.20,17.58,16.77,9.70,1,87,83,48
90,control,None,rest_evening,NCR G Vijay Nagar 2,1300,2740,909,638,33.18,70.19,23.28,89.33,291,0,0.00,177.0,109.0,234.0,165.0,10.0,1.10,6.82,18.70,2.75,10,62,170,25
91,control,None,rest_evening,NCR N Gharoli,1895,4103,1243,833,30.29,67.02,20.30,90.91,430,0,0.00,71.0,97.0,296.0,228.0,13.0,0.32,5.23,23.01,3.46,4,65,286,43
92,control,None,rest_evening,NCR N Sharda University 2,604,1288,466,294,36.18,63.09,22.83,82.83,159,0,0.00,115.0,92.0,234.0,145.0,7.0,2.15,11.37,17.81,3.43,10,53,83,16
93,control,None,rest_evening,NCR N Venice Mall,746,1711,641,332,37.46,51.79,19.40,76.29,230,0,0.00,92.0,129.0,251.0,172.0,8.0,4.99,11.39,23.71,7.33,32,73,152,47
94,control,None,rest_evening,NCR N sec 22/62,988,2137,790,577,36.97,73.04,27.00,91.27,307,0,0.00,36.0,125.0,286.0,192.0,12.0,0.25,6.58,17.34,1.90,2,52,137,15
95,control,None,rest_evening,Other_clusters,89765,248729,85633,50761,34.43,59.28,20.41,81.07,27507,0,0.00,107.0,116.0,300.0,179.0,15.0,1.20,12.30,21.18,5.34,1024,10531,18134,4574
96,control,None,rest_evening,Sec-39,805,1831,710,431,38.78,60.70,23.54,83.10,335,0,0.00,59.0,118.0,332.0,178.0,12.0,0.56,12.54,21.83,3.66,4,89,155,26
97,control,None,rest_evening,Sec-57,862,1994,814,483,40.82,59.34,24.22,77.27,386,0,0.00,69.0,106.0,361.0,153.0,11.0,1.35,15.11,17.20,6.02,11,123,140,49
98,control,None,rest_evening,Sector 45-46,983,2483,1033,629,41.60,60.89,25.33,81.32,451,0,0.00,85.0,119.0,228.0,173.0,13.0,0.39,14.62,20.43,3.68,4,151,211,38
99,control,None,rest_morning,Dashrathpuri_Del_East,2127,5766,2024,1077,35.10,53.21,18.68,74.36,782,0,0.00,108.0,132.0,387.0,183.0,20.0,1.24,19.27,20.80,5.14,25,390,421,104
100,control,None,rest_morning,Gurgaon Rural,722,1899,897,356,47.24,39.69,18.75,54.63,434,0,0.00,98.0,156.0,294.0,184.0,15.0,0.33,25.98,14.60,19.06,3,233,131,171
101,control,None,rest_morning,NCR G Vijay Nagar 2,1260,2858,1077,811,37.68,75.30,28.38,92.94,307,0,0.00,94.0,117.0,171.0,152.0,8.0,0.74,4.92,16.99,1.39,8,53,183,15
102,control,None,rest_morning,NCR N Gharoli,1689,4018,1315,914,32.73,69.51,22.75,92.17,378,0,0.00,127.0,134.0,301.0,202.0,9.0,1.29,4.56,21.90,1.98,17,60,288,26
103,control,None,rest_morning,NCR N Sharda University 2,364,810,231,134,28.52,58.01,16.54,76.62,91,0,0.00,102.0,129.0,260.0,153.0,6.0,8.66,7.36,17.32,7.36,20,17,40,17
104,control,None,rest_morning,NCR N Venice Mall,853,2583,1102,408,42.66,37.02,15.80,51.27,362,0,0.00,116.0,100.0,251.0,124.0,10.0,14.70,21.23,13.79,12.79,162,234,152,141
105,control,None,rest_morning,NCR N sec 22/62,803,1921,678,517,35.29,76.25,26.91,94.40,199,0,0.00,88.0,133.0,217.0,195.0,7.0,1.03,3.24,17.70,1.33,7,22,120,9
106,control,None,rest_morning,Other_clusters,76882,238648,82701,45535,34.65,55.06,19.08,75.82,24470,0,0.00,107.0,130.0,258.0,159.0,12.0,2.93,14.07,20.34,7.18,2420,11636,16819,5936
107,control,None,rest_morning,Sec-39,800,2148,1026,487,47.77,47.47,22.67,62.77,398,0,0.00,69.0,148.0,259.0,165.0,12.0,0.97,18.23,15.11,18.03,10,187,155,185
108,control,None,rest_morning,Sec-57,855,2389,1094,474,45.79,43.33,19.84,57.22,450,0,0.00,132.0,119.0,292.0,139.0,11.0,2.74,23.67,13.25,16.36,30,259,145,179
109,control,None,rest_morning,Sector 45-46,894,2366,1030,521,43.53,50.58,22.02,65.92,453,0,0.00,90.0,139.0,299.0,161.0,11.0,0.68,18.74,15.24,14.66,7,193,157,151
110,test,clicked_users,afternoon,Dashrathpuri_Del_East,21,66,19,7,28.79,36.84,10.61,57.89,23,21,91.30,NaN,134.0,498.0,215.0,9.0,0.00,26.32,21.05,15.79,0,5,4,3
111,test,clicked_users,afternoon,Gurgaon Rural,33,156,85,20,54.49,23.53,12.82,35.29,37,33,89.19,NaN,143.0,453.0,169.0,80.0,0.00,38.82,11.76,25.88,0,33,10,22
112,test,clicked_users,afternoon,NCR G Vijay Nagar 2,9,35,13,7,37.14,53.85,20.00,53.85,11,10,90.91,NaN,182.0,NaN,182.0,6.0,0.00,23.08,0.00,23.08,0,3,0,3
113,test,clicked_users,afternoon,NCR N Gharoli,20,55,23,10,41.82,43.48,18.18,73.91,23,20,86.96,NaN,253.0,244.0,248.0,11.0,0.00,8.70,30.43,17.39,0,2,7,4
114,test,clicked_users,afternoon,NCR N Sharda University 2,74,359,208,17,57.94,8.17,4.74,15.38,83,75,90.36,171.0,127.0,460.0,137.0,40.0,1.92,62.98,7.21,19.71,4,131,15,41
115,test,clicked_users,afternoon,NCR N Venice Mall,24,77,36,15,46.75,41.67,19.48,50.00,26,24,92.31,NaN,164.0,836.0,190.0,10.0,0.00,30.56,8.33,19.44,0,11,3,7
116,test,clicked_users,afternoon,NCR N sec 22/62,14,45,16,6,35.56,37.50,13.33,50.00,15,14,93.33,NaN,68.0,245.0,219.0,24.0,0.00,12.50,12.50,37.50,0,2,2,6
117,test,clicked_users,afternoon,Other_clusters,911,3794,1797,537,47.36,29.88,14.15,46.74,1016,919,90.45,129.0,150.0,373.0,180.0,17.0,3.51,24.21,16.81,25.54,63,435,302,459
118,test,clicked_users,afternoon,Sec-39,18,50,23,9,46.00,39.13,18.00,47.83,21,18,85.71,NaN,211.0,1438.0,322.0,12.0,0.00,13.04,8.70,39.13,0,3,2,9
119,test,clicked_users,afternoon,Sec-57,19,38,14,9,36.84,64.29,23.68,85.71,20,19,95.00,NaN,149.0,3131.0,2155.0,314.0,0.00,7.14,21.43,7.14,0,1,3,1
120,test,clicked_users,afternoon,Sector 45-46,15,29,12,7,41.38,58.33,24.14,91.67,16,15,93.75,NaN,NaN,627.0,627.0,492.0,0.00,0.00,33.33,8.33,0,0,4,1
121,test,clicked_users,evening,Dashrathpuri_Del_East,14,50,15,6,30.00,40.00,12.00,60.00,17,14,82.35,NaN,132.0,702.0,266.0,119.0,0.00,33.33,20.00,6.67,0,5,3,1
122,test,clicked_users,evening,Gurgaon Rural,11,21,8,3,38.10,37.50,14.29,87.50,13,11,84.62,NaN,NaN,359.0,359.0,10.0,0.00,0.00,50.00,12.50,0,0,4,1

In [50]:
curr_session_cluseter_df.to_csv('curr_session_cluseter_df.csv',index=False)

In [52]:
curr_overall_segment_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-05'
    
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        segment.ltr_segment,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        segment
        ON exp_category.customer_id=segment.customer_id
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        ltr_segment,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            ltr_segment,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
curr_overall_segment_df=pd.read_sql(curr_overall_segment_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/3858488940.py:244: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_overall_segment_df=pd.read_sql(curr_overall_segment_query,conn)

In [69]:
curr_overall_segment_df.to_csv('curr_overall_segment_df.csv',index=False)

In [53]:
curr_overall_segment_df

,sample_category,user_type,ltr_segment,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,HH,636,4256,1886,364,44.31,19.30,8.55,35.21,699,638,91.27,165,166,474,208,39,3.45,27.78,15.85,33.46,65,524,299,631
1,control,clicked_users,PHH,2513,18101,9026,1952,49.86,21.63,10.78,35.44,2814,2528,89.84,165,155,297,175,36,1.34,33.88,13.65,29.33,121,3058,1232,2647
2,control,clicked_users,UNKNOWN,114,696,316,28,45.40,8.86,4.02,21.52,127,115,90.55,189,162,634,196,151,4.11,25.63,12.66,48.73,13,81,40,154
3,control,clicked_users,None,260,1930,782,166,40.52,21.23,8.60,32.99,278,262,94.24,224,163,595,219,65,3.45,20.97,11.51,42.46,27,164,90,332
4,control,None,HH,100337,463794,121378,65571,26.17,54.02,14.14,75.18,23573,0,0.00,118,140,344,191,13,1.39,14.17,20.70,9.24,1688,17197,25129,11214
5,control,None,PHH,347693,2320750,892466,504646,38.46,56.55,21.74,74.50,157542,0,0.00,107,126,291,166,14,0.88,16.53,17.62,8.07,7876,147511,157256,72039
6,control,None,UNKNOWN,14813,72328,18158,5850,25.11,32.22,8.09,68.87,3513,0,0.00,88,116,142,122,12,3.27,15.17,36.07,12.65,594,2754,6550,2297
7,control,None,None,40583,207724,39443,21937,18.99,55.62,10.56,77.83,6393,0,0.00,115,143,403,221,12,1.61,11.10,21.42,9.41,635,4380,8449,3713
8,test,clicked_users,HH,519,3703,1652,305,44.61,18.46,8.24,31.66,563,526,93.43,139,168,526,194,39,4.06,28.45,13.01,35.84,67,470,215,592
9,test,clicked_users,PHH,2319,18068,9470,1867,52.41,19.71,10.33,32.30,2601,2335,89.77,120,154,356,177,35,1.38,36.30,12.45,30.01,131,3438,1179,2842
10,test,clicked_users,UNKNOWN,95,588,263,16,44.73,6.08,2.72,17.87,107,96,89.72,78,178,328,186,82,5.70,27.38,11.79,49.05,15,72,31,129
11,test,clicked_users,None,108,886,350,61,39.50,17.43,6.88,29.43,120,109,90.83,173,157,479,208,36,4.86,25.43,12.00,40.29,17,89,42,141
12,test,None,HH,98445,452785,118304,64226,26.13,54.29,14.18,75.51,11710,0,0.00,114,139,353,196,13,1.37,13.85,20.71,9.23,1626,16385,24497,10918
13,test,None,PHH,339876,2261275,870896,492363,38.51,56.54,21.77,74.60,89296,0,0.00,106,125,289,168,14,0.86,16.51,17.73,8.02,7447,143746,154404,69859
14,test,None,UNKNOWN,14523,69956,17077,5641,24.41,33.03,8.06,67.93,1736,0,0.00,100,133,245,165,12,2.85,15.79,34.26,13.37,487,2697,5851,2283
15,test,None,None,40172,204719,39779,21911,19.43,55.08,10.70,77.03,1628,0,0.00,96,143,396,215,13,1.54,11.47,21.18,9.93,611,4561,8427,3951

In [79]:
curr_overall_retention_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-05'
    
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        segment.retention_segment,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        segment
        ON exp_category.customer_id=segment.customer_id
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        retention_segment,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            retention_segment,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
curr_overall_retention_df=pd.read_sql(curr_overall_retention_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/3862842824.py:244: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_overall_retention_df=pd.read_sql(curr_overall_retention_query,conn)

In [81]:
curr_overall_retention_df.to_csv('curr_overall_retention_only_df.csv',index=False)

In [80]:
curr_overall_retention_df

,sample_category,user_type,retention_segment,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,DORMANT,455,2781,1253,210,45.06,16.76,7.55,32.24,485,455,93.81,172,175,457,208,55,2.47,30.97,15.24,34.32,31,388,191,430
1,control,clicked_users,ELITE,582,5429,2784,679,51.28,24.39,12.51,37.54,686,586,85.42,173,155,282,175,38,1.08,35.49,13.00,25.90,30,988,362,721
2,control,clicked_users,GOLD,570,3601,1741,408,48.35,23.43,11.33,36.47,618,573,92.72,145,172,409,197,36,1.32,32.51,12.81,29.70,23,566,223,517
3,control,clicked_users,HH,358,2475,1101,231,44.48,20.98,9.33,37.15,399,359,89.97,189,169,464,210,45,3.27,26.79,16.17,32.61,36,295,178,359
4,control,clicked_users,INACTIVE,221,1254,572,94,45.61,16.43,7.50,30.24,239,222,92.89,151,155,399,199,41,2.97,28.67,13.64,38.11,17,164,78,218
5,control,clicked_users,PLATINUM,600,4440,2330,453,52.48,19.44,10.20,34.08,678,606,89.38,112,136,226,145,25,1.20,34.85,14.55,29.83,28,812,339,695
6,control,clicked_users,PRIME,35,344,154,42,44.77,27.27,12.21,44.16,41,36,87.80,89,132,324,145,23,1.95,35.06,16.88,18.83,3,54,26,29
7,control,clicked_users,SILVER,328,2033,977,199,48.06,20.37,9.79,34.29,367,329,89.65,205,169,330,187,47,1.84,32.24,13.72,31.63,18,315,134,309
8,control,clicked_users,UNKNOWN,114,696,316,28,45.40,8.86,4.02,21.52,127,115,90.55,189,162,615,195,152,4.11,25.63,12.66,48.73,13,81,40,154
9,control,clicked_users,None,260,1930,782,166,40.52,21.23,8.60,32.99,278,262,94.24,223,164,596,219,66,3.45,20.97,11.51,42.46,27,164,90,332
10,control,None,DORMANT,79817,308966,84835,42148,27.46,49.68,13.64,71.56,18931,0,0.00,123,136,339,187,13,1.31,16.53,21.38,10.57,1115,14019,18139,8969
11,control,None,ELITE,62709,744332,335577,196683,45.08,58.61,26.42,75.51,49181,0,0.00,99,120,270,156,15,0.74,16.57,16.62,7.16,2489,55618,55770,24029
12,control,None,GOLD,79104,447371,160137,89587,35.80,55.94,20.03,74.30,31288,0,0.00,107,131,309,175,13,1.00,16.20,18.00,8.48,1603,25949,28832,13585
13,control,None,HH,52719,275278,78986,44751,28.69,56.66,16.26,76.01,15015,0,0.00,120,138,343,187,13,1.25,14.25,18.92,8.47,988,11259,14948,6689
14,control,None,INACTIVE,43587,176742,40442,20171,22.88,49.88,11.41,73.12,8247,0,0.00,122,140,350,197,13,1.37,14.84,22.72,10.64,554,6002,9189,4305
15,control,None,PLATINUM,76930,553938,221481,123274,39.98,55.66,22.25,73.85,40181,0,0.00,111,126,289,167,14,0.87,17.09,17.86,8.18,1924,37862,39558,18117
16,control,None,PRIME,3519,53415,20595,13209,38.56,64.14,24.73,79.17,3113,0,0.00,102,122,264,158,14,0.70,14.91,14.76,5.22,145,3070,3040,1075
17,control,None,SILVER,49645,224502,71791,40394,31.98,56.27,17.99,74.69,15159,0,0.00,119,134,322,180,13,1.04,15.22,17.98,9.03,746,10929,12909,6484
18,control,None,UNKNOWN,14813,72328,18158,5850,25.11,32.22,8.09,68.87,3513,0,0.00,88,116,142,122,11,3.27,15.17,36.07,12.65,594,2754,6550,2297
19,control,None,None,40583,207724,39443,21937,18.99,55.62,10.56,77.83,6393,0,0.00,115,144,404,222,13,1.61,11.10,21.42,9.41,635,4380,8449,3713
20,test,clicked_users,DORMANT,273,1596,775,87,48.56,11.23,5.45,24.26,295,274,92.88,182,164,340,187,49,0.77,37.03,13.03,37.94,6,287,101,294
21,test,clicked_users,ELITE,686,6297,3451,753,54.80,21.82,11.96,34.71,802,692,86.28,80,155,313,172,30,1.13,37.35,12.72,26.80,39,1289,439,925
22,test,clicked_users,GOLD,508,3757,1849,357,49.21,19.31,9.50,32.29,563,515,91.47,130,154,421,182,37,1.35,34.83,12.87,31.53,25,644,238,583
23,test,clicked_users,HH,354,2653,1168,241,44.03,20.63,9.08,34.76,384,358,93.23,140,161,533,193,33,4.37,27.31,13.87,33.56,51,319,162,392
24,test,clicked_users,INACTIVE,148,937,437,59,46.64,13.50,6.30,23.34,162,150,92.59,115,186,472,206,91,4.35,29.29,9.84,43.02,19,128,43,188
25,test,clicked_users,PLATINUM,587,4502,2413,474,53.60,19.64,10.53,31.83,649,590,90.91,142,144,402,163,35,1.53,37.17,12.02,29.47,37,897,290,711
26,test,clicked_users,PRIME,42,513,200,60,38.99,30.00,11.70,45.50,47,42,89.36,185,204,372,230,47,1.50,32.00,15.50,21.00,3,64,31,42
27,test,clicked_users,SILVER,240,1516,829,141,54.68,17.01,9.30,27.99,262,240,91.60,176,178,424,208,53,2.17,33.78,10.86,36.07,18,280,90,299
28,test,clicked_users,UNKNOWN,95,588,263,16,44.73,6.08,2.72,17.87,107,96,89.72,77,180,332,186,81,5.70,27.38,11.79,49.05,15,72,31,129
29,test,clicked_users,None,108,886,350,61,39.50,17.43,6.88,29.43,120,109,90.83,173,159,480,205,35,4.86,25.43,12.00,40.29,17,89,42,141
30,test,None,DORMANT,78461,304926,83819,41619,27.49,49.65,13.65,71.73,7509,0,0.00,125,137,326,190,13,1.29,16.39,21.61,10.55,1081,13740,18115,8845
31,test,None,ELITE,60757,717568,326193,190681,45.46,58.46,26.57,75.59,31063,0,0.00,92,120,267,158,14,0.67,16.53,16.84,7.20,2178,53935,54931,23479
32,test,None,GOLD,77496,439543,156728,87569,35.66,55.87,19.92,74.38,17406,0,0.00,112,130,312,175,13,1.03,16.27,18.16,8.30,1609,25503,28457,13007
33,test,None,HH,52052,269300,76995,44222,28.59,57.43,16.42,76.83,8621,0,0.00,118,136,359,195,13,1.18,13.66,18.94,8.30,908,10520,14584,6393
34,test,None,INACTIVE,42397,170833,39577,19547,23.17,49.39,11.44,72.67,2960,0,0.00,101,142,333,195,13,1.51,14.68,22.68,11.12,598,5809,8976,4400
35,test,None,PLATINUM,75288,537891,215322,120231,40.03,55.84,22.35,73.90,23200,0,0.00,102,125,284,165,14,0.87,17.11,17.73,8.10,1877,36834,38185,17451
36,test,None,PRIME,3506,54635,20479,13090,37.48,63.92,23.96,79.26,2041,0,0.00,102,119,262,154,14,0.65,15.29,15.11,4.80,133,3132,3094,982
37,test,None,SILVER,48364,219364,70087,39630,31.95,56.54,18.07,74.91,8207,0,0.00,120,133,328,183,13,0.98,15.21,17.92,8.87,689,10658,12559,6220
38,test,None,UNKNOWN,14523,69956,17077,5641,24.41,33.03,8.06,67.93,1736,0,0.00,101,133,245,167,12,2.85,15.79,34.26,13.37,487,2697,5851,2283
39,test,None,None,40172,204719,39779,21911,19.43,55.08,10.70,77.03,1628,0,0.00,95,143,393,215,13,1.54,11.47,21.18,9.93,611,4561,8427,3951

In [67]:
curr_overall_retention_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-05'
    
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        segment.retention_segment,
        segment.ltr_segment,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        segment
        ON exp_category.customer_id=segment.customer_id
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        ltr_segment,
        retention_segment,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            ltr_segment,
            retention_segment,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4


"""
curr_overall_retention_df=pd.read_sql(curr_overall_retention_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/3543502264.py:247: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_overall_retention_df=pd.read_sql(curr_overall_retention_query,conn)

In [68]:
curr_overall_retention_df

,sample_category,user_type,ltr_segment,retention_segment,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,HH,DORMANT,162,1029,444,79,43.15,17.79,7.68,33.78,172,162,94.19,135,172,599,210,30,3.15,29.05,15.99,34.01,14,129,71,151
1,control,clicked_users,HH,HH,358,2475,1101,231,44.48,20.98,9.33,37.15,399,359,89.97,189,168,464,211,45,3.27,26.79,16.17,32.61,36,295,178,359
2,control,clicked_users,HH,INACTIVE,116,752,341,54,45.35,15.84,7.18,30.79,128,117,91.41,141,135,407,190,26,4.40,29.33,14.66,35.48,15,100,50,121
3,control,clicked_users,PHH,DORMANT,293,1752,809,131,46.18,16.19,7.48,31.40,313,293,93.61,190,175,408,208,65,2.10,32.01,14.83,34.49,17,259,120,279
4,control,clicked_users,PHH,ELITE,582,5429,2784,679,51.28,24.39,12.51,37.54,686,586,85.42,176,155,281,175,38,1.08,35.49,13.00,25.90,30,988,362,721
5,control,clicked_users,PHH,GOLD,570,3601,1741,408,48.35,23.43,11.33,36.47,618,573,92.72,145,171,409,197,36,1.32,32.51,12.81,29.70,23,566,223,517
6,control,clicked_users,PHH,INACTIVE,105,502,231,40,46.02,17.32,7.97,29.44,111,105,94.59,180,180,393,215,80,0.87,27.71,12.12,41.99,2,64,28,97
7,control,clicked_users,PHH,PLATINUM,600,4440,2330,453,52.48,19.44,10.20,34.08,678,606,89.38,112,136,225,146,24,1.20,34.85,14.55,29.83,28,812,339,695
8,control,clicked_users,PHH,PRIME,35,344,154,42,44.77,27.27,12.21,44.16,41,36,87.80,89,132,330,147,22,1.95,35.06,16.88,18.83,3,54,26,29
9,control,clicked_users,PHH,SILVER,328,2033,977,199,48.06,20.37,9.79,34.29,367,329,89.65,205,169,327,187,47,1.84,32.24,13.72,31.63,18,315,134,309
10,control,clicked_users,UNKNOWN,UNKNOWN,114,696,316,28,45.40,8.86,4.02,21.52,127,115,90.55,189,162,617,195,149,4.11,25.63,12.66,48.73,13,81,40,154
11,control,clicked_users,None,None,260,1930,782,166,40.52,21.23,8.60,32.99,278,262,94.24,223,162,596,218,68,3.45,20.97,11.51,42.46,27,164,90,332
12,control,None,HH,DORMANT,24609,93744,21943,10607,23.41,48.34,11.31,72.91,4598,0,0.00,119,143,349,198,13,1.75,14.45,24.09,10.84,384,3171,5286,2379
13,control,None,HH,HH,52719,275278,78986,44751,28.69,56.66,16.26,76.01,15015,0,0.00,119,139,342,185,13,1.25,14.25,18.92,8.47,988,11259,14948,6689
14,control,None,HH,INACTIVE,23009,94772,20449,10213,21.58,49.94,10.78,74.40,3960,0,0.00,110,141,350,204,12,1.55,13.53,23.94,10.49,316,2767,4895,2146
15,control,None,PHH,DORMANT,55208,215222,62892,31541,29.22,50.15,14.66,71.08,14333,0,0.00,125,134,336,183,14,1.16,17.25,20.44,10.48,731,10848,12853,6590
16,control,None,PHH,ELITE,62709,744332,335577,196683,45.08,58.61,26.42,75.51,49181,0,0.00,99,120,271,156,14,0.74,16.57,16.62,7.16,2489,55618,55770,24029
17,control,None,PHH,GOLD,79104,447371,160137,89587,35.80,55.94,20.03,74.30,31288,0,0.00,106,131,307,174,13,1.00,16.20,18.00,8.48,1603,25949,28832,13585
18,control,None,PHH,INACTIVE,20578,81970,19993,9958,24.39,49.81,12.15,71.80,4287,0,0.00,133,140,349,190,14,1.19,16.18,21.48,10.80,238,3235,4294,2159
19,control,None,PHH,PLATINUM,76930,553938,221481,123274,39.98,55.66,22.25,73.85,40181,0,0.00,110,125,287,166,13,0.87,17.09,17.86,8.18,1924,37862,39558,18117
20,control,None,PHH,PRIME,3519,53415,20595,13209,38.56,64.14,24.73,79.17,3113,0,0.00,103,122,264,159,14,0.70,14.91,14.76,5.22,145,3070,3040,1075
21,control,None,PHH,SILVER,49645,224502,71791,40394,31.98,56.27,17.99,74.69,15159,0,0.00,119,134,324,180,14,1.04,15.22,17.98,9.03,746,10929,12909,6484
22,control,None,UNKNOWN,UNKNOWN,14813,72328,18158,5850,25.11,32.22,8.09,68.87,3513,0,0.00,89,116,144,122,12,3.27,15.17,36.07,12.65,594,2754,6550,2297
23,control,None,None,None,40583,207724,39443,21937,18.99,55.62,10.56,77.83,6393,0,0.00,115,143,402,222,13,1.61,11.10,21.42,9.41,635,4380,8449,3713
24,test,clicked_users,HH,DORMANT,85,523,236,27,45.12,11.44,5.16,25.00,92,86,93.48,218,167,447,200,48,0.42,30.51,13.56,44.07,1,72,32,104
25,test,clicked_users,HH,HH,354,2653,1168,241,44.03,20.63,9.08,34.76,384,358,93.23,140,161,541,192,33,4.37,27.31,13.87,33.56,51,319,162,392
26,test,clicked_users,HH,INACTIVE,80,527,248,37,47.06,14.92,7.02,23.39,87,82,94.25,110,190,547,200,103,6.05,31.85,8.47,38.71,15,79,21,96
27,test,clicked_users,PHH,DORMANT,188,1073,539,60,50.23,11.13,5.59,23.93,203,188,92.61,182,163,298,183,53,0.93,39.89,12.80,35.25,5,215,69,190
28,test,clicked_users,PHH,ELITE,686,6297,3451,753,54.80,21.82,11.96,34.71,802,692,86.28,82,155,308,173,29,1.13,37.35,12.72,26.80,39,1289,439,925
29,test,clicked_users,PHH,GOLD,508,3757,1849,357,49.21,19.31,9.50,32.29,563,515,91.47,130,154,418,181,37,1.35,34.83,12.87,31.53,25,644,238,583
30,test,clicked_users,PHH,INACTIVE,68,410,189,22,46.10,11.64,5.37,23.28,75,68,90.67,158,155,339,217,64,2.12,25.93,11.64,48.68,4,49,22,92
31,test,clicked_users,PHH,PLATINUM,587,4502,2413,474,53.60,19.64,10.53,31.83,649,590,90.91,143,144,398,163,35,1.53,37.17,12.02,29.47,37,897,290,711
32,test,clicked_users,PHH,PRIME,42,513,200,60,38.99,30.00,11.70,45.50,47,42,89.36,185,204,374,229,46,1.50,32.00,15.50,21.00,3,64,31,42
33,test,clicked_users,PHH,SILVER,240,1516,829,141,54.68,17.01,9.30,27.99,262,240,91.60,176,178,425,208,53,2.17,33.78,10.86,36.07,18,280,90,299
34,test,clicked_users,UNKNOWN,UNKNOWN,95,588,263,16,44.73,6.08,2.72,17.87,107,96,89.72,77,177,332,185,83,5.70,27.38,11.79,49.05,15,72,31,129
35,test,clicked_users,None,None,108,886,350,61,39.50,17.43,6.88,29.43,120,109,90.83,173,160,484,208,35,4.86,25.43,12.00,40.29,17,89,42,141
36,test,None,HH,DORMANT,24135,92188,21754,10472,23.60,48.14,11.36,72.35,1733,0,0.00,126,144,338,200,13,1.72,15.11,23.60,10.77,374,3288,5133,2343
37,test,None,HH,HH,52052,269300,76995,44222,28.59,57.43,16.42,76.83,8621,0,0.00,118,136,358,194,13,1.18,13.66,18.94,8.30,908,10520,14584,6393
38,test,None,HH,INACTIVE,22258,91297,19555,9532,21.42,48.74,10.44,73.86,1356,0,0.00,90,142,348,206,13,1.76,13.18,24.44,11.16,344,2577,4780,2182
39,test,None,PHH,DORMANT,54326,212738,62065,31147,29.17,50.18,14.64,71.51,5776,0,0.00,125,136,323,186,13,1.14,16.84,20.92,10.48,707,10452,12982,6502
40,test,None,PHH,ELITE,60757,717568,326193,190681,45.46,58.46,26.57,75.59,31063,0,0.00,93,120,267,157,13,0.67,16.53,16.84,7.20,2178,53935,54931,23479
41,test,None,PHH,GOLD,77496,439543,156728,87569,35.66,55.87,19.92,74.38,17406,0,0.00,112,130,314,175,13,1.03,16.27,18.16,8.30,1609,25503,28457,13007
42,test,None,PHH,INACTIVE,20139,79536,20022,10015,25.17,50.02,12.59,71.50,1604,0,0.00,110,141,313,184,12,1.27,16.14,20.96,11.08,254,3232,4196,2218
43,test,None,PHH,PLATINUM,75288,537891,215322,120231,40.03,55.84,22.35,73.90,23200,0,0.00,102,125,284,165,13,0.87,17.11,17.73,8.10,1877,36834,38185,17451
44,test,None,PHH,PRIME,3506,54635,20479,13090,37.48,63.92,23.96,79.26,2041,0,0.00,102,119,264,154,14,0.65,15.29,15.11,4.80,133,3132,3094,982
45,test,None,PHH,SILVER,48364,219364,70087,39630,31.95,56.54,18.07,74.91,8207,0,0.00,120,134,328,182,14,0.98,15.21,17.92,8.87,689,10658,12559,6220
46,test,None,UNKNOWN,UNKNOWN,14523,69956,17077,5641,24.41,33.03,8.06,67.93,1736,0,0.00,100,133,243,166,12,2.85,15.79,34.26,13.37,487,2697,5851,2283
47,test,None,None,None,40172,204719,39779,21911,19.43,55.08,10.70,77.03,1628,0,0.00,96,142,394,216,13,1.54,11.47,21.18,9.93,611,4561,8427,3951

In [71]:
curr_overall_service_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category

        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        rr_net.service_category,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        service_category,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            service_category,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
curr_overall_service_df=pd.read_sql(curr_overall_service_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/3379055199.py:232: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_overall_service_df=pd.read_sql(curr_overall_service_query,conn)

In [ ]:
filtered_df = df[df['service_category'].notnull()]

In [73]:
curr_overall_service_df=curr_overall_service_df[curr_overall_service_df['service_category'].notnull()]

In [74]:
curr_overall_service_df

,sample_category,user_type,service_category,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,auto,2017,4775,5767,752,120.77,13.04,15.75,21.68,2285,2029,88.80,167.0,148.0,330.0,165.0,49.0,2.06,32.13,8.64,44.13,119,1853,498,2545
1,control,clicked_users,bike,1766,4256,4558,1375,107.10,30.17,32.31,49.45,2064,1779,86.19,200.0,157.0,350.0,189.0,38.0,2.04,32.27,18.96,16.17,93,1471,864,737
2,control,clicked_users,cab,795,1557,1685,383,108.22,22.73,24.60,40.65,926,802,86.61,89.0,187.0,335.0,208.0,25.0,0.83,29.85,17.74,28.61,14,503,299,482
4,control,None,auto,136440,306921,324482,131239,105.72,40.45,42.76,55.61,86943,0,0.00,112.0,128.0,284.0,152.0,15.0,1.95,24.46,15.12,17.97,6339,79354,49073,58313
5,control,None,bike,232911,582681,588387,381709,100.98,64.87,65.51,84.28,116098,0,0.00,111.0,123.0,296.0,177.0,14.0,0.54,12.12,18.78,3.05,3153,71308,110526,17940
6,control,None,cab,80648,156190,158576,85056,101.53,53.64,54.46,77.58,39700,0,0.00,87.0,136.0,316.0,192.0,12.0,0.82,13.36,23.83,8.20,1301,21180,37785,13010
8,test,clicked_users,auto,1918,4994,5981,669,119.76,11.19,13.40,19.18,2180,1937,88.85,136.0,155.0,359.0,167.0,37.0,2.21,35.68,7.99,42.94,132,2134,478,2568
9,test,clicked_users,bike,1549,3746,3995,1224,106.65,30.64,32.67,48.04,1815,1563,86.12,91.0,154.0,347.0,183.0,36.0,1.45,33.89,17.05,16.62,58,1354,681,664
10,test,clicked_users,cab,756,1632,1759,356,107.78,20.24,21.81,37.86,863,764,88.53,142.0,169.0,504.0,215.0,33.0,2.27,33.03,17.51,26.83,40,581,308,472
12,test,None,auto,133888,299578,316822,128557,105.76,40.58,42.91,55.79,46651,0,0.00,109.0,129.0,285.0,155.0,14.0,1.85,24.37,15.16,17.98,5858,77221,48032,56960
13,test,None,bike,228999,569321,574931,372974,100.99,64.87,65.51,84.31,63979,0,0.00,111.0,122.0,299.0,182.0,13.0,0.52,12.09,18.81,3.07,2982,69515,108132,17625
14,test,None,cab,78246,152126,154303,82610,101.43,53.54,54.30,77.64,21008,0,0.00,76.0,134.0,313.0,195.0,12.0,0.86,13.38,23.99,8.05,1331,20653,37015,12426

In [75]:
curr_overall_service_df.to_csv('curr_overall_service_df.csv',index=False)

In [76]:
past_overall_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240828' AND yyyymmdd <= '20240904'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240828' AND yyyymmdd <= '20240904'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        --AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2
        )
    ORDER BY 1,2


"""
past_overall_df=pd.read_sql(past_overall_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/3217329975.py:222: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  past_overall_df=pd.read_sql(past_overall_query,conn)

In [77]:
past_overall_df

,sample_category,user_type,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,2419,34431,14257,7170,41.41,50.29,20.82,66.56,2719,2436,89.59,121,131,270,163,16,1.03,19.98,15.98,12.40,147,2848,2278,1768
1,control,None,355630,3535059,1315561,746010,37.21,56.71,21.10,74.43,147383,0,0.00,96,125,272,163,14,0.91,16.55,17.38,8.11,11910,217693,228635,106674
2,test,clicked_users,2325,39170,16657,7996,42.52,48.00,20.41,65.32,2617,2344,89.57,139,139,287,176,19,1.75,19.99,16.95,12.93,292,3330,2824,2153
3,test,None,347069,3437069,1281944,725859,37.30,56.62,21.12,74.34,86277,0,0.00,97,125,272,166,14,0.94,16.57,17.37,8.14,12100,212394,222723,104344

In [78]:
past_overall_df.to_csv('past_overall_df.csv',index=False)

In [106]:
click_time_bucket_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
         
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

click_time AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        event_epoch
         
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
),


fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        order_requested_epoch,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category

        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        rr_net.service_category,
        rr_net.order_requested_epoch,
        click_time.event_epoch,
        user_type
    FROM 
        intermediate_merge
    LEFT JOIN 
        click_time
        ON intermediate_merge.userid=click.userid
        and intermediate_merge.yyyymmdd=click.yyyymmdd
        and intermediate_merge.adid=click.adid
        and intermediate_merge.click_adid is not null
    LEFT JOIN 
        fe_tbl
        ON intermediate_merge.customer_id = fe_tbl.user_id 
        AND intermediate_merge.yyyymmdd = fe_tbl.yyyymmdd
        and intermediate_merge.click_adid is not null
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
        
        
)

SELECT
        sample_category,
        user_type,
        time_interval,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            CASE 
                WHEN click_adid IS NOT NULL THEN 
                    CASE 
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 0 AND 50 THEN '0-50 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 51 AND 100 THEN '51-100 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 101 AND 150 THEN '101-150 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 151 AND 200 THEN '151-200 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 201 AND 250 THEN '201-250 seconds'
                        ELSE '> 250 seconds'
                    END
                ELSE NULL
            END AS time_interval,

            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
            and click_adid is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
click_time_bucket_df=pd.read_sql(click_time_bucket_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/2356992927.py:275: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  click_time_bucket_df=pd.read_sql(click_time_bucket_query,conn)

In [107]:
click_time_bucket_df

,sample_category,user_type,time_interval,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,0-50 seconds,3377,8763,9046,1895,103.23,20.95,21.63,35.62,3757,3396,90.39,171,154,335,181,55,1.76,32.95,14.51,29.64,159,2981,1313,2681
1,control,clicked_users,101-150 seconds,1768,2442,2500,231,102.38,9.24,9.46,20.12,2001,1772,88.56,131,131,255,137,139,3.08,46.44,10.84,30.36,77,1161,271,759
2,control,clicked_users,151-200 seconds,1596,2216,2282,177,102.98,7.76,7.99,18.14,1795,1604,89.36,187,160,245,166,173,3.02,48.20,10.34,30.54,69,1100,236,697
3,control,clicked_users,201-250 seconds,1439,2024,2091,111,103.31,5.31,5.48,16.12,1635,1447,88.50,233,195,247,204,163,3.20,50.45,10.76,30.18,67,1055,225,631
4,control,clicked_users,51-100 seconds,1940,2857,2914,348,102.00,11.94,12.18,24.57,2183,1948,89.23,136,102,277,120,113,2.40,42.72,12.59,30.27,70,1245,367,882
5,control,clicked_users,> 250 seconds,3436,24332,11331,2318,46.57,20.46,9.53,34.40,3831,3456,90.21,156,146,309,165,34,1.89,31.61,13.79,32.07,214,3582,1562,3634
6,test,clicked_users,0-50 seconds,2943,9042,9367,1839,103.59,19.63,20.34,32.80,3280,2965,90.40,100,150,361,170,45,1.95,35.96,13.00,29.29,183,3368,1218,2744
7,test,clicked_users,101-150 seconds,1750,2754,2824,196,102.54,6.94,7.12,16.75,1951,1759,90.16,129,133,253,137,149,2.94,49.75,9.81,30.56,83,1405,277,863
8,test,clicked_users,151-200 seconds,1678,2566,2647,151,103.16,5.70,5.88,15.60,1877,1689,89.98,148,168,203,167,159,3.10,51.61,9.86,29.69,82,1366,261,786
9,test,clicked_users,201-250 seconds,1523,2312,2380,121,102.94,5.08,5.23,14.79,1712,1532,89.49,179,196,251,200,114,3.03,51.89,9.66,30.29,72,1235,230,721
10,test,clicked_users,51-100 seconds,1964,3270,3361,356,102.78,10.59,10.89,20.35,2191,1975,90.14,73,115,264,117,122,2.77,46.27,9.70,30.62,93,1555,326,1029
11,test,clicked_users,> 250 seconds,2976,22792,11265,2114,49.43,18.77,9.28,31.30,3325,3000,90.23,137,150,374,173,28,2.00,34.65,12.41,32.06,225,3903,1398,3611

In [99]:
click_time_bucket_df

,sample_category,user_type,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,3523,24983,12010,2510,48.07,20.90,10.05,34.88,3918,3543,90.43,162,147,307,165,37,1.88,31.87,13.83,31.34,226,3827,1661,3764
1,test,clicked_users,3041,23245,11735,2249,50.48,19.16,9.68,31.80,3391,3066,90.42,133,150,360,171,32,1.96,34.67,12.50,31.56,230,4069,1467,3704

In [116]:
curr_overall_service_df

,sample_category,user_type,time_interval,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,0-50 seconds,3122,3151,3151,635,100.00,20.15,20.15,35.35,3466,3137,90.51,222.0,199,388,228,67,1.33,27.86,15.07,35.42,42,878,475,1116
1,control,clicked_users,101-150 seconds,38,38,38,0,100.00,0.00,0.00,10.53,58,38,65.52,91.0,116,29,111,13,5.26,55.26,10.53,28.95,2,21,4,11
2,control,clicked_users,151-200 seconds,34,34,34,2,100.00,5.88,5.88,17.65,51,34,66.67,277.0,154,166,157,98,2.94,55.88,11.76,23.53,1,19,4,8
3,control,clicked_users,201-250 seconds,28,28,28,1,100.00,3.57,3.57,14.29,45,28,62.22,NaN,194,208,199,118,0.00,57.14,10.71,28.57,0,16,3,8
4,control,clicked_users,51-100 seconds,28,28,28,3,100.00,10.71,10.71,21.43,44,28,63.64,NaN,67,426,68,175,0.00,50.00,10.71,28.57,0,14,3,8
5,control,clicked_users,> 250 seconds,3394,22272,8757,1871,39.32,21.37,8.40,34.94,3789,3414,90.10,165.0,149,332,172,33,2.07,33.00,13.42,29.95,181,2890,1175,2623
6,test,clicked_users,0-50 seconds,2702,2734,2734,562,100.00,20.56,20.56,34.89,3003,2720,90.58,226.0,191,407,221,51,1.35,28.49,14.16,35.26,37,779,387,964
7,test,clicked_users,101-150 seconds,19,19,19,1,100.00,5.26,5.26,21.05,28,19,67.86,211.0,103,275,109,123,5.26,42.11,15.79,31.58,1,8,3,6
8,test,clicked_users,151-200 seconds,27,27,27,1,100.00,3.70,3.70,11.11,41,27,65.85,171.0,171,53,170,10,7.41,51.85,7.41,29.63,2,14,2,8
9,test,clicked_users,201-250 seconds,32,32,32,2,100.00,6.25,6.25,12.50,54,32,59.26,197.0,205,25,201,25,3.13,53.13,6.25,31.25,1,17,2,10
10,test,clicked_users,51-100 seconds,53,53,53,5,100.00,9.43,9.43,16.98,67,53,79.10,135.0,98,456,122,179,1.89,45.28,7.55,35.85,1,24,4,19
11,test,clicked_users,> 250 seconds,2941,20849,8902,1686,42.70,18.94,8.09,31.07,3290,2965,90.12,121.0,148,374,171,34,2.11,36.42,12.01,30.40,188,3242,1069,2706

In [142]:
click_time_bucket_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
         
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

click_time AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        MIN(event_epoch) as event_epoch
         
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
        group by 1,2,3
),


fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

req_time as(
    select
            yyyymmdd, 
            customer_id,
            estimate_id AS fare_estimate_id, 
            Min(order_requested_epoch) as order_requested_epoch
    FROM 
        orders.order_logs_fact fact
        
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android' 
    group by 1,2,3

),


rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category

        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        rr_net.service_category,
        req_time.order_requested_epoch,
        click_time.event_epoch,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        click_time
            ON click.userid=click_time.userid
            and click.yyyymmdd=click_time.yyyymmdd
            and click_time.adid=click.adid
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
    LEFT JOIN req_time
        ON req_time.yyyymmdd = rr_net.yyyymmdd
        AND req_time.customer_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
        
        
)

SELECT
        sample_category,
        user_type,
        time_interval,
        customers,
        --fe_count,
        gross_count,
        net_count,
        --COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            CASE 
                WHEN click_adid IS NOT NULL THEN 
                    CASE 
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 0 AND 50 THEN '0-50 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 51 AND 100 THEN '51-100 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 101 AND 150 THEN '101-150 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 151 AND 200 THEN '151-200 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 201 AND 250 THEN '201-250 seconds'
                        WHEN (event_epoch / 1000 - order_requested_epoch / 1000) BETWEEN 251 AND 300 THEN '251-300 seconds'
                        ELSE '> 250 seconds'
                    END
                ELSE NULL
            END AS time_interval,

            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
            and click_adid is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
click_time_bucket_df=pd.read_sql(click_time_bucket_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/2511804075.py:303: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  click_time_bucket_df=pd.read_sql(click_time_bucket_query,conn)

In [143]:
click_time_bucket_df

,sample_category,user_type,time_interval,customers,gross_count,net_count,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,0-50 seconds,3122,10920,2301,21.07,23.84,35.01,3466,3137,90.51,176.0,156,335,178,40,1.91,32.29,13.78,30.76,209,3526,1505,3359
1,control,clicked_users,101-150 seconds,36,197,23,11.68,12.57,25.38,55,36,65.45,134.0,123,302,133,29,2.03,47.72,13.20,24.87,4,94,26,49
2,control,clicked_users,151-200 seconds,29,179,19,10.61,11.80,20.67,44,29,65.91,NaN,149,304,154,63,0.00,57.54,10.06,21.79,0,103,18,39
3,control,clicked_users,201-250 seconds,26,147,25,17.01,17.99,29.93,42,26,61.90,NaN,156,260,167,25,0.00,48.30,12.93,21.77,0,71,19,32
4,control,clicked_users,251-300 seconds,24,107,17,15.89,18.28,27.10,32,24,75.00,134.0,149,390,164,58,2.80,39.25,11.21,30.84,3,42,12,33
5,control,clicked_users,51-100 seconds,25,135,26,19.26,20.31,33.33,38,25,65.79,NaN,110,446,129,55,0.00,46.67,14.07,20.00,0,63,19,27
6,control,clicked_users,> 250 seconds,3351,10894,2265,20.79,9.39,34.89,3746,3371,89.99,144.0,142,224,152,30,1.92,33.39,13.94,29.77,209,3638,1519,3243
7,test,clicked_users,0-50 seconds,2701,10579,2053,19.41,21.79,32.20,3002,2719,90.57,124.0,156,374,179,35,1.96,35.02,12.65,30.83,207,3705,1338,3261
8,test,clicked_users,101-150 seconds,18,85,15,17.65,18.99,44.71,27,18,66.67,40.0,118,224,132,12,3.53,30.59,27.06,21.18,3,26,23,18
9,test,clicked_users,151-200 seconds,24,124,18,14.52,15.25,25.81,37,24,64.86,171.0,168,275,172,43,3.23,45.16,11.29,25.81,4,56,14,32
10,test,clicked_users,201-250 seconds,27,165,18,10.91,12.41,20.00,46,27,58.70,78.0,150,312,150,13,1.21,51.52,9.09,27.27,2,85,15,45
11,test,clicked_users,251-300 seconds,19,98,16,16.33,17.39,26.53,32,19,59.38,232.0,169,490,195,36,3.06,53.06,10.20,17.35,3,52,10,17
12,test,clicked_users,51-100 seconds,51,237,32,13.50,15.53,27.85,63,51,80.95,43.0,125,279,132,14,2.53,38.82,14.35,30.80,6,92,34,73
13,test,clicked_users,> 250 seconds,2909,10925,2060,18.86,9.11,31.57,3257,2933,90.05,122.0,144,329,161,23,2.06,36.02,12.59,30.35,225,3935,1375,3316

In [131]:
click_time_bucket_df

,sample_category,user_type,time_interval,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,0-50 seconds,3122,9652,10920,2301,113.14,21.07,23.84,35.01,3466,3137,90.51,174.0,156,335,178,39,1.91,32.29,13.78,30.76,209,3526,1505,3359
1,control,clicked_users,101-150 seconds,36,183,197,23,107.65,11.68,12.57,25.38,55,36,65.45,134.0,124,293,132,27,2.03,47.72,13.20,24.87,4,94,26,49
2,control,clicked_users,151-200 seconds,29,161,179,19,111.18,10.61,11.80,20.67,44,29,65.91,NaN,149,306,154,63,0.00,57.54,10.06,21.79,0,103,18,39
3,control,clicked_users,201-250 seconds,26,139,147,25,105.76,17.01,17.99,29.93,42,26,61.90,NaN,156,265,167,26,0.00,48.30,12.93,21.77,0,71,19,32
4,control,clicked_users,51-100 seconds,25,128,135,26,105.47,19.26,20.31,33.33,38,25,65.79,NaN,111,445,129,54,0.00,46.67,14.07,20.00,0,63,19,27
5,control,clicked_users,> 250 seconds,3351,24134,10903,2266,45.18,20.78,9.39,34.88,3746,3371,89.99,143.0,142,224,152,30,1.92,33.38,13.94,29.80,209,3639,1520,3249
6,test,clicked_users,0-50 seconds,2701,9420,10579,2053,112.30,19.41,21.79,32.20,3002,2719,90.57,126.0,156,378,179,37,1.96,35.02,12.65,30.83,207,3705,1338,3261
7,test,clicked_users,101-150 seconds,18,79,85,15,107.59,17.65,18.99,44.71,27,18,66.67,40.0,119,221,132,13,3.53,30.59,27.06,21.18,3,26,23,18
8,test,clicked_users,151-200 seconds,24,118,124,18,105.08,14.52,15.25,25.81,37,24,64.86,171.0,169,285,173,40,3.23,45.16,11.29,25.81,4,56,14,32
9,test,clicked_users,201-250 seconds,27,145,165,18,113.79,10.91,12.41,20.00,46,27,58.70,78.0,150,310,151,13,1.21,51.52,9.09,27.27,2,85,15,45
10,test,clicked_users,51-100 seconds,51,206,237,32,115.05,13.50,15.53,27.85,63,51,80.95,43.0,125,277,132,13,2.53,38.82,14.35,30.80,6,92,34,73
11,test,clicked_users,> 250 seconds,2909,22624,10933,2061,48.32,18.85,9.11,31.56,3257,2933,90.05,123.0,144,334,162,23,2.07,36.03,12.59,30.34,226,3939,1376,3317

In [140]:
click_time_bucket_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
         
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

click_time AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        MIN(event_epoch) as event_epoch
         
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
        group by 1,2,3
),


fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

req_time as(
    select
            yyyymmdd, 
            customer_id,
            estimate_id AS fare_estimate_id, 
            Min(order_requested_epoch) as order_requested_epoch
    FROM 
        orders.order_logs_fact fact
        
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android' 
    group by 1,2,3

),


rr_net AS (
    SELECT 
        fact.yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN click.adid is not null
            THEN (event_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_click,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category

        
    
    FROM 
        orders.order_logs_fact fact
    LEFT JOIN 
        click
        ON customer_id = click.userid 
        AND fact.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        click_time
            ON click.userid=click_time.userid
            and click.yyyymmdd=click_time.yyyymmdd
            and click_time.adid=click.adid
    WHERE 
         fact.yyyymmdd >= '20240905' AND fact.yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        rr_net.service_category,
        rr_net.time_taken_to_click,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        click_time
            ON click.userid=click_time.userid
            and click.yyyymmdd=click_time.yyyymmdd
            and click_time.adid=click.adid
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON 
        -- fe_tbl.yyyymmdd = rr_net.yyyymmdd
        -- AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
        -and 
        
        
)

SELECT
        sample_category,
        user_type,
        time_interval,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            CASE 
                WHEN time_taken_to_click IS NOT NULL THEN 
                    CASE 
                        WHEN time_taken_to_click BETWEEN 0 AND 50 THEN '0-50 seconds'
                        WHEN time_taken_to_click BETWEEN 51 AND 100 THEN '51-100 seconds'
                        WHEN time_taken_to_click BETWEEN 101 AND 150 THEN '101-150 seconds'
                        WHEN time_taken_to_click BETWEEN 151 AND 200 THEN '151-200 seconds'
                        WHEN time_taken_to_click BETWEEN 201 AND 250 THEN '201-250 seconds'
                        WHEN time_taken_to_click BETWEEN 251 AND 300 THEN '251-300 seconds'
                    END
                ELSE NULL
            END AS time_interval,


            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
            and click_adid is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
click_time_bucket_df=pd.read_sql(click_time_bucket_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/3384563671.py:312: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  click_time_bucket_df=pd.read_sql(click_time_bucket_query,conn)

In [141]:
click_time_bucket_df

,sample_category,user_type,time_interval,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,0-50 seconds,3122,3151,3151,635,100.00,20.15,20.15,35.35,3466,3142,90.65,220.0,198.0,385.0,227.0,66.0,1.33,27.86,15.07,35.42,42,878,475,1116
1,control,clicked_users,101-150 seconds,38,38,38,0,100.00,0.00,0.00,10.53,58,39,67.24,91.0,119.0,29.0,112.0,13.0,5.26,55.26,10.53,28.95,2,21,4,11
2,control,clicked_users,151-200 seconds,34,34,34,2,100.00,5.88,5.88,17.65,51,35,68.63,277.0,150.0,166.0,154.0,98.0,2.94,55.88,11.76,23.53,1,19,4,8
3,control,clicked_users,201-250 seconds,28,28,28,1,100.00,3.57,3.57,14.29,45,30,66.67,NaN,191.0,208.0,197.0,118.0,0.00,57.14,10.71,28.57,0,16,3,8
4,control,clicked_users,251-300 seconds,27,27,27,4,100.00,14.81,14.81,25.93,36,28,77.78,134.0,228.0,245.0,228.0,32.0,3.70,40.74,11.11,29.63,1,11,3,8
5,control,clicked_users,51-100 seconds,28,28,28,3,100.00,10.71,10.71,21.43,44,28,63.64,NaN,67.0,426.0,68.0,175.0,0.00,50.00,10.71,28.57,0,14,3,8
6,control,clicked_users,> 300 seconds,2810,7859,8731,1867,111.10,21.38,23.76,34.97,3198,2828,88.43,168.0,149.0,336.0,172.0,34.0,2.06,32.99,13.42,29.95,180,2880,1172,2615
7,control,clicked_users,None,3165,14395,0,0,0.00,0.00,0.00,0.00,3544,3183,89.81,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0
8,test,clicked_users,0-50 seconds,2702,2734,2734,562,100.00,20.56,20.56,34.89,3003,2724,90.71,226.0,191.0,406.0,219.0,50.0,1.35,28.49,14.16,35.26,37,779,387,964
9,test,clicked_users,101-150 seconds,19,19,19,1,100.00,5.26,5.26,21.05,28,19,67.86,211.0,103.0,275.0,109.0,123.0,5.26,42.11,15.79,31.58,1,8,3,6
10,test,clicked_users,151-200 seconds,27,27,27,1,100.00,3.70,3.70,11.11,41,29,70.73,171.0,156.0,53.0,161.0,10.0,7.41,51.85,7.41,29.63,2,14,2,8
11,test,clicked_users,201-250 seconds,32,32,32,2,100.00,6.25,6.25,12.50,54,33,61.11,197.0,204.0,25.0,202.0,25.0,3.13,53.13,6.25,31.25,1,17,2,10
12,test,clicked_users,251-300 seconds,22,22,22,1,100.00,4.55,4.55,4.55,37,24,64.86,261.0,246.0,NaN,248.0,18.0,4.55,77.27,0.00,13.64,1,17,0,3
13,test,clicked_users,51-100 seconds,53,53,53,5,100.00,9.43,9.43,16.98,67,54,80.60,135.0,89.0,456.0,103.0,179.0,1.89,45.28,7.55,35.85,1,24,4,19
14,test,clicked_users,> 300 seconds,2505,7960,8882,1685,111.58,18.97,21.17,31.13,2849,2529,88.77,118.0,150.0,373.0,171.0,34.0,2.11,36.32,12.04,30.44,187,3226,1069,2704
15,test,clicked_users,None,2735,12873,0,0,0.00,0.00,0.00,0.00,3066,2759,89.99,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0,0,0,0

In [ ]:
curr_overall_service_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category

        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        rr_net.service_category,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        service_category,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            service_category,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3


"""
curr_overall_service_df=pd.read_sql(curr_overall_service_query,conn)

In [158]:
time_bucket_query=f"""
with olf as (

    SELECT
        yyyymmdd,
        customer_id,
        order_id,
        order_requested_epoch,
        customer_cancelled_epoch
        
    FROM 
        orders.order_logs_fact
    WHERE
        yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND modified_order_status = 'COBRA'
    ),

    click AS (
    
        SELECT
            yyyymmdd,
            adid,
            userid,
            epoch click_epoch
             
        FROM 
            canonical.iceberg_log_telemetry_ads_impressions_immutable
        WHERE  
             yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
            --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
            --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
            AND responseType = 'GAMBanner'
            AND city = 'Delhi'
            AND appversion >= '8.30.0'
            AND slotname = 'CaptainSearch1'
            AND eventName = 'Ad_Click'
    ),
    
    merge AS (
    
    SELECT 
        olf.*,
        click_epoch,
        (click_epoch / 1000 - order_requested_epoch / 1000) time_to_click,
        row_number() over(partition by olf.yyyymmdd,olf.customer_id,olf.order_id order by click_epoch) seq_no
    FROM 
        olf
    JOIN 
        click
        on olf.yyyymmdd = click.yyyymmdd
        and olf.customer_id = click.userid
        and olf.order_requested_epoch < click.click_epoch
        and olf.customer_cancelled_epoch > click.click_epoch
    )
    
    
    SELECT
        yyyymmdd,
        case 
        when time_to_click <= 60 then '0-60sec'
        when time_to_click between 61 and 120 then '61-120sec'
        when time_to_click between 121 and 180 then '121-180sec'
        when time_to_click between 180 and 240 then '181-240sec'
        when time_to_click > 240 then '240+sec' 
        else 'check' end as click_bucket,
        count(distinct customer_id) customers
    FROM 
        merge
    WHERE 
        seq_no = 1
    GROUP BY 1,2
    ORDER BY 1,2

    """

time_bucket_df=pd.read_sql(time_bucket_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/3122631905.py:79: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  time_bucket_df=pd.read_sql(time_bucket_query,conn)

In [159]:
time_bucket_df

    yyyymmdd click_bucket  customers
0   20240905      0-60sec        151
1   20240905   121-180sec        173
2   20240905   181-240sec        103
3   20240905      240+sec         62
4   20240905    61-120sec        227
5   20240906      0-60sec        241
6   20240906   121-180sec        264
7   20240906   181-240sec        172
8   20240906      240+sec        109
9   20240906    61-120sec        306
10  20240907      0-60sec         24
11  20240907   121-180sec         40
12  20240907   181-240sec         27
13  20240907      240+sec         14
14  20240907    61-120sec         61
15  20240908      0-60sec         14
16  20240908   121-180sec         21
17  20240908   181-240sec         11
18  20240908      240+sec          7
19  20240908    61-120sec         28
20  20240909      0-60sec         23
21  20240909   121-180sec         33
22  20240909   181-240sec         28
23  20240909      240+sec         23
24  20240909    61-120sec         46

In [161]:
pivot_df = time_bucket_df.pivot(index='yyyymmdd', columns='click_bucket', values='customers')
pivot_df

click_bucket  0-60sec  121-180sec  181-240sec  240+sec  61-120sec
yyyymmdd
20240905          151         173         103       62        227
20240906          241         264         172      109        306
20240907           24          40          27       14         61
20240908           14          21          11        7         28
20240909           23          33          28       23         46

In [162]:
df_percentage = pivot_df.div(pivot_df.sum(axis=1), axis=0) * 100

In [163]:
df_percentage

click_bucket    0-60sec  121-180sec  181-240sec    240+sec  61-120sec
yyyymmdd
20240905      21.089385   24.162011   14.385475   8.659218  31.703911
20240906      22.069597   24.175824   15.750916   9.981685  28.021978
20240907      14.457831   24.096386   16.265060   8.433735  36.746988
20240908      17.283951   25.925926   13.580247   8.641975  34.567901
20240909      15.032680   21.568627   18.300654  15.032680  30.065359

In [165]:
df_percentage.to_clipboard()

In [157]:
click_non_click_query=f"""
WITH exp_category AS (
    SELECT 
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
        yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id IN (
            SELECT DISTINCT userid
            FROM canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),
olf AS (
    SELECT
        customer_id,
        order_id,
        order_requested_epoch,
        customer_cancelled_epoch,
        order_status,
        modified_order_status,
        spd_fraud_flag,
        rider_accepted_epoch
    FROM 
        orders.order_logs_fact
    WHERE
        yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        AND city_name = 'Delhi'
),
click AS (
    SELECT
        userid,
        MIN(epoch) AS first_click_epoch
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
        yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName = 'Ad_Click'
    GROUP BY 1
),
merge AS (
    SELECT 
        olf.*,
        ec.sample_category,
        click.first_click_epoch,
        CASE 
            WHEN click.first_click_epoch IS NOT NULL 
                AND olf.order_requested_epoch < click.first_click_epoch
                AND olf.customer_cancelled_epoch > click.first_click_epoch
            THEN (click.first_click_epoch / 1000 - olf.order_requested_epoch / 1000)
            ELSE NULL
        END AS time_to_click,
        CASE 
            WHEN click.first_click_epoch IS NOT NULL THEN
                CASE
                    WHEN olf.order_requested_epoch < click.first_click_epoch
                        AND olf.customer_cancelled_epoch > click.first_click_epoch
                    THEN 'Click Order'
                    ELSE 'No-Click Order'
                END
            ELSE 'Non-Clicked User Order'
        END AS click_status
    FROM 
        olf
    JOIN
        exp_category ec ON olf.customer_id = ec.customer_id
    LEFT JOIN 
        click ON olf.customer_id = click.userid
)
SELECT
    m.sample_category,
    m.click_status,
    COUNT(DISTINCT m.customer_id) AS customers,
    COUNT(DISTINCT m.order_id) AS gross_orders,
    COUNT(DISTINCT CASE WHEN m.order_status = 'dropped' OR m.modified_order_status IN ('OCARA', 'aborted') THEN m.order_id END) AS net_orders,
    COUNT(DISTINCT CASE WHEN m.order_status = 'dropped' OR m.modified_order_status IN ('OCARA', 'aborted') THEN m.order_id END) AS accepted_orders,
    COUNT(DISTINCT CASE WHEN m.modified_order_status = 'COBRM' THEN m.order_id END) AS cobrm_orders,
    COUNT(DISTINCT CASE WHEN m.modified_order_status = 'COBRA' THEN m.order_id END) AS cobra_orders,
    COUNT(DISTINCT CASE WHEN m.modified_order_status = 'OCARA' THEN m.order_id END) AS ocara_orders,
    COUNT(DISTINCT CASE WHEN m.order_status = 'expired' THEN m.order_id END) AS expired_orders,
    AVG(CASE WHEN m.modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
        THEN (m.customer_cancelled_epoch / 1000 - m.order_requested_epoch / 1000) END) AS avg_cancellation_time,
    AVG(CASE WHEN m.order_status = 'dropped' OR m.modified_order_status IN ('OCARA', 'aborted') 
        THEN (m.rider_accepted_epoch / 1000 - m.order_requested_epoch / 1000) END) AS avg_acceptance_time,
    AVG(m.time_to_click) AS avg_time_to_click,
    COALESCE(
        COUNT(DISTINCT CASE WHEN m.order_status = 'dropped' OR m.modified_order_status IN ('OCARA', 'aborted') THEN m.order_id END) * 100.0 / 
        NULLIF(COUNT(DISTINCT m.order_id), 0),
        0
    ) AS acceptance_rate
FROM 
    merge m
GROUP BY 
    m.sample_category,
    m.click_status
ORDER BY 
    m.sample_category, 
    m.click_status
"""
click_non_click_df=pd.read_sql(click_non_click_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/2270914200.py:109: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  click_non_click_df=pd.read_sql(click_non_click_query,conn)

In [160]:
click_non_click_df

,sample_category,click_status,customers,gross_orders,net_orders,accepted_orders,cobrm_orders,cobra_orders,ocara_orders,expired_orders,avg_cancellation_time,avg_acceptance_time,avg_time_to_click,acceptance_rate
0,control,Click Order,1584,1584,432,432,69,1083,430,0,329.805512,245.101555,146.975201,27.3
1,control,No-Click Order,3428,18556,8945,8945,353,4343,2637,4911,251.282619,86.146002,NaN,48.2
2,control,Non-Clicked User Order,362443,1098731,812305,812305,14269,178695,200975,93269,286.598180,68.000577,NaN,73.9
3,test,Click Order,1394,1394,332,332,69,991,328,2,316.913136,268.091580,144.727688,23.8
4,test,No-Click Order,3008,19622,9356,9356,325,4993,2738,4948,253.963060,87.453151,NaN,47.7
5,test,Non-Clicked User Order,355611,1071304,792801,792801,13436,173892,196468,90957,286.472712,67.677012,NaN,74.0

In [166]:
time_bucket_query = """
WITH olf AS (
    SELECT
        customer_id,
        order_id,
        order_requested_epoch,
        customer_cancelled_epoch
    FROM 
        orders.order_logs_fact
    WHERE
        yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        AND city_name = 'Delhi'
        AND modified_order_status = 'COBRA'
),

click AS (
    SELECT
        adid,
        userid,
        epoch click_epoch
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
        yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName = 'Ad_Click'
),

merge AS (
    SELECT 
        olf.*,
        click_epoch,
        (click_epoch / 1000 - order_requested_epoch / 1000) time_to_click,
        ROW_NUMBER() OVER(PARTITION BY olf.customer_id, olf.order_id ORDER BY click_epoch) seq_no
    FROM 
        olf
    JOIN 
        click
        ON olf.customer_id = click.userid
        AND olf.order_requested_epoch < click.click_epoch
        AND olf.customer_cancelled_epoch > click.click_epoch
)

SELECT
    CASE 
        WHEN time_to_click <= 60 THEN '0-60sec'
        WHEN time_to_click BETWEEN 61 AND 120 THEN '61-120sec'
        WHEN time_to_click BETWEEN 121 AND 180 THEN '121-180sec'
        WHEN time_to_click BETWEEN 181 AND 240 THEN '181-240sec'
        WHEN time_to_click > 240 THEN '240+sec' 
        ELSE 'check' 
    END AS click_bucket,
    COUNT(DISTINCT customer_id) AS customers
FROM 
    merge
WHERE 
    seq_no = 1
GROUP BY 1
ORDER BY 1
"""

time_bucket_df = pd.read_sql(time_bucket_query, conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_4765/2279916104.py:65: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  time_bucket_df = pd.read_sql(time_bucket_query, conn)

In [167]:
time_bucket_df

  click_bucket  customers
0      0-60sec        453
1   121-180sec        531
2   181-240sec        341
3      240+sec        215
4    61-120sec        667

In [168]:
# Calculate total customers
total_customers = time_bucket_df['customers'].sum()

# Add a new column for customer percentage
time_bucket_df['customer_percentage'] = (time_bucket_df['customers'] / total_customers) * 100

# Optionally round to 2 decimal places
time_bucket_df['customer_percentage'] = time_bucket_df['customer_percentage'].round(2)

# Display the updated DataFrame
time_bucket_df

  click_bucket  customers  customer_percentage
0      0-60sec        453                20.53
1   121-180sec        531                24.06
2   181-240sec        341                15.45
3      240+sec        215                 9.74
4    61-120sec        667                30.22

In [170]:
time_bucket_df.to_clipboard(index=False)

## Wip

In [4]:
curr_overall_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression', 'Ad_Click')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2
        )
    ORDER BY 1,2


"""
curr_overall_df=pd.read_sql(curr_overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62362/3925239526.py:222: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  curr_overall_df=pd.read_sql(curr_overall_query,conn)

In [5]:
curr_overall_df

,sample_category,user_type,customers,fe_count,gross_count,net_count,fe2rr,g2n,fe2net,aor,impression_count,click_count,ctr,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,clicked_users,3523,24983,12010,2510,48.07,20.90,10.05,34.88,3918,3543,90.43,173,157,343,181,39,1.88,31.87,13.83,31.34,226,3827,1661,3764
1,control,None,503477,3064719,1071476,598029,34.96,55.81,19.51,74.61,191032,0,0.00,108,127,297,169,14,1.01,16.04,18.42,8.33,10793,171843,197385,89267
2,test,clicked_users,3041,23245,11735,2249,50.48,19.16,9.68,31.80,3391,3066,90.42,126,156,380,180,36,1.96,34.67,12.50,31.56,230,4069,1467,3704
3,test,None,493077,2988917,1046105,584167,35.00,55.84,19.54,74.69,104370,0,0.00,106,127,298,173,14,0.97,16.00,18.47,8.32,10171,167398,193184,87020

In [ ]:
curr_overall_query=f"""
WITH exp_category AS (
    SELECT 
        yyyymmdd,
        customer_id,
        sample_category
    FROM 
        iceberg.experiments_internal.rapidex_user_customer_adSlots_v1_root 
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND experiment_name = 'CaptainSearchScreen_meme'
        AND customer_id in (
            SELECT 
                DISTINCT userid
            FROM
                 canonical.iceberg_log_telemetry_ads_impressions_immutable
            WHERE
                 yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
                --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
                --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
                AND city='Delhi'
                AND appversion >= '8.30.0'
        )
),

impression AS (
    SELECT
        yyyymmdd,
        adid,
        userid
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
       -- yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName IN ('Ad_Request', 'Ad_Response', 'Ad_Impression')
    GROUP BY 
        yyyymmdd, adid, userid
    HAVING 
        COUNT(DISTINCT eventName) = 3
),

click AS (
    SELECT
        yyyymmdd,
        adid,
        userid,
        epoch click_epoch,
        'clicked_users' as user_type
    FROM 
        canonical.iceberg_log_telemetry_ads_impressions_immutable
    WHERE  
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND responseType = 'GAMBanner'
        AND city = 'Delhi'
        AND appversion >= '8.30.0'
        AND slotname = 'CaptainSearch1'
        AND eventName = 'Ad_Click'
    GROUP BY 
        1,2,3,4
),

fe_tbl AS (
    SELECT
        DISTINCT
        yyyymmdd,
        user_id,
        city,
        fare_estimate_id,
        quarter_hour
    FROM
        pricing.fare_estimates_enriched fee
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city = 'Delhi'
        AND channel='android'
),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        estimate_id AS fare_estimate_id, 
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240909'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
),

merge AS (
    SELECT
        exp_category.customer_id,
        exp_category.sample_category,
        fe_tbl.*,
        rr_net.order_id,
        rr_net.order_status,
        rr_net.modified_order_status,
        rr_net.spd_fraud_flag,
        rr_net.time_spent_in_sec,
        rr_net.time_taken_to_accp,
        impression.adid as impression_adid,
        click.adid as click_adid,
        user_type
    FROM 
        exp_category
    LEFT JOIN 
        impression
        ON exp_category.customer_id = impression.userid 
        AND exp_category.yyyymmdd = impression.yyyymmdd
    LEFT JOIN 
        click
        ON exp_category.customer_id = click.userid 
        AND exp_category.yyyymmdd = click.yyyymmdd
    LEFT JOIN 
        fe_tbl
        ON exp_category.customer_id = fe_tbl.user_id 
        AND exp_category.yyyymmdd = fe_tbl.yyyymmdd
    LEFT JOIN rr_net
        ON fe_tbl.yyyymmdd = rr_net.yyyymmdd
        AND fe_tbl.user_id = rr_net.customer_id 
        AND fe_tbl.fare_estimate_id = rr_net.fare_estimate_id
)

SELECT
        sample_category,
        user_type,
        customers,
        fe_count,
        gross_count,
        net_count,
        COALESCE(TRY(gross_count*100.00/fe_count), 0) fe2rr,
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        COALESCE(TRY(net_count*100.00/fe_count), 0) fe2net,
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",

        impression_count,
        click_count,
        COALESCE(TRY(click_count*100.00/impression_count), 0) "ctr",
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            sample_category,
            user_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT fare_estimate_id) fe_count,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,


           COUNT(DISTINCT impression_adid) as impression_count,
            COUNT(DISTINCT click_adid) as click_count,
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
        
        GROUP BY 1,2
        )
    ORDER BY 1,2


"""
curr_overall_df=pd.read_sql(curr_overall_query,conn)