## Imports

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [4]:
os.getcwd()
output_file = '/Users/E2074/local-datasets/customer/ads-monetisation/jas-plan'

## Datasets & Parameter

In [5]:
## Parameter 
start_date = '20240420'
end_date = '20240520'

# Convert date strings to datetime objects
start_dt = datetime.strptime(start_date, '%Y%m%d')
end_dt = datetime.strptime(end_date, '%Y%m%d')

df_customer_base = pd.DataFrame()
current_dt = start_dt

while current_dt <= end_dt:
    
    current_date_str = current_dt.strftime('%Y%m%d')
    
    customer_base_query = f"""
        SELECT 
            yyyymmdd,
            city_name,
            service_obj_service_name service_name,
            customer_id,
            order_id,
            order_status,
            spd_fraud_flag
        FROM 
            orders.order_logs_snapshot
        WHERE
            yyyymmdd = '{current_date_str}'
            and order_status = 'dropped'
            AND service_obj_service_name IN ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium',
                                            'CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro')
    """
    
    df_day = pd.read_sql(customer_base_query, connection)
    df_customer_base = pd.concat([df_customer_base, df_day], ignore_index=True)
    current_dt += timedelta(days=1)


df_customer_base.to_csv(output_file + '/customer_base_part2.csv', index = False)

In [6]:
# df_customer_base_final.to_csv(output_file + '/customer_base_final.csv', index = False)
df_customer_base_final = pd.read_csv(output_file + '/customer_base_final.csv')

rewards_query = f"""
    with unlocled as (
        SELECT
            yyyymmdd,
            user_id,
            order_id,
            rewards_external_id,
            rewards_type
        FROM 
            (
            SELECT
                yyyymmdd,
                user_id,
                rewards_transaction_id order_id,
                JSON_EXTRACT_SCALAR(rewards, '$.externalRewardMetaData.externalRewardId') rewards_external_id,
                -- rewards_state,
                rewards_type,
                epoch,
                ROW_NUMBER() OVER(PARTITION BY user_id,rewards_transaction_id ORDER BY epoch ) seq_no
                
            FROM 
                raw.kafka_pricing_scratchcards_immutable
            WHERE 
                yyyymmdd >= '{start_date}'
                AND yyyymmdd <= '{end_date}'
                AND rewards_state = 'UNLOCKED'
                AND rewards_type = 'EXTERNAL_REWARD'
                -- AND user_id = '6288c6694281e53bbe33d133'
            GROUP BY 1,2,3,4,5,6
            )
        WHERE
            seq_no = 1
    ),
    
    
    scratched AS (
        
        SELECT
            *
        FROM 
            (
            SELECT
                yyyymmdd,
                user_id,
                rewards_transaction_id order_id,
                rewards_state,
                rewards_type,
                JSON_EXTRACT_SCALAR(rewards, '$.externalRewardMetaData.externalRewardId') rewards_external_id,
                JSON_EXTRACT_SCALAR(rewards, '$.externalReward.partnerName') rewards_partner_name,
                JSON_EXTRACT_SCALAR(rewards, '$.amount') amount,
                epoch,
                ROW_NUMBER() OVER(PARTITION BY user_id,rewards_transaction_id ORDER BY epoch ) seq_no
            FROM 
                raw.kafka_pricing_scratchcards_immutable
            WHERE 
                yyyymmdd >= '{start_date}'
                AND yyyymmdd <= '20240528'
                -- AND user_id = '6288c6694281e53bbe33d133'
                AND rewards_state = 'SCRATCHED' 
            GROUP BY 1,2,3,4,5,6,7,8,9
            )
        WHERE
            seq_no = 1
        )
        
        SELECT 
            a.*,
            b.rewards_state rewards_state_updated,
            b.rewards_type rewards_type_updated,
            b.rewards_partner_name rewards_partner_name_updated,
            CASE WHEN b.rewards_type = 'COIN' AND b.amount = '0' THEN 'Better luck next time' ELSE b.rewards_partner_name END scratched_state
            
        FROM 
            unlocled a
        LEFT JOIN 
            scratched b
            ON a.yyyymmdd <= b.yyyymmdd
            AND a.user_id = b.user_id
            AND a.order_id = b.order_id

"""

df_rewards_v1 = pd.read_sql(rewards_query, connection)

In [7]:
df_rewards_v1 = pd.read_csv(output_file + '/rewards_v1.csv')

### Mapping

In [8]:
# # Define the mapping 
# mapping = {'Auto': 'Auto',
#            'Auto Pool': 'Auto', 
#            'Link': 'Link', 
#            'Bike Lite': 'Link', 
#            'Cab': 'CabEconomy',} 

# # Apply the mapping to the time_period column 
# df_customer_base['service'] = df_customer_base['service_name'].map(mapping)

## Data Schema

In [9]:
df_customer_base_final.head(2)

,yyyymmdd,city_name,service_name,customer_id,order_id,order_status,spd_fraud_flag
0,20240420,Delhi,CabEconomy,64bbe7e60c4ec46d25f0fb5d,662309cc5273492f21264510,dropped,False
1,20240420,Indore,Auto,662304fdc9dad6b18c25e8a2,6623054564e0ac4b47c7d2bf,dropped,False

In [10]:
df_rewards_v1.head(2)

,yyyymmdd,user_id,order_id,rewards_external_id,rewards_type,rewards_state_updated,rewards_type_updated,rewards_partner_name_updated,scratched_state
0,20240519,6182998316ec5217d5d3de21,6649b2927144a34c0f8e1b8f,6643172e3e1b91fc3591c411,EXTERNAL_REWARD,NaN,NaN,NaN,NaN
1,20240513,64db9895e4eb8c9eb1c544e1,66424f296afdf15098d890a0,6641f70c59683237cd2ba44c,EXTERNAL_REWARD,NaN,NaN,NaN,NaN

In [11]:
df_rewards_v1.scratched_state.unique()

array([nan, 'Better luck next time', 'Rummy Circle', 'My 11Circle',
       'Lenskart', 'OTT Play', 'Myntra', 'Jio Saavn', 'NewSanity1'],
      dtype=object)

In [12]:
df_rewards_v1.nunique()

yyyymmdd                              30
user_id                          6293418
order_id                        16645910
rewards_external_id                   28
rewards_type                           1
rewards_state_updated                  1
rewards_type_updated                   2
rewards_partner_name_updated           7
scratched_state                        8
dtype: int64

### Merge

In [13]:
df_merge = pd.merge(df_customer_base_final,
                    df_rewards_v1,
                    how='left',
                    left_on = ['customer_id', 'order_id'],
                    right_on = ['user_id', 'order_id']
                   )
        
df_merge.head(1)

,yyyymmdd_x,city_name,service_name,customer_id,order_id,order_status,spd_fraud_flag,yyyymmdd_y,user_id,rewards_external_id,rewards_type,rewards_state_updated,rewards_type_updated,rewards_partner_name_updated,scratched_state
0,20240420,Delhi,CabEconomy,64bbe7e60c4ec46d25f0fb5d,662309cc5273492f21264510,dropped,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_customers = df_merge.groupby(['customer_id']).agg(orders_bins = ('order_id' , 'nunique')).reset_index()
df_customers.shape

(12980809, 2)

In [20]:
df_customers.head(2)

                customer_id  orders_bins
0  5737c6adddbec2203f73316d            1
1  5737c6aeddbec2203f733176            4

In [21]:
df_merged = pd.merge(df_merge,
                     df_customers,
                     how='left',
                     left_on = ['customer_id'],
                     right_on = ['customer_id']
                    )
df_merged.head(1)

,yyyymmdd_x,city_name,service_name,customer_id,order_id,order_status,spd_fraud_flag,yyyymmdd_y,user_id,rewards_external_id,rewards_type,rewards_state_updated,rewards_type_updated,rewards_partner_name_updated,scratched_state,geo-level,orders_bins
0,20240420,Delhi,CabEconomy,64bbe7e60c4ec46d25f0fb5d,662309cc5273492f21264510,dropped,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN India,1

In [22]:
df_merge.shape

(48318962, 16)

In [23]:
df_merged.shape

(48318962, 17)

## User Defined func

In [24]:
df_merged['geo-level'] = 'PAN India'

In [29]:
agg_functions = {
    
    'start_date' : ('yyyymmdd_x', 'min'), 
    'end_date' : ('yyyymmdd_x', 'max'),
    'net_customers' : ('customer_id', lambda x: x[df_merged['order_status'] == 'dropped'].nunique()),
    'net_orders' : ('order_id', 
                    lambda x: x[(df_merged.loc[x.index, 'order_status'] == 'dropped')].nunique()),
    
    'sc_unlocked_customers' : ('customer_id', lambda x: x[~df_merged['rewards_external_id'].isna()].nunique()),
    'sc_scratched_customers' : ('customer_id', lambda x: x[df_merged['rewards_state_updated'] == 'SCRATCHED'].nunique()),
    'sc_scratched_earned_customers' : ('customer_id', lambda x: x[df_merged['rewards_type_updated'] == 'EXTERNAL_REWARD'].nunique()),
    
    'sc_unlocked' : ('order_id', lambda x: x[~df_merged['rewards_external_id'].isna()].nunique()),
    'sc_scratched_overall' : ('order_id', lambda x: x[df_merged['rewards_state_updated'] == 'SCRATCHED'].nunique()),
    'sc_scratched_earned' : ('order_id', lambda x: x[df_merged['rewards_type_updated'] == 'EXTERNAL_REWARD'].nunique()),
    'sc_scratched_not_earned' : ('order_id', lambda x: x[df_merged['rewards_type_updated'] == 'COIN'].nunique()),
}

In [30]:
def calculate_percentage(df, numerator, denominator):
    percentage = (df[numerator] * 100.00 / df[denominator]).round(2)
    return percentage

def calculate_percentage_columns(df, grouper_column):
    
    df['% scratch_rate overall'] = calculate_percentage(df, 'sc_scratched_overall', 'sc_unlocked')
    df['% scratch_rate earned'] = calculate_percentage(df, 'sc_scratched_earned', 'sc_unlocked')
    df['% scratch_rate not_earned'] = calculate_percentage(df, 'sc_scratched_not_earned', 'sc_unlocked')
    df['date_range'] = df['start_date'].astype(str) + ' - ' + df['end_date'].astype(str)
    
    list_agg_column = ['date_range', 
                       'net_customers', 
                       'sc_unlocked_customers', 'sc_scratched_customers', 'sc_scratched_earned_customers',
                       'net_orders', 
                       'sc_unlocked', 'sc_scratched_overall', 'sc_scratched_earned', 'sc_scratched_not_earned',
                       '% scratch_rate overall', '% scratch_rate earned', '% scratch_rate not_earned',]
    grouper_column.remove('geo-level')
    df_new = df[grouper_column + list_agg_column]

    return df_new

## Analysis

In [31]:
df_merged.head(2)

,yyyymmdd_x,city_name,service_name,customer_id,order_id,order_status,spd_fraud_flag,yyyymmdd_y,user_id,rewards_external_id,rewards_type,rewards_state_updated,rewards_type_updated,rewards_partner_name_updated,scratched_state,geo-level,orders_bins
0,20240420,Delhi,CabEconomy,64bbe7e60c4ec46d25f0fb5d,662309cc5273492f21264510,dropped,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN India,1
1,20240420,Indore,Auto,662304fdc9dad6b18c25e8a2,6623054564e0ac4b47c7d2bf,dropped,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN India,1

### 1. Platform level net rides on given time period?

In [32]:
grouper_column = ['geo-level']

df_overall = df_merged\
.groupby(grouper_column)\
.agg(**agg_functions)\
.sort_values(by=grouper_column)\
.reset_index()

df_overall = calculate_percentage_columns(df_overall, grouper_column)
df_overall

,date_range,net_customers,sc_unlocked_customers,sc_scratched_customers,sc_scratched_earned_customers,net_orders,sc_unlocked,sc_scratched_overall,sc_scratched_earned,sc_scratched_not_earned,% scratch_rate overall,% scratch_rate earned,% scratch_rate not_earned
0,20240420 - 20240520,12980809,6289993,1343558,730700,48318962,16633177,3807513,967358,2840155,22.89,5.82,17.08

Overall Opportunity Sizing
        
    - Customers 
        - Number of platform level net customers - ~1.3 Cr
        - Number of platform level net customers offered rewards (Distributed/Unlocked) - 6.2 M
        - Number of platform level net customers offered rewards (Scratched) - 1.3 M
        
    - Orders
        - Number of platform rides happening - ~4.3 Cr
        - Number of platform rides offered rewards (Distributed/Unlocked) - 1.6 Cr
        - Number of platform rides offered rewards (Scratched) - 3.8 M
        - Number of platform rides offered rewards (Earned) - 0.9 M


    - Benchmark 
        - % scratch_rate earned - 5.82 %
        - % scratch_rate not_earned - 17.08 %
        - % scratch_rate overall - 22.89 %

### 2. Customer level multiple-offer cuts

In [33]:
grouper_column = ['geo-level', 'orders_bins']

df_orders_bins = df_merged\
.groupby(grouper_column)\
.agg(**agg_functions)\
.sort_values(by=grouper_column)\
.reset_index()

df_orders_bins = calculate_percentage_columns(df_orders_bins, grouper_column)
df_orders_bins

,orders_bins,date_range,net_customers,sc_unlocked_customers,sc_scratched_customers,sc_scratched_earned_customers,net_orders,sc_unlocked,sc_scratched_overall,sc_scratched_earned,sc_scratched_not_earned,% scratch_rate overall,% scratch_rate earned,% scratch_rate not_earned
0,1,20240420 - 20240520,5250897,1714295,160731,87437,5250897,1714295,160731,87437,73294,9.38,5.10,4.28
1,2,20240420 - 20240520,2595578,1206328,178895,90164,5191156,1735672,224726,98127,126599,12.95,5.65,7.29
2,3,20240420 - 20240520,1414293,773030,147986,72385,4242879,1417531,223487,83080,140407,15.77,5.86,9.91
3,4,20240420 - 20240520,903220,542919,124088,61040,3612880,1219278,221223,73196,148027,18.14,6.00,12.14
4,5,20240420 - 20240520,603604,386260,100690,50357,3018020,1022613,206942,62857,144085,20.24,6.15,14.09
5,6,20240420 - 20240520,430655,289176,83214,42648,2583930,885766,194231,54904,139327,21.93,6.20,15.73
6,7,20240420 - 20240520,315712,221055,68717,35868,2209984,764464,179269,47596,131673,23.45,6.23,17.22
7,8,20240420 - 20240520,240013,172877,57258,30489,1920104,668336,164346,41440,122906,24.59,6.20,18.39
8,9,20240420 - 20240520,186411,137098,48442,26534,1677699,584829,152245,36936,115309,26.03,6.32,19.72
9,10,20240420 - 20240520,148789,111887,41249,22988,1487890,521294,140520,32768,107752,26.96,6.29,20.67
10,11,20240420 - 20240520,120034,92144,35375,20117,1320374,464994,130371,29236,101135,28.04,6.29,21.75
11,12,20240420 - 20240520,98152,76339,30306,17686,1177824,415671,119494,26198,93296,28.75,6.30,22.44
12,13,20240420 - 20240520,82112,64931,26503,15609,1067456,378146,111479,23643,87836,29.48,6.25,23.23
13,14,20240420 - 20240520,69022,55017,23192,14013,966308,342942,103875,21567,82308,30.29,6.29,24.00
14,15,20240420 - 20240520,58990,47809,20557,12609,884850,316071,96524,19758,76766,30.54,6.25,24.29
15,16,20240420 - 20240520,50610,41266,18068,11141,809760,288414,89208,17599,71609,30.93,6.10,24.83
16,17,20240420 - 20240520,43932,36254,16167,10044,746844,267919,84562,16110,68452,31.56,6.01,25.55
17,18,20240420 - 20240520,38301,31734,14545,9092,689418,244651,77200,14682,62518,31.56,6.00,25.55
18,19,20240420 - 20240520,33835,28354,13141,8350,642865,229981,73621,13666,59955,32.01,5.94,26.07
19,20,20240420 - 20240520,29670,25035,11722,7488,593400,212219,68588,12358,56230,32.32,5.82,26.50
20,21,20240420 - 20240520,26527,22451,10724,6941,557067,197808,64209,11592,52617,32.46,5.86,26.60
21,22,20240420 - 20240520,23496,19989,9602,6280,516912,183538,60158,10677,49481,32.78,5.82,26.96
22,23,20240420 - 20240520,20610,17736,8561,5651,474030,168343,55035,9705,45330,32.69,5.77,26.93
23,24,20240420 - 20240520,18662,16065,7873,5194,447888,159271,52512,8995,43517,32.97,5.65,27.32
24,25,20240420 - 20240520,16852,14661,7344,4875,421300,151793,50497,8542,41955,33.27,5.63,27.64
25,26,20240420 - 20240520,14962,13045,6658,4426,389012,139928,46914,7751,39163,33.53,5.54,27.99
26,27,20240420 - 20240520,13490,11835,6102,4138,364230,131307,45206,7388,37818,34.43,5.63,28.80
27,28,20240420 - 20240520,12248,10797,5566,3765,342944,122519,41314,6816,34498,33.72,5.56,28.16
28,29,20240420 - 20240520,10824,9611,5043,3404,313896,111610,38514,6073,32441,34.51,5.44,29.07
29,30,20240420 - 20240520,9644,8573,4492,3138,289320,104015,35400,5704,29696,34.03,5.48,28.55
30,31,20240420 - 20240520,8936,7972,4255,2934,277016,98690,33330,5328,28002,33.77,5.40,28.37
31,32,20240420 - 20240520,8098,7272,3896,2732,259136,91677,31672,5005,26667,34.55,5.46,29.09
32,33,20240420 - 20240520,7234,6544,3429,2451,238722,86451,28955,4462,24493,33.49,5.16,28.33
33,34,20240420 - 20240520,6727,6062,3188,2258,228718,82335,27593,4242,23351,33.51,5.15,28.36
34,35,20240420 - 20240520,6142,5541,3027,2121,214970,76609,25758,3973,21785,33.62,5.19,28.44
35,36,20240420 - 20240520,5593,5066,2804,2049,201348,71830,25353,3847,21506,35.30,5.36,29.94
36,37,20240420 - 20240520,5173,4721,2586,1819,191401,68938,23604,3500,20104,34.24,5.08,29.16
37,38,20240420 - 20240520,4693,4309,2469,1783,178334,63385,22632,3398,19234,35.71,5.36,30.34
38,39,20240420 - 20240520,4209,3845,2159,1570,164151,57877,19422,2914,16508,33.56,5.03,28.52
39,40,20240420 - 20240520,3928,3616,2041,1469,157120,57214,19489,2817,16672,34.06,4.92,29.14
40,41,20240420 - 20240520,3596,3295,1810,1330,147436,51752,17627,2566,15061,34.06,4.96,29.10
41,42,20240420 - 20240520,3289,3056,1680,1247,138138,50412,17556,2478,15078,34.83,4.92,29.91
42,43,20240420 - 20240520,2952,2732,1537,1136,126936,45382,15204,2183,13021,33.50,4.81,28.69
43,44,20240420 - 20240520,2782,2583,1454,1087,122408,44372,15124,2108,13016,34.08,4.75,29.33
44,45,20240420 - 20240520,2565,2400,1396,1005,115425,41219,14267,1971,12296,34.61,4.78,29.83
45,46,20240420 - 20240520,2240,2079,1141,858,103040,36619,12434,1735,10699,33.96,4.74,29.22
46,47,20240420 - 20240520,2004,1858,1090,811,94188,33792,12097,1653,10444,35.80,4.89,30.91
47,48,20240420 - 20240520,1809,1669,971,725,86832,30362,10361,1432,8929,34.12,4.72,29.41
48,49,20240420 - 20240520,1693,1589,889,647,82957,29750,9807,1299,8508,32.96,4.37,28.60
49,50,20240420 - 20240520,1563,1460,834,620,78150,28108,8833,1197,7636,31.43,4.26,27.17
50,51,20240420 - 20240520,1379,1305,749,563,70329,24635,8246,1188,7058,33.47,4.82,28.65
51,52,20240420 - 20240520,1228,1164,663,483,63856,23203,7889,976,6913,34.00,4.21,29.79
52,53,20240420 - 20240520,1046,993,546,413,55438,19702,6545,817,5728,33.22,4.15,29.07
53,54,20240420 - 20240520,966,924,557,440,52164,19141,6526,897,5629,34.09,4.69,29.41
54,55,20240420 - 20240520,899,859,498,396,49445,18019,6209,846,5363,34.46,4.70,29.76
55,56,20240420 - 20240520,798,757,427,320,44688,15998,5007,640,4367,31.30,4.00,27.30
56,57,20240420 - 20240520,764,719,420,313,43548,14923,4875,627,4248,32.67,4.20,28.47
57,58,20240420 - 20240520,624,594,338,263,36192,12720,3985,528,3457,31.33,4.15,27.18
58,59,20240420 - 20240520,549,523,293,219,32391,11800,3546,470,3076,30.05,3.98,26.07
59,60,20240420 - 20240520,534,507,295,214,32040,11528,3666,429,3237,31.80,3.72,28.08
60,61,20240420 - 20240520,488,463,290,215,29768,11075,3658,443,3215,33.03,4.00,29.03
61,62,20240420 - 20240520,413,398,239,186,25606,8941,2794,374,2420,31.25,4.18,27.07
62,63,20240420 - 20240520,390,366,214,164,24570,8564,2367,320,2047,27.64,3.74,23.90
63,64,20240420 - 20240520,329,314,182,144,21056,8060,2523,320,2203,31.30,3.97,27.33
64,65,20240420 - 20240520,274,264,149,112,17810,6250,1851,228,1623,29.62,3.65,25.97
65,66,20240420 - 20240520,283,266,159,124,18678,6740,2061,249,1812,30.58,3.69,26.88
66,67,20240420 - 20240520,267,251,153,114,17889,6489,2122,240,1882,32.70,3.70,29.00
67,68,20240420 - 20240520,228,219,134,104,15504,5813,1747,229,1518,30.05,3.94,26.11
68,69,20240420 - 20240520,216,211,133,103,14904,4994,1821,222,1599,36.46,4.45,32.02
69,70,20240420 - 20240520,204,196,113,88,14280,5146,1574,182,1392,30.59,3.54,27.05
70,71,20240420 - 20240520,195,186,108,76,13845,4590,1371,159,1212,29.87,3.46,26.41
71,72,20240420 - 20240520,146,138,79,64,10512,3767,1356,146,1210,36.00,3.88,32.12
72,73,20240420 - 20240520,160,152,100,79,11680,4141,1450,172,1278,35.02,4.15,30.86
73,74,20240420 - 20240520,121,115,70,50,8954,3179,906,112,794,28.50,3.52,24.98
74,75,20240420 - 20240520,127,119,76,60,9525,3605,1145,119,1026,31.76,3.30,28.46
75,76,20240420 - 20240520,118,113,65,49,8968,3273,961,108,853,29.36,3.30,26.06
76,77,20240420 - 20240520,102,98,60,44,7854,2646,877,87,790,33.14,3.29,29.86
77,78,20240420 - 20240520,115,112,64,46,8970,3137,926,90,836,29.52,2.87,26.65
78,79,20240420 - 20240520,87,85,47,39,6873,2558,764,85,679,29.87,3.32,26.54
79,80,20240420 - 20240520,100,96,74,54,8000,2840,1104,121,983,38.87,4.26,34.61
80,81,20240420 - 20240520,88,86,57,41,7128,2598,714,81,633,27.48,3.12,24.36
81,82,20240420 - 20240520,86,82,50,40,7052,2464,811,92,719,32.91,3.73,29.18
82,83,20240420 - 20240520,62,61,30,21,5146,1706,372,42,330,21.81,2.46,19.34
83,84,20240420 - 20240520,74,72,45,32,6216,1977,680,61,619,34.40,3.09,31.31
84,85,20240420 - 20240520,56,55,35,31,4760,1641,587,71,516,35.77,4.33,31.44
85,86,20240420 - 20240520,51,49,33,25,4386,1540,431,50,381,27.99,3.25,24.74
86,87,20240420 - 20240520,66,65,42,32,5742,2046,800,80,720,39.10,3.91,35.19
87,88,20240420 - 20240520,59,57,34,28,5192,1991,853,67,786,42.84,3.37,39.48
88,89,20240420 - 20240520,52,51,29,22,4628,1945,648,64,584,33.32,3.29,30.03
89,90,20240420 - 20240520,36,36,21,17,3240,1202,321,35,286,26.71,2.91,23.79
90,91,20240420 - 20240520,34,33,25,22,3094,1028,462,49,413,44.94,4.77,40.18
91,92,20240420 - 20240520,42,41,23,16,3864,1555,375,34,341,24.12,2.19,21.93
92,93,20240420 - 20240520,36,35,27,23,3348,1328,315,47,268,23.72,3.54,20.18
93,94,20240420 - 20240520,34,33,16,12,3196,1253,367,32,335,29.29,2.55,26.74
94,95,20240420 - 20240520,22,21,12,10,2090,845,272,27,245,32.19,3.20,28.99
95,96,20240420 - 20240520,30,30,23,21,2880,864,360,39,321,41.67,4.51,37.15
96,97,20240420 - 20240520,33,33,20,16,3201,1336,238,38,200,17.81,2.84,14.97
97,98,20240420 - 20240520,28,28,17,14,2744,1147,280,30,250,24.41,2.62,21.80
98,99,20240420 - 20240520,22,22,13,10,2178,826,299,20,279,36.20,2.42,33.78
99,100,20240420 - 20240520,21,20,13,11,2100,689,141,22,119,20.46,3.19,17.27
100,101,20240420 - 20240520,20,19,15,13,2020,714,315,33,282,44.12,4.62,39.50
101,102,20240420 - 20240520,29,27,19,14,2958,783,265,30,235,33.84,3.83,30.01
102,103,20240420 - 20240520,13,13,10,7,1339,486,212,18,194,43.62,3.70,39.92
103,104,20240420 - 20240520,16,16,9,8,1664,451,181,16,165,40.13,3.55,36.59
104,105,20240420 - 20240520,12,12,6,3,1260,595,154,14,140,25.88,2.35,23.53
105,106,20240420 - 20240520,16,16,10,6,1696,642,243,20,223,37.85,3.12,34.74
106,107,20240420 - 20240520,17,15,12,11,1819,556,266,23,243,47.84,4.14,43.71
107,108,20240420 - 20240520,13,12,5,4,1404,366,80,5,75,21.86,1.37,20.49
108,109,20240420 - 20240520,8,8,8,7,872,228,118,13,105,51.75,5.70,46.05
109,110,20240420 - 20240520,20,18,15,12,2200,583,294,34,260,50.43,5.83,44.60
110,111,20240420 - 20240520,16,16,12,11,1776,577,173,21,152,29.98,3.64,26.34
111,112,20240420 - 20240520,9,7,1,1,1008,287,14,2,12,4.88,0.70,4.18
112,113,20240420 - 20240520,5,5,2,1,565,283,14,2,12,4.95,0.71,4.24
113,114,20240420 - 20240520,9,9,8,8,1026,289,131,15,116,45.33,5.19,40.14
114,115,20240420 - 20240520,6,6,4,4,690,181,114,7,107,62.98,3.87,59.12
115,116,20240420 - 20240520,9,9,6,3,1044,348,67,7,60,19.25,2.01,17.24
116,117,20240420 - 20240520,6,6,6,5,702,348,133,10,123,38.22,2.87,35.34
117,118,20240420 - 20240520,6,4,3,3,708,225,15,6,9,6.67,2.67,4.00
118,119,20240420 - 20240520,9,8,5,5,1071,394,172,16,156,43.65,4.06,39.59
119,120,20240420 - 20240520,6,6,3,3,720,266,106,6,100,39.85,2.26,37.59
120,121,20240420 - 20240520,8,8,7,7,968,331,146,11,135,44.11,3.32,40.79
121,122,20240420 - 20240520,6,5,4,3,732,204,77,5,72,37.75,2.45,35.29
122,123,20240420 - 20240520,2,2,0,0,246,131,0,0,0,0.00,0.00,0.00
123,124,20240420 - 20240520,3,3,3,3,372,95,25,6,19,26.32,6.32,20.00
124,125,20240420 - 20240520,2,2,1,1,250,17,7,1,6,41.18,5.88,35.29
125,126,20240420 - 20240520,5,5,4,3,630,170,64,5,59,37.65,2.94,34.71
126,127,20240420 - 20240520,3,2,2,2,381,92,31,2,29,33.70,2.17,31.52
127,128,20240420 - 20240520,5,5,3,2,640,246,75,4,71,30.49,1.63,28.86
128,129,20240420 - 20240520,2,2,1,1,258,24,7,3,4,29.17,12.50,16.67
129,130,20240420 - 20240520,2,2,1,0,260,104,4,0,4,3.85,0.00,3.85
130,131,20240420 - 20240520,2,2,2,2,262,87,39,2,37,44.83,2.30,42.53
131,132,20240420 - 20240520,6,5,3,3,792,368,173,9,164,47.01,2.45,44.57
132,133,20240420 - 20240520,1,1,1,1,133,61,51,2,49,83.61,3.28,80.33
133,135,20240420 - 20240520,1,1,0,0,135,85,0,0,0,0.00,0.00,0.00
134,136,20240420 - 20240520,1,1,0,0,136,91,0,0,0,0.00,0.00,0.00
135,138,20240420 - 20240520,2,1,1,1,276,90,52,1,51,57.78,1.11,56.67
136,139,20240420 - 20240520,3,3,2,2,417,184,38,2,36,20.65,1.09,19.57
137,140,20240420 - 20240520,6,5,5,4,840,164,51,9,42,31.10,5.49,25.61
138,141,20240420 - 20240520,5,5,5,5,705,339,193,13,180,56.93,3.83,53.10
139,142,20240421 - 20240520,1,1,0,0,142,87,0,0,0,0.00,0.00,0.00
140,143,20240420 - 20240520,2,2,1,1,286,207,21,5,16,10.14,2.42,7.73
141,144,20240420 - 20240520,1,1,1,1,144,17,9,3,6,52.94,17.65,35.29
142,145,20240420 - 20240520,2,2,1,1,290,124,18,2,16,14.52,1.61,12.90
143,146,20240420 - 20240520,1,1,1,1,146,92,31,2,29,33.70,2.17,31.52
144,147,20240420 - 20240520,2,2,2,2,294,117,13,4,9,11.11,3.42,7.69
145,149,20240420 - 20240520,2,2,1,1,298,23,9,4,5,39.13,17.39,21.74
146,150,20240420 - 20240520,2,2,2,2,300,92,24,6,18,26.09,6.52,19.57
147,152,20240420 - 20240520,1,1,0,0,152,18,0,0,0,0.00,0.00,0.00
148,155,20240420 - 20240520,1,1,0,0,155,98,0,0,0,0.00,0.00,0.00
149,156,20240420 - 20240520,5,5,3,3,780,104,24,8,16,23.08,7.69,15.38
150,158,20240420 - 20240520,1,1,1,1,158,96,96,5,91,100.00,5.21,94.79
151,165,20240420 - 20240520,1,1,1,1,165,6,6,2,4,100.00,33.33,66.67
152,166,20240420 - 20240520,1,1,0,0,166,104,0,0,0,0.00,0.00,0.00
153,169,20240420 - 20240519,1,1,0,0,169,5,0,0,0,0.00,0.00,0.00
154,170,20240420 - 20240517,1,1,1,1,170,93,93,2,91,100.00,2.15,97.85
155,175,20240420 - 20240520,1,1,1,1,175,12,3,3,0,25.00,25.00,0.00
156,177,20240420 - 20240520,2,2,2,1,354,160,82,3,79,51.25,1.88,49.38
157,179,20240420 - 20240520,2,2,2,2,358,172,172,8,164,100.00,4.65,95.35
158,180,20240420 - 20240520,1,1,1,1,180,5,4,1,3,80.00,20.00,60.00
159,182,20240420 - 20240520,1,1,0,0,182,19,0,0,0,0.00,0.00,0.00
160,185,20240420 - 20240520,1,1,0,0,185,109,0,0,0,0.00,0.00,0.00
161,189,20240420 - 20240520,1,1,1,0,189,1,1,0,1,100.00,0.00,100.00
162,198,20240420 - 20240520,1,1,0,0,198,8,0,0,0,0.00,0.00,0.00
163,213,20240420 - 20240520,1,1,0,0,213,19,0,0,0,0.00,0.00,0.00
164,215,20240420 - 20240520,1,1,0,0,215,97,0,0,0,0.00,0.00,0.00
165,216,20240420 - 20240520,1,1,1,1,216,21,21,4,17,100.00,19.05,80.95
166,222,20240420 - 20240520,1,1,1,1,222,27,27,6,21,100.00,22.22,77.78
167,224,20240420 - 20240520,1,1,1,1,224,12,12,1,11,100.00,8.33,91.67
168,225,20240420 - 20240520,1,1,0,0,225,81,0,0,0,0.00,0.00,0.00
169,230,20240420 - 20240520,1,1,1,1,230,149,29,1,28,19.46,0.67,18.79
170,243,20240420 - 20240520,1,1,0,0,243,32,0,0,0,0.00,0.00,0.00
171,322,20240420 - 20240520,1,1,1,1,322,35,1,1,0,2.86,2.86,0.00
172,523,20240420 - 20240520,1,0,0,0,523,0,0,0,0,NaN,NaN,NaN
173,633,20240420 - 20240520,1,0,0,0,633,0,0,0,0,NaN,NaN,NaN

### 3. Service level net rides on given time period?

In [34]:
grouper_column = ['geo-level', 'service_name']

df_service = df_merged\
.groupby(grouper_column)\
.agg(**agg_functions)\
.sort_values(by=grouper_column)\
.reset_index()

df_service = calculate_percentage_columns(df_service, grouper_column)
df_service

,service_name,date_range,net_customers,sc_unlocked_customers,sc_scratched_customers,sc_scratched_earned_customers,net_orders,sc_unlocked,sc_scratched_overall,sc_scratched_earned,sc_scratched_not_earned,% scratch_rate overall,% scratch_rate earned,% scratch_rate not_earned
0,Auto,20240420 - 20240520,6776488,3630424,818634,413709,19721441,8785475,1958247,524244,1434003,22.29,5.97,16.32
1,Auto NCR,20240420 - 20240520,23489,0,0,0,38892,0,0,0,0,NaN,NaN,NaN
2,Auto Pool,20240422 - 20240520,12383,0,0,0,27033,0,0,0,0,NaN,NaN,NaN
3,Bike Lite,20240420 - 20240520,825614,0,0,0,2499237,0,0,0,0,NaN,NaN,NaN
4,Bike Metro,20240420 - 20240520,90059,0,0,0,152578,0,0,0,0,NaN,NaN,NaN
5,Bike Pink,20240420 - 20240520,2216,0,0,0,2568,0,0,0,0,NaN,NaN,NaN
6,CabEconomy,20240420 - 20240520,2334366,0,0,0,4362240,0,0,0,0,NaN,NaN,NaN
7,Link,20240420 - 20240520,7334687,3491726,722963,353725,21514973,7847702,1849266,443114,1406152,23.56,5.65,17.92

Service level only Link & Auto are distributed by rewards

- Link having 1% higher delta when compared with Auto

## Summary

In [35]:
df_overall

,date_range,net_customers,sc_unlocked_customers,sc_scratched_customers,sc_scratched_earned_customers,net_orders,sc_unlocked,sc_scratched_overall,sc_scratched_earned,sc_scratched_not_earned,% scratch_rate overall,% scratch_rate earned,% scratch_rate not_earned
0,20240420 - 20240520,12980809,6289993,1343558,730700,48318962,16633177,3807513,967358,2840155,22.89,5.82,17.08

In [36]:
df_orders_bins

,orders_bins,date_range,net_customers,sc_unlocked_customers,sc_scratched_customers,sc_scratched_earned_customers,net_orders,sc_unlocked,sc_scratched_overall,sc_scratched_earned,sc_scratched_not_earned,% scratch_rate overall,% scratch_rate earned,% scratch_rate not_earned
0,1,20240420 - 20240520,5250897,1714295,160731,87437,5250897,1714295,160731,87437,73294,9.38,5.10,4.28
1,2,20240420 - 20240520,2595578,1206328,178895,90164,5191156,1735672,224726,98127,126599,12.95,5.65,7.29
2,3,20240420 - 20240520,1414293,773030,147986,72385,4242879,1417531,223487,83080,140407,15.77,5.86,9.91
3,4,20240420 - 20240520,903220,542919,124088,61040,3612880,1219278,221223,73196,148027,18.14,6.00,12.14
4,5,20240420 - 20240520,603604,386260,100690,50357,3018020,1022613,206942,62857,144085,20.24,6.15,14.09
5,6,20240420 - 20240520,430655,289176,83214,42648,2583930,885766,194231,54904,139327,21.93,6.20,15.73
6,7,20240420 - 20240520,315712,221055,68717,35868,2209984,764464,179269,47596,131673,23.45,6.23,17.22
7,8,20240420 - 20240520,240013,172877,57258,30489,1920104,668336,164346,41440,122906,24.59,6.20,18.39
8,9,20240420 - 20240520,186411,137098,48442,26534,1677699,584829,152245,36936,115309,26.03,6.32,19.72
9,10,20240420 - 20240520,148789,111887,41249,22988,1487890,521294,140520,32768,107752,26.96,6.29,20.67
10,11,20240420 - 20240520,120034,92144,35375,20117,1320374,464994,130371,29236,101135,28.04,6.29,21.75
11,12,20240420 - 20240520,98152,76339,30306,17686,1177824,415671,119494,26198,93296,28.75,6.30,22.44
12,13,20240420 - 20240520,82112,64931,26503,15609,1067456,378146,111479,23643,87836,29.48,6.25,23.23
13,14,20240420 - 20240520,69022,55017,23192,14013,966308,342942,103875,21567,82308,30.29,6.29,24.00
14,15,20240420 - 20240520,58990,47809,20557,12609,884850,316071,96524,19758,76766,30.54,6.25,24.29
15,16,20240420 - 20240520,50610,41266,18068,11141,809760,288414,89208,17599,71609,30.93,6.10,24.83
16,17,20240420 - 20240520,43932,36254,16167,10044,746844,267919,84562,16110,68452,31.56,6.01,25.55
17,18,20240420 - 20240520,38301,31734,14545,9092,689418,244651,77200,14682,62518,31.56,6.00,25.55
18,19,20240420 - 20240520,33835,28354,13141,8350,642865,229981,73621,13666,59955,32.01,5.94,26.07
19,20,20240420 - 20240520,29670,25035,11722,7488,593400,212219,68588,12358,56230,32.32,5.82,26.50
20,21,20240420 - 20240520,26527,22451,10724,6941,557067,197808,64209,11592,52617,32.46,5.86,26.60
21,22,20240420 - 20240520,23496,19989,9602,6280,516912,183538,60158,10677,49481,32.78,5.82,26.96
22,23,20240420 - 20240520,20610,17736,8561,5651,474030,168343,55035,9705,45330,32.69,5.77,26.93
23,24,20240420 - 20240520,18662,16065,7873,5194,447888,159271,52512,8995,43517,32.97,5.65,27.32
24,25,20240420 - 20240520,16852,14661,7344,4875,421300,151793,50497,8542,41955,33.27,5.63,27.64
25,26,20240420 - 20240520,14962,13045,6658,4426,389012,139928,46914,7751,39163,33.53,5.54,27.99
26,27,20240420 - 20240520,13490,11835,6102,4138,364230,131307,45206,7388,37818,34.43,5.63,28.80
27,28,20240420 - 20240520,12248,10797,5566,3765,342944,122519,41314,6816,34498,33.72,5.56,28.16
28,29,20240420 - 20240520,10824,9611,5043,3404,313896,111610,38514,6073,32441,34.51,5.44,29.07
29,30,20240420 - 20240520,9644,8573,4492,3138,289320,104015,35400,5704,29696,34.03,5.48,28.55
30,31,20240420 - 20240520,8936,7972,4255,2934,277016,98690,33330,5328,28002,33.77,5.40,28.37
31,32,20240420 - 20240520,8098,7272,3896,2732,259136,91677,31672,5005,26667,34.55,5.46,29.09
32,33,20240420 - 20240520,7234,6544,3429,2451,238722,86451,28955,4462,24493,33.49,5.16,28.33
33,34,20240420 - 20240520,6727,6062,3188,2258,228718,82335,27593,4242,23351,33.51,5.15,28.36
34,35,20240420 - 20240520,6142,5541,3027,2121,214970,76609,25758,3973,21785,33.62,5.19,28.44
35,36,20240420 - 20240520,5593,5066,2804,2049,201348,71830,25353,3847,21506,35.30,5.36,29.94
36,37,20240420 - 20240520,5173,4721,2586,1819,191401,68938,23604,3500,20104,34.24,5.08,29.16
37,38,20240420 - 20240520,4693,4309,2469,1783,178334,63385,22632,3398,19234,35.71,5.36,30.34
38,39,20240420 - 20240520,4209,3845,2159,1570,164151,57877,19422,2914,16508,33.56,5.03,28.52
39,40,20240420 - 20240520,3928,3616,2041,1469,157120,57214,19489,2817,16672,34.06,4.92,29.14
40,41,20240420 - 20240520,3596,3295,1810,1330,147436,51752,17627,2566,15061,34.06,4.96,29.10
41,42,20240420 - 20240520,3289,3056,1680,1247,138138,50412,17556,2478,15078,34.83,4.92,29.91
42,43,20240420 - 20240520,2952,2732,1537,1136,126936,45382,15204,2183,13021,33.50,4.81,28.69
43,44,20240420 - 20240520,2782,2583,1454,1087,122408,44372,15124,2108,13016,34.08,4.75,29.33
44,45,20240420 - 20240520,2565,2400,1396,1005,115425,41219,14267,1971,12296,34.61,4.78,29.83
45,46,20240420 - 20240520,2240,2079,1141,858,103040,36619,12434,1735,10699,33.96,4.74,29.22
46,47,20240420 - 20240520,2004,1858,1090,811,94188,33792,12097,1653,10444,35.80,4.89,30.91
47,48,20240420 - 20240520,1809,1669,971,725,86832,30362,10361,1432,8929,34.12,4.72,29.41
48,49,20240420 - 20240520,1693,1589,889,647,82957,29750,9807,1299,8508,32.96,4.37,28.60
49,50,20240420 - 20240520,1563,1460,834,620,78150,28108,8833,1197,7636,31.43,4.26,27.17
50,51,20240420 - 20240520,1379,1305,749,563,70329,24635,8246,1188,7058,33.47,4.82,28.65
51,52,20240420 - 20240520,1228,1164,663,483,63856,23203,7889,976,6913,34.00,4.21,29.79
52,53,20240420 - 20240520,1046,993,546,413,55438,19702,6545,817,5728,33.22,4.15,29.07
53,54,20240420 - 20240520,966,924,557,440,52164,19141,6526,897,5629,34.09,4.69,29.41
54,55,20240420 - 20240520,899,859,498,396,49445,18019,6209,846,5363,34.46,4.70,29.76
55,56,20240420 - 20240520,798,757,427,320,44688,15998,5007,640,4367,31.30,4.00,27.30
56,57,20240420 - 20240520,764,719,420,313,43548,14923,4875,627,4248,32.67,4.20,28.47
57,58,20240420 - 20240520,624,594,338,263,36192,12720,3985,528,3457,31.33,4.15,27.18
58,59,20240420 - 20240520,549,523,293,219,32391,11800,3546,470,3076,30.05,3.98,26.07
59,60,20240420 - 20240520,534,507,295,214,32040,11528,3666,429,3237,31.80,3.72,28.08
60,61,20240420 - 20240520,488,463,290,215,29768,11075,3658,443,3215,33.03,4.00,29.03
61,62,20240420 - 20240520,413,398,239,186,25606,8941,2794,374,2420,31.25,4.18,27.07
62,63,20240420 - 20240520,390,366,214,164,24570,8564,2367,320,2047,27.64,3.74,23.90
63,64,20240420 - 20240520,329,314,182,144,21056,8060,2523,320,2203,31.30,3.97,27.33
64,65,20240420 - 20240520,274,264,149,112,17810,6250,1851,228,1623,29.62,3.65,25.97
65,66,20240420 - 20240520,283,266,159,124,18678,6740,2061,249,1812,30.58,3.69,26.88
66,67,20240420 - 20240520,267,251,153,114,17889,6489,2122,240,1882,32.70,3.70,29.00
67,68,20240420 - 20240520,228,219,134,104,15504,5813,1747,229,1518,30.05,3.94,26.11
68,69,20240420 - 20240520,216,211,133,103,14904,4994,1821,222,1599,36.46,4.45,32.02
69,70,20240420 - 20240520,204,196,113,88,14280,5146,1574,182,1392,30.59,3.54,27.05
70,71,20240420 - 20240520,195,186,108,76,13845,4590,1371,159,1212,29.87,3.46,26.41
71,72,20240420 - 20240520,146,138,79,64,10512,3767,1356,146,1210,36.00,3.88,32.12
72,73,20240420 - 20240520,160,152,100,79,11680,4141,1450,172,1278,35.02,4.15,30.86
73,74,20240420 - 20240520,121,115,70,50,8954,3179,906,112,794,28.50,3.52,24.98
74,75,20240420 - 20240520,127,119,76,60,9525,3605,1145,119,1026,31.76,3.30,28.46
75,76,20240420 - 20240520,118,113,65,49,8968,3273,961,108,853,29.36,3.30,26.06
76,77,20240420 - 20240520,102,98,60,44,7854,2646,877,87,790,33.14,3.29,29.86
77,78,20240420 - 20240520,115,112,64,46,8970,3137,926,90,836,29.52,2.87,26.65
78,79,20240420 - 20240520,87,85,47,39,6873,2558,764,85,679,29.87,3.32,26.54
79,80,20240420 - 20240520,100,96,74,54,8000,2840,1104,121,983,38.87,4.26,34.61
80,81,20240420 - 20240520,88,86,57,41,7128,2598,714,81,633,27.48,3.12,24.36
81,82,20240420 - 20240520,86,82,50,40,7052,2464,811,92,719,32.91,3.73,29.18
82,83,20240420 - 20240520,62,61,30,21,5146,1706,372,42,330,21.81,2.46,19.34
83,84,20240420 - 20240520,74,72,45,32,6216,1977,680,61,619,34.40,3.09,31.31
84,85,20240420 - 20240520,56,55,35,31,4760,1641,587,71,516,35.77,4.33,31.44
85,86,20240420 - 20240520,51,49,33,25,4386,1540,431,50,381,27.99,3.25,24.74
86,87,20240420 - 20240520,66,65,42,32,5742,2046,800,80,720,39.10,3.91,35.19
87,88,20240420 - 20240520,59,57,34,28,5192,1991,853,67,786,42.84,3.37,39.48
88,89,20240420 - 20240520,52,51,29,22,4628,1945,648,64,584,33.32,3.29,30.03
89,90,20240420 - 20240520,36,36,21,17,3240,1202,321,35,286,26.71,2.91,23.79
90,91,20240420 - 20240520,34,33,25,22,3094,1028,462,49,413,44.94,4.77,40.18
91,92,20240420 - 20240520,42,41,23,16,3864,1555,375,34,341,24.12,2.19,21.93
92,93,20240420 - 20240520,36,35,27,23,3348,1328,315,47,268,23.72,3.54,20.18
93,94,20240420 - 20240520,34,33,16,12,3196,1253,367,32,335,29.29,2.55,26.74
94,95,20240420 - 20240520,22,21,12,10,2090,845,272,27,245,32.19,3.20,28.99
95,96,20240420 - 20240520,30,30,23,21,2880,864,360,39,321,41.67,4.51,37.15
96,97,20240420 - 20240520,33,33,20,16,3201,1336,238,38,200,17.81,2.84,14.97
97,98,20240420 - 20240520,28,28,17,14,2744,1147,280,30,250,24.41,2.62,21.80
98,99,20240420 - 20240520,22,22,13,10,2178,826,299,20,279,36.20,2.42,33.78
99,100,20240420 - 20240520,21,20,13,11,2100,689,141,22,119,20.46,3.19,17.27
100,101,20240420 - 20240520,20,19,15,13,2020,714,315,33,282,44.12,4.62,39.50
101,102,20240420 - 20240520,29,27,19,14,2958,783,265,30,235,33.84,3.83,30.01
102,103,20240420 - 20240520,13,13,10,7,1339,486,212,18,194,43.62,3.70,39.92
103,104,20240420 - 20240520,16,16,9,8,1664,451,181,16,165,40.13,3.55,36.59
104,105,20240420 - 20240520,12,12,6,3,1260,595,154,14,140,25.88,2.35,23.53
105,106,20240420 - 20240520,16,16,10,6,1696,642,243,20,223,37.85,3.12,34.74
106,107,20240420 - 20240520,17,15,12,11,1819,556,266,23,243,47.84,4.14,43.71
107,108,20240420 - 20240520,13,12,5,4,1404,366,80,5,75,21.86,1.37,20.49
108,109,20240420 - 20240520,8,8,8,7,872,228,118,13,105,51.75,5.70,46.05
109,110,20240420 - 20240520,20,18,15,12,2200,583,294,34,260,50.43,5.83,44.60
110,111,20240420 - 20240520,16,16,12,11,1776,577,173,21,152,29.98,3.64,26.34
111,112,20240420 - 20240520,9,7,1,1,1008,287,14,2,12,4.88,0.70,4.18
112,113,20240420 - 20240520,5,5,2,1,565,283,14,2,12,4.95,0.71,4.24
113,114,20240420 - 20240520,9,9,8,8,1026,289,131,15,116,45.33,5.19,40.14
114,115,20240420 - 20240520,6,6,4,4,690,181,114,7,107,62.98,3.87,59.12
115,116,20240420 - 20240520,9,9,6,3,1044,348,67,7,60,19.25,2.01,17.24
116,117,20240420 - 20240520,6,6,6,5,702,348,133,10,123,38.22,2.87,35.34
117,118,20240420 - 20240520,6,4,3,3,708,225,15,6,9,6.67,2.67,4.00
118,119,20240420 - 20240520,9,8,5,5,1071,394,172,16,156,43.65,4.06,39.59
119,120,20240420 - 20240520,6,6,3,3,720,266,106,6,100,39.85,2.26,37.59
120,121,20240420 - 20240520,8,8,7,7,968,331,146,11,135,44.11,3.32,40.79
121,122,20240420 - 20240520,6,5,4,3,732,204,77,5,72,37.75,2.45,35.29
122,123,20240420 - 20240520,2,2,0,0,246,131,0,0,0,0.00,0.00,0.00
123,124,20240420 - 20240520,3,3,3,3,372,95,25,6,19,26.32,6.32,20.00
124,125,20240420 - 20240520,2,2,1,1,250,17,7,1,6,41.18,5.88,35.29
125,126,20240420 - 20240520,5,5,4,3,630,170,64,5,59,37.65,2.94,34.71
126,127,20240420 - 20240520,3,2,2,2,381,92,31,2,29,33.70,2.17,31.52
127,128,20240420 - 20240520,5,5,3,2,640,246,75,4,71,30.49,1.63,28.86
128,129,20240420 - 20240520,2,2,1,1,258,24,7,3,4,29.17,12.50,16.67
129,130,20240420 - 20240520,2,2,1,0,260,104,4,0,4,3.85,0.00,3.85
130,131,20240420 - 20240520,2,2,2,2,262,87,39,2,37,44.83,2.30,42.53
131,132,20240420 - 20240520,6,5,3,3,792,368,173,9,164,47.01,2.45,44.57
132,133,20240420 - 20240520,1,1,1,1,133,61,51,2,49,83.61,3.28,80.33
133,135,20240420 - 20240520,1,1,0,0,135,85,0,0,0,0.00,0.00,0.00
134,136,20240420 - 20240520,1,1,0,0,136,91,0,0,0,0.00,0.00,0.00
135,138,20240420 - 20240520,2,1,1,1,276,90,52,1,51,57.78,1.11,56.67
136,139,20240420 - 20240520,3,3,2,2,417,184,38,2,36,20.65,1.09,19.57
137,140,20240420 - 20240520,6,5,5,4,840,164,51,9,42,31.10,5.49,25.61
138,141,20240420 - 20240520,5,5,5,5,705,339,193,13,180,56.93,3.83,53.10
139,142,20240421 - 20240520,1,1,0,0,142,87,0,0,0,0.00,0.00,0.00
140,143,20240420 - 20240520,2,2,1,1,286,207,21,5,16,10.14,2.42,7.73
141,144,20240420 - 20240520,1,1,1,1,144,17,9,3,6,52.94,17.65,35.29
142,145,20240420 - 20240520,2,2,1,1,290,124,18,2,16,14.52,1.61,12.90
143,146,20240420 - 20240520,1,1,1,1,146,92,31,2,29,33.70,2.17,31.52
144,147,20240420 - 20240520,2,2,2,2,294,117,13,4,9,11.11,3.42,7.69
145,149,20240420 - 20240520,2,2,1,1,298,23,9,4,5,39.13,17.39,21.74
146,150,20240420 - 20240520,2,2,2,2,300,92,24,6,18,26.09,6.52,19.57
147,152,20240420 - 20240520,1,1,0,0,152,18,0,0,0,0.00,0.00,0.00
148,155,20240420 - 20240520,1,1,0,0,155,98,0,0,0,0.00,0.00,0.00
149,156,20240420 - 20240520,5,5,3,3,780,104,24,8,16,23.08,7.69,15.38
150,158,20240420 - 20240520,1,1,1,1,158,96,96,5,91,100.00,5.21,94.79
151,165,20240420 - 20240520,1,1,1,1,165,6,6,2,4,100.00,33.33,66.67
152,166,20240420 - 20240520,1,1,0,0,166,104,0,0,0,0.00,0.00,0.00
153,169,20240420 - 20240519,1,1,0,0,169,5,0,0,0,0.00,0.00,0.00
154,170,20240420 - 20240517,1,1,1,1,170,93,93,2,91,100.00,2.15,97.85
155,175,20240420 - 20240520,1,1,1,1,175,12,3,3,0,25.00,25.00,0.00
156,177,20240420 - 20240520,2,2,2,1,354,160,82,3,79,51.25,1.88,49.38
157,179,20240420 - 20240520,2,2,2,2,358,172,172,8,164,100.00,4.65,95.35
158,180,20240420 - 20240520,1,1,1,1,180,5,4,1,3,80.00,20.00,60.00
159,182,20240420 - 20240520,1,1,0,0,182,19,0,0,0,0.00,0.00,0.00
160,185,20240420 - 20240520,1,1,0,0,185,109,0,0,0,0.00,0.00,0.00
161,189,20240420 - 20240520,1,1,1,0,189,1,1,0,1,100.00,0.00,100.00
162,198,20240420 - 20240520,1,1,0,0,198,8,0,0,0,0.00,0.00,0.00
163,213,20240420 - 20240520,1,1,0,0,213,19,0,0,0,0.00,0.00,0.00
164,215,20240420 - 20240520,1,1,0,0,215,97,0,0,0,0.00,0.00,0.00
165,216,20240420 - 20240520,1,1,1,1,216,21,21,4,17,100.00,19.05,80.95
166,222,20240420 - 20240520,1,1,1,1,222,27,27,6,21,100.00,22.22,77.78
167,224,20240420 - 20240520,1,1,1,1,224,12,12,1,11,100.00,8.33,91.67
168,225,20240420 - 20240520,1,1,0,0,225,81,0,0,0,0.00,0.00,0.00
169,230,20240420 - 20240520,1,1,1,1,230,149,29,1,28,19.46,0.67,18.79
170,243,20240420 - 20240520,1,1,0,0,243,32,0,0,0,0.00,0.00,0.00
171,322,20240420 - 20240520,1,1,1,1,322,35,1,1,0,2.86,2.86,0.00
172,523,20240420 - 20240520,1,0,0,0,523,0,0,0,0,NaN,NaN,NaN
173,633,20240420 - 20240520,1,0,0,0,633,0,0,0,0,NaN,NaN,NaN

In [38]:
df_orders_bins.head(100).to_clipboard(index=False)