## Imports

In [5]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [6]:
from pyxlsb import open_workbook

In [7]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [8]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [9]:
# Load data from 'Elite Customer data.xlsb'
file_path = "Elite Customer data.xlsb"  # Ensure this file is in your current directory

# Read a specific sheet (replace 'Sheet1' with the actual sheet name)
df = pd.read_excel(file_path, sheet_name='Sheet1', engine='pyxlsb')

## Datasets & Parameter

In [10]:
df

,city,gender,user_id,customer_obj_mobile,taxi_retention_segments,Customer_Obj_Name
0,Delhi,female,625d1422b9eaf550004a3b6f,8178430135,ELITE,Pooja
1,Delhi,male,5daa690a52047954050e05e9,9667116049,ELITE,Sunny Vats
2,Hyderabad,male,64b98f0f218ffc447c9ad73a,9849410041,ELITE,Parthiban Abhiramacheri
3,Bangalore,male,642086d1c541dacb4f19f7f5,9845720987,ELITE,Vijaykumar S
4,Bangalore,male,602b3a2319e49823b91f6641,8130507623,ELITE,Vishesh Verma
...,...,...,...,...,...,...
824,Mumbai,female,63b1293aa9f27531da9eed81,9665725753,ELITE,Sunita Nair
825,Mumbai,female,65dd5ab9fc33e16621c4e223,7887753543,ELITE,Chandni Khatri
826,Mumbai,female,625d9ed3797562256b3bed6b,9930790789,ELITE,Yukta Borkar
827,Mumbai,male,67623e714a965b2ba8d40e2c,9819861820,ELITE,Amey
828,Mumbai,female,627267b1975f02c8bbc2c08e,7506863180,ELITE,Tejaswini Rahate

In [30]:
df.user_id.nunique()

812

In [12]:
customer_list = df['user_id'].to_list()
len(customer_list)

829

In [29]:
829 - 842

-13

In [15]:
customer_str = ", ".join(f"'{customer}'" for customer in customer_list)
print(customer_str)

'625d1422b9eaf550004a3b6f', '5daa690a52047954050e05e9', '64b98f0f218ffc447c9ad73a', '642086d1c541dacb4f19f7f5', '602b3a2319e49823b91f6641', '661d07f69c553250f4663dac', '65cab9d06cc0ecbf0e4ae24a', '66c5e5e87e612e28343ac5bd', '63d366cdf17fa764ceedf141', '5cf4a712c0b26018f5d7210e', '62db6a8fcb61570f63578a18', '65f854ba0087bd4d5f4afd79', '629b5e02a9c7b43889fbb098', '630da253744a5c204181e8dd', '641d25a4a4eb4702b8ab85f0', '5fc9a6c45441f851e343a732', '5d77b94bd0286d106d84539e', '61b5e04a61bb51102dcbcbf5', '5cc2b3713d65ca5e2563617a', '62c230ba17af9a77be69731d', '5e46851e981e4336e2e20f22', '63ecd808d6d9b2097fe87c5a', '627b59f4c75b904f52072a1b', '656ef8f7100f1b7ab43c0dc5', '6702e9a53d68e97659d6737f', '5cf4a712c0b26018f5d7210e', '5d56259455fbf50d45f72f27', '675a78e75bff40bffb47d1df', '65b61a23157cf55fe4e60d9e', '60f6febb8f3479d97d1adebe', '63fe44288e212c64f44ab363', '6115012b8dddcb578c6d0eaf', '6641fc1c54d49f2b96e7c248', '65f698117ca1e4915fad39b7', '661415a2c142c14d90144cd2', '62456e2e5fd0224ece693f3a', '653464edefd5ea98845a0880', '674e88c99fd6047e3341d72c', '64899db5f91ba30320f4c408', '65927f8cc2bc4f50af783a8f', '5f5a1b2d9672eb161e6828ad', '652613d9947e7725774b2a7b', '6769493fa171d63d5a719103', '66efeead12c16a1a9e7a474a', '668e141c3d08a0e26e88114a', '5d96db5b941a7d1c51d39e77', '6689767e5046441b73ba6139', '63be4c8de7c64258ca6a34da', '5d699498d0286d106d6e2149', '639d2b4eadb2f2a11591f3e5', '623c54d2b9a21e58a7ccdf6f', '6483b02aa5165d225683252c', '62aaa7ce7b34ac629c26f0d0', '64706629901c8fc4c95fb5f8', '63a18572bdc65a8ce6a023d5', '63888ec81f92ae902caefbac', '593fb6a35d2e2a3565be9401', '67665cee95ea87e413d3af06', '5fea06d94319a722fab80546', '62c264ac17af9a129c699aef', '64cb886f31d8dd49dd9b8b0c', '65d09a35ef37b018261a60e5', '63c3d1486901fb5f664f62ad', '61f426ecebef82867327e466', '60ffcf107b23c8aa0ba6332c', '59afb3cfe9c3aa253ddef68b', '6283bf6429a4a01f6b015b42', '60bf68d7270b9c442ee18307', '66d73b86ff13445e81330d05', '61f781896916b84875afb288', '66ab87e8ebc0d2223a6e7d35', '5d399fc09996733edb00ec31', '65413bee2dc35a3c47b5086e', '668ec797bef3c9c20258a799', '61d05b80a75746ae94e4ea29', '66d90fb6681733691aa4a511', '63957f4708e36da5b8254d1f', '61a653c417dd6abc32060d74', '663646ae051e29e3287b83de', '661a83322944354d89a0b4d4', '5d81c60fd0286d106d94a424', '6633b664a0942ac8d46105c9', '573f29139b0ffc283677665c', '62e227ab5b3d20bd4d34358c', '5fdb7cf6bb140a0c77b02b28', '66e66e4eedbab5bbfeafe2e5', '5b7a2caeab09737a50f90b27', '642039a61dfee2273578e82e', '62dd63b4cb6157828d592367', '63f3bc9f0bf08090022f3bbc', '671d48b86bd8d149ab5fd741', '671f6dc8ba70e6baeeb4e73a', '67644613ed568cd927614819', '6424089c9a0e93b2685ba882', '642271ca5df907c52d6778ab', '64e4770d143ba33bd0eedf5f', '64a8cf4af1bf6856b3ac0920', '659a869b1db2220a5f49f16a', '65585746580653acfce71342', '5c20e2f5d9bacb2f6f9e26de', '5b45b49ba034a4279225d38e', '646706476c2c5d7355a09fe0', '67415e2c2bfa95f33516b6eb', '6625f7f322754e8f53555139', '61ff8d09d2ae40b8d49715e5', '6241561c5a102b7212b65d8d', '6698a80eb182a444a4d3a572', '66851d6737e9a33149854ee5', '66aefd87d12aac182fc53704', '5e4e23331146d681ff45bcb0', '66d84d20f7550237c69039bc', '634193978c74c568cae0cdf1', '662e708cba5292320f2b9057', '5dd8d5a453a0f569a71c54f6', '604f4dbeb07070bcaeefcec0', '5cbdeb9f54bc7263ff47feea', '6333cce05ef3d71b01ee54b2', '66d1f39ee7887919415d83c0', '650f0052d4499c4951d574a0', '65637401a93905826be9026b', '627cddb6dc46f370cf1c1c4b', '5e42345a6c87f11b5c8f7ba6', '64460791e63c5baabc6f69eb', '678ca5174768c015f821b5e6', '625e4e8b797562309b3c4e82', '5e6f00b52f5b269b58e196b6', '610a808606f56f9292a8514f', '6616b7e85b004e16f3b3c384', '63b858d3404a6e78e2abb4b8', '61a80eecf3de6f0a363fd01e', '658544e17da060f99f32f2cf', '662df4356af9127715ba2087', '629ae19b1b57e4a1cfe67394', '624f210efc8d846b88ace526', '6395e2cc22af926590ba51c8', '5da6d41d941a7d1c51e8aec6', '651809297b04310ba9296e0b', '66ab87e8ebc0d2223a6e7d35', '620bb69d677997847b1429df', '5e65ba64a1647575ee9799d0', '6753c93b218132cd6fcde1ab', '5db7d140c54ee1212529b241', '64d9212f6e299f27ec003d09', '67455e14353da47eac14eac3', '661ab1dcd3cadf2624ed75d1', '66d665e51601e849209c4a62', '66ab14035e1a95dc41c5d7a6', '6269021740b3e5216dc078aa', '5ef9de883609b83eecd74d22', '62a8a07c5df25c08e03d65d2', '5c72e1e3343a5357615c6e09', '630121487c613802a6254c57', '5d8e6090941a7d1c51c85544', '61db57d3fb8e4d19ba314c79', '5dc41d14079aed53a6fe046b', '638de74f1952d827b67c5b2f', '6754035764d2b7c65258627b', '601c163791cc11e265b520d5', '66175f2334bf60208decf7dc', '67602d6617b102345dfc67b4', '650ec5ce79e8af721e169ca1', '5c23444d4a267149c75d6050', '6757bf17fd36307b93312291', '653464edefd5ea98845a0880', '622829b1e6c6b60bd34aeb75', '66f5673d2197924fd5921129', '65c62f662b682d572d090fd5', '64abfbb652841995e72f98ea', '6420c3f2550f0a15853c23e4', '6347e00f4d1d9407362ef354', '5ceeb09b25ee3218d4ea636b', '617e5f5c16ec521fecd12764', '658c23ecd9b0e7c3b74549aa', '60e3ffe8569b2680fa720799', '66761daa3636ab5e1126d160', '64a8d0ca3d4c6c382dc867f0', '636667587337c90452ba58aa', '655a20ad79947625a5048fbc', '661360a92a6d8682dde8a6f9', '65ec1095067422eb459a3433', '66834259a052eebdd02baa5d', '670fb0dd4491a6b4ab35b53b', '652a8b483847e2dae37bf333', '60c0543c270b9cd2ebe1ba2e', '6156b88a953ffc4f9676c98c', '641cd9d7946b0f13dd29d1e0', '5b129a8ad7f02472c28c5180', '5ae32fb1df428a75be04db6d', '62ab26abd3109e3aa93a920e', '669dcb8422ad7d8f44fcf495', '5d42d1e501176418cc60bd1b', '615e7d3b77c7e6a144931b7f', '626a553979756280e843d362', '6654874afc4eb917bf4120f1', '638d58cb0ae82dfc0b7b6473', '644fbd699699a7dcb4fcb8a2', '6264cabaecbc420a0bca5275', '60ed1fa2ac6ff47b2d62b35b', '5c94f32d8c352421eaf6d5c9', '5d528426bde10e0d543bf62d', '613346840a1f1b68f9f7bff1', '66757f1f2f84ea1490c36b13', '677cbd12320b5ab24984a0ea', '6620c590560fb3b73ef9fa05', '65cf1db5dc9af69e5c027a69', '63a5dd9a00d79e392466643d', '6450edd88fac8a5ec4c66625', '5ae886112afde368e9c797cd', '5d3ad8fd9996733edb026999', '5e345eac86bdf5cf368fc9de', '649071df93f597a87884358c', '60f2304b8f34790ca91833f0', '63f8b15e093fe71bcfbf5eaa', '600bf273027f2582b2a1b9a6', '5fcf1b1e1eb6a75e999eabec', '654b43e344862543febc9c4e', '64eaf1f85a6ec77d96bde080', '66422a2d929576aabfabc116', '6444024333c02957f523cb9a', '65a14489bffa3ed75bf51f77', '63941cd669f1f017f09fd343', '644f541e9699a709affc59f6', '6508041647166b8549577c6c', '63b98a7acb153326678ce689', '6565bcfb172b741e651b0a9f', '62bd5cd416a2a764e956f20b', '63e7a234b5e7158b9fd65a43', '674ff1e80060ea290346295c', '61c0685a17dd6afab4196ced', '6067d952b26846cf73db3df2', '646c39d99a77741331307e7f', '67878984923fd4f31e972b2f', '6498741904fb2b7a8276a4bb', '6761767ba6d75efe5b02baac', '62c1c955d9dd8942a371a945', '6673f50326174a2ab42c9cc8', '6255bc61b4846f71638bd9b2', '613b4ae0b6866c0bf57ea0cf', '6738dd52a0661888e1c4da48', '65331d19bb1bff61195dd57d', '663e39206204f94c6af8de21', '5cd57d86d2ee6e6cf2e046fa', '663f286c54d49f169c763230', '643ade4817641a3864aad238', '64637602718a2754ab3c7a73', '5dd346c659e2e3257f74a806', '668111773d028a0300bfd18b', '610b7970ed6ff4213056b25e', '64a13272d2cad572b302d751', '625579a07ee64189ab536dec', '60f9769ed417d45e207d77ba', '622575acfe738534b22d7b7a', '67545f6f6841a478924a907e', '6730a609d858ef740d8947fd', '628bf7cc3a744977325f19a4', '5f633a63d477027e1c53a70d', '63148f8ad9aff237537031c3', '64d8c0ca143ba38bc37ff807', '641d1046ab1ed1707b9bda95', '5d399fc09996733edb00ec31', '5dfe7426dc631c72b9fbdaf2', '5902e15fd854235518362b21', '677b78797d522644aee9a562', '64c49e424840dbf35986c32d', '6466ef96b4a32c2423417fcb', '67602dbb2fc6ad41e678618e', '63f9eb6a0bf080731e33870f', '5dc8168b907d93538e40b1c0', '631ff69dacf22a8554a6b5e6', '6723827c7567360b07cae19e', '676439e5ab4605788626745e', '67838f8dda7bab56d941aec6', '626bf091eafec9810f59427b', '5cc1788d54bc7263ff4d7aac', '66e66e4eedbab5bbfeafe2e5', '63df05a299ac6457336957db', '663c62c7d8bc1ad1235d1a17', '650eb1c102966a74116cee53', '66a94be5d12aac0eeadb0745', '6312d3a350fdb54f97d5f272', '6271d0e120022e1a268582cd', '6767fc18db31197fde008804', '649da2db426b5f1fcfdfc475', '623ee2846ac420a5f5516b9c', '63236627790e6a8794859c1b', '5dee29c61a882e3354ba4f04', '62a5a1514becf63b65314f09', '64ca01b957a12fbb2def67e4', '5d3326a9f8fc6575c0873bbc', '5d563eddbde10e0d5440e48a', '6791d11f13806380f39d31c6', '6482ce6dc7aada4c1225b87f', '5dc6fd8b079aed53a6045769', '61b0ca8e955fb20394ea507b', '5c1ddb9ed9bacb2f6f9c2423', '5dca934e010c5a4601fc35ce', '5f11556f24d6295303b1125d', '66eff085ac1bfa57a906c94b', '66c3f5f8246d7e815c98fcf7', '676932f6e45afa5e453ff867', '615f00087fefc54e968b45b9', '66a661c902a401aaf3b7f810', '6350bc8e40f1041d691b7844', '638605d17064af7d784a7039', '65af9c02414b191a8def8879', '5b84c89641aec06e4212d67a', '6399452635e841e843d800b2', '633dce6ce90ec6398f7f28d8', '665551a1cd38d45d16faab07', '5dfd1822a9d65972a3531a8c', '66b0485d0c634a5b3777f4a4', '67a01958c3d410aa8d16d10d', '653333b73c58b35c964ab340', '6283ccc0e6802e6361b439ab', '673053d39297b385b5a43843', '633a436be90ec6acf67d12d6', '605dd5c3476329d2c0612b1e', '639df45ccd56c04285838951', '5c6c48d721163e7a7c54b483', '6746e590c746f4830e54b69f', '657c825a22df37e26c4e89b6', '67638899bdacf25ab58ed626', '5a8d6f53fa4af239b7fdb271', '65330a85bb1bff1dc25b5e3c', '6355ee5885b3996d764efcbe', '5cf36916c0b26018f5d617c3', '5b659307004974653d390b6f', '672f95df83900b0368cc8fe4', '607fa567f58375baf8b284df', '667da861515079030dfaa47c', '669ce0d1cc248f7f167e49aa', '62ee87ec8c0c5c64f9ad9bef', '62d3eac5d0596368d6af9a9b', '62f9eb434831de735d32eba6', '60fd36f0a0ea0d166f741678', '5a9f78262314ba427eed6420', '64fa05cf1ce35a45576568cf', '65cc63d97b7dc80a43b60d5f', '66f1264e12c16a1de0ae4558', '6222f8f6c1a4e45637645638', '6623ab543ec5dc0cb24540b4', '634c32648cfdc97c620f7b1a', '67838cac13a4a4385d7c93a1', '62988020ab4bf15b6a1b40c6', '60c828cfbe7e7cffaf1db03d', '5d106bf4c2a56b449fa20344', '66b0f51939a64ef37bc92940', '623dc0596e78d127b7f7c33d', '65500e8fe10b6e744d01a630', '66056bd0f2c51f7b6eb00efc', '66a1c5e0e0586419d45bf5cf', '5d137fb2b6097734094e23b8', '5fd911068e98075afcb6d7e3', '66ded40c2c6cf35e89484634', '5c8da0ee8c352421eaedf89c', '66aa3fdd98009af868e113d8', '669a39dba9c5cb09c694c597', '630f5dcb9c868b0e358d5e88', '5de0f58c890e14220648a29c', '63758cacd4369dff8a6fbad1', '665339271fbb990abe462e05', '64de504e07d31982f5c4f5c7', '63385858dd94e3c310576200', '623fca2db9a21e44ebcf0bb3', '6537abf6b5145a56fba2a866', '5b8e7c92cd63c759405f5cb5', '5dd386ea1f60ef2568f08c3a', '62cdf78f551cdb45c2c3e56a', '6507c80e99739d3346eb99d9', '64d7ba7ae216f99dcf777231', '646c53fa4d2117267fa644ac', '640ea7502573f6e0a5a7a869', '6355579f9909ffb22f7c0a39', '64d7ba7ae216f99dcf777231', '64bb6b5e9831bc581d10a64c', '5b265b3364523d06b896df08', '5d2ddc536ed7674e6114c88b', '6380c1c30ed41c66a02e94bc', '645671d50b5c2786800e5e9f', '65cb9ef863f0212efb8888f8', '5dc6601a079aed53a602bdaf', '655b7ee43664844e5ed743f3', '5e004ac1dc631c72b9fd5193', '664395e0d120e4232bf7fb69', '60e5710c09aa9907c741a5d1', '678e3c6b0042a496e240ec6e', '62a318327d7967116ee41044', '65d56a8f777f4a5ffb25d096', '5d7d3c43a24c96105e4e71eb', '615498d18fb56a04a618bd61', '6630a22bf0f7835673f583e0', '6305b549ca3c324876921a9f', '5d5ecd73a24c96105e1f5c38', '5d7d3c43a24c96105e4e71eb', '63482a2d7e67c8dcfbbf0924', '60669b05d54270596e92f138', '65a0c2c4a1645d3ac037c426', '5e26bc256d833e02b9b98543', '6232b4126f6ad06519572573', '6242870ec18d8272a6191d7c', '66862bf6253469678d65d3e1', '6688137c2fe345215bc6bd31', '618ab27115672fc0aa83e079', '63a30f4975c11b104ac99b08', '63a198b10cd851a778fe3fdb', '608073faf583759b45b2ed99', '64f43d9fae82cc5e04c68549', '60705d4e7761604ace19cc19', '66caf3bd03229bbeb7cf1a43', '61613232812c788edab0ba6b', '62a9562d9d10c91288892e85', '5ddfb625a5cb3035eee73630', '6717720f225acb1cf1f6e516', '5c28fc014a267149c7614b14', '63751d7b83ee539dcc3f4d12', '661ab1dcd3cadf2624ed75d1', '65e6a5e1d8310ceac0670358', '6762a199a9b00e8c1e313e7c', '656c6179e11ea9b67b6af406', '605294135e55c32fbdcfc21b', '661c1242f86042c7a68bcfdd', '6395e2cc22af926590ba51c8', '649fa55c135f4b2801e54d29', '5d735ceda24c96105e3e18c9', '65faa6450a450747d34baec6', '659fcaab361868710f30f237', '632f07df316a55ef5f71fc7d', '63458568630369f63c3fd5be', '5f077ab5e8c1271cceb0966e', '62f9d330efdf7d2c2438f8f9', '67116c3d69597312aec78894', '5cf4cf24c0b26018f5d75aaf', '6655c9283ecd5837fef3d9ed', '635925fd854c2574a6b29808', '65bf4466500c32beef042dc9', '65cd89cc04017e8c4531bf97', '64eca2615a6ec7291207c0cd', '611dcd7f6a8985792bb94d8f', '62909f81e5106fde309e4a55', '5dc901b58119a030d4b9956b', '66023506a9381b2ed213768a', '6706061cd0576418b89a5ef2', '66cfe52c77a80023d178b598', '62c99307551cdb26d9c0c4f0', '66d05231255b89b027284f2e', '66fac87405d5f9156d0bddde', '645e68f4af7f5abebcce8102', '66633bcef883d50e21c2487c', '6378ecfc044d6d15200042d5', '65af33fe7c50e32fb344d57c', '65d46fbeb8921ed24fbec704', '630b7426f28b23520be7f210', '6565803dcb782f4770e41f9f', '614ca72dde864c5419050660', '65fe8dbce5527fcb4ed1cd0e', '65562ad5015b9c3511c261b8', '67171134f799ba9b07ea59a7', '6582f1656ee0b5fe422d12a0', '6754843e136b602290bc8e91', '6629b83cc8b39e90cb6c3626', '6634d65591bf4738f73b05cc', '62f9d6397410031f6f7066da', '64ad1f1ecee96732c4131518', '59c8d121cd75ba844e44d775', '628111fb9df961201d000296', '637347c2812105600c6a09a0', '678118d8ad16b565c141cd33', '656f52ede60841d7cd5263b0', '670d31104fefa6d80e3d498c', '5f8a876b863bfc54f69d2526', '621de1b2a9bdb153f2ec22d9', '5d072d4d2c115b5fd4d0b4f6', '6379ce1683ee534aa4424eeb', '669de72771533186320d9ac5', '672dc68e323c9054d4556b21', '6506fd296dfd96b51f44333f', '670f9465712446f117097d07', '639ef5c2380526073c877596', '66d43e19f755021e08e62900', '5c8a0d848c352421eae966a4', '668ec797bef3c9c20258a799', '6421bf5013361546ac9a14e8', '625d47c65d34e3ef0a92facb', '5d5d7db1d0286d106d5caeb0', '5e510a287f868969461bb7c2', '678d28ebd18b8d3904ff7bb5', '5e6e4e4982da82c97677ef5d', '621f753df0b26bcbba5f2655', '5c3af0bd4a267149c76e89d3', '656714e693c3c55516f63310', '6541dd122dc35a3120c9bd53', '634adf1d09c7bf7f45e07264', '655f420c6aae37089ae7c980', '5e5713074094cd10d2b71f89', '5c3ae3744a267149c76e7c44', '6075d6dd79860eb040b3dece', '6380bdb7b5d727210e3cfe49', '62cd1f279a52694abb480ed3', '67186be3826ccce0d63803ed', '64bf5269a032e79cd610bc77', '65348ec8efd5ea044f6198b1', '636a6bc2cc95ad31454b5346', '64b81c7d80780619fabb6486', '5d2edc886ed7674e6115f664', '66c6f1df81c6d617e9824a66', '5d872d7a486b0b21477418ce', '5db2e387dcff3c45797930c8', '629a0a501b57e4943fe5d65c', '5db96adfc54ee121252d161b', '650432d2d4499ccf72229482', '66be0adc0eec199535d53c14', '633a436be90ec6acf67d12d6', '5fd0b53e014147cb9112a0cd', '65a66b8ace9b18074c68fc3d', '5d627f68d0286d106d63608f', '5e63aa8852ed422fa15422fc', '6585b62034899f072c24c2df', '6459a8b592e829a8894aa8ca', '630a0437bbb21525ad42bd6b', '6283ccc0e6802e6361b439ab', '673a27d42db5511bd9d5f4d6', '6593f2c56ae4027c19e834b9', '624305a96636bb6092f51550', '63e671ab8645afb82715ba93', '6459d9a518815f0b72696c28', '635021854282ce9dd75b4acd', '6648952cc47fbc7dcfd33c51', '668281ce804e40e73239e409', '5eda42369adf084531f5fcad', '5e301e95572666177d83db9f', '630726f4e3fa3c6786523161', '66e124a438b2a9645d4e9299', '61d03d98f423ac30d2507d49', '66c6078d2140e0c3a4c54637', '6655fc54d1fe7821d458c112', '5e6b68a78b7082561db8290b', '64b23b5a218ffc27b0ad8beb', '6248235006b5bc90b59cc9c3', '668c29506db48cd06b891982', '66fe9e3045b082657d8b6559', '5e0bca45a10a71228f88c236', '66cd5926b041433c57698d96', '654e56f50c2ddf04410bf71a', '637dd5d65b774181fa7c818a', '6678773b26174a1586cf9007', '628b7d30cb7f6c5ca7ac0a56', '6621d404c1f1f5489840b995', '6663c5b096252602c0bd6c1e', '628a4657fb23d07cefe66fb2', '6460d35b2de5a1903c1be560', '6575ede5dd6ceb2aabeba6da', '6278bd8e210c8cc8a84f0e44', '6469cc0197dc7407f27180c7', '66e2f0b74e84a12fe909956d', '6575ede5dd6ceb2aabeba6da', '602d15bf7dcd0f676582e272', '64ab829d8c6e0872be70e4fe', '6145f370de864c6cfb00aa87', '62661efe30d20228374a0622', '63120a4d91460f905ee0fc0f', '6176bfaa4c6ba1c3faded549', '5afd14a6943fca7a02f39f5e', '62c31af159628dee9010cb60', '674b06c4b727fa44115304d8', '5c25c8264a267149c75f2526', '64082c550bf0800f853d15f0', '65252d71b2a8a0a1ebfa41c3', '671d01126bd8d155d453a0c6', '6674f294e59fb890f58ba269', '62caf62efd2f160f3927e06f', '623a7a536e78d147f1f5a541', '62d750d56af03d1b4dc0bd9a', '5dbea8503405484920184d6f', '643c1210f6c53c7dfdddbd15', '661976c8c684d34e413f4533', '61f3b0b4242f4e634cdf019b', '622b7bdd478611a70859b2e1', '5e3b0295814e562141163256', '5ab3b68dc39f5c50a356a7dc', '624c60d817d0943ace94a417', '619350b16837ccce002f708c', '67506a91a62bce8b50a50edc', '62c2310d17af9a6c35697352', '5d130f77d6cbfc6a9db3c4a0', '62b7249b6a3d0d38b7340b14', '64b81b4c218ffc27da69ddbb', '62c4f6bd7d79670d85fc611d', '65e0767f777f4a2a8bed86b6', '668ac967cdbeed8e7cfb6fe2', '5dbc735c3087fd49362e7f78', '5da0c19a61bf5a14d098afc8', '65e7edf42c6f83c21e19929f', '613b4ae0b6866c0bf57ea0cf', '616ee65f4c6ba12548d988f6', '66f7723fe67795d5c3199b0c', '5f94157c3fbcbe7cdd49e0cf', '67624a6f9adca110b884b8e4', '60f0d3d5d417d47d1978e35e', '656f276a8eed3a3794e3721c', '670394bbce7719aa3747738d', '6740b25029285e20cbce4001', '670637dbffcc2b75c956ee59', '651edee303da7c455bb6b3b5', '62917aad2b800f882af6a123', '666d71774ccb333cceb14acc', '5e36bd2926b694333dc65368', '66099ea1db0e9c3b843e5228', '5d498e54bde10e0d542fd2d1', '6694ab158ddb253b020aebc7', '5f4cc816f330ba25860c80f7', '64ddb925950dcd1bd74f9f1b', '6241a34d6e78d1dc95fa77c3', '66e5118675f8abac3828b765', '61ceea9aba6ae14be67aeb13', '5fe97e9a026a406fcfce0a27', '677cb2c0eb8f477c1d5a9f8d', '5df46c13732f142b594b0096', '664d9cd27095b024b1062a4e', '64ae2f351b8e7bd75e2c7c4c', '60ccb3a0f5cf1167d99212df', '5f64d11cde129c0ce779edae', '66416fd88ad78d05af82122d', '66ab4634d4ca3013f839aab3', '5c8cd5b18c352421eaed2012', '5cbdeb9f54bc7263ff47feea', '65e3439dcab947315d83c929', '61dd05c4fb8e4d4f1f326294', '63e64762d6d9b22c62e3cbc0', '5b5ed8f603ef4d62d816a8f5', '65edf3a27d20bff35abea47b', '65d19fb023921ff7ae42ed8a', '64abc809bd6a90627c583f37', '62d7bf626af03dbfd0c11aad', '6396518280e415054df73279', '573f28f89b0ffc2836770d81', '63455878630369a9633fbede', '642135c51aa8f440674d1e84', '61b9f97db26e0e20c6a53088', '5ccbb04840e03a5c70b88678', '62dea142c389d9458f90d96c', '661c2ee72a30118bee98d426', '628d8f9d991337277e35d748', '66f6b938bfe37995619009d5', '65477c5683a79b7bfde4a301', '6774656166024a84214990aa', '66d2979e56553506af271c6d', '66f6b938bfe37995619009d5', '661e7fb0eace356afd572bbd', '6514dd7c88f6275b2cc843d6', '65b89e3cea5be7ae8e4e75e0', '66de6f482c6cf300073639d3', '5d282c4116609737fa48b610', '60e059bf569b26d7eb701797', '62ab69cd7d79671785eac594', '642eace5f7aa950f3ba8748f', '6415149f47c36b14444323be', '64ff55f44c8c4e461d9f0772', '61d0378e86fd1786f7be2c7c', '63da62da2f51db7965feeff0', '65eef95f60cf42493a724ae9', '67384b42bc46a47d949033ce', '62a602937d7967fe6ee6988d', '665c7b08dc7ccaed2fdbb61a', '63482a2d7e67c8dcfbbf0924', '666bfd9cd0d6252ab3410044', '6627ce531b7e50c426f8aab2', '624154b5b9a21e7080d03620', '5d5e0da8d0286d106d5d0324', '6764659651c8abcada9a7b19', '6645a8fe2f593a4e3f1e7e96', '5f797650f9451da66ed97aea', '662f6b42396311c68a94212f', '62d403ed7f7d1d12aa5a3526', '6103cc6e6cd4924e5b404b2d', '63134b284e349ce834079b68', '62b4a47c68ed981ed2b1efe5', '61acc4d3f3de6f1803438358', '6103b05a6cd492cfd940373b', '674d26728ae1cc126c54378a', '6335180fe90ec6469779e35f', '5f3f9fb0d358d19aa64f9ccd', '669f82462816a28b4e5005e6', '5a643d1b7956b277ebb19887', '63bcd4d34fd273f4844b9e94', '5d63cc63d0286d106d656e80', '65409690ee11aa0f8840fcb0', '6319a703d676d97e140baeec', '6714d3adecc9eb1e162eaa89', '634ff6644282ce11145b32cf', '644ec09ece292843462d7f23', '61ac2f3af3de6f608242e9c6', '5bc2079505793a5a367fbef7', '631b6dfb4c119bea5978cc43', '67283759a01ab12cd2add2e9', '62c93716d46b67e18ea05e79', '672839adbd4dc768b54adc4b', '674d29c9030ae2ce392e5d95', '59d7c981383da2197e86e3c9', '66a4d26f39a64ee10bcff674', '654f6e8a5319213f89fe985d', '6144a8bcc1762c6a188030be', '61bf69a2f3de6fc9cf515984', '665469d3579a946399b3f0ad', '62526f09282764261999873e', '6030d306454cef7d4e5cfb4f', '62b47a646ec933fc07ec13ad', '672f5d96bb419ab48b0368e5', '6468949ca3b17dc872577714', '63490cf4ec32736fc238f4f9', '66693f555d18077ba212fb34', '66387591436aa3ad97c7c5a8', '659ff435e0861520b7d2b829', '662ce454a54cc010d2d63217', '66373b78497334e86365cfa0', '5ca3c05

In [22]:
## base

base_query = f"""

with csv as (
    select 
        customerId,
        mobileOS,
        deviceManufacturer
    from 
        datasets.customer_single_view
    where 
        customerId IN ({customer_str})
    ),
    
    appo as (
    select 
        userid,
        case when regexp_like(lower(appographydata), 'zomato') then '1' else '0' end zomato,
        case when regexp_like(lower(appographydata), 'swiggy') then '1' else '0' end swiggy
    from 
        datasets.customer_apps_installed_snapshot
    where 
        userid IN ({customer_str})
    )
    
    select
        coalesce(customerId, userid) customer_id,
        mobileOS,
        deviceManufacturer,
        coalesce(zomato, 'UNKNOWN') zomato,
        coalesce(swiggy, 'UNKNOWN') swiggy
    from 
        csv a
    full join 
        appo b
        on customerId = userid

"""

df_base_query = pd.read_sql(base_query, connection)
df_base_query

                  customer_id mobileOS    deviceManufacturer zomato swiggy
0    6303bb0104cb1b28700dcc78  ANDROID                  vivo      0      0
1    62dea142c389d9458f90d96c  ANDROID               samsung      1      1
2    67602d6617b102345dfc67b4  ANDROID                  ITEL      1      0
3    5ccbb04840e03a5c70b88678  ANDROID               OnePlus      0      0
4    6774656166024a84214990aa  ANDROID                realme      0      0
..                        ...      ...                   ...    ...    ...
837  61a653c417dd6abc32060d74  ANDROID  TECNO MOBILE LIMITED      1      1
838  639df45ccd56c04285838951  ANDROID               OnePlus      1      1
839  663646ae051e29e3287b83de  ANDROID               samsung      1      1
840  672f5d96bb419ab48b0368e5  ANDROID              motorola      1      0
841  63e671ab8645afb82715ba93  ANDROID               samsung      0      0

[842 rows x 5 columns]

In [31]:
df_base_query.customer_id.nunique()

812

In [23]:
df_base_query.shape

(842, 5)

In [24]:
df_base_query[ df_base_query['mobileOS'] == 'IOS']

                  customer_id mobileOS deviceManufacturer   zomato   swiggy
33   652f177d1e930b6ca2544107      IOS              Apple  UNKNOWN  UNKNOWN
91   6299fbbb734ac520cd0bbeec      IOS              Apple  UNKNOWN  UNKNOWN
118  6618a8fe05d4ee1af982e9d1      IOS              Apple        1        1
267  66be0adc0eec199535d53c14      IOS              Apple        1        1
274  662f6b42396311c68a94212f      IOS              Apple        1        1
285  61854194692d9de8917cb9da      IOS              Apple  UNKNOWN  UNKNOWN
308  6115012b8dddcb578c6d0eaf      IOS              Apple        1        0
361  676a3bcc91c9d1930d54a4ba      IOS              Apple  UNKNOWN  UNKNOWN
362  62addccb214ba0106df329ad      IOS              Apple        1        1
402  629c6a8da3627ea2578d9351      IOS              Apple  UNKNOWN  UNKNOWN
405  6391e8f31d927e4119e61dd1      IOS              Apple  UNKNOWN  UNKNOWN
432  627267b1975f02c8bbc2c08e      IOS              Apple  UNKNOWN  UNKNOWN
513  5d699498d0286d106d6e2149      IOS              Apple        0        1
619  619a18fabd845bb72cceb946      IOS              Apple  UNKNOWN  UNKNOWN
622  67545f6f6841a478924a907e      IOS              Apple        0        0
720  64a8d0ca3d4c6c382dc867f0      IOS              Apple        1        1
762  5a9f78262314ba427eed6420      IOS              Apple        0        0
778  671087b7cb5b6e2bea5b0b60      IOS              Apple  UNKNOWN  UNKNOWN
820  618ba04cfbd171b9ddcc56a1      IOS              Apple  UNKNOWN  UNKNOWN

In [26]:
df_final = pd.merge(df, df_base_query[['customer_id', 'zomato', 'swiggy']], how='left', left_on = 'user_id', right_on='customer_id')
df_final

,city,gender,user_id,customer_obj_mobile,taxi_retention_segments,Customer_Obj_Name,customer_id,zomato,swiggy
0,Delhi,female,625d1422b9eaf550004a3b6f,8178430135,ELITE,Pooja,625d1422b9eaf550004a3b6f,0,0
1,Delhi,male,5daa690a52047954050e05e9,9667116049,ELITE,Sunny Vats,5daa690a52047954050e05e9,0,0
2,Hyderabad,male,64b98f0f218ffc447c9ad73a,9849410041,ELITE,Parthiban Abhiramacheri,64b98f0f218ffc447c9ad73a,0,0
3,Bangalore,male,642086d1c541dacb4f19f7f5,9845720987,ELITE,Vijaykumar S,642086d1c541dacb4f19f7f5,0,0
4,Bangalore,male,602b3a2319e49823b91f6641,8130507623,ELITE,Vishesh Verma,602b3a2319e49823b91f6641,1,1
...,...,...,...,...,...,...,...,...,...
854,Mumbai,female,63b1293aa9f27531da9eed81,9665725753,ELITE,Sunita Nair,63b1293aa9f27531da9eed81,1,0
855,Mumbai,female,65dd5ab9fc33e16621c4e223,7887753543,ELITE,Chandni Khatri,65dd5ab9fc33e16621c4e223,1,1
856,Mumbai,female,625d9ed3797562256b3bed6b,9930790789,ELITE,Yukta Borkar,625d9ed3797562256b3bed6b,1,0
857,Mumbai,male,67623e714a965b2ba8d40e2c,9819861820,ELITE,Amey,67623e714a965b2ba8d40e2c,1,1
858,Mumbai,female,627267b1975f02c8bbc2c08e,7506863180,ELITE,Tejaswini Rahate,627267b1975f02c8bbc2c08e,UNKNOWN,UNKNOWN

In [28]:
df_final.to_clipboard(index=False)

In [32]:
df_final_v1 = df_final.drop_duplicates(keep='last')
df_final_v1

,city,gender,user_id,customer_obj_mobile,taxi_retention_segments,Customer_Obj_Name,customer_id,zomato,swiggy
0,Delhi,female,625d1422b9eaf550004a3b6f,8178430135,ELITE,Pooja,625d1422b9eaf550004a3b6f,0,0
1,Delhi,male,5daa690a52047954050e05e9,9667116049,ELITE,Sunny Vats,5daa690a52047954050e05e9,0,0
2,Hyderabad,male,64b98f0f218ffc447c9ad73a,9849410041,ELITE,Parthiban Abhiramacheri,64b98f0f218ffc447c9ad73a,0,0
3,Bangalore,male,642086d1c541dacb4f19f7f5,9845720987,ELITE,Vijaykumar S,642086d1c541dacb4f19f7f5,0,0
4,Bangalore,male,602b3a2319e49823b91f6641,8130507623,ELITE,Vishesh Verma,602b3a2319e49823b91f6641,1,1
...,...,...,...,...,...,...,...,...,...
854,Mumbai,female,63b1293aa9f27531da9eed81,9665725753,ELITE,Sunita Nair,63b1293aa9f27531da9eed81,1,0
855,Mumbai,female,65dd5ab9fc33e16621c4e223,7887753543,ELITE,Chandni Khatri,65dd5ab9fc33e16621c4e223,1,1
856,Mumbai,female,625d9ed3797562256b3bed6b,9930790789,ELITE,Yukta Borkar,625d9ed3797562256b3bed6b,1,0
857,Mumbai,male,67623e714a965b2ba8d40e2c,9819861820,ELITE,Amey,67623e714a965b2ba8d40e2c,1,1
858,Mumbai,female,627267b1975f02c8bbc2c08e,7506863180,ELITE,Tejaswini Rahate,627267b1975f02c8bbc2c08e,UNKNOWN,UNKNOWN

In [33]:
df_final_v1.to_clipboard(index=False)

In [36]:
df_final_v1[ df_final_v1['zomato'] == 'UNKNOWN'].user_id.nunique()

19

In [11]:
df_base_query.to_parquet('data_dump_for_process_mining_bangalore.parquet', index=False)

In [12]:
test1 = pd.read_parquet('data_dump_for_process_mining_without_payment.parquet')

In [13]:
test1.shape

(1338288, 9)

In [15]:
1341310-1338288

3022

In [18]:
## base

base_query = f"""

SELECT
    city AS city,
    pickup_cluster,
    user_id as customer_id,
    fare_estimate_id,service_detail_id as service_id_fare,
    api_context,
    date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
    cast(final_amount AS double) AS fe_amount,polyline,
    epoch
FROM
    hive.pricing.fare_estimates_enriched
WHERE
     yyyymmdd = '20241021'             
     and service_name in ('Link')
     AND city = 'Bangalore'
     AND api_context='/fare/estimate'
"""

df_base_query = pd.read_sql(base_query, connection)
df_base_query

DatabaseError: {'message': 'Query exceeded the maximum execution time limit of 10.00m', 'errorCode': 131075, 'errorName': 'EXCEEDED_TIME_LIMIT', 'errorType': 'INSUFFICIENT_RESOURCES', 'failureInfo': {'type': 'io.trino.spi.TrinoException', 'message': 'Query exceeded the maximum execution time limit of 10.00m', 'suppressed': [], 'stack': ['io.trino.execution.QueryTracker.enforceTimeLimits(QueryTracker.java:187)', 'io.trino.execution.QueryTracker.lambda$start$0(QueryTracker.java:89)', 'com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:730)', 'java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)', 'java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)', 'java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)', 'java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)', 'java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)', 'java.base/java.lang.Thread.run(Thread.java:829)']}}

In [ ]:
df_base_query.to_parquet('fare_estimates_bangalore_link_20241021.parquet', index=False)