# Imports

In [1]:
import os
import re
import time

import numpy as np
import pandas as pd
import hiplot as hip
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 500)
os.environ['PYDEVD_DISABLE_FILE_VALIDATION'] = '1'


## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

# Parameters

In [2]:
start_date = '20240322'
end_date = '20240510'

local_datasets = '/Users/rapido/local-datasets/customer/appography/appography_data_dump/'

In [3]:
category_list = pd.read_csv('/Users/rapido/local-datasets/customer/appography/appography_v1/category_list_v1.csv')
category_list['app_name'] = category_list['app_name'].str.lower()
category_list['categories_l1'] = category_list['categories_l1'].str.lower()
category_list['categories_l2'] = category_list['categories_l2'].str.lower()
category_list = category_list[['app_name', 'categories_l1', 'categories_l2']]
print(category_list.shape)
print(category_list.categories_l1.unique())
print(category_list.categories_l2.unique())
category_list.head(1)

(433, 3)
['educational' 'ott' 'delivery_grocery' 'tools' 'office' 'dating' 'news'
 'devotional' 'travel_metro' 'gaming' 'travel_bookings'
 'finance_transactions' 'ecommerce' 'streaming_music' 'finance_investment'
 'health' 'fantasy_sports' 'delivery_food' 'home_security' 'finance_news'
 'travel_ridehailing' 'social' 'telecom' 'entertainment' 'news_finance'
 'wearable' 'driver_app' 'service']
['educational' 'rest' 'office' 'ride haling' 'gaming' 'finance_investment'
 'driver_app']

          app_name categories_l1 categories_l2
0  ignou e-content   educational   educational

# Data

### Scratch Card

In [4]:
scratchcards = f"""
    
    WITH unlocked AS (

    SELECT
        user_id
        -- rewards_transaction_id order_id
    FROM 
        raw.kafka_pricing_scratchcards_immutable
    WHERE 
        yyyymmdd >= '{start_date}'
        AND yyyymmdd <= '{end_date}'
        AND rewards_state = 'UNLOCKED'
        AND rewards_type = 'EXTERNAL_REWARD'
        AND JSON_EXTRACT_SCALAR(rewards, '$.externalRewardMetaData.externalRewardId') IN (  '6603f871448cb38c86d1f0d0', '65fc8e0a5d26549b39e572de', '660c0c93639d07858bc1d721', '660c0c1c7c0420ce6f6c7a5d', '6603faa7639d07858bbd37a9',
                                                                                            '660c0d056d7ddb4719d4eab3', '660c0e5c712d0067117c2de5', '65fc8536c3c58734495647d7', '6603f9af712d00671177355d', '65fc8d19fb638769daf4bb1e',
                                                                                            '66311e60b397b66e22161cd5', '65fc8a50d53292624c41d395', '6603fd28639d07858bbea5c0', '65fac1cce4838dd72578e34c', '65e85625a1bed81a09450b32',
                                                                                            '65d457d4d79b4ea79b5a6b09', '65cb6dc116c7594d528d8d50', '65e85b3a78839f742cac6cb4', '65d31c5fc526f1e342f2d9cb', '65e847c39bb6821c785b9e21')
    GROUP BY 1
    ),
    
    
    scratched AS (
    
    SELECT
        user_id
        -- rewards_transaction_id order_id

    FROM 
        raw.kafka_pricing_scratchcards_immutable
    WHERE 
        yyyymmdd >= '{start_date}'
        AND yyyymmdd <= '{end_date}'
        AND rewards_type = 'EXTERNAL_REWARD'
        AND rewards_state = 'SCRATCHED' 
        AND JSON_EXTRACT_SCALAR(rewards, '$.externalRewardMetaData.externalRewardId') IN (  '6603f871448cb38c86d1f0d0', '65fc8e0a5d26549b39e572de', '660c0c93639d07858bc1d721', '660c0c1c7c0420ce6f6c7a5d', '6603faa7639d07858bbd37a9',
                                                                                            '660c0d056d7ddb4719d4eab3', '660c0e5c712d0067117c2de5', '65fc8536c3c58734495647d7', '6603f9af712d00671177355d', '65fc8d19fb638769daf4bb1e',
                                                                                            '66311e60b397b66e22161cd5', '65fc8a50d53292624c41d395', '6603fd28639d07858bbea5c0', '65fac1cce4838dd72578e34c', '65e85625a1bed81a09450b32',
                                                                                            '65d457d4d79b4ea79b5a6b09', '65cb6dc116c7594d528d8d50', '65e85b3a78839f742cac6cb4', '65d31c5fc526f1e342f2d9cb', '65e847c39bb6821c785b9e21')
    GROUP BY 1
    ),
    
    rewards AS (
    
    SELECT
        event_props_user_id user_id,
        MAX(CASE WHEN event_props_action = 'ctaClicked' THEN event_props_user_id END) AS cta_clicked_user_id,
        MAX(CASE WHEN event_props_action = 'copyCodeClicked' THEN event_props_user_id END) AS copy_code_clicked_user_id
        
    FROM 
        clevertap.customer_rewards_immutable
    WHERE 
        yyyymmdd >= '{start_date}'
        AND yyyymmdd <= '{end_date}'
        AND event_props_action IN ('ctaClicked', 'copyCodeClicked')
        AND event_props_reward_partner in ('My11 Circle', 'My 11Circle')
        
    GROUP BY 1
    )
    
    SELECT  
        unlocked.user_id unlocked_customer_id,
        COALESCE(scratched.user_id, rewards.user_id) scratched_customer_id,
        rewards.user_id rewards_customer_id,
        cta_clicked_user_id,
        copy_code_clicked_user_id
    FROM 
        unlocked 
    LEFT JOIN scratched
        ON unlocked.user_id = scratched.user_id
    LEFT JOIN rewards
        ON unlocked.user_id = rewards.user_id
"""
df_scratchcards = pd.read_sql(scratchcards, connection)

In [5]:
df_scratchcards.head()

,unlocked_customer_id,scratched_customer_id,rewards_customer_id,cta_clicked_user_id,copy_code_clicked_user_id
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,None,None,None
1,5cb02eb654bc7263ff34a5ff,None,None,None,None
2,65e73c6bf5efdbc08f2f1317,None,None,None,None
3,641bc23ed8f1b3f1dee45fc2,None,None,None,None
4,5d576ca6bde10e0d544289f7,5d576ca6bde10e0d544289f7,None,None,None

In [41]:
# df_scratchcards.to_csv('df_scratchcards.csv', index=False)
df_scratchcards = pd.read_csv('df_scratchcards.csv')

### Appo

In [43]:
local_database = '/Users/rapido/local-datasets/customer/appography/appography_v2/bangalore/database/'
# df_customer_appography_data.to_csv(local_database + 'raw_customer_appography_data.csv', index=False)
df_customer_appography_data = pd.read_csv(local_database + 'raw_customer_appography_data.csv')

# regular-exp 
def extract_and_trim(text):
    return [val.strip() for val in re.findall(r"'([^']*)'", text)]

df_customer_appography_data['app_list_set'] = df_customer_appography_data['app_list_set'].apply(lambda x: extract_and_trim(x))

In [45]:
df_customer_appography_data

,customer_id,app_list_set
0,5737c6adddbec2203f73316d,"[whatsapp, paytm money, samsung galaxy wearabl..."
1,5737c6aeddbec2203f733176,"[outlook, onedrive, ola, microsoft 365, groww,..."
2,5737c6b0ddbec2203f733182,"[wynk music, messenger, mx takatak, google cal..."
3,5737c6b1ddbec2203f73318b,"[snapchat, instagram, google photos, zoom, my1..."
4,5737c6baddbec2203f7331d9,"[google sheets, jio cinema, paytm money, googl..."
...,...,...
1878610,6609aa278fcbab0f6302fbe0,"[google photos, uber, flipkart, google maps, p..."
1878611,6609aa86a9381bb7123b1d14,"[whatsapp, instagram, messenger, snapchat, jio..."
1878612,6609aab4db0e9caafc405cd8,"[facebook, snapchat, google maps, samsung gala..."
1878613,6609aacc8fcbabbbfa031371,"[brainly, zomato, spotify, wynk music, google ..."
1878614,6609ab52c1792a370902d4a6,"[wynk music, messenger, google maps, youtube, ..."

In [47]:
df1 = df_scratchcards[~df_scratchcards['scratched_customer_id'].isna()]

In [51]:
df1.reset_index(inplace=True)

In [53]:
df1.drop('index', axis=1, inplace=True)

In [54]:
df1

,unlocked_customer_id,scratched_customer_id,rewards_customer_id,cta_clicked_user_id,copy_code_clicked_user_id
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN
1,5d576ca6bde10e0d544289f7,5d576ca6bde10e0d544289f7,NaN,NaN,NaN
2,6505907a3134867e03caacf2,6505907a3134867e03caacf2,NaN,NaN,NaN
3,63483e6f0229b1fe4944c38b,63483e6f0229b1fe4944c38b,NaN,NaN,NaN
4,65f5c8480f9aeb073b0aaf16,65f5c8480f9aeb073b0aaf16,NaN,NaN,NaN
...,...,...,...,...,...
1056834,635bc4c385b399d2a6534ee6,635bc4c385b399d2a6534ee6,NaN,NaN,NaN
1056835,61eecc596916b8683faa53a8,61eecc596916b8683faa53a8,NaN,NaN,NaN
1056836,62d030de7bdc24d87f3c8c2e,62d030de7bdc24d87f3c8c2e,NaN,NaN,NaN
1056837,61a1debb17dd6a9f8e02c43e,61a1debb17dd6a9f8e02c43e,NaN,NaN,NaN
1056838,5d5bcefbd0286d106d5a5f54,5d5bcefbd0286d106d5a5f54,NaN,NaN,NaN

### DE

In [55]:
df_appo_data = pd.merge(df1,
                        df_customer_appography_data,
                        how = 'inner',
                        left_on = 'scratched_customer_id',
                        right_on = 'customer_id'
                       )
df_appo_data

,unlocked_customer_id,scratched_customer_id,rewards_customer_id,cta_clicked_user_id,copy_code_clicked_user_id,customer_id,app_list_set
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,"[google maps, spotify, namma yatri, bookmyshow..."
1,5d576ca6bde10e0d544289f7,5d576ca6bde10e0d544289f7,NaN,NaN,NaN,5d576ca6bde10e0d544289f7,"[porter driver app, google calendar, jio cinem..."
2,6505907a3134867e03caacf2,6505907a3134867e03caacf2,NaN,NaN,NaN,6505907a3134867e03caacf2,"[dropbox, groww, truecaller, grofers, notion, ..."
3,63483e6f0229b1fe4944c38b,63483e6f0229b1fe4944c38b,NaN,NaN,NaN,63483e6f0229b1fe4944c38b,"[jiomart, goibibo, youtube, google news, adobe..."
4,5dba2be934054849200ef9a5,5dba2be934054849200ef9a5,NaN,NaN,NaN,5dba2be934054849200ef9a5,"[facebook, ola, disney+ hotstar, wynk music, g..."
...,...,...,...,...,...,...,...
189754,65e0496f113cbe2194d4e3ae,65e0496f113cbe2194d4e3ae,NaN,NaN,NaN,65e0496f113cbe2194d4e3ae,"[microsoft teams, wynk music, snapchat, trueca..."
189755,66068bec12bd0f6364109426,66068bec12bd0f6364109426,NaN,NaN,NaN,66068bec12bd0f6364109426,"[instagram, google maps, amazon prime video, z..."
189756,634cc330be6aa75b532eb84f,634cc330be6aa75b532eb84f,NaN,NaN,NaN,634cc330be6aa75b532eb84f,"[zomato, gmail, snapchat, spotify, youtube, di..."
189757,630100e745985b54cbc40825,630100e745985b54cbc40825,NaN,NaN,NaN,630100e745985b54cbc40825,"[gmail, google maps, whatsapp, paytm money, cl..."
189758,63b924f5cb15335b788c968f,63b924f5cb15335b788c968f,NaN,NaN,NaN,63b924f5cb15335b788c968f,"[pinterest, google calendar, disney+ hotstar, ..."

# User Defined Function()

In [56]:
def calculate_percentage(df, numerator_col, denominator_col):
    return (df[numerator_col] * 100.00 / df[denominator_col]).round(2)

# Analysis

In [57]:
df_scratchcards.head(2)

,unlocked_customer_id,scratched_customer_id,rewards_customer_id,cta_clicked_user_id,copy_code_clicked_user_id
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN
1,5cb02eb654bc7263ff34a5ff,NaN,NaN,NaN,NaN

In [58]:
df_scratchcards['date_range'] = start_date + ' to ' + end_date

In [59]:
df_overall_numbers =  df_scratchcards\
                            .groupby(['date_range'])\
                            .agg(unlocked_customers = ('unlocked_customer_id', 'nunique'),
                                 scratched_customers = ('scratched_customer_id', 'nunique'),
                                 rewards_customers = ('rewards_customer_id', 'nunique'),
                                 cta_customers = ('cta_clicked_user_id', 'nunique'),
                                 copyCodeClicked_customers = ('copy_code_clicked_user_id', 'nunique')
                                )\
                            .reset_index()

df_overall_numbers

,date_range,unlocked_customers,scratched_customers,rewards_customers,cta_customers,copyCodeClicked_customers
0,20240322 to 20240510,6508503,1056839,122598,78490,120726

In [60]:
df_overall_numbers['% scratched_customers'] = calculate_percentage(df_overall_numbers, 'scratched_customers', 'unlocked_customers')
df_overall_numbers['% rewards code/click'] = calculate_percentage(df_overall_numbers, 'rewards_customers', 'scratched_customers')
df_overall_numbers['% rewards cta'] = calculate_percentage(df_overall_numbers, 'cta_customers', 'scratched_customers')
df_overall_numbers['% rewards copyCodeClicked'] = calculate_percentage(df_overall_numbers, 'copyCodeClicked_customers', 'scratched_customers')

## Overall

In [61]:
df_overall_numbers[['date_range','unlocked_customers','scratched_customers',
                    'rewards_customers','cta_customers','copyCodeClicked_customers']]

,date_range,unlocked_customers,scratched_customers,rewards_customers,cta_customers,copyCodeClicked_customers
0,20240322 to 20240510,6508503,1056839,122598,78490,120726

In [62]:
df_overall_numbers[['date_range','% scratched_customers','% rewards code/click',
                    '% rewards cta','% rewards copyCodeClicked']]

,date_range,% scratched_customers,% rewards code/click,% rewards cta,% rewards copyCodeClicked
0,20240322 to 20240510,16.24,11.6,7.43,11.42

## copyCodeClicked Customer

In [63]:
df_appo_data

,unlocked_customer_id,scratched_customer_id,rewards_customer_id,cta_clicked_user_id,copy_code_clicked_user_id,customer_id,app_list_set
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,"[google maps, spotify, namma yatri, bookmyshow..."
1,5d576ca6bde10e0d544289f7,5d576ca6bde10e0d544289f7,NaN,NaN,NaN,5d576ca6bde10e0d544289f7,"[porter driver app, google calendar, jio cinem..."
2,6505907a3134867e03caacf2,6505907a3134867e03caacf2,NaN,NaN,NaN,6505907a3134867e03caacf2,"[dropbox, groww, truecaller, grofers, notion, ..."
3,63483e6f0229b1fe4944c38b,63483e6f0229b1fe4944c38b,NaN,NaN,NaN,63483e6f0229b1fe4944c38b,"[jiomart, goibibo, youtube, google news, adobe..."
4,5dba2be934054849200ef9a5,5dba2be934054849200ef9a5,NaN,NaN,NaN,5dba2be934054849200ef9a5,"[facebook, ola, disney+ hotstar, wynk music, g..."
...,...,...,...,...,...,...,...
189754,65e0496f113cbe2194d4e3ae,65e0496f113cbe2194d4e3ae,NaN,NaN,NaN,65e0496f113cbe2194d4e3ae,"[microsoft teams, wynk music, snapchat, trueca..."
189755,66068bec12bd0f6364109426,66068bec12bd0f6364109426,NaN,NaN,NaN,66068bec12bd0f6364109426,"[instagram, google maps, amazon prime video, z..."
189756,634cc330be6aa75b532eb84f,634cc330be6aa75b532eb84f,NaN,NaN,NaN,634cc330be6aa75b532eb84f,"[zomato, gmail, snapchat, spotify, youtube, di..."
189757,630100e745985b54cbc40825,630100e745985b54cbc40825,NaN,NaN,NaN,630100e745985b54cbc40825,"[gmail, google maps, whatsapp, paytm money, cl..."
189758,63b924f5cb15335b788c968f,63b924f5cb15335b788c968f,NaN,NaN,NaN,63b924f5cb15335b788c968f,"[pinterest, google calendar, disney+ hotstar, ..."

In [64]:
## Explode list into individual rows

df_appography_explode = df_appo_data.explode('app_list_set')
df_appography_explode['app_list_set'] = df_appography_explode['app_list_set'].str.lower()

df_appography_explode.head(4)

,unlocked_customer_id,scratched_customer_id,rewards_customer_id,cta_clicked_user_id,copy_code_clicked_user_id,customer_id,app_list_set
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,google maps
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,spotify
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,namma yatri
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,bookmyshow

In [65]:
category_list

                            app_name         categories_l1       categories_l2
0                    ignou e-content           educational         educational
1                                aha                   ott                rest
2               grofers delivery app      delivery_grocery                rest
3                     qr code reader                 tools                rest
4                            nishtha                office              office
5                            brainly           educational         educational
6                              hinge                dating                rest
7                         wunderlist                office              office
8                              slack                office              office
9                             aajtak                  news                rest
10                         aastha tv            devotional                rest
11                          abp live                  news                rest
12                       accuweather                 tools                rest
13                   weather & radar                 tools                rest
14                      mumbai metro          travel_metro         ride haling
15                   adobe lightroom                 tools                rest
16                        adobe scan                 tools                rest
17                        afterlight                gaming              gaming
18                            airbnb       travel_bookings                rest
19                     airtel thanks  finance_transactions                rest
20                             aisle                dating                rest
21                      weather live                 tools                rest
22                al jazeera english           educational         educational
23                         altbalaji                   ott                rest
24                      amazon alexa                 tools                rest
25                amazon prime video                   ott                rest
26                   amazon shopping             ecommerce                rest
27                      amazon music       streaming_music                rest
28                        calculator                 tools                rest
29                             clock                 tools                rest
30                     angel broking    finance_investment  finance_investment
31                       apollo 24/7                health                rest
32                           dream11        fantasy_sports                rest
33                       apple music       streaming_music                rest
34                            zomato         delivery_food                rest
35                              arlo         home_security                rest
36                             asana                office              office
37                        confluence                office              office
38                              jira                office              office
39                            trello                office              office
40                  mumbai metro one          travel_metro         ride haling
41                       august home         home_security                rest
42                       axis mobile  finance_transactions                rest
43                     ayurveda yoga                health                rest
44                  ms authenticator                office              office
45                        alt balaji                   ott                rest
46                               mlb        fantasy_sports                rest
47                    bansal classes           educational         educational
48                         bigbasket      delivery_grocery                rest
49                         bloomberg          finance_news                rest
50                          blusmart    travel_ridehailing         ride haling
51                       booking.com       travel_bookings                rest
52                              hike                social                rest
53                        wynk music       streaming_music                rest
54                       namma metro          travel_metro         ride haling
55                    bsnl my circle               telecom                rest
56                        bookmyshow         entertainment                rest
57                            bumble                dating                rest
58                 business standard          finance_news                rest
59                            aakash           educational         educational
60                              byju           educational         educational
61                              byte           educational         educational
62                       chegg study           educational         educational
63                     chennai metro          travel_metro         ride haling
64                          chingari                social                rest
65                             cisco                office              office
66                             webex                office              office
67                         cleartrip       travel_bookings                rest
68                         cnbc tv18                  news                rest
69                coffee meets bagel                dating                rest
70                      colegeduniya           educational         educational
71                       course hero           educational         educational
72                          coursera           educational         educational
73                          cricbuzz        fantasy_sports                rest
74                          cricplay        fantasy_sports                rest
75                          cure.fit                health                rest
76                     dainik jagran                  news                rest
77                       delhi metro          travel_metro         ride haling
78                            feedly                  news                rest
79                        quick ride    travel_ridehailing         ride haling
80                         quickride    travel_ridehailing         ride haling
81                    domino's pizza         delivery_food                rest
82                          doubtnut           educational         educational
83                           dream11        fantasy_sports                rest
84                              cred  finance_transactions                rest
85                 driveu driver app    travel_ridehailing         ride haling
86                           dropbox                office              office
87                      moneycontrol          news_finance                rest
88                         free fire                gaming              gaming
89                             dunzo         delivery_food                rest
90                          duolingo           educational         educational
91                            ecobee         home_security                rest
92                            eenadu                  news                rest
93                            embibe           educational         educational
94                          eros now                   ott                rest
95                      espncricinfo        fantasy_sports                rest
96                              espn        fantasy_sports                rest
97                    economic times          finance_news                rest
98                          evernote                 tools                rest
99                           expedia       travel_bookings                rest
100                         facebook                social                rest
101                        messenger                social                rest
102                         fanfight        fantasy_sports                rest
103                 fantasy power 11        fantasy_sports                rest
104                           fitbit                health                rest
105                            fiton                health                rest
106                            fittr                health                rest
107                         flipkart             ecommerce                rest
108                        foodpanda         delivery_food                rest
109              fossil smartwatches              wearable                rest
110                       freecharge  finance_transactions                rest
111                            nykaa             ecommerce                rest
112                            happn                dating                rest
113                       big bazaar      delivery_grocery                rest
114                            gaana       streaming_music                rest
115                       my11circle        fantasy_sports                rest
116                   garmin connect              wearable                rest
117                          fiitjee           educational         educational
118                     collegedekho           educational         educational
119                           github                office              office
120                          goibibo       travel_bookings                rest
121                        goodreads           educational         educational
122             google authenticator                office              office
123                 google classroom           educational         educational
124                    google sheets                 tools                rest
125                    google slides                 tools                rest
126                     google drive                 tools                rest
127                      google home                 tools                rest
128                 google analytics                office              office
129                      google news                  news                rest
130                      google maps                 tools                rest
131                         bhim upi  finance_transactions                rest
132                       google pay  finance_transactions                rest
133                    google photos                 tools                rest
134                  google calendar                 tools                rest
135                            gmail                 tools                rest
136                         hangouts                 tools                rest
137                          youtube                 tools                rest
138                              nfl        fantasy_sports                rest
139                             zee5                   ott                rest
140                          grofers      delivery_grocery                rest
141                          happify           educational         educational
142                  hdfc securities    finance_investment  finance_investment
143                      healthifyme                health                rest
144                             helo                health                rest
145                          hotstar                   ott                rest
146                             mint          finance_news                rest
147                  hindustan times                  news                rest
148                   zepp (amazfit)              wearable                rest
149                    huawei health              wearable                rest
150                    hungama music       streaming_music                rest
151                     icici direct    finance_investment  finance_investment
152                           pocket           educational         educational
153                      imd weather                 tools                rest
154               the indian express                  news                rest
155                        instagram                social                rest
156           instacart delivery app      delivery_grocery                rest
157                      caclubindia           educational         educational
158                          invideo                 tools                rest
159                         sadhguru            devotional                rest
160                          jiochat                 tools                rest
161                       mx takatak                social                rest
162                         jiosaavn       streaming_music                rest
163                       jio cinema                   ott                rest
164                            jiotv                   ott                rest
165                          jiomart             ecommerce                rest
166                            kayak       travel_bookings                rest
167                        kfc india         delivery_food                rest
168                    kolkata metro          travel_metro         ride haling
169                            koovs             ecommerce                rest
170               kotak stock trader    finance_investment  finance_investment
171                            likee                 tools                rest
172                         limeroad             ecommerce                rest
173                         linkedin                social                rest
174                linkedin learning           educational         educational
175                  bangalore metro          travel_metro         ride haling
176                        ludo king                gaming              gaming
177                         dubsmash                social                rest
178                        camera mx                 tools                rest
179                       makemytrip       travel_bookings                rest
180                malayala manorama                  news                rest
181                 mcdonald's india         delivery_food                rest
182                          medlife             ecommerce                rest
183                           meesho             ecommerce                rest
184                           meetup           educational         educational
185                      meritnation           educational         educational
186                            mfine                health                rest
187                       bolo indya                social                rest
188                        photomath           educational         educational
189                          ms edge                 tools                rest
190                microsoft kaizala                social                rest
191            microsoft math solver           educational         educational
192                  microsoft excel                 tools                rest
193           microsoft office suite                office              office
194                    microsoft 365                office              office
195                   microsoft lens                 tools                rest
196                microsoft onenote                 tools                rest
197                          outlook                office              office
198                         onedrive                office              office
199                  microsoft teams                office              office
200           intune  company portal                office              office
201                         mobikwik  finance_transactions                rest
202                      simplilearn           educational         educational
203                   file commander                 tools                rest
204                           mobvoi              wearable                rest
205                              moj                social                rest
206                     moneycontrol          finance_news                rest
207                      money lover                 tools                rest
208                           moodle           educational         educational
209                       mparivahan       travel_bookings                rest
210                           voonik             ecommerce                rest
211                    angel broking    finance_investment  finance_investment
212                        mxtakatak                social                rest
213                        mx player                 tools                rest
214                     myfitnesspal                health                rest
215                           myntra             ecommerce                rest
216                              nba        fantasy_sports                rest
217                      ncert books           educational         educational
218                        ndtv news                  news                rest
219                          netflix                   ott                rest
220                          netmeds             ecommerce                rest
221                         inshorts                  news                rest
222                            groww    finance_investment  finance_investment
223                              nhl        fantasy_sports                rest
224                         snapseed                 tools                rest
225                    shiksha mitra           educational         educational
226               nike training club                health                rest
227                          retrica                 tools                rest
228                           walnut                 tools                rest
229                            nykaa             ecommerce                rest
230                          okcupid                dating                rest
231                              ola    travel_ridehailing         ride haling
232                   ola driver app            driver_app          driver_app
233                              1mg             ecommerce                rest
234                           pocket                office              office
235                   oneplus health              wearable                rest
236                         1weather                 tools                rest
237                              oyo       travel_bookings                rest
238                         divya tv            devotional                rest
239                            paytm  finance_transactions                rest
240                paytm first games        fantasy_sports                rest
241                      paytm money  finance_transactions                rest
242                       paytm mall             ecommerce                rest
243                        pepperfry             ecommerce                rest
244                        pharmeasy             ecommerce                rest
245                          phonepe  finance_transactions                rest
246                          picsart                 tools                rest
247                        pinterest                social                rest
248                           practo                health                rest
249            delhi metro navigator          travel_metro         ride haling
250                           prisma                 tools                rest
251              kolkata metro guide          travel_metro         ride haling

In [83]:
df_explode = pd.merge(df_appography_explode,
                      category_list,
                      how='left',
                      left_on='app_list_set',
                      right_on='app_name'
                     )
df_explode.head(5)

,unlocked_customer_id,scratched_customer_id,rewards_customer_id,cta_clicked_user_id,copy_code_clicked_user_id,customer_id,app_list_set,app_name,categories_l1,categories_l2
0,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,google maps,google maps,tools,rest
1,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,spotify,spotify,streaming_music,rest
2,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,namma yatri,namma yatri,travel_ridehailing,ride haling
3,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,bookmyshow,bookmyshow,entertainment,rest
4,5bc74480265bc271049bf01a,5bc74480265bc271049bf01a,NaN,NaN,NaN,5bc74480265bc271049bf01a,messenger,messenger,social,rest

In [84]:
df_summary = df_explode\
                .groupby(['categories_l1'])\
                .agg(scratched_customers = ('scratched_customer_id', 'nunique'),
#                      rewards_customers = ('rewards_customer_id', 'nunique'),
                     cta_customers = ('cta_clicked_user_id', 'nunique'),
                     copy_code_clicked_customers = ('copy_code_clicked_user_id', 'nunique'),
                    )\
                .reset_index()

In [85]:
df_summary

,categories_l1,scratched_customers,cta_customers,copy_code_clicked_customers
0,dating,12291,759,987
1,delivery_food,138048,9521,13301
2,delivery_grocery,79336,4893,6795
3,devotional,4,0,2
4,driver_app,15767,2038,2740
5,ecommerce,153239,12657,17639
6,educational,42836,2489,3599
7,entertainment,65123,4019,5507
8,fantasy_sports,6586,1593,2125
9,finance_investment,79163,4687,6551
10,finance_news,3786,157,233
11,finance_transactions,135779,10712,14692
12,gaming,25662,2491,3408
13,health,12639,623,887
14,news,64191,5549,7777
15,office,123585,7554,10848
16,ott,158148,12906,18121
17,social,189476,16300,22908
18,streaming_music,131230,10426,14632
19,tools,189758,16331,22945
20,travel_bookings,61943,3771,5252
21,travel_ridehailing,147998,11063,15454
22,wearable,26343,1504,2140

In [86]:
# df_summary['% rewards pv'] = calculate_percentage(df_summary, 'rewards_customers', 'scratched_customers')
df_summary['% cta'] = calculate_percentage(df_summary, 'cta_customers', 'scratched_customers')
df_summary['% copy_code_clicked'] = calculate_percentage(df_summary, 'copy_code_clicked_customers', 'scratched_customers')

In [106]:
df_summary.rename(columns={'categories_l1': 'category/app'}, inplace=True)
df_summary.sort_values(by='% copy_code_clicked', ascending=False)

,category/app,scratched_customers,cta_customers,copy_code_clicked_customers,% cta,% copy_code_clicked
3,devotional,4,0,2,0.00,50.00
8,fantasy_sports,6586,1593,2125,24.19,32.27
4,driver_app,15767,2038,2740,12.93,17.38
12,gaming,25662,2491,3408,9.71,13.28
14,news,64191,5549,7777,8.64,12.12
17,social,189476,16300,22908,8.60,12.09
19,tools,189758,16331,22945,8.61,12.09
5,ecommerce,153239,12657,17639,8.26,11.51
16,ott,158148,12906,18121,8.16,11.46
18,streaming_music,131230,10426,14632,7.94,11.15
11,finance_transactions,135779,10712,14692,7.89,10.82
21,travel_ridehailing,147998,11063,15454,7.48,10.44
1,delivery_food,138048,9521,13301,6.90,9.64
15,office,123585,7554,10848,6.11,8.78
2,delivery_grocery,79336,4893,6795,6.17,8.56
20,travel_bookings,61943,3771,5252,6.09,8.48
7,entertainment,65123,4019,5507,6.17,8.46
6,educational,42836,2489,3599,5.81,8.40
9,finance_investment,79163,4687,6551,5.92,8.28
22,wearable,26343,1504,2140,5.71,8.12
0,dating,12291,759,987,6.18,8.03
13,health,12639,623,887,4.93,7.02
10,finance_news,3786,157,233,4.15,6.15

In [91]:
df_app_summary = df_explode[df_explode['app_list_set'].isin(['my11circle'])]\
                .groupby(['app_list_set'])\
                .agg(scratched_customers = ('scratched_customer_id', 'nunique'),
#                      rewards_customers = ('rewards_customer_id', 'nunique'),
                     cta_customers = ('cta_clicked_user_id', 'nunique'),
                     copy_code_clicked_customers = ('copy_code_clicked_user_id', 'nunique'),
                    )\
                .reset_index()

In [92]:
df_app_summary

,app_list_set,scratched_customers,cta_customers,copy_code_clicked_customers
0,my11circle,6224,1563,2084

In [93]:
# df_summary['% rewards pv'] = calculate_percentage(df_summary, 'rewards_customers', 'scratched_customers')
df_app_summary['% cta'] = calculate_percentage(df_app_summary, 'cta_customers', 'scratched_customers')
df_app_summary['% copy_code_clicked'] = calculate_percentage(df_app_summary, 'copy_code_clicked_customers', 'scratched_customers')

In [107]:
df_app_summary.rename(columns={'app_list_set': 'category/app'}, inplace=True)
df_app_summary.sort_values(by='% copy_code_clicked', ascending=False)

,category/app,scratched_customers,cta_customers,copy_code_clicked_customers,% cta,% copy_code_clicked
0,my11circle,6224,1563,2084,25.11,33.48

In [108]:
concatenated_df = pd.concat([df_summary, df_app_summary], ignore_index=False)

In [110]:
concatenated_df.sort_values(by='% copy_code_clicked', ascending=False)

,category/app,scratched_customers,cta_customers,copy_code_clicked_customers,% cta,% copy_code_clicked
3,devotional,4,0,2,0.00,50.00
0,my11circle,6224,1563,2084,25.11,33.48
8,fantasy_sports,6586,1593,2125,24.19,32.27
4,driver_app,15767,2038,2740,12.93,17.38
12,gaming,25662,2491,3408,9.71,13.28
14,news,64191,5549,7777,8.64,12.12
17,social,189476,16300,22908,8.60,12.09
19,tools,189758,16331,22945,8.61,12.09
5,ecommerce,153239,12657,17639,8.26,11.51
16,ott,158148,12906,18121,8.16,11.46
18,streaming_music,131230,10426,14632,7.94,11.15
11,finance_transactions,135779,10712,14692,7.89,10.82
21,travel_ridehailing,147998,11063,15454,7.48,10.44
1,delivery_food,138048,9521,13301,6.90,9.64
15,office,123585,7554,10848,6.11,8.78
2,delivery_grocery,79336,4893,6795,6.17,8.56
20,travel_bookings,61943,3771,5252,6.09,8.48
7,entertainment,65123,4019,5507,6.17,8.46
6,educational,42836,2489,3599,5.81,8.40
9,finance_investment,79163,4687,6551,5.92,8.28
22,wearable,26343,1504,2140,5.71,8.12
0,dating,12291,759,987,6.18,8.03
13,health,12639,623,887,4.93,7.02
10,finance_news,3786,157,233,4.15,6.15

# Previous analysis

In [4]:
df_data['app_list'] = df_data['app_list'].str.strip()
df_data.drop_duplicates(inplace=True)

df_merge = pd.merge(df_data, 
                    category_list,
                    how='left',
                    left_on='app_list',
                    right_on='app_name'
                   )
df_merge['values'] = 1
df_merge

,user_id,cta_clicked,copy_code_clicked,id,app_list,app_name,categories_l1,categories_l2,values
0,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,amazon prime video,amazon prime video,ott,rest,1
1,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,zomato,zomato,delivery_food,rest,1
2,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,zomato,zomato,delivery_food,rest,1
3,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,alt balaji,alt balaji,ott,rest,1
4,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,bookmyshow,bookmyshow,entertainment,rest,1
...,...,...,...,...,...,...,...,...,...
2331347,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,ola,ola,travel_ridehailing,ride haling,1
2331348,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,ola driver app,ola driver app,driver_app,driver_app,1
2331349,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,rapido captain,rapido captain,driver_app,driver_app,1
2331350,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,snapchat,snapchat,social,rest,1
2331351,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,spotify,spotify,streaming_music,rest,1

### Apps

In [5]:
df1 = df_merge.groupby(['app_list'])\
                .agg(count = ('user_id', 'nunique'))\
                .sort_values(by='count', ascending=False)\
                .reset_index()

df1['total_customers'] = df_merge.user_id.nunique()
df1['%'] = (df1['count']*100.00/df1['total_customers']).round(2)

In [7]:
df1.sort_values(by='%', ascending=False).head(60)

                   app_list   count  total_customers      %
0               google maps  100722           100770  99.95
1                   youtube  100474           100770  99.71
2                     gmail  100429           100770  99.66
3                  whatsapp   97229           100770  96.49
4             google photos   93904           100770  93.19
5                 instagram   81833           100770  81.21
6                  facebook   73284           100770  72.72
7                truecaller   67906           100770  67.39
8           google calendar   61272           100770  60.80
9                  flipkart   58242           100770  57.80
10              paytm money   58140           100770  57.70
11               jio cinema   52198           100770  51.80
12                 snapchat   51236           100770  50.84
13                 telegram   48416           100770  48.05
14          disney+ hotstar   46718           100770  46.36
15                  spotify   46294           100770  45.94
16                   zomato   43834           100770  43.50
17                      ola   42953           100770  42.62
18                messenger   41128           100770  40.81
19                  netflix   40516           100770  40.21
20                     uber   40448           100770  40.14
21                 linkedin   39664           100770  39.36
22                   swiggy   37201           100770  36.92
23                    clock   36003           100770  35.73
24                   meesho   34437           100770  34.17
25              google news   31024           100770  30.79
26       amazon prime video   26779           100770  26.57
27                   myntra   25899           100770  25.70
28                  grofers   24174           100770  23.99
29               wynk music   22053           100770  21.88
30            google sheets   20685           100770  20.53
31                 onedrive   20420           100770  20.26
32                     zoom   20260           100770  20.11
33               my11circle   19336           100770  19.19
34                ludo king   17685           100770  17.55
35               bookmyshow   17239           100770  17.11
36               mx takatak   16482           100770  16.36
37            microsoft 365   15926           100770  15.80
38                  outlook   15863           100770  15.74
39                     ajio   14557           100770  14.45
40          microsoft teams   13475           100770  13.37
41            google slides   13207           100770  13.11
42                  twitter   12877           100770  12.78
43                sharechat   12714           100770  12.62
44      hdfc mobile banking   12455           100770  12.36
45                    groww   12389           100770  12.29
46                   redbus   11793           100770  11.70
47                     zee5   11674           100770  11.58
48                pinterest   11222           100770  11.14
49                     cred   10659           100770  10.58
50                bigbasket   10296           100770  10.22
51               adobe scan   10053           100770   9.98
52                  sonyliv    9427           100770   9.35
53              axis mobile    9138           100770   9.07
54                  picsart    8927           100770   8.86
55                 in drive    8725           100770   8.66
56                  jiomart    7819           100770   7.76
57          microsoft excel    7590           100770   7.53
58  samsung galaxy wearable    7214           100770   7.16
59           rapido captain    6573           100770   6.52

### Categories

In [9]:
df2 = df_merge.groupby(['categories_l1'])\
                .agg(count = ('user_id', 'nunique'))\
                .sort_values(by='count', ascending=False)\
                .reset_index()

df2['total_customers'] = df_merge.user_id.nunique()
df2['%'] = (df2['count']*100.00/df2['total_customers']).round(2)

In [10]:
df2.sort_values(by='%', ascending=False).head(60)

           categories_l1   count  total_customers       %
0                  tools  100765           100770  100.00
1                 social  100592           100770   99.82
2                    ott   78234           100770   77.64
3              ecommerce   72496           100770   71.94
4   finance_transactions   64575           100770   64.08
5     travel_ridehailing   61721           100770   61.25
6        streaming_music   60862           100770   60.40
7          delivery_food   54651           100770   54.23
8                 office   45440           100770   45.09
9                   news   31105           100770   30.87
10    finance_investment   28357           100770   28.14
11      delivery_grocery   28237           100770   28.02
12        fantasy_sports   19538           100770   19.39
13       travel_bookings   18879           100770   18.73
14                gaming   17749           100770   17.61
15         entertainment   17239           100770   17.11
16           educational   16186           100770   16.06
17            driver_app   10568           100770   10.49
18              wearable    8430           100770    8.37
19                dating    3667           100770    3.64
20                health    2931           100770    2.91
21          finance_news     852           100770    0.85
22            devotional      10           100770    0.01

### Remove most common apps

In [53]:
most_common_apps = ['google maps', 'youtube', 'gmail', 'whatsapp', 'google photos', 
                    'google calendar','clock', 'google news', 'hangouts', 'calculator',
                    'accuweather', 'truecaller'
                   ]

In [35]:
df3 = df_merge[~df_merge['app_list'].isin(most_common_apps)]\
                .groupby(['app_list'])\
                .agg(count = ('user_id', 'nunique'))\
                .sort_values(by='count', ascending=False)\
                .reset_index()

df3['total_customers'] = df_merge.user_id.nunique()
df3['%'] = (df3['count']*100.00/df3['total_customers']).round(2)

In [36]:
df3.head(40)

               app_list  count  total_customers      %
0             instagram  81833           100770  81.21
1              facebook  73284           100770  72.72
2            truecaller  67906           100770  67.39
3              flipkart  58242           100770  57.80
4           paytm money  58140           100770  57.70
5            jio cinema  52198           100770  51.80
6              snapchat  51236           100770  50.84
7              telegram  48416           100770  48.05
8       disney+ hotstar  46718           100770  46.36
9               spotify  46294           100770  45.94
10               zomato  43834           100770  43.50
11                  ola  42953           100770  42.62
12            messenger  41128           100770  40.81
13              netflix  40516           100770  40.21
14                 uber  40448           100770  40.14
15             linkedin  39664           100770  39.36
16               swiggy  37201           100770  36.92
17               meesho  34437           100770  34.17
18   amazon prime video  26779           100770  26.57
19               myntra  25899           100770  25.70
20              grofers  24174           100770  23.99
21           wynk music  22053           100770  21.88
22        google sheets  20685           100770  20.53
23             onedrive  20420           100770  20.26
24                 zoom  20260           100770  20.11
25           my11circle  19336           100770  19.19
26            ludo king  17685           100770  17.55
27           bookmyshow  17239           100770  17.11
28           mx takatak  16482           100770  16.36
29        microsoft 365  15926           100770  15.80
30              outlook  15863           100770  15.74
31                 ajio  14557           100770  14.45
32      microsoft teams  13475           100770  13.37
33        google slides  13207           100770  13.11
34              twitter  12877           100770  12.78
35            sharechat  12714           100770  12.62
36  hdfc mobile banking  12455           100770  12.36
37                groww  12389           100770  12.29
38               redbus  11793           100770  11.70
39                 zee5  11674           100770  11.58

In [37]:
df4 = df_merge[~df_merge['app_list'].isin(most_common_apps)]\
                .groupby(['categories_l1'])\
                .agg(count = ('user_id', 'nunique'))\
                .sort_values(by='count', ascending=False)\
                .reset_index()

df4['total_customers'] = df_merge.user_id.nunique()
df4['%'] = (df4['count']*100.00/df4['total_customers']).round(2)

In [38]:
df4.sort_values(by='%', ascending=False).head(60)

           categories_l1  count  total_customers      %
0                 social  98018           100770  97.27
1                  tools  79281           100770  78.68
2                    ott  78234           100770  77.64
3              ecommerce  72496           100770  71.94
4   finance_transactions  64575           100770  64.08
5     travel_ridehailing  61721           100770  61.25
6        streaming_music  60862           100770  60.40
7          delivery_food  54651           100770  54.23
8                 office  45440           100770  45.09
9     finance_investment  28357           100770  28.14
10      delivery_grocery  28237           100770  28.02
11        fantasy_sports  19538           100770  19.39
12       travel_bookings  18879           100770  18.73
13                gaming  17749           100770  17.61
14         entertainment  17239           100770  17.11
15           educational  16186           100770  16.06
16            driver_app  10568           100770  10.49
17              wearable   8430           100770   8.37
18                dating   3667           100770   3.64
19                health   2931           100770   2.91
20          finance_news    852           100770   0.85
21                  news    143           100770   0.14
22            devotional     10           100770   0.01

### Check

In [39]:
df5 = df_merge[~df_merge['copy_code_clicked'].isna()][~df_merge['app_list'].isin(most_common_apps)]\
                .groupby(['app_list'])\
                .agg(count = ('user_id', 'nunique'))\
                .sort_values(by='count', ascending=False)\
                .reset_index()

df5['total_customers'] = df_merge.user_id.nunique()
df5['%'] = (df5['count']*100.00/df5['total_customers']).round(2)

In [40]:
df5.head(40)

               app_list  count  total_customers      %
0             instagram  81763           100770  81.14
1              facebook  73220           100770  72.66
2            truecaller  67852           100770  67.33
3              flipkart  58194           100770  57.75
4           paytm money  58091           100770  57.65
5            jio cinema  52160           100770  51.76
6              snapchat  51190           100770  50.80
7              telegram  48381           100770  48.01
8       disney+ hotstar  46677           100770  46.32
9               spotify  46253           100770  45.90
10               zomato  43797           100770  43.46
11                  ola  42917           100770  42.59
12            messenger  41102           100770  40.79
13              netflix  40468           100770  40.16
14                 uber  40407           100770  40.10
15             linkedin  39629           100770  39.33
16               swiggy  37160           100770  36.88
17               meesho  34417           100770  34.15
18   amazon prime video  26743           100770  26.54
19               myntra  25876           100770  25.68
20              grofers  24148           100770  23.96
21           wynk music  22022           100770  21.85
22        google sheets  20660           100770  20.50
23             onedrive  20393           100770  20.24
24                 zoom  20240           100770  20.09
25           my11circle  19333           100770  19.19
26            ludo king  17669           100770  17.53
27           bookmyshow  17220           100770  17.09
28           mx takatak  16469           100770  16.34
29        microsoft 365  15908           100770  15.79
30              outlook  15844           100770  15.72
31                 ajio  14543           100770  14.43
32      microsoft teams  13460           100770  13.36
33        google slides  13194           100770  13.09
34              twitter  12870           100770  12.77
35            sharechat  12706           100770  12.61
36  hdfc mobile banking  12441           100770  12.35
37                groww  12377           100770  12.28
38               redbus  11782           100770  11.69
39                 zee5  11664           100770  11.57

In [41]:
df_merge[~df_merge['copy_code_clicked'].isna()]

,user_id,cta_clicked,copy_code_clicked,id,app_list,app_name,categories_l1,categories_l2,values
0,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,amazon prime video,amazon prime video,ott,rest,1
1,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,zomato,zomato,delivery_food,rest,1
2,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,zomato,zomato,delivery_food,rest,1
3,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,alt balaji,alt balaji,ott,rest,1
4,5972f3e07f0aec4b796cb7e1,ctaClicked,copyCodeClicked,5972f3e07f0aec4b796cb7e1,bookmyshow,bookmyshow,entertainment,rest,1
...,...,...,...,...,...,...,...,...,...
2331347,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,ola,ola,travel_ridehailing,ride haling,1
2331348,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,ola driver app,ola driver app,driver_app,driver_app,1
2331349,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,rapido captain,rapido captain,driver_app,driver_app,1
2331350,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,snapchat,snapchat,social,rest,1
2331351,63276f1c426a42baf332def0,ctaClicked,copyCodeClicked,63276f1c426a42baf332def0,spotify,spotify,streaming_music,rest,1

In [42]:
df6 = df_merge[~df_merge['copy_code_clicked'].isna()][~df_merge['app_list'].isin(most_common_apps)]\
                .groupby(['categories_l1'])\
                .agg(count = ('user_id', 'nunique'))\
                .sort_values(by='count', ascending=False)\
                .reset_index()

df6['total_customers'] = df_merge.user_id.nunique()
df6['%'] = (df6['count']*100.00/df6['total_customers']).round(2)

In [43]:
df6.head(40)

           categories_l1  count  total_customers      %
0                 social  97927           100770  97.18
1                  tools  79217           100770  78.61
2                    ott  78159           100770  77.56
3              ecommerce  72441           100770  71.89
4   finance_transactions  64521           100770  64.03
5     travel_ridehailing  61669           100770  61.20
6        streaming_music  60798           100770  60.33
7          delivery_food  54596           100770  54.18
8                 office  45386           100770  45.04
9     finance_investment  28333           100770  28.12
10      delivery_grocery  28207           100770  27.99
11        fantasy_sports  19534           100770  19.38
12       travel_bookings  18859           100770  18.71
13                gaming  17733           100770  17.60
14         entertainment  17220           100770  17.09
15           educational  16166           100770  16.04
16            driver_app  10560           100770  10.48
17              wearable   8418           100770   8.35
18                dating   3659           100770   3.63
19                health   2927           100770   2.90
20          finance_news    850           100770   0.84
21                  news    143           100770   0.14
22            devotional     10           100770   0.01

In [44]:
category_list[category_list['categories_l1'] == 'finance_transactions']

                   app_name         categories_l1 categories_l2
19            airtel thanks  finance_transactions          rest
42              axis mobile  finance_transactions          rest
84                     cred  finance_transactions          rest
110              freecharge  finance_transactions          rest
131                bhim upi  finance_transactions          rest
132              google pay  finance_transactions          rest
201                mobikwik  finance_transactions          rest
239                   paytm  finance_transactions          rest
241             paytm money  finance_transactions          rest
245                 phonepe  finance_transactions          rest
260                    ring  finance_transactions          rest
328  vi (vodafone idea) app  finance_transactions          rest
382             paytm money  finance_transactions          rest
398                    cred  finance_transactions          rest

In [47]:
# df_merge

In [58]:
df7 = df_merge[~df_merge['cta_clicked'].isna()][~df_merge['app_list'].isin(most_common_apps)]\
                .groupby(['categories_l1'])\
                .agg(apps  = ('app_name', set),
                     count = ('user_id', 'nunique'))\
                .sort_values(by='count', ascending=False)\
                .reset_index()
    
df7

,categories_l1,apps,count
0,social,"{linkedin, viber, mx takatak, sharechat, line,...",64093
1,ott,"{alt balaji, voot, amazon prime video, sonyliv...",51417
2,ecommerce,"{myntra, firstcry, meesho, nykaa, zivame, phar...",47854
3,finance_transactions,"{airtel thanks, freecharge, paytm money, mobik...",43547
4,travel_ridehailing,"{quick ride, in drive, blusmart, quickride, ub...",40441
5,streaming_music,"{wynk music, amazon music, spotify, hungama mu...",39672
6,delivery_food,"{swiggy, uber eats, zomato, dunzo}",35700
7,office,"{trello, zoho meeting, ms authenticator, onedr...",28726
8,tools,"{adobe scan, notion, file commander, google sh...",26799
9,finance_investment,"{kite by zerodha, nps, angel broking, namma pa...",18955
10,delivery_grocery,"{bigbasket, grofers delivery app, grofers}",18318
11,fantasy_sports,"{nba, myteam11, nhl, vision11, my11circle, cri...",14386
12,travel_bookings,"{yatra, trivago, airbnb, goibibo, kayak, booki...",12475
13,gaming,"{ludo king, pubg mobile, free fire}",11715
14,entertainment,{bookmyshow},11530
15,educational,"{vedantu, ncert books, caclubindia, edx, diksh...",9816
16,driver_app,"{ola driver app, borzo driver app, shadowfax d...",7560
17,wearable,"{garmin connect, mi fit, huawei health, samsun...",5463
18,dating,"{quackquack, bumble, happn, okcupid, coffee me...",2472
19,health,"{fitbit, nike training club, healthifyme, myfi...",1800
20,finance_news,"{economic times, mint, bloomberg}",521
21,news,"{the indian express, feedly}",99
22,devotional,{aastha tv},5

In [59]:
df7['total_customers'] = df_merge[~df_merge['cta_clicked'].isna()][~df_merge['app_list'].isin(most_common_apps)].user_id.nunique()
df7['%'] = (df7['count']*100.00/df7['total_customers']).round(2)

In [60]:
df7

,categories_l1,apps,count,total_customers,%
0,social,"{linkedin, viber, mx takatak, sharechat, line,...",64093,65603,97.70
1,ott,"{alt balaji, voot, amazon prime video, sonyliv...",51417,65603,78.38
2,ecommerce,"{myntra, firstcry, meesho, nykaa, zivame, phar...",47854,65603,72.94
3,finance_transactions,"{airtel thanks, freecharge, paytm money, mobik...",43547,65603,66.38
4,travel_ridehailing,"{quick ride, in drive, blusmart, quickride, ub...",40441,65603,61.65
5,streaming_music,"{wynk music, amazon music, spotify, hungama mu...",39672,65603,60.47
6,delivery_food,"{swiggy, uber eats, zomato, dunzo}",35700,65603,54.42
7,office,"{trello, zoho meeting, ms authenticator, onedr...",28726,65603,43.79
8,tools,"{adobe scan, notion, file commander, google sh...",26799,65603,40.85
9,finance_investment,"{kite by zerodha, nps, angel broking, namma pa...",18955,65603,28.89
10,delivery_grocery,"{bigbasket, grofers delivery app, grofers}",18318,65603,27.92
11,fantasy_sports,"{nba, myteam11, nhl, vision11, my11circle, cri...",14386,65603,21.93
12,travel_bookings,"{yatra, trivago, airbnb, goibibo, kayak, booki...",12475,65603,19.02
13,gaming,"{ludo king, pubg mobile, free fire}",11715,65603,17.86
14,entertainment,{bookmyshow},11530,65603,17.58
15,educational,"{vedantu, ncert books, caclubindia, edx, diksh...",9816,65603,14.96
16,driver_app,"{ola driver app, borzo driver app, shadowfax d...",7560,65603,11.52
17,wearable,"{garmin connect, mi fit, huawei health, samsun...",5463,65603,8.33
18,dating,"{quackquack, bumble, happn, okcupid, coffee me...",2472,65603,3.77
19,health,"{fitbit, nike training club, healthifyme, myfi...",1800,65603,2.74
20,finance_news,"{economic times, mint, bloomberg}",521,65603,0.79
21,news,"{the indian express, feedly}",99,65603,0.15
22,devotional,{aastha tv},5,65603,0.01