## Imports

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

## Datasets

In [4]:
## Parameter 
start_date = '20231002'
end_date = '20231015'

start_date_range = datetime.strptime(start_date, '%Y%m%d')
end_date_range = datetime.strptime(end_date, '%Y%m%d')

##base

base = f"""

    with orders_tbl as 
        (
            SELECT   
                order_id,
                service_obj_service_name service_name, 
                captain_id,
                lifetimerides,
                CASE 
                WHEN lifetimerides BETWEEN 1 AND 5 THEN 'a. 1 to 5'
                WHEN lifetimerides BETWEEN 6 AND 10 THEN 'b. 6 to 10'
                WHEN lifetimerides BETWEEN 11 AND 20 THEN 'c. 11 to 20'
                WHEN lifetimerides BETWEEN 21 AND 50 THEN 'd. 21 to 50'
                WHEN lifetimerides > 50 AND lifetimerides <= 100 THEN 'e. 51 to 100'
                WHEN lifetimerides > 100 AND lifetimerides <= 200 THEN 'f. 101 to 200'
                WHEN lifetimerides > 200 AND lifetimerides <= 400 THEN 'g. 201 to 400'
                WHEN lifetimerides > 400 AND lifetimerides <= 800 THEN 'h. 401 to 800'
                WHEN lifetimerides > 800 THEN 'i. 800+'
                END captain_ltr,
                avgcaptainrating
            FROM
                orders.order_logs_snapshot
            
            INNER JOIN datasets.captain_single_view
            on captain_id = captainid 
            
            WHERE
                yyyymmdd >= '{start_date}'
                AND yyyymmdd <= '{end_date}'
    
                AND order_status in ('dropped')
                AND spd_fraud_flag != True
                AND service_obj_service_name IN ('Link', 'Auto')
        ) 
        
        SELECT * FROM orders_tbl
"""

df_base = pd.read_sql(base, connection)
df_base.to_csv('df_base_with_ltr_{}_{}.csv'.format(start_date, end_date), index=False)
df_base

In [5]:
df_base = pd.read_csv('df_base_with_ltr_{}_{}.csv'.format(start_date, end_date)) 
df_base.head(2)

,order_id,service_name,captain_id,lifetimerides,captain_ltr,avgcaptainrating
0,651fd9cb9781eb517f4de3bd,Link,640f45c9d7bf2958fb70ff74,577,h. 401 to 800,4.53
1,651fda1fbb70a9053e0a2d8a,Link,64ca87be858781c1fab0c437,544,h. 401 to 800,4.42

In [6]:
grouped_avg = df_base.groupby('captain_ltr')['avgcaptainrating'].transform('mean')

# Fill null values in 'value_column' with the corresponding group average
df_base['avgcaptainrating'] = df_base['avgcaptainrating'].fillna(grouped_avg)
df_base['avgcaptainrating'] = df_base['avgcaptainrating'].round(1)
df_base

,order_id,service_name,captain_id,lifetimerides,captain_ltr,avgcaptainrating
0,651fd9cb9781eb517f4de3bd,Link,640f45c9d7bf2958fb70ff74,577,h. 401 to 800,4.5
1,651fda1fbb70a9053e0a2d8a,Link,64ca87be858781c1fab0c437,544,h. 401 to 800,4.4
2,651fdab49a207c7b871ed03f,Auto,612f658dcb05bcab912dc5a8,1444,i. 800+,4.2
3,651fdafa7db73a4d2cb61326,Auto,646f2ffd885aa0300d90ee63,180,f. 101 to 200,4.2
4,651fdbeb48c8051c177f0be9,Link,5f7b49dc7d99a7913c5b0a44,252,g. 201 to 400,4.4
...,...,...,...,...,...,...
15025827,651a61090e36ff7664fa56d3,Auto,6333d7c862cc3b6590c713c9,3335,i. 800+,4.5
15025828,651a566d8c67782b7b0ff5b1,Auto,602eed94e32da95eabb5fed1,1544,i. 800+,4.3
15025829,651a56e1ce45113227a29d6c,Auto,61c01e019d88022789a568c2,554,h. 401 to 800,4.6
15025830,651a56e1ce45113227a29d6d,Link,63455e1923dd9670d408d319,2371,i. 800+,4.2
15025831,651a58528c67782b7b0ffaf7,Auto,5fc74c9c01414792690de725,187,f. 101 to 200,4.5

In [7]:
df_base.groupby(['service_name', 'avgcaptainrating']).agg({'order_id' : 'nunique', 'captain_id' : 'nunique'})

                               order_id  captain_id
service_name avgcaptainrating
Auto         1.0                    135          65
             1.2                      2           1
             1.3                      9           1
             1.7                      2           1
             1.8                      5           1
             2.0                     59          27
             2.2                     15           6
             2.3                    118          26
             2.4                     27           3
             2.5                     73          20
             2.6                     41          14
             2.7                     75          21
             2.8                    135          24
             2.9                     73          14
             3.0                    703         227
             3.1                    273          48
             3.2                    602         104
             3.3                    803         150
             3.4                   1578         227
             3.5                   2208         329
             3.6                   5073         607
             3.7                   7646         905
             3.8                  19042        1878
             3.9                  31152        2605
             4.0                  75609        6238
             4.1                 127559        9107
             4.2                 347423       21085
             4.3                 554721       28580
             4.4                1064255       49592
             4.5                1049127       47302
             4.6                1161478       48248
             4.7                 544592       19034
             4.8                 169085        7908
             4.9                  17805        2230
             5.0                  12955        3371
Link         1.0                    668         276
             1.2                      2           1
             1.3                      7           2
             1.5                     49          14
             1.7                     13           4
             1.8                      3           2
             2.0                    349         124
             2.2                     13           2
             2.3                    181          41
             2.4                     18           3
             2.5                    265          67
             2.6                     45           9
             2.7                    214          40
             2.8                    143          35
             2.9                    123          16
             3.0                   2994         795
             3.1                    354          43
             3.2                   1013         176
             3.3                   1887         262
             3.4                   2011         267
             3.5                   3210         549
             3.6                   4988         565
             3.7                   9769        1270
             3.8                  16352        1614
             3.9                  24394        1961
             4.0                  57590        5737
             4.1                  91894        6303
             4.2                 245096       15444
             4.3                 467586       24757
             4.4                1328189       56552
             4.5                2084212       75498
             4.6                3029838      106293
             4.7                1554071       58658
             4.8                 645847       33316
             4.9                 138633       11476
             5.0                 119353       22058

In [8]:
conditions = [
    (df_base['avgcaptainrating'] >= 1.0) & (df_base['avgcaptainrating'] < 2.0),
    (df_base['avgcaptainrating'] >= 2.0) & (df_base['avgcaptainrating'] < 3.0),
    (df_base['avgcaptainrating'] >= 3.0) & (df_base['avgcaptainrating'] <= 3.5),
    (df_base['avgcaptainrating'] >= 3.6) & (df_base['avgcaptainrating'] <= 3.7),
    (df_base['avgcaptainrating'] >= 3.8) & (df_base['avgcaptainrating'] <= 3.9),
]

values = [2.0, 3.0, 3.5, 3.7, 3.9]

df_base['rounded_avgcaptainrating'] = df_base['avgcaptainrating']

for condition, value in zip(conditions, values):
    df_base['rounded_avgcaptainrating'] = np.where(condition, value, df_base['rounded_avgcaptainrating'])

In [9]:
df_base.rounded_avgcaptainrating.unique()

array([4.5, 4.4, 4.2, 4.3, 4.1, 4.6, 4.7, 3.9, 4.8, 5. , 4.9, 4. , 3.7,
       3.5, 2. , 3. ])

In [10]:
df_base \
.groupby(['service_name', 'rounded_avgcaptainrating']) \
.agg({'order_id' : 'nunique', 'captain_id' : 'nunique'})

                                       order_id  captain_id
service_name rounded_avgcaptainrating
Auto         2.0                            153          69
             3.0                            616         155
             3.5                           6167        1085
             3.7                          12719        1512
             3.9                          50194        4483
             4.0                          75609        6238
             4.1                         127559        9107
             4.2                         347423       21085
             4.3                         554721       28580
             4.4                        1064255       49592
             4.5                        1049127       47302
             4.6                        1161478       48248
             4.7                         544592       19034
             4.8                         169085        7908
             4.9                          17805        2230
             5.0                          12955        3371
Link         2.0                            742         299
             3.0                           1351         337
             3.5                          11469        2092
             3.7                          14757        1835
             3.9                          40746        3575
             4.0                          57590        5737
             4.1                          91894        6303
             4.2                         245096       15444
             4.3                         467586       24757
             4.4                        1328189       56552
             4.5                        2084212       75498
             4.6                        3029838      106293
             4.7                        1554071       58658
             4.8                         645847       33316
             4.9                         138633       11476
             5.0                         119353       22058

##routeDIff

routeDIff = f"""

with orders_tbl as 
    ( SELECT
            orderdate,
            city,
            service_name,
            estimate_id, 
            estimate_ids,
            captain_id,
            fare_recalculated_reason reason,
            amount_breakup_prev_due_total,
            order_id,
            order_amount,
            fe_re_type,
            fe_re_diff_amount,
            distance_final_distance,
            u.id_array as fare_estimate_id
        FROM
            (
            SELECT   
                city_name as city,
                service_obj_service_name as service_name,
                order_id,
                captain_id,
                amount as order_amount,
                date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
                epoch,
                estimate_id,
                estimate_ids,
                CASE 
                WHEN  customer_obj_gender = '0' THEN 'Male'
                WHEN customer_obj_gender = '1' THEN 'Female'
                ELSE 'Unknown/Other' END
                gender,
                amount_breakup_prev_due_total,
                distance_final_distance,
                fare_recalculated_reason,
                fare_recalculated_type AS fe_re_type,
                fare_recalculated_diff_amount AS fe_re_diff_amount,
                cast(json_parse(estimate_ids) as array<varchar>) AS id_array
            FROM
                orders.order_logs_snapshot
            WHERE
                yyyymmdd >= '{start_date}'
                AND yyyymmdd <= '{end_date}'
                AND order_status in ('dropped')
                AND spd_fraud_flag != True
                AND service_obj_service_name IN ('Link', 'Auto')
            ) as t
        CROSS JOIN UNNEST(t.id_array) AS u(id_array)),

fe_tbl as (
        SELECT
            city AS city,
            user_id as customer_id,
            fare_estimate_id,
            service_name,
            api_context,
            date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
            cast(final_amount AS double) AS fe_amount,
            ride_distance,
            epoch
        FROM
            pricing.fare_estimates_enriched
        WHERE
            yyyymmdd >= '{start_date}'
            AND yyyymmdd <= '{end_date}'
            AND service_name IN ('Link', 'Auto', 'Auto Pool', 'CabEconomy')
            
),
      

merged_tbl as (
    SELECT 
        *,
        CASE 
        WHEN amt_diff < -10 THEN '< -10'
        WHEN amt_diff >= -10 AND amt_diff < -7 THEN '-10 to -7'
        WHEN amt_diff >= -7 AND amt_diff < -5 THEN '-7 to -5'
        WHEN amt_diff >= -5 AND amt_diff < 0 THEN '-5 to 0'
        WHEN amt_diff > 0 AND amt_diff <= 5 THEN '0 to 5'
        WHEN amt_diff > 5 AND amt_diff <= 7 THEN '5 to 7'
        WHEN amt_diff > 7 AND amt_diff <= 10 THEN '7 to 10'
        WHEN amt_diff > 10 THEN '> 10'
        END AS amt_diff_bucket
    FROM
    (
    SELECT  
        o.orderdate,
        o.city,
        o.service_name,
        o.captain_id,
        o.order_id,
        o.estimate_id,
        estimate_ids,
        api_context,
        o.fare_estimate_id,
        o.reason,
        fe_amount,
        o.order_amount,
        o.order_amount -  fe_amount AS amt_diff,
        fe_re_type,
        fe_re_diff_amount,
        row_number() over (partition by o.estimate_id order by f.epoch asc)  as updated_seq 
    From orders_tbl o
    INNER JOIN fe_tbl f
    ON o.fare_estimate_id = f.fare_estimate_id
    AND o.service_name = f.service_name
    )

)
    
    SELECT
        orderdate,
        city,
        service_name,
        captain_id,
        order_id,
        estimate_id,
        fare_estimate_id,
        reason,
        fe_amount,
        order_amount,
        amt_diff,
        fe_re_type,
        fe_re_diff_amount,
        amt_diff_bucket
    FROM merged_tbl
    
    
    Where order_id in (SELECT order_id from merged_tbl where  amt_diff!=0)
    and order_id not in (SELECT order_id from merged_tbl where api_context = '/fare/editOrder')
    and updated_seq = 1
    and reason = 'routeDiff'
    
"""

df_routeDIff = pd.read_sql(routeDIff, connection)
df_routeDIff.to_csv('df_routeDIff_with_ltr.csv', index=False)
df_routeDIff

In [11]:
df_routeDIff = pd.read_csv('df_routeDIff_with_ltr.csv') 
df_routeDIff.head(2)

,orderdate,city,service_name,captain_id,order_id,estimate_id,fare_estimate_id,reason,fe_amount,order_amount,amt_diff,fe_re_type,fe_re_diff_amount,amt_diff_bucket
0,2023-10-15,Chennai,Link,638b311abaa3a5b058a48298,652bb6e5e27b914847feb3df,652bc32c544f0934b03c40b0,652bb698a4c61e3b013b1283,routeDiff,399.0,389.0,-10.0,decrease,10.0,-10 to -7
1,2023-10-08,Chennai,Link,5f4c9fb8f330ba75fa0c6b29,652284d37af97d5a950142d0,652289042537b4489f49bfec,652284c41be44517a90808fe,routeDiff,47.0,75.0,28.0,increase,28.0,> 10

## Analysis
### New vs. Old captains analysis with LTR bins

In [12]:
df_captain_analysis = pd.merge(df_base,
                               df_routeDIff,
                               how='left',
                               on=['order_id', 'captain_id']
                              )
df_captain_analysis.head(2)

,order_id,service_name_x,captain_id,lifetimerides,captain_ltr,avgcaptainrating,rounded_avgcaptainrating,orderdate,city,service_name_y,estimate_id,fare_estimate_id,reason,fe_amount,order_amount,amt_diff,fe_re_type,fe_re_diff_amount,amt_diff_bucket
0,651fd9cb9781eb517f4de3bd,Link,640f45c9d7bf2958fb70ff74,577,h. 401 to 800,4.5,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,651fda1fbb70a9053e0a2d8a,Link,64ca87be858781c1fab0c437,544,h. 401 to 800,4.4,4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
## Taxi

df_agg = df_captain_analysis \
                            .groupby(['captain_ltr']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_captain_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_captain_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_captain_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_captain_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg['date_range'] = start_date + ' to -' + end_date
df_agg['routeDiff_orders %'] = df_agg['routeDiff_orders']*100.0/df_agg['total_net_orders']
df_agg['routeDiff_captain %'] = df_agg['routeDiff_captains']*100.0/df_agg['total_net_captains']
df_agg = df_agg[['date_range', 'captain_ltr', 
                 'total_net_captains', 'routeDiff_captains', 'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
df_agg.round(2)

,date_range,captain_ltr,total_net_captains,routeDiff_captains,routeDiff_captain %,total_net_orders,routeDiff_orders,routeDiff_orders %
0,20231002 to -20231015,a. 1 to 5,13535,4079,30.14,28080,5330,18.98
1,20231002 to -20231015,b. 6 to 10,12125,4968,40.97,49203,9159,18.61
2,20231002 to -20231015,c. 11 to 20,23151,10284,44.42,130967,24373,18.61
3,20231002 to -20231015,d. 21 to 50,61414,31049,50.56,489008,95714,19.57
4,20231002 to -20231015,e. 51 to 100,80965,45153,55.77,893035,175853,19.69
5,20231002 to -20231015,f. 101 to 200,114109,69315,60.74,1683455,337553,20.05
6,20231002 to -20231015,g. 201 to 400,133591,87754,65.69,2670398,538177,20.15
7,20231002 to -20231015,h. 401 to 800,118080,82486,69.86,3266311,647210,19.81
8,20231002 to -20231015,i. 800+,117074,84431,72.12,5815375,996953,17.14

In [14]:
## Taxi

df_agg = df_captain_analysis \
                            .groupby(['service_name_x', 'captain_ltr']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_captain_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_captain_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_captain_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_captain_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()
df_agg.rename(columns = {'service_name_x' : 'service_name'}, inplace=True)

df_agg['date_range'] = start_date + ' to -' + end_date
df_agg['routeDiff_orders %'] = df_agg['routeDiff_orders']*100.0/df_agg['total_net_orders']
df_agg['routeDiff_captain %'] = df_agg['routeDiff_captains']*100.0/df_agg['total_net_captains']
df_agg = df_agg[['date_range', 'service_name', 'captain_ltr', 
                 'total_net_captains', 'routeDiff_captains', 'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
df_agg.round(2)

,date_range,service_name,captain_ltr,total_net_captains,routeDiff_captains,routeDiff_captain %,total_net_orders,routeDiff_orders,routeDiff_orders %
0,20231002 to -20231015,Auto,a. 1 to 5,1722,594,34.49,2868,687,23.95
1,20231002 to -20231015,Auto,b. 6 to 10,1886,847,44.91,4944,1204,24.35
2,20231002 to -20231015,Auto,c. 11 to 20,4377,2139,48.87,15034,3541,23.55
3,20231002 to -20231015,Auto,d. 21 to 50,14864,8486,57.09,73137,17579,24.04
4,20231002 to -20231015,Auto,e. 51 to 100,24223,15845,65.41,174606,41833,23.96
5,20231002 to -20231015,Auto,f. 101 to 200,41499,29793,71.79,423184,100985,23.86
6,20231002 to -20231015,Auto,g. 201 to 400,56545,44467,78.64,837842,198389,23.68
7,20231002 to -20231015,Auto,h. 401 to 800,54481,45892,84.23,1219113,278663,22.86
8,20231002 to -20231015,Auto,i. 800+,50402,44646,88.58,2443730,420639,17.21
9,20231002 to -20231015,Link,a. 1 to 5,11813,3485,29.50,25212,4643,18.42
10,20231002 to -20231015,Link,b. 6 to 10,10241,4123,40.26,44259,7955,17.97
11,20231002 to -20231015,Link,c. 11 to 20,18778,8145,43.38,115933,20832,17.97
12,20231002 to -20231015,Link,d. 21 to 50,46566,22567,48.46,415871,78135,18.79
13,20231002 to -20231015,Link,e. 51 to 100,56764,29314,51.64,718429,134020,18.65
14,20231002 to -20231015,Link,f. 101 to 200,72641,39532,54.42,1260271,236568,18.77
15,20231002 to -20231015,Link,g. 201 to 400,77083,43305,56.18,1832556,339788,18.54
16,20231002 to -20231015,Link,h. 401 to 800,63636,36614,57.54,2047198,368547,18.00
17,20231002 to -20231015,Link,i. 800+,66708,39806,59.67,3371645,576314,17.09

In [15]:
## Taxi

df_agg = df_captain_analysis \
                            .groupby(['rounded_avgcaptainrating']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_captain_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_captain_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_captain_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_captain_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg['date_range'] = start_date + ' to -' + end_date
df_agg['routeDiff_orders %'] = df_agg['routeDiff_orders']*100.0/df_agg['total_net_orders']
df_agg['routeDiff_captain %'] = df_agg['routeDiff_captains']*100.0/df_agg['total_net_captains']
df_agg = df_agg[['date_range', 'rounded_avgcaptainrating', 
                 'total_net_captains', 'routeDiff_captains', 'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
df_agg.round(2)

,date_range,rounded_avgcaptainrating,total_net_captains,routeDiff_captains,routeDiff_captain %,total_net_orders,routeDiff_orders,routeDiff_orders %
0,20231002 to -20231015,2.0,368,131,35.60,895,206,23.02
1,20231002 to -20231015,3.0,492,221,44.92,1967,440,22.37
2,20231002 to -20231015,3.5,3176,1456,45.84,17636,3712,21.05
3,20231002 to -20231015,3.7,3347,1809,54.05,27476,6021,21.91
4,20231002 to -20231015,3.9,8058,4840,60.06,90940,20536,22.58
5,20231002 to -20231015,4.0,11973,6987,58.36,133199,29703,22.30
6,20231002 to -20231015,4.1,15404,9901,64.28,219453,48480,22.09
7,20231002 to -20231015,4.2,36520,23869,65.36,592519,129216,21.81
8,20231002 to -20231015,4.3,53320,35334,66.27,1022307,213317,20.87
9,20231002 to -20231015,4.4,106120,69937,65.90,2392444,472169,19.74
10,20231002 to -20231015,4.5,122753,79998,65.17,3133339,598421,19.10
11,20231002 to -20231015,4.6,154490,98259,63.60,4191316,774741,18.48
12,20231002 to -20231015,4.7,77678,47145,60.69,2098663,352206,16.78
13,20231002 to -20231015,4.8,41217,22578,54.78,814932,131151,16.09
14,20231002 to -20231015,4.9,13702,6819,49.77,156438,26633,17.02
15,20231002 to -20231015,5.0,25426,10235,40.25,132308,23370,17.66

<br><br><br>

## Segmentation

In [15]:
## Parameter 
start_date1 = '20231016'
end_date1 = '20231022'

##segmentation

segmentation = f"""

    with segment as (
    
    SELECT 
        captain_id,
        performance,
        consistency,
        pc_segment
    FROM 
    (
    SELECT 
        *,
        row_number() over(partition by captain_id order by epoch desc) rn
    FROM
        (
        SELECT   
            ols.yyyymmdd,
            ols.epoch,
            ols.service_obj_service_name service_name, 
            ols.captain_id,
            ols.order_id,
            
            CASE 
            WHEN ols.service_obj_service_name = 'Link' THEN b.performance_segment
            WHEN ols.service_obj_service_name = 'Auto' THEN a.performance
            ELSE 'Unknow/New'
            END AS performance,
            
            CASE 
            WHEN ols.service_obj_service_name = 'Link' THEN b.consistency
            WHEN ols.service_obj_service_name = 'Auto' THEN a.consistency
            ELSE 'Unknow/New'
            END AS consistency,
            
            CASE 
            WHEN ols.service_obj_service_name = 'Link' THEN b.performance_segment || '_' || b.consistency
            WHEN ols.service_obj_service_name = 'Auto' THEN a.pc_segment
            ELSE 'Unknow/New'
            END AS pc_segment
            
        FROM
            orders.order_logs_snapshot ols 
            
        LEFT JOIN
            datasets.captain_auto_pc_segments a
            ON ols.captain_id = a.captain_id
            AND ols.yyyymmdd = a.yyyymmdd
            AND ols.service_obj_service_name = a.service_name
            AND a.yyyymmdd >= '{start_date1}'
            AND a.yyyymmdd <= '{end_date1}'
        
        LEFT JOIN
            datasets.poc_segments_immutable_28_days b
            ON ols.captain_id = b.captain_id
            AND ols.yyyymmdd = b.yyyymmdd
            AND ols.service_obj_service_name = b.service_name
            AND ols.service_detail_id = b.servicedetailid
            AND b.yyyymmdd >= '{start_date1}'
            AND b.yyyymmdd <= '{end_date1}'
        
        WHERE
            ols.yyyymmdd >= '{start_date1}'
            AND ols.yyyymmdd <= '{end_date1}'
            AND order_status in ('dropped')
            AND spd_fraud_flag != True
            AND service_obj_service_name IN ('Link', 'Auto')
        )
    ) 
    WHERE 
        rn = 1
    ),    
    
    orders_tbl as 
    (
        SELECT   
            ols.order_id,
            ols.service_obj_service_name service_name, 
            ols.captain_id,
            segment.performance,
            segment.consistency,
            segment.pc_segment
        FROM
            orders.order_logs_snapshot ols
        
        LEFT JOIN segment
        ON ols.captain_id = segment.captain_id 
        
        WHERE
            ols.yyyymmdd >= '{start_date1}'
            AND ols.yyyymmdd <= '{end_date1}'
            AND order_status in ('dropped')
            AND spd_fraud_flag != True
            AND service_obj_service_name IN ('Link', 'Auto')
    ) 
    
    SELECT * FROM orders_tbl
        
"""

df_segmentation = pd.read_sql(segmentation, connection)
df_segmentation.to_csv('df_segmentation_{}_{}.csv'.format(start_date1, end_date1), index=False) 
df_segmentation

In [16]:
df_segmentation = pd.read_csv('df_segmentation_{}_{}.csv'.format(start_date1, end_date1)) 
df_segmentation.head(2)

,order_id,service_name,captain_id,performance,consistency,pc_segment
0,652c811ddd46a057208555d0,Link,64bf911317b096705a391bc4,UHP,daily,UHP_daily
1,652c816b8ca1ac1f45ed244d,Link,6014e1117143230bd4c4e7cb,HP,daily,HP_daily

##routeDIff

routeDIff1 = f"""

with orders_tbl as 
    ( SELECT
            orderdate,
            city,
            service_name,
            estimate_id, 
            estimate_ids,
            captain_id,
            fare_recalculated_reason reason,
            amount_breakup_prev_due_total,
            order_id,
            order_amount,
            fe_re_type,
            fe_re_diff_amount,
            distance_final_distance,
            u.id_array as fare_estimate_id
        FROM
            (
            SELECT   
                city_name as city,
                service_obj_service_name as service_name,
                order_id,
                captain_id,
                amount as order_amount,
                date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
                epoch,
                estimate_id,
                estimate_ids,
                CASE 
                WHEN  customer_obj_gender = '0' THEN 'Male'
                WHEN customer_obj_gender = '1' THEN 'Female'
                ELSE 'Unknown/Other' END
                gender,
                amount_breakup_prev_due_total,
                distance_final_distance,
                fare_recalculated_reason,
                fare_recalculated_type AS fe_re_type,
                fare_recalculated_diff_amount AS fe_re_diff_amount,
                cast(json_parse(estimate_ids) as array<varchar>) AS id_array
            FROM
                orders.order_logs_snapshot
            WHERE
                yyyymmdd >= '{start_date1}'
                AND yyyymmdd <= '{end_date1}'
                AND order_status in ('dropped')
                AND spd_fraud_flag != True
                AND service_obj_service_name IN ('Link', 'Auto')
            ) as t
        CROSS JOIN UNNEST(t.id_array) AS u(id_array)),

fe_tbl as (
        SELECT
            city AS city,
            user_id as customer_id,
            fare_estimate_id,
            service_name,
            api_context,
            date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
            cast(final_amount AS double) AS fe_amount,
            ride_distance,
            epoch
        FROM
            pricing.fare_estimates_enriched
        WHERE
            yyyymmdd >= '{start_date1}'
            AND yyyymmdd <= '{end_date1}'
            AND service_name IN ('Link', 'Auto', 'Auto Pool', 'CabEconomy')
            
),
      

merged_tbl as (
    SELECT 
        *,
        CASE 
        WHEN amt_diff < -10 THEN '< -10'
        WHEN amt_diff >= -10 AND amt_diff < -7 THEN '-10 to -7'
        WHEN amt_diff >= -7 AND amt_diff < -5 THEN '-7 to -5'
        WHEN amt_diff >= -5 AND amt_diff < 0 THEN '-5 to 0'
        WHEN amt_diff > 0 AND amt_diff <= 5 THEN '0 to 5'
        WHEN amt_diff > 5 AND amt_diff <= 7 THEN '5 to 7'
        WHEN amt_diff > 7 AND amt_diff <= 10 THEN '7 to 10'
        WHEN amt_diff > 10 THEN '> 10'
        END AS amt_diff_bucket
    FROM
    (
    SELECT  
        o.orderdate,
        o.city,
        o.service_name,
        o.captain_id,
        o.order_id,
        o.estimate_id,
        estimate_ids,
        api_context,
        o.fare_estimate_id,
        o.reason,
        fe_amount,
        o.order_amount,
        o.order_amount -  fe_amount AS amt_diff,
        fe_re_type,
        fe_re_diff_amount,
        row_number() over (partition by o.estimate_id order by f.epoch asc)  as updated_seq 
    From orders_tbl o
    INNER JOIN fe_tbl f
    ON o.fare_estimate_id = f.fare_estimate_id
    AND o.service_name = f.service_name
    )

)
    
    SELECT
        orderdate,
        city,
        service_name,
        captain_id,
        order_id,
        estimate_id,
        fare_estimate_id,
        reason,
        fe_amount,
        order_amount,
        amt_diff,
        fe_re_type,
        fe_re_diff_amount,
        amt_diff_bucket
    FROM merged_tbl
    
    
    Where order_id in (SELECT order_id from merged_tbl where  amt_diff!=0)
    and order_id not in (SELECT order_id from merged_tbl where api_context = '/fare/editOrder')
    and updated_seq = 1
    and reason = 'routeDiff'
    
"""

df_routeDIff1 = pd.read_sql(routeDIff1, connection)
df_routeDIff1.to_csv('df_routeDIff1_{}_{}.csv'.format(start_date1, end_date1), index=False) 
df_routeDIff1

In [17]:
df_routeDIff1 = pd.read_csv('df_routeDIff1_{}_{}.csv'.format(start_date1, end_date1)) 
df_routeDIff1.head(2)

,orderdate,city,service_name,captain_id,order_id,estimate_id,fare_estimate_id,reason,fe_amount,order_amount,amt_diff,fe_re_type,fe_re_diff_amount,amt_diff_bucket
0,2023-10-21,Chennai,Link,64808752c24bfecd58d830ba,65334e9a9abf3746b19e33e3,653351e5800b91ed59673d9e,65334e962a4f47448bc47ce7,routeDiff,34.0,32.0,-2.0,decrease,2.0,-5 to 0
1,2023-10-22,Hyderabad,Link,610020417b23c8f7c9a676a6,653454991686876329d14075,65345adf2bf378fac6382d81,653454873a9dc2b98cc75280,routeDiff,79.0,74.0,-5.0,decrease,5.0,-5 to 0

In [18]:
df_segment_analysis = pd.merge(df_segmentation,
                               df_routeDIff1,
                               how='left',
                               on=['captain_id','order_id']
                              )
df_segment_analysis.head(2)

,order_id,service_name_x,captain_id,performance,consistency,pc_segment,orderdate,city,service_name_y,estimate_id,fare_estimate_id,reason,fe_amount,order_amount,amt_diff,fe_re_type,fe_re_diff_amount,amt_diff_bucket
0,652c811ddd46a057208555d0,Link,64bf911317b096705a391bc4,UHP,daily,UHP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,652c816b8ca1ac1f45ed244d,Link,6014e1117143230bd4c4e7cb,HP,daily,HP_daily,2023-10-16,Jaipur,Link,652c8669a3f2d0e026b31850,652c814da3f2d0f9c2b2eb5f,routeDiff,65.0,56.0,-9.0,decrease,9.0,-10 to -7

In [19]:
## Taxi

df_agg = df_segment_analysis \
                            .groupby(['service_name_x', 'performance']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_segment_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_segment_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_segment_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_segment_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg.rename(columns = {'service_name_x' : 'service_name'}, inplace=True)

df_agg['date_range'] = start_date + ' to -' + end_date1
df_agg['routeDiff_orders %'] = df_agg['routeDiff_orders']*100.0/df_agg['total_net_orders']
df_agg['routeDiff_captain %'] = df_agg['routeDiff_captains']*100.0/df_agg['total_net_captains']
df_agg = df_agg[['date_range', 'service_name', 'performance', ## 'consistency', 'pc_segment', 
                 'total_net_captains', 'routeDiff_captains', 'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
df_agg[df_agg['total_net_captains'] > 10].round(2)

,date_range,service_name,performance,total_net_captains,routeDiff_captains,routeDiff_captain %,total_net_orders,routeDiff_orders,routeDiff_orders %
0,20231002 to -20231022,Auto,HP,13899,13012,93.62,660067,127558,19.33
1,20231002 to -20231022,Auto,LP,122281,72725,59.47,603866,150423,24.91
2,20231002 to -20231022,Auto,MP,74010,62713,84.74,1205466,281631,23.36
3,20231002 to -20231022,Auto,UHP,2968,2759,92.96,319383,28209,8.83
4,20231002 to -20231022,Link,HP,35270,23243,65.90,1323445,229497,17.34
5,20231002 to -20231022,Link,LP,134234,52000,38.74,749015,139408,18.61
6,20231002 to -20231022,Link,MP,138030,83391,60.42,2137787,402004,18.80
7,20231002 to -20231022,Link,UHP,11761,6835,58.12,809378,125984,15.57

Check for multiple weeks (min 3 weeks)

Auto
- UHP, HP -> 93% (Less routeDiff_orders %)
- ML-83%, LP-58% (High routeDiff_orders %)

Link
- UHP -> 59% (Less routeDiff_orders %)

- HP -> 67% (High routeDiff_orders %)
- ML-60% (High routeDiff_orders %)
- LP-58% (High routeDiff_orders %)

In [20]:
## Taxi

df_agg = df_segment_analysis \
                            .groupby(['service_name_x', 'consistency']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_segment_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_segment_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_segment_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_segment_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg.rename(columns = {'service_name_x' : 'service_name'}, inplace=True)

df_agg['date_range'] = start_date + ' to -' + end_date1
df_agg['routeDiff_orders %'] = df_agg['routeDiff_orders']*100.0/df_agg['total_net_orders']
df_agg['routeDiff_captain %'] = df_agg['routeDiff_captains']*100.0/df_agg['total_net_captains']
df_agg = df_agg[['date_range', 'service_name', 'consistency', ## 'consistency', 'pc_segment', 
                 'total_net_captains', 'routeDiff_captains', 'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
df_agg[df_agg['total_net_captains'] > 10].round(2)

,date_range,service_name,consistency,total_net_captains,routeDiff_captains,routeDiff_captain %,total_net_orders,routeDiff_orders,routeDiff_orders %
0,20231002 to -20231022,Auto,daily,88015,77365,87.90,1943522,404251,20.80
1,20231002 to -20231022,Auto,inter,60129,29715,49.42,282428,60417,21.39
3,20231002 to -20231022,Auto,intra,65008,44124,67.87,562765,123138,21.88
5,20231002 to -20231022,Link,daily,215426,121728,56.51,4448089,789159,17.74
6,20231002 to -20231022,Link,inter,25,13,52.00,277,67,24.19
7,20231002 to -20231022,Link,inter_week,34864,12440,35.68,115615,21553,18.64
9,20231002 to -20231022,Link,intra_week,68979,31288,45.36,455634,86114,18.90

Auto
- Daily > Intra > Inter

Link
- Daily > Inter > Intra week > Inter week

In [21]:

## Taxi

df_agg = df_segment_analysis \
                            .groupby(['service_name_x', 'pc_segment']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_segment_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_segment_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_segment_analysis['orderdate'].notna())
                                                                 &
                                                                 (df_segment_analysis['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg.rename(columns = {'service_name_x' : 'service_name'}, inplace=True)

df_agg['date_range'] = start_date + ' to -' + end_date1
df_agg['routeDiff_orders %'] = df_agg['routeDiff_orders']*100.0/df_agg['total_net_orders']
df_agg['routeDiff_captain %'] = df_agg['routeDiff_captains']*100.0/df_agg['total_net_captains']
df_agg = df_agg[['date_range', 'service_name', 'pc_segment', ## 'consistency', 'pc_segment', 
                 'total_net_captains', 'routeDiff_captains', 'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
df_agg[df_agg['total_net_captains'] > 10].round(2)

,date_range,service_name,pc_segment,total_net_captains,routeDiff_captains,routeDiff_captain %,total_net_orders,routeDiff_orders,routeDiff_orders %
0,20231002 to -20231022,Auto,HP_daily,9828,9496,96.62,520270,102951,19.79
1,20231002 to -20231022,Auto,HP_inter,1854,1548,83.50,51282,8815,17.19
2,20231002 to -20231022,Auto,HP_intra,2217,1968,88.77,88515,15792,17.84
3,20231002 to -20231022,Auto,LP_daily,30749,24658,80.19,268475,68174,25.39
4,20231002 to -20231022,Auto,LP_inter,46069,19719,42.80,114479,27862,24.34
6,20231002 to -20231022,Auto,LP_intra,45460,28345,62.35,220865,54375,24.62
8,20231002 to -20231022,Auto,MP_daily,45197,41064,90.86,884882,208914,23.61
9,20231002 to -20231022,Auto,MP_inter,11882,8190,68.93,99746,22330,22.39
11,20231002 to -20231022,Auto,MP_intra,16929,13458,79.50,220825,50385,22.82
12,20231002 to -20231022,Auto,UHP_daily,2241,2147,95.81,269895,24212,8.97
13,20231002 to -20231022,Auto,UHP_inter,324,258,79.63,16921,1410,8.33
15,20231002 to -20231022,Auto,UHP_intra,402,353,87.81,32560,2586,7.94
16,20231002 to -20231022,Link,HP_daily,28977,19246,66.42,1226831,211598,17.25
17,20231002 to -20231022,Link,HP_inter,14,8,57.14,238,61,25.63
18,20231002 to -20231022,Link,HP_inter_week,2349,1459,62.11,21933,4143,18.89
19,20231002 to -20231022,Link,HP_intra_week,3930,2530,64.38,74443,13695,18.40
20,20231002 to -20231022,Link,LP_daily,75453,32877,43.57,572167,105571,18.45
22,20231002 to -20231022,Link,LP_inter_week,19529,4921,25.20,31680,6183,19.52
23,20231002 to -20231022,Link,LP_intra_week,39247,14200,36.18,145153,27652,19.05
24,20231002 to -20231022,Link,MP_daily,100482,63294,62.99,1867698,349523,18.71
26,20231002 to -20231022,Link,MP_inter_week,12422,5811,46.78,53712,10148,18.89
28,20231002 to -20231022,Link,MP_intra_week,25116,14281,56.86,216340,42327,19.57
29,20231002 to -20231022,Link,UHP_daily,10513,6310,60.02,781392,122466,15.67
30,20231002 to -20231022,Link,UHP_inter_week,562,248,44.13,8288,1078,13.01
31,20231002 to -20231022,Link,UHP_intra_week,686,277,40.38,19698,2440,12.39

## Captain Rating + Segmentation

In [22]:
## Parameter 
start_date1 = '20231016'
end_date1 = '20231022'

##base

base1 = f"""

    with orders_tbl as 
        (
            SELECT   
                order_id,
                service_obj_service_name service_name, 
                captain_id,
                lifetimerides,
                CASE 
                WHEN lifetimerides BETWEEN 1 AND 5 THEN 'a. 1 to 5'
                WHEN lifetimerides BETWEEN 6 AND 10 THEN 'b. 6 to 10'
                WHEN lifetimerides BETWEEN 11 AND 20 THEN 'c. 11 to 20'
                WHEN lifetimerides BETWEEN 21 AND 50 THEN 'd. 21 to 50'
                WHEN lifetimerides > 50 AND lifetimerides <= 100 THEN 'e. 51 to 100'
                WHEN lifetimerides > 100 AND lifetimerides <= 200 THEN 'f. 101 to 200'
                WHEN lifetimerides > 200 AND lifetimerides <= 400 THEN 'g. 201 to 400'
                WHEN lifetimerides > 400 AND lifetimerides <= 800 THEN 'h. 401 to 800'
                WHEN lifetimerides > 800 THEN 'i. 800+'
                END captain_ltr,
                avgcaptainrating
            FROM
                orders.order_logs_snapshot
            
            INNER JOIN datasets.captain_single_view
            on captain_id = captainid 
            
            WHERE
                yyyymmdd >= '{start_date1}'
                AND yyyymmdd <= '{end_date1}'
    
                AND order_status in ('dropped')
                AND spd_fraud_flag != True
                AND service_obj_service_name IN ('Link', 'Auto')
        ) 
        
        SELECT * FROM orders_tbl
"""

df_base1 = pd.read_sql(base1, connection)
df_base1.to_csv('df_base1_with_ltr_{}_{}.csv'.format(start_date1, end_date1), index=False)
df_base1

##base

base1_lm = f"""

    with orders_tbl as 
        (
            SELECT   
                order_id,
                service_obj_service_name service_name, 
                captain_id,
                distance_final_distance last_mile
            FROM
                orders.order_logs_snapshot
            
            WHERE
                yyyymmdd >= '{start_date1}'
                AND yyyymmdd <= '{end_date1}'
    
                AND order_status in ('dropped')
                AND spd_fraud_flag != True
                AND service_obj_service_name IN ('Link', 'Auto')
        ) 
        
        SELECT * FROM orders_tbl
"""

df_base1_lm = pd.read_sql(base1_lm, connection)
df_base1_lm.to_csv('df_base1_with_lm_{}_{}.csv'.format(start_date1, end_date1), index=False)
df_base1_lm

In [23]:
df_base1_lm = pd.read_csv('df_base1_with_lm_{}_{}.csv'.format(start_date1, end_date1)) 
df_base1_lm.head(2)

                   order_id service_name                captain_id  last_mile
0  6532c6464c28820c53a60fed         Link  635baa95d58af72732db6a84      1.700
1  6532c6594033182c9ec341d8         Link  64e2e078fb75840616e1b1fc      5.142

In [24]:
df_base1 = pd.read_csv('df_base1_with_ltr_{}_{}.csv'.format(start_date1, end_date1)) 
df_base1.head(2)

,order_id,service_name,captain_id,lifetimerides,captain_ltr,avgcaptainrating
0,6534dfd1ccfcf22e7fd69ca3,Auto,5d2dc7786ed7674e61149fb2,1011,i. 800+,4.42
1,6534dfe64033182c9ec7dc9a,Link,63d3c3e5f17fa775d2ee41c3,1225,i. 800+,4.59

In [25]:
## merge lm info

df_base1 = pd.merge(df_base1,df_base1_lm, how='left', on=['order_id','service_name','captain_id'])

In [26]:
conditions = [
    (df_base1['last_mile'] >= 0.0) & (df_base1['last_mile'] < 2.0),
    (df_base1['last_mile'] >= 2.0) & (df_base1['last_mile'] < 5.0),
    (df_base1['last_mile'] >= 5.0) & (df_base1['last_mile'] < 8.0),
    (df_base1['last_mile'] >= 8.0) & (df_base1['last_mile'] < 12.0),
    (df_base1['last_mile'] >= 12.0),
    ]

values = ['below 2km', '2-5km', '5-8km', '8-12km', '12+ km']

df_base1['rounded_last_mile'] = df_base1['last_mile']

for condition, value in zip(conditions, values):
    df_base1['rounded_last_mile'] = np.where(condition, value, df_base1['rounded_last_mile'])

In [27]:
grouped_avg1 = df_base1.groupby('captain_ltr')['avgcaptainrating'].transform('mean')

# Fill null values in 'value_column' with the corresponding group average
df_base1['avgcaptainrating'] = df_base1['avgcaptainrating'].fillna(grouped_avg1)
df_base1['avgcaptainrating'] = df_base1['avgcaptainrating'].round(1)
df_base1

,order_id,service_name,captain_id,lifetimerides,captain_ltr,avgcaptainrating,last_mile,rounded_last_mile
0,6534dfd1ccfcf22e7fd69ca3,Auto,5d2dc7786ed7674e61149fb2,1011,i. 800+,4.4,3.660,2-5km
1,6534dfe64033182c9ec7dc9a,Link,63d3c3e5f17fa775d2ee41c3,1225,i. 800+,4.6,5.980,5-8km
2,6534e2abe49af525e066a2ba,Link,5cb989fb54bc7263ff418c25,190,f. 101 to 200,4.6,1.530,below 2km
3,6534e2eafed63e17c49ca84e,Link,5d88beadaf7944215671fa16,275,g. 201 to 400,4.6,8.380,8-12km
4,6534e96c4033182c9ec7f4d5,Auto,6470c319703079827ea28013,704,h. 401 to 800,4.6,1.070,below 2km
...,...,...,...,...,...,...,...,...
7808376,653251e6dc9b7e3eae694451,Link,5d18f6493b752c45cf907e16,3843,i. 800+,4.7,4.185,2-5km
7808377,6532522833744d12a3cee65b,Auto,5d4a804d55fbf50d45e7651d,1049,i. 800+,4.5,9.460,8-12km
7808378,653253324033182c9ec20b98,Auto,629ae14c0fb5e9f1382d26ba,762,h. 401 to 800,4.6,1.240,below 2km
7808379,6532494047e18a6deb3f0870,Link,64966e1f4e8ea9b963388717,787,h. 401 to 800,4.6,5.070,5-8km
7808380,6532499833744d12a3cecb48,Auto,62e53a06eef1b17d55c895c6,1232,i. 800+,4.4,5.230,5-8km

In [28]:
df_base1.groupby(['service_name', 'avgcaptainrating']).agg({'order_id' : 'nunique', 'captain_id' : 'nunique'})

                               order_id  captain_id
service_name avgcaptainrating
Auto         1.0                     91          50
             1.2                      3           1
             1.3                     13           4
             1.8                      1           1
             2.0                     24          11
             2.2                     13           6
             2.3                     39          11
             2.4                      3           2
             2.5                     27          16
             2.6                     29           7
             2.7                     40          17
             2.8                     62          20
             2.9                     25          12
             3.0                    427         156
             3.1                    235          43
             3.2                    285          74
             3.3                    605         124
             3.4                    770         172
             3.5                   1463         257
             3.6                   2771         492
             3.7                   4503         738
             3.8                  10070        1493
             3.9                  16591        2203
             4.0                  40498        5136
             4.1                  68327        7663
             4.2                 187956       17971
             4.3                 296165       24392
             4.4                 574412       42845
             4.5                 563744       40789
             4.6                 623932       41474
             4.7                 286950       16271
             4.8                  91206        6644
             4.9                  10394        1802
             5.0                   7108        2261
Link         1.0                    376         150
             1.3                      1           1
             1.5                     34           9
             1.9                      6           1
             2.0                    181          63
             2.2                     25           6
             2.3                    103          32
             2.4                     20           3
             2.5                    152          37
             2.6                     30           6
             2.7                     86          23
             2.8                     92          22
             2.9                     48           9
             3.0                   1569         465
             3.1                    134          23
             3.2                    528          91
             3.3                    691         157
             3.4                   1113         189
             3.5                   1828         333
             3.6                   2449         350
             3.7                   4599         759
             3.8                   8659        1117
             3.9                  12932        1431
             4.0                  29755        3784
             4.1                  45403        4455
             4.2                 124419       11226
             4.3                 235228       18262
             4.4                 669348       43210
             4.5                1042849       58744
             4.6                1543248       82861
             4.7                 818053       45819
             4.8                 344460       25059
             4.9                  70201        7984
             5.0                  60979       12615

In [29]:
df_base1_auto = df_base1[df_base1['service_name'].isin(['Auto'])]
df_base1_link = df_base1[df_base1['service_name'].isin(['Link'])]

In [30]:
conditions = [
    (df_base1_auto['avgcaptainrating'] >= 1.0) & (df_base1_auto['avgcaptainrating'] < 4.0),
    (df_base1_auto['avgcaptainrating'] >= 4.0) & (df_base1_auto['avgcaptainrating'] < 4.3),
    (df_base1_auto['avgcaptainrating'] >= 4.3) & (df_base1_auto['avgcaptainrating'] < 4.6),
    (df_base1_auto['avgcaptainrating'] >= 4.6) & (df_base1_auto['avgcaptainrating'] < 4.8),
    (df_base1_auto['avgcaptainrating'] >= 4.8) & (df_base1_auto['avgcaptainrating'] < 5.0),
    ]

values = [3.9, 4.3, 4.5, 4.7, 5.0]

df_base1_auto['rounded_avgcaptainrating'] = df_base1_auto['avgcaptainrating']

for condition, value in zip(conditions, values):
    df_base1_auto['rounded_avgcaptainrating'] = np.where(condition, value, df_base1_auto['rounded_avgcaptainrating'])

In [31]:
conditions = [
    (df_base1_link['avgcaptainrating'] >= 1.0) & (df_base1_link['avgcaptainrating'] < 4.0),
    (df_base1_link['avgcaptainrating'] >= 4.0) & (df_base1_link['avgcaptainrating'] < 4.4),
    (df_base1_link['avgcaptainrating'] >= 4.4) & (df_base1_link['avgcaptainrating'] < 4.6),
    (df_base1_link['avgcaptainrating'] >= 4.6) & (df_base1_link['avgcaptainrating'] < 4.8),
    (df_base1_link['avgcaptainrating'] >= 4.8) & (df_base1_link['avgcaptainrating'] < 5.0),
    (df_base1_link['avgcaptainrating'] == 5.0),
    ]

values = [3.9, 4.3, 4.5, 4.7, 4.9, 5.0]

df_base1_link['rounded_avgcaptainrating'] = df_base1_link['avgcaptainrating']

for condition, value in zip(conditions, values):
    df_base1_link['rounded_avgcaptainrating'] = np.where(condition, value, df_base1_link['rounded_avgcaptainrating'])

In [32]:
df_base1_auto.rounded_avgcaptainrating.unique()

array([4.5, 4.7, 4.3, 5. , 3.9])

In [33]:
df_base1_link.rounded_avgcaptainrating.unique()

array([4.7, 4.5, 4.9, 4.3, 3.9, 5. ])

In [34]:
frames = [df_base1_auto,df_base1_link]
df_basev1 = pd.concat(frames)

In [35]:
df_basev1.rounded_avgcaptainrating.unique()

array([4.5, 4.7, 4.3, 5. , 3.9, 4.9])

In [36]:
df_basev1.groupby(['service_name', 'rounded_avgcaptainrating']).agg({'order_id' : 'nunique', 'captain_id' : 'nunique'})

                                       order_id  captain_id
service_name rounded_avgcaptainrating
Auto         3.9                          38090        5910
             4.3                         296781       30770
             4.5                        1434321      108026
             4.7                         910882       57745
             5.0                         108708       10707
Link         3.9                          35656        5277
             4.3                         434805       37727
             4.5                        1712197      101954
             4.7                        2361301      128680
             4.9                         414661       33043
             5.0                          60979       12615

In [37]:
df_basev1.groupby(['service_name', 'rounded_last_mile']).agg({'order_id' : 'nunique', 'captain_id' : 'nunique'})

                                order_id  captain_id
service_name rounded_last_mile
Auto         12+ km               435015      118781
             2-5km                946246      145176
             5-8km                611569      150153
             8-12km               453934      135208
             below 2km            342018       74790
Link         12+ km               382256      140143
             2-5km               2169794      267659
             5-8km               1133774      238037
             8-12km               630735      191479
             below 2km            703040      181692

In [38]:
df_basev1

,order_id,service_name,captain_id,lifetimerides,captain_ltr,avgcaptainrating,last_mile,rounded_last_mile,rounded_avgcaptainrating
0,6534dfd1ccfcf22e7fd69ca3,Auto,5d2dc7786ed7674e61149fb2,1011,i. 800+,4.4,3.660,2-5km,4.5
4,6534e96c4033182c9ec7f4d5,Auto,6470c319703079827ea28013,704,h. 401 to 800,4.6,1.070,below 2km,4.7
6,6534eadfc53bf00fc8a6f0b2,Auto,5f895ee0fb10b88d9e2471d0,2697,i. 800+,4.5,9.903,8-12km,4.5
7,6534deed1686876329d2907d,Auto,6187c5f9b281d73c9ac87c50,1459,i. 800+,4.5,1.770,below 2km,4.5
9,6534e0b98c1cc00bb7a2b78d,Auto,6177e11397513c3c18d5a9c6,1722,i. 800+,4.6,0.510,below 2km,4.7
...,...,...,...,...,...,...,...,...,...
7808373,65325079a20d2d0c2e9cd271,Link,64ace9dcc4d7796e3d85614f,835,i. 800+,4.7,4.240,2-5km,4.7
7808374,653250bda20d2d0c2e9cd34e,Link,64d8a4148103d9ac3b9ed5a5,244,g. 201 to 400,4.6,0.980,below 2km,4.7
7808375,653251cd33744d12a3cee542,Link,64004a9e8e212cc2c64bf041,228,g. 201 to 400,4.4,1.654,below 2km,4.5
7808376,653251e6dc9b7e3eae694451,Link,5d18f6493b752c45cf907e16,3843,i. 800+,4.7,4.185,2-5km,4.7
7808379,6532494047e18a6deb3f0870,Link,64966e1f4e8ea9b963388717,787,h. 401 to 800,4.6,5.070,5-8km,4.7

In [39]:
df_segment_analysis

,order_id,service_name_x,captain_id,performance,consistency,pc_segment,orderdate,city,service_name_y,estimate_id,fare_estimate_id,reason,fe_amount,order_amount,amt_diff,fe_re_type,fe_re_diff_amount,amt_diff_bucket
0,652c811ddd46a057208555d0,Link,64bf911317b096705a391bc4,UHP,daily,UHP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,652c816b8ca1ac1f45ed244d,Link,6014e1117143230bd4c4e7cb,HP,daily,HP_daily,2023-10-16,Jaipur,Link,652c8669a3f2d0e026b31850,652c814da3f2d0f9c2b2eb5f,routeDiff,65.0,56.0,-9.0,decrease,9.0,-10 to -7
2,652c7de947b95d6fddcfdde3,Auto,63c7796d87dc9022eddc759a,MP,daily,MP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,652c7b2a8ca1ac1f45ed1c73,Link,62239ce3f0b26be55061fda9,LP,daily,LP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,652c80d68ca1ac1f45ed238b,Auto,62a0db8317af9a5132512b10,LP,intra,LP_intra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7808405,65321336dc9b7e3eae6880c4,Link,61fb9130ebef824f2f2c432d,LP,daily,LP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7808406,65321458e47099469228881a,Link,633c38d7f5442149ff034fea,MP,daily,MP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7808407,65321491e4709946922888b1,Link,62e56411d8a2490105b085a1,HP,daily,HP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7808408,653214bb1686876329cbf28b,Auto,5f6dcbdf7d99a7734d561e10,MP,intra,MP_intra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7808409,653214d647e18a6deb3e64ba,Link,5b236a98c83c3b590c7788ff,MP,daily,MP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df_rating_segment = pd.merge(df_segment_analysis,
                             df_basev1,
                             how='left',
                             left_on = ['captain_id', 'order_id', 'service_name_x'],
                             right_on = ['captain_id', 'order_id', 'service_name']
                            )
df_rating_segment

,order_id,service_name_x,captain_id,performance,consistency,pc_segment,orderdate,city,service_name_y,estimate_id,fare_estimate_id,reason,fe_amount,order_amount,amt_diff,fe_re_type,fe_re_diff_amount,amt_diff_bucket,service_name,lifetimerides,captain_ltr,avgcaptainrating,last_mile,rounded_last_mile,rounded_avgcaptainrating
0,652c811ddd46a057208555d0,Link,64bf911317b096705a391bc4,UHP,daily,UHP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Link,932.0,i. 800+,4.6,5.790,5-8km,4.7
1,652c816b8ca1ac1f45ed244d,Link,6014e1117143230bd4c4e7cb,HP,daily,HP_daily,2023-10-16,Jaipur,Link,652c8669a3f2d0e026b31850,652c814da3f2d0f9c2b2eb5f,routeDiff,65.0,56.0,-9.0,decrease,9.0,-10 to -7,Link,986.0,i. 800+,4.5,4.876,2-5km,4.5
2,652c7de947b95d6fddcfdde3,Auto,63c7796d87dc9022eddc759a,MP,daily,MP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Auto,1404.0,i. 800+,4.4,2.890,2-5km,4.5
3,652c7b2a8ca1ac1f45ed1c73,Link,62239ce3f0b26be55061fda9,LP,daily,LP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Link,501.0,h. 401 to 800,4.8,1.340,below 2km,4.9
4,652c80d68ca1ac1f45ed238b,Auto,62a0db8317af9a5132512b10,LP,intra,LP_intra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Auto,175.0,f. 101 to 200,4.7,3.850,2-5km,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7808405,65321336dc9b7e3eae6880c4,Link,61fb9130ebef824f2f2c432d,LP,daily,LP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Link,330.0,g. 201 to 400,4.6,0.950,below 2km,4.7
7808406,65321458e47099469228881a,Link,633c38d7f5442149ff034fea,MP,daily,MP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Link,280.0,g. 201 to 400,4.5,3.200,2-5km,4.5
7808407,65321491e4709946922888b1,Link,62e56411d8a2490105b085a1,HP,daily,HP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Link,430.0,h. 401 to 800,4.4,1.510,below 2km,4.5
7808408,653214bb1686876329cbf28b,Auto,5f6dcbdf7d99a7734d561e10,MP,intra,MP_intra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Auto,547.0,h. 401 to 800,4.2,13.960,12+ km,4.3
7808409,653214d647e18a6deb3e64ba,Link,5b236a98c83c3b590c7788ff,MP,daily,MP_daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Link,360.0,g. 201 to 400,4.6,1.990,below 2km,4.7

In [41]:
## Taxi

df_agg2 = df_rating_segment \
                            .groupby(['service_name_x', 'performance']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg2['date_range'] = start_date1 + ' to -' + end_date1
df_agg2['routeDiff_orders %'] = df_agg2['routeDiff_orders']*100.0/df_agg2['total_net_orders']
df_agg2['routeDiff_captain %'] = df_agg2['routeDiff_captains']*100.0/df_agg2['total_net_captains']
df_agg2 = df_agg2[['service_name_x', 'performance',
                 'total_net_captains', 'routeDiff_captains', ##'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
print(start_date1, end_date1)
df_agg2.round(2)

20231016 20231022

,service_name_x,performance,total_net_captains,routeDiff_captains,total_net_orders,routeDiff_orders,routeDiff_orders %
0,Auto,HP,13899,13012,660067,127558,19.33
1,Auto,LP,122281,72725,603866,150423,24.91
2,Auto,MP,74010,62713,1205466,281631,23.36
3,Auto,UHP,2968,2759,319383,28209,8.83
4,Link,HP,35270,23243,1323445,229497,17.34
5,Link,LP,134234,52000,749015,139408,18.61
6,Link,MP,138030,83391,2137787,402004,18.80
7,Link,UHP,11761,6835,809378,125984,15.57
8,Link,ZP,3,2,3,2,66.67

In [42]:
## Taxi

df_agg2 = df_rating_segment \
                            .groupby(['service_name_x', 'performance','rounded_last_mile']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg2['date_range'] = start_date1 + ' to -' + end_date1
df_agg2['routeDiff_orders %'] = df_agg2['routeDiff_orders']*100.0/df_agg2['total_net_orders']
df_agg2['routeDiff_captain %'] = df_agg2['routeDiff_captains']*100.0/df_agg2['total_net_captains']
df_agg2 = df_agg2[['service_name_x', 'performance', 'rounded_last_mile',
                 'total_net_captains', 'routeDiff_captains', ##'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
print(start_date1, end_date1)
df_agg2.round(2)

20231016 20231022

,service_name_x,performance,rounded_last_mile,total_net_captains,routeDiff_captains,total_net_orders,routeDiff_orders,routeDiff_orders %
0,Auto,HP,12+ km,10075,7672,64243,24729,38.49
1,Auto,HP,2-5km,13476,10368,257645,34698,13.47
2,Auto,HP,5-8km,13290,10512,148572,32672,21.99
3,Auto,HP,8-12km,12115,9266,94410,28504,30.19
4,Auto,HP,below 2km,11740,4196,95197,6955,7.31
5,Auto,LP,12+ km,62429,35270,161582,57890,35.83
6,Auto,LP,2-5km,65085,18309,141747,22025,15.54
7,Auto,LP,5-8km,70635,24794,139732,30684,21.96
8,Auto,LP,8-12km,65291,27992,127702,36267,28.40
9,Auto,LP,below 2km,22387,3343,33103,3557,10.75
10,Auto,MP,12+ km,45002,31618,204556,78526,38.39
11,Auto,MP,2-5km,63677,32715,385152,58955,15.31
12,Auto,MP,5-8km,63471,36896,286849,67236,23.44
13,Auto,MP,8-12km,55740,35130,219765,67068,30.52
14,Auto,MP,below 2km,37781,8141,109144,9846,9.02
15,Auto,UHP,12+ km,1275,750,4634,1618,34.92
16,Auto,UHP,2-5km,2938,2546,161702,13125,8.12
17,Auto,UHP,5-8km,2757,1989,36416,6634,18.22
18,Auto,UHP,8-12km,2062,1212,12057,3140,26.04
19,Auto,UHP,below 2km,2882,1321,104574,3692,3.53
20,Link,HP,12+ km,23005,13569,88034,31998,36.35
21,Link,HP,2-5km,34692,20078,590420,78307,13.26
22,Link,HP,5-8km,33396,18821,294719,57793,19.61
23,Link,HP,8-12km,29797,16566,156668,42476,27.11
24,Link,HP,below 2km,31005,10093,193604,18923,9.77
25,Link,LP,12+ km,39443,16272,72548,23146,31.90
26,Link,LP,2-5km,94994,25230,297204,43020,14.47
27,Link,LP,5-8km,77892,23226,175159,34695,19.81
28,Link,LP,8-12km,57248,19466,108450,27422,25.29
29,Link,LP,below 2km,50132,8452,95641,11122,11.63
30,Link,MP,12+ km,70031,37420,185828,67266,36.20
31,Link,MP,2-5km,126292,54805,889875,125359,14.09
32,Link,MP,5-8km,115311,51364,496804,101257,20.38
33,Link,MP,8-12km,94360,44109,289202,78263,27.06
34,Link,MP,below 2km,89345,20391,276062,29859,10.82
35,Link,UHP,12+ km,7663,4228,35845,12413,34.63
36,Link,UHP,2-5km,11680,6526,392294,49798,12.69
37,Link,UHP,5-8km,11438,6235,167092,30752,18.40
38,Link,UHP,8-12km,10073,5374,76414,19079,24.97
39,Link,UHP,below 2km,11210,4643,137733,13942,10.12
40,Link,ZP,12+ km,1,0,1,0,0.00
41,Link,ZP,2-5km,1,1,1,1,100.00
42,Link,ZP,8-12km,1,1,1,1,100.00

Auto
- MP/LP > HP > UHP


Link 
- MP/LP > HP > UHP

In [43]:
## Taxi

df_agg2 = df_rating_segment \
                            .groupby(['service_name_x', 'rounded_avgcaptainrating']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg2['date_range'] = start_date1 + ' to -' + end_date1
df_agg2['routeDiff_orders %'] = df_agg2['routeDiff_orders']*100.0/df_agg2['total_net_orders']
df_agg2['routeDiff_captain %'] = df_agg2['routeDiff_captains']*100.0/df_agg2['total_net_captains']
df_agg2 = df_agg2[['service_name_x', 'rounded_avgcaptainrating',
                 'total_net_captains', 'routeDiff_captains', ##'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
print(start_date1, end_date1)
df_agg2.round(2)

20231016 20231022

,service_name_x,rounded_avgcaptainrating,total_net_captains,routeDiff_captains,total_net_orders,routeDiff_orders,routeDiff_orders %
0,Auto,3.9,5910,3903,38090,11357,29.82
1,Auto,4.3,30770,22494,296781,82154,27.68
2,Auto,4.5,108026,79347,1434321,333723,23.27
3,Auto,4.7,57745,39363,910882,145298,15.95
4,Auto,5.0,10707,6102,108708,15289,14.06
5,Link,3.9,5277,1963,35656,5248,14.72
6,Link,4.3,37727,16555,434805,67109,15.43
7,Link,4.5,101954,54288,1712197,305639,17.85
8,Link,4.7,128680,71948,2361301,439280,18.60
9,Link,4.9,33043,15969,414661,69506,16.76
10,Link,5.0,12615,4747,60979,10110,16.58

Auto
- Below 4 > Middle > Above 4.3

Link
- Below 4 < Middle < Above 4.3

In [44]:
## Taxi

df_agg2 = df_rating_segment \
                            .groupby(['service_name_x', 'rounded_avgcaptainrating', 'performance']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg2['date_range'] = start_date1 + ' to -' + end_date1
df_agg2['routeDiff_orders %'] = df_agg2['routeDiff_orders']*100.0/df_agg2['total_net_orders']
df_agg2['routeDiff_captain %'] = df_agg2['routeDiff_captains']*100.0/df_agg2['total_net_captains']
df_agg2 = df_agg2[['service_name_x', 'rounded_avgcaptainrating', 'performance',
                 'total_net_captains', 'routeDiff_captains', ##'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]
print(start_date1, end_date1)
df_agg2[df_agg2['total_net_captains'] > 1].round(2)

20231016 20231022

,service_name_x,rounded_avgcaptainrating,performance,total_net_captains,routeDiff_captains,total_net_orders,routeDiff_orders,routeDiff_orders %
0,Auto,3.9,HP,61,59,2366,613,25.91
1,Auto,3.9,LP,4411,2608,17541,5397,30.77
2,Auto,3.9,MP,1437,1235,18168,5342,29.40
4,Auto,4.3,HP,858,840,37522,9534,25.41
5,Auto,4.3,LP,19609,12560,96511,27848,28.85
6,Auto,4.3,MP,10263,9055,159207,44216,27.77
7,Auto,4.3,UHP,40,39,3541,556,15.70
8,Auto,4.5,HP,7425,7106,356492,77772,21.82
9,Auto,4.5,LP,60109,36954,313235,78663,25.11
10,Auto,4.5,MP,39623,34457,680464,164646,24.20
11,Auto,4.5,UHP,869,830,84130,12642,15.03
12,Auto,4.7,HP,5146,4650,246316,37527,15.24
13,Auto,4.7,LP,31011,17183,151976,32914,21.66
14,Auto,4.7,MP,19809,15899,315746,61625,19.52
15,Auto,4.7,UHP,1779,1631,196844,13232,6.72
16,Auto,5.0,HP,409,357,17371,2112,12.16
17,Auto,5.0,LP,7141,3420,24603,5601,22.77
18,Auto,5.0,MP,2878,2067,31881,5802,18.20
19,Auto,5.0,UHP,279,258,34853,1774,5.09
20,Link,3.9,HP,245,125,5135,626,12.19
21,Link,3.9,LP,3237,925,12949,1790,13.82
22,Link,3.9,MP,1754,895,15788,2642,16.73
23,Link,3.9,UHP,41,18,1784,190,10.65
24,Link,4.3,HP,2714,1600,88045,13638,15.49
25,Link,4.3,LP,19354,6383,102869,15365,14.94
26,Link,4.3,MP,14992,8314,208559,34613,16.60
27,Link,4.3,UHP,666,257,35331,3492,9.88
29,Link,4.5,HP,12093,8078,471300,82810,17.57
30,Link,4.5,LP,41718,16567,252405,45599,18.07
31,Link,4.5,MP,44336,27503,727159,137509,18.91
32,Link,4.5,UHP,3806,2139,261332,39720,15.20
34,Link,4.7,HP,16593,11342,650624,116113,17.85
35,Link,4.7,LP,48296,20506,288668,59275,20.53
36,Link,4.7,MP,57386,36094,956319,187184,19.57
37,Link,4.7,UHP,6405,4006,465690,76708,16.47
38,Link,4.9,HP,3144,1854,101129,15429,15.26
39,Link,4.9,LP,14214,5419,71789,13711,19.10
40,Link,4.9,MP,14930,8301,198460,34573,17.42
41,Link,4.9,UHP,754,395,43282,5793,13.38
43,Link,5.0,HP,481,244,7212,881,12.22
44,Link,5.0,LP,7414,2199,20322,3665,18.03
45,Link,5.0,MP,4631,2284,31486,5483,17.41
46,Link,5.0,UHP,89,20,1959,81,4.13

Auto

- Below 4
    - MP/LP -> 30%
    - HP -> 25%
   
- Middle 
    - MP/HP -> 28
    - HP -> 25%
    
- Above 4.3
    - MP/LP -> ~23.5%
    - HP -> 18%
    
Link

- Below 4
    - MP -> 16.7%
    - LP -> 13.8%
    - HP -> 12%
   
- Middle 
    - MP -> 16%
    - LP -> 14.5%
    - HP -> 15%
    
- Above 4.3
    - MP -> 18%
    - LP -> 19%
    - HP -> 17%

In [48]:
## Taxi

df_agg2 = df_rating_segment \
                            .groupby(['service_name_x', 'performance', 'rounded_avgcaptainrating', 'rounded_last_mile']) \
                            .agg(total_net_orders = pd.NamedAgg('order_id', 'nunique'),
                                 total_net_captains = pd.NamedAgg('captain_id', 'nunique'),
                                 routeDiff_orders = ('order_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique()),
                                 routeDiff_captains = ('captain_id', 
                                                     lambda x: x[(df_rating_segment['orderdate'].notna())
                                                                 &
                                                                 (df_rating_segment['orderdate'] != '')
                                                             ] \
                                                  .nunique())
                                ) \
                            .reset_index()

df_agg2['date_range'] = start_date1 + ' to -' + end_date1
df_agg2['routeDiff_orders %'] = df_agg2['routeDiff_orders']*100.0/df_agg2['total_net_orders']
df_agg2['routeDiff_captain %'] = df_agg2['routeDiff_captains']*100.0/df_agg2['total_net_captains']
df_agg2 = df_agg2[['service_name_x', 'performance', 'rounded_avgcaptainrating', 'rounded_last_mile',
                 'total_net_captains', 'routeDiff_captains', ##'routeDiff_captain %',
                 'total_net_orders', 'routeDiff_orders', 'routeDiff_orders %'
                ]]

df_agg2.rename(columns = {'rounded_avgcaptainrating' : 'captainrating', 
                          'rounded_last_mile' : 'last_mile',
                          'service_name_x' : 'service_name'
                         }, inplace = True)


print(start_date1, end_date1)
df_agg2 = df_agg2[df_agg2['total_net_captains'] > 1].round(2)
df_agg2

20231016 20231022

,service_name,performance,captainrating,last_mile,total_net_captains,routeDiff_captains,total_net_orders,routeDiff_orders,routeDiff_orders %
0,Auto,HP,3.9,12+ km,52,44,405,167,41.23
1,Auto,HP,3.9,2-5km,56,40,708,122,17.23
2,Auto,HP,3.9,5-8km,59,49,566,157,27.74
3,Auto,HP,3.9,8-12km,59,50,439,140,31.89
4,Auto,HP,3.9,below 2km,44,18,248,27,10.89
5,Auto,HP,4.3,12+ km,713,598,5924,2559,43.20
6,Auto,HP,4.3,2-5km,829,631,11550,1863,16.13
7,Auto,HP,4.3,5-8km,841,711,9003,2288,25.41
8,Auto,HP,4.3,8-12km,805,686,7092,2407,33.94
9,Auto,HP,4.3,below 2km,666,254,3953,417,10.55
10,Auto,HP,4.5,12+ km,5791,4669,40470,15830,39.12
11,Auto,HP,4.5,2-5km,7195,5738,129195,19789,15.32
12,Auto,HP,4.5,5-8km,7164,5989,83968,19851,23.64
13,Auto,HP,4.5,8-12km,6725,5473,57086,18079,31.67
14,Auto,HP,4.5,below 2km,6180,2555,45773,4223,9.23
15,Auto,HP,4.7,12+ km,3321,2247,16731,5963,35.64
16,Auto,HP,4.7,2-5km,5002,3678,107984,12085,11.19
17,Auto,HP,4.7,5-8km,4867,3524,52039,9809,18.85
18,Auto,HP,4.7,8-12km,4242,2895,28496,7574,26.58
19,Auto,HP,4.7,below 2km,4488,1262,41066,2096,5.10
20,Auto,HP,5.0,12+ km,198,114,713,210,29.45
21,Auto,HP,5.0,2-5km,394,281,8208,839,10.22
22,Auto,HP,5.0,5-8km,359,239,2996,567,18.93
23,Auto,HP,5.0,8-12km,284,162,1297,304,23.44
24,Auto,HP,5.0,below 2km,362,107,4157,192,4.62
25,Auto,LP,3.9,12+ km,1854,1137,4187,1833,43.78
26,Auto,LP,3.9,2-5km,2225,760,4475,955,21.34
27,Auto,LP,3.9,5-8km,2322,921,4195,1169,27.87
28,Auto,LP,3.9,8-12km,2040,958,3563,1254,35.20
29,Auto,LP,3.9,below 2km,790,168,1121,186,16.59
30,Auto,LP,4.3,12+ km,9685,6000,26666,10513,39.42
31,Auto,LP,4.3,2-5km,10319,3310,22134,4091,18.48
32,Auto,LP,4.3,5-8km,11380,4585,22241,5782,26.00
33,Auto,LP,4.3,8-12km,10335,5045,20239,6710,33.15
34,Auto,LP,4.3,below 2km,3617,700,5231,752,14.38
35,Auto,LP,4.5,12+ km,32273,18565,86495,31013,35.86
36,Auto,LP,4.5,2-5km,31919,9125,70854,10966,15.48
37,Auto,LP,4.5,5-8km,35275,12637,71585,15752,22.00
38,Auto,LP,4.5,8-12km,33556,14659,67660,19175,28.34
39,Auto,LP,4.5,below 2km,11099,1652,16641,1757,10.56
40,Auto,LP,4.7,12+ km,16001,8284,39264,12748,32.47
41,Auto,LP,4.7,2-5km,16809,4189,37028,4949,13.37
42,Auto,LP,4.7,5-8km,18024,5535,35599,6683,18.77
43,Auto,LP,4.7,8-12km,16414,6212,31572,7832,24.81
44,Auto,LP,4.7,below 2km,5720,671,8513,702,8.25
45,Auto,LP,5.0,12+ km,2616,1284,4970,1783,35.88
46,Auto,LP,5.0,2-5km,3813,925,7256,1064,14.66
47,Auto,LP,5.0,5-8km,3634,1116,6112,1298,21.24
48,Auto,LP,5.0,8-12km,2946,1118,4668,1296,27.76
49,Auto,LP,5.0,below 2km,1161,152,1597,160,10.02
50,Auto,MP,3.9,12+ km,802,594,3380,1457,43.11
51,Auto,MP,3.9,2-5km,1174,650,5502,1138,20.68
52,Auto,MP,3.9,5-8km,1182,712,4353,1255,28.83
53,Auto,MP,3.9,8-12km,1003,659,3408,1268,37.21
54,Auto,MP,3.9,below 2km,707,187,1525,224,14.69
55,Auto,MP,4.3,12+ km,6480,4942,33117,13688,41.33
56,Auto,MP,4.3,2-5km,8491,4541,44537,8131,18.26
57,Auto,MP,4.3,5-8km,8841,5520,37830,10176,26.90
58,Auto,MP,4.3,8-12km,7985,5483,31861,10805,33.91
59,Auto,MP,4.3,below 2km,4730,1175,11862,1416,11.94
60,Auto,MP,4.5,12+ km,25064,18206,121074,47033,38.85
61,Auto,MP,4.5,2-5km,34168,18158,210499,33343,15.84
62,Auto,MP,4.5,5-8km,34412,20701,162480,38895,23.94
63,Auto,MP,4.5,8-12km,30743,20087,127557,39668,31.10
64,Auto,MP,4.5,below 2km,20324,4672,58854,5707,9.70
65,Auto,MP,4.7,12+ km,11462,7186,43810,15208,34.71
66,Auto,MP,4.7,2-5km,17392,8286,111582,14642,13.12
67,Auto,MP,4.7,5-8km,16859,8981,74963,15429,20.58
68,Auto,MP,4.7,8-12km,14358,8082,52543,14112,26.86
69,Auto,MP,4.7,below 2km,10610,1881,32848,2234,6.80
70,Auto,MP,5.0,12+ km,1194,690,3175,1140,35.91
71,Auto,MP,5.0,2-5km,2452,1080,13032,1701,13.05
72,Auto,MP,5.0,5-8km,2177,982,7223,1481,20.50
73,Auto,MP,5.0,8-12km,1651,819,4396,1215,27.64
74,Auto,MP,5.0,below 2km,1410,226,4055,265,6.54
79,Auto,UHP,4.3,12+ km,26,18,89,37,41.57
80,Auto,UHP,4.3,2-5km,40,37,1670,235,14.07
81,Auto,UHP,4.3,5-8km,39,34,534,135,25.28
82,Auto,UHP,4.3,8-12km,34,22,264,80,30.30
83,Auto,UHP,4.3,below 2km,40,22,984,69,7.01
84,Auto,UHP,4.5,12+ km,467,326,2123,798,37.59
85,Auto,UHP,4.5,2-5km,858,786,41614,5428,13.04
86,Auto,UHP,4.5,5-8km,840,723,13371,3084,23.06
87,Auto,UHP,4.5,8-12km,701,525,5422,1609,29.68
88,Auto,UHP,4.5,below 2km,837,535,21600,1723,7.98
89,Auto,UHP,4.7,12+ km,716,378,2293,738,32.18
90,Auto,UHP,4.7,2-5km,1763,1479,102356,6519,6.37
91,Auto,UHP,4.7,5-8km,1642,1086,20145,3086,15.32
92,Auto,UHP,4.7,8-12km,1190,613,5908,1355,22.94
93,Auto,UHP,4.7,below 2km,1735,637,66142,1534,2.32
94,Auto,UHP,5.0,12+ km,65,28,128,45,35.16
95,Auto,UHP,5.0,2-5km,276,244,16059,943,5.87
96,Auto,UHP,5.0,5-8km,235,145,2357,325,13.79
97,Auto,UHP,5.0,8-12km,136,51,461,95,20.61
98,Auto,UHP,5.0,below 2km,270,127,15848,366,2.31
99,Link,HP,3.9,12+ km,121,54,300,100,33.33
100,Link,HP,3.9,2-5km,238,88,2325,188,8.09
101,Link,HP,3.9,5-8km,229,80,1264,167,13.21
102,Link,HP,3.9,8-12km,180,66,593,125,21.08
103,Link,HP,3.9,below 2km,182,32,653,46,7.04
104,Link,HP,4.3,12+ km,1682,922,5754,2116,36.77
105,Link,HP,4.3,2-5km,2656,1328,38829,4280,11.02
106,Link,HP,4.3,5-8km,2545,1219,19973,3481,17.43
107,Link,HP,4.3,8-12km,2210,1112,10737,2783,25.92
108,Link,HP,4.3,below 2km,2325,598,12752,978,7.67
109,Link,HP,4.5,12+ km,8067,4886,30718,11533,37.54
110,Link,HP,4.5,2-5km,11897,7007,207544,27587,13.29
111,Link,HP,4.5,5-8km,11502,6661,105800,21032,19.88
112,Link,HP,4.5,8-12km,10392,5955,56145,15643,27.86
113,Link,HP,4.5,below 2km,10737,3640,71093,7015,9.87
114,Link,HP,4.7,12+ km,11012,6638,44401,16013,36.06
115,Link,HP,4.7,2-5km,16339,9936,291143,40395,13.87
116,Link,HP,4.7,5-8km,15769,9283,143990,29013,20.15
117,Link,HP,4.7,8-12km,14161,8126,77326,21076,27.26
118,Link,HP,4.7,below 2km,14723,5076,93764,9616,10.26
119,Link,HP,4.9,12+ km,1898,975,6392,2097,32.81
120,Link,HP,4.9,2-5km,3093,1555,46758,5565,11.90
121,Link,HP,4.9,5-8km,2940,1447,22353,3879,17.35
122,Link,HP,4.9,8-12km,2529,1193,11100,2678,24.13
123,Link,HP,4.9,below 2km,2687,700,14526,1210,8.33
124,Link,HP,5.0,12+ km,225,94,469,139,29.64
125,Link,HP,5.0,2-5km,469,164,3821,292,7.64
126,Link,HP,5.0,5-8km,411,131,1339,221,16.50
127,Link,HP,5.0,8-12km,325,114,767,171,22.29
128,Link,HP,5.0,below 2km,351,47,816,58,7.11
129,Link,LP,3.9,12+ km,805,268,1315,328,24.94
130,Link,LP,3.9,2-5km,2140,396,5117,538,10.51
131,Link,LP,3.9,5-8km,1611,348,2989,432,14.45
132,Link,LP,3.9,8-12km,1086,277,1829,353,19.30
133,Link,LP,3.9,below 2km,1041,122,1699,139,8.18
134,Link,LP,4.3,12+ km,5213,1901,9289,2564,27.60
135,Link,LP,4.3,2-5km,13568,2909,40811,4449,10.90
136,Link,LP,4.3,5-8km,11083,2754,24564,3878,15.79
137,Link,LP,4.3,8-12km,8024,2346,14896,3193,21.44
138,Link,LP,4.3,below 2km,7160,943,13309,1281,9.63
139,Link,LP,4.5,12+ km,13030,5412,24470,7754,31.69
140,Link,LP,4.5,2-5km,30168,8070,99358,13794,13.88
141,Link,LP,4.5,5-8km,25389,7527,59491,11346,19.07
142,Link,LP,4.5,8-12km,18842,6437,36688,9108,24.83
143,Link,LP,4.5,below 2km,16362,2735,32398,3597,11.10
144,Link,LP,4.7,12+ km,15315,6705,29411,9910,33.69
145,Link,LP,4.7,2-5km,34534,10186,113738,18514,16.28
146,Link,LP,4.7,5-8km,28746,9444,66994,14678,21.91
147,Link,LP,4.7,8-12km,21683,7909,42613,11510,27.01
148,Link,LP,4.7,below 2km,18234,3481,35912,4663,12.98
149,Link,LP,4.9,12+ km,3747,1501,6272,2023,32.25
150,Link,LP,4.9,2-5km,10001,2729,29750,4532,15.23
151,Link,LP,4.9,5-8km,7989,2378,16579,3443,20.77
152,Link,LP,4.9,8-12km,5649,1904,9762,2586,26.49
153,Link,LP,4.9,below 2km,5198,880,9426,1127,11.96
154,Link,LP,5.0,12+ km,1333,485,1791,567,31.66
155,Link,LP,5.0,2-5km,4583,940,8430,1193,14.15
156,Link,LP,5.0,5-8km,3074,775,4542,918,20.21
157,Link,LP,5.0,8-12km,1964,593,2662,672,25.24
158,Link,LP,5.0,below 2km,2137,291,2897,315,10.87
159,Link,MP,3.9,12+ km,733,347,1449,504,34.78
160,Link,MP,3.9,2-5km,1506,468,6423,747,11.63
161,Link,MP,3.9,5-8km,1278,438,3682,665,18.06
162,Link,MP,3.9,8-12km,990,364,2183,521,23.87
163,Link,MP,3.9,below 2km,920,157,2051,205,10.00
164,Link,MP,4.3,12+ km,7163,3549,17708,6139,34.67
165,Link,MP,4.3,2-5km,13599,5130,85675,10017,11.69
166,Link,MP,4.3,5-8km,12322,4840,49216,8762,17.80
167,Link,MP,4.3,8-12km,9915,4212,28879,7115,24.64
168,Link,MP,4.3,below 2km,9322,1734,27081,2580,9.53
169,Link,MP,4.5,12+ km,23178,12742,62667,23193,37.01
170,Link,MP,4.5,2-5km,40776,18324,300018,42199,14.07
171,Link,MP,4.5,5-8km,37661,17235,169553,34410,20.29
172,Link,MP,4.5,8-12km,31241,15055,99106,27335,27.58
173,Link,MP,4.5,below 2km,29460,7021,95815,10372,10.83
174,Link,MP,4.7,12+ km,30256,16587,84701,30756,36.31
175,Link,MP,4.7,2-5km,52823,24499,398996,59602,14.94
176,Link,MP,4.7,5-8km,48690,22949,221741,47144,21.26
177,Link,MP,4.7,8-12km,40376,19624,129461,35741,27.61
178,Link,MP,4.7,below 2km,38019,9409,121420,13941,11.48
179,Link,MP,4.9,12+ km,7097,3470,16679,5728,34.34
180,Link,MP,4.9,2-5km,13595,5212,84895,11040,13.00
181,Link,MP,4.9,5-8km,12220,4893,45689,8865,19.40
182,Link,MP,4.9,8-12km,9600,4045,25676,6520,25.39
183,Link,MP,4.9,below 2km,9342,1772,25521,2420,9.48
184,Link,MP,5.0,12+ km,1604,725,2624,946,36.05
185,Link,MP,5.0,2-5km,3993,1172,13868,1754,12.65
186,Link,MP,5.0,5-8km,3140,1009,6923,1411,20.38
187,Link,MP,5.0,8-12km,2238,809,3897,1031,26.46
188,Link,MP,5.0,below 2km,2282,298,4174,341,8.17
189,Link,UHP,3.9,12+ km,19,5,34,8,23.53
190,Link,UHP,3.9,2-5km,41,15,1158,87,7.51
191,Link,UHP,3.9,5-8km,39,13,301,47,15.61
192,Link,UHP,3.9,8-12km,34,8,126,22,17.46
193,Link,UHP,3.9,below 2km,32,10,165,26,15.76
194,Link,UHP,4.3,12+ km,384,153,1482,417,28.14
195,Link,UHP,4.3,2-5km,662,228,17025,1201,7.05
196,Link,UHP,4.3,5-8km,644,226,7923,898,11.33
197,Link,UHP,4.3,8-12km,535,194,3636,632,17.38
198,Link,UHP,4.3,below 2km,616,149,5265,344,6.53
199,Link,UHP,4.5,12+ km,2544,1413,12173,4283,35.18
200,Link,UHP,4.5,2-5km,3780,2047,123373,14980,12.14
201,Link,UHP,4.5,5-8km,3709,1975,54846,9813,17.89
202,Link,UHP,4.5,8-12km,3294,1717,26087,6365,24.40
203,Link,UHP,4.5,below 2km,3646,1482,44853,4279,9.54
204,Link,UHP,4.7,12+ km,4258,2454,20563,7184,34.94
205,Link,UHP,4.7,2-5km,6361,3848,227332,30965,13.62
206,Link,UHP,4.7,5-8km,6255,3671,95578,18670,19.53
207,Link,UHP,4.7,8-12km,5541,3176,42927,11267,26.25
208,Link,UHP,4.7,below 2km,6142,2768,79290,8622,10.87
209,Link,UHP,4.9,12+ km,426,196,1535,508,33.09
210,Link,UHP,4.9,2-5km,747,372,22170,2536,11.44
211,Link,UHP,4.9,5-8km,716,334,8104,1300,16.04
212,Link,UHP,4.9,8-12km,620,272,3505,781,22.28
213,Link,UHP,4.9,below 2km,713,231,7968,668,8.38
214,Link,UHP,5.0,12+ km,32,7,58,13,22.41
215,Link,UHP,5.0,2-5km,89,16,1236,29,2.35
216,Link,UHP,5.0,5-8km,75,16,340,24,7.06
217,Link,UHP,5.0,8-12km,49,7,133,12,9.02
218,Link,UHP,5.0,below 2km,61,3,192,3,1.56

In [51]:
df_agg2.to_clipboard(index=False)