<div class="alert alert-block alert-info">

## Imports & Connection
</div>

In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from IPython.display import display
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [4]:
print('Notebook dir - ', os.getcwd())
local_extract = '/Users/E2074/local-datasets/customer/fare-shock/policy_change'
print('Data dir - ', local_extract)

Notebook dir -  /Users/E2074/analytics/customer/fare-shock/policy_change
Data dir -  /Users/E2074/local-datasets/customer/fare-shock/policy_change

<div class="alert alert-block alert-info">
    
## Datasets & Parameter
</div>

In [5]:
## Parameter 
sep_start_date = '20240901'
sep_end_date = '20240929'
retention_start_date = '20240930'
retention_end_date = '20241110'

In [6]:
sdid_query = f"""
    SELECT 
        service.city_display_name AS city,
        service.service_level_l2 AS service_level_l2,
        service_level,
        service.service_detail_id AS service_detail_id
    FROM
        datasets.service_level_mapping_qc AS service
    WHERE 
        city_display_name IN ('bangalore', 'delhi')
        AND service_category in ('auto', 'cab')
        AND service_level_l2 in ('auto', 'cabeconomy')
        AND service_detail_id_isActive = true
    ORDER BY 1,2,3
    """
df_sdid = pd.read_sql(sdid_query, connection)

In [7]:
df_sdid

        city service_level_l2 service_level         service_detail_id
0  bangalore             auto          auto  5c53562fceb6fc9241980547
1  bangalore             auto      cityauto  634c544443b7adfc2c5a4300
2  bangalore       cabeconomy    cabeconomy  6516a74cb0ef8abf16cec40d
3      delhi             auto          auto  5fc8c40bf4f0a70007d7cfbc
4      delhi             auto      auto ncr  64d22fba29b334580f1e3a18
5      delhi       cabeconomy    cabeconomy  648aaa1b4cf8d978be7ac5f6

In [8]:
sdid_list = df_sdid['service_detail_id'].tolist()
sdid_list

['5c53562fceb6fc9241980547',
 '634c544443b7adfc2c5a4300',
 '6516a74cb0ef8abf16cec40d',
 '5fc8c40bf4f0a70007d7cfbc',
 '64d22fba29b334580f1e3a18',
 '648aaa1b4cf8d978be7ac5f6']

<div class="alert alert-block alert-info">
    
### Data
</div>

In [51]:
def domain_fare_estimates_function(sep_start_date, sep_end_date, sdid_list, local_extract):

    df = pd.DataFrame()
    
    for sdid in sdid_list:
        
        base_query = f"""
        
        WITH domain_fare_estimates AS (
            SELECT
                yyyymmdd,
                customer_id,
                JSON_EXTRACT_SCALAR(service_obj, '$.estimates[0].serviceDetailId') servicedetailid,
                id,
                initial_estimated_fare,
                recalculated_fare,
                (recalculated_fare - initial_estimated_fare) difference,
                final_fare,
                -- recalculation_reason,
                -- fare_recalculated,
                -- recalculated_fare_used,
                data_set
            FROM
                iceberg.pricing.domain_fare_estimates_v3_immutable
            WHERE 
                yyyymmdd >= '{sep_start_date}'
                AND yyyymmdd <= '{sep_end_date}'
                AND recalculation_reason = 'routeDiff'
                AND fare_recalculated = 'true' 
                AND recalculated_fare_used = false
                AND JSON_EXTRACT_SCALAR(service_obj, '$.estimates[0].serviceDetailId') = '{sdid}'
            ),
            
            base AS (
            SELECT
                *
            FROM 
                domain_fare_estimates
            WHERE 
                difference < 0
            ),
            
            orders AS (
            SELECT 
                yyyymmdd,
                service_detail_id,
                customer_id,
                order_id,
                u.id_array as fare_estimate_id
            FROM 
                ( 
                SELECT 
                    yyyymmdd,
                    city_name,
                    service_obj_service_name service_name,
                    service_detail_id,
                    customer_id,
                    order_id,
                    fare_recalculated_reason,
                    case 
                        when fare_recalculated_type is null then 0 
                        when fare_recalculated_type = 'decrease' then fare_recalculated_diff_amount*-1
                        else fare_recalculated_diff_amount 
                    end fare_recalculated_diff_amount,
                    COALESCE(fare_recalculated_type, 'same') fare_recalculated_type,
                    amount,
                    estimate_id,
                    CAST(JSON_PARSE(estimate_ids) as ARRAY<VARCHAR>) AS id_array
                FROM 
                    orders.order_logs_snapshot ols  
                    
                WHERE 
                    yyyymmdd >= '{sep_start_date}'
                    AND yyyymmdd <= '{sep_end_date}'
                    AND order_status = 'dropped'
                    AND service_detail_id = '{sdid}'
                ) 
                AS t
                CROSS JOIN UNNEST(t.id_array) AS u(id_array)
            )
            
            
            SELECT 
                a.*,
                order_id
            FROM 
                base a
            LEFT JOIN 
                orders b
                ON a.yyyymmdd = b.yyyymmdd
                AND a.servicedetailid = b.service_detail_id
                AND a.customer_id = b.customer_id
                AND id = fare_estimate_id
        """
        
        df_base = pd.read_sql(base_query, connection)
        df = pd.concat([df, df_base], ignore_index=True)
        print('Data fetched successfully for sdid - ', sdid)
        df.to_parquet(local_extract + '/domain_fare_estimates.parquet', index=False)
        
    print('Data fetched successfully')
    
    return df

domain_fare_estimates_function(sep_start_date, sep_end_date, sdid_list, local_extract)

Data fetched successfully for sdid -  5c53562fceb6fc9241980547
Data fetched successfully for sdid -  634c544443b7adfc2c5a4300
Data fetched successfully for sdid -  6516a74cb0ef8abf16cec40d
Data fetched successfully for sdid -  5fc8c40bf4f0a70007d7cfbc
Data fetched successfully for sdid -  64d22fba29b334580f1e3a18
Data fetched successfully for sdid -  648aaa1b4cf8d978be7ac5f6
Data fetched successfully

,yyyymmdd,customer_id,servicedetailid,id,initial_estimated_fare,recalculated_fare,difference,final_fare,data_set,order_id
0,20240929,5dde36e3ee2b89270c78edf1,5c53562fceb6fc9241980547,66f9127432c5b8cfdb74058e,152,133,-19,152,"{""finalFare"":152,""finalLocationProvider"":""hF"",...",66f912881f7d80644bcf44d2
1,20240929,6469b79d161d3224dbe08ab3,5c53562fceb6fc9241980547,66f95efb2f8c41d35b987036,89,40,-49,89,"{""finalFare"":89,""finalLocationProvider"":""hF"",""...",66f95f5139608d3aeeb82c1d
2,20240929,65742a54cbd5973c356ea122,5c53562fceb6fc9241980547,66f902c844f1f5671712bcde,394,362,-32,394,"{""finalFare"":394,""finalLocationProvider"":""hF"",...",66f902e15fdbef0ebe877d79
3,20240929,6520be9f0d20f17162978501,5c53562fceb6fc9241980547,66f99187f133480c0f50b417,56,55,-1,56,"{""finalFare"":56,""finalLocationProvider"":""hF"",""...",66f991b1fb942e6ccde6d8c7
4,20240929,63d216ba3442951fe3181ba5,5c53562fceb6fc9241980547,66f9622ae4f811c01c22dd91,180,162,-18,181,"{""finalFare"":181,""finalLocationProvider"":""hF"",...",66f9623e39608d3aeeb833af
...,...,...,...,...,...,...,...,...,...,...
2264192,20240901,6631fa1f8a1f8d0b991be09c,648aaa1b4cf8d978be7ac5f6,66d45123f1f45291eb4c105f,243,57,-186,243,"{""finalFare"":243,""finalLocationProvider"":""Goog...",66d45123fac7540c582d8889
2264193,20240901,6468c3269cddd63aa3efddc0,648aaa1b4cf8d978be7ac5f6,66d452301dab827e1d5658c8,167,148,-19,167,"{""finalFare"":167,""finalLocationProvider"":""hF"",...",66d4523aae80b22dcb8529dc
2264194,20240901,61682af23cf262d59619a300,648aaa1b4cf8d978be7ac5f6,66d456effc366abb8f79afb7,236,215,-21,236,"{""finalFare"":236,""finalLocationProvider"":""hF"",...",66d4570b5eb53c1b3a76ca2d
2264195,20240901,658ad3d4124d6b349d064207,648aaa1b4cf8d978be7ac5f6,66d4598a744357352171231d,147,134,-13,147,"{""finalFare"":147,""finalLocationProvider"":""Goog...",66d4599ebc576064d6a45762
2264196,20240901,63836bdce344c010f448b520,648aaa1b4cf8d978be7ac5f6,66d452c3f1a18e1403a7b05c,490,485,-5,495,"{""finalFare"":495,""finalLocationProvider"":""hF"",...",66d452d7ae80b22dcb852c13

In [9]:
df_domain_fare_estimates = pd.read_parquet(local_extract + '/domain_fare_estimates.parquet')

In [10]:
df_domain_fare_estimates.shape

(2264197, 10)

In [11]:
df_domain_fare_estimates.head()

,yyyymmdd,customer_id,servicedetailid,id,initial_estimated_fare,recalculated_fare,difference,final_fare,data_set,order_id
0,20240929,5dde36e3ee2b89270c78edf1,5c53562fceb6fc9241980547,66f9127432c5b8cfdb74058e,152,133,-19,152,"{""finalFare"":152,""finalLocationProvider"":""hF"",...",66f912881f7d80644bcf44d2
1,20240929,6469b79d161d3224dbe08ab3,5c53562fceb6fc9241980547,66f95efb2f8c41d35b987036,89,40,-49,89,"{""finalFare"":89,""finalLocationProvider"":""hF"",""...",66f95f5139608d3aeeb82c1d
2,20240929,65742a54cbd5973c356ea122,5c53562fceb6fc9241980547,66f902c844f1f5671712bcde,394,362,-32,394,"{""finalFare"":394,""finalLocationProvider"":""hF"",...",66f902e15fdbef0ebe877d79
3,20240929,6520be9f0d20f17162978501,5c53562fceb6fc9241980547,66f99187f133480c0f50b417,56,55,-1,56,"{""finalFare"":56,""finalLocationProvider"":""hF"",""...",66f991b1fb942e6ccde6d8c7
4,20240929,63d216ba3442951fe3181ba5,5c53562fceb6fc9241980547,66f9622ae4f811c01c22dd91,180,162,-18,181,"{""finalFare"":181,""finalLocationProvider"":""hF"",...",66f9623e39608d3aeeb833af

In [12]:
df_domain_fare_estimates.servicedetailid.unique()

array(['5c53562fceb6fc9241980547', '6516a74cb0ef8abf16cec40d',
       '5fc8c40bf4f0a70007d7cfbc', '64d22fba29b334580f1e3a18',
       '648aaa1b4cf8d978be7ac5f6'], dtype=object)

In [13]:
def customer_order_query_function(sep_start_date, sep_end_date, sdid_list, local_extract):

    df = pd.DataFrame()
    
    for sdid in sdid_list:
        
        base_query = f"""
        
        WITH customer_orders AS (    
        
            -- SELECT 
            --     *,
            --     u.id_array as fare_estimate_id
            -- FROM 
                ( 
                SELECT 
                    yyyymmdd,
                    city_name,
                    service_obj_service_name service_name,
                    service_detail_id,
                    customer_id,
                    order_id,
                    fare_recalculated_reason,
                    case 
                        when fare_recalculated_type is null then 0 
                        when fare_recalculated_type = 'decrease' then fare_recalculated_diff_amount*-1
                        else fare_recalculated_diff_amount 
                    end fare_recalculated_diff_amount,
                    COALESCE(fare_recalculated_type, 'same') fare_recalculated_type,
                    amount,
                    estimate_id,
                    CAST(JSON_PARSE(estimate_ids) as ARRAY<VARCHAR>) AS id_array
                FROM 
                    orders.order_logs_snapshot ols  
                    
                WHERE 
                    yyyymmdd >= '{sep_start_date}'
                    AND yyyymmdd <= '{sep_end_date}'
                    AND order_status = 'dropped'
                    AND service_detail_id = '{sdid}'
                ) 
                -- AS t
                -- CROSS JOIN UNNEST(t.id_array) AS u(id_array)
            ),
        
            segment AS (
        
            SELECT 
                customer_id,
                taxi_retention_segments,
                taxi_regularity_segment,
                ps_tag_auto
            FROM 
                datasets.iallocator_customer_segments 
            WHERE 
                run_date = '2024-09-30'
                AND taxi_retention_segments != 'INACTIVE'
            )
            
            SELECT
                yyyymmdd,
                city_name,
                service_name,
                service_detail_id,
                customer_orders.customer_id,
                order_id,
                fare_recalculated_reason,
                fare_recalculated_diff_amount,
                fare_recalculated_type,
                amount,
                estimate_id,
                -- fare_estimate_id,
                coalesce(taxi_retention_segments, 'UNKNOWN') retention_segments,
                coalesce(taxi_regularity_segment, 'UNKNOWN') regularity_segments,
                coalesce(ps_tag_auto, 'UNKNOWN') ps_tag_auto 
            FROM 
                customer_orders
            LEFT JOIN 
                segment
                ON segment.customer_id = customer_orders.customer_id

            """
        df_base = pd.read_sql(base_query, connection)
        df = pd.concat([df, df_base], ignore_index=True)
        print('Data fetched successfully for sdid - ', sdid)
        df.to_parquet(local_extract + '/customer_order.parquet', index=False)
        
    print('Data fetched successfully')
    
    return df

customer_order_query_function(sep_start_date, sep_end_date, sdid_list, local_extract)

Data fetched successfully for sdid -  5c53562fceb6fc9241980547
Data fetched successfully for sdid -  634c544443b7adfc2c5a4300
Data fetched successfully for sdid -  6516a74cb0ef8abf16cec40d
Data fetched successfully for sdid -  5fc8c40bf4f0a70007d7cfbc
Data fetched successfully for sdid -  64d22fba29b334580f1e3a18
Data fetched successfully for sdid -  648aaa1b4cf8d978be7ac5f6
Data fetched successfully

,yyyymmdd,city_name,service_name,service_detail_id,customer_id,order_id,fare_recalculated_reason,fare_recalculated_diff_amount,fare_recalculated_type,amount,estimate_id,retention_segments,regularity_segments,ps_tag_auto
0,20240913,Bangalore,Auto,5c53562fceb6fc9241980547,590b939933c57ee92c8a78ff,66e45101a6e3ce5f2dae7d1d,routeDiff,20,increase,123.0,66e45d498385ce8780b4bb8e,PRIME,WEEKLY,PS
1,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,66f6608111a6ef4e2004e703,None,0,same,310.0,66f660819e62b4674d17534a,PLATINUM,WEEKLY,UNKNOWN
2,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65841eced0269f8c95562d0e,66f663429e2a456423b58932,None,0,same,84.0,66f663002cf293416af76dbb,PLATINUM,WEEKLY,PS
3,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6331a989fcded19b614b061d,66f66bd15834435b3f11ed9f,routeDiff,0,same,56.0,66f66dc4afe48fcf9e119258,ELITE,DAILY,NPS
4,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6226c3e549fea91acf9f5fd0,66f66b539c002a5436eb885b,waitTimeCharges,3,increase,154.0,66f66b4b6f2c69bde5eee47f,ELITE,DAILY,NPS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11417368,20240912,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,6651ff2ad2a3e068db39c31c,66e324c0b392964657a5c3f4,None,0,same,149.0,66e324b7382109700b454f4b,ELITE,DAILY,NPS
11417369,20240916,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,668f6e03c2b70dcddf041ee0,66e7c4a70c18821b7f2d3e1a,None,0,same,206.0,66e7c4964c24fbdd0684118d,ELITE,DAILY,UNKNOWN
11417370,20240921,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,614803ddde864c824601edf9,66eeef5cab99a70aa3c2cf39,None,0,same,566.0,66eeef5ca48342ee499444d7,PLATINUM,WEEKLY,NPS
11417371,20240921,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,65ec66244b593aaea4a09936,66eef29fb39ef0352c4c12ac,dropDiff,0,decrease,302.0,66eef297d8983ee11a7d9b64,ELITE,WEEKLY,NPS
11417372,20240921,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,5de33ba0d472d62e9459e4b9,66eef34574dcd57fd92dc52b,None,0,same,334.0,66eef33694c9aa303d6b06c4,SILVER,RARE_NEED,UNKNOWN

In [14]:
df_customer_order = pd.read_parquet(local_extract + '/customer_order.parquet')

In [15]:
df_customer_order.shape

(11417373, 14)

In [16]:
df_customer_order.head()

,yyyymmdd,city_name,service_name,service_detail_id,customer_id,order_id,fare_recalculated_reason,fare_recalculated_diff_amount,fare_recalculated_type,amount,estimate_id,retention_segments,regularity_segments,ps_tag_auto
0,20240913,Bangalore,Auto,5c53562fceb6fc9241980547,590b939933c57ee92c8a78ff,66e45101a6e3ce5f2dae7d1d,routeDiff,20,increase,123.0,66e45d498385ce8780b4bb8e,PRIME,WEEKLY,PS
1,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,66f6608111a6ef4e2004e703,None,0,same,310.0,66f660819e62b4674d17534a,PLATINUM,WEEKLY,UNKNOWN
2,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65841eced0269f8c95562d0e,66f663429e2a456423b58932,None,0,same,84.0,66f663002cf293416af76dbb,PLATINUM,WEEKLY,PS
3,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6331a989fcded19b614b061d,66f66bd15834435b3f11ed9f,routeDiff,0,same,56.0,66f66dc4afe48fcf9e119258,ELITE,DAILY,NPS
4,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6226c3e549fea91acf9f5fd0,66f66b539c002a5436eb885b,waitTimeCharges,3,increase,154.0,66f66b4b6f2c69bde5eee47f,ELITE,DAILY,NPS

In [17]:
df_customer_order.city_name.unique()

array(['Bangalore', 'Delhi'], dtype=object)

In [47]:
def retension_customer_query_function(retention_start_date, retention_end_date, sdid_list, local_extract):

    df = pd.DataFrame()
    
    for sdid in sdid_list:
        
        base_query = f"""
        
        SELECT 
            DISTINCT
            date_format(date_trunc('week', date_parse(yyyymmdd, '%Y%m%d')), '%Y%m%d') week_start_date,
            city_name,
            service_obj_service_name service_name,
            service_detail_id,
            customer_id
        FROM 
            orders.order_logs_snapshot ols
        WHERE 
            yyyymmdd >= '{retention_start_date}'
            AND yyyymmdd <= '{retention_end_date}'
            AND order_status = 'dropped'
            AND service_detail_id = '{sdid}'

            """
        df_base = pd.read_sql(base_query, connection)
        df = pd.concat([df, df_base], ignore_index=True)
        print('Data fetched successfully for sdid - ', sdid)
        df.to_parquet(local_extract + '/retension_customer.parquet', index=False)
        
    print('Data fetched successfully')
    
    return df

retension_customer_query_function(retention_start_date, retention_end_date, sdid_list, local_extract)

Data fetched successfully for sdid -  5c53562fceb6fc9241980547
Data fetched successfully for sdid -  634c544443b7adfc2c5a4300
Data fetched successfully for sdid -  6516a74cb0ef8abf16cec40d
Data fetched successfully for sdid -  5fc8c40bf4f0a70007d7cfbc
Data fetched successfully for sdid -  64d22fba29b334580f1e3a18
Data fetched successfully for sdid -  648aaa1b4cf8d978be7ac5f6
Data fetched successfully

,week_start_date,city_name,service_name,service_detail_id,customer_id
0,20241104,Bangalore,Auto,5c53562fceb6fc9241980547,636791add58af7606ae3cc89
1,20241028,Bangalore,Auto,5c53562fceb6fc9241980547,669f4349968844374aff8541
2,20240930,Bangalore,Auto,5c53562fceb6fc9241980547,62824533d7dc68b90a756e83
3,20241104,Bangalore,Auto,5c53562fceb6fc9241980547,62a955a25948ea5765054177
4,20241104,Bangalore,Auto,5c53562fceb6fc9241980547,65fa6135a6458534260572e7
...,...,...,...,...,...
9382918,20241007,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,659257857a56fef292cf1017
9382919,20241007,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,6606f403d70f5db2f9a252be
9382920,20241007,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,65baedf9276cb44bc43d90d2
9382921,20241007,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,64c2953e0b4d07aa9f1ad927
9382922,20241007,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,66cdac9765b52800cb3bdf72

In [18]:
df_retension_customer = pd.read_parquet(local_extract + '/retension_customer.parquet')

In [19]:
df_retension_customer.shape

(9382923, 5)

In [20]:
df_customer_order.head()

,yyyymmdd,city_name,service_name,service_detail_id,customer_id,order_id,fare_recalculated_reason,fare_recalculated_diff_amount,fare_recalculated_type,amount,estimate_id,retention_segments,regularity_segments,ps_tag_auto
0,20240913,Bangalore,Auto,5c53562fceb6fc9241980547,590b939933c57ee92c8a78ff,66e45101a6e3ce5f2dae7d1d,routeDiff,20,increase,123.0,66e45d498385ce8780b4bb8e,PRIME,WEEKLY,PS
1,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,66f6608111a6ef4e2004e703,None,0,same,310.0,66f660819e62b4674d17534a,PLATINUM,WEEKLY,UNKNOWN
2,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65841eced0269f8c95562d0e,66f663429e2a456423b58932,None,0,same,84.0,66f663002cf293416af76dbb,PLATINUM,WEEKLY,PS
3,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6331a989fcded19b614b061d,66f66bd15834435b3f11ed9f,routeDiff,0,same,56.0,66f66dc4afe48fcf9e119258,ELITE,DAILY,NPS
4,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6226c3e549fea91acf9f5fd0,66f66b539c002a5436eb885b,waitTimeCharges,3,increase,154.0,66f66b4b6f2c69bde5eee47f,ELITE,DAILY,NPS

In [21]:
df_customer_order.city_name.unique()

array(['Bangalore', 'Delhi'], dtype=object)

<div class="alert alert-block alert-info">
    
## Data Processing
</div>

In [22]:
df_domain_fare_estimates.head()

,yyyymmdd,customer_id,servicedetailid,id,initial_estimated_fare,recalculated_fare,difference,final_fare,data_set,order_id
0,20240929,5dde36e3ee2b89270c78edf1,5c53562fceb6fc9241980547,66f9127432c5b8cfdb74058e,152,133,-19,152,"{""finalFare"":152,""finalLocationProvider"":""hF"",...",66f912881f7d80644bcf44d2
1,20240929,6469b79d161d3224dbe08ab3,5c53562fceb6fc9241980547,66f95efb2f8c41d35b987036,89,40,-49,89,"{""finalFare"":89,""finalLocationProvider"":""hF"",""...",66f95f5139608d3aeeb82c1d
2,20240929,65742a54cbd5973c356ea122,5c53562fceb6fc9241980547,66f902c844f1f5671712bcde,394,362,-32,394,"{""finalFare"":394,""finalLocationProvider"":""hF"",...",66f902e15fdbef0ebe877d79
3,20240929,6520be9f0d20f17162978501,5c53562fceb6fc9241980547,66f99187f133480c0f50b417,56,55,-1,56,"{""finalFare"":56,""finalLocationProvider"":""hF"",""...",66f991b1fb942e6ccde6d8c7
4,20240929,63d216ba3442951fe3181ba5,5c53562fceb6fc9241980547,66f9622ae4f811c01c22dd91,180,162,-18,181,"{""finalFare"":181,""finalLocationProvider"":""hF"",...",66f9623e39608d3aeeb833af

In [23]:
customer_negative_bins = df_domain_fare_estimates[df_domain_fare_estimates['difference'] < 0]\
                            .groupby(['servicedetailid', 'customer_id' ])\
                            .agg(negative_order_bin = ('order_id', 'nunique'))\
                            .reset_index()
customer_negative_bins.head()

            servicedetailid               customer_id  negative_order_bin
0  5c53562fceb6fc9241980547  5737c6d0ddbec2203f73329f                   1
1  5c53562fceb6fc9241980547  5737c6e3ddbec2203f733341                   1
2  5c53562fceb6fc9241980547  5737c6f3ddbec2203f7333d1                   3
3  5c53562fceb6fc9241980547  5737c6f6ddbec2203f7333e9                   1
4  5c53562fceb6fc9241980547  5737c70eddbec2203f7334b8                   2

In [24]:
df_customer_order.head()

,yyyymmdd,city_name,service_name,service_detail_id,customer_id,order_id,fare_recalculated_reason,fare_recalculated_diff_amount,fare_recalculated_type,amount,estimate_id,retention_segments,regularity_segments,ps_tag_auto
0,20240913,Bangalore,Auto,5c53562fceb6fc9241980547,590b939933c57ee92c8a78ff,66e45101a6e3ce5f2dae7d1d,routeDiff,20,increase,123.0,66e45d498385ce8780b4bb8e,PRIME,WEEKLY,PS
1,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,66f6608111a6ef4e2004e703,None,0,same,310.0,66f660819e62b4674d17534a,PLATINUM,WEEKLY,UNKNOWN
2,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65841eced0269f8c95562d0e,66f663429e2a456423b58932,None,0,same,84.0,66f663002cf293416af76dbb,PLATINUM,WEEKLY,PS
3,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6331a989fcded19b614b061d,66f66bd15834435b3f11ed9f,routeDiff,0,same,56.0,66f66dc4afe48fcf9e119258,ELITE,DAILY,NPS
4,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6226c3e549fea91acf9f5fd0,66f66b539c002a5436eb885b,waitTimeCharges,3,increase,154.0,66f66b4b6f2c69bde5eee47f,ELITE,DAILY,NPS

In [25]:
# Merge 
df_merge_bin = pd.merge(df_customer_order,
                        customer_negative_bins,
                        how='left',
                        left_on=['service_detail_id', 'customer_id'],
                        right_on=['servicedetailid', 'customer_id']
                        )
df_merge_bin['negative_order_bin'] = df_merge_bin['negative_order_bin'].fillna(0)

In [26]:
df_merge_bin.head()

,yyyymmdd,city_name,service_name,service_detail_id,customer_id,order_id,fare_recalculated_reason,fare_recalculated_diff_amount,fare_recalculated_type,amount,estimate_id,retention_segments,regularity_segments,ps_tag_auto,servicedetailid,negative_order_bin
0,20240913,Bangalore,Auto,5c53562fceb6fc9241980547,590b939933c57ee92c8a78ff,66e45101a6e3ce5f2dae7d1d,routeDiff,20,increase,123.0,66e45d498385ce8780b4bb8e,PRIME,WEEKLY,PS,5c53562fceb6fc9241980547,2.0
1,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,66f6608111a6ef4e2004e703,None,0,same,310.0,66f660819e62b4674d17534a,PLATINUM,WEEKLY,UNKNOWN,NaN,0.0
2,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65841eced0269f8c95562d0e,66f663429e2a456423b58932,None,0,same,84.0,66f663002cf293416af76dbb,PLATINUM,WEEKLY,PS,5c53562fceb6fc9241980547,2.0
3,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6331a989fcded19b614b061d,66f66bd15834435b3f11ed9f,routeDiff,0,same,56.0,66f66dc4afe48fcf9e119258,ELITE,DAILY,NPS,5c53562fceb6fc9241980547,1.0
4,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6226c3e549fea91acf9f5fd0,66f66b539c002a5436eb885b,waitTimeCharges,3,increase,154.0,66f66b4b6f2c69bde5eee47f,ELITE,DAILY,NPS,NaN,0.0

In [27]:
# Validation at city | service | customer level

df_merge_bin\
.groupby(['city_name', 'service_name', 'service_detail_id', 'customer_id', 'regularity_segments'])\
.agg(counts = ('negative_order_bin', 'nunique'))\
.sort_values(by=['counts'], ascending=False)\
.reset_index()\
.head()

,city_name,service_name,service_detail_id,customer_id,regularity_segments,counts
0,Bangalore,Auto,5c53562fceb6fc9241980547,5737c6d0ddbec2203f73329f,BI_WEEKLY,1
1,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,63233a9b5d3af4d950021a03,BI_WEEKLY,1
2,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,6323303e0f4eef94222e4c8f,DAILY,1
3,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,632330555ff6d3be234edcc7,WEEKLY,1
4,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,6323316a01c2fbb816ca5acd,BI_WEEKLY,1

In [28]:
df_customer_tag = df_merge_bin[['city_name', 'service_name', 'service_detail_id', 
                                'customer_id', 'regularity_segments', 'ps_tag_auto', 'negative_order_bin']]

<div class="alert alert-block alert-success">
    
### Analysis
</div>

In [29]:
df_customer_tag.head(1)

,city_name,service_name,service_detail_id,customer_id,regularity_segments,ps_tag_auto,negative_order_bin
0,Bangalore,Auto,5c53562fceb6fc9241980547,590b939933c57ee92c8a78ff,WEEKLY,PS,2.0

In [30]:
bins = [0, 1, 2, 5, float('inf')]  # float('inf') is used for 15+
labels = ['0', '1', '2-4', '5+']

# Create a new column with the bins
df_customer_tag['bins'] = pd.cut(df_customer_tag['negative_order_bin'], bins=bins, labels=labels, right=False)

In [31]:
df_retension_customer.head(1)

,week_start_date,city_name,service_name,service_detail_id,customer_id
0,20241104,Bangalore,Auto,5c53562fceb6fc9241980547,636791add58af7606ae3cc89

In [32]:
retention_df = pd.merge(df_customer_tag,
                        df_retension_customer,
                        how='left',
                        left_on=['city_name', 'service_name', 'service_detail_id', 'customer_id'],
                        right_on=['city_name', 'service_name', 'service_detail_id', 'customer_id']
                        )

In [33]:
retention_df.shape

(33118318, 9)

In [34]:
retention_df

,city_name,service_name,service_detail_id,customer_id,regularity_segments,ps_tag_auto,negative_order_bin,bins,week_start_date
0,Bangalore,Auto,5c53562fceb6fc9241980547,590b939933c57ee92c8a78ff,WEEKLY,PS,2.0,2-4,20241014
1,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,WEEKLY,UNKNOWN,0.0,0,20241021
2,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,WEEKLY,UNKNOWN,0.0,0,20241007
3,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,WEEKLY,UNKNOWN,0.0,0,20241028
4,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,WEEKLY,UNKNOWN,0.0,0,20241014
...,...,...,...,...,...,...,...,...,...
33118313,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,668f6e03c2b70dcddf041ee0,DAILY,UNKNOWN,0.0,0,20241014
33118314,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,614803ddde864c824601edf9,WEEKLY,NPS,0.0,0,20241014
33118315,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,614803ddde864c824601edf9,WEEKLY,NPS,0.0,0,20241104
33118316,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,65ec66244b593aaea4a09936,WEEKLY,NPS,0.0,0,NaN
33118317,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,5de33ba0d472d62e9459e4b9,RARE_NEED,UNKNOWN,0.0,0,20241021

In [35]:
df_grouped = retention_df\
                .groupby(['city_name', 'service_name', 'service_detail_id', 'ps_tag_auto', 'bins'])\
                .agg(unique_customers=('customer_id', 'nunique'))\
                .reset_index()
df_grouped.head(2)

,city_name,service_name,service_detail_id,ps_tag_auto,bins,unique_customers
0,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,0,343648
1,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,1,203391

In [36]:
df_grouped_weekly = retention_df\
                        .groupby(['city_name', 'service_name', 'service_detail_id', 'ps_tag_auto', 
                                  'bins', 'week_start_date'])\
                        .agg(unique_customers=('customer_id', 'nunique'))\
                        .reset_index()
df_grouped_weekly.head(2)

,city_name,service_name,service_detail_id,ps_tag_auto,bins,week_start_date,unique_customers
0,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,0,20240930,107136
1,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,0,20241007,102427

In [37]:
df_pivot_table = df_grouped_weekly.pivot(index=['city_name', 'service_name', 'service_detail_id', 
                                                'ps_tag_auto', 'bins'],
                         columns='week_start_date',
                         values='unique_customers',
                        ).reset_index()
pivot_table = df_pivot_table.reset_index(drop=True)
pivot_table

week_start_date,city_name,service_name,service_detail_id,ps_tag_auto,bins,20240930,20241007,20241014,20241021,20241028,20241104
0,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,0,107136,102427,109681,99391,88820,94732
1,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,1,74452,71009,73594,67819,60764,64539
2,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,2-4,69805,65009,65670,62441,54934,58468
3,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,5+,28605,26362,26369,25788,22425,24060
4,Bangalore,Auto,5c53562fceb6fc9241980547,PS,0,59029,56939,62344,54165,48752,50734
...,...,...,...,...,...,...,...,...,...,...,...
355,Delhi,CabEconomy,6516a74cb0ef8abf16cec40d,PS,5+,0,0,0,0,0,0
356,Delhi,CabEconomy,6516a74cb0ef8abf16cec40d,UNKNOWN,0,0,0,0,0,0,0
357,Delhi,CabEconomy,6516a74cb0ef8abf16cec40d,UNKNOWN,1,0,0,0,0,0,0
358,Delhi,CabEconomy,6516a74cb0ef8abf16cec40d,UNKNOWN,2-4,0,0,0,0,0,0
359,Delhi,CabEconomy,6516a74cb0ef8abf16cec40d,UNKNOWN,5+,0,0,0,0,0,0

<div class="alert alert-block alert-success">
    
### Retention %
</div>

In [38]:
df_grouped.shape

(360, 6)

In [39]:
pivot_table.shape

(360, 11)

In [40]:
df_grouped.head(1)

,city_name,service_name,service_detail_id,ps_tag_auto,bins,unique_customers
0,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,0,343648

In [41]:
pivot_table.head(1)

week_start_date,city_name,service_name,service_detail_id,ps_tag_auto,bins,20240930,20241007,20241014,20241021,20241028,20241104
0,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,0,107136,102427,109681,99391,88820,94732

In [42]:
df_final = pd.merge(df_grouped,
                    pivot_table,
                    how='inner',
                    on=['city_name', 'service_name', 'service_detail_id', 'ps_tag_auto', 'bins']
                   )
df_final.head(2)

,city_name,service_name,service_detail_id,ps_tag_auto,bins,unique_customers,20240930,20241007,20241014,20241021,20241028,20241104
0,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,0,343648,107136,102427,109681,99391,88820,94732
1,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,1,203391,74452,71009,73594,67819,60764,64539

In [43]:
date_columns = ["20240930", "20241007", "20241014", "20241021", "20241028", "20241104"]

for date in date_columns:

    df_final[f"{date}_%"] = (df_final[date]*100.00/df_final["unique_customers"]).round(2)

In [44]:
df_final = df_final[df_final['unique_customers'] > 0]

In [45]:
df_final

,city_name,service_name,service_detail_id,ps_tag_auto,bins,unique_customers,20240930,20241007,20241014,20241021,20241028,20241104,20240930_%,20241007_%,20241014_%,20241021_%,20241028_%,20241104_%
0,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,0,343648,107136,102427,109681,99391,88820,94732,31.18,29.81,31.92,28.92,25.85,27.57
1,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,1,203391,74452,71009,73594,67819,60764,64539,36.61,34.91,36.18,33.34,29.88,31.73
2,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,2-4,127219,69805,65009,65670,62441,54934,58468,54.87,51.10,51.62,49.08,43.18,45.96
3,Bangalore,Auto,5c53562fceb6fc9241980547,NPS,5+,34754,28605,26362,26369,25788,22425,24060,82.31,75.85,75.87,74.20,64.52,69.23
4,Bangalore,Auto,5c53562fceb6fc9241980547,PS,0,212178,59029,56939,62344,54165,48752,50734,27.82,26.84,29.38,25.53,22.98,23.91
5,Bangalore,Auto,5c53562fceb6fc9241980547,PS,1,137034,43575,41958,44484,39272,35575,37019,31.80,30.62,32.46,28.66,25.96,27.01
6,Bangalore,Auto,5c53562fceb6fc9241980547,PS,2-4,76186,38279,35647,36352,33655,29870,31477,50.24,46.79,47.71,44.17,39.21,41.32
7,Bangalore,Auto,5c53562fceb6fc9241980547,PS,5+,17608,14102,13113,12938,12646,10900,11743,80.09,74.47,73.48,71.82,61.90,66.69
8,Bangalore,Auto,5c53562fceb6fc9241980547,UNKNOWN,0,330998,52082,49609,54606,48498,43501,46185,15.73,14.99,16.50,14.65,13.14,13.95
9,Bangalore,Auto,5c53562fceb6fc9241980547,UNKNOWN,1,139066,22816,21961,23398,20806,19001,19937,16.41,15.79,16.83,14.96,13.66,14.34
10,Bangalore,Auto,5c53562fceb6fc9241980547,UNKNOWN,2-4,25198,8671,8092,8285,7923,6864,7412,34.41,32.11,32.88,31.44,27.24,29.42
11,Bangalore,Auto,5c53562fceb6fc9241980547,UNKNOWN,5+,3187,2201,1980,2009,1996,1699,1883,69.06,62.13,63.04,62.63,53.31,59.08
168,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,NPS,0,143998,22929,22112,21249,18895,17257,18035,15.92,15.36,14.76,13.12,11.98,12.52
169,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,NPS,1,47577,9681,9091,8768,7844,7001,7305,20.35,19.11,18.43,16.49,14.72,15.35
170,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,NPS,2-4,11059,4536,4172,3950,3768,3193,3545,41.02,37.72,35.72,34.07,28.87,32.06
171,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,NPS,5+,1075,812,744,710,702,573,637,75.53,69.21,66.05,65.30,53.30,59.26
172,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,PS,0,86124,13444,12613,12287,10852,9644,10019,15.61,14.65,14.27,12.60,11.20,11.63
173,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,PS,1,28616,5483,5192,5134,4521,3922,4094,19.16,18.14,17.94,15.80,13.71,14.31
174,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,PS,2-4,6304,2560,2326,2203,2062,1714,1900,40.61,36.90,34.95,32.71,27.19,30.14
175,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,PS,5+,700,532,483,479,459,347,394,76.00,69.00,68.43,65.57,49.57,56.29
176,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,UNKNOWN,0,114685,9029,8620,8289,7388,6737,7157,7.87,7.52,7.23,6.44,5.87,6.24
177,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,UNKNOWN,1,34030,3240,3130,2968,2697,2411,2615,9.52,9.20,8.72,7.93,7.08,7.68
178,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,UNKNOWN,2-4,4092,1147,1052,1020,965,820,919,28.03,25.71,24.93,23.58,20.04,22.46
179,Bangalore,CabEconomy,6516a74cb0ef8abf16cec40d,UNKNOWN,5+,339,229,217,205,204,163,183,67.55,64.01,60.47,60.18,48.08,53.98
192,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,NPS,0,198751,43474,43708,42052,41419,33384,38823,21.87,21.99,21.16,20.84,16.80,19.53
193,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,NPS,1,88872,22834,22608,21750,21678,17008,19856,25.69,25.44,24.47,24.39,19.14,22.34
194,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,NPS,2-4,35754,16294,15684,15343,14684,10898,13243,45.57,43.87,42.91,41.07,30.48,37.04
195,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,NPS,5+,6603,5148,4907,4777,4571,3344,4172,77.96,74.31,72.35,69.23,50.64,63.18
196,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,PS,0,138660,33914,33822,32997,31882,24924,30668,24.46,24.39,23.80,22.99,17.97,22.12
197,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,PS,1,65657,18396,18015,17671,16990,13166,16113,28.02,27.44,26.91,25.88,20.05,24.54
198,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,PS,2-4,29034,13969,13243,12954,12448,9069,11671,48.11,45.61,44.62,42.87,31.24,40.20
199,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,PS,5+,5617,4368,4081,4111,3930,2851,3664,77.76,72.65,73.19,69.97,50.76,65.23
200,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,UNKNOWN,0,208824,20086,19256,18387,18146,15111,17079,9.62,9.22,8.81,8.69,7.24,8.18
201,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,UNKNOWN,1,80314,7956,7810,7277,7179,6029,6796,9.91,9.72,9.06,8.94,7.51,8.46
202,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,UNKNOWN,2-4,9199,2474,2360,2245,2106,1568,1872,26.89,25.65,24.40,22.89,17.05,20.35
203,Delhi,Auto,5fc8c40bf4f0a70007d7cfbc,UNKNOWN,5+,525,347,325,317,305,223,266,66.10,61.90,60.38,58.10,42.48,50.67
276,Delhi,Auto NCR,64d22fba29b334580f1e3a18,NPS,0,14073,1632,1507,1469,1480,1226,1255,11.60,10.71,10.44,10.52,8.71,8.92
277,Delhi,Auto NCR,64d22fba29b334580f1e3a18,NPS,1,6389,909,884,855,842,707,684,14.23,13.84,13.38,13.18,11.07,10.71
278,Delhi,Auto NCR,64d22fba29b334580f1e3a18,NPS,2-4,1610,640,616,604,593,437,500,39.75,38.26,37.52,36.83,27.14,31.06
279,Delhi,Auto NCR,64d22fba29b334580f1e3a18,NPS,5+,309,229,217,212,212,168,198,74.11,70.23,68.61,68.61,54.37,64.08
280,Delhi,Auto NCR,64d22fba29b334580f1e3a18,PS,0,3195,328,329,334,348,256,286,10.27,10.30,10.45,10.89,8.01,8.95
281,Delhi,Auto NCR,64d22fba29b334580f1e3a18,PS,1,1409,189,180,182,175,150,155,13.41,12.78,12.92,12.42,10.65,11.00
282,Delhi,Auto NCR,64d22fba29b334580f1e3a18,PS,2-4,288,98,99,98,92,72,76,34.03,34.38,34.03,31.94,25.00,26.39
283,Delhi,Auto NCR,64d22fba29b334580f1e3a18,PS,5+,31,25,22,21,20,14,17,80.65,70.97,67.74,64.52,45.16,54.84
284,Delhi,Auto NCR,64d22fba29b334580f1e3a18,UNKNOWN,0,11832,722,724,659,659,558,551,6.10,6.12,5.57,5.57,4.72,4.66
285,Delhi,Auto NCR,64d22fba29b334580f1e3a18,UNKNOWN,1,5284,403,355,326,335,297,294,7.63,6.72,6.17,6.34,5.62,5.56
286,Delhi,Auto NCR,64d22fba29b334580f1e3a18,UNKNOWN,2-4,635,199,182,176,166,138,151,31.34,28.66,27.72,26.14,21.73,23.78
287,Delhi,Auto NCR,64d22fba29b334580f1e3a18,UNKNOWN,5+,65,54,51,48,44,32,40,83.08,78.46,73.85,67.69,49.23,61.54
324,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,NPS,0,169380,39656,40156,38157,38598,32895,36503,23.41,23.71,22.53,22.79,19.42,21.55
325,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,NPS,1,11781,4363,4433,4250,4262,3531,3944,37.03,37.63,36.08,36.18,29.97,33.48
326,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,NPS,2-4,1982,1270,1255,1205,1216,1005,1105,64.08,63.32,60.80,61.35,50.71,55.75
327,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,NPS,5+,49,37,41,42,39,31,37,75.51,83.67,85.71,79.59,63.27,75.51
328,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,PS,0,110605,25395,25616,24419,24920,20411,23480,22.96,23.16,22.08,22.53,18.45,21.23
329,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,PS,1,7169,2389,2424,2404,2378,1868,2222,33.32,33.81,33.53,33.17,26.06,30.99
330,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,PS,2-4,881,522,506,509,476,406,447,59.25,57.43,57.78,54.03,46.08,50.74
331,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,PS,5+,18,13,9,12,14,10,12,72.22,50.00,66.67,77.78,55.56,66.67
332,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,UNKNOWN,0,366830,48063,46958,44288,44275,39084,42463,13.10,12.80,12.07,12.07,10.65,11.58
333,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,UNKNOWN,1,19023,3585,3626,3612,3686,3083,3443,18.85,19.06,18.99,19.38,16.21,18.10
334,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,UNKNOWN,2-4,1957,895,848,860,860,700,795,45.73,43.33,43.94,43.94,35.77,40.62
335,Delhi,CabEconomy,648aaa1b4cf8d978be7ac5f6,UNKNOWN,5+,43,29,24,25,24,21,25,67.44,55.81,58.14,55.81,48.84,58.14

In [46]:
df_final[['city_name','service_name', 'ps_tag_auto', 'bins',
          'unique_customers', 
          '20240930_%',	'20241007_%',	'20241014_%',	'20241021_%', '20241028_%',	'20241104_%' ]]

,city_name,service_name,ps_tag_auto,bins,unique_customers,20240930_%,20241007_%,20241014_%,20241021_%,20241028_%,20241104_%
0,Bangalore,Auto,NPS,0,343648,31.18,29.81,31.92,28.92,25.85,27.57
1,Bangalore,Auto,NPS,1,203391,36.61,34.91,36.18,33.34,29.88,31.73
2,Bangalore,Auto,NPS,2-4,127219,54.87,51.10,51.62,49.08,43.18,45.96
3,Bangalore,Auto,NPS,5+,34754,82.31,75.85,75.87,74.20,64.52,69.23
4,Bangalore,Auto,PS,0,212178,27.82,26.84,29.38,25.53,22.98,23.91
5,Bangalore,Auto,PS,1,137034,31.80,30.62,32.46,28.66,25.96,27.01
6,Bangalore,Auto,PS,2-4,76186,50.24,46.79,47.71,44.17,39.21,41.32
7,Bangalore,Auto,PS,5+,17608,80.09,74.47,73.48,71.82,61.90,66.69
8,Bangalore,Auto,UNKNOWN,0,330998,15.73,14.99,16.50,14.65,13.14,13.95
9,Bangalore,Auto,UNKNOWN,1,139066,16.41,15.79,16.83,14.96,13.66,14.34
10,Bangalore,Auto,UNKNOWN,2-4,25198,34.41,32.11,32.88,31.44,27.24,29.42
11,Bangalore,Auto,UNKNOWN,5+,3187,69.06,62.13,63.04,62.63,53.31,59.08
168,Bangalore,CabEconomy,NPS,0,143998,15.92,15.36,14.76,13.12,11.98,12.52
169,Bangalore,CabEconomy,NPS,1,47577,20.35,19.11,18.43,16.49,14.72,15.35
170,Bangalore,CabEconomy,NPS,2-4,11059,41.02,37.72,35.72,34.07,28.87,32.06
171,Bangalore,CabEconomy,NPS,5+,1075,75.53,69.21,66.05,65.30,53.30,59.26
172,Bangalore,CabEconomy,PS,0,86124,15.61,14.65,14.27,12.60,11.20,11.63
173,Bangalore,CabEconomy,PS,1,28616,19.16,18.14,17.94,15.80,13.71,14.31
174,Bangalore,CabEconomy,PS,2-4,6304,40.61,36.90,34.95,32.71,27.19,30.14
175,Bangalore,CabEconomy,PS,5+,700,76.00,69.00,68.43,65.57,49.57,56.29
176,Bangalore,CabEconomy,UNKNOWN,0,114685,7.87,7.52,7.23,6.44,5.87,6.24
177,Bangalore,CabEconomy,UNKNOWN,1,34030,9.52,9.20,8.72,7.93,7.08,7.68
178,Bangalore,CabEconomy,UNKNOWN,2-4,4092,28.03,25.71,24.93,23.58,20.04,22.46
179,Bangalore,CabEconomy,UNKNOWN,5+,339,67.55,64.01,60.47,60.18,48.08,53.98
192,Delhi,Auto,NPS,0,198751,21.87,21.99,21.16,20.84,16.80,19.53
193,Delhi,Auto,NPS,1,88872,25.69,25.44,24.47,24.39,19.14,22.34
194,Delhi,Auto,NPS,2-4,35754,45.57,43.87,42.91,41.07,30.48,37.04
195,Delhi,Auto,NPS,5+,6603,77.96,74.31,72.35,69.23,50.64,63.18
196,Delhi,Auto,PS,0,138660,24.46,24.39,23.80,22.99,17.97,22.12
197,Delhi,Auto,PS,1,65657,28.02,27.44,26.91,25.88,20.05,24.54
198,Delhi,Auto,PS,2-4,29034,48.11,45.61,44.62,42.87,31.24,40.20
199,Delhi,Auto,PS,5+,5617,77.76,72.65,73.19,69.97,50.76,65.23
200,Delhi,Auto,UNKNOWN,0,208824,9.62,9.22,8.81,8.69,7.24,8.18
201,Delhi,Auto,UNKNOWN,1,80314,9.91,9.72,9.06,8.94,7.51,8.46
202,Delhi,Auto,UNKNOWN,2-4,9199,26.89,25.65,24.40,22.89,17.05,20.35
203,Delhi,Auto,UNKNOWN,5+,525,66.10,61.90,60.38,58.10,42.48,50.67
276,Delhi,Auto NCR,NPS,0,14073,11.60,10.71,10.44,10.52,8.71,8.92
277,Delhi,Auto NCR,NPS,1,6389,14.23,13.84,13.38,13.18,11.07,10.71
278,Delhi,Auto NCR,NPS,2-4,1610,39.75,38.26,37.52,36.83,27.14,31.06
279,Delhi,Auto NCR,NPS,5+,309,74.11,70.23,68.61,68.61,54.37,64.08
280,Delhi,Auto NCR,PS,0,3195,10.27,10.30,10.45,10.89,8.01,8.95
281,Delhi,Auto NCR,PS,1,1409,13.41,12.78,12.92,12.42,10.65,11.00
282,Delhi,Auto NCR,PS,2-4,288,34.03,34.38,34.03,31.94,25.00,26.39
283,Delhi,Auto NCR,PS,5+,31,80.65,70.97,67.74,64.52,45.16,54.84
284,Delhi,Auto NCR,UNKNOWN,0,11832,6.10,6.12,5.57,5.57,4.72,4.66
285,Delhi,Auto NCR,UNKNOWN,1,5284,7.63,6.72,6.17,6.34,5.62,5.56
286,Delhi,Auto NCR,UNKNOWN,2-4,635,31.34,28.66,27.72,26.14,21.73,23.78
287,Delhi,Auto NCR,UNKNOWN,5+,65,83.08,78.46,73.85,67.69,49.23,61.54
324,Delhi,CabEconomy,NPS,0,169380,23.41,23.71,22.53,22.79,19.42,21.55
325,Delhi,CabEconomy,NPS,1,11781,37.03,37.63,36.08,36.18,29.97,33.48
326,Delhi,CabEconomy,NPS,2-4,1982,64.08,63.32,60.80,61.35,50.71,55.75
327,Delhi,CabEconomy,NPS,5+,49,75.51,83.67,85.71,79.59,63.27,75.51
328,Delhi,CabEconomy,PS,0,110605,22.96,23.16,22.08,22.53,18.45,21.23
329,Delhi,CabEconomy,PS,1,7169,33.32,33.81,33.53,33.17,26.06,30.99
330,Delhi,CabEconomy,PS,2-4,881,59.25,57.43,57.78,54.03,46.08,50.74
331,Delhi,CabEconomy,PS,5+,18,72.22,50.00,66.67,77.78,55.56,66.67
332,Delhi,CabEconomy,UNKNOWN,0,366830,13.10,12.80,12.07,12.07,10.65,11.58
333,Delhi,CabEconomy,UNKNOWN,1,19023,18.85,19.06,18.99,19.38,16.21,18.10
334,Delhi,CabEconomy,UNKNOWN,2-4,1957,45.73,43.33,43.94,43.94,35.77,40.62
335,Delhi,CabEconomy,UNKNOWN,5+,43,67.44,55.81,58.14,55.81,48.84,58.14

In [56]:
df_final.to_clipboard(index=False)

### Orders

In [47]:
df_merge_bin.head()

,yyyymmdd,city_name,service_name,service_detail_id,customer_id,order_id,fare_recalculated_reason,fare_recalculated_diff_amount,fare_recalculated_type,amount,estimate_id,retention_segments,regularity_segments,ps_tag_auto,servicedetailid,negative_order_bin
0,20240913,Bangalore,Auto,5c53562fceb6fc9241980547,590b939933c57ee92c8a78ff,66e45101a6e3ce5f2dae7d1d,routeDiff,20,increase,123.0,66e45d498385ce8780b4bb8e,PRIME,WEEKLY,PS,5c53562fceb6fc9241980547,2.0
1,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65b8126fec61531661fc53d3,66f6608111a6ef4e2004e703,None,0,same,310.0,66f660819e62b4674d17534a,PLATINUM,WEEKLY,UNKNOWN,NaN,0.0
2,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,65841eced0269f8c95562d0e,66f663429e2a456423b58932,None,0,same,84.0,66f663002cf293416af76dbb,PLATINUM,WEEKLY,PS,5c53562fceb6fc9241980547,2.0
3,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6331a989fcded19b614b061d,66f66bd15834435b3f11ed9f,routeDiff,0,same,56.0,66f66dc4afe48fcf9e119258,ELITE,DAILY,NPS,5c53562fceb6fc9241980547,1.0
4,20240927,Bangalore,Auto,5c53562fceb6fc9241980547,6226c3e549fea91acf9f5fd0,66f66b539c002a5436eb885b,waitTimeCharges,3,increase,154.0,66f66b4b6f2c69bde5eee47f,ELITE,DAILY,NPS,NaN,0.0

In [48]:
df_test_orders = df_merge_bin.copy()

In [49]:
bins_test = [0, 1, float('inf')]  # float('inf') is used for 15+
labels_test = ['Zero', '1 =< ' ]

# Create a new column with the bins
df_test_orders['bins'] = pd.cut(df_test_orders['negative_order_bin'], bins=bins_test, labels=labels_test, right=False)

In [50]:
df1 = df_test_orders\
.groupby(['city_name', 'service_name', 'service_detail_id', 'ps_tag_auto', 'bins'])\
.agg(orders = ('order_id', 'nunique'))\
.reset_index()

In [51]:
df1 = df1[df1['orders'] > 0]

In [59]:
df1.to_clipboard(index=False)

In [52]:
df2 = df_test_orders\
.groupby(['city_name', 'service_name', 'service_detail_id', 'bins'])\
.agg(orders = ('order_id', 'nunique'))\
.reset_index()

In [53]:
df2 = df2[df2['orders'] > 0]

In [54]:
df2

    city_name service_name         service_detail_id   bins   orders
0   Bangalore         Auto  5c53562fceb6fc9241980547   Zero  1964424
1   Bangalore         Auto  5c53562fceb6fc9241980547  1 =<   4369488
28  Bangalore   CabEconomy  6516a74cb0ef8abf16cec40d   Zero   544698
29  Bangalore   CabEconomy  6516a74cb0ef8abf16cec40d  1 =<    409216
32      Delhi         Auto  5fc8c40bf4f0a70007d7cfbc   Zero  1059465
33      Delhi         Auto  5fc8c40bf4f0a70007d7cfbc  1 =<   1318029
46      Delhi     Auto NCR  64d22fba29b334580f1e3a18   Zero    42776
47      Delhi     Auto NCR  64d22fba29b334580f1e3a18  1 =<     44094
54      Delhi   CabEconomy  648aaa1b4cf8d978be7ac5f6   Zero  1425298
55      Delhi   CabEconomy  648aaa1b4cf8d978be7ac5f6  1 =<    239885

In [62]:
df2.to_clipboard(index=False)