## Imports

In [2]:
import glob
import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

import time

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [3]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [4]:
## Connection
connection = presto.connect(
        host='processing-2.processing.data.production.internal' ,
    # 'presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'
conn1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
conn2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
conn3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
conn4= presto.connect('processing.processing.data.production.internal',presto_port,username)

In [5]:
local_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/'
local_path

'/Users/E2074/local-datasets/customer/segmentation/consideration/'

In [6]:
city = 'delhi'
city_name = 'Delhi'

## Datasets & Parameter

In [7]:
start_date = datetime.strptime("2025-03-03", "%Y-%m-%d")

run_date = [(start_date + timedelta(weeks=i)).strftime("%Y-%m-%d") for i in range(10)]
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [8]:
def get_feature_engineering(df):
    
    print('feature engineering part')
    # Adding required active month fields
    df['isAct_m01'] = np.where(df[['isAct_w01', 'isAct_w02', 'isAct_w03', 'isAct_w04']].sum(axis=1) >= 1, 1, 0)
    df['isAct_m02'] = np.where(df[['isAct_w05', 'isAct_w06', 'isAct_w07', 'isAct_w08']].sum(axis=1) >= 1, 1, 0)
    df['isAct_m03'] = np.where(df[['isAct_w09', 'isAct_w10', 'isAct_w11', 'isAct_w12', 'isAct_w13']].sum(axis=1) >= 1, 1, 0)
    
    df['max_active_months'] = 3
    df['total_active_months'] = df[['isAct_m01', 'isAct_m02', 'isAct_m03']].sum(axis=1)
    
    df['days_since_1st_ride_in_3months'] = np.where(df['rapido_firstride_age']>=91,91,df['rapido_firstride_age'])
    df['weeks_since_1st_ride_in_3months'] = np.ceil(df['days_since_1st_ride_in_3months']/7)
    df['months_since_1st_ride_in_3months'] = np.ceil(df['days_since_1st_ride_in_3months']/31)

    df["customerid"] = df["customerid"].fillna('NA')
    df.fillna(0,inplace=True)


    # Adding required derived percentage fields for making thresholds
    df['active_days_percet'] = (df['total_active_days']/df['days_since_1st_ride_in_3months']).round(2)
    df['active_weeks_percet'] = (df['total_active_weeks']/df['weeks_since_1st_ride_in_3months']).round(2)
    df['active_months_percet'] = (df['total_active_months']/df['months_since_1st_ride_in_3months']).round(2)

    return df

In [9]:
def get_segment(df):

    print('segmentation part')
    
    df['hh_monthly_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])) & (df['active_months_percet'] >= 0.66), '1-HH-MONTHLY', None)
    df['hh_quarterly_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])) & (df['total_active_days'] > 0), '2-HH-QUARTERLY', None)
    df['hh_inactive_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])), '3-HH-INACTIVE',  None)
    
    df['daily_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH']))& (df['active_days_percet'] >= 0.45), '4-DAILY', None)
    df['weekly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['active_weeks_percet'] >= 0.70), '5-WEEKLY', None)
    df['monthly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['active_months_percet'] >= 0.66), '6-MONTHLY', None)
    df['quarterly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & df['total_active_days'] > 0, '7-QUARTERLY', None)
    df['inactive_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['total_active_days'] == 0), '8-INACTIVE', None)
    df['new_segment'] = np.where((~df['taxi_ltr_segment'].isin(['HH', 'PHH'])), '9-NEW', None)
    df['segment'] = df['hh_monthly_segment']\
                        .fillna(df['hh_quarterly_segment'])\
                        .fillna(df['hh_inactive_segment'])\
                        .fillna(df['daily_segment'])\
                        .fillna(df['weekly_segment'])\
                        .fillna(df['monthly_segment'])\
                        .fillna(df['quarterly_segment'])\
                        .fillna(df['inactive_segment'])\
                        .fillna(df['new_segment'])\
                        .fillna('check')
    
    df['updated_segment'] = df['segment']
    
    df.loc[((df['updated_segment']=='7-QUARTERLY')& (df['weeks_since_1st_ride_in_3months']<=8)), 'updated_segment'] = '6-MONTHLY'
    df.loc[((df['updated_segment'] == '5-WEEKLY') & (df['weeks_since_1st_ride_in_3months']<=2)), 'updated_segment'] = '6-MONTHLY'

    return df

In [10]:
df_list

NameError: name 'df_list' is not defined

In [11]:
for df_name in df_list:
    print(df_name)
    df = dfs[df_name]
    df_temp = get_feature_engineering(df)
    df_final = get_segment(df_temp)
    df_final.to_parquet(local_path + city + '/segment/{}.parquet'.format(df_name), index=False)
    
    print('---')

NameError: name 'df_list' is not defined

In [12]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/' + city + '/segment/test/'

# Get all parquet files in the folder
parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

In [13]:
parquet_files = sorted(parquet_files)
parquet_files

['/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250303.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250310.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250317.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250324.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250331.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250407.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250414.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250421.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250428.parquet',
 '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/segment/test/df_20250505.parquet']

In [14]:
# Read and concatenate all parquet files into a single DataFrame
df_segment_concat = pd.concat([pd.read_parquet(file) for file in parquet_files], ignore_index=True)

In [15]:
df_segment_concat.head(1)

     run_date               customer_id        segment updated_segment
0  2025-03-03  63145a0640c18148020ff5e5  3-HH-INACTIVE   3-HH-INACTIVE

In [16]:
df_segment_concat.shape

(95649138, 4)

In [17]:
df_segment_concat.segment.unique()

array(['3-HH-INACTIVE', '2-HH-QUARTERLY', '1-HH-MONTHLY', '6-MONTHLY',
       '7-QUARTERLY', '5-WEEKLY', '4-DAILY'], dtype=object)

## Stability

In [18]:
df_segment_concat.run_date.unique()

array(['2025-03-03', '2025-03-10', '2025-03-17', '2025-03-24',
       '2025-03-31', '2025-04-07', '2025-04-14', '2025-04-21',
       '2025-04-28', '2025-05-05'], dtype=object)

In [19]:
df_base = df_segment_concat[df_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base

           run_date               customer_id         segment updated_segment
0        2025-03-03  63145a0640c18148020ff5e5   3-HH-INACTIVE   3-HH-INACTIVE
1        2025-03-03  65953febb6c2d0503fbb8c1c  2-HH-QUARTERLY  2-HH-QUARTERLY
2        2025-03-03  670da09b0401f7fbd582e8ba   3-HH-INACTIVE   3-HH-INACTIVE
3        2025-03-03  67205781aa7eb8928ebbe454   3-HH-INACTIVE   3-HH-INACTIVE
4        2025-03-03  62fb9bc8c496e55cdb09a787   3-HH-INACTIVE   3-HH-INACTIVE
...             ...                       ...             ...             ...
9106563  2025-03-03  65b05f9c706706ae5505ac91     7-QUARTERLY     7-QUARTERLY
9106564  2025-03-03  646477b619489e42cdcbdd69       6-MONTHLY       6-MONTHLY
9106565  2025-03-03  5d8a4485941a7d1c51c1b779        5-WEEKLY        5-WEEKLY
9106566  2025-03-03  5c39ec214a267149c76dee56        5-WEEKLY        5-WEEKLY
9106567  2025-03-03  6651bb27ff7759169f1cc345     7-QUARTERLY     7-QUARTERLY

[9106568 rows x 4 columns]

In [20]:
df_stability_window = df_segment_concat[~df_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window

            run_date               customer_id        segment updated_segment
0         2025-03-10  672b3dd7c465a3565e785770   1-HH-MONTHLY    1-HH-MONTHLY
1         2025-03-10  654ce60924b813830ee4b720      6-MONTHLY       6-MONTHLY
2         2025-03-10  66897198bdbf8155016aa634      6-MONTHLY       6-MONTHLY
3         2025-03-10  656052879ef2f505d955cf5f       5-WEEKLY        5-WEEKLY
4         2025-03-10  624417cdf42d275568a7f69e    7-QUARTERLY     7-QUARTERLY
...              ...                       ...            ...             ...
86542565  2025-05-05  67594e59feadb698c3c75fa2  3-HH-INACTIVE   3-HH-INACTIVE
86542566  2025-05-05  64dad77aeb25685129bd04d6  3-HH-INACTIVE   3-HH-INACTIVE
86542567  2025-05-05  654a01704ced0fce02f621d3  3-HH-INACTIVE   3-HH-INACTIVE
86542568  2025-05-05  62e2ced6d8a2495544aec6bf  3-HH-INACTIVE   3-HH-INACTIVE
86542569  2025-05-05  65f9072d7ca1e480b009dff6      6-MONTHLY       6-MONTHLY

[86542570 rows x 4 columns]

In [21]:
df_stability_window.run_date.unique()

array(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
       '2025-04-07', '2025-04-14', '2025-04-21', '2025-04-28',
       '2025-05-05'], dtype=object)

In [22]:
df_merge = pd.merge(df_base, df_stability_window, how='left', on='customer_id')
df_merge

,run_date_x,customer_id,segment_x,updated_segment_x,run_date_y,segment_y,updated_segment_y
0,2025-03-03,63145a0640c18148020ff5e5,3-HH-INACTIVE,3-HH-INACTIVE,2025-03-10,3-HH-INACTIVE,3-HH-INACTIVE
1,2025-03-03,63145a0640c18148020ff5e5,3-HH-INACTIVE,3-HH-INACTIVE,2025-03-17,3-HH-INACTIVE,3-HH-INACTIVE
2,2025-03-03,63145a0640c18148020ff5e5,3-HH-INACTIVE,3-HH-INACTIVE,2025-03-24,3-HH-INACTIVE,3-HH-INACTIVE
3,2025-03-03,63145a0640c18148020ff5e5,3-HH-INACTIVE,3-HH-INACTIVE,2025-03-31,3-HH-INACTIVE,3-HH-INACTIVE
4,2025-03-03,63145a0640c18148020ff5e5,3-HH-INACTIVE,3-HH-INACTIVE,2025-04-07,3-HH-INACTIVE,3-HH-INACTIVE
...,...,...,...,...,...,...,...
77768511,2025-03-03,6651bb27ff7759169f1cc345,7-QUARTERLY,7-QUARTERLY,2025-04-07,7-QUARTERLY,7-QUARTERLY
77768512,2025-03-03,6651bb27ff7759169f1cc345,7-QUARTERLY,7-QUARTERLY,2025-04-14,7-QUARTERLY,7-QUARTERLY
77768513,2025-03-03,6651bb27ff7759169f1cc345,7-QUARTERLY,7-QUARTERLY,2025-04-21,7-QUARTERLY,7-QUARTERLY
77768514,2025-03-03,6651bb27ff7759169f1cc345,7-QUARTERLY,7-QUARTERLY,2025-04-28,6-MONTHLY,6-MONTHLY
77768515,2025-03-03,6651bb27ff7759169f1cc345,7-QUARTERLY,7-QUARTERLY,2025-05-05,6-MONTHLY,6-MONTHLY

In [23]:
df_merge_pivot = df_merge.groupby(['run_date_x', 'run_date_y', 'updated_segment_x', 'updated_segment_y']).agg(customers=('customer_id','nunique')).reset_index()

In [24]:
df_merge_pivot

     run_date_x  run_date_y updated_segment_x updated_segment_y  customers
0    2025-03-03  2025-03-10      1-HH-MONTHLY      1-HH-MONTHLY     609229
1    2025-03-03  2025-03-10      1-HH-MONTHLY    2-HH-QUARTERLY     136995
2    2025-03-03  2025-03-10      1-HH-MONTHLY     3-HH-INACTIVE         42
3    2025-03-03  2025-03-10      1-HH-MONTHLY           4-DAILY       2838
4    2025-03-03  2025-03-10      1-HH-MONTHLY          5-WEEKLY       6683
..          ...         ...               ...               ...        ...
319  2025-03-03  2025-05-05         6-MONTHLY       7-QUARTERLY     347930
320  2025-03-03  2025-05-05       7-QUARTERLY           4-DAILY       5143
321  2025-03-03  2025-05-05       7-QUARTERLY          5-WEEKLY      14298
322  2025-03-03  2025-05-05       7-QUARTERLY         6-MONTHLY     352927
323  2025-03-03  2025-05-05       7-QUARTERLY       7-QUARTERLY     314058

[324 rows x 5 columns]

In [25]:
df_merge_pivot.pivot(index = ['run_date_x', 'updated_segment_x', 'updated_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                                customers             \
run_date_y                                     2025-03-10 2025-03-17
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        609229.0   483042.0
                             2-HH-QUARTERLY      136995.0   236439.0
                             3-HH-INACTIVE           42.0       72.0
                             4-DAILY               2838.0     2095.0
                             5-WEEKLY              6683.0    14209.0
                             6-MONTHLY            22232.0    38429.0
                             7-QUARTERLY            845.0     2272.0
           2-HH-QUARTERLY    1-HH-MONTHLY         63046.0    91851.0
                             2-HH-QUARTERLY      806700.0   672207.0
                             3-HH-INACTIVE        87638.0   175284.0
                             4-DAILY                 27.0       30.0
                             5-WEEKLY               110.0      353.0
                             6-MONTHLY             7270.0    16548.0
                             7-QUARTERLY           9524.0    14895.0
           3-HH-INACTIVE     1-HH-MONTHLY         13518.0    13072.0
                             2-HH-QUARTERLY       38499.0    76096.0
                             3-HH-INACTIVE      3582282.0  3529495.0
                             4-DAILY                765.0      554.0
                             5-WEEKLY                 0.0        0.0
                             6-MONTHLY              435.0     1204.0
                             7-QUARTERLY           7357.0    16114.0
           4-DAILY           4-DAILY             167227.0   155965.0
                             5-WEEKLY              9940.0    17809.0
                             6-MONTHLY             3370.0     5489.0
                             7-QUARTERLY              0.0        5.0
           5-WEEKLY          4-DAILY               9741.0    13141.0
                             5-WEEKLY            316760.0   283768.0
                             6-MONTHLY            35205.0    61865.0
                             7-QUARTERLY              0.0        5.0
           6-MONTHLY         4-DAILY               2025.0     3613.0
                             5-WEEKLY             33947.0    53230.0
                             6-MONTHLY          1845484.0  1710946.0
                             7-QUARTERLY         151240.0   247190.0
           7-QUARTERLY       4-DAILY                  2.0       44.0
                             5-WEEKLY                 0.0        0.0
                             6-MONTHLY           138923.0   226599.0
                             7-QUARTERLY         859683.0   688486.0

                                                                      \
run_date_y                                     2025-03-24 2025-03-31
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        382462.0   307695.0
                             2-HH-QUARTERLY      311261.0   363424.0
                             3-HH-INACTIVE           91.0      114.0
                             4-DAILY               1877.0     1766.0
                             5-WEEKLY             18387.0    17696.0
                             6-MONTHLY            57467.0    79430.0
                             7-QUARTERLY           3198.0     2955.0
           2-HH-QUARTERLY    1-HH-MONTHLY        100612.0    89358.0
                             2-HH-QUARTERLY      579837.0   507405.0
                             3-HH-INACTIVE       240723.0   307064.0
                             4-DAILY                 26.0       18.0
                             5-WEEKLY               274.0      207.0
                             6-MONTHLY            28068.0    39863.0
                             7-QUARTERLY          18790.0    21621.0
           3-HH-INACTIVE     1-HH-MONTHLY         12500.0    11902.0
                             2-HH-QUARTERLY      107570.0   135074.0
                             3-HH-INACTIVE      3480697.0  3435788.0
                             4-DAILY                454.0      402.0
                             5-WEEKLY               716.0     1237.0
                             6-MONTHLY             1116.0     1047.0
                             7-QUARTERLY          26797.0    38189.0
           4-DAILY           4-DAILY             150654.0   146105.0
                             5-WEEKLY             21150.0    21752.0
                             6-MONTHLY             8265.0    11162.0
                             7-QUARTERLY             56.0      228.0
           5-WEEKLY          4-DAILY              19421.0    26053.0
                             5-WEEKLY            261609.0   240219.0
                             6-MONTHLY            78720.0    92225.0
                             7-QUARTERLY              7.0      421.0
           6-MONTHLY         4-DAILY               6298.0     9447.0
                             5-WEEKLY             72698.0    92287.0
                             6-MONTHLY          1640524.0  1598654.0
                             7-QUARTERLY         289155.0   300776.0
           7-QUARTERLY       4-DAILY                236.0      647.0
                             5-WEEKLY                 0.0        0.0
                             6-MONTHLY           274271.0   281256.0
                             7-QUARTERLY         576121.0   505103.0

                                                                      \
run_date_y                                     2025-04-07 2025-04-14
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        253187.0   224314.0
                             2-HH-QUARTERLY      380547.0   376702.0
                             3-HH-INACTIVE        17289.0    29329.0
                             4-DAILY               1654.0     1658.0
                             5-WEEKLY             16740.0    17282.0
                             6-MONTHLY            98973.0   113621.0
                             7-QUARTERLY           3092.0     6774.0
           2-HH-QUARTERLY    1-HH-MONTHLY        102574.0    99732.0
                             2-HH-QUARTERLY      430810.0   370417.0
                             3-HH-INACTIVE       354111.0   399462.0
                             4-DAILY                 19.0       13.0
                             5-WEEKLY               388.0      324.0
                             6-MONTHLY            53685.0    63325.0
                             7-QUARTERLY          21316.0    26585.0
           3-HH-INACTIVE     1-HH-MONTHLY             0.0    12182.0
                             2-HH-QUARTERLY      171962.0   189133.0
                             3-HH-INACTIVE      3391975.0  3340907.0
                             4-DAILY                362.0      327.0
                             5-WEEKLY               963.0      751.0
                             6-MONTHLY             1705.0    13210.0
                             7-QUARTERLY          50249.0    53615.0
           4-DAILY           4-DAILY             142890.0   137866.0
                             5-WEEKLY             22560.0    23745.0
                             6-MONTHLY            13473.0    15822.0
                             7-QUARTERLY            632.0     1251.0
           5-WEEKLY          4-DAILY              31802.0    35976.0
                             5-WEEKLY            222274.0   208070.0
                             6-MONTHLY           103440.0   111948.0
                             7-QUARTERLY           1562.0     1847.0
           6-MONTHLY         4-DAILY              12873.0    16395.0
                             5-WEEKLY            109508.0   124148.0
                             6-MONTHLY          1522599.0  1446747.0
                             7-QUARTERLY         316974.0   339026.0
           7-QUARTERLY       4-DAILY               1248.0     2098.0
                             5-WEEKLY              1261.0     3837.0
                             6-MONTHLY           324313.0   344263.0
                             7-QUARTERLY         436502.0   390911.0

                                                                      \
run_date_y                                     2025-04-21 2025-04-28
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        203739.0   190597.0
                             2-HH-QUARTERLY      367473.0   356579.0
                             3-HH-INACTIVE        39745.0    48348.0
                             4-DAILY               1632.0     1647.0
                             5-WEEKLY             15277.0    14105.0
                             6-MONTHLY           129862.0   141988.0
                             7-QUARTERLY          10301.0    13401.0
           2-HH-QUARTERLY    1-HH-MONTHLY         92460.0    79371.0
                             2-HH-QUARTERLY      310042.0   256416.0
                             3-HH-INACTIVE       449759.0   501434.0
                             4-DAILY                 24.0       70.0
                             5-WEEKLY               348.0      561.0
                             6-MONTHLY            72313.0    79558.0
                             7-QUARTERLY          32376.0    37506.0
           3-HH-INACTIVE     1-HH-MONTHLY         19603.0    24969.0
                             2-HH-QUARTERLY      210197.0   225925.0
                             3-HH-INACTIVE      3289890.0  3248140.0
                             4-DAILY                324.0      339.0
                             5-WEEKLY              1095.0      878.0
                             6-MONTHLY            23695.0    34934.0
                             7-QUARTERLY          58279.0    61612.0
           4-DAILY           4-DAILY             133012.0   129043.0
                             5-WEEKLY             25178.0    26319.0
                             6-MONTHLY            17882.0    20041.0
                             7-QUARTERLY           2222.0     2980.0
           5-WEEKLY          4-DAILY              38671.0    41843.0
                             5-WEEKLY            195738.0   183311.0
                             6-MONTHLY           119582.0   125433.0
                             7-QUARTERLY           3043.0     6707.0
           6-MONTHLY         4-DAILY              19371.0    22495.0
                             5-WEEKLY            135647.0   145208.0
                             6-MONTHLY          1387062.0  1343805.0
                             7-QUARTERLY         351343.0   354295.0
           7-QUARTERLY       4-DAILY               3093.0     4213.0
                             5-WEEKLY              7360.0    11594.0
                             6-MONTHLY           353943.0   349972.0
                             7-QUARTERLY         353505.0   328596.0


run_date_y                                     2025-05-05
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        173763.0
                             2-HH-QUARTERLY      321075.0
                             3-HH-INACTIVE        85938.0
                             4-DAILY               1655.0
                             5-WEEKLY             14020.0
                             6-MONTHLY           153390.0
                             7-QUARTERLY          15430.0
           2-HH-QUARTERLY    1-HH-MONTHLY         71876.0
                             2-HH-QUARTERLY      229030.0
                             3-HH-INACTIVE       521618.0
                             4-DAILY                144.0
                             5-WEEKLY               946.0
                             6-MONTHLY            89404.0
                             7-QUARTERLY          39582.0
           3-HH-INACTIVE     1-HH-MONTHLY         29840.0
                             2-HH-QUARTERLY      242637.0
                             3-HH-INACTIVE      3205898.0
                             4-DAILY                379.0
                             5-WEEKLY               734.0
                             6-MONTHLY            45058.0
                             7-QUARTERLY          66023.0
           4-DAILY           4-DAILY             124620.0
                             5-WEEKLY             27450.0
                             6-MONTHLY            21825.0
                             7-QUARTERLY           3951.0
           5-WEEKLY          4-DAILY              44040.0
                             5-WEEKLY            173082.0
                             6-MONTHLY           128231.0
                             7-QUARTERLY          11458.0
           6-MONTHLY         4-DAILY              25550.0
                             5-WEEKLY            154829.0
                             6-MONTHLY          1299115.0
                             7-QUARTERLY         347930.0
           7-QUARTERLY       4-DAILY               5143.0
                             5-WEEKLY             14298.0
                             6-MONTHLY           352927.0
                             7-QUARTERLY         314058.0

In [26]:
df_base.groupby(['run_date', 'updated_segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date updated_segment  customers
0  2025-03-03    1-HH-MONTHLY     782084
1  2025-03-03  2-HH-QUARTERLY     978043
2  2025-03-03   3-HH-INACTIVE    3651762
3  2025-03-03         4-DAILY     182416
4  2025-03-03        5-WEEKLY     365821
5  2025-03-03       6-MONTHLY    2056708
6  2025-03-03     7-QUARTERLY    1089734

In [27]:
df_merge_pivot1 = df_merge.groupby(['run_date_x', 'run_date_y', 'segment_x', 'segment_y']).agg(customers=('customer_id','nunique')).reset_index()

In [28]:
df_merge_pivot1

     run_date_x  run_date_y     segment_x       segment_y  customers
0    2025-03-03  2025-03-10  1-HH-MONTHLY    1-HH-MONTHLY     609229
1    2025-03-03  2025-03-10  1-HH-MONTHLY  2-HH-QUARTERLY     136995
2    2025-03-03  2025-03-10  1-HH-MONTHLY   3-HH-INACTIVE         42
3    2025-03-03  2025-03-10  1-HH-MONTHLY         4-DAILY       2838
4    2025-03-03  2025-03-10  1-HH-MONTHLY        5-WEEKLY       9012
..          ...         ...           ...             ...        ...
326  2025-03-03  2025-05-05     6-MONTHLY     7-QUARTERLY     344550
327  2025-03-03  2025-05-05   7-QUARTERLY         4-DAILY       5198
328  2025-03-03  2025-05-05   7-QUARTERLY        5-WEEKLY      14521
329  2025-03-03  2025-05-05   7-QUARTERLY       6-MONTHLY     356331
330  2025-03-03  2025-05-05   7-QUARTERLY     7-QUARTERLY     316735

[331 rows x 5 columns]

In [29]:
df_merge_pivot1.pivot(index = ['run_date_x', 'segment_x', 'segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                          customers                        \
run_date_y                               2025-03-10 2025-03-17 2025-03-24
run_date_x segment_x      segment_y
2025-03-03 1-HH-MONTHLY   1-HH-MONTHLY     609229.0   483042.0   382462.0
                          2-HH-QUARTERLY   136995.0   236439.0   311261.0
                          3-HH-INACTIVE        42.0       72.0       91.0
                          4-DAILY            2838.0     2095.0     1877.0
                          5-WEEKLY           9012.0    14430.0    18387.0
                          6-MONTHLY         19107.0    36846.0    55250.0
                          7-QUARTERLY        1641.0     3634.0     5415.0
           2-HH-QUARTERLY 1-HH-MONTHLY      63046.0    91851.0   100612.0
                          2-HH-QUARTERLY   806700.0   672207.0   579837.0
                          3-HH-INACTIVE     87638.0   175284.0   240723.0
                          4-DAILY              27.0       30.0       26.0
                          5-WEEKLY            110.0      359.0      274.0
                          6-MONTHLY          7104.0    16402.0    27988.0
                          7-QUARTERLY        9690.0    15035.0    18870.0
           3-HH-INACTIVE  1-HH-MONTHLY      13518.0    13072.0    12500.0
                          2-HH-QUARTERLY    38499.0    76096.0   107570.0
                          3-HH-INACTIVE   3582282.0  3529495.0  3480697.0
                          4-DAILY             765.0      554.0      454.0
                          5-WEEKLY            298.0      635.0      716.0
                          6-MONTHLY            96.0      482.0      949.0
                          7-QUARTERLY        7398.0    16201.0    26964.0
           4-DAILY        4-DAILY          167227.0   155965.0   150654.0
                          5-WEEKLY          10543.0    17819.0    21150.0
                          6-MONTHLY          2730.0     5230.0     7557.0
                          7-QUARTERLY          37.0      254.0      764.0
           5-WEEKLY       4-DAILY           10056.0    13368.0    19662.0
                          5-WEEKLY         318949.0   286230.0   263424.0
                          6-MONTHLY         35422.0    62617.0    79546.0
                          7-QUARTERLY        1417.0      661.0     1199.0
           6-MONTHLY      4-DAILY            1706.0     3376.0     6044.0
                          5-WEEKLY          32025.0    50358.0    70613.0
                          6-MONTHLY       1830794.0  1695858.0  1626689.0
                          7-QUARTERLY      153333.0   250759.0   290865.0
           7-QUARTERLY    4-DAILY               6.0       54.0      249.0
                          5-WEEKLY             29.0      410.0      270.0
                          6-MONTHLY        142808.0   231672.0   279395.0
                          7-QUARTERLY      866465.0   693524.0   581104.0

                                                                           \
run_date_y                               2025-03-31 2025-04-07 2025-04-14
run_date_x segment_x      segment_y
2025-03-03 1-HH-MONTHLY   1-HH-MONTHLY     307695.0   253187.0   224314.0
                          2-HH-QUARTERLY   363424.0   380547.0   376702.0
                          3-HH-INACTIVE       114.0    17289.0    29329.0
                          4-DAILY            1766.0     1654.0     1658.0
                          5-WEEKLY          17696.0    16740.0    17282.0
                          6-MONTHLY         76438.0    98713.0   112484.0
                          7-QUARTERLY        5947.0     3352.0     7911.0
           2-HH-QUARTERLY 1-HH-MONTHLY      89358.0   102574.0    99732.0
                          2-HH-QUARTERLY   507405.0   430810.0   370417.0
                          3-HH-INACTIVE    307064.0   354111.0   399462.0
                          4-DAILY              18.0       19.0       13.0
                          5-WEEKLY            207.0      388.0      324.0
                          6-MONTHLY         39863.0    53682.0    63321.0
                          7-QUARTERLY       21621.0    21319.0    26589.0
           3-HH-INACTIVE  1-HH-MONTHLY      11902.0        0.0    12182.0
                          2-HH-QUARTERLY   135074.0   171962.0   189133.0
                          3-HH-INACTIVE   3435788.0  3391975.0  3340907.0
                          4-DAILY             402.0      362.0      327.0
                          5-WEEKLY           1237.0      963.0      751.0
                          6-MONTHLY           731.0        0.0    12767.0
                          7-QUARTERLY       38505.0    51954.0    54058.0
           4-DAILY        4-DAILY          146105.0   142890.0   137866.0
                          5-WEEKLY          21752.0    22560.0    23745.0
                          6-MONTHLY         10075.0    12267.0    14356.0
                          7-QUARTERLY        1315.0     1838.0     2717.0
           5-WEEKLY       4-DAILY           26289.0    32019.0    36199.0
                          5-WEEKLY         241526.0   223802.0   209325.0
                          6-MONTHLY         93326.0   104163.0   113367.0
                          7-QUARTERLY        1838.0     3142.0     2976.0
           6-MONTHLY      4-DAILY            9190.0    12631.0    16142.0
                          5-WEEKLY          90767.0   107628.0   122628.0
                          6-MONTHLY       1587872.0  1512891.0  1438838.0
                          7-QUARTERLY      298996.0   314574.0   334979.0
           7-QUARTERLY    4-DAILY             668.0     1273.0     2128.0
                          5-WEEKLY            213.0     1613.0     4102.0
                          6-MONTHLY        284834.0   329140.0   348901.0
                          7-QUARTERLY      511569.0   441480.0   395681.0


run_date_y                               2025-04-21 2025-04-28 2025-05-05
run_date_x segment_x      segment_y
2025-03-03 1-HH-MONTHLY   1-HH-MONTHLY     203739.0   190597.0   173763.0
                          2-HH-QUARTERLY   367473.0   356579.0   321075.0
                          3-HH-INACTIVE     39745.0    48348.0    85938.0
                          4-DAILY            1632.0     1647.0     1655.0
                          5-WEEKLY          15277.0    14105.0    14020.0
                          6-MONTHLY        128498.0   141892.0   153390.0
                          7-QUARTERLY       11665.0    13497.0    15430.0
           2-HH-QUARTERLY 1-HH-MONTHLY      92460.0    79371.0    71876.0
                          2-HH-QUARTERLY   310042.0   256416.0   229030.0
                          3-HH-INACTIVE    449759.0   501434.0   521618.0
                          4-DAILY              24.0       70.0      144.0
                          5-WEEKLY            348.0      561.0      946.0
                          6-MONTHLY         72306.0    79552.0    89404.0
                          7-QUARTERLY       32383.0    37512.0    39582.0
           3-HH-INACTIVE  1-HH-MONTHLY      19603.0    24969.0    29840.0
                          2-HH-QUARTERLY   210197.0   225925.0   242637.0
                          3-HH-INACTIVE   3289890.0  3248140.0  3205898.0
                          4-DAILY             324.0      339.0      379.0
                          5-WEEKLY           1095.0      878.0      734.0
                          6-MONTHLY         23252.0    34500.0    45058.0
                          7-QUARTERLY       58722.0    62046.0    66023.0
           4-DAILY        4-DAILY          133012.0   129043.0   124620.0
                          5-WEEKLY          25178.0    26319.0    27450.0
                          6-MONTHLY         17037.0    20036.0    21825.0
                          7-QUARTERLY        3067.0     2985.0     3951.0
           5-WEEKLY       4-DAILY           38883.0    42052.0    44243.0
                          5-WEEKLY         196768.0   184472.0   174080.0
                          6-MONTHLY        121192.0   127759.0   130320.0
                          7-QUARTERLY        4204.0     7004.0    12161.0
           6-MONTHLY      4-DAILY           19122.0    22243.0    25292.0
                          5-WEEKLY         134385.0   143814.0   153608.0
                          6-MONTHLY       1380984.0  1337936.0  1293622.0
                          7-QUARTERLY      346318.0   351020.0   344550.0
           7-QUARTERLY    4-DAILY            3130.0     4256.0     5198.0
                          5-WEEKLY           7592.0    11827.0    14521.0
                          6-MONTHLY        358156.0   353515.0   356331.0
                          7-QUARTERLY      357624.0   331574.0   316735.0

In [30]:
df_base.groupby(['run_date', 'segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date         segment  customers
0  2025-03-03    1-HH-MONTHLY     782084
1  2025-03-03  2-HH-QUARTERLY     978043
2  2025-03-03   3-HH-INACTIVE    3651762
3  2025-03-03         4-DAILY     182416
4  2025-03-03        5-WEEKLY     370043
5  2025-03-03       6-MONTHLY    2041465
6  2025-03-03     7-QUARTERLY    1100755

## Previous Segment Stability

### taxi_regularity_segment

In [8]:
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [17]:
def get_previous_segment_customer_base(run_date):
    
    base_query = f"""
    
    select 
        run_date, 
        customer_id, 
        taxi_regularity_segment
        -- taxi_fe_regularity_segment 
    from 
        datasets.iallocator_customer_segments 
    where 
        run_date = date_format(date('{run_date}'), '%Y-%m-%d')
        and taxi_lifetime_last_ride_city = '{city_name}'
        and taxi_regularity_segment != 'UNKNOWN' 
    """
    
    df_base_query = pd.read_sql(base_query, conn3)
    df_base_query['run_date'] = run_date
    print('executed - ', run_date)

    df_base_query.to_parquet(local_path + city + '/prev_segment/prev_customer_base_{}.parquet'.format(run_date), index=False)

In [18]:
for i in run_date[3:]:
    
    print('starting - ', i)
    get_previous_segment_customer_base(i)

starting -  2025-03-24
executed -  2025-03-24
starting -  2025-03-31
executed -  2025-03-31
starting -  2025-04-07
executed -  2025-04-07
starting -  2025-04-14
executed -  2025-04-14
starting -  2025-04-21
executed -  2025-04-21
starting -  2025-04-28
executed -  2025-04-28
starting -  2025-05-05
executed -  2025-05-05

In [19]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/prev_segment'

# Get all parquet files in the folder
prev_parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

# Read and concatenate all parquet files into a single DataFrame
df_previous_segment_concat = pd.concat([pd.read_parquet(file) for file in prev_parquet_files], ignore_index=True)

In [20]:
df_previous_segment_concat.head(1)

     run_date               customer_id taxi_regularity_segment
0  2025-03-31  63621000192f9565bfe3c91a                   DAILY

In [21]:
df_previous_segment_concat.shape

(60488342, 3)

### Stability

In [22]:
df_previous_segment_concat.run_date.unique()

array(['2025-03-31', '2025-03-17', '2025-04-14', '2025-04-28',
       '2025-04-07', '2025-04-21', '2025-03-10', '2025-05-05',
       '2025-03-03', '2025-03-24'], dtype=object)

In [23]:
df_base_prev = df_previous_segment_concat[df_previous_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base_prev

           run_date               customer_id taxi_regularity_segment
0        2025-03-03  65cc9f5d107646988ca7cbfe                 MONTHLY
1        2025-03-03  5fec62a5ee2e9cf63c81f3d0                  WEEKLY
2        2025-03-03  6260f2fb2c04373d294067d4               RARE_NEED
3        2025-03-03  63d8ae8f6b21d714418dfa55                  WEEKLY
4        2025-03-03  659e4952b3bae65867b994db               RARE_NEED
...             ...                       ...                     ...
5729986  2025-03-03  66ece87d7a4c8a6141bac9a9               RARE_NEED
5729987  2025-03-03  61b2daeebd965e1f5fbcefa3               RARE_NEED
5729988  2025-03-03  6460a8f39bb65e1f9021ee64                 MONTHLY
5729989  2025-03-03  61585820c94e7965abcd3146               RARE_NEED
5729990  2025-03-03  625d223d00b5f41ac4b124c2               RARE_NEED

[5729991 rows x 3 columns]

In [24]:
df_stability_window_prev = df_previous_segment_concat[~df_previous_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window_prev

            run_date               customer_id taxi_regularity_segment
0         2025-03-10  6720a5f8b0cf4681ad13ec44               BI_WEEKLY
1         2025-03-10  61cf75d1a75746bfa8e44619               RARE_NEED
2         2025-03-10  620b355057d2b2ceeeafedf8               RARE_NEED
3         2025-03-10  64aecfb77fe9533b3ff6af57                 MONTHLY
4         2025-03-10  61b867c417dd6a10c413e7fa                  WEEKLY
...              ...                       ...                     ...
54758346  2025-05-05  66abf5a7c9ff56fcce918df4                  WEEKLY
54758347  2025-05-05  62c2718c5bce425623ae2591               RARE_NEED
54758348  2025-05-05  5e6b3350f5667d7cb3239387               RARE_NEED
54758349  2025-05-05  64d5e6e412dbf310dfa2a262               RARE_NEED
54758350  2025-05-05  66b23201ca8ed76ffd0e2939                  WEEKLY

[54758351 rows x 3 columns]

In [25]:
df_stability_window_prev.run_date.unique()

array(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
       '2025-04-07', '2025-04-14', '2025-04-21', '2025-04-28',
       '2025-05-05'], dtype=object)

In [26]:
df_merge_prev = pd.merge(df_base_prev, df_stability_window_prev, how='left', on='customer_id')
df_merge_prev

,run_date_x,customer_id,taxi_regularity_segment_x,run_date_y,taxi_regularity_segment_y
0,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-03-10,MONTHLY
1,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-03-17,MONTHLY
2,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-03-24,MONTHLY
3,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-03-31,MONTHLY
4,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-04-07,MONTHLY
...,...,...,...,...,...
50084312,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-04-07,RARE_NEED
50084313,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-04-14,RARE_NEED
50084314,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-04-21,RARE_NEED
50084315,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-04-28,RARE_NEED
50084316,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-05-05,RARE_NEED

In [27]:
df_merge_pivot_prev = df_merge_prev.groupby(['run_date_x', 'run_date_y', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y']).agg(customers=('customer_id','nunique')).reset_index()
df_merge_pivot_prev

,run_date_x,run_date_y,taxi_regularity_segment_x,taxi_regularity_segment_y,customers
0,2025-03-03,2025-03-10,BI_WEEKLY,BI_WEEKLY,756971
1,2025-03-03,2025-03-10,BI_WEEKLY,DAILY,9220
2,2025-03-03,2025-03-10,BI_WEEKLY,MONTHLY,115954
3,2025-03-03,2025-03-10,BI_WEEKLY,WEEKLY,77517
4,2025-03-03,2025-03-10,DAILY,BI_WEEKLY,5320
5,2025-03-03,2025-03-10,DAILY,DAILY,313881
6,2025-03-03,2025-03-10,DAILY,WEEKLY,14562
7,2025-03-03,2025-03-10,MONTHLY,BI_WEEKLY,109612
8,2025-03-03,2025-03-10,MONTHLY,MONTHLY,660047
9,2025-03-03,2025-03-10,MONTHLY,RARE_NEED,104682
10,2025-03-03,2025-03-10,RARE_NEED,MONTHLY,82384
11,2025-03-03,2025-03-10,RARE_NEED,RARE_NEED,2716145
12,2025-03-03,2025-03-10,WEEKLY,BI_WEEKLY,68762
13,2025-03-03,2025-03-10,WEEKLY,DAILY,18447
14,2025-03-03,2025-03-10,WEEKLY,WEEKLY,614960
15,2025-03-03,2025-03-17,BI_WEEKLY,BI_WEEKLY,633212
16,2025-03-03,2025-03-17,BI_WEEKLY,DAILY,16382
17,2025-03-03,2025-03-17,BI_WEEKLY,MONTHLY,185302
18,2025-03-03,2025-03-17,BI_WEEKLY,WEEKLY,113711
19,2025-03-03,2025-03-17,DAILY,BI_WEEKLY,9866
20,2025-03-03,2025-03-17,DAILY,DAILY,296106
21,2025-03-03,2025-03-17,DAILY,WEEKLY,23890
22,2025-03-03,2025-03-17,MONTHLY,BI_WEEKLY,153905
23,2025-03-03,2025-03-17,MONTHLY,MONTHLY,527646
24,2025-03-03,2025-03-17,MONTHLY,RARE_NEED,184614
25,2025-03-03,2025-03-17,RARE_NEED,BI_WEEKLY,16567
26,2025-03-03,2025-03-17,RARE_NEED,MONTHLY,130372
27,2025-03-03,2025-03-17,RARE_NEED,RARE_NEED,2639717
28,2025-03-03,2025-03-17,WEEKLY,BI_WEEKLY,96637
29,2025-03-03,2025-03-17,WEEKLY,DAILY,24967
30,2025-03-03,2025-03-17,WEEKLY,WEEKLY,571060
31,2025-03-03,2025-03-24,BI_WEEKLY,BI_WEEKLY,542104
32,2025-03-03,2025-03-24,BI_WEEKLY,DAILY,22193
33,2025-03-03,2025-03-24,BI_WEEKLY,MONTHLY,226933
34,2025-03-03,2025-03-24,BI_WEEKLY,RARE_NEED,9814
35,2025-03-03,2025-03-24,BI_WEEKLY,WEEKLY,141911
36,2025-03-03,2025-03-24,DAILY,BI_WEEKLY,13887
37,2025-03-03,2025-03-24,DAILY,DAILY,288264
38,2025-03-03,2025-03-24,DAILY,WEEKLY,28972
39,2025-03-03,2025-03-24,MONTHLY,BI_WEEKLY,170240
40,2025-03-03,2025-03-24,MONTHLY,DAILY,2003
41,2025-03-03,2025-03-24,MONTHLY,MONTHLY,445498
42,2025-03-03,2025-03-24,MONTHLY,RARE_NEED,238855
43,2025-03-03,2025-03-24,MONTHLY,WEEKLY,3668
44,2025-03-03,2025-03-24,RARE_NEED,BI_WEEKLY,35906
45,2025-03-03,2025-03-24,RARE_NEED,MONTHLY,156970
46,2025-03-03,2025-03-24,RARE_NEED,RARE_NEED,2583089
47,2025-03-03,2025-03-24,WEEKLY,BI_WEEKLY,118869
48,2025-03-03,2025-03-24,WEEKLY,DAILY,35355
49,2025-03-03,2025-03-24,WEEKLY,WEEKLY,537038
50,2025-03-03,2025-03-31,BI_WEEKLY,BI_WEEKLY,475335
51,2025-03-03,2025-03-31,BI_WEEKLY,DAILY,24604
52,2025-03-03,2025-03-31,BI_WEEKLY,MONTHLY,242370
53,2025-03-03,2025-03-31,BI_WEEKLY,RARE_NEED,32117
54,2025-03-03,2025-03-31,BI_WEEKLY,WEEKLY,163209
55,2025-03-03,2025-03-31,DAILY,BI_WEEKLY,16326
56,2025-03-03,2025-03-31,DAILY,DAILY,279589
57,2025-03-03,2025-03-31,DAILY,MONTHLY,1669
58,2025-03-03,2025-03-31,DAILY,WEEKLY,31796
59,2025-03-03,2025-03-31,MONTHLY,BI_WEEKLY,171199
60,2025-03-03,2025-03-31,MONTHLY,DAILY,4982
61,2025-03-03,2025-03-31,MONTHLY,MONTHLY,391421
62,2025-03-03,2025-03-31,MONTHLY,RARE_NEED,276384
63,2025-03-03,2025-03-31,MONTHLY,WEEKLY,10906
64,2025-03-03,2025-03-31,RARE_NEED,BI_WEEKLY,54151
65,2025-03-03,2025-03-31,RARE_NEED,DAILY,471
66,2025-03-03,2025-03-31,RARE_NEED,MONTHLY,175415
67,2025-03-03,2025-03-31,RARE_NEED,RARE_NEED,2535722
68,2025-03-03,2025-03-31,RARE_NEED,WEEKLY,181
69,2025-03-03,2025-03-31,WEEKLY,BI_WEEKLY,139302
70,2025-03-03,2025-03-31,WEEKLY,DAILY,43704
71,2025-03-03,2025-03-31,WEEKLY,MONTHLY,4251
72,2025-03-03,2025-03-31,WEEKLY,WEEKLY,501196
73,2025-03-03,2025-04-07,BI_WEEKLY,BI_WEEKLY,428866
74,2025-03-03,2025-04-07,BI_WEEKLY,DAILY,27004
75,2025-03-03,2025-04-07,BI_WEEKLY,MONTHLY,241981
76,2025-03-03,2025-04-07,BI_WEEKLY,RARE_NEED,60232
77,2025-03-03,2025-04-07,BI_WEEKLY,WEEKLY,175588
78,2025-03-03,2025-04-07,DAILY,BI_WEEKLY,17961
79,2025-03-03,2025-04-07,DAILY,DAILY,273912
80,2025-03-03,2025-04-07,DAILY,MONTHLY,4101
81,2025-03-03,2025-04-07,DAILY,WEEKLY,33769
82,2025-03-03,2025-04-07,MONTHLY,BI_WEEKLY,171539
83,2025-03-03,2025-04-07,MONTHLY,DAILY,6361
84,2025-03-03,2025-04-07,MONTHLY,MONTHLY,347986
85,2025-03-03,2025-04-07,MONTHLY,RARE_NEED,303686
86,2025-03-03,2025-04-07,MONTHLY,WEEKLY,20880
87,2025-03-03,2025-04-07,RARE_NEED,BI_WEEKLY,68713
88,2025-03-03,2025-04-07,RARE_NEED,DAILY,1884
89,2025-03-03,2025-04-07,RARE_NEED,MONTHLY,194300
90,2025-03-03,2025-04-07,RARE_NEED,RARE_NEED,2489196
91,2025-03-03,2025-04-07,RARE_NEED,WEEKLY,2253
92,2025-03-03,2025-04-07,WEEKLY,BI_WEEKLY,149228
93,2025-03-03,2025-04-07,WEEKLY,DAILY,53295
94,2025-03-03,2025-04-07,WEEKLY,MONTHLY,14176
95,2025-03-03,2025-04-07,WEEKLY,WEEKLY,470838
96,2025-03-03,2025-04-14,BI_WEEKLY,BI_WEEKLY,393132
97,2025-03-03,2025-04-14,BI_WEEKLY,DAILY,28978
98,2025-03-03,2025-04-14,BI_WEEKLY,MONTHLY,230501
99,2025-03-03,2025-04-14,BI_WEEKLY,RARE_NEED,88077
100,2025-03-03,2025-04-14,BI_WEEKLY,WEEKLY,188560
101,2025-03-03,2025-04-14,DAILY,BI_WEEKLY,19365
102,2025-03-03,2025-04-14,DAILY,DAILY,264704
103,2025-03-03,2025-04-14,DAILY,MONTHLY,5590
104,2025-03-03,2025-04-14,DAILY,RARE_NEED,1122
105,2025-03-03,2025-04-14,DAILY,WEEKLY,37313
106,2025-03-03,2025-04-14,MONTHLY,BI_WEEKLY,174481
107,2025-03-03,2025-04-14,MONTHLY,DAILY,7677
108,2025-03-03,2025-04-14,MONTHLY,MONTHLY,310601
109,2025-03-03,2025-04-14,MONTHLY,RARE_NEED,320948
110,2025-03-03,2025-04-14,MONTHLY,WEEKLY,31989
111,2025-03-03,2025-04-14,RARE_NEED,BI_WEEKLY,85507
112,2025-03-03,2025-04-14,RARE_NEED,DAILY,3339
113,2025-03-03,2025-04-14,RARE_NEED,MONTHLY,214276
114,2025-03-03,2025-04-14,RARE_NEED,RARE_NEED,2436068
115,2025-03-03,2025-04-14,RARE_NEED,WEEKLY,6162
116,2025-03-03,2025-04-14,WEEKLY,BI_WEEKLY,152543
117,2025-03-03,2025-04-14,WEEKLY,DAILY,61283
118,2025-03-03,2025-04-14,WEEKLY,MONTHLY,25273
119,2025-03-03,2025-04-14,WEEKLY,RARE_NEED,1225
120,2025-03-03,2025-04-14,WEEKLY,WEEKLY,444365
121,2025-03-03,2025-04-21,BI_WEEKLY,BI_WEEKLY,359376
122,2025-03-03,2025-04-21,BI_WEEKLY,DAILY,31295
123,2025-03-03,2025-04-21,BI_WEEKLY,MONTHLY,223249
124,2025-03-03,2025-04-21,BI_WEEKLY,RARE_NEED,112399
125,2025-03-03,2025-04-21,BI_WEEKLY,WEEKLY,199332
126,2025-03-03,2025-04-21,DAILY,BI_WEEKLY,20407
127,2025-03-03,2025-04-21,DAILY,DAILY,256344
128,2025-03-03,2025-04-21,DAILY,MONTHLY,6814
129,2025-03-03,2025-04-21,DAILY,RARE_NEED,2813
130,2025-03-03,2025-04-21,DAILY,WEEKLY,40758
131,2025-03-03,2025-04-21,MONTHLY,BI_WEEKLY,183350
132,2025-03-03,2025-04-21,MONTHLY,DAILY,8811
133,2025-03-03,2025-04-21,MONTHLY,MONTHLY,274487
134,2025-03-03,2025-04-21,MONTHLY,RARE_NEED,334346
135,2025-03-03,2025-04-21,MONTHLY,WEEKLY,40173
136,2025-03-03,2025-04-21,RARE_NEED,BI_WEEKLY,102099
137,2025-03-03,2025-04-21,RARE_NEED,DAILY,5000
138,2025-03-03,2025-04-21,RARE_NEED,MONTHLY,230216
139,2025-03-03,2025-04-21,RARE_NEED,RARE_NEED,2386361
140,2025-03-03,2025-04-21,RARE_NEED,WEEKLY,11470
141,2025-03-03,2025-04-21,WEEKLY,BI_WEEKLY,152578
142,2025-03-03,2025-04-21,WEEKLY,DAILY,68478
143,2025-03-03,2025-04-21,WEEKLY,MONTHLY,35127
144,2025-03-03,2025-04-21,WEEKLY,RARE_NEED,4881
145,2025-03-03,2025-04-21,WEEKLY,WEEKLY,421449
146,2025-03-03,2025-04-28,BI_WEEKLY,BI_WEEKLY,331904
147,2025-03-03,2025-04-28,BI_WEEKLY,DAILY,33506
148,2025-03-03,2025-04-28,BI_WEEKLY,MONTHLY,213533
149,2025-03-03,2025-04-28,BI_WEEKLY,RARE_NEED,141377
150,2025-03-03,2025-04-28,BI_WEEKLY,WEEKLY,202825
151,2025-03-03,2025-04-28,DAILY,BI_WEEKLY,21567
152,2025-03-03,2025-04-28,DAILY,DAILY,249051
153,2025-03-03,2025-04-28,DAILY,MONTHLY,7930
154,2025-03-03,2025-04-28,DAILY,RARE_NEED,4786
155,2025-03-03,2025-04-28,DAILY,WEEKLY,44161
156,2025-03-03,2025-04-28,MONTHLY,BI_WEEKLY,185142
157,2025-03-03,2025-04-28,MONTHLY,DAILY,9874
158,2025-03-03,2025-04-28,MONTHLY,MONTHLY,247481
159,2025-03-03,2025-04-28,MONTHLY,RARE_NEED,347979
160,2025-03-03,2025-04-28,MONTHLY,WEEKLY,47511
161,2025-03-03,2025-04-28,RARE_NEED,BI_WEEKLY,114075
162,2025-03-03,2025-04-28,RARE_NEED,DAILY,6697
163,2025-03-03,2025-04-28,RARE_NEED,MONTHLY,240197
164,2025-03-03,2025-04-28,RARE_NEED,RARE_NEED,2348315
165,2025-03-03,2025-04-28,RARE_NEED,WEEKLY,17398
166,2025-03-03,2025-04-28,WEEKLY,BI_WEEKLY,153991
167,2025-03-03,2025-04-28,WEEKLY,DAILY,75302
168,2025-03-03,2025-04-28,WEEKLY,MONTHLY,44026
169,2025-03-03,2025-04-28,WEEKLY,RARE_NEED,11023
170,2025-03-03,2025-04-28,WEEKLY,WEEKLY,398093
171,2025-03-03,2025-05-05,BI_WEEKLY,BI_WEEKLY,311443
172,2025-03-03,2025-05-05,BI_WEEKLY,DAILY,35680
173,2025-03-03,2025-05-05,BI_WEEKLY,MONTHLY,202402
174,2025-03-03,2025-05-05,BI_WEEKLY,RARE_NEED,165425
175,2025-03-03,2025-05-05,BI_WEEKLY,WEEKLY,205677
176,2025-03-03,2025-05-05,DAILY,BI_WEEKLY,22335
177,2025-03-03,2025-05-05,DAILY,DAILY,241002
178,2025-03-03,2025-05-05,DAILY,MONTHLY,8785
179,2025-03-03,2025-05-05,DAILY,RARE_NEED,6973
180,2025-03-03,2025-05-05,DAILY,WEEKLY,47672
181,2025-03-03,2025-05-05,MONTHLY,BI_WEEKLY,185956
182,2025-03-03,2025-05-05,MONTHLY,DAILY,11064
183,2025-03-03,2025-05-05,MONTHLY,MONTHLY,227791
184,2025-03-03,2025-05-05,MONTHLY,RARE_NEED,354967
185,2025-03-03,2025-05-05,MONTHLY,WEEKLY,55302
186,2025-03-03,2025-05-05,RARE_NEED,BI_WEEKLY,127447
187,2025-03-03,2025-05-05,RARE_NEED,DAILY,8424
188,2025-03-03,2025-05-05,RARE_NEED,MONTHLY,247738
189,2025-03-03,2025-05-05,RARE_NEED,RARE_NEED,2310661
190,2025-03-03,2025-05-05,RARE_NEED,WEEKLY,24038
191,2025-03-03,2025-05-05,WEEKLY,BI_WEEKLY,152760
192,2025-03-03,2025-05-05,WEEKLY,DAILY,81182
193,2025-03-03,2025-05-05,WEEKLY,MONTHLY,50413
194,2025-03-03,2025-05-05,WEEKLY,RARE_NEED,18989
195,2025-03-03,2025-05-05,WEEKLY,WEEKLY,378100

In [28]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                                                customers  \
run_date_y                                                     2025-03-10
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   756971.0
                                     DAILY                         9220.0
                                     MONTHLY                     115954.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       77517.0
           DAILY                     BI_WEEKLY                     5320.0
                                     DAILY                       313881.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       14562.0
           MONTHLY                   BI_WEEKLY                   109612.0
                                     DAILY                            0.0
                                     MONTHLY                     660047.0
                                     RARE_NEED                   104682.0
                                     WEEKLY                           0.0
           RARE_NEED                 BI_WEEKLY                        0.0
                                     DAILY                            0.0
                                     MONTHLY                      82384.0
                                     RARE_NEED                  2716145.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                    68762.0
                                     DAILY                        18447.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      614960.0

                                                                           \
run_date_y                                                     2025-03-17
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   633212.0
                                     DAILY                        16382.0
                                     MONTHLY                     185302.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      113711.0
           DAILY                     BI_WEEKLY                     9866.0
                                     DAILY                       296106.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       23890.0
           MONTHLY                   BI_WEEKLY                   153905.0
                                     DAILY                            0.0
                                     MONTHLY                     527646.0
                                     RARE_NEED                   184614.0
                                     WEEKLY                           0.0
           RARE_NEED                 BI_WEEKLY                    16567.0
                                     DAILY                            0.0
                                     MONTHLY                     130372.0
                                     RARE_NEED                  2639717.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                    96637.0
                                     DAILY                        24967.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      571060.0

                                                                           \
run_date_y                                                     2025-03-24
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   542104.0
                                     DAILY                        22193.0
                                     MONTHLY                     226933.0
                                     RARE_NEED                     9814.0
                                     WEEKLY                      141911.0
           DAILY                     BI_WEEKLY                    13887.0
                                     DAILY                       288264.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       28972.0
           MONTHLY                   BI_WEEKLY                   170240.0
                                     DAILY                         2003.0
                                     MONTHLY                     445498.0
                                     RARE_NEED                   238855.0
                                     WEEKLY                        3668.0
           RARE_NEED                 BI_WEEKLY                    35906.0
                                     DAILY                            0.0
                                     MONTHLY                     156970.0
                                     RARE_NEED                  2583089.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                   118869.0
                                     DAILY                        35355.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      537038.0

                                                                           \
run_date_y                                                     2025-03-31
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   475335.0
                                     DAILY                        24604.0
                                     MONTHLY                     242370.0
                                     RARE_NEED                    32117.0
                                     WEEKLY                      163209.0
           DAILY                     BI_WEEKLY                    16326.0
                                     DAILY                       279589.0
                                     MONTHLY                       1669.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       31796.0
           MONTHLY                   BI_WEEKLY                   171199.0
                                     DAILY                         4982.0
                                     MONTHLY                     391421.0
                                     RARE_NEED                   276384.0
                                     WEEKLY                       10906.0
           RARE_NEED                 BI_WEEKLY                    54151.0
                                     DAILY                          471.0
                                     MONTHLY                     175415.0
                                     RARE_NEED                  2535722.0
                                     WEEKLY                         181.0
           WEEKLY                    BI_WEEKLY                   139302.0
                                     DAILY                        43704.0
                                     MONTHLY                       4251.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      501196.0

                                                                           \
run_date_y                                                     2025-04-07
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   428866.0
                                     DAILY                        27004.0
                                     MONTHLY                     241981.0
                                     RARE_NEED                    60232.0
                                     WEEKLY                      175588.0
           DAILY                     BI_WEEKLY                    17961.0
                                     DAILY                       273912.0
                                     MONTHLY                       4101.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       33769.0
           MONTHLY                   BI_WEEKLY                   171539.0
                                     DAILY                         6361.0
                                     MONTHLY                     347986.0
                                     RARE_NEED                   303686.0
                                     WEEKLY                       20880.0
           RARE_NEED                 BI_WEEKLY                    68713.0
                                     DAILY                         1884.0
                                     MONTHLY                     194300.0
                                     RARE_NEED                  2489196.0
                                     WEEKLY                        2253.0
           WEEKLY                    BI_WEEKLY                   149228.0
                                     DAILY                        53295.0
                                     MONTHLY                      14176.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      470838.0

                                                                           \
run_date_y                                                     2025-04-14
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   393132.0
                                     DAILY                        28978.0
                                     MONTHLY                     230501.0
                                     RARE_NEED                    88077.0
                                     WEEKLY                      188560.0
           DAILY                     BI_WEEKLY                    19365.0
                                     DAILY                       264704.0
                                     MONTHLY                       5590.0
                                     RARE_NEED                     1122.0
                                     WEEKLY                       37313.0
           MONTHLY                   BI_WEEKLY                   174481.0
                                     DAILY                         7677.0
                                     MONTHLY                     310601.0
                                     RARE_NEED                   320948.0
                                     WEEKLY                       31989.0
           RARE_NEED                 BI_WEEKLY                    85507.0
                                     DAILY                         3339.0
                                     MONTHLY                     214276.0
                                     RARE_NEED                  2436068.0
                                     WEEKLY                        6162.0
           WEEKLY                    BI_WEEKLY                   152543.0
                                     DAILY                        61283.0
                                     MONTHLY                      25273.0
                                     RARE_NEED                     1225.0
                                     WEEKLY                      444365.0

                                                                           \
run_date_y                                                     2025-04-21
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   359376.0
                                     DAILY                        31295.0
                                     MONTHLY                     223249.0
                                     RARE_NEED                   112399.0
                                     WEEKLY                      199332.0
           DAILY                     BI_WEEKLY                    20407.0
                                     DAILY                       256344.0
                                     MONTHLY                       6814.0
                                     RARE_NEED                     2813.0
                                     WEEKLY                       40758.0
           MONTHLY                   BI_WEEKLY                   183350.0
                                     DAILY                         8811.0
                                     MONTHLY                     274487.0
                                     RARE_NEED                   334346.0
                                     WEEKLY                       40173.0
           RARE_NEED                 BI_WEEKLY                   102099.0
                                     DAILY                         5000.0
                                     MONTHLY                     230216.0
                                     RARE_NEED                  2386361.0
                                     WEEKLY                       11470.0
           WEEKLY                    BI_WEEKLY                   152578.0
                                     DAILY                        68478.0
                                     MONTHLY                      35127.0
                                     RARE_NEED                     4881.0
                                     WEEKLY                      421449.0

                                                                           \
run_date_y                                                     2025-04-28
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   331904.0
                                     DAILY                        33506.0
                                     MONTHLY                     213533.0
                                     RARE_NEED                   141377.0
                                     WEEKLY                      202825.0
           DAILY                     BI_WEEKLY                    21567.0
                                     DAILY                       249051.0
                                     MONTHLY                       7930.0
                                     RARE_NEED                     4786.0
                                     WEEKLY                       44161.0
           MONTHLY                   BI_WEEKLY                   185142.0
                                     DAILY                         9874.0
                                     MONTHLY                     247481.0
                                     RARE_NEED                   347979.0
                                     WEEKLY                       47511.0
           RARE_NEED                 BI_WEEKLY                   114075.0
                                     DAILY                         6697.0
                                     MONTHLY                     240197.0
                                     RARE_NEED                  2348315.0
                                     WEEKLY                       17398.0
           WEEKLY                    BI_WEEKLY                   153991.0
                                     DAILY                        75302.0
                                     MONTHLY                      44026.0
                                     RARE_NEED                    11023.0
                                     WEEKLY                      398093.0


run_date_y                                                     2025-05-05
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   311443.0
                                     DAILY                        35680.0
                                     MONTHLY                     202402.0
                                     RARE_NEED                   165425.0
                                     WEEKLY                      205677.0
           DAILY                     BI_WEEKLY                    22335.0
                                     DAILY                       241002.0
                                     MONTHLY                       8785.0
                                     RARE_NEED                     6973.0
                                     WEEKLY                       47672.0
           MONTHLY                   BI_WEEKLY                   185956.0
                                     DAILY                        11064.0
                                     MONTHLY                     227791.0
                                     RARE_NEED                   354967.0
                                     WEEKLY                       55302.0
           RARE_NEED                 BI_WEEKLY                   127447.0
                                     DAILY                         8424.0
                                     MONTHLY                     247738.0
                                     RARE_NEED                  2310661.0
                                     WEEKLY                       24038.0
           WEEKLY                    BI_WEEKLY                   152760.0
                                     DAILY                        81182.0
                                     MONTHLY                      50413.0
                                     RARE_NEED                    18989.0
                                     WEEKLY                      378100.0

In [91]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0).to_clipboard(index=False)

In [30]:
df_base_prev.groupby(['run_date', 'taxi_regularity_segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date taxi_regularity_segment  customers
0  2025-03-03               BI_WEEKLY     974871
1  2025-03-03                   DAILY     340655
2  2025-03-03                 MONTHLY     884696
3  2025-03-03               RARE_NEED    2812984
4  2025-03-03                  WEEKLY     716785

### FE Regularity

In [31]:
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [34]:
def get_previous_segment_customer_base(run_date):
    
    base_query = f"""
    
    select 
        run_date, 
        customer_id, 
        -- taxi_regularity_segment
        taxi_fe_regularity_segment 
    from 
        datasets.iallocator_customer_segments 
    where 
        run_date = date_format(date('{run_date}'), '%Y-%m-%d')
        and taxi_lifetime_last_ride_city = '{city_name}'
        and taxi_fe_regularity_segment != 'UNKNOWN' 
    """
    
    df_base_query = pd.read_sql(base_query, conn3)
    df_base_query['run_date'] = run_date
    print('executed - ', run_date)

    df_base_query.to_parquet(local_path + city + '/prev_segment2/prev_customer_base_{}.parquet'.format(run_date), index=False)

In [ ]:
for i in run_date:
    
    print('starting - ', i)
    get_previous_segment_customer_base(i)

starting -  2025-03-03
executed -  2025-03-03
starting -  2025-03-10
executed -  2025-03-10
starting -  2025-03-17
executed -  2025-03-17
starting -  2025-03-24

In [28]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/prev_segment2'

# Get all parquet files in the folder
prev_parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

# Read and concatenate all parquet files into a single DataFrame
df_previous_segment_concat = pd.concat([pd.read_parquet(file) for file in prev_parquet_files], ignore_index=True)

In [29]:
df_previous_segment_concat.head(1)

     run_date               customer_id taxi_fe_regularity_segment
0  2025-03-31  6474a5c8694393cc7e442e77                      DAILY

In [30]:
df_previous_segment_concat.shape

(35532535, 3)

### Stability

In [31]:
df_previous_segment_concat.run_date.unique()

array(['2025-03-31', '2025-03-17', '2025-04-14', '2025-04-28',
       '2025-04-07', '2025-04-21', '2025-03-10', '2025-05-05',
       '2025-03-03', '2025-03-24'], dtype=object)

In [32]:
df_base_prev = df_previous_segment_concat[df_previous_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base_prev

           run_date               customer_id taxi_fe_regularity_segment
0        2025-03-03  64e70e90be1489e998c46848                  BI_WEEKLY
1        2025-03-03  61dbe366fb8e4d610931ab58                  BI_WEEKLY
2        2025-03-03  661a4d851f79f98055656dc3                    MONTHLY
3        2025-03-03  5e33d682c725ca6c303e47e2                  RARE_NEED
4        2025-03-03  61619a34aa0ecd1f9713558f                  BI_WEEKLY
...             ...                       ...                        ...
3448101  2025-03-03  65d0a2f26e764329106ed317                    MONTHLY
3448102  2025-03-03  66384d8d5b3860598dc602e1                  BI_WEEKLY
3448103  2025-03-03  5d844ff1af794421566a1ef1                     WEEKLY
3448104  2025-03-03  6585c70a1093bb34fc3a09a0                     WEEKLY
3448105  2025-03-03  61e5682e93bdd008c8df9947                  BI_WEEKLY

[3448106 rows x 3 columns]

In [33]:
df_stability_window_prev = df_previous_segment_concat[~df_previous_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window_prev

            run_date               customer_id taxi_fe_regularity_segment
0         2025-03-10  5abdecea25abd634611d51aa                    MONTHLY
1         2025-03-10  62a735f41420e29d95401dc1                    MONTHLY
2         2025-03-10  67aa9d57fe551003ad9fe5d9                    MONTHLY
3         2025-03-10  67c341027c3ccf7a49876869                  RARE_NEED
4         2025-03-10  6730dedc8ea7d581ee78aa92                  BI_WEEKLY
...              ...                       ...                        ...
32084424  2025-05-05  67e38cabd25c76821790bfd1                  RARE_NEED
32084425  2025-05-05  6583d607cfe5392da9d31334                     WEEKLY
32084426  2025-05-05  639b49dbd79523ee6cce4771                     WEEKLY
32084427  2025-05-05  647dd4970b7c4a5f730081c2                  RARE_NEED
32084428  2025-05-05  65d16d826e76437e0a8f22c8                     WEEKLY

[32084429 rows x 3 columns]

In [34]:
df_stability_window_prev.run_date.unique()

array(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
       '2025-04-07', '2025-04-14', '2025-04-21', '2025-04-28',
       '2025-05-05'], dtype=object)

In [35]:
df_merge_prev = pd.merge(df_base_prev, df_stability_window_prev, how='left', on='customer_id')
df_merge_prev

,run_date_x,customer_id,taxi_fe_regularity_segment_x,run_date_y,taxi_fe_regularity_segment_y
0,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-03-10,BI_WEEKLY
1,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-03-17,BI_WEEKLY
2,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-03-24,BI_WEEKLY
3,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-03-31,MONTHLY
4,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-04-07,MONTHLY
...,...,...,...,...,...
26076936,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-04-07,BI_WEEKLY
26076937,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-04-14,MONTHLY
26076938,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-04-21,MONTHLY
26076939,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-04-28,MONTHLY
26076940,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-05-05,MONTHLY

In [36]:
df_merge_pivot_prev = df_merge_prev.groupby(['run_date_x', 'run_date_y', 'taxi_fe_regularity_segment_x', 'taxi_fe_regularity_segment_y']).agg(customers=('customer_id','nunique')).reset_index()
df_merge_pivot_prev

,run_date_x,run_date_y,taxi_fe_regularity_segment_x,taxi_fe_regularity_segment_y,customers
0,2025-03-03,2025-03-10,BI_WEEKLY,BI_WEEKLY,852070
1,2025-03-03,2025-03-10,BI_WEEKLY,DAILY,9595
2,2025-03-03,2025-03-10,BI_WEEKLY,MONTHLY,119637
3,2025-03-03,2025-03-10,BI_WEEKLY,WEEKLY,55537
4,2025-03-03,2025-03-10,DAILY,BI_WEEKLY,6707
5,2025-03-03,2025-03-10,DAILY,DAILY,263169
6,2025-03-03,2025-03-10,DAILY,WEEKLY,14437
7,2025-03-03,2025-03-10,MONTHLY,BI_WEEKLY,119766
8,2025-03-03,2025-03-10,MONTHLY,MONTHLY,782052
9,2025-03-03,2025-03-10,MONTHLY,RARE_NEED,101823
10,2025-03-03,2025-03-10,RARE_NEED,MONTHLY,68392
11,2025-03-03,2025-03-10,RARE_NEED,RARE_NEED,425258
12,2025-03-03,2025-03-10,WEEKLY,BI_WEEKLY,55659
13,2025-03-03,2025-03-10,WEEKLY,DAILY,13805
14,2025-03-03,2025-03-10,WEEKLY,WEEKLY,380275
15,2025-03-03,2025-03-17,BI_WEEKLY,BI_WEEKLY,744171
16,2025-03-03,2025-03-17,BI_WEEKLY,DAILY,17325
17,2025-03-03,2025-03-17,BI_WEEKLY,MONTHLY,179325
18,2025-03-03,2025-03-17,BI_WEEKLY,WEEKLY,84522
19,2025-03-03,2025-03-17,DAILY,BI_WEEKLY,11878
20,2025-03-03,2025-03-17,DAILY,DAILY,247903
21,2025-03-03,2025-03-17,DAILY,WEEKLY,22008
22,2025-03-03,2025-03-17,MONTHLY,BI_WEEKLY,180067
23,2025-03-03,2025-03-17,MONTHLY,MONTHLY,621075
24,2025-03-03,2025-03-17,MONTHLY,RARE_NEED,153928
25,2025-03-03,2025-03-17,RARE_NEED,BI_WEEKLY,486
26,2025-03-03,2025-03-17,RARE_NEED,MONTHLY,98306
27,2025-03-03,2025-03-17,RARE_NEED,RARE_NEED,323727
28,2025-03-03,2025-03-17,WEEKLY,BI_WEEKLY,80343
29,2025-03-03,2025-03-17,WEEKLY,DAILY,20732
30,2025-03-03,2025-03-17,WEEKLY,WEEKLY,343519
31,2025-03-03,2025-03-24,BI_WEEKLY,BI_WEEKLY,655737
32,2025-03-03,2025-03-24,BI_WEEKLY,DAILY,25653
33,2025-03-03,2025-03-24,BI_WEEKLY,MONTHLY,222233
34,2025-03-03,2025-03-24,BI_WEEKLY,RARE_NEED,2730
35,2025-03-03,2025-03-24,BI_WEEKLY,WEEKLY,111079
36,2025-03-03,2025-03-24,DAILY,BI_WEEKLY,16592
37,2025-03-03,2025-03-24,DAILY,DAILY,239289
38,2025-03-03,2025-03-24,DAILY,WEEKLY,25985
39,2025-03-03,2025-03-24,MONTHLY,BI_WEEKLY,216432
40,2025-03-03,2025-03-24,MONTHLY,MONTHLY,512813
41,2025-03-03,2025-03-24,MONTHLY,RARE_NEED,181942
42,2025-03-03,2025-03-24,RARE_NEED,BI_WEEKLY,11882
43,2025-03-03,2025-03-24,RARE_NEED,MONTHLY,103174
44,2025-03-03,2025-03-24,RARE_NEED,RARE_NEED,265095
45,2025-03-03,2025-03-24,WEEKLY,BI_WEEKLY,97553
46,2025-03-03,2025-03-24,WEEKLY,DAILY,27889
47,2025-03-03,2025-03-24,WEEKLY,WEEKLY,317392
48,2025-03-03,2025-03-31,BI_WEEKLY,BI_WEEKLY,582524
49,2025-03-03,2025-03-31,BI_WEEKLY,DAILY,28262
50,2025-03-03,2025-03-31,BI_WEEKLY,MONTHLY,250545
51,2025-03-03,2025-03-31,BI_WEEKLY,RARE_NEED,16026
52,2025-03-03,2025-03-31,BI_WEEKLY,WEEKLY,128975
53,2025-03-03,2025-03-31,DAILY,BI_WEEKLY,20267
54,2025-03-03,2025-03-31,DAILY,DAILY,228773
55,2025-03-03,2025-03-31,DAILY,MONTHLY,1178
56,2025-03-03,2025-03-31,DAILY,WEEKLY,28900
57,2025-03-03,2025-03-31,MONTHLY,BI_WEEKLY,230360
58,2025-03-03,2025-03-31,MONTHLY,DAILY,3243
59,2025-03-03,2025-03-31,MONTHLY,MONTHLY,441977
60,2025-03-03,2025-03-31,MONTHLY,RARE_NEED,188610
61,2025-03-03,2025-03-31,MONTHLY,WEEKLY,4478
62,2025-03-03,2025-03-31,RARE_NEED,BI_WEEKLY,22335
63,2025-03-03,2025-03-31,RARE_NEED,MONTHLY,101601
64,2025-03-03,2025-03-31,RARE_NEED,RARE_NEED,226334
65,2025-03-03,2025-03-31,WEEKLY,BI_WEEKLY,114646
66,2025-03-03,2025-03-31,WEEKLY,DAILY,30864
67,2025-03-03,2025-03-31,WEEKLY,MONTHLY,1645
68,2025-03-03,2025-03-31,WEEKLY,WEEKLY,291856
69,2025-03-03,2025-04-07,BI_WEEKLY,BI_WEEKLY,528297
70,2025-03-03,2025-04-07,BI_WEEKLY,DAILY,31274
71,2025-03-03,2025-04-07,BI_WEEKLY,MONTHLY,256991
72,2025-03-03,2025-04-07,BI_WEEKLY,RARE_NEED,34138
73,2025-03-03,2025-04-07,BI_WEEKLY,WEEKLY,144627
74,2025-03-03,2025-04-07,DAILY,BI_WEEKLY,23128
75,2025-03-03,2025-04-07,DAILY,DAILY,222271
76,2025-03-03,2025-04-07,DAILY,MONTHLY,3229
77,2025-03-03,2025-04-07,DAILY,WEEKLY,31285
78,2025-03-03,2025-04-07,MONTHLY,BI_WEEKLY,234551
79,2025-03-03,2025-04-07,MONTHLY,DAILY,7067
80,2025-03-03,2025-04-07,MONTHLY,MONTHLY,390350
81,2025-03-03,2025-04-07,MONTHLY,RARE_NEED,183908
82,2025-03-03,2025-04-07,MONTHLY,WEEKLY,11991
83,2025-03-03,2025-04-07,RARE_NEED,BI_WEEKLY,32367
84,2025-03-03,2025-04-07,RARE_NEED,MONTHLY,101605
85,2025-03-03,2025-04-07,RARE_NEED,RARE_NEED,192834
86,2025-03-03,2025-04-07,WEEKLY,BI_WEEKLY,126065
87,2025-03-03,2025-04-07,WEEKLY,DAILY,35635
88,2025-03-03,2025-04-07,WEEKLY,MONTHLY,7345
89,2025-03-03,2025-04-07,WEEKLY,WEEKLY,269576
90,2025-03-03,2025-04-14,BI_WEEKLY,BI_WEEKLY,485892
91,2025-03-03,2025-04-14,BI_WEEKLY,DAILY,32179
92,2025-03-03,2025-04-14,BI_WEEKLY,MONTHLY,254509
93,2025-03-03,2025-04-14,BI_WEEKLY,RARE_NEED,52716
94,2025-03-03,2025-04-14,BI_WEEKLY,WEEKLY,152538
95,2025-03-03,2025-04-14,DAILY,BI_WEEKLY,25772
96,2025-03-03,2025-04-14,DAILY,DAILY,211433
97,2025-03-03,2025-04-14,DAILY,MONTHLY,5582
98,2025-03-03,2025-04-14,DAILY,WEEKLY,35183
99,2025-03-03,2025-04-14,MONTHLY,BI_WEEKLY,235612
100,2025-03-03,2025-04-14,MONTHLY,DAILY,8480
101,2025-03-03,2025-04-14,MONTHLY,MONTHLY,352557
102,2025-03-03,2025-04-14,MONTHLY,RARE_NEED,173342
103,2025-03-03,2025-04-14,MONTHLY,WEEKLY,18814
104,2025-03-03,2025-04-14,RARE_NEED,BI_WEEKLY,38313
105,2025-03-03,2025-04-14,RARE_NEED,DAILY,1576
106,2025-03-03,2025-04-14,RARE_NEED,MONTHLY,100814
107,2025-03-03,2025-04-14,RARE_NEED,RARE_NEED,164704
108,2025-03-03,2025-04-14,RARE_NEED,WEEKLY,1272
109,2025-03-03,2025-04-14,WEEKLY,BI_WEEKLY,133117
110,2025-03-03,2025-04-14,WEEKLY,DAILY,37384
111,2025-03-03,2025-04-14,WEEKLY,MONTHLY,15285
112,2025-03-03,2025-04-14,WEEKLY,WEEKLY,250255
113,2025-03-03,2025-04-21,BI_WEEKLY,BI_WEEKLY,452749
114,2025-03-03,2025-04-21,BI_WEEKLY,DAILY,34422
115,2025-03-03,2025-04-21,BI_WEEKLY,MONTHLY,244691
116,2025-03-03,2025-04-21,BI_WEEKLY,RARE_NEED,64766
117,2025-03-03,2025-04-21,BI_WEEKLY,WEEKLY,159504
118,2025-03-03,2025-04-21,DAILY,BI_WEEKLY,27675
119,2025-03-03,2025-04-21,DAILY,DAILY,203220
120,2025-03-03,2025-04-21,DAILY,MONTHLY,7461
121,2025-03-03,2025-04-21,DAILY,RARE_NEED,852
122,2025-03-03,2025-04-21,DAILY,WEEKLY,36650
123,2025-03-03,2025-04-21,MONTHLY,BI_WEEKLY,239042
124,2025-03-03,2025-04-21,MONTHLY,DAILY,9762
125,2025-03-03,2025-04-21,MONTHLY,MONTHLY,322278
126,2025-03-03,2025-04-21,MONTHLY,RARE_NEED,159353
127,2025-03-03,2025-04-21,MONTHLY,WEEKLY,27180
128,2025-03-03,2025-04-21,RARE_NEED,BI_WEEKLY,43981
129,2025-03-03,2025-04-21,RARE_NEED,DAILY,2740
130,2025-03-03,2025-04-21,RARE_NEED,MONTHLY,100215
131,2025-03-03,2025-04-21,RARE_NEED,RARE_NEED,141443
132,2025-03-03,2025-04-21,RARE_NEED,WEEKLY,3053
133,2025-03-03,2025-04-21,WEEKLY,BI_WEEKLY,134946
134,2025-03-03,2025-04-21,WEEKLY,DAILY,42050
135,2025-03-03,2025-04-21,WEEKLY,MONTHLY,22742
136,2025-03-03,2025-04-21,WEEKLY,RARE_NEED,948
137,2025-03-03,2025-04-21,WEEKLY,WEEKLY,232252
138,2025-03-03,2025-04-28,BI_WEEKLY,BI_WEEKLY,424435
139,2025-03-03,2025-04-28,BI_WEEKLY,DAILY,36452
140,2025-03-03,2025-04-28,BI_WEEKLY,MONTHLY,238639
141,2025-03-03,2025-04-28,BI_WEEKLY,RARE_NEED,73327
142,2025-03-03,2025-04-28,BI_WEEKLY,WEEKLY,160893
143,2025-03-03,2025-04-28,DAILY,BI_WEEKLY,30057
144,2025-03-03,2025-04-28,DAILY,DAILY,195829
145,2025-03-03,2025-04-28,DAILY,MONTHLY,8748
146,2025-03-03,2025-04-28,DAILY,RARE_NEED,2326
147,2025-03-03,2025-04-28,DAILY,WEEKLY,38890
148,2025-03-03,2025-04-28,MONTHLY,BI_WEEKLY,235073
149,2025-03-03,2025-04-28,MONTHLY,DAILY,10782
150,2025-03-03,2025-04-28,MONTHLY,MONTHLY,297850
151,2025-03-03,2025-04-28,MONTHLY,RARE_NEED,151518
152,2025-03-03,2025-04-28,MONTHLY,WEEKLY,34006
153,2025-03-03,2025-04-28,RARE_NEED,BI_WEEKLY,48624
154,2025-03-03,2025-04-28,RARE_NEED,DAILY,3197
155,2025-03-03,2025-04-28,RARE_NEED,MONTHLY,98413
156,2025-03-03,2025-04-28,RARE_NEED,RARE_NEED,122353
157,2025-03-03,2025-04-28,RARE_NEED,WEEKLY,4213
158,2025-03-03,2025-04-28,WEEKLY,BI_WEEKLY,138251
159,2025-03-03,2025-04-28,WEEKLY,DAILY,45192
160,2025-03-03,2025-04-28,WEEKLY,MONTHLY,29671
161,2025-03-03,2025-04-28,WEEKLY,RARE_NEED,3447
162,2025-03-03,2025-04-28,WEEKLY,WEEKLY,215366
163,2025-03-03,2025-05-05,BI_WEEKLY,BI_WEEKLY,402389
164,2025-03-03,2025-05-05,BI_WEEKLY,DAILY,38183
165,2025-03-03,2025-05-05,BI_WEEKLY,MONTHLY,228792
166,2025-03-03,2025-05-05,BI_WEEKLY,RARE_NEED,75978
167,2025-03-03,2025-05-05,BI_WEEKLY,WEEKLY,163940
168,2025-03-03,2025-05-05,DAILY,BI_WEEKLY,31924
169,2025-03-03,2025-05-05,DAILY,DAILY,187191
170,2025-03-03,2025-05-05,DAILY,MONTHLY,9797
171,2025-03-03,2025-05-05,DAILY,RARE_NEED,3582
172,2025-03-03,2025-05-05,DAILY,WEEKLY,41148
173,2025-03-03,2025-05-05,MONTHLY,BI_WEEKLY,235715
174,2025-03-03,2025-05-05,MONTHLY,DAILY,11868
175,2025-03-03,2025-05-05,MONTHLY,MONTHLY,278407
176,2025-03-03,2025-05-05,MONTHLY,RARE_NEED,139189
177,2025-03-03,2025-05-05,MONTHLY,WEEKLY,40623
178,2025-03-03,2025-05-05,RARE_NEED,BI_WEEKLY,53090
179,2025-03-03,2025-05-05,RARE_NEED,DAILY,3652
180,2025-03-03,2025-05-05,RARE_NEED,MONTHLY,96969
181,2025-03-03,2025-05-05,RARE_NEED,RARE_NEED,106161
182,2025-03-03,2025-05-05,RARE_NEED,WEEKLY,6320
183,2025-03-03,2025-05-05,WEEKLY,BI_WEEKLY,137471
184,2025-03-03,2025-05-05,WEEKLY,DAILY,48310
185,2025-03-03,2025-05-05,WEEKLY,MONTHLY,33910
186,2025-03-03,2025-05-05,WEEKLY,RARE_NEED,6916
187,2025-03-03,2025-05-05,WEEKLY,WEEKLY,202078

In [37]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_fe_regularity_segment_x', 'taxi_fe_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                                                      customers  \
run_date_y                                                           2025-03-10
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      852070.0
                                        DAILY                            9595.0
                                        MONTHLY                        119637.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          55537.0
           DAILY                        BI_WEEKLY                        6707.0
                                        DAILY                          263169.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          14437.0
           MONTHLY                      BI_WEEKLY                      119766.0
                                        DAILY                               0.0
                                        MONTHLY                        782052.0
                                        RARE_NEED                      101823.0
                                        WEEKLY                              0.0
           RARE_NEED                    BI_WEEKLY                           0.0
                                        DAILY                               0.0
                                        MONTHLY                         68392.0
                                        RARE_NEED                      425258.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                       55659.0
                                        DAILY                           13805.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         380275.0

                                                                                 \
run_date_y                                                           2025-03-17
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      744171.0
                                        DAILY                           17325.0
                                        MONTHLY                        179325.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          84522.0
           DAILY                        BI_WEEKLY                       11878.0
                                        DAILY                          247903.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          22008.0
           MONTHLY                      BI_WEEKLY                      180067.0
                                        DAILY                               0.0
                                        MONTHLY                        621075.0
                                        RARE_NEED                      153928.0
                                        WEEKLY                              0.0
           RARE_NEED                    BI_WEEKLY                         486.0
                                        DAILY                               0.0
                                        MONTHLY                         98306.0
                                        RARE_NEED                      323727.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                       80343.0
                                        DAILY                           20732.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         343519.0

                                                                                 \
run_date_y                                                           2025-03-24
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      655737.0
                                        DAILY                           25653.0
                                        MONTHLY                        222233.0
                                        RARE_NEED                        2730.0
                                        WEEKLY                         111079.0
           DAILY                        BI_WEEKLY                       16592.0
                                        DAILY                          239289.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          25985.0
           MONTHLY                      BI_WEEKLY                      216432.0
                                        DAILY                               0.0
                                        MONTHLY                        512813.0
                                        RARE_NEED                      181942.0
                                        WEEKLY                              0.0
           RARE_NEED                    BI_WEEKLY                       11882.0
                                        DAILY                               0.0
                                        MONTHLY                        103174.0
                                        RARE_NEED                      265095.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                       97553.0
                                        DAILY                           27889.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         317392.0

                                                                                 \
run_date_y                                                           2025-03-31
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      582524.0
                                        DAILY                           28262.0
                                        MONTHLY                        250545.0
                                        RARE_NEED                       16026.0
                                        WEEKLY                         128975.0
           DAILY                        BI_WEEKLY                       20267.0
                                        DAILY                          228773.0
                                        MONTHLY                          1178.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          28900.0
           MONTHLY                      BI_WEEKLY                      230360.0
                                        DAILY                            3243.0
                                        MONTHLY                        441977.0
                                        RARE_NEED                      188610.0
                                        WEEKLY                           4478.0
           RARE_NEED                    BI_WEEKLY                       22335.0
                                        DAILY                               0.0
                                        MONTHLY                        101601.0
                                        RARE_NEED                      226334.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                      114646.0
                                        DAILY                           30864.0
                                        MONTHLY                          1645.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         291856.0

                                                                                 \
run_date_y                                                           2025-04-07
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      528297.0
                                        DAILY                           31274.0
                                        MONTHLY                        256991.0
                                        RARE_NEED                       34138.0
                                        WEEKLY                         144627.0
           DAILY                        BI_WEEKLY                       23128.0
                                        DAILY                          222271.0
                                        MONTHLY                          3229.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          31285.0
           MONTHLY                      BI_WEEKLY                      234551.0
                                        DAILY                            7067.0
                                        MONTHLY                        390350.0
                                        RARE_NEED                      183908.0
                                        WEEKLY                          11991.0
           RARE_NEED                    BI_WEEKLY                       32367.0
                                        DAILY                               0.0
                                        MONTHLY                        101605.0
                                        RARE_NEED                      192834.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                      126065.0
                                        DAILY                           35635.0
                                        MONTHLY                          7345.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         269576.0

                                                                                 \
run_date_y                                                           2025-04-14
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      485892.0
                                        DAILY                           32179.0
                                        MONTHLY                        254509.0
                                        RARE_NEED                       52716.0
                                        WEEKLY                         152538.0
           DAILY                        BI_WEEKLY                       25772.0
                                        DAILY                          211433.0
                                        MONTHLY                          5582.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          35183.0
           MONTHLY                      BI_WEEKLY                      235612.0
                                        DAILY                            8480.0
                                        MONTHLY                        352557.0
                                        RARE_NEED                      173342.0
                                        WEEKLY                          18814.0
           RARE_NEED                    BI_WEEKLY                       38313.0
                                        DAILY                            1576.0
                                        MONTHLY                        100814.0
                                        RARE_NEED                      164704.0
                                        WEEKLY                           1272.0
           WEEKLY                       BI_WEEKLY                      133117.0
                                        DAILY                           37384.0
                                        MONTHLY                         15285.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         250255.0

                                                                                 \
run_date_y                                                           2025-04-21
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      452749.0
                                        DAILY                           34422.0
                                        MONTHLY                        244691.0
                                        RARE_NEED                       64766.0
                                        WEEKLY                         159504.0
           DAILY                        BI_WEEKLY                       27675.0
                                        DAILY                          203220.0
                                        MONTHLY                          7461.0
                                        RARE_NEED                         852.0
                                        WEEKLY                          36650.0
           MONTHLY                      BI_WEEKLY                      239042.0
                                        DAILY                            9762.0
                                        MONTHLY                        322278.0
                                        RARE_NEED                      159353.0
                                        WEEKLY                          27180.0
           RARE_NEED                    BI_WEEKLY                       43981.0
                                        DAILY                            2740.0
                                        MONTHLY                        100215.0
                                        RARE_NEED                      141443.0
                                        WEEKLY                           3053.0
           WEEKLY                       BI_WEEKLY                      134946.0
                                        DAILY                           42050.0
                                        MONTHLY                         22742.0
                                        RARE_NEED                         948.0
                                        WEEKLY                         232252.0

                                                                                 \
run_date_y                                                           2025-04-28
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      424435.0
                                        DAILY                           36452.0
                                        MONTHLY                        238639.0
                                        RARE_NEED                       73327.0
                                        WEEKLY                         160893.0
           DAILY                        BI_WEEKLY                       30057.0
                                        DAILY                          195829.0
                                        MONTHLY                          8748.0
                                        RARE_NEED                        2326.0
                                        WEEKLY                          38890.0
           MONTHLY                      BI_WEEKLY                      235073.0
                                        DAILY                           10782.0
                                        MONTHLY                        297850.0
                                        RARE_NEED                      151518.0
                                        WEEKLY                          34006.0
           RARE_NEED                    BI_WEEKLY                       48624.0
                                        DAILY                            3197.0
                                        MONTHLY                         98413.0
                                        RARE_NEED                      122353.0
                                        WEEKLY                           4213.0
           WEEKLY                       BI_WEEKLY                      138251.0
                                        DAILY                           45192.0
                                        MONTHLY                         29671.0
                                        RARE_NEED                        3447.0
                                        WEEKLY                         215366.0


run_date_y                                                           2025-05-05
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      402389.0
                                        DAILY                           38183.0
                                        MONTHLY                        228792.0
                                        RARE_NEED                       75978.0
                                        WEEKLY                         163940.0
           DAILY                        BI_WEEKLY                       31924.0
                                        DAILY                          187191.0
                                        MONTHLY                          9797.0
                                        RARE_NEED                        3582.0
                                        WEEKLY                          41148.0
           MONTHLY                      BI_WEEKLY                      235715.0
                                        DAILY                           11868.0
                                        MONTHLY                        278407.0
                                        RARE_NEED                      139189.0
                                        WEEKLY                          40623.0
           RARE_NEED                    BI_WEEKLY                       53090.0
                                        DAILY                            3652.0
                                        MONTHLY                         96969.0
                                        RARE_NEED                      106161.0
                                        WEEKLY                           6320.0
           WEEKLY                       BI_WEEKLY                      137471.0
                                        DAILY                           48310.0
                                        MONTHLY                         33910.0
                                        RARE_NEED                        6916.0

In [38]:
df_base_prev.groupby(['run_date', 'taxi_fe_regularity_segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date taxi_fe_regularity_segment  customers
0  2025-03-03                  BI_WEEKLY    1056482
1  2025-03-03                      DAILY     292637
2  2025-03-03                    MONTHLY    1047096
3  2025-03-03                  RARE_NEED     590726
4  2025-03-03                     WEEKLY     461165