In [1]:
import os
import h3 as h3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import date, timedelta

from scipy import stats
from pyhive import presto
from keplergl import KeplerGl
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='md.sohel@rapido.bike'
    
    
)

## Parameter

In [17]:
## Parameter 
start_date = date(2023, 10, 16)
end_date = date(2023, 10, 20)

In [10]:
# Initialize an empty DataFrame
df_postorderstatus_requesting = pd.DataFrame()

# Loop through the date range day by day using a for loop
for current_date in (start_date + timedelta(n) for n in range((end_date - start_date).days + 1)):
    
    current_date = current_date.strftime('%Y%m%d')
    # Construct the query with the current date
    query = f"""
        SELECT 
            *,
            SUBSTR(profile_phone, 3) customer_mobile,
            json_extract_scalar(eventProps_data,'$.orderId') order_id
        FROM
            raw.clevertap_customer_postorderstatus_requesting
        WHERE 
            yyyymmdd = '{current_date}'
    """
    
    # Execute the query and append the results to the DataFrame
    daily_data = pd.read_sql(query, connection)
    df_postorderstatus_requesting = df_postorderstatus_requesting.append(daily_data, ignore_index=True)

# Print the first few rows of the combined DataFrame
df_postorderstatus_requesting

,eventname,yyyymmdd,hhmmss,quarter_hour,epoch,created_ist,deviceInfo_appVersion,deviceInfo_browser,deviceInfo_dimensions_height,deviceInfo_dimensions_unit,deviceInfo_dimensions_width,deviceInfo_dpi,deviceInfo_make,deviceInfo_model,deviceInfo_osVersion,deviceInfo_sdkVersion,profile_all_identities,profile_email,profile_identity,profile_name,profile_phone,profile_platform,eventProps_area,eventProps_currentCity,eventProps_currentCluster,eventProps_epoch,eventProps_hhmmss,eventProps_latitude,eventProps_locationAccuracy,eventProps_longitude,eventProps_occurred_date,eventProps_yyyymmdd,eventProps_CTAppVersion,eventProps_CTLatitude,eventProps_CTLongitude,eventProps_CTSource,eventProps_CTSessionId,deviceInfo_data,profile_data,eventProps_data,customer_mobile,order_id
0,postorderstatus_requesting,20231016,234353,2330,1697480033000,2023-10-16 23:43:53.000,8.8.1,MobileApp,115,mm,47,480,Realme,Rmx3561,13,40704,"[""636eacdbb48cdd1414f8a062""]",None,636eacdbb48cdd1414f8a062,mohammed azeem,918897941649,Android,None,Warangal,REDDY COLONY,1697480033765,234353,18.011797,4.27,79.567154,Mon Oct 16 2023 23:43:53 pm,20231016,8.8.1,18.01174,79.567085,Mobile,1.697479828E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""636eacdbb48cdd1414f8a062""]...","{""app_variant"":""v8"",""cleverTapId"":""__420899005...",8897941649,652d7d603d1073246b92d084
1,postorderstatus_requesting,20231016,151953,1515,1697449793000,2023-10-16 15:19:53.000,8.8.1,MobileApp,131,mm,65,280,Samsung,Sm-a125f,12,40704,None,None,None,None,None,Android,None,Hyderabad,Ashok Nagar 2,1697449793399,151953,17.405336,2.066,78.47649,Mon Oct 16 2023 15:19:53 pm,20231016,8.8.1,None,None,Mobile,1.697449383E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""platform"":""Android"",""push_token"":""fcm:e4GmZc...","{""app_variant"":""v7"",""cleverTapId"":""__e322f702a...",None,652d05d07bd73a0d9475d81c
2,postorderstatus_requesting,20231016,152114,1515,1697449874000,2023-10-16 15:21:14.000,8.8.1,MobileApp,131,mm,65,280,Samsung,Sm-a125f,12,40704,None,None,None,None,None,Android,None,Hyderabad,Ashok Nagar 2,1697449874063,152114,17.405329,3.516,78.47677,Mon Oct 16 2023 15:21:14 pm,20231016,8.8.1,None,None,Mobile,1.697449383E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""platform"":""Android"",""push_token"":""fcm:e4GmZc...","{""app_variant"":""v7"",""cleverTapId"":""__e322f702a...",None,652d05d07bd73a0d9475d81c
3,postorderstatus_requesting,20231016,151446,1500,1697449486000,2023-10-16 15:14:46.000,8.8.1,MobileApp,131,mm,65,280,Samsung,Sm-a125f,12,40704,None,None,None,None,None,Android,None,Hyderabad,Ashok Nagar 2,1697449486054,151446,17.40521,17.094,78.47611,Mon Oct 16 2023 15:14:46 pm,20231016,8.8.1,None,None,Mobile,1.697449383E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""platform"":""Android"",""push_token"":""fcm:e4GmZc...","{""app_variant"":""v7"",""cleverTapId"":""__e322f702a...",None,652d05d07bd73a0d9475d81c
4,postorderstatus_requesting,20231016,123348,1230,1697439828000,2023-10-16 12:33:48.000,8.7.0,MobileApp,121,mm,60,450,Oneplus,Hd1901,12,40704,"[""629251487a954321f0c09c39"",""sana11sultana@gma...",sana11sultana@gmail.com,629251487a954321f0c09c39,sana sultana,918919876342,Android,None,Hyderabad,Nanakramguda 2,1697439828757,123348,17.422178,20.893,78.33243,Mon Oct 16 2023 12:33:48 pm,20231016,8.7.0,None,None,Mobile,1.697439542E9,"{""appVersion"":""8.7.0"",""browser"":""MobileApp"",""d...","{""all_identities"":[""629251487a954321f0c09c39"",...","{""app_variant"":""v7"",""cleverTapId"":""__075962a00...",8919876342,652cdf7b3d1073246b9171ac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1654499,postorderstatus_requesting,20231020,201956,2015,1697813396000,2023-10-20 20:19:56.000,8.4.1,MobileApp,124,mm,62,440,Xiaomi,21091116i,13,40704,"[""5e3fc29e98e7062836e0180d"",""jiaarohi2512@gmai...",jiaarohi2512@gmail.com,5e3fc29e98e7062836e0180d,PUJA GUPTA,917992342811,Android,None,Jamshedpur,Sakchi,1697813396253,201956,22.8013,28.066,86.20677,Fri Oct 20 2023 20:19:56 pm,20231020,8.4.1,22.8013,86.20677,Mobile,1.697812868E9,"{""appVersion"":""8.4.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5e3fc29e98e7062836e0180d"",...","{""app_variant"":""v7"",""cleverTapId"":""__g6b4117f3...",7992342811,653292e58dd5ad4cd1b57c09
1654500,postorderstatus_requesting,20231020,202017,2015,1697813417000,2023-10-20 20:20:17.000,3.0.6,MobileApp,None,None,None,None,Apple,"Iphone14,7",16.6.1,301000,"[""archana.18kumari@gmail.com"",""5d54509ebde10e0...",archana.18kumari@gmail.com,5d54509ebde10e0d543ec7da,Archana Choudhary,919891560505,iOS,,Hyderabad,Banjara Hills,1697813417883,None,17.424063,None,78.44367,$D_1697813417,None,3.0.6,17.424063,78.44367,Mobile,1.697812581E9,"{""appVersion"":""3.0.6"",""browser"":""MobileApp"",""m...","{""all_identities"":[""archana.18kumari@gmail.com...","{""area"":"""",""cleverTapId"":""-v7f36a58055d54e8b88...",9891560505,None
1654501,postorderstatus_requesting,20231020,202051,2015,1697813451000,2023-10-20 20:20:51.000,8.8.1,MobileApp,127,mm,52,440,Vivo,V2126,13,40704,"[""61477072e8f223269aaa62f1"",""kondinaga1082@gma...",kondinaga1082@gmail.com,61477072e8f223269aaa62f1,nagaraju,918639055183,Android,None,Hyderabad,Amberpet,1697813451887,202051,17.393187,4.393,78.52134,Fri Oct 20 2023 20:20:51 pm,20231020,8.8.1,17.393187,78.52134,Mobile,1.697813271E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""61477072e8f223269aaa62f1"",...","{""app_variant"":""v7"",""cleverTapId"":""__072c58879...",8639055183,653293ae685ace085e905ea4
1654502,postorderstatus_requesting,20231020,202135,2015,1697813495000,2023-10-20 20:21:35.000,8.8.1,MobileApp,138,mm,59,400,Motorola,Edge 20 fusion,12,40704,"[""5da2d10ba1f0a71c6066d0d1""]",None,5da2d10ba1f0a71c6066d0d1,KanchanBharti,917891779753,Android,None,Hyderabad,Hitech City,1697813495259,202135,17.44835,7.878,78.367004,Fri Oct 20 2023 20:21:35 pm,20231020,8.8.1,17.448107,78.36712,Mobile,1.697813319E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5da2d10ba1f0a71c6066d0d1""]...","{""app_variant"":""v8"",""cleverTapId"":""__2a82ca77e...",7891779753,653293f633744d12a3cfb2f3
1654503,postorderstatus_requesting,20231020,202133,2015,1697813493000,2023-10-20 20:21:33.000,8.8.1,MobileApp,118,mm,50,640,Oneplus,In2021,12,40704,"[""62d4defe91f095830859647d""]",None,62d4defe91f095830859647d,Shaurya Sharma,919703233561,Android,None,Bangalore,Kaikondrahalli,1697813493005,202133,12.919726,18.87,77.68497,Fri Oct 20 2023 20:21:33 pm,20231020,8.8.1,12.919726,77.68497,Mobile,1.69781341E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""62d4defe91f095830859647d""]...","{""app_variant"":""v7"",""cleverTapId"":""__g0a99b07e...",9703233561,653293b84c28820c53a5a26d

In [11]:
df_postorderstatus_requesting.to_csv('raw_postorderstatus_requesting_{}_to_{}.csv'.format(start_date, end_date), 
                                     index=False)

In [12]:
# Initialize an empty DataFrame
df_postorderstatus_started = pd.DataFrame()

# Loop through the date range day by day using a for loop
for current_date in (start_date + timedelta(n) for n in range((end_date - start_date).days + 1)):
    
    current_date = current_date.strftime('%Y%m%d')
    # Construct the query with the current date
    query = f"""
        SELECT 
            *,
            SUBSTR(profile_phone, 3) customer_mobile,
            json_extract_scalar(eventProps_data,'$.orderId') order_id
        FROM
            raw.clevertap_customer_postorderstatus_started
        WHERE 
            yyyymmdd = '{current_date}'
    """
    
    # Execute the query and append the results to the DataFrame
    daily_data = pd.read_sql(query, connection)
    df_postorderstatus_started = df_postorderstatus_started.append(daily_data, ignore_index=True)

# Print the first few rows of the combined DataFrame
df_postorderstatus_started

,eventname,yyyymmdd,hhmmss,quarter_hour,epoch,created_ist,deviceInfo_appVersion,deviceInfo_browser,deviceInfo_dimensions_height,deviceInfo_dimensions_unit,deviceInfo_dimensions_width,deviceInfo_dpi,deviceInfo_make,deviceInfo_model,deviceInfo_osVersion,deviceInfo_sdkVersion,profile_all_identities,profile_email,profile_identity,profile_name,profile_phone,profile_platform,eventProps_area,eventProps_currentCity,eventProps_currentCluster,eventProps_epoch,eventProps_hhmmss,eventProps_latitude,eventProps_locationAccuracy,eventProps_longitude,eventProps_occurred_date,eventProps_yyyymmdd,eventProps_CTAppVersion,eventProps_CTLatitude,eventProps_CTLongitude,eventProps_CTSource,eventProps_CTSessionId,deviceInfo_data,profile_data,eventProps_data,customer_mobile,order_id
0,postorderstatus_started,20231016,094826,0945,1697429906000,2023-10-16 09:48:26.000,8.7.0,MobileApp,128,mm,65,280,Samsung,Sm-m115f,11,40704,"[""6349572ff0a0f3018f22512f""]",None,6349572ff0a0f3018f22512f,budharam,919940397455,Android,None,Chennai,Allapakkam,1697429906793,094826,13.045036,22.894,80.16491,Mon Oct 16 2023 09:48:26 am,20231016,8.7.0,None,None,Mobile,1.69742823E9,"{""appVersion"":""8.7.0"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6349572ff0a0f3018f22512f""]...","{""app_variant"":""v7"",""cleverTapId"":""__g3bd625b4...",9940397455,652cb88e8ca1ac1f45edc98e
1,postorderstatus_started,20231016,124231,1230,1697440351000,2023-10-16 12:42:31.000,8.8.1,MobileApp,112,mm,57,480,Realme,Rmx2076,12,40704,"[""64c0e67f17061a4721c187a2"",""debasisnayak442@g...",debasisnayak442@gmail.com,64c0e67f17061a4721c187a2,debasis patro,919348749329,Android,None,Bhubaneswar,Nelladiri Vihar,1697440351743,124231,20.336988,52.4,85.80565,Mon Oct 16 2023 12:42:31 pm,20231016,8.8.1,None,None,Mobile,1.697439425E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""64c0e67f17061a4721c187a2"",...","{""app_variant"":""v8"",""cleverTapId"":""__6323ed96c...",9348749329,652cdf23cb03672ceff59cba
2,postorderstatus_started,20231016,194402,1930,1697465642000,2023-10-16 19:44:02.000,8.7.0,MobileApp,111,mm,57,480,Oppo,Cph1989,11,40704,"[""5c8f32d88c352421eaefe9d5"",""rajendrakumarshah...",rajendrakumarshah16@gmail.com,5c8f32d88c352421eaefe9d5,Rajendra Kumar Rajendra Kumar,917488812046,Android,None,Bangalore,Peenya 2nd Stage,1697465642352,194402,12.996618,9.966,77.50881,Mon Oct 16 2023 19:44:02 pm,20231016,8.7.0,None,None,Mobile,1.697464652E9,"{""appVersion"":""8.7.0"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5c8f32d88c352421eaefe9d5"",...","{""app_variant"":""v7"",""cleverTapId"":""__g46e58870...",7488812046,652d437ec64e7c43cd63b61f
3,postorderstatus_started,20231016,202226,2015,1697467946000,2023-10-16 20:22:26.000,8.8.1,MobileApp,114,mm,47,480,Realme,Rmx3471,13,40704,"[""614c80b48c5923a7df8423d8"",""ammar@gmail.com"",...",ammar.husain1122@gmail.com,614c80b48c5923a7df8423d8,Ammar Husain,918878628971,Android,None,Bhopal,Old Bhopal,1697467946617,202226,23.267275,3.9,77.378555,Mon Oct 16 2023 20:22:26 pm,20231016,8.8.1,None,None,Mobile,1.697467943E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""614c80b48c5923a7df8423d8"",...","{""app_variant"":""v8"",""cleverTapId"":""__68d9a9c2c...",8878628971,652cf3c88b6f7c103cbf26ca
4,postorderstatus_started,20231016,202233,2015,1697467953000,2023-10-16 20:22:33.000,8.8.1,MobileApp,114,mm,47,480,Realme,Rmx3471,13,40704,"[""614c80b48c5923a7df8423d8"",""ammar@gmail.com"",...",ammar.husain1122@gmail.com,614c80b48c5923a7df8423d8,Ammar Husain,918878628971,Android,None,Bhopal,Old Bhopal,1697467953137,202233,23.29684,5.186,77.40053,Mon Oct 16 2023 20:22:33 pm,20231016,8.8.1,None,None,Mobile,1.697467943E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""614c80b48c5923a7df8423d8"",...","{""app_variant"":""v8"",""cleverTapId"":""__68d9a9c2c...",8878628971,652cf3c88b6f7c103cbf26ca
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5253436,postorderstatus_started,20231020,171126,1700,1697802086000,2023-10-20 17:11:26.000,8.8.1,MobileApp,122,mm,68,440,Xiaomi,Poco f1,10,40704,"[""62824622587765fa98d0f147""]",None,62824622587765fa98d0f147,Shravan,919177565509,Android,None,Hyderabad,Hitech City,1697802086872,171126,17.452013,19.124,78.369675,Fri Oct 20 2023 17:11:26 pm,20231020,8.8.1,17.451633,78.36994,Mobile,1.697801466E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""62824622587765fa98d0f147""]...","{""app_variant"":""v7"",""cleverTapId"":""__264a2d910...",9177565509,6532651c33744d12a3cf2202
5253437,postorderstatus_started,20231020,171131,1700,1697802091000,2023-10-20 17:11:31.000,8.7.0,MobileApp,126,mm,68,480,Motorola,One power,10,40704,"[""632e9fdb7ebbde6311158ca8""]",None,632e9fdb7ebbde6311158ca8,puneeth H L,917353640722,Android,None,Chennai,Vadapalani,1697802091523,171131,13.057387,12.27,80.2115,Fri Oct 20 2023 17:11:31 pm,20231020,8.7.0,13.057499,80.21179,Mobile,1.697801558E9,"{""appVersion"":""8.7.0"",""browser"":""MobileApp"",""d...","{""all_identities"":[""632e9fdb7ebbde6311158ca8""]...","{""app_variant"":""v7"",""cleverTapId"":""__9ee5b6085...",7353640722,6532671833744d12a3cf288e
5253438,postorderstatus_started,20231020,171144,1700,1697802104000,2023-10-20 17:11:44.000,8.8.1,MobileApp,125,mm,62,440,Vivo,V2126,13,40704,"[""623c5349cbae732431bb53a2"",""yashodhapeter@123...",yashodhapete@123gmail.com,623c5349cbae732431bb53a2,john,917349500991,Android,None,Bangalore,Electronic City Phase 2,1697802104337,171144,12.854744,3.9,77.68508,Fri Oct 20 2023 17:11:44 pm,20231020,8.8.1,12.854864,77.68438,Mobile,1.697800875E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""623c5349cbae732431bb53a2"",...","{""app_variant"":""v7"",""cleverTapId"":""__g96e6454d...",7349500991,653262cb685ace085e8fc6bf
5253439,postorderstatus_started,20231020,171210,1700,1697802130000,2023-10-20 17:12:10.000,8.8.1,MobileApp,130,mm,55,420,Google,Pixel 6a,13,40704,"[""623a770db9a21e0139cba2f8"",""jyoshnasunchu@gma...",jyoshnasunchu@gmail.com,"623a770db9a21e0139cba2f8,63706f62aa4f7ac694845008",jyoshna,919121702011,Android,None,Hyderabad,Nagole,1697802130656,171210,17.370262,4.194,78.5727,Fri Oct 20 2023 17:12:10 pm,20231020,8.8.1,17.37127,78.5677,Mobile,1.697801616E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""623a770db9a21e0139cba2f8"",...","{""app_variant"":""v7"",""cleverTapId"":""__g29924a0e...",9121702011,6532660b685ace085e8fd0fc
5253440,postorderstatus_started,20231020,171209,1700,1697802129000,2023-10-20 17:12:09.000,8.8.1,MobileApp,134,mm,66,480,Vivo,V2218,13,40704,"[""61d593b5731a6d34e7061bc3"",""sudhanshusrivasta...",sudhanshusrivastav48@gmail.com,61d593b5731a6d34e7061bc3,sudhanshu,917888854952,Android,None,Chandigarh,Sec-27-28-29-30,1697802129948,171209,30.71302,10.574,76.78931,Fri Oct 20 2023 17:12:09 pm,20231020,8.8.1,30.713104,76.78934,Mobile,1.697801666E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""61d593b5731a6d34e7061bc3"",...","{""app_variant"":""v7"",""cleverTapId"":""__ae0162d1e...",7888854952,6532662013f59263b39f63d2

In [18]:
df_postorderstatus_started.to_csv('raw_postorderstatus_started_{}_to_{}.csv'.format(start_date, end_date), 
                                     index=False)

In [19]:
# Initialize an empty DataFrame
df_postorderstatus_dropped = pd.DataFrame()

# Loop through the date range day by day using a for loop
for current_date in (start_date + timedelta(n) for n in range((end_date - start_date).days + 1)):
    
    current_date = current_date.strftime('%Y%m%d')
    # Construct the query with the current date
    query = f"""
        SELECT 
            *,
            SUBSTR(profile_phone, 3) customer_mobile,
            json_extract_scalar(eventProps_data,'$.orderId') order_id
        FROM
            raw.clevertap_customer_postorderstatus_dropped
        WHERE 
            yyyymmdd = '{current_date}'
    """
    
    # Execute the query and append the results to the DataFrame
    daily_data = pd.read_sql(query, connection)
    df_postorderstatus_dropped = df_postorderstatus_dropped.append(daily_data, ignore_index=True)

# Print the first few rows of the combined DataFrame
df_postorderstatus_dropped

,eventname,yyyymmdd,hhmmss,quarter_hour,epoch,created_ist,deviceInfo_appVersion,deviceInfo_browser,deviceInfo_dimensions_height,deviceInfo_dimensions_unit,deviceInfo_dimensions_width,deviceInfo_dpi,deviceInfo_make,deviceInfo_model,deviceInfo_osVersion,deviceInfo_sdkVersion,profile_all_identities,profile_email,profile_identity,profile_name,profile_phone,profile_platform,eventProps_area,eventProps_currentCity,eventProps_currentCluster,eventProps_epoch,eventProps_hhmmss,eventProps_latitude,eventProps_locationAccuracy,eventProps_longitude,eventProps_occurred_date,eventProps_yyyymmdd,eventProps_CTAppVersion,eventProps_CTLatitude,eventProps_CTLongitude,eventProps_CTSource,eventProps_CTSessionId,deviceInfo_data,profile_data,eventProps_data,customer_mobile,order_id
0,postorderstatus_dropped,20231016,222241,2215,1697475161000,2023-10-16 22:22:41.000,3.0.6,MobileApp,None,None,None,None,Apple,"Iphone13,1",16.6,301000,"[""62121eb719276564da56ef26"",""sasroy9@gmail.com""]",sasroy9@gmail.com,62121eb719276564da56ef26,Sasadhar Roy,917019193274,iOS,,Bangalore,CPWD Qtrs HSR,1697475161668,None,12.911281,None,77.63437,$D_1697475161,None,3.0.6,None,None,Mobile,1.697474652E9,"{""appVersion"":""3.0.6"",""browser"":""MobileApp"",""m...","{""all_identities"":[""62121eb719276564da56ef26"",...","{""area"":"""",""cleverTapId"":""-vceb48322094d420b9f...",7019193274,None
1,postorderstatus_dropped,20231016,201553,2015,1697467553000,2023-10-16 20:15:53.000,8.8.1,MobileApp,114,mm,47,480,Realme,Rmx3660,13,40704,None,None,None,None,None,Android,None,Delhi,NCR N ISKCON,1697467553352,201553,28.589624,1.0,77.34475,Mon Oct 16 2023 20:15:53 pm,20231016,8.8.1,None,None,Mobile,1.697467446E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""platform"":""Android"",""push_token"":""fcm:dH10FF...","{""app_variant"":""v7"",""cleverTapId"":""__e1cd4f8b3...",None,652d43f6c2c27c459ea83a27
2,postorderstatus_dropped,20231016,214208,2130,1697472728000,2023-10-16 21:42:08.000,8.8.1,MobileApp,109,mm,57,320,Vivo,1938,12,40704,"[""62216919f0b26b4bfd606390"",""premgeetha305@gma...",premgeetha305@gmail.com,62216919f0b26b4bfd606390,prem yadav,917032080280,Android,None,Tirupati,Jeevakona,1697472728322,214208,13.631911,11.2,79.40985,Mon Oct 16 2023 21:42:08 pm,20231016,8.8.1,13.631133,79.40835,Mobile,1.697471704E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""62216919f0b26b4bfd606390"",...","{""app_variant"":""v7"",""cleverTapId"":""__2787b90a1...",7032080280,652d5cfb3d1073246b92946e
3,postorderstatus_dropped,20231016,190654,1900,1697463414000,2023-10-16 19:06:54.000,8.8.1,MobileApp,115,mm,57,480,Oppo,Cph1907,11,40704,"[""63f9702df22ead2b8d852ce8"",""praveenchoudharyp...",praveenchoudharypc1213@gmail.com,63f9702df22ead2b8d852ce8,praveen choudhary,919983711890,Android,None,Jaipur,VKI_JAI,1697463414860,190654,26.97919,13.064,75.767876,Mon Oct 16 2023 19:06:54 pm,20231016,8.8.1,None,None,Mobile,1.697463155E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""63f9702df22ead2b8d852ce8"",...","{""app_variant"":""v7"",""cleverTapId"":""__gb418316c...",9983711890,652d3ac451edf965b4f585b1
4,postorderstatus_dropped,20231016,200143,2000,1697466703000,2023-10-16 20:01:43.000,8.8.1,MobileApp,118,mm,60,450,Samsung,Sm-a346e,13,40704,"[""5ded16ec1a882e3354b92426"",""nemathnemathullah...",nemathnemathullah@gmail.com,5ded16ec1a882e3354b92426,Nemathullah Nemath,919885801950,Android,None,Hyderabad,Charminar Murad Mahal Colony,1697466703678,200143,17.355051,4.733,78.48344,Mon Oct 16 2023 20:01:43 pm,20231016,8.8.1,None,None,Mobile,1.69746661E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5ded16ec1a882e3354b92426"",...","{""app_variant"":""v7"",""cleverTapId"":""__05b60e899...",9885801950,652d3d80754e4e1ff0ccd12f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2701557,postorderstatus_dropped,20231020,183911,1830,1697807351000,2023-10-20 18:39:11.000,3.0.6,MobileApp,None,None,None,None,Apple,"Iphone14,7",16.6,301000,"[""5e29494d329ce57f86d18a24"",""aprince946@gmail....",aprince946@gmail.com,5e29494d329ce57f86d18a24,Amandeep singh,919034940315,iOS,,Bhopal,Tulsi Nagar,1697807351930,None,23.235409,None,77.401276,$D_1697807351,None,3.0.6,23.194065,77.43269,Mobile,1.697807351E9,"{""appVersion"":""3.0.6"",""browser"":""MobileApp"",""m...","{""all_identities"":[""5e29494d329ce57f86d18a24"",...","{""area"":"""",""cleverTapId"":""-vafee7fbfdefc4a5395...",9034940315,None
2701558,postorderstatus_dropped,20231020,183938,1830,1697807378000,2023-10-20 18:39:38.000,8.7.0,MobileApp,98,mm,50,540,Oneplus,Cph2467,13,40704,"[""651519b531a586cfd8b23da6""]",None,651519b531a586cfd8b23da6,R Marimuthu,917676823595,Android,None,Bangalore,Bommasandra Industrial Area,1697807378452,183938,12.819571,4.701,77.644325,Fri Oct 20 2023 18:39:38 pm,20231020,8.7.0,12.819571,77.644325,Mobile,1.697806434E9,"{""appVersion"":""8.7.0"",""browser"":""MobileApp"",""d...","{""all_identities"":[""651519b531a586cfd8b23da6""]...","{""app_variant"":""v7"",""cleverTapId"":""__a42a33954...",7676823595,65327874685ace085e900ca7
2701559,postorderstatus_dropped,20231020,183946,1830,1697807386000,2023-10-20 18:39:46.000,8.8.1,MobileApp,114,mm,57,320,Oppo,Cph2239,11,40704,"[""6276266a1234c55f2114ad72""]",None,6276266a1234c55f2114ad72,Mohammad Jahangir,918977755909,Android,None,Hyderabad,Secunderabad,1697807386612,183946,17.39493,14.057,78.459175,Fri Oct 20 2023 18:39:46 pm,20231020,8.8.1,17.395683,78.45953,Mobile,1.697806242E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6276266a1234c55f2114ad72""]...","{""app_variant"":""v7"",""cleverTapId"":""__g7cc56760...",8977755909,65326f29dc9b7e3eae69a112
2701560,postorderstatus_dropped,20231020,184050,1830,1697807450000,2023-10-20 18:40:50.000,8.4.1,MobileApp,127,mm,65,420,Samsung,Sm-f415f,12,40704,"[""5e49357f8cfe828290ed545f"",""meghanko96@gmail....",meghanko96@gmail.com,5e49357f8cfe828290ed545f,meghanko Mukherjee,919038630080,Android,None,Kolkata,TollyGunge,1697807450598,184050,22.510668,24.9,88.34857,Fri Oct 20 2023 18:40:50 pm,20231020,8.4.1,22.510668,88.34857,Mobile,1.697807423E9,"{""appVersion"":""8.4.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5e49357f8cfe828290ed545f"",...","{""app_variant"":""v7"",""cleverTapId"":""__aa53300e2...",9038630080,653276459abf3746b19c7c04
2701561,postorderstatus_dropped,20231020,184102,1830,1697807462000,2023-10-20 18:41:02.000,8.7.0,MobileApp,114,mm,57,320,Oppo,Cph2495,13,40704,"[""5dcf289a010c5a4601066611"",""dharani.abhi1994@...",dharani.abhi1994@gmail.com,5dcf289a010c5a4601066611,Sarai Dharani,918639724139,Android,None,Bangalore,Columbia Asia Whitefield,1697807462099,184102,12.955845,6.297,77.72867,Fri Oct 20 2023 18:41:02 pm,20231020,8.7.0,12.955845,77.72867,Mobile,1.697807461E9,"{""appVersion"":""8.7.0"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5dcf289a010c5a4601066611"",...","{""app_variant"":""v7"",""cleverTapId"":""__1caa6d24f...",8639724139,653273271686876329cd1b4f

In [20]:
df_postorderstatus_dropped.to_csv('raw_postorderstatus_dropped_{}_to_{}.csv'.format(start_date, end_date), 
                                     index=False)

## Others

In [25]:
## Parameter 
start_date1 = date(2023, 11, 1)
end_date1 = date(2023, 11, 1)

In [26]:
# Initialize an empty DataFrame
df_postorderstatus_requesting = pd.DataFrame()

# Loop through the date range day by day using a for loop
for current_date in (start_date1 + timedelta(n) for n in range((end_date1 - start_date1).days + 1)):
    
    current_date = current_date.strftime('%Y%m%d')
    # Construct the query with the current date
    query = f"""
        SELECT 
            *
        FROM
            raw.clevertap_customer_pip_action
        WHERE 
            yyyymmdd = '{current_date}'
        LIMIT 100
    """
    
    # Execute the query and append the results to the DataFrame
    daily_data = pd.read_sql(query, connection)
    df_postorderstatus_requesting = pd.concat([df_postorderstatus_requesting, daily_data], ignore_index=True)

# Print the first few rows of the combined DataFrame
df_postorderstatus_requesting

,eventname,yyyymmdd,hhmmss,quarter_hour,epoch,created_ist,deviceInfo_appVersion,deviceInfo_browser,deviceInfo_dimensions_height,deviceInfo_dimensions_unit,deviceInfo_dimensions_width,deviceInfo_dpi,deviceInfo_make,deviceInfo_model,deviceInfo_osVersion,deviceInfo_sdkVersion,profile_all_identities,profile_email,profile_identity,profile_name,profile_phone,profile_platform,eventProps_action,eventProps_area,eventProps_cleverTapId,eventProps_currentCity,eventProps_currentCluster,eventProps_epoch,eventProps_hhmmss,eventProps_latitude,eventProps_locationAccuracy,eventProps_longitude,eventProps_occurred_date,eventProps_orderstatus,eventProps_trigger,eventProps_userId,eventProps_yyyymmdd,eventProps_version,eventProps_CTAppVersion,eventProps_CTLatitude,eventProps_CTLongitude,eventProps_CTSource,eventProps_CTSessionId,deviceInfo_data,profile_data,eventProps_data
0,pip_action,20231101,154458,1530,1698833698000,2023-11-01 15:44:58.000,8.8.1,MobileApp,123,mm,60,300,Samsung,Sm-m022g,11,40704,"[""6083fcdda54f842d0447f294"",""gauravsinghsmarty...",gaurav231221@gmail.com,"6083fcdda54f842d0447f294,6259548b8004cf690b66fe00",Gaurav Singh,917969019151,Android,show,None,__gd0635a6a8cbf4b38a6766012330aaf8f,Delhi,Sarhaul 2,1698833698190,154458,28.500092,7.806,77.060745,Wed Nov 01 2023 15:44:58 pm,arrived,home_button,6259548b8004cf690b66fe00,20231101,v2,8.8.1,None,None,Mobile,1.698832821E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6083fcdda54f842d0447f294"",...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."
1,pip_action,20231101,191518,1915,1698846318000,2023-11-01 19:15:18.000,8.8.1,MobileApp,133,mm,68,320,Oppo,Cph1809,8.1.0,40704,"[""64d65bbb12dbf377a4b1bf1d""]",None,64d65bbb12dbf377a4b1bf1d,Brahman Dilkhush kumar jha,919106469277,Android,close,None,__730354c3865f4cc588f75775d5448b15,Ahmedabad,vastrapur,1698846318019,191518,23.089035,699.999,72.54987,Wed Nov 01 2023 19:15:18 PM,started,home_button,64d65bbb12dbf377a4b1bf1d,20231101,v2,8.8.1,None,None,Mobile,1.698845885E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""64d65bbb12dbf377a4b1bf1d""]...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
2,pip_action,20231101,094621,0945,1698812181000,2023-11-01 09:46:21.000,8.8.1,MobileApp,112,mm,57,480,Vivo,1818,11,40704,"[""61f2d6d46916b83f62acefc5"",""davulurikranthi19...",davulurikranthi1992@gamil.com,61f2d6d46916b83f62acefc5,kiran kumar,917396165383,Android,show,None,__g4737b83f3c2443dab4f0511780b31955,Vijayawada,S N Puram,1698812181470,094621,16.509,7.649,80.651474,Wed Nov 01 2023 09:46:21 am,started,back_button,5be72fc18e46340b577e2aa4,20231101,v2,8.8.1,None,None,Mobile,1.698810997E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""61f2d6d46916b83f62acefc5"",...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."
3,pip_action,20231101,094626,0945,1698812186000,2023-11-01 09:46:26.000,8.8.1,MobileApp,112,mm,57,480,Vivo,1818,11,40704,"[""61f2d6d46916b83f62acefc5"",""davulurikranthi19...",davulurikranthi1992@gamil.com,61f2d6d46916b83f62acefc5,kiran kumar,917396165383,Android,close,None,__g4737b83f3c2443dab4f0511780b31955,Vijayawada,S N Puram,1698812186335,094626,16.509,7.649,80.651474,Wed Nov 01 2023 09:46:26 am,started,back_button,5be72fc18e46340b577e2aa4,20231101,v2,8.8.1,None,None,Mobile,1.698810997E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""61f2d6d46916b83f62acefc5"",...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
4,pip_action,20231101,191157,1900,1698846117000,2023-11-01 19:11:57.000,8.8.1,MobileApp,123,mm,51,300,Vivo,V2111,12,40704,"[""5b377d4efb73a94e5d7f43d9"",""mahegoudnani02@gm...",mahegoudaithagani@gmail.com,5b377d4efb73a94e5d7f43d9,Aithagani Mahesh Goud,919542585104,Android,close,None,__gff4e215af2be4916ab5bfd1dea6d0e05,Hyderabad,Saroor Nagar,1698846117811,191157,17.34393,7.395,78.50713,Wed Nov 01 2023 19:11:57 pm,started,other,5a154fb398ade9102df176f5,20231101,v2,8.8.1,None,None,Mobile,1.698845321E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5b377d4efb73a94e5d7f43d9"",...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
5,pip_action,20231101,154504,1545,1698833704000,2023-11-01 15:45:04.000,8.8.1,MobileApp,123,mm,60,300,Samsung,Sm-m022g,11,40704,"[""6083fcdda54f842d0447f294"",""gauravsinghsmarty...",gaurav231221@gmail.com,"6083fcdda54f842d0447f294,6259548b8004cf690b66fe00",Gaurav Singh,917969019151,Android,close,None,__gd0635a6a8cbf4b38a6766012330aaf8f,Delhi,Sarhaul 2,1698833704972,154504,28.503874,6.2,77.067894,Wed Nov 01 2023 15:45:04 pm,arrived,home_button,6259548b8004cf690b66fe00,20231101,v2,8.8.1,None,None,Mobile,1.698832821E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6083fcdda54f842d0447f294"",...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
6,pip_action,20231101,191514,1915,1698846314000,2023-11-01 19:15:14.000,8.8.1,MobileApp,133,mm,68,320,Oppo,Cph1809,8.1.0,40704,"[""64d65bbb12dbf377a4b1bf1d""]",None,64d65bbb12dbf377a4b1bf1d,Brahman Dilkhush kumar jha,919106469277,Android,show,None,__730354c3865f4cc588f75775d5448b15,Ahmedabad,vastrapur,1698846314655,191514,23.087662,68.4,72.55042,Wed Nov 01 2023 19:15:14 PM,started,home_button,64d65bbb12dbf377a4b1bf1d,20231101,v2,8.8.1,None,None,Mobile,1.698845885E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""64d65bbb12dbf377a4b1bf1d""]...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."
7,pip_action,20231101,212008,2115,1698853808000,2023-11-01 21:20:08.000,8.6.1,MobileApp,115,mm,57,320,Oppo,Cph2349,11,40704,"[""coolshubham191@gmail.com"",""5b89a1a56025eb4de...",coolshubham191@gmail.com,5b89a1a56025eb4de188155d,shubham singh,917905874940,Android,close,None,__g42611f5a3f364516b41a4f8b9630184c,Lucknow,Ashiyana,1698853774006,211934,26.786768,39.164,80.91631,Wed Nov 01 2023 21:19:34 pm,,home_button,620901d88e29c8dec11be090,20231101,v2,8.6.1,None,None,Mobile,1.698852886E9,"{""appVersion"":""8.6.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""coolshubham191@gmail.com"",...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
8,pip_action,20231101,134444,1330,1698826484000,2023-11-01 13:44:44.000,7.20.0,MobileApp,134,mm,65,420,Samsung,Sm-m515f,12,40704,"[""61d8596b49d69608b987643a"",""shubhrajyotiray@g...",shubhrajyotiray@gmail.com,61d8596b49d69608b987643a,shubhra ray,919954897759,Android,close,None,__g66842a17d10d450ba457336a9998dac5,Guwahati,Kalapahar,1698826484448,134444,26.152752,15.095,91.74033,Wed Nov 01 2023 13:44:44 pm,started,other,61d8596b49d69608b987643a,20231101,v2,7.20.0,26.152752,91.74033,Mobile,1.698824293E9,"{""appVersion"":""7.20.0"",""browser"":""MobileApp"",""...","{""all_identities"":[""61d8596b49d69608b987643a"",...","{""action"":""close"",""cleverTapId"":""__g66842a17d1..."
9,pip_action,20231101,185146,1845,1698844906000,2023-11-01 18:51:46.000,7.15.0,MobileApp,127,mm,65,420,Samsung,Sm-m215f,12,40601,"[""61fd1dd689c809863d928b6c"",""akshayapothani@gm...",akshayapothani@gmail.com,"61fd1dd689c809863d928b6c,634148858c74c56dc6e09ec0",Akshaya,919177166066,Android,close,Hari Vihar Colony,__g7adbdc6007454a2b8c6862c4522b5983,Hyderabad,Himayatnagar,1698844897095,185137,17.409142,19.983,78.50967,Wed Nov 01 2023 18:51:37 pm,started,,61fd1dd689c809863d928b6c,20231101,None,7.15.0,None,None,Mobile,1.698844906E9,"{""appVersion"":""7.15.0"",""browser"":""MobileApp"",""...","{""all_identities"":[""61fd1dd689c809863d928b6c"",...","{""action"":""close"",""area"":""Hari Vihar Colony"",""..."
10,pip_action,20231101,232423,2315,1698861263000,2023-11-01 23:24:23.000,8.2.0,MobileApp,132,mm,67,440,Xiaomi,Redmi note 7 pro,9,40704,"[""645a247478f5a2b7655fba63""]",None,645a247478f5a2b7655fba63,Gayathri,919110745247,Android,movetofullscreen,None,__ce187d7ade7945a2a717b637384e06d7,Rajahmundry,Luthergiri,1698861263482,232423,17.026438,12.775,81.7843,Wed Nov 01 2023 23:24:23 PM,arrived,other,645a247478f5a2b7655fba63,20231101,v2,8.2.0,None,None,Mobile,1.698861262E9,"{""appVersion"":""8.2.0"",""browser"":""MobileApp"",""d...","{""all_identities"":[""645a247478f5a2b7655fba63""]...","{""action"":""movetofullscreen"",""app_variant"":""v7..."
11,pip_action,20231101,163431,1630,1698836671000,2023-11-01 16:34:31.000,8.3.1,MobileApp,121,mm,60,450,Samsung,Sm-a336e,13,40704,"[""5e7da759f4963359d631a5f5"",""gorthysathvika02@...",gorthysathvika02@gmail.com,5e7da759f4963359d631a5f5,gorthy sathvika,918328429412,Android,close,None,__gfeddc633ed654bc4af39db9373db14de,Hyderabad,Madhapur Metro,1698836671984,163431,17.419752,9.5,78.37219,Wed Nov 01 2023 16:34:31 pm,started,other,5e7da759f4963359d631a5f5,20231101,v2,8.3.1,None,None,Mobile,1.698835536E9,"{""appVersion"":""8.3.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5e7da759f4963359d631a5f5"",...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
12,pip_action,20231101,171403,1700,1698839043000,2023-11-01 17:14:03.000,8.1.1,MobileApp,145,mm,70,320,Tecno mobile limited,Tecno ke6j,10,40704,"[""kaluramkumhar763@gmail.com"",""62737afa06d01e2...",kaluramkumhar763@gmail.com,"62737afa06d01e244dc7f65a,64243eecaabd5e5f922e9986",Kaluram Kumhar,919079274886,Android,close,None,__b767cb09dc74463dbfbf184908a4393d,Jaipur,Narayan Vihar_JAI,1698839043433,171403,26.871437,3.9,75.73718,Wed Nov 01 2023 17:14:03 pm,started,other,64243eecaabd5e5f922e9986,20231101,v2,8.1.1,None,None,Mobile,1.69883904E9,"{""appVersion"":""8.1.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""kaluramkumhar763@gmail.com...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
13,pip_action,20231101,202918,2015,1698850758000,2023-11-01 20:29:18.000,7.26.2,MobileApp,112,mm,57,480,Oppo,Cph2359,13,40704,"[""6411d611b63b49b4ce01a1d7""]",None,6411d611b63b49b4ce01a1d7,RajeshN,919381561273,Android,close,None,__fd59b0a335e74fde8f3faf5b94decd75,Hyderabad,Alwal,1698850758026,202918,17.495642,3.9,78.5129,Wed Nov 01 2023 20:29:18 pm,started,home_button,6411d611b63b49b4ce01a1d7,20231101,v2,7.26.2,None,None,Mobile,1.698849995E9,"{""appVersion"":""7.26.2"",""browser"":""MobileApp"",""...","{""all_identities"":[""6411d611b63b49b4ce01a1d7""]...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
14,pip_action,20231101,182915,1815,1698843555000,2023-11-01 18:29:15.000,8.6.1,MobileApp,101,mm,41,540,Realme,Rmx3771,13,40704,"[""5deca619350e59334ef0f804"",""rajendarsingh0099...",rajendarsingh00998877@gmail.com,5deca619350e59334ef0f804,Djeet Singh,918889300654,Android,close,None,__230ca13d9c424e14ab4f761442e37e87,Kolkata,Dakshineswar Kali Temple R,1698843555995,182915,22.58301,5.917,88.361916,Wed Nov 01 2023 18:29:15 pm,started,other,5deca619350e59334ef0f804,20231101,v2,8.6.1,None,None,Mobile,1.698842352E9,"{""appVersion"":""8.6.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""5deca619350e59334ef0f804"",...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
15,pip_action,20231101,165408,1645,1698837848000,2023-11-01 16:54:08.000,7.26.0,MobileApp,122,mm,60,450,Samsung,Sm-a135f,12,40704,"[""6271358c20022e1730852f07"",""dholakiamadura@gm...",dholakiamadura@gmail.com,6271358c20022e1730852f07,Madura,918469851397,Android,close,None,__g9a104db88eee46e0960690e325064db8,Ahmedabad,Vejalpur,1698837848070,165408,23.016518,12.0,72.525856,Wed Nov 01 2023 16:54:08 pm,started,other,6271358c20022e1730852f07,20231101,v2,7.26.0,None,None,Mobile,1.698837369E9,"{""appVersion"":""7.26.0"",""browser"":""MobileApp"",""...","{""all_identities"":[""6271358c20022e1730852f07"",...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
16,pip_action,20231101,121957,1215,1698821397000,2023-11-01 12:19:57.000,7.16.0,MobileApp,55,mm,133,408,Oneplus,Le2101,13,40601,"[""6204c75d062e901241215f0c"",""jeevangowdag1151@...",jeevangowdag1151@gmail.com,6204c75d062e901241215f0c,Jeevan Gowda G,918746028798,Android,show,Vidyaranyapura,__307d77042d534d97a04d1b8f634ba7e3,Mysore,Vidyaranyapuram,1698821397530,121957,12.277603,6.485,76.64752,Wed Nov 01 2023 12:19:57 pm,arrived,,6204c75d062e901241215f0c,20231101,None,7.16.0,None,None,Mobile,1.698820854E9,"{""appVersion"":""7.16.0"",""browser"":""MobileApp"",""...","{""all_identities"":[""6204c75d062e901241215f0c"",...","{""action"":""show"",""area"":""Vidyaranyapura"",""clev..."
17,pip_action,20231101,130742,1300,1698824262000,2023-11-01 13:07:42.000,8.8.1,MobileApp,177,mm,77,314,Vivo,V2158,13,40704,"[""64ffd3625d5cf24ef2213f59""]",None,64ffd3625d5cf24ef2213f59,manoj kumar,919959865110,Android,show,None,__ba053943806c4d5f8719c39bc78ac45c,Vijayawada,S N Puram,1698824262136,130742,16.524225,1500.0,80.61795,Wed Nov 01 2023 13:07:42 pm,arrived,other,64ffd3625d5cf24ef2213f59,20231101,v2,8.8.1,None,None,Mobile,1.698823461E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""64ffd3625d5cf24ef2213f59""]...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."
18,pip_action,20231101,184419,1830,1698844459000,2023-11-01 18:44:19.000,8.8.1,MobileApp,127,mm,52,440,Vivo,V2055,13,40704,"[""63292eee0bc7e6caa9d9b908""]",None,63292eee0bc7e6caa9d9b908,Gaurav Singh,917506245490,Android,show,None,__5b9b12989e3640a89139fce8ca3ee14c,Delhi,NCR N Sharda University 2,1698844459067,184419,28.469913,60.0,77.4868,Wed Nov 01 2023 18:44:19 pm,arrived,home_button,63292eee0bc7e6caa9d9b908,20231101,v2,8.8.1,None,None,Mobile,1.698844017E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""63292eee0bc7e6caa9d9b908""]...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."
19,pip_action,20231101,184423,1830,1698844463000,2023-11-01 18:44:23.000,8.8.1,MobileApp,127,mm,52,440,Vivo,V2055,13,40704,"[""63292eee0bc7e6caa9d9b908""]",None,63292eee0bc7e6caa9d9b908,Gaurav Singh,917506245490,Android,close,None,__5b9b12989e3640a89139fce8ca3ee14c,Delhi,NCR N Sharda University 2,1698844463270,184423,28.470064,7.05,77.48689,Wed Nov 01 2023 18:44:23 pm,arrived,home_button,63292eee0bc7e6caa9d9b908,20231101,v2,8.8.1,None,None,Mobile,1.698844017E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""63292eee0bc7e6caa9d9b908""]...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
20,pip_action,20231101,184558,1845,1698844558000,2023-11-01 18:45:58.000,8.8.1,MobileApp,127,mm,52,440,Vivo,V2055,13,40704,"[""63292eee0bc7e6caa9d9b908""]",None,63292eee0bc7e6caa9d9b908,Gaurav Singh,917506245490,Android,show,None,__5b9b12989e3640a89139fce8ca3ee14c,Delhi,NCR N Sharda University 2,1698844558990,184558,28.46983,4.966,77.48698,Wed Nov 01 2023 18:45:58 pm,arrived,home_button,63292eee0bc7e6caa9d9b908,20231101,v2,8.8.1,None,None,Mobile,1.698844017E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""63292eee0bc7e6caa9d9b908""]...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."
21,pip_action,20231101,184943,1845,1698844783000,2023-11-01 18:49:43.000,8.8.1,MobileApp,127,mm,52,440,Vivo,V2055,13,40704,"[""63292eee0bc7e6caa9d9b908""]",None,63292eee0bc7e6caa9d9b908,Gaurav Singh,917506245490,Android,close,None,__5b9b12989e3640a89139fce8ca3ee14c,Delhi,NCR N Sharda University 2,1698844783519,184943,28.46928,29.009,77.487404,Wed Nov 01 2023 18:49:43 pm,arrived,other,63292eee0bc7e6caa9d9b908,20231101,v2,8.8.1,None,None,Mobile,1.698844017E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""63292eee0bc7e6caa9d9b908""]...","{""action"":""close"",""app_variant"":""v7"",""cleverTa..."
22,pip_action,20231101,162700,1615,1698836220000,2023-11-01 16:27:00.000,8.8.1,MobileApp,112,mm,57,480,Oneplus,Dn2101,12,40704,"[""6541f04d1e0096c14625f202""]",None,6541f04d1e0096c14625f202,Sangita Bhattacharjee,919818427689,Android,movetofullscreen,None,__a829287329d9489288e2baf59061a55c,Kolkata,Rajpur Sonarpur,1698836200500,162640,22.437263,15.543,88.394066,Wed Nov 01 2023 16:26:40 pm,arrived,other,6541f04d1e0096c14625f202,20231101,v2,8.8.1,None,None,Mobile,1.698835538E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6541f04d1e0096c14625f202""]...","{""action"":""movetofullscreen"",""app_variant"":""v7..."
23,pip_action,20231101,162808,1615,1698836288000,2023-11-01 16:28:08.000,8.8.1,MobileApp,112,mm,57,480,Oneplus,Dn2101,12,40704,"[""6541f04d1e0096c14625f202""]",None,6541f04d1e0096c14625f202,Sangita Bhattacharjee,919818427689,Android,show,None,__a829287329d9489288e2baf59061a55c,Kolkata,Rajpur Sonarpur,1698836257933,162737,22.440292,20.325,88.392975,Wed Nov 01 2023 16:27:37 pm,arrived,home_button,6541f04d1e0096c14625f202,20231101,v2,8.8.1,None,None,Mobile,1.698835538E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6541f04d1e0096c14625f202""]...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."
24,pip_action,20231101,162808,1615,1698836288000,2023-11-01 16:28:08.000,8.8.1,MobileApp,112,mm,57,480,Oneplus,Dn2101,12,40704,"[""6541f04d1e0096c14625f202""]",None,6541f04d1e0096c14625f202,Sangita Bhattacharjee,919818427689,Android,movetofullscreen,None,__a829287329d9489288e2baf59061a55c,Kolkata,Rajpur Sonarpur,1698836262030,162742,22.440893,9.375,88.3933,Wed Nov 01 2023 16:27:42 pm,arrived,home_button,6541f04d1e0096c14625f202,20231101,v2,8.8.1,None,None,Mobile,1.698835538E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6541f04d1e0096c14625f202""]...","{""action"":""movetofullscreen"",""app_variant"":""v7..."
25,pip_action,20231101,162808,1615,1698836288000,2023-11-01 16:28:08.000,8.8.1,MobileApp,112,mm,57,480,Oneplus,Dn2101,12,40704,"[""6541f04d1e0096c14625f202""]",None,6541f04d1e0096c14625f202,Sangita Bhattacharjee,919818427689,Android,show,None,__a829287329d9489288e2baf59061a55c,Kolkata,Rajpur Sonarpur,1698836266795,162746,22.4416,3.9,88.39316,Wed Nov 01 2023 16:27:46 pm,arrived,home_button,6541f04d1e0096c14625f202,20231101,v2,8.8.1,None,None,Mobile,1.698835538E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6541f04d1e0096c14625f202""]...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."
26,pip_action,20231101,163115,1630,1698836475000,2023-11-01 16:31:15.000,8.8.1,MobileApp,112,mm,57,480,Oneplus,Dn2101,12,40704,"[""6541f04d1e0096c14625f202""]",None,6541f04d1e0096c14625f202,Sangita Bhattacharjee,919818427689,Android,movetofullscreen,None,__a829287329d9489288e2baf59061a55c,Kolkata,Rajpur Sonarpur,1698836391765,162951,22.450258,11.1,88.39323,Wed Nov 01 2023 16:29:51 pm,arrived,other,6541f04d1e0096c14625f202,20231101,v2,8.8.1,None,None,Mobile,1.698835538E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6541f04d1e0096c14625f202""]...","{""action"":""movetofullscreen"",""app_variant"":""v7..."
27,pip_action,20231101,163115,1630,1698836475000,2023-11-01 16:31:15.000,8.8.1,MobileApp,112,mm,57,480,Oneplus,Dn2101,12,40704,"[""6541f04d1e0096c14625f202""]",None,6541f04d1e0096c14625f202,Sangita Bhattacharjee,919818427689,Android,show,None,__a829287329d9489288e2baf59061a55c,Kolkata,Rajpur Sonarpur,1698836404171,163004,22.45454,4.083,88.3953,Wed Nov 01 2023 16:30:04 pm,arrived,other,6541f04d1e0096c14625f202,20231101,v2,8.8.1,None,None,Mobile,1.698835538E9,"{""appVersion"":""8.8.1"",""browser"":""MobileApp"",""d...","{""all_identities"":[""6541f04d1e0096c14625f202""]...","{""action"":""show"",""app_variant"":""v7"",""cleverTap..."

In [44]:
# Initialize an empty DataFrame
df_postorderstatus_requesting = pd.DataFrame()

# Loop through the date range day by day using a for loop
for current_date in (start_date1 + timedelta(n) for n in range((end_date1 - start_date1).days + 1)):
    
    current_date = current_date.strftime('%Y%m%d')
    # Construct the query with the current date
    query = f"""
        SELECT 
            *
        FROM
            clevertap.customer_postorderstatus_dropped_immutable
        WHERE 
            yyyymmdd = '{current_date}'
        LIMIT 1
    """
    
    # Execute the query and append the results to the DataFrame
    daily_data = pd.read_sql(query, connection)
    df_postorderstatus_requesting = pd.concat([df_postorderstatus_requesting, daily_data], ignore_index=True)

# Print the first few rows of the combined DataFrame
df_postorderstatus_requesting

,device_info_app_version,device_info_browser,device_info_dimensions_height,device_info_dimensions_unit,device_info_dimensions_width,device_info_dpi,device_info_make,device_info_model,device_info_os_version,device_info_sdk_version,profile_all_identities,profile_email,profile_identity,profile_name,profile_phone,profile_platform,event_props_area,event_props_current_city,event_props_current_cluster,event_props_epoch,event_props_hhmmss,event_props_latitude,event_props_location_accuracy,event_props_longitude,event_props_occurred_date,...,event_props_location_hex_7,event_props_location_hex_8,event_props_location_hex_9,event_props_location_hex_10,event_props_location_hex_11,event_props_location_hex_12,event_props_location_hex_13,event_props_location_hex_14,event_props_location_hex_15,event_props_location_latitude,event_props_location_longitude,yyyymmdd,hhmmss,quarter_hour,hh,epoch,updated_epoch,updated_hhmmss,updated_quarter_hour,updated_yyyymmdd,updated_hh,event_props_ct_location_hex_8_city,event_props_ct_location_hex_8_cluster,event_props_location_hex_8_city,event_props_location_hex_8_cluster
0,8.8.1,MobileApp,114,mm,47,480,Oneplus,Cph2381,13,40704,"[""rachinsingh@gmail.com"",""5d9eceea941a7d1c51de...",rachinsingh@gmail.com,5d9eceea941a7d1c51de0d71,Rachin Singh,919711171900,Android,None,Delhi,IFFCO Forest,1698789755438,033235,28.476086,9.2,77.05831,Wed Nov 01 2023 03:32:35 am,...,873da11adffffff,883da11ad5fffff,893da11ad53ffff,8a3da11ad517fff,8b3da11ad513fff,8c3da11ad5133ff,8d3da11ad5132ff,8e3da11ad5132d7,8f3da11ad5132d3,28.476086,77.05831,20231101,033235,0330,03,1698789755000,1698789755000,033235,0330,20231101,03,None,None,Delhi,IFFCO Forest

In [38]:
columns_as_string_request = ', '.join(df_postorderstatus_requesting.columns)
columns_as_string_request

'device_info_app_version, device_info_browser, device_info_dimensions_height, device_info_dimensions_unit, device_info_dimensions_width, device_info_dpi, device_info_make, device_info_model, device_info_os_version, device_info_sdk_version, profile_all_identities, profile_email, profile_identity, profile_name, profile_phone, profile_platform, event_props_area, event_props_current_city, event_props_current_cluster, event_props_epoch, event_props_hhmmss, event_props_latitude, event_props_location_accuracy, event_props_longitude, event_props_occurred_date, event_props_yyyymmdd, event_props_ct_app_version, event_props_ctlatitude, event_props_ctlongitude, event_props_ct_source, event_props_ct_session_id, device_info, profile, event_props, created_ist, created_utc, event_props_ct_location_hex_0, event_props_ct_location_hex_1, event_props_ct_location_hex_2, event_props_ct_location_hex_3, event_props_ct_location_hex_4, event_props_ct_location_hex_5, event_props_ct_location_hex_6, event_props_ct_location_hex_7, event_props_ct_location_hex_8, event_props_ct_location_hex_9, event_props_ct_location_hex_10, event_props_ct_location_hex_11, event_props_ct_location_hex_12, event_props_ct_location_hex_13, event_props_ct_location_hex_14, event_props_ct_location_hex_15, event_props_ct_location_latitude, event_props_ct_location_longitude, event_props_location_hex_0, event_props_location_hex_1, event_props_location_hex_2, event_props_location_hex_3, event_props_location_hex_4, event_props_location_hex_5, event_props_location_hex_6, event_props_location_hex_7, event_props_location_hex_8, event_props_location_hex_9, event_props_location_hex_10, event_props_location_hex_11, event_props_location_hex_12, event_props_location_hex_13, event_props_location_hex_14, event_props_location_hex_15, event_props_location_latitude, event_props_location_longitude, yyyymmdd, hhmmss, quarter_hour, hh, epoch, updated_epoch, updated_hhmmss, updated_quarter_hour, updated_yyyymmdd, updated_hh, event_props_ct_location_hex_8_city, event_props_ct_location_hex_8_cluster, event_props_location_hex_8_city, event_props_location_hex_8_cluster'

In [36]:
columns_as_string_started = ', '.join(df_postorderstatus_requesting.columns)
columns_as_string_started

'device_info_app_version, device_info_browser, device_info_dimensions_height, device_info_dimensions_unit, device_info_dimensions_width, device_info_dpi, device_info_make, device_info_model, device_info_os_version, device_info_sdk_version, profile_all_identities, profile_email, profile_identity, profile_name, profile_phone, profile_platform, event_props_area, event_props_current_city, event_props_current_cluster, event_props_epoch, event_props_hhmmss, event_props_latitude, event_props_location_accuracy, event_props_longitude, event_props_occurred_date, event_props_yyyymmdd, event_props_ct_app_version, event_props_ctlatitude, event_props_ctlongitude, event_props_ct_source, event_props_ct_session_id, device_info, profile, event_props, created_ist, created_utc, event_props_ct_location_hex_0, event_props_ct_location_hex_1, event_props_ct_location_hex_2, event_props_ct_location_hex_3, event_props_ct_location_hex_4, event_props_ct_location_hex_5, event_props_ct_location_hex_6, event_props_ct_location_hex_7, event_props_ct_location_hex_8, event_props_ct_location_hex_9, event_props_ct_location_hex_10, event_props_ct_location_hex_11, event_props_ct_location_hex_12, event_props_ct_location_hex_13, event_props_ct_location_hex_14, event_props_ct_location_hex_15, event_props_ct_location_latitude, event_props_ct_location_longitude, event_props_location_hex_0, event_props_location_hex_1, event_props_location_hex_2, event_props_location_hex_3, event_props_location_hex_4, event_props_location_hex_5, event_props_location_hex_6, event_props_location_hex_7, event_props_location_hex_8, event_props_location_hex_9, event_props_location_hex_10, event_props_location_hex_11, event_props_location_hex_12, event_props_location_hex_13, event_props_location_hex_14, event_props_location_hex_15, event_props_location_latitude, event_props_location_longitude, yyyymmdd, hhmmss, quarter_hour, hh, epoch, updated_epoch, updated_hhmmss, updated_quarter_hour, updated_yyyymmdd, updated_hh, event_props_ct_location_hex_8_city, event_props_ct_location_hex_8_cluster, event_props_location_hex_8_city, event_props_location_hex_8_cluster'

In [40]:
columns_as_string_dropped = ', '.join(df_postorderstatus_requesting.columns)
columns_as_string_dropped

'device_info_app_version, device_info_browser, device_info_dimensions_height, device_info_dimensions_unit, device_info_dimensions_width, device_info_dpi, device_info_make, device_info_model, device_info_os_version, device_info_sdk_version, profile_all_identities, profile_email, profile_identity, profile_name, profile_phone, profile_platform, event_props_area, event_props_current_city, event_props_current_cluster, event_props_epoch, event_props_hhmmss, event_props_latitude, event_props_location_accuracy, event_props_longitude, event_props_occurred_date, event_props_yyyymmdd, event_props_ct_app_version, event_props_ctlatitude, event_props_ctlongitude, event_props_ct_source, event_props_ct_session_id, device_info, profile, event_props, created_ist, created_utc, event_props_ct_location_hex_0, event_props_ct_location_hex_1, event_props_ct_location_hex_2, event_props_ct_location_hex_3, event_props_ct_location_hex_4, event_props_ct_location_hex_5, event_props_ct_location_hex_6, event_props_ct_location_hex_7, event_props_ct_location_hex_8, event_props_ct_location_hex_9, event_props_ct_location_hex_10, event_props_ct_location_hex_11, event_props_ct_location_hex_12, event_props_ct_location_hex_13, event_props_ct_location_hex_14, event_props_ct_location_hex_15, event_props_ct_location_latitude, event_props_ct_location_longitude, event_props_location_hex_0, event_props_location_hex_1, event_props_location_hex_2, event_props_location_hex_3, event_props_location_hex_4, event_props_location_hex_5, event_props_location_hex_6, event_props_location_hex_7, event_props_location_hex_8, event_props_location_hex_9, event_props_location_hex_10, event_props_location_hex_11, event_props_location_hex_12, event_props_location_hex_13, event_props_location_hex_14, event_props_location_hex_15, event_props_location_latitude, event_props_location_longitude, yyyymmdd, hhmmss, quarter_hour, hh, epoch, updated_epoch, updated_hhmmss, updated_quarter_hour, updated_yyyymmdd, updated_hh, event_props_ct_location_hex_8_city, event_props_ct_location_hex_8_cluster, event_props_location_hex_8_city, event_props_location_hex_8_cluster'

In [45]:
df_postorderstatus_requesting.T

                                                                                       0
device_info_app_version                                                            8.8.1
device_info_browser                                                            MobileApp
device_info_dimensions_height                                                        114
device_info_dimensions_unit                                                           mm
device_info_dimensions_width                                                          47
device_info_dpi                                                                      480
device_info_make                                                                 Oneplus
device_info_model                                                                Cph2381
device_info_os_version                                                                13
device_info_sdk_version                                                            40704
profile_all_identities                 ["rachinsingh@gmail.com","5d9eceea941a7d1c51de...
profile_email                                                      rachinsingh@gmail.com
profile_identity                                                5d9eceea941a7d1c51de0d71
profile_name                                                                Rachin Singh
profile_phone                                                               919711171900
profile_platform                                                                 Android
event_props_area                                                                    None
event_props_current_city                                                           Delhi
event_props_current_cluster                                                 IFFCO Forest
event_props_epoch                                                          1698789755438
event_props_hhmmss                                                                033235
event_props_latitude                                                           28.476086
event_props_location_accuracy                                                        9.2
event_props_longitude                                                           77.05831
event_props_occurred_date                                    Wed Nov 01 2023 03:32:35 am
event_props_yyyymmdd                                                            20231101
event_props_ct_app_version                                                         8.8.1
event_props_ctlatitude                                                              None
event_props_ctlongitude                                                             None
event_props_ct_source                                                             Mobile
event_props_ct_session_id                                                   1.69878975E9
device_info                            {"appVersion":"8.8.1","browser":"MobileApp","d...
profile                                {"all_identities":["rachinsingh@gmail.com","5d...
event_props                            {"app_variant":"v7","cleverTapId":"__3f48e7bbe...
created_ist                                                          2023-11-01 03:32:35
created_utc                                                          2023-10-31 22:02:35
event_props_ct_location_hex_0
event_props_ct_location_hex_1
event_props_ct_location_hex_2
event_props_ct_location_hex_3
event_props_ct_location_hex_4
event_props_ct_location_hex_5
event_props_ct_location_hex_6
event_props_ct_location_hex_7
event_props_ct_location_hex_8
event_props_ct_location_hex_9
event_props_ct_location_hex_10
event_props_ct_location_hex_11
event_props_ct_location_hex_12
event_props_ct_location_hex_13
event_props_ct_location_hex_14
event_props_ct_location_hex_15
event_props_ct_location_latitude                                                    None
event_props_ct_location_longitude                                                   None
event_props_location_hex_0                                               803dfffffffffff
event_props_location_hex_1                                               813dbffffffffff
event_props_location_hex_2                                               823da7fffffffff
event_props_location_hex_3                                               833da1fffffffff
event_props_location_hex_4                                               843da11ffffffff
event_props_location_hex_5                                               853da11bfffffff
event_props_location_hex_6                                               863da11afffffff
event_props_location_hex_7                                               873da11adffffff
event_props_location_hex_8                                               883da11ad5fffff
event_props_location_hex_9                                               893da11ad53ffff
event_props_location_hex_10                                              8a3da11ad517fff
event_props_location_hex_11                                              8b3da11ad513fff
event_props_location_hex_12                                              8c3da11ad5133ff
event_props_location_hex_13                                              8d3da11ad5132ff
event_props_location_hex_14                                              8e3da11ad5132d7
event_props_location_hex_15                                              8f3da11ad5132d3
event_props_location_latitude                                                  28.476086
event_props_location_longitude                                                  77.05831
yyyymmdd                                                                        20231101
hhmmss                                                                            033235
quarter_hour                                                                        0330
hh                                                                                    03
epoch                                                                      1698789755000
updated_epoch                                                              1698789755000
updated_hhmmss                                                                    033235
updated_quarter_hour                                                                0330
updated_yyyymmdd                                                                20231101
updated_hh                                                                            03
event_props_ct_location_hex_8_city                                                  None
event_props_ct_location_hex_8_cluster                                               None
event_props_location_hex_8_city                                                    Delhi
event_props_location_hex_8_cluster                                          IFFCO Forest

In [46]:
df_postorderstatus_requesting.T.to_clipboard()

## bannar_monet

In [4]:

query = f"""
    SELECT 
        *
    FROM
        raw.customer_banner_monetisation_immutable
    WHERE 
        yyyymmdd = '20240110'
        
    select table_name from hive.information_schema.tables where table_schema = 'raw' and table_name like 'clevertap_customer_%' and table_name != 'clevertap_customer_events_master' order by table_name    
    
"""

data = pd.read_sql(query, connection)
data

DatabaseError: {'message': "line 5:9: Table 'hive.raw.customer_banner_monetisation_immutable' does not exist", 'errorCode': 46, 'errorName': 'TABLE_NOT_FOUND', 'errorType': 'USER_ERROR', 'errorLocation': {'lineNumber': 5, 'columnNumber': 9}, 'failureInfo': {'type': 'io.trino.spi.TrinoException', 'message': "line 5:9: Table 'hive.raw.customer_banner_monetisation_immutable' does not exist", 'suppressed': [], 'stack': ['io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)', 'io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1791)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:445)', 'io.trino.sql.tree.Table.accept(Table.java:60)', 'io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:462)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3668)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2407)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:445)', 'io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)', 'io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:462)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:470)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1387)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:445)', 'io.trino.sql.tree.Query.accept(Query.java:107)', 'io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:462)', 'io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:425)', 'io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)', 'io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)', 'io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)', 'io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:193)', 'io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:808)', 'io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:135)', 'io.trino.$gen.Trino_386____20240111_093220_2.call(Unknown Source)', 'com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)', 'com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)', 'com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)', 'java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)', 'java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)', 'java.base/java.lang.Thread.run(Thread.java:829)'], 'errorLocation': {'lineNumber': 5, 'columnNumber': 9}}}

In [ ]:
data