## Imports

In [1]:
import os
import re
import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

from sklearn.model_selection import StratifiedShuffleSplit

import warnings
warnings.filterwarnings('ignore')

In [24]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
## Connection
connection = presto.connect(
        
        host='presto-gateway.processing.data.production.internal',
#     presto.processing.yoda.run
#     presto-gateway.processing.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [4]:
cwd = os.getcwd()
print(cwd)
local_datasource = '/Users/E2074/local-datasets/customer/ads-monetisation/amazon-mintv'
print(local_datasource)

/Users/E2074/analytics/customer/Ads-Monetisation/amazon-minitv
/Users/E2074/local-datasets/customer/ads-monetisation/amazon-mintv

## Datasets & Parameter

In [5]:
## Parameter 
current_date = datetime.now()
start_date = '20240524'
end_date = '20240603'

# Convert date strings to datetime objects
start_dt = datetime.strptime(start_date, '%Y%m%d')
end_dt = datetime.strptime(end_date, '%Y%m%d')
segment_date = end_dt.strftime('%Y-%m-%d')
print(start_date, ' to ' ,end_date)

20240524  to  20240603

### Ads

In [6]:
# Initialize an empty DataFrame to hold the results
df_data = pd.DataFrame()

# Loop through each date in the range
current_dt = start_dt
while current_dt <= end_dt:
    # Format the current date as a string in 'YYYYMMDD' format
    current_date_str = current_dt.strftime('%Y%m%d')
    
    data_query = f"""
    
        WITH ads_base as (
    
        SELECT 
            distinct
            yyyymmdd,
            city,
            CASE 
            WHEN service = 'Bike' THEN 'Bike Lite' 
            WHEN service = 'Cab' THEN 'CabEconomy'
            ELSE service END service,
            userid,
            hh hour,
            pagename,
            CASE 
            WHEN pagename IN ('HomeScreen', 'CaptainSearchScreen') THEN pagename
            WHEN lower(slotname) LIKE '%ontheway%' THEN 'onTheWay'
            WHEN lower(slotname) LIKE '%arrived%' THEN 'arrived'
            WHEN lower(slotname) LIKE '%started%' THEN 'started'
            WHEN ltrim(orderstatus) IS NOT NULL THEN orderstatus
            END screen_slot_name,
            CASE WHEN eventName = 'Ad_Viewable_Impression' THEN adid END viewed,
            CASE WHEN eventName = 'Ad_Click' THEN adid END clicked
        FROM    
            canonical.iceberg_log_telemetry_ads_impressions_immutable_full
        
        WHERE  
            yyyymmdd = '{current_date_str}'
            AND eventname in ('Ad_Viewable_Impression', 'Ad_Click')
            AND responsetype = 'GAMBanner'
            AND city in ('Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Mumbai')
            AND format in ('nativeVideoBanner')
            AND (service in ('Auto', 'Auto NCR', 'Bike', 'Bike Lite', 'Cab', 'CabEconomy', 'Link') or pagename = 'HomeScreen')
        ),
        
        segment AS (
        
        SELECT
            customer_id,
            taxi_ltr_segment ltr_segment,
            taxi_retention_segments retention_segment,
            taxi_lifetime_stage lifetime_stage,
            taxi_service_affinity service_affinity,
            gender_tag gender
        FROM
            datasets.iallocator_customer_segments
        WHERE 
            run_date = '{segment_date}'
        )
        
        SELECT 
            ads_base.*,
            coalesce(ads_base.service, 'HomeScreen') service_name,
            coalesce( ltr_segment, 'UNKNOWN')ltr_segment,
            coalesce( retention_segment, 'UNKNOWN') retention_segment,
            coalesce( lifetime_stage, 'UNKNOWN') lifetime_stage,
            coalesce( service_affinity, 'UNKNOWN') service_affinity,
            coalesce( gender, 'UNKNOWN')gender
        FROM 
            ads_base
        LEFT JOIN 
            segment
            ON ads_base.userid = segment.customer_id
    """

    # Execute the query and get the result as a DataFrame
    df_day = pd.read_sql(data_query, connection)
    
    # Concatenate the result with the existing DataFrame
    df_data = pd.concat([df_data, df_day], ignore_index=True)
    
    print(current_date_str)
    # Move to the next date
    current_dt += timedelta(days=1)


df_data.to_csv( local_datasource + '/analysis_data_{}_{}.csv'.format(start_date, end_date), index=False)

20240524
20240525
20240526
20240527
20240528
20240529
20240530
20240531
20240601
20240602
20240603

In [6]:
df_data = pd.read_csv( local_datasource + '/analysis_data_{}_{}.csv'.format(start_date, end_date))

### Appography

In [11]:
appography_query = f"""

    WITH ads_base as (
        
        SELECT 
            DISTINCT userid
        FROM    
            canonical.iceberg_log_telemetry_ads_impressions_immutable_full
        
        WHERE  
            yyyymmdd >= '{start_date}'
            AND yyyymmdd <= '{end_date}'
            AND eventname in ('Ad_Viewable_Impression', 'Ad_Click')
            AND responsetype = 'GAMBanner'
            AND city in ('Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Mumbai')
            AND format in ('nativeVideoBanner')
            AND (service in ('Auto', 'Auto NCR', 'Bike', 'Bike Lite', 'Cab', 'CabEconomy', 'Link') or pagename = 'HomeScreen')
        ),
        
        appography_data AS (
        SELECT
            user_id,
            app_list
        FROM 
            (
            SELECT
                yyyymmdd,
                id user_id,
                appography_data as app_list,
                row_number() over(partition by id order by updated_epoch desc) updated_seq
            FROM
                customer.info_customer_installed_apps_immutable
            WHERE
                yyyymmdd >= date_format(current_date - INTERVAL '50' DAY, '%Y%m%d')
                and yyyymmdd <= date_format(current_date, '%Y%m%d')
                and id IN (SELECT userid FROM ads_base)
            ) 
        WHERE
            updated_seq = 1
        )
        
        SELECT
            *
        FROM 
            appography_data
"""

df_appography = pd.read_sql(appography_query, connection)
df_appography.to_csv( local_datasource + '/appography_data_{}_{}.csv'.format(start_date, end_date), index=False)

In [7]:
df_appography = pd.read_csv( local_datasource + '/appography_data_{}_{}.csv'.format(start_date, end_date))

### Category mapping

In [8]:
# df_category = pd.read_clipboard()

In [9]:
# df_category.to_csv( local_datasource + '/category_mapping.csv', index=False)
df_category = pd.read_csv( local_datasource + '/category_mapping.csv')
df_category.head(3)

  category            app_name
0   Dating               Aisle
1   Dating              Bumble
2   Dating  Coffee Meets Bagel

## User defined function

In [10]:
agg_dict = {
    'customers': ('userid', 'nunique'),
    'viewed': ('viewed', 'nunique'),
    'clicked': ('clicked', 'nunique'),
}

def calculate_percentage(df, numerator, denominator):
    
    percentage = (df[numerator] * 100.00 / df[denominator]).round(2)
    
    return percentage

def calculate_percentage_columns(df):
        
    df['cta'] = calculate_percentage(df, 'clicked', 'viewed')
    
    return df

##Define a function to extract values between double quotations and trim extra spaces
def extract_and_trim(text):
    
    return [val.strip() for val in re.findall(r'"(.*?)"', text)]

## Analysis

In [9]:
df_data.head(5)

,yyyymmdd,city,service,userid,hour,pagename,screen_slot_name,viewed,clicked,service_name,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender
0,20240524,Hyderabad,,6275e949dce696199d55340b,22,HomeScreen,HomeScreen,ad_6275e949dce696199d55340b_1716568565212,None,,PHH,ELITE,COMMITTED,NO_AFFINITY,MALE
1,20240524,Bangalore,CabEconomy,5de287bcd472d62e9459774f,16,CaptainSearchScreen,CaptainSearchScreen,ad_5de287bcd472d62e9459774f_1716524715744,None,CabEconomy,PHH,SILVER,CHURN_OTB,ONLY_CAB,FEMALE
2,20240524,Bangalore,Auto,6645cf59a31b59235065f83a,23,CaptainSearchScreen,CaptainSearchScreen,ad_6645cf59a31b59235065f83a_1716573150861,None,Auto,HH,HH,HANDHOLDING,LINK_AUTO,MALE
3,20240524,Mumbai,,621c55ba61482dc318a02a18,23,HomeScreen,HomeScreen,ad_621c55ba61482dc318a02a18_1716574639728,None,,PHH,INACTIVE,INACTIVE,UNKNOWN,MALE
4,20240524,Bangalore,Auto,65ec2eae283274d33fb1f4a9,08,CaptainSearchScreen,CaptainSearchScreen,ad_65ec2eae283274d33fb1f4a9_1716440888836,None,Auto,PHH,PLATINUM,HOOK,ONLY_AUTO,FEMALE

In [10]:
df_data.columns

Index(['yyyymmdd', 'city', 'service', 'userid', 'hour', 'pagename',
       'screen_slot_name', 'viewed', 'clicked', 'service_name', 'ltr_segment',
       'retention_segment', 'lifetime_stage', 'service_affinity', 'gender'],
      dtype='object')

In [11]:
df_data['service'].fillna(df_data['pagename'], inplace=True)
df_data

,yyyymmdd,city,service,userid,hour,pagename,screen_slot_name,viewed,clicked,service_name,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender
0,20240524,Hyderabad,,6275e949dce696199d55340b,22,HomeScreen,HomeScreen,ad_6275e949dce696199d55340b_1716568565212,None,,PHH,ELITE,COMMITTED,NO_AFFINITY,MALE
1,20240524,Bangalore,CabEconomy,5de287bcd472d62e9459774f,16,CaptainSearchScreen,CaptainSearchScreen,ad_5de287bcd472d62e9459774f_1716524715744,None,CabEconomy,PHH,SILVER,CHURN_OTB,ONLY_CAB,FEMALE
2,20240524,Bangalore,Auto,6645cf59a31b59235065f83a,23,CaptainSearchScreen,CaptainSearchScreen,ad_6645cf59a31b59235065f83a_1716573150861,None,Auto,HH,HH,HANDHOLDING,LINK_AUTO,MALE
3,20240524,Mumbai,,621c55ba61482dc318a02a18,23,HomeScreen,HomeScreen,ad_621c55ba61482dc318a02a18_1716574639728,None,,PHH,INACTIVE,INACTIVE,UNKNOWN,MALE
4,20240524,Bangalore,Auto,65ec2eae283274d33fb1f4a9,08,CaptainSearchScreen,CaptainSearchScreen,ad_65ec2eae283274d33fb1f4a9_1716440888836,None,Auto,PHH,PLATINUM,HOOK,ONLY_AUTO,FEMALE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20187204,20240603,Hyderabad,Link,63f0f9a0dfeed30718e3e071,10,PostOrderScreen,onTheWay,ad_63f0f9a0dfeed30718e3e071_1717391914381,None,Link,PHH,SILVER,HOOK,LINK_AUTO,MALE
20187205,20240603,Bangalore,CabEconomy,6651df52b46daa1619cfddee,18,PostOrderScreen,arrived,ad_6651df52b46daa1619cfddee_1717421206890,None,CabEconomy,PHH,PLATINUM,COMMITTED,ONLY_AUTO,MALE
20187206,20240603,Chennai,Auto,64b8adf3a6ff71c1b1dbe1f7,09,PostOrderScreen,started,ad_64b8adf3a6ff71c1b1dbe1f7_1717387682347,None,Auto,PHH,PLATINUM,SUSTENANCE,NO_AFFINITY,MALE
20187207,20240603,Bangalore,Link,5d6a29d1a24c96105e2ff242,09,CaptainSearchScreen,CaptainSearchScreen,ad_5d6a29d1a24c96105e2ff242_1717387233811,None,Link,PHH,SILVER,HOOK,ONLY_AUTO,MALE
20187208,20240603,Chennai,Auto,624136f75a102b7cc3b64574,10,PostOrderScreen,onTheWay,ad_624136f75a102b7cc3b64574_1717392352145,None,Auto,PHH,PLATINUM,HOOK,LINK_AUTO,FEMALE

### Pivot view

In [12]:
df_analysis1 = df_data\
.groupby(['yyyymmdd'])\
.agg(**agg_dict)\
.reset_index()

df_analysis1 = calculate_percentage_columns(df_analysis1)
df_analysis1

    yyyymmdd  customers   viewed  clicked   cta
0   20240524     538400   998921     4607  0.46
1   20240525     625422  1364432     4765  0.35
2   20240526     594464  1326198     5844  0.44
3   20240527     706307  1746602     7641  0.44
4   20240528     657464  1865709     4314  0.23
5   20240529     742847  1981602     5704  0.29
6   20240530     804400  2545637     9066  0.36
7   20240531     849958  2563930     8837  0.34
8   20240601     769214  2226874    12039  0.54
9   20240602     552875  1191621     5852  0.49
10  20240603     535653  1098070     3377  0.31

In [13]:
df_analysis2 = df_data\
.groupby(['city'])\
.agg(**agg_dict)\
.reset_index()

df_analysis2 = calculate_percentage_columns(df_analysis2)
df_analysis2

        city  customers   viewed  clicked   cta
0  Bangalore     951598  4884758    25993  0.53
1    Chennai     567673  1998267     6931  0.35
2      Delhi     856151  3520347    11367  0.32
3  Hyderabad    1379540  7097633    25270  0.36
4     Mumbai     182212   636608     2274  0.36

In [14]:
df_analysis3 = df_data\
.groupby(['service_name'])\
.agg(**agg_dict)\
.reset_index()

df_analysis3 = calculate_percentage_columns(df_analysis3)
df_analysis3

  service_name  customers   viewed  clicked   cta
0                 1785458  2396854     3000  0.13
1         Auto    1872890  7434396    35185  0.47
2     Auto NCR       7024    18722       87  0.46
3    Bike Lite     318896   981764     3700  0.38
4   CabEconomy     582579  1686543     9284  0.55
5         Link    1454130  5877908    20757  0.35

In [15]:
df_analysis4 = df_data\
.groupby(['pagename'])\
.agg(**agg_dict)\
.reset_index()

df_analysis4 = calculate_percentage_columns(df_analysis4)
df_analysis4

              pagename  customers    viewed  clicked   cta
0  CaptainSearchScreen    2112268   3330564    35751  1.07
1           HomeScreen    1785458   2396854     3000  0.13
2      PostOrderScreen    2937543  12513889    33081  0.26

In [16]:
df_analysis5 = df_data\
.groupby(['pagename','screen_slot_name'])\
.agg(**agg_dict)\
.reset_index()

df_analysis5 = calculate_percentage_columns(df_analysis5)
df_analysis5

              pagename     screen_slot_name  customers   viewed  clicked   cta
0  CaptainSearchScreen  CaptainSearchScreen    2112268  3330564    35751  1.07
1           HomeScreen           HomeScreen    1785458  2396854     3000  0.13
2      PostOrderScreen              arrived    1479571  2715573     2630  0.10
3      PostOrderScreen             onTheWay    2392191  6151886    16070  0.26
4      PostOrderScreen              started    1760385  3646807    14381  0.39

In [17]:
df_analysis_6 = df_data\
.groupby(['ltr_segment'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_6 = calculate_percentage_columns(df_analysis_6)
df_analysis_6

  ltr_segment  customers    viewed  clicked   cta
0          HH     736221   2273007    10234  0.45
1         PHH    2992567  15575957    59856  0.38
2     UNKNOWN     173054    279193     1741  0.62

In [18]:
df_analysis_7 = df_data\
.groupby(['retention_segment'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_7 = calculate_percentage_columns(df_analysis_7)
df_analysis_7

  retention_segment  customers   viewed  clicked   cta
0           DORMANT     314642   490970     3077  0.63
1             ELITE     412226  4184774    15183  0.36
2              GOLD     872379  4029915    15476  0.38
3                HH     572489  2025462     8724  0.43
4          INACTIVE     160775   241744     1478  0.61
5          PLATINUM     720497  4353573    16457  0.38
6             PRIME      28012   342115     1176  0.34
7            SILVER     647768  2180418     8519  0.39
8           UNKNOWN     173054   279193     1741  0.62

In [19]:
df_analysis_8 = df_data\
.groupby(['lifetime_stage'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_8 = calculate_percentage_columns(df_analysis_8)
df_analysis_8

  lifetime_stage  customers   viewed  clicked   cta
0      CHURN_OTB     145615   432384     1464  0.34
1      COMMITTED     897106  7454210    27602  0.37
2          DETOX      11531    74081      244  0.33
3        DORMANT     314642   490970     3077  0.63
4    HANDHOLDING     572489  2025462     8724  0.43
5           HOOK    1096610  4916099    18407  0.37
6       INACTIVE     160775   241744     1478  0.61
7     SOFT_CHURN      51123   120804      486  0.40
8     SUSTENANCE     478897  2093217     8608  0.41
9        UNKNOWN     173054   279193     1741  0.62

In [20]:
df_analysis_9 = df_data\
.groupby(['service_affinity'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_9 = calculate_percentage_columns(df_analysis_9)
df_analysis_9

  service_affinity  customers   viewed  clicked   cta
0         AUTO_CAB     109932   494128     2276  0.46
1        LINK_AUTO     346609  1706095     6390  0.37
2         LINK_CAB      39783   150078      599  0.40
3      NO_AFFINITY     349192  1752417     7165  0.41
4        ONLY_AUTO    1371517  6607872    28812  0.44
5         ONLY_CAB     193136   784524     3300  0.42
6        ONLY_LINK    1247783  6267605    21265  0.34
7          UNKNOWN     243890   365445     2024  0.55

In [21]:
df_analysis_10 = df_data\
.groupby(['gender'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_10 = calculate_percentage_columns(df_analysis_10)
df_analysis_10

    gender  customers    viewed  clicked   cta
0   FEMALE    1076431   5304946    24025  0.45
1     MALE    2630784  12195363    45175  0.37
2   OTHERS      12874     67509      395  0.59
3  UNKNOWN     181753    560341     2236  0.40

In [22]:
df_analysis_11 = df_data\
.groupby(['city', 'service_name','ltr_segment'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_11 = calculate_percentage_columns(df_analysis_11)
df_analysis_11

         city service_name ltr_segment  customers   viewed  clicked   cta
0   Bangalore                       HH      66402    78650      108  0.14
1   Bangalore                      PHH     303468   421744      369  0.09
2   Bangalore                  UNKNOWN      20546    22938       55  0.24
3   Bangalore         Auto          HH      85472   258472     1953  0.76
4   Bangalore         Auto         PHH     486860  2197147    13738  0.63
5   Bangalore         Auto     UNKNOWN      11566    18187      332  1.83
6   Bangalore    Bike Lite          HH       5247     8028       58  0.72
7   Bangalore    Bike Lite         PHH      30367    55445      358  0.65
8   Bangalore    Bike Lite     UNKNOWN        460      574        6  1.05
9   Bangalore   CabEconomy          HH      24603    65028      491  0.76
10  Bangalore   CabEconomy         PHH     129501   371196     2600  0.70
11  Bangalore   CabEconomy     UNKNOWN       3457     5856      104  1.78
12  Bangalore         Link          HH      52336   159954      782  0.49
13  Bangalore         Link         PHH     295558  1323869     5060  0.38
14  Bangalore         Link     UNKNOWN       5164    11105      110  0.99
15    Chennai                       HH      30718    34285       79  0.23
16    Chennai                      PHH     155461   196583      284  0.14
17    Chennai                  UNKNOWN       8749     9422       26  0.28
18    Chennai         Auto          HH      46721   109574      446  0.41
19    Chennai         Auto         PHH     271855   892122     3225  0.36
20    Chennai         Auto     UNKNOWN       2983     4608       47  1.02
21    Chennai    Bike Lite          HH       3204     5024       29  0.58
22    Chennai    Bike Lite         PHH      23041    38271      211  0.55
23    Chennai    Bike Lite     UNKNOWN        213      329        6  1.82
24    Chennai   CabEconomy          HH      10789    21917      115  0.52
25    Chennai   CabEconomy         PHH      53515   117679      452  0.38
26    Chennai   CabEconomy     UNKNOWN       1010     1682       19  1.13
27    Chennai         Link          HH      27408    59881      250  0.42
28    Chennai         Link         PHH     170475   523139     1723  0.33
29    Chennai         Link     UNKNOWN       1793     3706       30  0.81
30      Delhi                       HH     114560   136977      225  0.16
31      Delhi                      PHH     294845   422296      425  0.10
32      Delhi                  UNKNOWN      48322    54863      147  0.27
33      Delhi         Auto          HH      37551    99698      456  0.46
34      Delhi         Auto         PHH     160261   556387     1774  0.32
35      Delhi         Auto     UNKNOWN       3513     6569       50  0.76
36      Delhi     Auto NCR          HH       1554     3947       27  0.68
37      Delhi     Auto NCR         PHH       5308    14490       59  0.41
38      Delhi     Auto NCR     UNKNOWN        162      286        1  0.35
39      Delhi    Bike Lite          HH      17834    43203      218  0.50
40      Delhi    Bike Lite         PHH     131162   559060     1896  0.34
41      Delhi    Bike Lite     UNKNOWN        821     2059       26  1.26
42      Delhi   CabEconomy          HH      40655   110260      544  0.49
43      Delhi   CabEconomy         PHH     108032   350389     1358  0.39
44      Delhi   CabEconomy     UNKNOWN       5026     9620       62  0.64
45      Delhi         Link          HH      79019   213458      878  0.41
46      Delhi         Link         PHH     244314   923058     3091  0.33
47      Delhi         Link     UNKNOWN       8059    17062      133  0.78
48  Hyderabad                       HH      93367   111118      200  0.18
49  Hyderabad                      PHH     485953   656794      733  0.11
50  Hyderabad                  UNKNOWN      25441    28785       60  0.21
51  Hyderabad         Auto          HH      89573   293753     1321  0.45
52  Hyderabad         Auto         PHH     605489  2704403    10605  0.39
53  Hyderabad         Auto     UNKNOWN       6336    12719      121  0.95
54  Hyderabad    Bike Lite          HH      10949    24932      113  0.45
55  Hyderabad    Bike Lite         PHH      94997   243174      765  0.31
56  Hyderabad    Bike Lite     UNKNOWN        796     1708       14  0.82
57  Hyderabad   CabEconomy          HH      22733    63695      366  0.57
58  Hyderabad   CabEconomy         PHH     139946   431436     2239  0.52
59  Hyderabad   CabEconomy     UNKNOWN       2354     4351       65  1.49
60  Hyderabad         Link          HH      70482   232138      946  0.41
61  Hyderabad         Link         PHH     500901  2398255     7635  0.32
62  Hyderabad         Link     UNKNOWN       4889    13486      118  0.87
63     Mumbai                       HH      40176    58718       98  0.17
64     Mumbai                      PHH      77962   127904      103  0.08
65     Mumbai                  UNKNOWN      27603    37723       88  0.23
66     Mumbai         Auto          HH      17830    52246      255  0.49
67     Mumbai         Auto         PHH      53628   224448      806  0.36
68     Mumbai         Auto     UNKNOWN       3840     6575       57  0.87
69     Mumbai    Bike Lite         PHH          8       19        0  0.00
70     Mumbai   CabEconomy          HH      15354    45391      292  0.64
71     Mumbai   CabEconomy         PHH      25104    81768      503  0.62
72     Mumbai   CabEconomy     UNKNOWN       4205     7133       75  1.05
73     Mumbai         Link          HH         16       41        0  0.00
74     Mumbai         Link         PHH         62      131        2  1.53
75     Mumbai         Link     UNKNOWN          4        7        0  0.00

In [26]:

pd.pivot_table(df_analysis_11, values= ['cta'] , index=['city', 'ltr_segment'],
                       columns=['service_name'])

                        cta
service_name                 Auto Auto NCR Bike Lite CabEconomy  Link
city      ltr_segment
Bangalore HH           0.14  0.76      NaN      0.72       0.76  0.49
          PHH          0.09  0.63      NaN      0.65       0.70  0.38
          UNKNOWN      0.24  1.83      NaN      1.05       1.78  0.99
Chennai   HH           0.23  0.41      NaN      0.58       0.52  0.42
          PHH          0.14  0.36      NaN      0.55       0.38  0.33
          UNKNOWN      0.28  1.02      NaN      1.82       1.13  0.81
Delhi     HH           0.16  0.46     0.68      0.50       0.49  0.41
          PHH          0.10  0.32     0.41      0.34       0.39  0.33
          UNKNOWN      0.27  0.76     0.35      1.26       0.64  0.78
Hyderabad HH           0.18  0.45      NaN      0.45       0.57  0.41
          PHH          0.11  0.39      NaN      0.31       0.52  0.32
          UNKNOWN      0.21  0.95      NaN      0.82       1.49  0.87
Mumbai    HH           0.17  0.49      NaN       NaN       0.64  0.00
          PHH          0.08  0.36      NaN      0.00       0.62  1.53
          UNKNOWN      0.23  0.87      NaN       NaN       1.05  0.00

In [23]:
df_analysis12 = df_data\
.groupby(['city', 'service_name', 'pagename','screen_slot_name'])\
.agg(**agg_dict)\
.reset_index()

df_analysis12 = calculate_percentage_columns(df_analysis12)
df_analysis12

,city,service_name,pagename,screen_slot_name,customers,viewed,clicked,cta
0,Bangalore,,HomeScreen,HomeScreen,390416,523332,532,0.10
1,Bangalore,Auto,CaptainSearchScreen,CaptainSearchScreen,454903,684673,11737,1.71
2,Bangalore,Auto,PostOrderScreen,arrived,217805,380077,306,0.08
3,Bangalore,Auto,PostOrderScreen,onTheWay,367981,839874,1935,0.23
4,Bangalore,Auto,PostOrderScreen,started,284424,588471,2045,0.35
5,Bangalore,Bike Lite,CaptainSearchScreen,CaptainSearchScreen,34157,44657,356,0.80
6,Bangalore,Bike Lite,PostOrderScreen,arrived,2559,3814,3,0.08
7,Bangalore,Bike Lite,PostOrderScreen,onTheWay,5417,10619,37,0.35
8,Bangalore,Bike Lite,PostOrderScreen,started,3045,5084,26,0.51
9,Bangalore,CabEconomy,CaptainSearchScreen,CaptainSearchScreen,114498,131530,2201,1.67
10,Bangalore,CabEconomy,PostOrderScreen,arrived,42831,61826,85,0.14
11,Bangalore,CabEconomy,PostOrderScreen,onTheWay,85082,150468,554,0.37
12,Bangalore,CabEconomy,PostOrderScreen,started,58336,100425,355,0.35
13,Bangalore,Link,CaptainSearchScreen,CaptainSearchScreen,247796,414158,2850,0.69
14,Bangalore,Link,PostOrderScreen,arrived,129712,215967,173,0.08
15,Bangalore,Link,PostOrderScreen,onTheWay,248962,581094,1627,0.28
16,Bangalore,Link,PostOrderScreen,started,159380,301225,1302,0.43
17,Chennai,,HomeScreen,HomeScreen,194928,240290,389,0.16
18,Chennai,Auto,CaptainSearchScreen,CaptainSearchScreen,173089,235587,1929,0.82
19,Chennai,Auto,PostOrderScreen,arrived,92602,129254,85,0.07
20,Chennai,Auto,PostOrderScreen,onTheWay,162433,296992,328,0.11
21,Chennai,Auto,PostOrderScreen,started,189305,349834,1376,0.39
22,Chennai,Bike Lite,CaptainSearchScreen,CaptainSearchScreen,20782,25274,200,0.79
23,Chennai,Bike Lite,PostOrderScreen,arrived,2359,2889,2,0.07
24,Chennai,Bike Lite,PostOrderScreen,onTheWay,5729,8909,16,0.18
25,Chennai,Bike Lite,PostOrderScreen,started,4631,6615,28,0.42
26,Chennai,CabEconomy,CaptainSearchScreen,CaptainSearchScreen,37175,41220,374,0.91
27,Chennai,CabEconomy,PostOrderScreen,arrived,14567,18814,18,0.10
28,Chennai,CabEconomy,PostOrderScreen,onTheWay,30748,50128,95,0.19
29,Chennai,CabEconomy,PostOrderScreen,started,21510,31433,99,0.31
30,Chennai,Link,CaptainSearchScreen,CaptainSearchScreen,102151,151679,1153,0.76
31,Chennai,Link,PostOrderScreen,arrived,59107,84133,33,0.04
32,Chennai,Link,PostOrderScreen,onTheWay,115063,224835,347,0.15
33,Chennai,Link,PostOrderScreen,started,79605,128663,470,0.37
34,Delhi,,HomeScreen,HomeScreen,457727,614136,797,0.13
35,Delhi,Auto,CaptainSearchScreen,CaptainSearchScreen,46157,55462,435,0.78
36,Delhi,Auto,PostOrderScreen,arrived,83547,127857,152,0.12
37,Delhi,Auto,PostOrderScreen,onTheWay,152725,309420,1021,0.33
38,Delhi,Auto,PostOrderScreen,started,98650,169939,672,0.40
39,Delhi,Auto NCR,CaptainSearchScreen,CaptainSearchScreen,1550,1691,19,1.12
40,Delhi,Auto NCR,PostOrderScreen,arrived,2448,3328,5,0.15
41,Delhi,Auto NCR,PostOrderScreen,onTheWay,5022,8773,43,0.49
42,Delhi,Auto NCR,PostOrderScreen,started,3145,4931,20,0.41
43,Delhi,Bike Lite,CaptainSearchScreen,CaptainSearchScreen,45852,60271,529,0.88
44,Delhi,Bike Lite,PostOrderScreen,arrived,70272,127843,157,0.12
45,Delhi,Bike Lite,PostOrderScreen,onTheWay,118024,309470,911,0.29
46,Delhi,Bike Lite,PostOrderScreen,started,60078,106746,543,0.51
47,Delhi,CabEconomy,CaptainSearchScreen,CaptainSearchScreen,32448,37314,349,0.94
48,Delhi,CabEconomy,PostOrderScreen,arrived,58542,85681,147,0.17
49,Delhi,CabEconomy,PostOrderScreen,onTheWay,116190,227125,985,0.43
50,Delhi,CabEconomy,PostOrderScreen,started,70632,120161,483,0.40
51,Delhi,Link,CaptainSearchScreen,CaptainSearchScreen,66738,83620,741,0.89
52,Delhi,Link,PostOrderScreen,arrived,148832,240490,320,0.13
53,Delhi,Link,PostOrderScreen,onTheWay,261544,582592,1828,0.31
54,Delhi,Link,PostOrderScreen,started,145600,246963,1213,0.49
55,Hyderabad,,HomeScreen,HomeScreen,604761,796697,993,0.12
56,Hyderabad,Auto,CaptainSearchScreen,CaptainSearchScreen,472862,631301,5628,0.89
57,Hyderabad,Auto,PostOrderScreen,arrived,312034,531925,481,0.09
58,Hyderabad,Auto,PostOrderScreen,onTheWay,512721,1153753,3123,0.27
59,Hyderabad,Auto,PostOrderScreen,started,362057,712305,2815,0.40
60,Hyderabad,Bike Lite,CaptainSearchScreen,CaptainSearchScreen,88623,104678,548,0.52
61,Hyderabad,Bike Lite,PostOrderScreen,arrived,31959,45188,44,0.10
62,Hyderabad,Bike Lite,PostOrderScreen,onTheWay,49330,79071,150,0.19
63,Hyderabad,Bike Lite,PostOrderScreen,started,27132,42133,150,0.36
64,Hyderabad,CabEconomy,CaptainSearchScreen,CaptainSearchScreen,120917,135484,1665,1.23
65,Hyderabad,CabEconomy,PostOrderScreen,arrived,56208,83679,122,0.15
66,Hyderabad,CabEconomy,PostOrderScreen,onTheWay,98130,177678,565,0.32
67,Hyderabad,CabEconomy,PostOrderScreen,started,61342,105041,318,0.30
68,Hyderabad,Link,CaptainSearchScreen,CaptainSearchScreen,377537,614916,4027,0.65
69,Hyderabad,Link,PostOrderScreen,arrived,286647,525532,445,0.08
70,Hyderabad,Link,PostOrderScreen,onTheWay,424524,984683,2146,0.22
71,Hyderabad,Link,PostOrderScreen,started,285560,549610,2081,0.38
72,Mumbai,,HomeScreen,HomeScreen,145741,224345,289,0.13
73,Mumbai,Auto,CaptainSearchScreen,CaptainSearchScreen,56511,81389,640,0.79
74,Mumbai,Auto,PostOrderScreen,arrived,22522,33551,27,0.08
75,Mumbai,Auto,PostOrderScreen,onTheWay,49084,107422,201,0.19
76,Mumbai,Auto,PostOrderScreen,started,34652,64753,250,0.39
77,Mumbai,Bike Lite,CaptainSearchScreen,CaptainSearchScreen,1,1,0,0.00
78,Mumbai,Bike Lite,PostOrderScreen,arrived,4,7,0,0.00
79,Mumbai,Bike Lite,PostOrderScreen,onTheWay,6,6,0,0.00
80,Mumbai,Bike Lite,PostOrderScreen,started,2,5,0,0.00
81,Mumbai,CabEconomy,CaptainSearchScreen,CaptainSearchScreen,36127,42136,554,1.31
82,Mumbai,CabEconomy,PostOrderScreen,arrived,10019,13704,25,0.18
83,Mumbai,CabEconomy,PostOrderScreen,onTheWay,24964,48940,157,0.32
84,Mumbai,CabEconomy,PostOrderScreen,started,17196,30895,134,0.43
85,Mumbai,Link,PostOrderScreen,arrived,27,33,0,0.00
86,Mumbai,Link,PostOrderScreen,onTheWay,53,89,1,1.12
87,Mumbai,Link,PostOrderScreen,started,32,57,1,1.75

In [24]:

pd.pivot_table(df_analysis12, values= ['cta'] , index=['city', 'service_name'],
                       columns=['screen_slot_name'])

                                       cta
screen_slot_name       CaptainSearchScreen HomeScreen arrived onTheWay started
city      service_name
Bangalore                              NaN       0.10     NaN      NaN     NaN
          Auto                        1.71        NaN    0.08     0.23    0.35
          Bike Lite                   0.80        NaN    0.08     0.35    0.51
          CabEconomy                  1.67        NaN    0.14     0.37    0.35
          Link                        0.69        NaN    0.08     0.28    0.43
Chennai                                NaN       0.16     NaN      NaN     NaN
          Auto                        0.82        NaN    0.07     0.11    0.39
          Bike Lite                   0.79        NaN    0.07     0.18    0.42
          CabEconomy                  0.91        NaN    0.10     0.19    0.31
          Link                        0.76        NaN    0.04     0.15    0.37
Delhi                                  NaN       0.13     NaN      NaN     NaN
          Auto                        0.78        NaN    0.12     0.33    0.40
          Auto NCR                    1.12        NaN    0.15     0.49    0.41
          Bike Lite                   0.88        NaN    0.12     0.29    0.51
          CabEconomy                  0.94        NaN    0.17     0.43    0.40
          Link                        0.89        NaN    0.13     0.31    0.49
Hyderabad                              NaN       0.12     NaN      NaN     NaN
          Auto                        0.89        NaN    0.09     0.27    0.40
          Bike Lite                   0.52        NaN    0.10     0.19    0.36
          CabEconomy                  1.23        NaN    0.15     0.32    0.30
          Link                        0.65        NaN    0.08     0.22    0.38
Mumbai                                 NaN       0.13     NaN      NaN     NaN
          Auto                        0.79        NaN    0.08     0.19    0.39
          Bike Lite                   0.00        NaN    0.00     0.00    0.00
          CabEconomy                  1.31        NaN    0.18     0.32    0.43
          Link                         NaN        NaN    0.00     1.12    1.75

In [28]:
df_analysis_13 = df_data\
.groupby(['city', 'service_name','pagename'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_13 = calculate_percentage_columns(df_analysis_13)
df_analysis_13

,city,service_name,pagename,customers,viewed,clicked,cta
0,Bangalore,,HomeScreen,390416,523332,532,0.10
1,Bangalore,Auto,CaptainSearchScreen,454903,684673,11737,1.71
2,Bangalore,Auto,PostOrderScreen,452580,1808379,4286,0.24
3,Bangalore,Bike Lite,CaptainSearchScreen,34157,44657,356,0.80
4,Bangalore,Bike Lite,PostOrderScreen,6451,19516,66,0.34
5,Bangalore,CabEconomy,CaptainSearchScreen,114498,131530,2201,1.67
6,Bangalore,CabEconomy,PostOrderScreen,110262,312713,994,0.32
7,Bangalore,Link,CaptainSearchScreen,247796,414158,2850,0.69
8,Bangalore,Link,PostOrderScreen,296334,1098238,3102,0.28
9,Chennai,,HomeScreen,194928,240290,389,0.16
10,Chennai,Auto,CaptainSearchScreen,173089,235587,1929,0.82
11,Chennai,Auto,PostOrderScreen,274603,776054,1789,0.23
12,Chennai,Bike Lite,CaptainSearchScreen,20782,25274,200,0.79
13,Chennai,Bike Lite,PostOrderScreen,9142,18412,46,0.25
14,Chennai,CabEconomy,CaptainSearchScreen,37175,41220,374,0.91
15,Chennai,CabEconomy,PostOrderScreen,47006,100369,212,0.21
16,Chennai,Link,CaptainSearchScreen,102151,151679,1153,0.76
17,Chennai,Link,PostOrderScreen,165310,437593,850,0.19
18,Delhi,,HomeScreen,457727,614136,797,0.13
19,Delhi,Auto,CaptainSearchScreen,46157,55462,435,0.78
20,Delhi,Auto,PostOrderScreen,189189,607204,1845,0.30
21,Delhi,Auto NCR,CaptainSearchScreen,1550,1691,19,1.12
22,Delhi,Auto NCR,PostOrderScreen,6437,17031,68,0.40
23,Delhi,Bike Lite,CaptainSearchScreen,45852,60271,529,0.88
24,Delhi,Bike Lite,PostOrderScreen,136875,544056,1611,0.30
25,Delhi,CabEconomy,CaptainSearchScreen,32448,37314,349,0.94
26,Delhi,CabEconomy,PostOrderScreen,144543,432963,1615,0.37
27,Delhi,Link,CaptainSearchScreen,66738,83620,741,0.89
28,Delhi,Link,PostOrderScreen,317943,1070005,3361,0.31
29,Hyderabad,,HomeScreen,604761,796697,993,0.12
30,Hyderabad,Auto,CaptainSearchScreen,472862,631301,5628,0.89
31,Hyderabad,Auto,PostOrderScreen,620829,2397941,6419,0.27
32,Hyderabad,Bike Lite,CaptainSearchScreen,88623,104678,548,0.52
33,Hyderabad,Bike Lite,PostOrderScreen,61218,166390,344,0.21
34,Hyderabad,CabEconomy,CaptainSearchScreen,120917,135484,1665,1.23
35,Hyderabad,CabEconomy,PostOrderScreen,125023,366386,1005,0.27
36,Hyderabad,Link,CaptainSearchScreen,377537,614916,4027,0.65
37,Hyderabad,Link,PostOrderScreen,517342,2059735,4672,0.23
38,Mumbai,,HomeScreen,145741,224345,289,0.13
39,Mumbai,Auto,CaptainSearchScreen,56511,81389,640,0.79
40,Mumbai,Auto,PostOrderScreen,59463,205721,478,0.23
41,Mumbai,Bike Lite,CaptainSearchScreen,1,1,0,0.00
42,Mumbai,Bike Lite,PostOrderScreen,7,18,0,0.00
43,Mumbai,CabEconomy,CaptainSearchScreen,36127,42136,554,1.31
44,Mumbai,CabEconomy,PostOrderScreen,31187,93532,316,0.34
45,Mumbai,Link,PostOrderScreen,82,179,2,1.12

In [31]:
pd.pivot_table(df_analysis_13, values= ['cta'] , index=['city', 'pagename'],
                       columns=['service_name'])

                                cta
service_name                         Auto Auto NCR Bike Lite CabEconomy  Link
city      pagename
Bangalore CaptainSearchScreen   NaN  1.71      NaN      0.80       1.67  0.69
          HomeScreen           0.10   NaN      NaN       NaN        NaN   NaN
          PostOrderScreen       NaN  0.24      NaN      0.34       0.32  0.28
Chennai   CaptainSearchScreen   NaN  0.82      NaN      0.79       0.91  0.76
          HomeScreen           0.16   NaN      NaN       NaN        NaN   NaN
          PostOrderScreen       NaN  0.23      NaN      0.25       0.21  0.19
Delhi     CaptainSearchScreen   NaN  0.78     1.12      0.88       0.94  0.89
          HomeScreen           0.13   NaN      NaN       NaN        NaN   NaN
          PostOrderScreen       NaN  0.30     0.40      0.30       0.37  0.31
Hyderabad CaptainSearchScreen   NaN  0.89      NaN      0.52       1.23  0.65
          HomeScreen           0.12   NaN      NaN       NaN        NaN   NaN
          PostOrderScreen       NaN  0.27      NaN      0.21       0.27  0.23
Mumbai    CaptainSearchScreen   NaN  0.79      NaN      0.00       1.31   NaN
          HomeScreen           0.13   NaN      NaN       NaN        NaN   NaN
          PostOrderScreen       NaN  0.23      NaN      0.00       0.34  1.12

In [32]:
df_analysis_14 = df_data\
.groupby(['city', 'service_name','gender'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_14 = calculate_percentage_columns(df_analysis_14)
df_analysis_14

          city service_name   gender  customers   viewed  clicked   cta
0    Bangalore                FEMALE     110548   152290      129  0.08
1    Bangalore                  MALE     256803   342942      349  0.10
2    Bangalore                OTHERS       1322     1822        3  0.16
3    Bangalore               UNKNOWN      21743    26279       51  0.19
4    Bangalore         Auto   FEMALE     217791   995033     7289  0.73
5    Bangalore         Auto     MALE     346665  1397347     8120  0.58
6    Bangalore         Auto   OTHERS       2006     9670       89  0.92
7    Bangalore         Auto  UNKNOWN      17436    71757      525  0.73
8    Bangalore    Bike Lite   FEMALE       6282    12132      106  0.87
9    Bangalore    Bike Lite     MALE      28649    49914      299  0.60
10   Bangalore    Bike Lite   OTHERS        144      235        3  1.28
11   Bangalore    Bike Lite  UNKNOWN        999     1766       14  0.79
12   Bangalore   CabEconomy   FEMALE      49878   132424     1164  0.88
13   Bangalore   CabEconomy     MALE     102968   296929     1926  0.65
14   Bangalore   CabEconomy   OTHERS        502     1541       10  0.65
15   Bangalore   CabEconomy  UNKNOWN       4213    11187       95  0.85
16   Bangalore         Link   FEMALE      61293   273386     1183  0.43
17   Bangalore         Link     MALE     281374  1178724     4567  0.39
18   Bangalore         Link   OTHERS       1174     5460       37  0.68
19   Bangalore         Link  UNKNOWN       9217    37358      165  0.44
20     Chennai                FEMALE      61022    75961       91  0.12
21     Chennai                  MALE     122559   151211      266  0.18
22     Chennai                OTHERS        570      722        2  0.28
23     Chennai               UNKNOWN      10777    12396       30  0.24
24     Chennai         Auto   FEMALE     139147   468287     1812  0.39
25     Chennai         Auto     MALE     171622   504305     1793  0.36
26     Chennai         Auto   OTHERS       1019     3179       14  0.44
27     Chennai         Auto  UNKNOWN       9771    30533       99  0.32
28     Chennai    Bike Lite   FEMALE       4545     7705       40  0.52
29     Chennai    Bike Lite     MALE      21159    34727      198  0.57
30     Chennai    Bike Lite   OTHERS         77      127        1  0.79
31     Chennai    Bike Lite  UNKNOWN        677     1064        7  0.66
32     Chennai   CabEconomy   FEMALE      21162    43939      205  0.47
33     Chennai   CabEconomy     MALE      42191    93135      365  0.39
34     Chennai   CabEconomy   OTHERS        157      393        4  1.02
35     Chennai   CabEconomy  UNKNOWN       1804     3812       12  0.31
36     Chennai         Link   FEMALE      30476    88707      366  0.41
37     Chennai         Link     MALE     163440   481764     1581  0.33
38     Chennai         Link   OTHERS        549     1662        7  0.42
39     Chennai         Link  UNKNOWN       5211    14593       49  0.34
40       Delhi                FEMALE      96152   135055      132  0.10
41       Delhi                  MALE     322017   432351      539  0.12
42       Delhi                OTHERS       1164     1611        3  0.19
43       Delhi               UNKNOWN      38394    45119      123  0.27
44       Delhi         Auto   FEMALE      63435   220965      812  0.37
45       Delhi         Auto     MALE     132129   423430     1401  0.33
46       Delhi         Auto   OTHERS        578     1955       12  0.61
47       Delhi         Auto  UNKNOWN       5183    16304       55  0.34
48       Delhi     Auto NCR   FEMALE       2275     6274       40  0.64
49       Delhi     Auto NCR     MALE       4553    11923       45  0.38
50       Delhi     Auto NCR   OTHERS         17       71        0  0.00
51       Delhi     Auto NCR  UNKNOWN        179      455        2  0.44
52       Delhi    Bike Lite   FEMALE      33305   155093      587  0.38
53       Delhi    Bike Lite     MALE     112478   433880     1480  0.34
54       Delhi    Bike Lite   OTHERS        376     1700       12  0.71
55       Delhi    Bike Lite  UNKNOWN       3658    13649       61  0.45
56       Delhi   CabEconomy   FEMALE      40149   122603      556  0.45
57       Delhi   CabEconomy     MALE     109764   336605     1361  0.40
58       Delhi   CabEconomy   OTHERS        423     1378        7  0.51
59       Delhi   CabEconomy  UNKNOWN       3377     9683       40  0.41
60       Delhi         Link   FEMALE      56138   211165      809  0.38
61       Delhi         Link     MALE     266439   913075     3173  0.35
62       Delhi         Link   OTHERS        902     3330       17  0.51
63       Delhi         Link  UNKNOWN       7913    26007      103  0.40
64   Hyderabad                FEMALE     166133   223341      243  0.11
65   Hyderabad                  MALE     405278   532827      689  0.13
66   Hyderabad                OTHERS       2424     3316        6  0.18
67   Hyderabad               UNKNOWN      30926    37213       55  0.15
68   Hyderabad         Auto   FEMALE     253932  1166894     5009  0.43
69   Hyderabad         Auto     MALE     424601  1742818     6596  0.38
70   Hyderabad         Auto   OTHERS       3218    15750       93  0.59
71   Hyderabad         Auto  UNKNOWN      19647    85414      349  0.41
72   Hyderabad    Bike Lite   FEMALE      19952    50268      179  0.36
73   Hyderabad    Bike Lite     MALE      83827   212162      685  0.32
74   Hyderabad    Bike Lite   OTHERS        387      934        8  0.86
75   Hyderabad    Bike Lite  UNKNOWN       2576     6452       20  0.31
76   Hyderabad   CabEconomy   FEMALE      49728   146027      846  0.58
77   Hyderabad   CabEconomy     MALE     110630   339635     1746  0.51
78   Hyderabad   CabEconomy   OTHERS        600     1847       16  0.87
79   Hyderabad   CabEconomy  UNKNOWN       4075    11974       62  0.52
80   Hyderabad         Link   FEMALE     108011   499881     1767  0.35
81   Hyderabad         Link     MALE     452685  2072775     6687  0.32
82   Hyderabad         Link   OTHERS       1988    10231       39  0.38
83   Hyderabad         Link  UNKNOWN      13588    60992      206  0.34
84      Mumbai                FEMALE      36477    58158       65  0.11
85      Mumbai                  MALE      87665   136243      164  0.12
86      Mumbai                OTHERS        296      493        0  0.00
87      Mumbai               UNKNOWN      21303    29451       60  0.20
88      Mumbai         Auto   FEMALE      25975   102894      432  0.42
89      Mumbai         Auto     MALE      46490   169717      635  0.37
90      Mumbai         Auto   OTHERS        193      785        8  1.02
91      Mumbai         Auto  UNKNOWN       2640     9873       43  0.44
92      Mumbai    Bike Lite   FEMALE          2        9        0  0.00
93      Mumbai    Bike Lite     MALE          5        9        0  0.00
94      Mumbai    Bike Lite  UNKNOWN          1        1        0  0.00
95      Mumbai   CabEconomy   FEMALE      11511    31982      236  0.74
96      Mumbai   CabEconomy     MALE      31845    98477      612  0.62
97      Mumbai   CabEconomy   OTHERS         96      296        5  1.69
98      Mumbai   CabEconomy  UNKNOWN       1211     3538       17  0.48
99      Mumbai         Link   FEMALE         12       30        2  6.67
100     Mumbai         Link     MALE         65      138        0  0.00
101     Mumbai         Link   OTHERS          1        3        0  0.00
102     Mumbai         Link  UNKNOWN          4        8        0  0.00

In [33]:
pd.pivot_table(df_analysis_14, values= ['cta'] , index=['city', 'gender'],
                       columns=['service_name'])

                    cta
service_name             Auto Auto NCR Bike Lite CabEconomy  Link
city      gender
Bangalore FEMALE   0.08  0.73      NaN      0.87       0.88  0.43
          MALE     0.10  0.58      NaN      0.60       0.65  0.39
          OTHERS   0.16  0.92      NaN      1.28       0.65  0.68
          UNKNOWN  0.19  0.73      NaN      0.79       0.85  0.44
Chennai   FEMALE   0.12  0.39      NaN      0.52       0.47  0.41
          MALE     0.18  0.36      NaN      0.57       0.39  0.33
          OTHERS   0.28  0.44      NaN      0.79       1.02  0.42
          UNKNOWN  0.24  0.32      NaN      0.66       0.31  0.34
Delhi     FEMALE   0.10  0.37     0.64      0.38       0.45  0.38
          MALE     0.12  0.33     0.38      0.34       0.40  0.35
          OTHERS   0.19  0.61     0.00      0.71       0.51  0.51
          UNKNOWN  0.27  0.34     0.44      0.45       0.41  0.40
Hyderabad FEMALE   0.11  0.43      NaN      0.36       0.58  0.35
          MALE     0.13  0.38      NaN      0.32       0.51  0.32
          OTHERS   0.18  0.59      NaN      0.86       0.87  0.38
          UNKNOWN  0.15  0.41      NaN      0.31       0.52  0.34
Mumbai    FEMALE   0.11  0.42      NaN      0.00       0.74  6.67
          MALE     0.12  0.37      NaN      0.00       0.62  0.00
          OTHERS   0.00  1.02      NaN       NaN       1.69  0.00
          UNKNOWN  0.20  0.44      NaN      0.00       0.48  0.00

In [34]:
df_analysis_15 = df_data\
.groupby(['city', 'retention_segment'])\
.agg(**agg_dict)\
.reset_index()

df_analysis_15 = calculate_percentage_columns(df_analysis_15)
df_analysis_15

         city retention_segment  customers   viewed  clicked   cta
0   Bangalore           DORMANT      82103   131119     1381  1.05
1   Bangalore             ELITE     101593  1183171     5597  0.47
2   Bangalore              GOLD     217404  1085186     5589  0.52
3   Bangalore                HH     131183   506715     2805  0.55
4   Bangalore          INACTIVE      37102    56622      605  1.07
5   Bangalore          PLATINUM     182394  1216698     6073  0.50
6   Bangalore             PRIME       6705    85190      382  0.45
7   Bangalore            SILVER     157961   562104     2959  0.53
8   Bangalore           UNKNOWN      35153    57959      602  1.04
9     Chennai           DORMANT      27556    37529      233  0.62
10    Chennai             ELITE      79844   525619     1761  0.34
11    Chennai              GOLD     136589   439731     1452  0.33
12    Chennai                HH      81109   211578      814  0.38
13    Chennai          INACTIVE      12565    16829      103  0.61
14    Chennai          PLATINUM     123369   497010     1610  0.32
15    Chennai             PRIME       3745    30377       97  0.32
16    Chennai            SILVER      89352   219942      733  0.33
17    Chennai           UNKNOWN      13544    19658      128  0.65
18      Delhi           DORMANT      72759   109556      364  0.33
19      Delhi             ELITE      94805   866955     2457  0.28
20      Delhi              GOLD     163351   690644     2144  0.31
21      Delhi                HH     165879   533479     2075  0.39
22      Delhi          INACTIVE      40573    58088      205  0.35
23      Delhi          PLATINUM     130310   712430     2170  0.30
24      Delhi             PRIME       8567    93985      295  0.31
25      Delhi            SILVER     120412   364943     1241  0.34
26      Delhi           UNKNOWN      59495    90273      416  0.46
27  Hyderabad           DORMANT     108164   171661      934  0.54
28  Hyderabad             ELITE     135377  1544540     5167  0.33
29  Hyderabad              GOLD     340106  1692396     5845  0.35
30  Hyderabad                HH     165378   649400     2527  0.39
31  Hyderabad          INACTIVE      48377    75258      422  0.56
32  Hyderabad          PLATINUM     278710  1831237     6304  0.34
33  Hyderabad             PRIME       9382   132419      401  0.30
34  Hyderabad            SILVER     259233   940181     3292  0.35
35  Hyderabad           UNKNOWN      34813    60550      378  0.62
36     Mumbai           DORMANT      24786    41241      165  0.40
37     Mumbai             ELITE       6834    66477      202  0.30
38     Mumbai              GOLD      24337   124319      447  0.36
39     Mumbai                HH      31763   124867      503  0.40
40     Mumbai          INACTIVE      22509    35022      143  0.41
41     Mumbai          PLATINUM      15570    98861      300  0.30
42     Mumbai             PRIME         96      294        1  0.34
43     Mumbai            SILVER      25448    94258      294  0.31
44     Mumbai           UNKNOWN      30869    51272      219  0.43

In [35]:
pd.pivot_table(df_analysis_15, values= ['cta'] , index=['city'],
                       columns=['retention_segment'])

                      cta                                                   \
retention_segment DORMANT ELITE  GOLD    HH INACTIVE PLATINUM PRIME SILVER
city
Bangalore            1.05  0.47  0.52  0.55     1.07     0.50  0.45   0.53
Chennai              0.62  0.34  0.33  0.38     0.61     0.32  0.32   0.33
Delhi                0.33  0.28  0.31  0.39     0.35     0.30  0.31   0.34
Hyderabad            0.54  0.33  0.35  0.39     0.56     0.34  0.30   0.35
Mumbai               0.40  0.30  0.36  0.40     0.41     0.30  0.34   0.31


retention_segment UNKNOWN
city
Bangalore            1.04
Chennai              0.65
Delhi                0.46
Hyderabad            0.62
Mumbai               0.43

## Appography category vs Screen

In [11]:
df_data.head(3)

,yyyymmdd,city,service,userid,hour,pagename,screen_slot_name,viewed,clicked,service_name,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender
0,20240524,Hyderabad,NaN,6275e949dce696199d55340b,22,HomeScreen,HomeScreen,ad_6275e949dce696199d55340b_1716568565212,NaN,NaN,PHH,ELITE,COMMITTED,NO_AFFINITY,MALE
1,20240524,Bangalore,CabEconomy,5de287bcd472d62e9459774f,16,CaptainSearchScreen,CaptainSearchScreen,ad_5de287bcd472d62e9459774f_1716524715744,NaN,CabEconomy,PHH,SILVER,CHURN_OTB,ONLY_CAB,FEMALE
2,20240524,Bangalore,Auto,6645cf59a31b59235065f83a,23,CaptainSearchScreen,CaptainSearchScreen,ad_6645cf59a31b59235065f83a_1716573150861,NaN,Auto,HH,HH,HANDHOLDING,LINK_AUTO,MALE

In [12]:
df_data.columns

Index(['yyyymmdd', 'city', 'service', 'userid', 'hour', 'pagename',
       'screen_slot_name', 'viewed', 'clicked', 'service_name', 'ltr_segment',
       'retention_segment', 'lifetime_stage', 'service_affinity', 'gender'],
      dtype='object')

In [17]:
df_data.shape, df_data.userid.nunique()

((20187209, 15), 3901841)

In [14]:
df_appography.head(1)

                    user_id                                           app_list
0  5d0096dbc0b26018f5e280e5  ["Adobe Lightroom"," Airtel Thanks"," Amazon A...

### Appography work-around

In [15]:
df_category.head(1)

  category app_name
0   Dating    Aisle

In [16]:
df_category['category'] = df_category['category'].str.lower()
df_category['app_name'] = df_category['app_name'].str.lower()
df_category.head(1)

  category app_name
0   dating    aisle

In [20]:
df_customer_installed_apps = df_appography[['user_id', 'app_list']].copy()
df_customer_installed_apps['app_list'] = df_customer_installed_apps['app_list'].apply(lambda x: extract_and_trim(x))

In [21]:
df_customer_installed_apps.head(1)

                    user_id                                           app_list
0  5d0096dbc0b26018f5e280e5  [Adobe Lightroom, Airtel Thanks, Amazon Alexa,...

In [22]:
## Explode list and map all the categories
df_customer_apps_explode = df_customer_installed_apps.explode('app_list')
df_customer_apps_explode['app_list'] = df_customer_apps_explode['app_list'].str.lower()

In [25]:
df_customer_apps_explode\
    .groupby(['app_list'])\
    .agg(customers = ('user_id','nunique'))\
    .sort_values(['customers'],ascending=False)\
    .reset_index()

                        app_list  customers
0                    google maps    3872227
1                        youtube    3865715
2                          gmail    3864923
3                       whatsapp    3778263
4                  google photos    3695566
5                      instagram    3126859
6                       facebook    2671660
7                     truecaller    2591337
8                google calendar    2448593
9                       flipkart    2437591
10                   paytm money    2371060
11               disney+ hotstar    2228044
12                           ola    2103057
13                        zomato    2062987
14                      snapchat    2034283
15                          uber    1981685
16                       netflix    1920565
17                      linkedin    1907152
18                        swiggy    1904400
19                       spotify    1902499
20                      telegram    1866710
21                    jio cinema    1838658
22                 airtel thanks    1626870
23            amazon prime video    1497493
24                        meesho    1420204
25                        myntra    1383676
26                     messenger    1313004
27                         clock    1309353
28                   google news    1248487
29                  google drive    1143296
30                    google pay    1130853
31                       grofers    1044531
32                    bookmyshow    1024065
33                          zoom    1023532
34                 google sheets     959115
35                    wynk music     958631
36                       phonepe     956129
37                          ajio     937197
38                      onedrive     904565
39                       outlook     881708
40                 microsoft 365     805651
41               microsoft teams     797864
42                         paytm     760849
43                       hotstar     718799
44           hdfc mobile banking     715299
45                     ludo king     692643
46                          cred     661907
47                        redbus     643191
48                     dailyhunt     630858
49                          zee5     623786
50                       twitter     607366
51                     bigbasket     585705
52                     pinterest     575501
53                 google slides     562731
54                    adobe scan     515107
55                         groww     507861
56              ms authenticator     498128
57                   axis mobile     479617
58                    mx takatak     476797
59                 urban company     470064
60              candy crush saga     469098
61                     sharechat     468264
62                       sonyliv     454896
63                   google home     444617
64          grofers delivery app     409519
65                       blinkit     401763
66                         zepto     397620
67       samsung galaxy wearable     386693
68                      nobroker     376232
69             where is my train     375385
70                       jiomart     366276
71                     mx player     359445
72                       picsart     354893
73               microsoft excel     346146
74                         ixigo     345043
75                           aha     342085
76                         nykaa     333725
77                   namma yatri     309713
78            irctc rail connect     309111
79                  amazon music     286109
80                 free fire max     285367
81                         dunzo     276239
82                      mobikwik     260025
83                rapido captain     257686
84                      sbi yono     257058
85                      in drive     247338
86        intune  company portal     244755
87                       abhibus     240080
88                       goibibo     224844
89          google authenticator     215942
90                      firstcry     215308
91               kite by zerodha     206583
92                      jiosaavn     203141
93                domino's pizza     197475
94                    makemytrip     196732
95                   imobile pay     190896
96                   booking.com     183072
97                 angel broking     178179
98              google classroom     168163
99                       ms edge     168023
100                        udemy     167578
101                 amazon alexa     157948
102              adobe lightroom     155506
103                  smartthings     150615
104                        jiotv     149637
105                     duolingo     146583
106                   my11circle     139383
107              uber driver app     135938
108                        gaana     134275
109                          uts     129517
110                        webex     129194
111                  8 ball pool     128916
112                        skype     128895
113                  pubg mobile     127673
114                       shopsy     126688
115                    tata cliq     125263
116        intune company portal     124437
117                    pharmeasy     123600
118               ola driver app     105794
119                       indigo     104203
120                     cricbuzz     100387
121                 zerodha kite     100358
122                    splitwise      99572
123                         voot      99468
124                  healthifyme      99160
125                       airbnb      98057
126                   apollo 247      97642
127                        slack      97257
128                      brainly      94149
129                      99acres      93735
130                  magicbricks      92294
131                     blusmart      88803
132               clash of clans      88172
133                     lenskart      87981
134                      purplle      81661
135                         yulu      81644
136                          moj      79752
137                    pocket fm      79223
138                         byju      78529
139                     snapseed      76532
140                    cleartrip      74258
141                       bumble      73264
142                          nps      72202
143                      dream11      69936
144                          oyo      69495
145            swiggy driver app      67582
146                       tinder      66779
147               microsoft lens      63764
148                   mparivahan      62237
149                          1mg      60387
150                    unacademy      59710
151                 medplus mart      57644
152                     inshorts      57170
153                     bhim upi      56964
154                      sun nxt      56749
155                       zivame      56281
156                     coursera      56279
157         call of duty: mobile      55966
158                     cult.fit      52121
159                   quick ride      51505
160            microsoft onenote      50675
161                       fitbit      47509
162                    kfc india      47179
163                          flo      47037
164                       reddit      46995
165            porter driver app      46781
166               physics wallah      45218
167                     among us      44939
168  home workout - no equipment      44938
169                        yatra      43667
170               youcam perfect      42992
171                dmrc momentum      42195
172                   freecharge      41484
173                         josh      39785
174                     hangouts      39605
175               economic times      39372
176                 moneycontrol      38810
177                       upstox      38690
178                fresh to home      38434
179                       practo      37949
180                          h&m      36558
181                   skyscanner      36165
182                      dropbox      35069
183                hungama music      35039
184                  namma metro      33569
185                       driveu      33551
186               ttdevasthanams      32830
187                        hinge      32628
188                       notion      31839
189                       swayam      31625
190               zepp (amazfit)      31137
191            zomato driver app      30990
192                    t savaari      30521
193                       strava      28695
194                 policybazaar      28493
195                   soundcloud      28276
196                    lifestyle      26793
197        delhi metro navigator      26786
198                       mi fit      26492
199               acko insurance      24919
200                   alt balaji      24634
201                       github      24235
202             the souled store      24014
203                    altbalaji      24001
204                   calculator      23237
205             zepto driver app      23172
206                   easemytrip      22676
207                       tummoc      22202
208                  google chat      21617
209                     moj lite      21545
210                     limeroad      21482
211                        happn      21423
212           asphalt 9: legends      19843
213              pizza hut india      19793
214                    zoho mail      19354
215                       signal      18999
216                 myfitnesspal      18303
217                         mint      18220
218                huawei health      18139
219                      netmeds      17677
220                  simplilearn      17188
221              amazon shopping      17136
222                       diksha      16580
223                        aisle      16508
224         shadowfax driver app      16209
225                      trivago      15993
226                    starmaker      15739
227                         zara      15449
228              weather & radar      15444
229                    uber eats      15283
230                namma partner      15251
231            linkedin learning      14729
232              geeks for geeks      14149
233                  apple music      14122
234                     doubtnut      14087
235           chennai metro rail      13896
236                     et money      13674
237                    nykaa man      13463
238             mcdonald's india      13412
239                 rummy circle      13258
240                        viber      13132
241             borzo driver app      12749
242                         jira      12668
243                    pepperfry      12574
244                flightradar24      12511
245                     nestaway      12082
246                     westside      12076
247                bsnl selfcare      12027
248          icicidirect: stocks      11198
249                    goodreads      11041
250             dunzo driver app      10948
251        shiprocket driver app      10890
252                  tripadvisor      10878
253                       moodle      10737
254              starbucks india      10596
255                         ring      10592
256                     sadhguru       9762
257                   quackquack       9539
258              period calendar       9272
259                         vsco       9271
260                          edx       8874
261                 zoho meeting       8533
262            driveu driver app       8458
263         train ticket booking       8251
264                         line       8236
265                    kotak neo       7885
266           the indian express       7346
267                         ebay       7026
268                       aajtak       6904
269      icicidirect markets app       6572
270          fossil smartwatches       6529
271                  accuweather       6465
272                        mfine       6394
273                     evernote       6304
274                        smule       6196
275                  ncert books       6039
276                    free fire       5846
277                    air india       5787
278                       tumblr       5663
279                      vedantu       5611
280                       trello       5507
281                       roposo       5452
282                    sharekhan       5412
283                      vistara       5337
284                    photomath       5290
285              ignou e-content       5236
286                  my bsnl app       5188
287                         wego       5135
288                 espncricinfo       5096
289        money manager expense       5082
290               garmin connect       5048
291             google analytics       5004
292                      okcupid       4896
293                 khan academy       4729
294                     vision11       4728
295                       meetup       4510
296                       wechat       3877
297                  mycbseguide       3834
298               oneplus health       3767
299                   paytm mall       3732
300                       jugnoo       3535
301                        asana       3427
302              hdfc securities       3404
303                     icai bos       3379
304                   trulymadly       3336
305           nike training club       3336
306               e-pg pathshala       3145
307     blinkit delivery partner       3085
308                    flipboard       2966
309                   confluence       2863
310                  officesuite       2852
311        microsoft math solver       2822
312            shemaroome livetv       2757
313                        cisco       2705
314                        kayak       2685
315                       pocket       2664
316                       aakash       2475
317                     spicejet       2386
318                          nba       2378
319                    bloomberg       2366
320                    ndtv news       2362
321                  chegg study       2341
322               file commander       2298
323                  shiksha.com       2274
324                        fittr       2226
325                       embibe       2112
326                    quickride       2100
327                         calm       2066
328                      todoist       2059
329                     spencers       2043
330                  eenadu news       1983
331                   aliexpress       1916
332                     chingari       1904
333                  whitehat jr       1811
334                     bbc news       1787
335                      jiochat       1655
336                     livspace       1650
337              hindustan times       1604
338                      lybrate       1553
339                         miro       1510
340               track my train       1277
341                       feedly       1176
342                 mumbai metro       1149
343                     abp live       1129
344            business standard       1012
345           al jazeera english       1009
346                yahoo finance        998
347          the weather channel        995
348                youcam makeup        969
349                     eros now        963
350                         hike        951
351                      expedia        929
352                 colegeduniya        753
353                      quizlet        661
354                     myteam11        622
355                        fiton        593
356                     homelane        529
357               qr code reader        523
358                    foodpanda        500
359            medibuddy vhealth        497
360                      reuters        495
361           coffee meets bagel        491
362                 club factory        491
363                          cnn        480
364                       prisma        477
365                  flightaware        435
366                         espn        406
367                    cnbc tv18        396
368           metro ride kolkata        390
369            malayala manorama        389
370                      invideo        373
371                  caclubindia        344
372            paytm first games        319
373                  course hero        280
374                yahoo weather        265
375                     1weather        260
376                    aastha tv        259
377                 tunein radio        248
378                my study life        235
379                 the athletic        230
380                         wyze        222
381                      triller        218
382                rosetta stone        218
383                     vidyakul        216
384                      myfab11        215
385                  money lover        208
386                   big bazaar        202
387               stack overflow        174
388                          woo        168
389                        toppr        148
390                shiksha mitra        125
391                    instashop        121
392               skymet weather        109
393                      happify         99
394                      groupme         98
395                 collegedekho         94
396                          nhl         90
397                          mlb         84
398                    bbc sport         77
399                          nfl         75
400                         vero         74
401                       mobvoi         67
402                   weatherbug         58
403               sri sankara tv         46
404                  august home         32
405                      fiitjee         28
406                       voonik         28
407                     cricplay         23
408                       ganesh         22
409         yahoo fantasy sports         21
410                      nishtha         14
411                        likee         14
412                      medlife          9
413                   shemaroome          8
414                     vihealth          7
415                  meritnation          7
416                       ecobee          6
417               bansal classes          5
418            sri ganesh videos          2
419                     divya tv          1

In [26]:
df_customer_apps_mapped = pd.merge(df_customer_apps_explode, 
                                   df_category, 
                                   how = 'left', 
                                   left_on = 'app_list', 
                                   right_on = 'app_name')

df_customer_apps_mapped.head(5)

,user_id,app_list,category,app_name
0,5d0096dbc0b26018f5e280e5,adobe lightroom,tools,adobe lightroom
1,5d0096dbc0b26018f5e280e5,airtel thanks,finance_transactions,airtel thanks
2,5d0096dbc0b26018f5e280e5,amazon alexa,tools,amazon alexa
3,5d0096dbc0b26018f5e280e5,amazon prime video,ott,amazon prime video
4,5d0096dbc0b26018f5e280e5,apple music,streaming_music,apple music

In [40]:
df_customer_apps_mapped.shape

(119113853, 4)

In [41]:
df_customer_category = df_customer_apps_mapped[['user_id', 'category']].drop_duplicates()
df_customer_category.shape

(39678964, 2)

### Appography & Ads

In [43]:
df_customer_category.head(2)

                    user_id              category
0  5d0096dbc0b26018f5e280e5                 tools
1  5d0096dbc0b26018f5e280e5  finance_transactions

In [45]:
df_data.head(2)

,yyyymmdd,city,service,userid,hour,pagename,screen_slot_name,viewed,clicked,service_name,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender
0,20240524,Hyderabad,NaN,6275e949dce696199d55340b,22,HomeScreen,HomeScreen,ad_6275e949dce696199d55340b_1716568565212,NaN,NaN,PHH,ELITE,COMMITTED,NO_AFFINITY,MALE
1,20240524,Bangalore,CabEconomy,5de287bcd472d62e9459774f,16,CaptainSearchScreen,CaptainSearchScreen,ad_5de287bcd472d62e9459774f_1716524715744,NaN,CabEconomy,PHH,SILVER,CHURN_OTB,ONLY_CAB,FEMALE

In [46]:
df_merge = pd.merge(df_data[['yyyymmdd', 'screen_slot_name', 'userid', 'viewed', 'clicked']], 
                    df_customer_category,
                    how='left',
                    left_on='userid',
                    right_on='user_id'
                   )

In [47]:
df_merge.head()

,yyyymmdd,screen_slot_name,userid,viewed,clicked,user_id,category
0,20240524,HomeScreen,6275e949dce696199d55340b,ad_6275e949dce696199d55340b_1716568565212,NaN,6275e949dce696199d55340b,delivery_grocery
1,20240524,HomeScreen,6275e949dce696199d55340b,ad_6275e949dce696199d55340b_1716568565212,NaN,6275e949dce696199d55340b,finance_transactions
2,20240524,HomeScreen,6275e949dce696199d55340b,ad_6275e949dce696199d55340b_1716568565212,NaN,6275e949dce696199d55340b,social
3,20240524,HomeScreen,6275e949dce696199d55340b,ad_6275e949dce696199d55340b_1716568565212,NaN,6275e949dce696199d55340b,tools
4,20240524,HomeScreen,6275e949dce696199d55340b,ad_6275e949dce696199d55340b_1716568565212,NaN,6275e949dce696199d55340b,ecommerce

In [49]:
df_merge.shape

(212722804, 7)

In [50]:
df_analysis1a = df_merge\
.groupby(['category', 'screen_slot_name'])\
.agg(**agg_dict)\
.reset_index()

df_analysis1a = calculate_percentage_columns(df_analysis1a)
df_analysis1a

,category,screen_slot_name,customers,viewed,clicked,cta
0,dating,CaptainSearchScreen,84613,151863,1497,0.99
1,dating,HomeScreen,69411,100122,91,0.09
2,dating,arrived,57454,110794,97,0.09
3,dating,onTheWay,96898,282207,569,0.20
4,dating,started,66174,142094,391,0.28
5,delivery_food,CaptainSearchScreen,1452183,2356580,24563,1.04
6,delivery_food,HomeScreen,1153403,1574366,1626,0.10
7,delivery_food,arrived,973021,1801611,1589,0.09
8,delivery_food,onTheWay,1589578,4171552,10014,0.24
9,delivery_food,started,1167119,2452955,8492,0.35
10,delivery_grocery,CaptainSearchScreen,806319,1379248,15434,1.12
11,delivery_grocery,HomeScreen,666171,935712,909,0.10
12,delivery_grocery,arrived,556186,1057818,982,0.09
13,delivery_grocery,onTheWay,912996,2524036,6160,0.24
14,delivery_grocery,started,656620,1409241,4573,0.32
15,devotional,CaptainSearchScreen,29171,53993,599,1.11
16,devotional,HomeScreen,19549,28762,26,0.09
17,devotional,arrived,17899,35630,25,0.07
18,devotional,onTheWay,28696,85342,173,0.20
19,devotional,started,22487,52095,163,0.31
20,driver_app,CaptainSearchScreen,201893,300923,3463,1.15
21,driver_app,HomeScreen,187126,247336,457,0.18
22,driver_app,arrived,140222,248927,258,0.10
23,driver_app,onTheWay,238533,600678,1688,0.28
24,driver_app,started,168500,346979,1563,0.45
25,ecommerce,CaptainSearchScreen,1681976,2661560,28873,1.08
26,ecommerce,HomeScreen,1416906,1910042,2253,0.12
27,ecommerce,arrived,1158621,2124798,2026,0.10
28,ecommerce,onTheWay,1875097,4816569,12434,0.26
29,ecommerce,started,1386492,2884203,11078,0.38
30,educational,CaptainSearchScreen,420259,681521,6348,0.93
31,educational,HomeScreen,344138,469051,430,0.09
32,educational,arrived,283297,521202,443,0.08
33,educational,onTheWay,459529,1182867,2611,0.22
34,educational,started,347464,719885,2454,0.34
35,entertainment,CaptainSearchScreen,620351,1000109,9420,0.94
36,entertainment,HomeScreen,458423,623904,566,0.09
37,entertainment,arrived,382670,697785,510,0.07
38,entertainment,onTheWay,636258,1641227,3471,0.21
39,entertainment,started,471289,985468,2907,0.29
40,fantasy_sports,CaptainSearchScreen,152998,267419,2925,1.09
41,fantasy_sports,HomeScreen,142893,205689,250,0.12
42,fantasy_sports,arrived,117546,233114,206,0.09
43,fantasy_sports,onTheWay,192162,586694,1470,0.25
44,fantasy_sports,started,134849,306194,1080,0.35
45,finance_investment,CaptainSearchScreen,827057,1352438,13738,1.02
46,finance_investment,HomeScreen,690209,952239,942,0.10
47,finance_investment,arrived,557784,1030062,837,0.08
48,finance_investment,onTheWay,918470,2424967,5607,0.23
49,finance_investment,started,673684,1413045,4739,0.34
50,finance_news,CaptainSearchScreen,51274,91776,894,0.97
51,finance_news,HomeScreen,41973,62448,68,0.11
52,finance_news,arrived,32660,62470,43,0.07
53,finance_news,onTheWay,54784,157591,318,0.20
54,finance_news,started,39538,85529,220,0.26
55,finance_transactions,CaptainSearchScreen,1783143,2869626,30510,1.06
56,finance_transactions,HomeScreen,1500876,2038112,2449,0.12
57,finance_transactions,arrived,1254391,2331298,2196,0.09
58,finance_transactions,onTheWay,2029152,5343490,13662,0.26
59,finance_transactions,started,1490258,3130482,11927,0.38
60,gaming,CaptainSearchScreen,767131,1211469,12664,1.05
61,gaming,HomeScreen,672017,905690,1059,0.12
62,gaming,arrived,556510,1036166,999,0.10
63,gaming,onTheWay,889729,2325248,6352,0.27
64,gaming,started,646854,1355716,5398,0.40
65,health,CaptainSearchScreen,217506,370983,3949,1.06
66,health,HomeScreen,156713,219262,188,0.09
67,health,arrived,132977,247750,186,0.08
68,health,onTheWay,220309,589092,1262,0.21
69,health,started,166576,355857,1002,0.28
70,home_security,CaptainSearchScreen,172,308,1,0.32
71,home_security,HomeScreen,129,173,0,0.00
72,home_security,arrived,116,265,0,0.00
73,home_security,onTheWay,175,563,0,0.00
74,home_security,started,129,366,0,0.00
75,home_service,CaptainSearchScreen,472739,794282,9039,1.14
76,home_service,HomeScreen,345365,481929,463,0.10
77,home_service,arrived,287835,532100,446,0.08
78,home_service,onTheWay,484295,1295500,2800,0.22
79,home_service,started,360198,762275,2240,0.29
80,insurance,CaptainSearchScreen,31119,58526,639,1.09
81,insurance,HomeScreen,24990,38535,37,0.10
82,insurance,arrived,21584,43936,40,0.09
83,insurance,onTheWay,35101,111067,291,0.26
84,insurance,started,25692,59465,176,0.30
85,news,CaptainSearchScreen,904464,1440656,15944,1.11
86,news,HomeScreen,760053,1023697,1243,0.12
87,news,arrived,628495,1157879,1131,0.10
88,news,onTheWay,1015699,2638317,6847,0.26
89,news,started,744579,1553361,5975,0.38
90,news_finance,CaptainSearchScreen,24954,48694,467,0.96
91,news_finance,HomeScreen,20473,32391,38,0.12
92,news_finance,arrived,16652,33608,27,0.08
93,news_finance,onTheWay,27215,86259,170,0.20
94,news_finance,started,19766,45458,107,0.24
95,office,CaptainSearchScreen,1217885,1947413,20014,1.03
96,office,HomeScreen,987009,1343214,1434,0.11
97,office,arrived,807367,1465053,1245,0.08
98,office,onTheWay,1321564,3360273,7688,0.23
99,office,started,978506,2008159,6852,0.34
100,ott,CaptainSearchScreen,1748317,2767853,29287,1.06
101,ott,HomeScreen,1469173,1981320,2300,0.12
102,ott,arrived,1208195,2215113,2055,0.09
103,ott,onTheWay,1957533,5035472,12765,0.25
104,ott,started,1443620,2996072,11305,0.38
105,social,CaptainSearchScreen,2096977,3311638,35591,1.07
106,social,HomeScreen,1770735,2380399,2976,0.13
107,social,arrived,1471754,2703946,2617,0.10
108,social,onTheWay,2377103,6124212,15968,0.26
109,social,started,1749530,3628718,14288,0.39
110,streaming_music,CaptainSearchScreen,1435648,2293334,23652,1.03
111,streaming_music,HomeScreen,1191257,1610984,1793,0.11
112,streaming_music,arrived,989927,1825572,1671,0.09
113,streaming_music,onTheWay,1603038,4161489,10363,0.25
114,streaming_music,started,1185450,2475063,9022,0.36
115,telecom,CaptainSearchScreen,9743,17832,184,1.03
116,telecom,HomeScreen,6882,10261,19,0.19
117,telecom,arrived,6243,12445,8,0.06
118,telecom,onTheWay,9911,28693,62,0.22
119,telecom,started,7918,18430,69,0.37
120,tools,CaptainSearchScreen,2099590,3315902,35639,1.07
121,tools,HomeScreen,1772788,2383161,2980,0.13
122,tools,arrived,1473752,2707746,2621,0.10
123,tools,onTheWay,2380251,6132791,15998,0.26
124,tools,started,1751755,3633395,14315,0.39
125,travel_bookings,CaptainSearchScreen,910255,1508215,15444,1.02
126,travel_bookings,HomeScreen,745859,1040827,1151,0.11
127,travel_bookings,arrived,611870,1156468,995,0.09
128,travel_bookings,onTheWay,997738,2710561,6334,0.23
129,travel_bookings,started,737739,1583930,5537,0.35
130,travel_metro,CaptainSearchScreen,67973,122634,1079,0.88
131,travel_metro,HomeScreen,67014,101713,79,0.08
132,travel_metro,arrived,58896,120556,92,0.08
133,travel_metro,onTheWay,92227,289074,683,0.24
134,travel_metro,started,64400,145344,449,0.31
135,travel_ridehailing,CaptainSearchScreen,1558403,2521146,27321,1.08
136,travel_ridehailing,HomeScreen,1278243,1748503,1969,0.11
137,travel_ridehailing,arrived,1053223,1945624,1749,0.09
138,travel_ridehailing,onTheWay,1724736,4516665,11344,0.25
139,travel_ridehailing,started,1258966,2631384,9540,0.36
140,wearable,CaptainSearchScreen,269823,439843,4575,1.04
141,wearable,HomeScreen,223501,313355,316,0.10
142,wearable,arrived,169513,307855,220,0.07
143,wearable,onTheWay,282888,724474,1453,0.20
144,wearable,started,208022,429076,1214,0.28

In [52]:
pd.pivot_table(df_analysis1a, values= ['cta', 'customers'] , index=['category'],
                       columns=['screen_slot_name'])

                                     cta                                      \
screen_slot_name     CaptainSearchScreen HomeScreen arrived onTheWay started
category
dating                              0.99       0.09    0.09     0.20    0.28
delivery_food                       1.04       0.10    0.09     0.24    0.35
delivery_grocery                    1.12       0.10    0.09     0.24    0.32
devotional                          1.11       0.09    0.07     0.20    0.31
driver_app                          1.15       0.18    0.10     0.28    0.45
ecommerce                           1.08       0.12    0.10     0.26    0.38
educational                         0.93       0.09    0.08     0.22    0.34
entertainment                       0.94       0.09    0.07     0.21    0.29
fantasy_sports                      1.09       0.12    0.09     0.25    0.35
finance_investment                  1.02       0.10    0.08     0.23    0.34
finance_news                        0.97       0.11    0.07     0.20    0.26
finance_transactions                1.06       0.12    0.09     0.26    0.38
gaming                              1.05       0.12    0.10     0.27    0.40
health                              1.06       0.09    0.08     0.21    0.28
home_security                       0.32       0.00    0.00     0.00    0.00
home_service                        1.14       0.10    0.08     0.22    0.29
insurance                           1.09       0.10    0.09     0.26    0.30
news                                1.11       0.12    0.10     0.26    0.38
news_finance                        0.96       0.12    0.08     0.20    0.24
office                              1.03       0.11    0.08     0.23    0.34
ott                                 1.06       0.12    0.09     0.25    0.38
social                              1.07       0.13    0.10     0.26    0.39
streaming_music                     1.03       0.11    0.09     0.25    0.36
telecom                             1.03       0.19    0.06     0.22    0.37
tools                               1.07       0.13    0.10     0.26    0.39
travel_bookings                     1.02       0.11    0.09     0.23    0.35
travel_metro                        0.88       0.08    0.08     0.24    0.31
travel_ridehailing                  1.08       0.11    0.09     0.25    0.36
wearable                            1.04       0.10    0.07     0.20    0.28

                               customers                                   \
screen_slot_name     CaptainSearchScreen HomeScreen    arrived   onTheWay
category
dating                           84613.0    69411.0    57454.0    96898.0
delivery_food                  1452183.0  1153403.0   973021.0  1589578.0
delivery_grocery                806319.0   666171.0   556186.0   912996.0
devotional                       29171.0    19549.0    17899.0    28696.0
driver_app                      201893.0   187126.0   140222.0   238533.0
ecommerce                      1681976.0  1416906.0  1158621.0  1875097.0
educational                     420259.0   344138.0   283297.0   459529.0
entertainment                   620351.0   458423.0   382670.0   636258.0
fantasy_sports                  152998.0   142893.0   117546.0   192162.0
finance_investment              827057.0   690209.0   557784.0   918470.0
finance_news                     51274.0    41973.0    32660.0    54784.0
finance_transactions           1783143.0  1500876.0  1254391.0  2029152.0
gaming                          767131.0   672017.0   556510.0   889729.0
health                          217506.0   156713.0   132977.0   220309.0
home_security                      172.0      129.0      116.0      175.0
home_service                    472739.0   345365.0   287835.0   484295.0
insurance                        31119.0    24990.0    21584.0    35101.0
news                            904464.0   760053.0   628495.0  1015699.0
news_finance                     24954.0    20473.0    16652.0    27215.0
office                         1217885.0   987009.0   807367.0  1321564.0
ott                            1748317.0  1469173.0  1208195.0  1957533.0
social                         2096977.0  1770735.0  1471754.0  2377103.0
streaming_music                1435648.0  1191257.0   989927.0  1603038.0
telecom                           9743.0     6882.0     6243.0     9911.0
tools                          2099590.0  1772788.0  1473752.0  2380251.0
travel_bookings                 910255.0   745859.0   611870.0   997738.0
travel_metro                     67973.0    67014.0    58896.0    92227.0
travel_ridehailing             1558403.0  1278243.0  1053223.0  1724736.0
wearable                        269823.0   223501.0   169513.0   282888.0


screen_slot_name        started
category
dating                  66174.0
delivery_food         1167119.0
delivery_grocery       656620.0
devotional              22487.0
driver_app             168500.0
ecommerce             1386492.0
educational            347464.0
entertainment          471289.0
fantasy_sports         134849.0
finance_investment     673684.0
finance_news            39538.0
finance_transactions  1490258.0
gaming                 646854.0
health                 166576.0
home_security             129.0
home_service           360198.0
insurance               25692.0
news                   744579.0
news_finance            19766.0
office                 978506.0
ott                   1443620.0
social                1749530.0
streaming_music       1185450.0
telecom                  7918.0
tools                 1751755.0
travel_bookings        737739.0
travel_metro            64400.0
travel_ridehailing    1258966.0
wearable               208022.0