## Imports & Connection

In [1]:
import os
import re
import time

import numpy as np
import pandas as pd
import hiplot as hip
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta
from sklearn.utils import resample
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
os.environ['PYDEVD_DISABLE_FILE_VALIDATION'] = '1'

In [2]:
## Connection
connection = presto.connect(
        host='presto-gateway.processing.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

## Parameter & Datasets

In [3]:
current_date = datetime.now()

start_date = '20240512'
end_date = '20240519'
print(start_date, ' to ' ,end_date)

# Convert date strings to datetime objects
start_dt = datetime.strptime(start_date, '%Y%m%d')
end_dt = datetime.strptime(end_date, '%Y%m%d')

segment_date = end_dt.strftime('%Y-%m-%d')

20240512  to  20240519

### Query 1

In [4]:
# Initialize an empty list to hold the DataFrames
df_data = pd.DataFrame()

# Loop through each date in the range
current_dt = start_dt
while current_dt <= end_dt:
    # Format the current date as a string in 'YYYYMMDD' format
    current_date_str = current_dt.strftime('%Y%m%d')

    data_query = f"""

        with olf_data as (

            select
                yyyymmdd,
                city_name,
                service_obj_service_name service_name,
                customer_id,
                order_id,
                order_status,
                modified_order_status,
                spd_fraud_flag,
                CASE WHEN modified_order_status in ('OCARA', 'COBRA', 'COBRM') THEN (customer_cancelled_epoch/1000 - order_requested_epoch/1000) END time_to_cancel_in_sec
            from
                orders.order_logs_fact
            where 
                yyyymmdd = '{current_date_str}'
                and city_name in ('Hyderabad', 'Bangalore', 'Delhi', 'Chennai', 'Jaipur', 'Pune', 'Kolkata')
                and service_obj_service_name in ('Auto', 'Auto Pool', 'AutoPremium', 'Bike Lite', 'Bike Metro', 'Bike Pink', 'Cab Premium', 'CabEconomy', 'CityAuto', 'Link')
            ),

            orderLogsFact as (

            select
                yyyymmdd,
                customer_id,
                city_name,
                service_name
            from
                olf_data
            group by 
                1,2,3,4
            ),

            intervention as (

            SELECT 
                yyyymmdd,
                userId,
                group_tc,
                max(coalesce(dispatch_ad_request, dispatch_ad_response, dispatch_ad_viewable_impression, dispatch_ad_click)) mapping_v1,
                max(coalesce(dispatch_ad_response, dispatch_ad_viewable_impression, dispatch_ad_click)) mapping_v2,
                max(coalesce(dispatch_ad_viewable_impression, dispatch_ad_click)) mapping_v3
            FROM
                (
                SELECT 
                    yyyymmdd,
                    userId,
                    'test' group_tc,
                    CASE WHEN pagename = 'CaptainSearchScreen' AND eventName = 'Ad_Request' THEN yyyymmdd || '-' || userId || '-' || hhmmss END AS dispatch_ad_request,
                    CASE WHEN pagename = 'CaptainSearchScreen' AND eventName = 'Ad_Response' THEN yyyymmdd || '-' || userId || '-' || hhmmss END AS dispatch_ad_response,
                    CASE WHEN pagename = 'CaptainSearchScreen' AND eventName = 'Ad_Viewable_Impression' THEN yyyymmdd || '-' || userId || '-' || hhmmss END AS dispatch_ad_viewable_impression,
                    CASE WHEN pagename = 'CaptainSearchScreen' AND eventName = 'Ad_Click' THEN yyyymmdd || '-' || userId || '-' || hhmmss END AS dispatch_ad_click
                FROM 
                    canonical.iceberg_log_telemetry_ads_impressions_immutable
                WHERE  
                    yyyymmdd = '{current_date_str}'
                    and responseType = 'GAMBanner'
                    and pagename = 'CaptainSearchScreen'
                    and city in ('Hyderabad', 'Bangalore', 'Delhi', 'Chennai', 'Jaipur', 'Pune', 'Kolkata')
                    and service in ('Auto', 'Auto Pool', 'AutoPremium', 'Bike Lite', 'Bike Metro', 'Bike Pink', 'Cab Premium', 'CabEconomy', 'CityAuto', 'Link')                
                    and userId IN (select distinct customer_id from orderLogsFact)

                )
            GROUP BY 1,2,3
            ),

            customer_segment as (

            select 
                customer_id,
                taxi_lifetime_stage customer_segment

            from
                datasets.iallocator_customer_segments
            where 
                run_date = '{segment_date}'
                and taxi_recency_segment != 'INACTIVE'
            ),

            experiment_base as (

            select
                a.yyyymmdd,
                a.city_name,
                a.service_name,
                a.customer_id,
                coalesce(b.group_tc, 'control') group_tc,
                c.customer_segment
            from
                orderLogsFact a
            left join 
                intervention b
                on a.yyyymmdd = b.yyyymmdd
                and a.customer_id = b.userId
            left join 
                customer_segment c
                on a.customer_id = c.customer_id

            group by 1,2,3,4,5,6

            )


            select
                a.*,

                count(distinct order_id) gross_orders,
                count(distinct case when order_status = 'dropped' and spd_fraud_flag != true then order_id end) net_orders,
                count(distinct case when modified_order_status = 'COBRM' then order_id end) cobrm,
                count(distinct case when modified_order_status = 'COBRA' then order_id end) cobra,
                count(distinct case when modified_order_status = 'OCARA' then order_id end) ocara,
                count(distinct case when modified_order_status = 'aborted' then order_id end) aborted,
                count(distinct case when modified_order_status = 'expired' then order_id end) expired,

                avg(CASE WHEN modified_order_status = 'COBRM' THEN time_to_cancel_in_sec END) as avg_cobrm_time,
                avg(CASE WHEN modified_order_status = 'COBRA' THEN time_to_cancel_in_sec END) as avg_cobra_time,
                avg(CASE WHEN modified_order_status = 'OCARA' THEN time_to_cancel_in_sec END) as avg_ocara_time

            from 
                experiment_base a
            join 
                olf_data b
                on a.yyyymmdd = b.yyyymmdd
                and a.customer_id = b.customer_id
                and a.city_name = b.city_name
            group by 1,2,3,4,5,6

    """

    # Execute the query and get the result as a DataFrame
    df_day = pd.read_sql(data_query, connection)
    
    # Concatenate the result with the existing DataFrame
    df_data = pd.concat([df_data, df_day], ignore_index=True)
    
    # Move to the next date
    current_dt += timedelta(days=1)

# Display the concatenated DataFrame
df_data

,yyyymmdd,city_name,service_name,customer_id,group_tc,customer_segment,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,avg_cobrm_time,avg_cobra_time,avg_ocara_time
0,20240512,Hyderabad,Auto,626949e640b3e5c5c9c0a868,control,COMMITTED,1,1,0,0,0,0,0,NaN,NaN,NaN
1,20240512,Delhi,CabEconomy,632bf5d4868f899277b13372,test,COMMITTED,5,1,0,3,1,0,0,NaN,60.0,268.0
2,20240512,Pune,Auto,64002e696ee30010063824ce,test,COMMITTED,1,1,0,0,0,0,0,NaN,NaN,NaN
3,20240512,Bangalore,Auto,5b120e43812a634e420f15fa,control,HOOK,1,0,0,0,1,0,0,NaN,NaN,304.0
4,20240512,Delhi,Link,632341845d3af40e86021dc1,control,COMMITTED,2,1,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10495928,20240519,Bangalore,Auto,5d6f1815a24c96105e370a5d,control,COMMITTED,4,2,0,1,0,0,1,NaN,192.0,NaN
10495929,20240519,Hyderabad,Auto,62fa2006a42e8131dd6ed8d6,control,HOOK,3,2,0,0,1,0,0,NaN,NaN,265.0
10495930,20240519,Chennai,Auto,65dc5f4f8f892e4ff9a74dc0,control,COMMITTED,1,0,0,0,1,0,0,NaN,NaN,341.0
10495931,20240519,Bangalore,Link,646614766f8f1bad18b8460f,test,COMMITTED,2,2,0,0,0,0,0,NaN,NaN,NaN
10495932,20240519,Delhi,Link,6348a760be6aa71cc22c217d,control,CHURN_OTB,1,1,0,0,0,0,0,NaN,NaN,NaN

### Query 2

In [5]:
# Initialize an empty list to hold the DataFrames
df_telemetry_ads = pd.DataFrame()

# Loop through each date in the range
current_dt = start_dt
while current_dt <= end_dt:
    # Format the current date as a string in 'YYYYMMDD' format
    current_date_str = current_dt.strftime('%Y%m%d')

    telemetry_ads = f"""

    with olf_data as (

            select
                yyyymmdd yyyymd,
                customer_id,
                city_name,
                service_obj_service_name service_name
            from
                orders.order_logs_fact
            where 
                yyyymmdd = '{current_date_str}'
                and city_name in ('Hyderabad', 'Bangalore', 'Delhi', 'Chennai', 'Jaipur', 'Pune', 'Kolkata')
                and service_obj_service_name in ('Auto', 'Auto Pool', 'AutoPremium', 'Bike Lite', 'Bike Metro', 'Bike Pink', 'Cab Premium', 'CabEconomy', 'CityAuto', 'Link')
            group by 1,2,3,4
            )

        SELECT 
            yyyymmdd,
            city_name,
            service_name,
            userId,

            -- pagename
            TRY(COUNT(DISTINCT CASE WHEN pagename = 'CaptainSearchScreen' AND eventName = 'Ad_Request' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS css_request,
            TRY(COUNT(DISTINCT CASE WHEN pagename = 'CaptainSearchScreen' AND eventName = 'Ad_Response' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS css_response,
            TRY(COUNT(DISTINCT CASE WHEN pagename = 'CaptainSearchScreen' AND eventName = 'Ad_Viewable_Impression' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS css_viewable_impression,
            TRY(COUNT(DISTINCT CASE WHEN pagename = 'CaptainSearchScreen' AND eventName = 'Ad_Click' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS css_click,

            TRY(COUNT(DISTINCT CASE WHEN pagename = 'PostOrderScreen' AND eventName = 'Ad_Request' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS pos_request,
            TRY(COUNT(DISTINCT CASE WHEN pagename = 'PostOrderScreen' AND eventName = 'Ad_Response' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS pos_response,
            TRY(COUNT(DISTINCT CASE WHEN pagename = 'PostOrderScreen' AND eventName = 'Ad_Viewable_Impression' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS pos_viewable_impression,
            TRY(COUNT(DISTINCT CASE WHEN pagename = 'PostOrderScreen' AND eventName = 'Ad_Click' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS pos_click,

            --screen_slot_name
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'onTheWay' AND eventName = 'Ad_Request' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS onTheWay_request,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'onTheWay' AND eventName = 'Ad_Response' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS onTheWay_response,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'onTheWay' AND eventName = 'Ad_Viewable_Impression' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS onTheWay_viewable_impression,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'onTheWay' AND eventName = 'Ad_Click' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS onTheWay_click,    

            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'arrived' AND eventName = 'Ad_Request' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS arrived_request,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'arrived' AND eventName = 'Ad_Response' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS arrived_response,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'arrived' AND eventName = 'Ad_Viewable_Impression' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS arrived_viewable_impression,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'arrived' AND eventName = 'Ad_Click' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS arrived_click,    

            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'started' AND eventName = 'Ad_Request' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS started_request,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'started' AND eventName = 'Ad_Response' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS started_response,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'started' AND eventName = 'Ad_Viewable_Impression' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS started_viewable_impression,
            TRY(COUNT(DISTINCT CASE WHEN screen_slot_name = 'started' AND eventName = 'Ad_Click' THEN yyyymmdd || '-' || userId || '-' || hhmmss END )) AS started_click

        FROM
        (
        SELECT 
            yyyymmdd,
            city_name,
            service_name,
            userId,
            pagename,
            CASE 
            WHEN pagename IN ('HomeScreen', 'CaptainSearchScreen') THEN pagename
            WHEN lower(slotname) LIKE '%ontheway%' THEN 'onTheWay'
            WHEN lower(slotname) LIKE '%arrived%' THEN 'arrived'
            WHEN lower(slotname) LIKE '%started%' THEN 'started'
            WHEN ltrim(orderstatus) IS NOT NULL THEN orderstatus
            END screen_slot_name,

            eventName,
            hhmmss
        FROM 
            canonical.iceberg_log_telemetry_ads_impressions_immutable 
        JOIN
            olf_data
            on yyyymmdd = yyyymd 
            and customer_id = userId
            and city_name = city
            and service_name = service

        WHERE  
            yyyymmdd = '{current_date_str}'
            and responseType = 'GAMBanner'
            and city in ('Hyderabad', 'Bangalore', 'Delhi', 'Chennai', 'Jaipur', 'Pune', 'Kolkata')
            and service in ('Auto', 'Auto Pool', 'AutoPremium', 'Bike Lite', 'Bike Metro', 'Bike Pink', 'Cab Premium', 'CabEconomy', 'CityAuto', 'Link')        
        )
        GROUP BY 1,2,3,4

    """
    
    # Execute the query and get the result as a DataFrame
    df1_day = pd.read_sql(telemetry_ads, connection)
    
    # Concatenate the result with the existing DataFrame
    df_telemetry_ads = pd.concat([df_telemetry_ads, df1_day], ignore_index=True)
    
    # Move to the next date
    current_dt += timedelta(days=1)

# Display the concatenated DataFrame
df_telemetry_ads

,yyyymmdd,city_name,service_name,userId,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,20240512,Kolkata,Link,638ca7a912ae9f6e1b3aa3c0,0,0,0,0,8,7,4,0,3,5,2,0,2,1,1,0,3,1,1,0
1,20240512,Chennai,CabEconomy,65fb05967af51440f43f13d5,0,0,0,0,12,16,5,0,3,10,2,0,3,2,1,0,6,4,2,0
2,20240512,Delhi,Link,639375d5fc444c74ff14d008,0,0,0,0,8,5,1,0,4,3,0,0,4,2,1,0,0,0,0,0
3,20240512,Chennai,Link,6138e8538709d27434978945,0,0,0,0,5,4,3,0,3,3,2,0,2,1,1,0,0,0,0,0
4,20240512,Kolkata,Link,60ebabe7ac6ff4bb6761e62e,0,0,0,0,4,1,3,0,2,1,3,0,2,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5122293,20240519,Delhi,Link,635aa25cc74d18c7359a9994,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
5122294,20240519,Delhi,Auto,6255368d91957f34da91150f,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5122295,20240519,Bangalore,Bike Lite,63199d7774328c4c3d92708b,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5122296,20240519,Bangalore,Link,633fb0b98521272ac1b13958,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5122297,20240519,Chennai,CabEconomy,6645c73c849c1d97039e3d4c,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## User Define Function

In [6]:
df_data.head(2)

,yyyymmdd,city_name,service_name,customer_id,group_tc,customer_segment,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,avg_cobrm_time,avg_cobra_time,avg_ocara_time
0,20240512,Hyderabad,Auto,626949e640b3e5c5c9c0a868,control,COMMITTED,1,1,0,0,0,0,0,NaN,NaN,NaN
1,20240512,Delhi,CabEconomy,632bf5d4868f899277b13372,test,COMMITTED,5,1,0,3,1,0,0,NaN,60.0,268.0

In [7]:
def calculate_percentage(df, numerator, denominator):
    percentage = (df[numerator] * 100.00 / df[denominator]).round(2)
    return percentage

In [8]:
customer_agg_dict = {
        'customers': ('customer_id', 'nunique'),
        'gross_orders': ('gross_orders', 'sum'),
        'net_orders': ('net_orders', 'sum'),
        'cobrm': ('cobrm', 'sum'),
        'cobra': ('cobra', 'sum'),
        'ocara': ('ocara', 'sum'),
        'aborted': ('aborted', 'sum'),
        'expired': ('expired', 'sum'),
        'cobrm_time': ('avg_cobrm_time', 'median'),
        'cobra_time': ('avg_cobra_time', 'median'),
        'ocara_time': ('avg_ocara_time', 'median')
}

telemetri_agg_dict = {
        'customers': ('customer_id', 'nunique'),
        'gross_orders': ('gross_orders', 'sum'),
        'net_orders': ('net_orders', 'sum'),
        'cobrm': ('cobrm', 'sum'),
        'cobra': ('cobra', 'sum'),
        'ocara': ('ocara', 'sum'),
        'aborted': ('aborted', 'sum'),
        'expired': ('expired', 'sum'),
        'cobrm_time': ('avg_cobrm_time', 'median'),
        'cobra_time': ('avg_cobra_time', 'median'),
        'ocara_time': ('avg_ocara_time', 'median'),

        'css_request': ('css_request', 'sum'),
        'css_response': ('css_response', 'sum'),
        'css_viewable_impression': ('css_viewable_impression', 'sum'),
        'css_click': ('css_click', 'sum'),

        'pos_request': ('pos_request', 'sum'),
        'pos_response': ('pos_response', 'sum'),
        'pos_viewable_impression': ('pos_viewable_impression', 'sum'),
        'pos_click': ('pos_click', 'sum'),

        'onTheWay_request': ('onTheWay_request', 'sum'), 
        'onTheWay_response': ('onTheWay_response', 'sum'), 
        'onTheWay_viewable_impression': ('onTheWay_viewable_impression', 'sum'),
        'onTheWay_click': ('onTheWay_click', 'sum'), 

        'arrived_request': ('arrived_request', 'sum'), 
        'arrived_response': ('arrived_response', 'sum'),
        'arrived_viewable_impression': ('arrived_viewable_impression', 'sum'), 
        'arrived_click': ('arrived_click', 'sum'), 

        'started_request': ('started_request', 'sum'),
        'started_response': ('started_response', 'sum'), 
        'started_viewable_impression': ('started_viewable_impression', 'sum'), 
        'started_click': ('started_click', 'sum'),
}

In [9]:
def sampling(df):
    
    df['group_tc'] = df['group_tc'].astype('category')

    # Create an empty DataFrame to store the sampled data
    sampled_df = pd.DataFrame()

    # Group by 'city_name' and 'service_name'
    grouped = df.groupby(['city_name', 'service_name'])

    for (city, service), group in grouped:
        # Get the proportions of 'customer_segment' within the group
        segment_proportions = group['customer_segment'].value_counts(normalize=True)

        # Get the test-control split proportions within the group
        test_control_split = group['group_tc'].value_counts(normalize=True)

        # Stratify by 'customer_segment' to ensure similar proportions in the sample
        stratified_sample = group.groupby('customer_segment', group_keys=False).apply(
            lambda x: x.sample(frac=1)
        )

        # Split the sampled data into test and control groups maintaining the original proportions
        test_group, control_group = train_test_split(
            stratified_sample, test_size=test_control_split['control'], stratify=stratified_sample['group_tc']
        )

        # Concatenate the test and control groups
        sampled_group = pd.concat([test_group, control_group])

        # Append the sampled group to the sampled_df
        sampled_df = pd.concat([sampled_df, sampled_group])

    # Reset index
    sampled_df.reset_index(drop=True, inplace=True)
    
    return sampled_df

## Check biasness

In [10]:
df_data_agg = df_data\
.groupby(['city_name', 
          'service_name',
          'group_tc'])\
.agg(**customer_agg_dict)\
.reset_index()

In [11]:
df_data_agg

,city_name,service_name,group_tc,customers,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,cobrm_time,cobra_time,ocara_time
0,Bangalore,Auto,control,475490,1788402,713101,14092,475630,269054,1525,311693,67.000000,131.000000,280.000000
1,Bangalore,Auto,test,435344,1722327,673693,18741,506361,239298,1208,279883,48.000000,133.000000,289.000000
2,Bangalore,Auto Pool,control,17454,85797,16573,11106,26230,8589,102,23080,81.000000,136.000000,295.000000
3,Bangalore,Auto Pool,test,7050,45352,7372,5441,17494,4127,28,10835,75.000000,138.000000,313.500000
4,Bangalore,Bike Lite,control,7706,26972,9336,204,10611,3591,32,3076,70.000000,131.000000,367.000000
5,Bangalore,Bike Lite,test,7481,29339,9949,455,11823,3793,34,3149,86.500000,134.000000,363.000000
6,Bangalore,CabEconomy,control,199502,593044,219704,5239,174859,106527,681,85421,101.000000,140.000000,322.000000
7,Bangalore,CabEconomy,test,64041,319284,82060,4878,134397,46697,182,50724,79.000000,139.500000,314.500000
8,Bangalore,Link,control,472690,1552535,675417,16666,440247,221472,2456,188978,87.000000,130.000000,343.000000
9,Bangalore,Link,test,100670,530417,159386,9375,215000,70740,438,74169,73.000000,129.000000,305.000000
10,Chennai,Auto,control,261715,731603,459230,6732,86799,133650,876,42476,104.217647,120.000000,297.000000
11,Chennai,Auto,test,272731,810949,519428,7032,100774,140179,849,40525,112.000000,126.000000,312.500000
12,Chennai,Bike Lite,control,7274,18632,9903,403,3595,3469,38,1091,105.000000,114.000000,338.000000
13,Chennai,Bike Lite,test,7299,20780,10964,519,4097,3876,36,1150,111.605263,116.200000,352.000000
14,Chennai,Bike Pink,control,6483,23283,6400,5434,4813,2777,16,3793,110.000000,124.000000,270.000000
15,Chennai,Bike Pink,test,6289,24106,6560,5928,5267,2803,19,3475,117.000000,130.000000,276.000000
16,Chennai,CabEconomy,control,89566,205467,113480,2725,31802,41807,366,15066,111.000000,123.000000,318.000000
17,Chennai,CabEconomy,test,22822,87656,39520,1818,21111,18029,84,6972,115.000000,128.000000,317.000000
18,Chennai,Link,control,315440,867285,558129,11324,117075,132349,1681,40196,105.333333,121.000000,324.000000
19,Chennai,Link,test,43104,169312,88521,5291,34886,30455,184,9185,107.000000,119.000000,296.000000
20,Delhi,Auto,control,194092,579472,284267,11449,101290,114531,493,66097,118.000000,127.000000,297.000000
21,Delhi,Auto,test,202188,619712,298998,15051,122823,116088,450,64751,123.500000,134.000000,324.000000
22,Delhi,Auto Pool,control,103,305,55,65,47,28,0,110,110.000000,148.333333,317.666667
23,Delhi,Auto Pool,test,49,232,48,43,64,23,0,53,85.000000,160.750000,263.500000
24,Delhi,Bike Lite,control,111122,397530,236391,3491,64982,70397,399,19666,109.166667,123.500000,358.000000
25,Delhi,Bike Lite,test,138278,546519,326084,5371,95150,93393,488,22849,114.000000,131.000000,372.833333
26,Delhi,Bike Metro,control,24722,67258,40006,305,11989,11991,51,2587,112.500000,111.000000,315.000000
27,Delhi,Bike Metro,test,25998,77352,45916,557,14496,13489,57,2474,100.000000,121.000000,333.333333
28,Delhi,CabEconomy,control,232581,540548,274341,7327,79243,133602,1188,44074,122.000000,129.000000,393.500000
29,Delhi,CabEconomy,test,38238,144341,56703,5783,35124,32278,136,14028,126.333333,136.000000,374.666667
30,Delhi,Link,control,510793,1363015,819118,16542,183803,268843,2587,65880,119.000000,123.000000,376.000000
31,Delhi,Link,test,79294,320957,142148,8367,85237,63152,288,20549,114.388889,132.400000,356.500000
32,Hyderabad,Auto,control,416811,1098457,580792,10647,222996,175701,1378,104343,86.000000,146.333333,316.000000
33,Hyderabad,Auto,test,516676,1460993,787652,15165,308460,220541,1467,124143,82.000000,152.000000,331.000000
34,Hyderabad,Auto Pool,control,19168,69315,13038,12315,20003,5990,78,17779,86.000000,147.500000,335.666667
35,Hyderabad,Auto Pool,test,9144,47463,10081,7081,16386,4334,16,9494,83.000000,154.000000,352.000000
36,Hyderabad,Bike Lite,control,28836,58863,37326,392,8084,9677,122,2697,98.000000,118.000000,341.000000
37,Hyderabad,Bike Lite,test,2902,10270,5338,246,2201,1826,17,584,93.000000,122.291667,307.500000
38,Hyderabad,CabEconomy,control,175445,403985,182840,4101,99389,66444,415,50395,105.850000,137.000000,340.000000
39,Hyderabad,CabEconomy,test,45526,187364,61389,3385,70215,28979,96,23079,99.000000,147.000000,337.708333
40,Hyderabad,Link,control,690977,1706114,1016290,15140,292816,243646,3277,123289,91.000000,128.000000,345.000000
41,Hyderabad,Link,test,85815,333200,151979,6612,94051,49452,331,29451,86.000000,138.000000,318.000000
42,Jaipur,Auto,control,57591,148054,70610,1698,35320,29174,167,10694,129.875000,139.500000,350.000000
43,Jaipur,Auto,test,54916,154583,73730,2188,38778,29841,135,9456,135.000000,136.500000,349.500000
44,Jaipur,Bike Lite,control,31734,91128,41071,407,25283,15745,139,8068,116.000000,131.708333,418.000000
45,Jaipur,Bike Lite,test,33388,107957,47652,569,32470,18056,126,8594,121.000000,135.000000,419.250000
46,Jaipur,Link,control,101747,243714,128010,1363,53428,45504,430,14247,127.000000,132.750000,399.000000
47,Jaipur,Link,test,20826,86819,29236,1352,34245,15613,66,6115,136.000000,134.000000,358.000000
48,Kolkata,Bike Lite,control,3860,8330,4276,132,1421,1670,12,765,89.000000,125.000000,358.000000
49,Kolkata,Bike Lite,test,15,40,15,0,2,10,1,12,NaN,203.500000,432.000000
50,Kolkata,CabEconomy,control,45918,103128,45278,1069,18284,28059,356,9974,129.000000,151.500000,363.000000
51,Kolkata,CabEconomy,test,1566,3388,1359,119,538,1076,9,282,120.277778,152.000000,386.500000
52,Kolkata,Link,control,187821,488281,283337,1981,72210,102102,863,26021,115.000000,135.000000,373.000000
53,Kolkata,Link,test,6065,12250,6840,158,1674,3016,19,495,95.500000,131.000000,415.000000
54,Pune,Auto,control,77012,214453,119325,1274,36916,38206,139,18148,120.000000,123.000000,252.000000
55,Pune,Auto,test,71057,207487,114624,1619,40449,34369,117,15933,118.666667,128.500000,275.000000
56,Pune,CabEconomy,control,58519,133382,74317,1149,22859,23677,129,11170,124.000000,121.500000,301.500000
57,Pune,CabEconomy,test,11757,43878,18541,916,12269,7972,20,4123,111.000000,127.000000,296.000000

In [12]:
df_data_agg['g2n'] = calculate_percentage(df_data_agg, 'net_orders', 'gross_orders')
df_data_agg['% cobrm'] = calculate_percentage(df_data_agg, 'cobrm', 'gross_orders')
df_data_agg['% cobra'] = calculate_percentage(df_data_agg, 'cobra', 'gross_orders')
df_data_agg['% ocara'] = calculate_percentage(df_data_agg, 'ocara', 'gross_orders')

df_data_agg[['city_name', 'group_tc','customers', 'g2n', '% cobrm', '% cobra', '% ocara']]

    city_name group_tc  customers    g2n  % cobrm  % cobra  % ocara
0   Bangalore  control     475490  39.87     0.79    26.60    15.04
1   Bangalore     test     435344  39.12     1.09    29.40    13.89
2   Bangalore  control      17454  19.32    12.94    30.57    10.01
3   Bangalore     test       7050  16.26    12.00    38.57     9.10
4   Bangalore  control       7706  34.61     0.76    39.34    13.31
5   Bangalore     test       7481  33.91     1.55    40.30    12.93
6   Bangalore  control     199502  37.05     0.88    29.48    17.96
7   Bangalore     test      64041  25.70     1.53    42.09    14.63
8   Bangalore  control     472690  43.50     1.07    28.36    14.27
9   Bangalore     test     100670  30.05     1.77    40.53    13.34
10    Chennai  control     261715  62.77     0.92    11.86    18.27
11    Chennai     test     272731  64.05     0.87    12.43    17.29
12    Chennai  control       7274  53.15     2.16    19.29    18.62
13    Chennai     test       7299  52.76     2.50    19.72    18.65
14    Chennai  control       6483  27.49    23.34    20.67    11.93
15    Chennai     test       6289  27.21    24.59    21.85    11.63
16    Chennai  control      89566  55.23     1.33    15.48    20.35
17    Chennai     test      22822  45.09     2.07    24.08    20.57
18    Chennai  control     315440  64.35     1.31    13.50    15.26
19    Chennai     test      43104  52.28     3.12    20.60    17.99
20      Delhi  control     194092  49.06     1.98    17.48    19.76
21      Delhi     test     202188  48.25     2.43    19.82    18.73
22      Delhi  control        103  18.03    21.31    15.41     9.18
23      Delhi     test         49  20.69    18.53    27.59     9.91
24      Delhi  control     111122  59.46     0.88    16.35    17.71
25      Delhi     test     138278  59.67     0.98    17.41    17.09
26      Delhi  control      24722  59.48     0.45    17.83    17.83
27      Delhi     test      25998  59.36     0.72    18.74    17.44
28      Delhi  control     232581  50.75     1.36    14.66    24.72
29      Delhi     test      38238  39.28     4.01    24.33    22.36
30      Delhi  control     510793  60.10     1.21    13.49    19.72
31      Delhi     test      79294  44.29     2.61    26.56    19.68
32  Hyderabad  control     416811  52.87     0.97    20.30    16.00
33  Hyderabad     test     516676  53.91     1.04    21.11    15.10
34  Hyderabad  control      19168  18.81    17.77    28.86     8.64
35  Hyderabad     test       9144  21.24    14.92    34.52     9.13
36  Hyderabad  control      28836  63.41     0.67    13.73    16.44
37  Hyderabad     test       2902  51.98     2.40    21.43    17.78
38  Hyderabad  control     175445  45.26     1.02    24.60    16.45
39  Hyderabad     test      45526  32.76     1.81    37.48    15.47
40  Hyderabad  control     690977  59.57     0.89    17.16    14.28
41  Hyderabad     test      85815  45.61     1.98    28.23    14.84
42     Jaipur  control      57591  47.69     1.15    23.86    19.70
43     Jaipur     test      54916  47.70     1.42    25.09    19.30
44     Jaipur  control      31734  45.07     0.45    27.74    17.28
45     Jaipur     test      33388  44.14     0.53    30.08    16.73
46     Jaipur  control     101747  52.52     0.56    21.92    18.67
47     Jaipur     test      20826  33.67     1.56    39.44    17.98
48    Kolkata  control       3860  51.33     1.58    17.06    20.05
49    Kolkata     test         15  37.50     0.00     5.00    25.00
50    Kolkata  control      45918  43.90     1.04    17.73    27.21
51    Kolkata     test       1566  40.11     3.51    15.88    31.76
52    Kolkata  control     187821  58.03     0.41    14.79    20.91
53    Kolkata     test       6065  55.84     1.29    13.67    24.62
54       Pune  control      77012  55.64     0.59    17.21    17.82
55       Pune     test      71057  55.24     0.78    19.49    16.56
56       Pune  control      58519  55.72     0.86    17.14    17.75
57       Pune     test      11757  42.26     2.09    27.96    18.17

In [13]:
df_data_agg[['city_name', 'service_name', 'group_tc','customers']]

    city_name service_name group_tc  customers
0   Bangalore         Auto  control     475490
1   Bangalore         Auto     test     435344
2   Bangalore    Auto Pool  control      17454
3   Bangalore    Auto Pool     test       7050
4   Bangalore    Bike Lite  control       7706
5   Bangalore    Bike Lite     test       7481
6   Bangalore   CabEconomy  control     199502
7   Bangalore   CabEconomy     test      64041
8   Bangalore         Link  control     472690
9   Bangalore         Link     test     100670
10    Chennai         Auto  control     261715
11    Chennai         Auto     test     272731
12    Chennai    Bike Lite  control       7274
13    Chennai    Bike Lite     test       7299
14    Chennai    Bike Pink  control       6483
15    Chennai    Bike Pink     test       6289
16    Chennai   CabEconomy  control      89566
17    Chennai   CabEconomy     test      22822
18    Chennai         Link  control     315440
19    Chennai         Link     test      43104
20      Delhi         Auto  control     194092
21      Delhi         Auto     test     202188
22      Delhi    Auto Pool  control        103
23      Delhi    Auto Pool     test         49
24      Delhi    Bike Lite  control     111122
25      Delhi    Bike Lite     test     138278
26      Delhi   Bike Metro  control      24722
27      Delhi   Bike Metro     test      25998
28      Delhi   CabEconomy  control     232581
29      Delhi   CabEconomy     test      38238
30      Delhi         Link  control     510793
31      Delhi         Link     test      79294
32  Hyderabad         Auto  control     416811
33  Hyderabad         Auto     test     516676
34  Hyderabad    Auto Pool  control      19168
35  Hyderabad    Auto Pool     test       9144
36  Hyderabad    Bike Lite  control      28836
37  Hyderabad    Bike Lite     test       2902
38  Hyderabad   CabEconomy  control     175445
39  Hyderabad   CabEconomy     test      45526
40  Hyderabad         Link  control     690977
41  Hyderabad         Link     test      85815
42     Jaipur         Auto  control      57591
43     Jaipur         Auto     test      54916
44     Jaipur    Bike Lite  control      31734
45     Jaipur    Bike Lite     test      33388
46     Jaipur         Link  control     101747
47     Jaipur         Link     test      20826
48    Kolkata    Bike Lite  control       3860
49    Kolkata    Bike Lite     test         15
50    Kolkata   CabEconomy  control      45918
51    Kolkata   CabEconomy     test       1566
52    Kolkata         Link  control     187821
53    Kolkata         Link     test       6065
54       Pune         Auto  control      77012
55       Pune         Auto     test      71057
56       Pune   CabEconomy  control      58519
57       Pune   CabEconomy     test      11757

In [14]:
df_data.query("group_tc == 'test'")["customer_segment"].value_counts(True)

customer_segment
COMMITTED      0.427750
HOOK           0.281174
SUSTENANCE     0.118078
HANDHOLDING    0.099084
DORMANT        0.038725
CHURN_OTB      0.018146
UNKNOWN        0.013974
SOFT_CHURN     0.001624
DETOX          0.001446
Name: proportion, dtype: float64

In [15]:
df_data.query("group_tc == 'control'")["customer_segment"].value_counts(True)

customer_segment
COMMITTED      0.404108
HOOK           0.279932
SUSTENANCE     0.120079
HANDHOLDING    0.106647
DORMANT        0.045096
CHURN_OTB      0.019936
UNKNOWN        0.018022
DETOX          0.003814
SOFT_CHURN     0.002366
Name: proportion, dtype: float64

### Sampling

In [16]:
df_sampled = sampling(df_data)

In [17]:
df_sampled.query("group_tc == 'test'")["customer_segment"].value_counts(True)

customer_segment
COMMITTED      0.427750
HOOK           0.281174
SUSTENANCE     0.118078
HANDHOLDING    0.099084
DORMANT        0.038725
CHURN_OTB      0.018146
UNKNOWN        0.013974
SOFT_CHURN     0.001624
DETOX          0.001446
Name: proportion, dtype: float64

In [18]:
df_sampled.query("group_tc == 'control'")["customer_segment"].value_counts(True)

customer_segment
COMMITTED      0.404108
HOOK           0.279932
SUSTENANCE     0.120079
HANDHOLDING    0.106647
DORMANT        0.045096
CHURN_OTB      0.019936
UNKNOWN        0.018022
DETOX          0.003814
SOFT_CHURN     0.002366
Name: proportion, dtype: float64

In [19]:
df_test = df_sampled\
.groupby(['city_name', 
          'service_name',
#           'customer_segment',
          'group_tc'])\
.agg(**customer_agg_dict)\
.reset_index()

In [20]:
df_test['g2n'] = calculate_percentage(df_test, 'net_orders', 'gross_orders')
df_test['% cobrm'] = calculate_percentage(df_test, 'cobrm', 'gross_orders')
df_test['% cobra'] = calculate_percentage(df_test, 'cobra', 'gross_orders')
df_test['% ocara'] = calculate_percentage(df_test, 'ocara', 'gross_orders')

df_test[['city_name', 
         'service_name', 
         'group_tc','customers', 'g2n', '% cobrm', '% cobra', '% ocara']]

,city_name,service_name,group_tc,customers,g2n,% cobrm,% cobra,% ocara
0,Bangalore,Auto,control,458934,40.57,0.78,26.33,14.89
1,Bangalore,Auto,test,423102,39.71,1.08,29.19,13.78
2,Bangalore,Auto Pool,control,16921,19.64,12.83,30.53,10.01
3,Bangalore,Auto Pool,test,6930,16.45,11.93,38.60,9.08
4,Bangalore,Bike Lite,control,7431,35.38,0.75,39.07,13.06
5,Bangalore,Bike Lite,test,7247,34.46,1.56,40.08,12.72
6,Bangalore,Bike Metro,control,0,NaN,NaN,NaN,NaN
7,Bangalore,Bike Metro,test,0,NaN,NaN,NaN,NaN
8,Bangalore,Bike Pink,control,0,NaN,NaN,NaN,NaN
9,Bangalore,Bike Pink,test,0,NaN,NaN,NaN,NaN
10,Bangalore,CabEconomy,control,193595,37.78,0.88,29.18,17.73
11,Bangalore,CabEconomy,test,62711,26.07,1.53,41.92,14.59
12,Bangalore,Link,control,459146,44.18,1.06,28.12,14.02
13,Bangalore,Link,test,99063,30.35,1.75,40.41,13.28
14,Chennai,Auto,control,256756,63.43,0.91,11.69,17.98
15,Chennai,Auto,test,269015,64.54,0.85,12.29,17.07
16,Chennai,Auto Pool,control,0,NaN,NaN,NaN,NaN
17,Chennai,Auto Pool,test,0,NaN,NaN,NaN,NaN
18,Chennai,Bike Lite,control,7087,53.97,2.16,19.17,18.10
19,Chennai,Bike Lite,test,7189,53.31,2.47,19.59,18.41
20,Chennai,Bike Metro,control,0,NaN,NaN,NaN,NaN
21,Chennai,Bike Metro,test,0,NaN,NaN,NaN,NaN
22,Chennai,Bike Pink,control,6186,28.18,23.17,20.68,11.94
23,Chennai,Bike Pink,test,6045,27.89,24.31,21.99,11.56
24,Chennai,CabEconomy,control,87675,56.06,1.30,15.23,20.01
25,Chennai,CabEconomy,test,22545,45.52,2.05,23.89,20.46
26,Chennai,Link,control,310167,64.92,1.29,13.38,14.95
27,Chennai,Link,test,42773,52.59,3.06,20.55,17.88
28,Delhi,Auto,control,187597,49.98,1.91,17.24,19.50
29,Delhi,Auto,test,196479,49.09,2.37,19.59,18.50
30,Delhi,Auto Pool,control,100,18.21,21.19,15.56,9.27
31,Delhi,Auto Pool,test,49,20.69,18.53,27.59,9.91
32,Delhi,Bike Lite,control,108844,60.03,0.86,16.17,17.43
33,Delhi,Bike Lite,test,136245,60.07,0.96,17.28,16.89
34,Delhi,Bike Metro,control,24234,60.08,0.45,17.62,17.51
35,Delhi,Bike Metro,test,25587,59.87,0.71,18.55,17.18
36,Delhi,Bike Pink,control,0,NaN,NaN,NaN,NaN
37,Delhi,Bike Pink,test,0,NaN,NaN,NaN,NaN
38,Delhi,CabEconomy,control,225410,51.82,1.33,14.39,24.20
39,Delhi,CabEconomy,test,37519,39.87,3.96,24.14,22.19
40,Delhi,Link,control,496372,61.03,1.19,13.27,19.19
41,Delhi,Link,test,78138,44.74,2.57,26.41,19.49
42,Hyderabad,Auto,control,405946,53.78,0.96,19.96,15.69
43,Hyderabad,Auto,test,506354,54.66,1.02,20.80,14.88
44,Hyderabad,Auto Pool,control,18390,19.29,17.67,28.91,8.60
45,Hyderabad,Auto Pool,test,8973,21.58,14.91,34.41,9.05
46,Hyderabad,Bike Lite,control,28429,64.09,0.65,13.51,16.11
47,Hyderabad,Bike Lite,test,2874,52.37,2.38,21.25,17.65
48,Hyderabad,Bike Metro,control,0,NaN,NaN,NaN,NaN
49,Hyderabad,Bike Metro,test,0,NaN,NaN,NaN,NaN
50,Hyderabad,Bike Pink,control,0,NaN,NaN,NaN,NaN
51,Hyderabad,Bike Pink,test,0,NaN,NaN,NaN,NaN
52,Hyderabad,CabEconomy,control,169937,46.46,0.99,24.18,16.07
53,Hyderabad,CabEconomy,test,44545,33.43,1.76,37.17,15.37
54,Hyderabad,Link,control,674746,60.45,0.87,16.87,13.91
55,Hyderabad,Link,test,84790,46.10,1.95,28.00,14.74
56,Jaipur,Auto,control,54708,49.27,1.08,23.31,19.09
57,Jaipur,Auto,test,52511,49.15,1.35,24.57,18.76
58,Jaipur,Auto Pool,control,0,NaN,NaN,NaN,NaN
59,Jaipur,Auto Pool,test,0,NaN,NaN,NaN,NaN
60,Jaipur,Bike Lite,control,30021,46.49,0.42,27.29,16.60
61,Jaipur,Bike Lite,test,32036,45.18,0.51,29.73,16.25
62,Jaipur,Bike Metro,control,0,NaN,NaN,NaN,NaN
63,Jaipur,Bike Metro,test,0,NaN,NaN,NaN,NaN
64,Jaipur,Bike Pink,control,0,NaN,NaN,NaN,NaN
65,Jaipur,Bike Pink,test,0,NaN,NaN,NaN,NaN
66,Jaipur,CabEconomy,control,0,NaN,NaN,NaN,NaN
67,Jaipur,CabEconomy,test,0,NaN,NaN,NaN,NaN
68,Jaipur,Link,control,97031,54.13,0.53,21.42,17.82
69,Jaipur,Link,test,20116,34.60,1.49,39.06,17.66
70,Kolkata,Auto,control,0,NaN,NaN,NaN,NaN
71,Kolkata,Auto,test,0,NaN,NaN,NaN,NaN
72,Kolkata,Auto Pool,control,0,NaN,NaN,NaN,NaN
73,Kolkata,Auto Pool,test,0,NaN,NaN,NaN,NaN
74,Kolkata,Bike Lite,control,3725,52.78,1.51,16.60,19.70
75,Kolkata,Bike Lite,test,15,37.50,0.00,5.00,25.00
76,Kolkata,Bike Metro,control,0,NaN,NaN,NaN,NaN
77,Kolkata,Bike Metro,test,0,NaN,NaN,NaN,NaN
78,Kolkata,Bike Pink,control,0,NaN,NaN,NaN,NaN
79,Kolkata,Bike Pink,test,0,NaN,NaN,NaN,NaN
80,Kolkata,CabEconomy,control,43112,45.94,0.96,17.12,26.40
81,Kolkata,CabEconomy,test,1479,42.14,3.60,15.07,31.29
82,Kolkata,Link,control,178175,59.73,0.37,14.34,19.94
83,Kolkata,Link,test,5842,57.37,1.31,13.31,23.60
84,Pune,Auto,control,74152,56.79,0.57,16.78,17.45
85,Pune,Auto,test,69021,56.16,0.76,19.11,16.29
86,Pune,Auto Pool,control,0,NaN,NaN,NaN,NaN
87,Pune,Auto Pool,test,0,NaN,NaN,NaN,NaN
88,Pune,Bike Lite,control,0,NaN,NaN,NaN,NaN
89,Pune,Bike Lite,test,0,NaN,NaN,NaN,NaN
90,Pune,Bike Metro,control,0,NaN,NaN,NaN,NaN
91,Pune,Bike Metro,test,0,NaN,NaN,NaN,NaN
92,Pune,Bike Pink,control,0,NaN,NaN,NaN,NaN
93,Pune,Bike Pink,test,0,NaN,NaN,NaN,NaN
94,Pune,CabEconomy,control,56782,56.88,0.82,16.72,17.37
95,Pune,CabEconomy,test,11536,42.83,2.04,27.68,18.11
96,Pune,Link,control,0,NaN,NaN,NaN,NaN
97,Pune,Link,test,0,NaN,NaN,NaN,NaN

## Merge

In [21]:
df_telemetry_ads.head(1)

,yyyymmdd,city_name,service_name,userId,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,20240512,Kolkata,Link,638ca7a912ae9f6e1b3aa3c0,0,0,0,0,8,7,4,0,3,5,2,0,2,1,1,0,3,1,1,0

In [22]:
df_merge = pd.merge(df_sampled,
                    df_telemetry_ads,
                    how='left',
                    left_on=['yyyymmdd', 'city_name', 'service_name', 'customer_id'],
                    right_on=['yyyymmdd', 'city_name', 'service_name', 'userId'],
                   )
df_merge

,yyyymmdd,city_name,service_name,customer_id,group_tc,customer_segment,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,avg_cobrm_time,avg_cobra_time,avg_ocara_time,userId,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,20240519,Bangalore,Auto,5e0046189a6d72727b1bc9b3,control,COMMITTED,2,2,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20240512,Bangalore,Auto,61346bfcb2fb0dab096a0fcc,control,HOOK,1,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20240516,Bangalore,Auto,602e0c7f85e2d8d86fa8aa42,control,SUSTENANCE,1,1,0,0,0,0,0,NaN,NaN,NaN,602e0c7f85e2d8d86fa8aa42,0.0,0.0,0.0,0.0,2.0,7.0,1.0,0.0,2.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20240514,Bangalore,Auto,66436819fe041fefaf3352bf,control,UNKNOWN,2,0,0,2,0,0,0,NaN,140.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20240512,Bangalore,Auto,660294d6697bdd0e9139ea68,control,HOOK,3,1,0,2,0,0,0,NaN,81.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10297220,20240519,Pune,CabEconomy,65e91d8a777f4af7c053fd1d,control,HOOK,2,1,0,1,0,0,0,NaN,216.0,NaN,65e91d8a777f4af7c053fd1d,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10297221,20240519,Pune,CabEconomy,6263e39ee98a6492b9949ab0,control,HOOK,4,2,0,1,1,0,0,NaN,153.0,794.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10297222,20240513,Pune,CabEconomy,64abea13de83ef791b1cc285,control,HOOK,2,2,0,0,0,0,0,NaN,NaN,NaN,64abea13de83ef791b1cc285,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
10297223,20240514,Pune,CabEconomy,638c8120510c06261256c144,control,HOOK,2,1,0,1,0,0,0,NaN,183.0,NaN,638c8120510c06261256c144,0.0,0.0,0.0,0.0,10.0,4.0,4.0,0.0,3.0,1.0,1.0,0.0,2.0,2.0,2.0,0.0,5.0,1.0,1.0,0.0
10297224,20240513,Pune,CabEconomy,5cf65143ca6e2921117247e5,control,HOOK,4,2,0,1,0,0,1,NaN,248.0,NaN,5cf65143ca6e2921117247e5,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0

## Analysis

In [23]:
df_analysis1 =  df_merge\
.groupby(['group_tc'])\
.agg(**telemetri_agg_dict)\
.sort_values(by=['group_tc'])\
.reset_index()

df_analysis1

,group_tc,customers,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,cobrm_time,cobra_time,ocara_time,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,control,3827634,13377738,7031955,159006,2638363,2220827,18794,1261563,97.0,130.0,330.0,0.0,0.0,0.0,0.0,14238008.0,5727658.0,3139853.0,14232.0,6541343.0,2994635.0,1410823.0,7226.0,3022588.0,1330373.0,793866.0,1610.0,4684086.0,1402658.0,935167.0,5396.0
1,test,1725329,8016759,3775785,130314,2009952,1262326,6647,810765,95.0,135.0,320.0,9463860.0,1215643.0,813401.0,11519.0,22459461.0,8760719.0,4821155.0,21799.0,10499270.0,4545500.0,2040262.0,10288.0,4543297.0,1977649.0,1140039.0,2042.0,7432483.0,2237577.0,1640857.0,9469.0

In [24]:
df_analysis2 =  df_merge\
.groupby(['group_tc','yyyymmdd'])\
.agg(**telemetri_agg_dict)\
.sort_values(by=['yyyymmdd', 'group_tc'])\
.reset_index()

df_analysis2

,group_tc,yyyymmdd,customers,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,cobrm_time,cobra_time,ocara_time,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,control,20240512,758761,1606719,841933,17316,311389,287422,2602,140286,105.000000,128.000000,332.0,0.0,0.0,0.0,0.0,1314425.0,497372.0,265456.0,1089.0,596553.0,275621.0,120903.0,623.0,277805.0,75909.0,48730.0,118.0,441007.0,145842.0,95823.0,348.0
1,test,20240512,252197,710121,339323,10120,173791,118113,679,66289,104.000000,133.000000,314.5,871155.0,111882.0,75262.0,594.0,2051050.0,735152.0,399094.0,1443.0,943751.0,396254.0,168543.0,758.0,418375.0,111195.0,66965.0,144.0,690268.0,227703.0,163586.0,541.0
2,control,20240513,805729,1758727,883019,23542,376963,283216,2364,183856,100.000000,132.000000,328.0,0.0,0.0,0.0,0.0,1490769.0,538783.0,285909.0,1507.0,685419.0,304438.0,141544.0,879.0,316356.0,99199.0,60465.0,174.0,490002.0,135146.0,83900.0,454.0
3,test,20240513,288467,861781,387799,16046,233550,128994,702,92625,97.000000,137.000000,316.5,1016236.0,112651.0,75747.0,719.0,2274055.0,752658.0,412489.0,1922.0,1053947.0,417305.0,192283.0,1047.0,471060.0,139484.0,81871.0,164.0,750607.0,195869.0,138336.0,711.0
4,control,20240514,864227,1886681,960753,24609,410714,287922,2276,194152,92.750000,133.000000,326.0,0.0,0.0,0.0,0.0,1808175.0,756342.0,485327.0,2767.0,825817.0,387907.0,224433.0,1503.0,398446.0,156909.0,112626.0,258.0,585167.0,211529.0,148268.0,1006.0
5,test,20240514,318107,969121,444198,17330,263573,140894,680,100064,93.000000,137.000000,313.0,1111195.0,121029.0,81230.0,617.0,2560870.0,1070462.0,695796.0,3943.0,1183670.0,540328.0,300121.0,1960.0,540755.0,210204.0,149500.0,335.0,838231.0,319930.0,246175.0,1648.0
6,control,20240515,859815,1796788,970229,23143,342813,290456,2344,161295,94.000000,130.000000,327.0,0.0,0.0,0.0,0.0,2020526.0,672727.0,374685.0,1059.0,921142.0,345093.0,169377.0,547.0,435627.0,175129.0,106015.0,161.0,665069.0,152505.0,99293.0,351.0
7,test,20240515,336468,980869,478845,16726,235089,152529,738,94328,92.416667,133.666667,317.0,1143386.0,157660.0,106264.0,1275.0,2805840.0,907964.0,501551.0,1326.0,1294223.0,461019.0,213467.0,663.0,575668.0,231296.0,134403.0,144.0,937794.0,215649.0,153681.0,519.0
8,control,20240516,834621,1877495,900138,26182,421483,292575,2628,228215,90.000000,136.500000,338.0,0.0,0.0,0.0,0.0,1933686.0,881374.0,444874.0,1780.0,911910.0,460556.0,186674.0,657.0,398950.0,194398.0,112609.0,185.0,624251.0,226423.0,145592.0,938.0
9,test,20240516,380560,1240779,518341,22252,360550,179908,940,155718,84.000000,143.000000,330.0,1344265.0,189089.0,124641.0,2743.0,3068232.0,1341241.0,678406.0,2835.0,1470790.0,694683.0,265951.0,1009.0,602592.0,286990.0,158521.0,265.0,997102.0,359572.0,253935.0,1561.0
10,control,20240517,820178,1641675,929001,19931,281816,279044,2357,123367,96.000000,127.000000,327.0,0.0,0.0,0.0,0.0,2158927.0,933438.0,491626.0,2229.0,997503.0,498973.0,230472.0,1186.0,459062.0,236357.0,129990.0,234.0,703959.0,198108.0,131165.0,809.0
11,test,20240517,370555,1038537,527435,18074,233002,168440,839,87874,92.000000,131.000000,318.0,1245049.0,171928.0,118004.0,1481.0,3136488.0,1314710.0,688673.0,3162.0,1480924.0,708427.0,308005.0,1518.0,630289.0,316103.0,169457.0,296.0,1027581.0,290180.0,211212.0,1348.0
12,control,20240518,770126,1507554,871386,11994,241628,271741,2386,102518,104.000000,122.500000,330.0,0.0,0.0,0.0,0.0,2028404.0,803414.0,434973.0,1928.0,926623.0,402640.0,185600.0,916.0,429987.0,221847.0,122651.0,231.0,673260.0,178928.0,126723.0,781.0
13,test,20240518,388425,1049929,547725,13101,218052,181161,1056,85747,102.833333,130.000000,321.0,1309204.0,162781.0,109153.0,1648.0,3308424.0,1273868.0,685412.0,3134.0,1546321.0,642605.0,278363.0,1371.0,665617.0,336307.0,180438.0,297.0,1098898.0,294957.0,226611.0,1466.0
14,control,20240519,629711,1302099,675496,12289,251557,228451,1837,127874,108.250000,128.000000,329.0,0.0,0.0,0.0,0.0,1483096.0,644208.0,357003.0,1873.0,676376.0,319407.0,151820.0,915.0,306355.0,170625.0,100780.0,249.0,501371.0,154177.0,104403.0,709.0
15,test,20240519,402550,1165622,532119,16665,292345,192287,1013,128120,106.000000,134.000000,325.0,1423370.0,188623.0,123100.0,2442.0,3254502.0,1364664.0,759734.0,4034.0,1525644.0,684879.0,313529.0,1962.0,638941.0,346070.0,198884.0,397.0,1092002.0,333717.0,247321.0,1675.0

In [25]:
df_analysis3 =  df_merge\
.groupby(['group_tc','city_name'])\
.agg(**telemetri_agg_dict)\
.sort_values(by=['city_name', 'group_tc'])\
.reset_index()

df_analysis3

,group_tc,city_name,customers,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,cobrm_time,cobra_time,ocara_time,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,control,Bangalore,884056,3978908,1634130,46107,1098582,591132,4560,593538,81.000000,132.000000,308.000000,0.0,0.0,0.0,0.0,2451223.0,999654.0,550596.0,2645.0,1143419.0,515436.0,238237.0,1193.0,483490.0,207826.0,119743.0,201.0,826185.0,276394.0,192618.0,1251.0
1,test,Bangalore,437712,2610237,932460,38153,868193,357109,1845,407618,63.000000,132.600000,295.500000,2767100.0,380311.0,235017.0,3738.0,5601671.0,2269068.0,1236913.0,5365.0,2584106.0,1116037.0,498825.0,2424.0,1121429.0,501901.0,273714.0,423.0,1900332.0,651133.0,464375.0,2518.0
2,control,Chennai,566969,1827287,1147141,25912,238685,305268,2829,99139,106.000000,120.500000,310.000000,0.0,0.0,0.0,0.0,1862576.0,710130.0,364292.0,1832.0,875770.0,362830.0,177130.0,1091.0,376426.0,152283.0,87236.0,169.0,611545.0,195019.0,99926.0,572.0
3,test,Chennai,283561,1103962,664992,19986,163399,191768,1137,59522,112.000000,124.500000,310.000000,1465291.0,198389.0,137201.0,1598.0,3913751.0,1440498.0,815145.0,4425.0,1792654.0,688983.0,326462.0,1937.0,777117.0,323136.0,177881.0,334.0,1346375.0,428380.0,310802.0,2154.0
4,control,Delhi,842038,2901173,1654176,37561,427850,577040,4405,190070,118.000000,125.000000,357.000000,0.0,0.0,0.0,0.0,3591363.0,1448556.0,834272.0,3812.0,1671487.0,753833.0,369845.0,1899.0,747227.0,344019.0,212612.0,461.0,1175102.0,350705.0,251815.0,1452.0
5,test,Delhi,334656,1688777,869897,34060,345599,311066,1374,120368,119.708333,132.500000,348.000000,1921462.0,223809.0,161018.0,1567.0,4572328.0,1699925.0,1004249.0,4107.0,2203330.0,861728.0,439481.0,2020.0,971645.0,431720.0,264136.0,410.0,1400794.0,406477.0,300633.0,1677.0
6,control,Hyderabad,1090237,3280430,1830286,41150,621726,481633,4974,286289,89.000000,135.000000,333.000000,0.0,0.0,0.0,0.0,4343133.0,1695931.0,974278.0,4106.0,1842258.0,839108.0,410658.0,2031.0,1026058.0,454953.0,271903.0,591.0,1478118.0,401872.0,291718.0,1484.0
7,test,Hyderabad,524191,2011228,1016439,31586,478483,297251,1842,180556,84.000000,148.166667,329.000000,2513069.0,326228.0,218888.0,3944.0,6227727.0,2363470.0,1322522.0,6100.0,2787499.0,1230101.0,568087.0,3087.0,1278171.0,559086.0,326986.0,727.0,2166376.0,574286.0,427450.0,2286.0
8,control,Jaipur,151845,468123,239689,3179,108151,84162,680,30899,127.000000,134.333333,383.000000,0.0,0.0,0.0,0.0,514162.0,266279.0,104038.0,454.0,291821.0,196087.0,54026.0,187.0,97443.0,37596.0,23818.0,67.0,125268.0,32597.0,26194.0,200.0
9,test,Jaipur,78493,339979,150618,3825,101213,60208,297,22783,133.000000,135.000000,369.583333,401274.0,35022.0,24965.0,301.0,1196039.0,633698.0,231276.0,1014.0,712235.0,484000.0,124567.0,528.0,201361.0,76358.0,47762.0,85.0,283061.0,73340.0,58947.0,401.0
10,control,Kolkata,205868,581048,332891,2821,86266,122232,1105,33967,120.000000,138.000000,369.000000,0.0,0.0,0.0,0.0,1232144.0,510688.0,252287.0,1115.0,620699.0,283260.0,138271.0,712.0,245351.0,112433.0,65152.0,95.0,366780.0,114995.0,48864.0,308.0
11,test,Kolkata,6991,15187,8214,272,2075,3832,27,721,100.000000,136.750000,401.000000,23394.0,3174.0,2292.0,26.0,59694.0,25327.0,12994.0,45.0,30064.0,13505.0,6842.0,35.0,11621.0,6399.0,3765.0,1.0,18048.0,5423.0,2387.0,9.0
12,control,Pune,114836,340769,193642,2276,57103,59360,241,27661,122.000000,122.000000,268.000000,0.0,0.0,0.0,0.0,243407.0,96420.0,60090.0,268.0,95889.0,44081.0,22656.0,113.0,46593.0,21263.0,13402.0,26.0,101088.0,31076.0,24032.0,129.0
13,test,Pune,70322,247389,133165,2432,50990,41092,125,19197,115.250000,128.000000,277.666667,372270.0,48710.0,34020.0,345.0,888251.0,328733.0,198056.0,743.0,389382.0,151146.0,75998.0,257.0,181953.0,79049.0,45795.0,62.0,317497.0,98538.0,76263.0,424.0

In [26]:
df_analysis4 =  df_merge\
.groupby(['group_tc','service_name'])\
.agg(**telemetri_agg_dict)\
.sort_values(by=['service_name', 'group_tc'])\
.reset_index()

df_analysis4

,group_tc,service_name,customers,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,cobrm_time,cobra_time,ocara_time,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,control,Auto,1429873,4484034,2227325,44245,929867,736343,4343,532494,93.5,132.000000,293.000000,0.0,0.0,0.0,0.0,188046.0,58349.0,39184.0,188.0,44125.0,16960.0,8725.0,43.0,32747.0,12385.0,8514.0,26.0,111331.0,29004.0,21945.0,119.0
1,test,Auto,1508301,4905614,2468125,57923,1088872,759654,4052,516148,91.0,137.000000,310.000000,8007573.0,1054056.0,695541.0,10140.0,16800761.0,6530870.0,3619890.0,16450.0,7663948.0,3319302.0,1485205.0,7440.0,3362702.0,1454548.0,827117.0,1505.0,5785605.0,1757026.0,1307570.0,7505.0
2,control,Auto Pool,35407,152247,29666,22829,45338,14285,167,39742,83.0,140.000000,310.000000,0.0,0.0,0.0,0.0,18607.0,8057.0,4483.0,18.0,9506.0,4805.0,2291.0,9.0,3021.0,1364.0,861.0,0.0,6098.0,1888.0,1331.0,9.0
3,test,Auto Pool,15946,91758,17501,12353,33438,8323,43,19977,80.0,144.500000,328.500000,435.0,81.0,53.0,2.0,10058.0,4066.0,2297.0,15.0,6148.0,2722.0,1388.0,11.0,1258.0,551.0,319.0,1.0,2656.0,793.0,590.0,3.0
4,control,Bike Lite,185349,593224,338301,4856,110819,101064,692,34182,106.0,125.666667,363.000000,0.0,0.0,0.0,0.0,124090.0,41759.0,26475.0,125.0,51918.0,18924.0,10310.0,45.0,28564.0,11701.0,7413.0,19.0,43694.0,11134.0,8752.0,61.0
5,test,Bike Lite,185394,707928,400002,6978,142887,118100,673,35429,113.0,132.000000,376.000000,1047744.0,110362.0,81851.0,753.0,2179702.0,840887.0,465143.0,1915.0,1130554.0,478684.0,218937.0,959.0,476839.0,201215.0,126880.0,206.0,573944.0,160988.0,119327.0,750.0
6,control,Bike Metro,24234,66583,40006,302,11733,11657,48,2524,114.0,111.000000,313.166667,0.0,0.0,0.0,0.0,2765.0,883.0,603.0,4.0,567.0,154.0,109.0,0.0,599.0,256.0,179.0,0.0,1599.0,473.0,315.0,4.0
7,test,Bike Metro,25587,76699,45916,545,14226,13178,54,2434,100.0,121.000000,332.000000,84603.0,9917.0,7436.0,64.0,175375.0,65422.0,40253.0,100.0,80466.0,29913.0,16821.0,38.0,46016.0,20752.0,12929.0,10.0,49088.0,14757.0,10503.0,52.0
8,control,Bike Pink,6186,22713,6400,5262,4697,2713,15,3578,109.0,124.000000,268.000000,0.0,0.0,0.0,0.0,32.0,15.0,11.0,0.0,13.0,6.0,4.0,0.0,2.0,1.0,1.0,0.0,17.0,8.0,6.0,0.0
9,test,Bike Pink,6045,23521,6560,5718,5173,2719,17,3283,117.0,130.000000,277.000000,19806.0,2589.0,1816.0,120.0,2803.0,984.0,653.0,4.0,1517.0,526.0,323.0,1.0,541.0,207.0,132.0,0.0,746.0,251.0,198.0,3.0
10,control,CabEconomy,771569,1936235,909959,20667,410571,383741,2931,206240,113.0,135.000000,347.000000,0.0,0.0,0.0,0.0,2808460.0,1234714.0,662306.0,3296.0,1230687.0,638948.0,294724.0,1832.0,526123.0,256228.0,156811.0,407.0,1053430.0,339539.0,210772.0,1057.0
11,test,CabEconomy,179699,773899,259572,16442,267716,132293,512,96358,107.0,138.750000,331.000000,89788.0,13014.0,8416.0,215.0,1025913.0,433009.0,222216.0,1106.0,482874.0,229364.0,100354.0,674.0,186483.0,91207.0,52345.0,114.0,357167.0,112438.0,69517.0,318.0
12,control,Link,2206190,6122702,3480298,60845,1125338,971024,10598,442803,100.0,128.000000,352.000000,0.0,0.0,0.0,0.0,11096008.0,4383881.0,2406791.0,10601.0,5204527.0,2314838.0,1094660.0,5297.0,2431532.0,1048438.0,620087.0,1158.0,3467917.0,1020612.0,692046.0,4146.0
13,test,Link,329623,1437340,578109,30355,457640,228059,1296,137136,96.0,130.500000,323.000000,213911.0,25624.0,18288.0,225.0,2264849.0,885481.0,470703.0,2209.0,1133763.0,484989.0,217234.0,1165.0,469458.0,209169.0,120317.0,206.0,663277.0,191324.0,133152.0,838.0

In [27]:
df_analysis5 =  df_merge\
.groupby(['group_tc','city_name', 'service_name'])\
.agg(**telemetri_agg_dict)\
.sort_values(by=['city_name', 'service_name', 'group_tc'])\
.reset_index()

df_analysis5[df_analysis5['customers'] > 0]

,group_tc,city_name,service_name,customers,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,cobrm_time,cobra_time,ocara_time,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,control,Bangalore,Auto,458934,1757817,713101,13789,462908,261769,1471,301613,66.000000,130.666667,280.000000,0.0,0.0,0.0,0.0,45282.0,14810.0,9961.0,43.0,9268.0,3370.0,1919.0,5.0,7544.0,2973.0,1970.0,6.0,28505.0,8467.0,6072.0,32.0
1,test,Bangalore,Auto,423102,1696601,673693,18358,495158,233714,1172,271447,48.000000,132.500000,289.000000,2658020.0,366800.0,226585.0,3598.0,4665167.0,1892663.0,1036872.0,4362.0,2110387.0,912658.0,407003.0,1861.0,947039.0,423470.0,230440.0,356.0,1611259.0,556537.0,399430.0,2145.0
2,control,Bangalore,Auto Pool,16921,84368,16573,10824,25757,8445,96,22561,81.000000,136.000000,295.000000,0.0,0.0,0.0,0.0,13075.0,5915.0,3176.0,8.0,6450.0,3389.0,1514.0,3.0,2308.0,1046.0,622.0,0.0,4329.0,1480.0,1040.0,5.0
3,test,Bangalore,Auto Pool,6930,44817,7372,5345,17300,4071,28,10647,75.000000,137.750000,312.500000,206.0,33.0,20.0,2.0,7112.0,2925.0,1628.0,7.0,4155.0,1850.0,909.0,5.0,963.0,427.0,243.0,0.0,1998.0,648.0,476.0,2.0
4,control,Bangalore,Bike Lite,7431,26385,9336,197,10309,3446,32,2951,70.000000,131.000000,366.000000,0.0,0.0,0.0,0.0,933.0,288.0,229.0,3.0,258.0,90.0,60.0,1.0,147.0,58.0,46.0,1.0,528.0,140.0,123.0,1.0
5,test,Bangalore,Bike Lite,7247,28868,9949,449,11569,3672,34,3066,86.000000,134.000000,362.000000,30017.0,3255.0,2208.0,28.0,37782.0,13371.0,7882.0,34.0,18747.0,7054.0,3561.0,12.0,7117.0,2810.0,1726.0,3.0,11941.0,3507.0,2595.0,19.0
10,control,Bangalore,CabEconomy,193595,581562,219703,5092,169674,103131,648,82720,101.000000,140.000000,322.000000,0.0,0.0,0.0,0.0,530516.0,249691.0,130484.0,703.0,231354.0,129030.0,55668.0,347.0,99900.0,49380.0,28972.0,75.0,199624.0,71282.0,45845.0,281.0
11,test,Bangalore,CabEconomy,62711,314744,82060,4807,131929,45914,177,49516,78.000000,139.200000,314.000000,27993.0,4256.0,2380.0,69.0,316043.0,138602.0,69832.0,388.0,151996.0,74134.0,31162.0,243.0,57019.0,27799.0,15284.0,32.0,107220.0,36669.0,23386.0,113.0
12,control,Bangalore,Link,459146,1528776,675417,16205,429934,214341,2313,183693,87.000000,130.000000,342.000000,0.0,0.0,0.0,0.0,1861417.0,728950.0,406746.0,1888.0,896089.0,379557.0,179076.0,837.0,373591.0,154369.0,88133.0,119.0,593199.0,195025.0,139538.0,932.0
13,test,Bangalore,Link,99063,525207,159386,9194,212237,69738,434,72942,73.000000,128.750000,305.000000,50864.0,5967.0,3824.0,41.0,575567.0,221507.0,120699.0,574.0,298821.0,120341.0,56190.0,303.0,109291.0,47395.0,26021.0,32.0,167914.0,53772.0,38488.0,239.0
14,control,Chennai,Auto,256756,724038,459230,6557,84633,130181,825,40850,104.000000,119.500000,295.500000,0.0,0.0,0.0,0.0,32885.0,9551.0,6901.0,35.0,7696.0,2320.0,1401.0,4.0,5761.0,2026.0,1412.0,1.0,19449.0,5205.0,4088.0,30.0
15,test,Chennai,Auto,269015,804755,519428,6835,98868,137409,823,39301,112.000000,126.000000,311.708333,1388175.0,188501.0,130093.0,1395.0,3421127.0,1253406.0,721974.0,3944.0,1548010.0,590956.0,280261.0,1646.0,683892.0,283014.0,155633.0,293.0,1191341.0,379437.0,286080.0,2005.0
18,control,Chennai,Bike Lite,7087,18350,9903,397,3517,3322,35,1057,105.125000,114.000000,337.500000,0.0,0.0,0.0,0.0,796.0,246.0,177.0,0.0,183.0,83.0,45.0,0.0,156.0,45.0,35.0,0.0,458.0,118.0,97.0,0.0
19,test,Chennai,Bike Lite,7189,20566,10964,509,4028,3787,33,1116,113.000000,116.000000,349.000000,20934.0,2606.0,1925.0,32.0,43073.0,15233.0,9338.0,56.0,21799.0,8004.0,4236.0,31.0,8315.0,3205.0,1957.0,5.0,12984.0,4024.0,3145.0,20.0
22,control,Chennai,Bike Pink,6186,22713,6400,5262,4697,2713,15,3578,109.000000,124.000000,268.000000,0.0,0.0,0.0,0.0,32.0,15.0,11.0,0.0,13.0,6.0,4.0,0.0,2.0,1.0,1.0,0.0,17.0,8.0,6.0,0.0
23,test,Chennai,Bike Pink,6045,23521,6560,5718,5173,2719,17,3283,117.000000,130.000000,277.000000,19806.0,2589.0,1816.0,120.0,2803.0,984.0,653.0,4.0,1517.0,526.0,323.0,1.0,541.0,207.0,132.0,0.0,746.0,251.0,198.0,3.0
24,control,Chennai,CabEconomy,87675,202440,113480,2627,30840,40517,351,14407,111.000000,123.000000,318.000000,0.0,0.0,0.0,0.0,314669.0,134971.0,64945.0,359.0,138385.0,68543.0,31362.0,232.0,58791.0,26580.0,15543.0,48.0,117680.0,39848.0,18040.0,79.0
25,test,Chennai,CabEconomy,22545,86815,39520,1776,20740,17760,83,6815,115.000000,128.000000,316.500000,9663.0,1494.0,1011.0,27.0,141375.0,57514.0,26657.0,161.0,67087.0,29787.0,13163.0,112.0,24890.0,11520.0,6390.0,13.0,49477.0,16207.0,7104.0,36.0
26,control,Chennai,Link,310167,859746,558128,11069,114998,128535,1603,39247,105.000000,121.000000,323.000000,0.0,0.0,0.0,0.0,1514194.0,565347.0,292258.0,1438.0,729493.0,291878.0,144318.0,855.0,311716.0,123631.0,70245.0,120.0,473941.0,149840.0,77695.0,463.0
27,test,Chennai,Link,42773,168305,88520,5148,34590,30093,181,9007,107.000000,119.000000,296.000000,26713.0,3199.0,2356.0,24.0,305373.0,113361.0,56523.0,260.0,154241.0,59710.0,28479.0,147.0,59479.0,25190.0,13769.0,23.0,91827.0,28461.0,14275.0,90.0
28,control,Delhi,Auto,187597,568805,284267,10836,98084,110928,461,62959,117.000000,127.000000,295.000000,0.0,0.0,0.0,0.0,25625.0,7688.0,5471.0,30.0,5790.0,1855.0,1169.0,6.0,4658.0,1904.0,1321.0,4.0,15200.0,3929.0,2981.0,20.0
29,test,Delhi,Auto,196479,609112,298998,14444,119304,112705,430,61744,123.000000,134.000000,323.000000,919916.0,114567.0,79869.0,876.0,1841031.0,693530.0,409273.0,1646.0,847446.0,343257.0,170478.0,783.0,366921.0,164382.0,98301.0,146.0,627994.0,185891.0,140494.0,717.0
30,control,Delhi,Auto Pool,100,302,55,64,47,28,0,108,111.500000,148.333333,317.666667,0.0,0.0,0.0,0.0,35.0,9.0,8.0,0.0,19.0,5.0,5.0,0.0,6.0,1.0,1.0,0.0,10.0,3.0,2.0,0.0
31,test,Delhi,Auto Pool,49,232,48,43,64,23,0,53,85.000000,160.750000,263.500000,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,control,Delhi,Bike Lite,108844,393804,236391,3387,63672,68651,372,19208,110.000000,124.000000,356.583333,0.0,0.0,0.0,0.0,13549.0,4057.0,2835.0,12.0,3975.0,1198.0,743.0,2.0,2830.0,1134.0,798.0,2.0,6754.0,1725.0,1294.0,8.0
33,test,Delhi,Bike Lite,136245,542797,326084,5236,93772,91699,474,22428,114.000000,131.000000,372.000000,844565.0,90655.0,67577.0,532.0,1733783.0,617505.0,374044.0,1512.0,870028.0,315814.0,170501.0,751.0,394955.0,169173.0,106404.0,171.0,470145.0,132518.0,97140.0,590.0
34,control,Delhi,Bike Metro,24234,66583,40006,302,11733,11657,48,2524,114.000000,111.000000,313.166667,0.0,0.0,0.0,0.0,2765.0,883.0,603.0,4.0,567.0,154.0,109.0,0.0,599.0,256.0,179.0,0.0,1599.0,473.0,315.0,4.0
35,test,Delhi,Bike Metro,25587,76699,45916,545,14226,13178,54,2434,100.000000,121.000000,332.000000,84603.0,9917.0,7436.0,64.0,175375.0,65422.0,40253.0,100.0,80466.0,29913.0,16821.0,38.0,46016.0,20752.0,12929.0,10.0,49088.0,14757.0,10503.0,52.0
38,control,Delhi,CabEconomy,225410,529438,274341,7016,76183,128141,1106,41905,122.000000,129.000000,393.000000,0.0,0.0,0.0,0.0,957766.0,410149.0,229967.0,1103.0,432014.0,214324.0,101826.0,608.0,173059.0,85175.0,54299.0,139.0,353285.0,110650.0,73842.0,356.0
39,test,Delhi,CabEconomy,37519,142207,56703,5629,34324,31549,133,13584,126.000000,135.500000,373.416667,23755.0,3037.0,2083.0,30.0,261780.0,108719.0,58312.0,254.0,125682.0,58593.0,26207.0,148.0,45713.0,22805.0,13758.0,27.0,90553.0,27321.0,18347.0,79.0
40,control,Delhi,Link,496372,1342241,819116,15956,178131,257635,2418,63366,119.000000,123.000000,373.000000,0.0,0.0,0.0,0.0,2591623.0,1025770.0,595388.0,2663.0,1229122.0,536297.0,265993.0,1283.0,566075.0,255549.0,156014.0,316.0,798254.0,233925.0,173381.0,1064.0
41,test,Delhi,Link,78138,317730,142148,8163,83909,61912,283,20125,114.444444,132.200000,356.000000,48623.0,5633.0,4053.0,65.0,560357.0,214749.0,122367.0,595.0,279706.0,114151.0,55474.0,300.0,118040.0,54608.0,32744.0,56.0,163014.0,45990.0,34149.0,239.0
42,control,Hyderabad,Auto,405946,1079950,580792,10317,215587,169440,1301,100046,85.400000,146.000000,315.000000,0.0,0.0,0.0,0.0,57959.0,16697.0,11384.0,49.0,12672.0,4744.0,2636.0,23.0,10310.0,3835.0,2643.0,8.0,35030.0,8118.0,6105.0,18.0
43,test,Hyderabad,Auto,506354,1441030,787652,14714,299673,214425,1401,119730,82.000000,152.000000,330.000000,2432796.0,315713.0,211135.0,3824.0,5384918.0,2039343.0,1142204.0,5268.0,2408276.0,1068469.0,490909.0,2644.0,1088225.0,470606.0,275955.0,614.0,1892102.0,500271.0,375341.0,2010.0
44,control,Hyderabad,Auto Pool,18390,67577,13038,11941,19534,5812,71,17073,85.500000,147.100000,334.666667,0.0,0.0,0.0,0.0,5497.0,2133.0,1299.0,10.0,3037.0,1411.0,772.0,6.0,707.0,317.0,238.0,0.0,1759.0,405.0,289.0,4.0
45,test,Hyderabad,Auto Pool,8973,46709,10081,6965,16074,4229,15,9277,83.000000,153.600000,350.000000,229.0,48.0,33.0,0.0,2944.0,1141.0,669.0,8.0,1991.0,872.0,479.0,6.0,295.0,124.0,76.0,1.0,658.0,145.0,114.0,1.0
46,control,Hyderabad,Bike Lite,28429,58240,37326,378,7866,9383,115,2639,98.000000,119.000000,340.000000,0.0,0.0,0.0,0.0,94471.0,32232.0,20221.0,84.0,40888.0,14911.0,8168.0,33.0,22584.0,9493.0,5878.0,13.0,31067.0,7828.0,6175.0,38.0
47,test,Hyderabad,Bike Lite,2874,10192,5338,243,2166,1799,15,574,93.000000,122.354167,306.250000,1672.0,199.0,150.0,3.0,14959.0,5303.0,3198.0,11.0,6762.0,2439.0,1275.0,5.0,3464.0,1591.0,949.0,1.0,4741.0,1273.0,974.0,5.0
52,control,Hyderabad,CabEconomy,169937,393570,182840,3904,95149,63231,393,47670,106.000000,137.000000,339.000000,0.0,0.0,0.0,0.0,575068.0,265229.0,136921.0,664.0,239208.0,139122.0,61676.0,382.0,117710.0,59906.0,35714.0,116.0,218529.0,66201.0,39531.0,166.0
53,test,Hyderabad,CabEconomy,44545,183614,61389,3232,68253,28219,92,22210,98.833333,146.500000,337.000000,17251.0,2604.0,1818.0,54.0,219359.0,93492.0,47462.0,221.0,98411.0,49427.0,21504.0,129.0,43025.0,21509.0,12379.0,32.0,78058.0,22556.0,13579.0,60.0
54,control,Hyderabad,Link,674746,1681093,1016290,14610,283590,233767,3094,118861,90.500000,128.000000,344.000000,0.0,0.0,0.0,0.0,3610138.0,1379640.0,804453.0,3299.0,1546453.0,678920.0,337406.0,1587.0,874747.0,381402.0,227430.0,454.0,1191733.0,319320.0,239618.0,1258.0
55,test,Hyderabad,Link,84790,329683,151979,6432,92317,48579,319,28765,85.958333,138.000000,317.000000,61121.0,7664.0,5752.0,63.0,605547.0,224191.0,128989.0,592.0,272059.0,108894.0,53920.0,303.0,143162.0,65256.0,37627.0,79.0,190817.0,50041.0,37442.0,210.0
56,control,Jaipur,Auto,54708,143311,70610,1547,33400,27360,158,9890,129.000000,139.500000,347.000000,0.0,0.0,0.0,0.0,16192.0,6608.0,3225.0,17.0,6771.0,4069.0,1233.0,5.0,2748.0,974.0,677.0,2.0,6690.0,1565.0,1315.0,10.0
57,test,Jaipur,Auto,52511,150021,73730,2022,36863,28151,120,8720,135.000000,137.000000,348.000000,243164.0,20739.0,14512.0,130.0,676228.0,353072.0,128882.0,564.0,394456.0,267645.0,67549.0,287.0,108697.0,40588.0,24855.0,44.0,173370.0,44839.0,36478.0,233.0
60,control,Jaipur,Bike Lite,30021,88344,41069,375,24110,14666,126,7628,115.000000,132.000000,413.000000,0.0,0.0,0.0,0.0,4644.0,1867.0,969.0,9.0,1726.0,1026.0,329.0,4.0,925.0,365.0,262.0,1.0,1996.0,476.0,378.0,4.0
61,test,Jaipur,Bike Lite,32036,105465,47652,541,31350,17133,116,8233,123.888889,135.000000,415.000000,150526.0,13646.0,9990.0,158.0,350012.0,189452.0,70667.0,302.0,213150.0,145356.0,39354.0,160.0,62972.0,24433.0,15843.0,26.0,74124.0,19663.0,15470.0,116.0
68,control,Jaipur,Link,97031,236468,128010,1257,50641,42136,396,13381,127.000000,133.000000,396.000000,0.0,0.0,0.0,0.0,493326.0,257804.0,99844.0,428.0,283324.0,190992.0,52464.0,178.0,93770.0,36257.0,22879.0,64.0,116582.0,30556.0,24501.0,186.0
69,test,Jaipur,Link,20116,84493,29236,1262,33000,14924,61,5830,136.000000,134.000000,358.000000,7584.0,637.0,463.0,13.0,169799.0,91174.0,31727.0,148.0,104629.0,70999.0,17664.0,81.0,29692.0,11337.0,7064.0,15.0,35567.0,8838.0,6999.0,52.0
74,control,Kolkata,Bike Lite,3725,8101,4276,122,1345,1596,12,699,95.000000,126.333333,358.000000,0.0,0.0,0.0,0.0,9697.0,3069.0,2044.0,17.0,4888.0,1616.0,965.0,5.0,1922.0,606.0,394.0,2.0,2891.0,847.0,685.0,10.0
75,test,Kolkata,Bike Lite,15,40,15,0,2,10,1,12,NaN,203.500000,432.000000,30.0,1.0,1.0,0.0,93.0,23.0,14.0,0.0,68.0,17.0,10.0,0.0,16.0,3.0,1.0,0.0,9.0,3.0,3.0,0.0
80,control,Kolkata,CabEconomy,43112,98569,45278,951,16877,26026,319,9013,130.000000,151.000000,363.000000,0.0,0.0,0.0,0.0,197137.0,81249.0,42141.0,213.0,95765.0,44450.0,21903.0,150.0,31796.0,14597.0,9372.0,8.0,69681.0,22202.0,10866.0,55.0
81,test,Kolkata,CabEconomy,1479,3225,1359,116,486,1009,8,242,120.277778,152.000000,387.000000,4358.0,649.0,451.0,7.0,11395.0,4805.0,2582.0,5.0,5689.0,2594.0,1325.0,4.0,1811.0,1013.0,672.0,0.0,3901.0,1198.0,585.0,1.0
82,control,Kolkata,Link,178175,474378,283337,1748,68044,94610,774,24255,117.000000,135.000000,370.000000,0.0,0.0,0.0,0.0,1025310.0,426370.0,208102.0,885.0,520046.0,237194.0,115403.0,557.0,211633.0,97230.0,55386.0,85.0,294208.0,91946.0,37313.0,243.0
83,test,Kolkata,Link,5842,11922,6840,156,1587,2813,18,467,95.000000,132.000000,407.000000,19006.0,2524.0,1840.0,19.0,48206.0,20499.0,10398.0,40.0,24307.0,10894.0,5507.0,31.0,9794.0,5383.0,3092.0,1.0,14138.0,4222.0,1799.0,8.0
84,control,Pune,Auto,74152,210113,119325,1199,35255,36665,127,17136,120.000000,122.333333,251.000000,0.0,0.0,0.0,0.0,10103.0,2995.0,2242.0,14.0,1928.0,602.0,367.0,0.0,1726.0,673.0,491.0,5.0,6457.0,1720.0,1384.0,9.0
85,test,Pune,Auto,69021,204095,114624,1550,39006,33250,106,15206,118.000000,128.500000,274.000000,365502.0,47736.0,33347.0,317.0,812290.0,298856.0,180685.0,666.0,355373.0,136317.0,69005.0,219.0,167928.0,72488.0,41933.0,52.0,289539.0,90051.0,69747.0,395.0
94,control,Pune,CabEconomy,56782,130656,74317,1077,21848,22695,114,10525,123.000000,122.000000,300.500000,0.0,0.0,0.0,0.0,233304.0,93425.0,57848.0,254.0,93961.0,43479.0,22289.0,113.0,44867.0,20590.0,12911.0,21.0,94631.0,29356.0,22648.0,120.0
95,test,Pune,CabEconomy,11536,43294,18541,882,11984,7842,19,3991,111.000000,127.000000,295.750000,6768.0,974.0,673.0,28.0,75961.0,29877.0,17371.0,77.0,34009.0,14829.0,6993.0,38.0,14025.0,6561.0,3862.0,10.0,27958.0,8487.0,6516.0,29.0

In [28]:
df_analysis4.to_clipboard(index=False)

In [29]:
df_analysis1

,group_tc,customers,gross_orders,net_orders,cobrm,cobra,ocara,aborted,expired,cobrm_time,cobra_time,ocara_time,css_request,css_response,css_viewable_impression,css_click,pos_request,pos_response,pos_viewable_impression,pos_click,onTheWay_request,onTheWay_response,onTheWay_viewable_impression,onTheWay_click,arrived_request,arrived_response,arrived_viewable_impression,arrived_click,started_request,started_response,started_viewable_impression,started_click
0,control,3827634,13377738,7031955,159006,2638363,2220827,18794,1261563,97.0,130.0,330.0,0.0,0.0,0.0,0.0,14238008.0,5727658.0,3139853.0,14232.0,6541343.0,2994635.0,1410823.0,7226.0,3022588.0,1330373.0,793866.0,1610.0,4684086.0,1402658.0,935167.0,5396.0
1,test,1725329,8016759,3775785,130314,2009952,1262326,6647,810765,95.0,135.0,320.0,9463860.0,1215643.0,813401.0,11519.0,22459461.0,8760719.0,4821155.0,21799.0,10499270.0,4545500.0,2040262.0,10288.0,4543297.0,1977649.0,1140039.0,2042.0,7432483.0,2237577.0,1640857.0,9469.0

In [30]:
df_analysis1['g2n'] = calculate_percentage(df_analysis1, 'net_orders', 'gross_orders')
df_analysis1['% cobrm'] = calculate_percentage(df_analysis1, 'cobrm', 'gross_orders')
df_analysis1['% cobra'] = calculate_percentage(df_analysis1, 'cobra', 'gross_orders')
df_analysis1['% ocara'] = calculate_percentage(df_analysis1, 'ocara', 'gross_orders')

df_analysis1[[ #'city_name', 
#          'service_name', 
         'group_tc','customers', 'g2n', '% cobrm', '% cobra', '% ocara']]

  group_tc  customers    g2n  % cobrm  % cobra  % ocara
0  control    3827634  52.56     1.19    19.72    16.60
1     test    1725329  47.10     1.63    25.07    15.75

In [31]:
df_data.group_tc.value_counts(True)

group_tc
control    0.678591
test       0.321409
Name: proportion, dtype: float64