## Imports

In [1]:
import glob
import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

import time

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='processing-2.processing.data.production.internal' ,
    # 'presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'
conn1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
conn2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
conn3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
conn4= presto.connect('processing.processing.data.production.internal',presto_port,username)

In [4]:
local_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/'
local_path

'/Users/E2074/local-datasets/customer/segmentation/consideration/'

In [5]:
city = 'delhi'
city_name = 'Delhi'

## Ignore following steps and go to <b>Customer Segment</b> Section directly

## Datasets & Parameter

In [7]:
start_date = datetime.strptime("2025-03-03", "%Y-%m-%d")

run_date = [(start_date + timedelta(weeks=i)).strftime("%Y-%m-%d") for i in range(10)]
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [23]:
def get_segment_customer_base(run_date):
    start_time = time.time()

    ltr_segment = ['HH', 'PHH']
    df_list = []
    
    for segment in ltr_segment:
        base_query = f"""
    
            with base as (
                select 
                    customer_id,
                    taxi_ltr_segment,
                    -- taxi_lifetime_rides,
                    date_diff( 'day', DATE(taxi_lifetime_first_ride_date), DATE(DATE_PARSE(run_date, '%Y-%m-%d'))) rapido_firstride_age
                from 
                    datasets.iallocator_customer_segments
                where 
                    run_date = date_format(date('{run_date}'), '%Y-%m-%d')
                    and taxi_lifetime_last_ride_city = '{city_name}'
                    and taxi_ltr_segment = '{segment}'
                ),
                
                active_week as (
                
                select
                    customerid,
                    91 max_active_days,
                    total_active_days,
                    isAct_w01,
                    isAct_w02,
                    isAct_w03,
                    isAct_w04,
                    isAct_w05,
                    isAct_w06,
                    isAct_w07,
                    isAct_w08,
                    isAct_w09,
                    isAct_w10,
                    isAct_w11,
                    isAct_w12,
                    isAct_w13,
                    13 max_active_weeks,
                    (isAct_w01 + isAct_w02 + isAct_w03 + isAct_w04 + isAct_w05 + isAct_w06 + isAct_w07 + isAct_w08 + isAct_w09 + isAct_w10 + isAct_w11 + isAct_w12 + isAct_w13) total_active_weeks,
                    act_days_w01,
                    act_days_w02,
                    act_days_w03,
                    act_days_w04,
                    act_days_w05,
                    act_days_w06,
                    act_days_w07,
                    act_days_w08,
                    act_days_w09,
                    act_days_w10,
                    act_days_w11,
                    act_days_w12,
                    act_days_w13,
                    net_rides
                from
                    (
                    select
                        customerid,
                        sum(rr_active_day) total_active_days,
                        max(case when day >= date_format(date('{run_date}') - interval '91' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '85' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w01,
                        max(case when day >= date_format(date('{run_date}') - interval '84' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '78' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w02,
                        max(case when day >= date_format(date('{run_date}') - interval '77' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '71' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w03,
                        max(case when day >= date_format(date('{run_date}') - interval '70' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '64' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w04,
                        max(case when day >= date_format(date('{run_date}') - interval '63' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '57' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w05,
                        max(case when day >= date_format(date('{run_date}') - interval '56' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '50' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w06,
                        max(case when day >= date_format(date('{run_date}') - interval '49' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '43' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w07,
                        max(case when day >= date_format(date('{run_date}') - interval '42' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '36' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w08,
                        max(case when day >= date_format(date('{run_date}') - interval '35' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '29' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w09,
                        max(case when day >= date_format(date('{run_date}') - interval '28' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '22' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w10,
                        max(case when day >= date_format(date('{run_date}') - interval '21' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '15' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w11,
                        max(case when day >= date_format(date('{run_date}') - interval '14' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '8' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w12,
                        max(case when day >= date_format(date('{run_date}') - interval '7' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '1' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w13,
                        
                        count(distinct case when day >= date_format(date('{run_date}') - interval '91' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '85' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w01,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '84' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '78' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w02,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '77' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '71' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w03,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '70' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '64' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w04,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '63' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '57' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w05,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '56' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '50' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w06,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '49' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '43' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w07,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '42' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '36' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w08,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '35' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '29' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w09,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '28' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '22' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w10,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '21' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '15' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w11,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '14' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '8' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w12,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '7' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '1' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w13,
                        sum(net_rides_daily) net_rides
                    
                    from    
                        (
                        select 
                            day,
                            customerid, 
                            -- max(fe_sessions_unique_daily) fe_session, 
                            -- sum(rr_sessions_unique_daily) rr_session, 
                            max(case when rr_sessions_unique_daily > 0 then 1 else 0 end) rr_active_day,
                            sum(net_rides_daily) net_rides_daily
                        from 
                            datasets.customer_rf_daily_kpi
                        where 
                            day >= date_format(date('{run_date}') - interval '91' day, '%Y-%m-%d')
                            and day <= date_format(date('{run_date}') - interval '1' day, '%Y-%m-%d')
                            and city = '{city_name}'
                            and service_name in ('Auto','Auto Lite','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium', 'Auto NCR')
                            -- and customerid = '6288c6694281e53bbe33d133'
                        group by 1,2
                        )
                    group by 1
                    )
                )
                
                select
                    *
                from
                    base
                left join 
                    active_week
                    on base.customer_id = active_week.customerid
            """

        df_segment = pd.read_sql(base_query, conn4)
        df_segment['run_date'] = run_date
        df_list.append(df_segment)
        print(f"Fetched data for segment: {segment}")
    
    # Concatenate all segment dataframes
    df_base_query = pd.concat(df_list, ignore_index=True)

    df_base_query.to_parquet(local_path + city + '/customer_base_{}.parquet'.format(run_date), index=False)
    end_time = time.time()
    print(f"Executed - Time taken: {end_time - start_time:.4f} seconds")

In [25]:
for i in run_date[9:]:
    
    print('Starting - ', i)
    get_segment_customer_base(i)

Starting -  2025-05-05
Fetched data for segment: HH
Fetched data for segment: PHH
Executed - Time taken: 781.3260 seconds

In [26]:
# Find all matching parquet files
file_paths = glob.glob(os.path.join(local_path + city + '/customer_base_*.parquet'))

# Dictionary to store dynamically created DataFrames
dfs = {}

for path in file_paths:
    filename = os.path.basename(path)
    # Get last 10 characters of the filename without extension
    name_part = os.path.splitext(filename)[0][-10:]
    # Remove special characters
    cleaned_name = re.sub(r'\W+', '', name_part)
    # Create a dynamic dataframe name
    df_name = f'df_{cleaned_name}'
    # Read the parquet file
    dfs[df_name] = pd.read_parquet(path)

In [27]:
df_list = list(dfs.keys())
df_list

['df_20250414',
 'df_20250331',
 'df_20250317',
 'df_20250428',
 'df_20250407',
 'df_20250421',
 'df_20250505',
 'df_20250310',
 'df_20250324',
 'df_20250303']

## Feature Engineering

In [28]:
def get_feature_engineering(df):
    
    print('feature engineering part')
    # Adding required active month fields
    df['isAct_m01'] = np.where(df[['isAct_w01', 'isAct_w02', 'isAct_w03', 'isAct_w04']].sum(axis=1) >= 1, 1, 0)
    df['isAct_m02'] = np.where(df[['isAct_w05', 'isAct_w06', 'isAct_w07', 'isAct_w08']].sum(axis=1) >= 1, 1, 0)
    df['isAct_m03'] = np.where(df[['isAct_w09', 'isAct_w10', 'isAct_w11', 'isAct_w12', 'isAct_w13']].sum(axis=1) >= 1, 1, 0)
    
    df['max_active_months'] = 3
    df['total_active_months'] = df[['isAct_m01', 'isAct_m02', 'isAct_m03']].sum(axis=1)
    
    df['days_since_1st_ride_in_3months'] = np.where(df['rapido_firstride_age']>=91,91,df['rapido_firstride_age'])
    df['weeks_since_1st_ride_in_3months'] = np.ceil(df['days_since_1st_ride_in_3months']/7)
    df['months_since_1st_ride_in_3months'] = np.ceil(df['days_since_1st_ride_in_3months']/31)

    df["customerid"] = df["customerid"].fillna('NA')
    df.fillna(0,inplace=True)


    # Adding required derived percentage fields for making thresholds
    df['active_days_percet'] = (df['total_active_days']/df['days_since_1st_ride_in_3months']).round(2)
    df['active_weeks_percet'] = (df['total_active_weeks']/df['weeks_since_1st_ride_in_3months']).round(2)
    df['active_months_percet'] = (df['total_active_months']/df['months_since_1st_ride_in_3months']).round(2)

    return df

## Segmentation

In [29]:
def get_segment(df):

    print('segmentation part')
    
    df['hh_monthly_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])) & (df['active_months_percet'] >= 0.66), '1-HH-MONTHLY', None)
    df['hh_quarterly_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])) & (df['total_active_days'] > 0), '2-HH-QUARTERLY', None)
    df['hh_inactive_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])), '3-HH-INACTIVE',  None)
    
    df['daily_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH']))& (df['active_days_percet'] >= 0.45), '4-DAILY', None)
    df['weekly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['active_weeks_percet'] >= 0.70), '5-WEEKLY', None)
    df['monthly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['active_months_percet'] >= 0.66), '6-MONTHLY', None)
    df['quarterly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & df['total_active_days'] > 0, '7-QUARTERLY', None)
    df['inactive_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['total_active_days'] == 0), '8-INACTIVE', None)
    df['new_segment'] = np.where((~df['taxi_ltr_segment'].isin(['HH', 'PHH'])), '9-NEW', None)
    df['segment'] = df['hh_monthly_segment']\
                        .fillna(df['hh_quarterly_segment'])\
                        .fillna(df['hh_inactive_segment'])\
                        .fillna(df['daily_segment'])\
                        .fillna(df['weekly_segment'])\
                        .fillna(df['monthly_segment'])\
                        .fillna(df['quarterly_segment'])\
                        .fillna(df['inactive_segment'])\
                        .fillna(df['new_segment'])\
                        .fillna('check')
    
    df['updated_segment'] = df['segment']
    
    df.loc[((df['updated_segment']=='7-QUARTERLY')& (df['weeks_since_1st_ride_in_3months']<=8)), 'updated_segment'] = '6-MONTHLY'
    df.loc[((df['updated_segment'] == '5-WEEKLY') & (df['weeks_since_1st_ride_in_3months']<=2)), 'updated_segment'] = '6-MONTHLY'

    return df

## Execution

In [30]:
df_list

['df_20250414',
 'df_20250331',
 'df_20250317',
 'df_20250428',
 'df_20250407',
 'df_20250421',
 'df_20250505',
 'df_20250310',
 'df_20250324',
 'df_20250303']

In [31]:
for df_name in df_list:
    print(df_name)
    df = dfs[df_name]
    df_temp = get_feature_engineering(df)
    df_final = get_segment(df_temp)
    df_final.to_parquet(local_path + city + '/segment/{}.parquet'.format(df_name), index=False)
    
    print('---')

df_20250414
feature engineering part
segmentation part
---
df_20250331
feature engineering part
segmentation part
---
df_20250317
feature engineering part
segmentation part
---
df_20250428
feature engineering part
segmentation part
---
df_20250407
feature engineering part
segmentation part
---
df_20250421
feature engineering part
segmentation part
---
df_20250505
feature engineering part
segmentation part
---
df_20250310
feature engineering part
segmentation part
---
df_20250324
feature engineering part
segmentation part
---
df_20250303
feature engineering part
segmentation part
---

## Customer Segment

In [ ]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/' + city + '/segment/'

# Get all parquet files in the folder
parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

# Read and concatenate all parquet files into a single DataFrame
df_segment_concat = pd.concat([pd.read_parquet(file) for file in parquet_files], ignore_index=True)

In [ ]:
df_segment_concat.head(1)

In [ ]:
df_segment_concat.shape

In [ ]:
df_segment_concat.segment.unique()

## Stability

In [ ]:
# Reducing df memory 
df_segment_concat = df_segment_concat[['run_date', 'customer_id', 'segment', 'updated_segment']]

In [ ]:
df_segment_concat.run_date.unique()

In [ ]:
df_base = df_segment_concat[df_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base

In [ ]:
df_stability_window = df_segment_concat[~df_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window

In [ ]:
df_stability_window.run_date.unique()

In [ ]:
df_merge = pd.merge(df_base, df_stability_window, how='left', on='customer_id')
df_merge

In [ ]:
df_merge_pivot = df_merge.groupby(['run_date_x', 'run_date_y', 'updated_segment_x', 'updated_segment_y']).agg(customers=('customer_id','nunique')).reset_index()

In [ ]:
df_merge_pivot

In [ ]:
df_merge_pivot.pivot(index = ['run_date_x', 'updated_segment_x', 'updated_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

In [ ]:
df_base.groupby(['run_date', 'updated_segment']).agg(customers=('customer_id','nunique')).reset_index()

## Previous Segment Stability

### taxi_regularity_segment

In [8]:
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [17]:
def get_previous_segment_customer_base(run_date):
    
    base_query = f"""
    
    select 
        run_date, 
        customer_id, 
        taxi_regularity_segment
        -- taxi_fe_regularity_segment 
    from 
        datasets.iallocator_customer_segments 
    where 
        run_date = date_format(date('{run_date}'), '%Y-%m-%d')
        and taxi_lifetime_last_ride_city = '{city_name}'
        and taxi_regularity_segment != 'UNKNOWN' 
    """
    
    df_base_query = pd.read_sql(base_query, conn3)
    df_base_query['run_date'] = run_date
    print('executed - ', run_date)

    df_base_query.to_parquet(local_path + city + '/prev_segment/prev_customer_base_{}.parquet'.format(run_date), index=False)

In [18]:
for i in run_date[3:]:
    
    print('starting - ', i)
    get_previous_segment_customer_base(i)

starting -  2025-03-24
executed -  2025-03-24
starting -  2025-03-31
executed -  2025-03-31
starting -  2025-04-07
executed -  2025-04-07
starting -  2025-04-14
executed -  2025-04-14
starting -  2025-04-21
executed -  2025-04-21
starting -  2025-04-28
executed -  2025-04-28
starting -  2025-05-05
executed -  2025-05-05

In [19]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/prev_segment'

# Get all parquet files in the folder
prev_parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

# Read and concatenate all parquet files into a single DataFrame
df_previous_segment_concat = pd.concat([pd.read_parquet(file) for file in prev_parquet_files], ignore_index=True)

In [20]:
df_previous_segment_concat.head(1)

     run_date               customer_id taxi_regularity_segment
0  2025-03-31  63621000192f9565bfe3c91a                   DAILY

In [21]:
df_previous_segment_concat.shape

(60488342, 3)

### Stability

In [22]:
df_previous_segment_concat.run_date.unique()

array(['2025-03-31', '2025-03-17', '2025-04-14', '2025-04-28',
       '2025-04-07', '2025-04-21', '2025-03-10', '2025-05-05',
       '2025-03-03', '2025-03-24'], dtype=object)

In [23]:
df_base_prev = df_previous_segment_concat[df_previous_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base_prev

           run_date               customer_id taxi_regularity_segment
0        2025-03-03  65cc9f5d107646988ca7cbfe                 MONTHLY
1        2025-03-03  5fec62a5ee2e9cf63c81f3d0                  WEEKLY
2        2025-03-03  6260f2fb2c04373d294067d4               RARE_NEED
3        2025-03-03  63d8ae8f6b21d714418dfa55                  WEEKLY
4        2025-03-03  659e4952b3bae65867b994db               RARE_NEED
...             ...                       ...                     ...
5729986  2025-03-03  66ece87d7a4c8a6141bac9a9               RARE_NEED
5729987  2025-03-03  61b2daeebd965e1f5fbcefa3               RARE_NEED
5729988  2025-03-03  6460a8f39bb65e1f9021ee64                 MONTHLY
5729989  2025-03-03  61585820c94e7965abcd3146               RARE_NEED
5729990  2025-03-03  625d223d00b5f41ac4b124c2               RARE_NEED

[5729991 rows x 3 columns]

In [24]:
df_stability_window_prev = df_previous_segment_concat[~df_previous_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window_prev

            run_date               customer_id taxi_regularity_segment
0         2025-03-10  6720a5f8b0cf4681ad13ec44               BI_WEEKLY
1         2025-03-10  61cf75d1a75746bfa8e44619               RARE_NEED
2         2025-03-10  620b355057d2b2ceeeafedf8               RARE_NEED
3         2025-03-10  64aecfb77fe9533b3ff6af57                 MONTHLY
4         2025-03-10  61b867c417dd6a10c413e7fa                  WEEKLY
...              ...                       ...                     ...
54758346  2025-05-05  66abf5a7c9ff56fcce918df4                  WEEKLY
54758347  2025-05-05  62c2718c5bce425623ae2591               RARE_NEED
54758348  2025-05-05  5e6b3350f5667d7cb3239387               RARE_NEED
54758349  2025-05-05  64d5e6e412dbf310dfa2a262               RARE_NEED
54758350  2025-05-05  66b23201ca8ed76ffd0e2939                  WEEKLY

[54758351 rows x 3 columns]

In [25]:
df_stability_window_prev.run_date.unique()

array(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
       '2025-04-07', '2025-04-14', '2025-04-21', '2025-04-28',
       '2025-05-05'], dtype=object)

In [26]:
df_merge_prev = pd.merge(df_base_prev, df_stability_window_prev, how='left', on='customer_id')
df_merge_prev

,run_date_x,customer_id,taxi_regularity_segment_x,run_date_y,taxi_regularity_segment_y
0,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-03-10,MONTHLY
1,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-03-17,MONTHLY
2,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-03-24,MONTHLY
3,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-03-31,MONTHLY
4,2025-03-03,65cc9f5d107646988ca7cbfe,MONTHLY,2025-04-07,MONTHLY
...,...,...,...,...,...
50084312,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-04-07,RARE_NEED
50084313,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-04-14,RARE_NEED
50084314,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-04-21,RARE_NEED
50084315,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-04-28,RARE_NEED
50084316,2025-03-03,625d223d00b5f41ac4b124c2,RARE_NEED,2025-05-05,RARE_NEED

In [27]:
df_merge_pivot_prev = df_merge_prev.groupby(['run_date_x', 'run_date_y', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y']).agg(customers=('customer_id','nunique')).reset_index()
df_merge_pivot_prev

,run_date_x,run_date_y,taxi_regularity_segment_x,taxi_regularity_segment_y,customers
0,2025-03-03,2025-03-10,BI_WEEKLY,BI_WEEKLY,756971
1,2025-03-03,2025-03-10,BI_WEEKLY,DAILY,9220
2,2025-03-03,2025-03-10,BI_WEEKLY,MONTHLY,115954
3,2025-03-03,2025-03-10,BI_WEEKLY,WEEKLY,77517
4,2025-03-03,2025-03-10,DAILY,BI_WEEKLY,5320
5,2025-03-03,2025-03-10,DAILY,DAILY,313881
6,2025-03-03,2025-03-10,DAILY,WEEKLY,14562
7,2025-03-03,2025-03-10,MONTHLY,BI_WEEKLY,109612
8,2025-03-03,2025-03-10,MONTHLY,MONTHLY,660047
9,2025-03-03,2025-03-10,MONTHLY,RARE_NEED,104682
10,2025-03-03,2025-03-10,RARE_NEED,MONTHLY,82384
11,2025-03-03,2025-03-10,RARE_NEED,RARE_NEED,2716145
12,2025-03-03,2025-03-10,WEEKLY,BI_WEEKLY,68762
13,2025-03-03,2025-03-10,WEEKLY,DAILY,18447
14,2025-03-03,2025-03-10,WEEKLY,WEEKLY,614960
15,2025-03-03,2025-03-17,BI_WEEKLY,BI_WEEKLY,633212
16,2025-03-03,2025-03-17,BI_WEEKLY,DAILY,16382
17,2025-03-03,2025-03-17,BI_WEEKLY,MONTHLY,185302
18,2025-03-03,2025-03-17,BI_WEEKLY,WEEKLY,113711
19,2025-03-03,2025-03-17,DAILY,BI_WEEKLY,9866
20,2025-03-03,2025-03-17,DAILY,DAILY,296106
21,2025-03-03,2025-03-17,DAILY,WEEKLY,23890
22,2025-03-03,2025-03-17,MONTHLY,BI_WEEKLY,153905
23,2025-03-03,2025-03-17,MONTHLY,MONTHLY,527646
24,2025-03-03,2025-03-17,MONTHLY,RARE_NEED,184614
25,2025-03-03,2025-03-17,RARE_NEED,BI_WEEKLY,16567
26,2025-03-03,2025-03-17,RARE_NEED,MONTHLY,130372
27,2025-03-03,2025-03-17,RARE_NEED,RARE_NEED,2639717
28,2025-03-03,2025-03-17,WEEKLY,BI_WEEKLY,96637
29,2025-03-03,2025-03-17,WEEKLY,DAILY,24967
30,2025-03-03,2025-03-17,WEEKLY,WEEKLY,571060
31,2025-03-03,2025-03-24,BI_WEEKLY,BI_WEEKLY,542104
32,2025-03-03,2025-03-24,BI_WEEKLY,DAILY,22193
33,2025-03-03,2025-03-24,BI_WEEKLY,MONTHLY,226933
34,2025-03-03,2025-03-24,BI_WEEKLY,RARE_NEED,9814
35,2025-03-03,2025-03-24,BI_WEEKLY,WEEKLY,141911
36,2025-03-03,2025-03-24,DAILY,BI_WEEKLY,13887
37,2025-03-03,2025-03-24,DAILY,DAILY,288264
38,2025-03-03,2025-03-24,DAILY,WEEKLY,28972
39,2025-03-03,2025-03-24,MONTHLY,BI_WEEKLY,170240
40,2025-03-03,2025-03-24,MONTHLY,DAILY,2003
41,2025-03-03,2025-03-24,MONTHLY,MONTHLY,445498
42,2025-03-03,2025-03-24,MONTHLY,RARE_NEED,238855
43,2025-03-03,2025-03-24,MONTHLY,WEEKLY,3668
44,2025-03-03,2025-03-24,RARE_NEED,BI_WEEKLY,35906
45,2025-03-03,2025-03-24,RARE_NEED,MONTHLY,156970
46,2025-03-03,2025-03-24,RARE_NEED,RARE_NEED,2583089
47,2025-03-03,2025-03-24,WEEKLY,BI_WEEKLY,118869
48,2025-03-03,2025-03-24,WEEKLY,DAILY,35355
49,2025-03-03,2025-03-24,WEEKLY,WEEKLY,537038
50,2025-03-03,2025-03-31,BI_WEEKLY,BI_WEEKLY,475335
51,2025-03-03,2025-03-31,BI_WEEKLY,DAILY,24604
52,2025-03-03,2025-03-31,BI_WEEKLY,MONTHLY,242370
53,2025-03-03,2025-03-31,BI_WEEKLY,RARE_NEED,32117
54,2025-03-03,2025-03-31,BI_WEEKLY,WEEKLY,163209
55,2025-03-03,2025-03-31,DAILY,BI_WEEKLY,16326
56,2025-03-03,2025-03-31,DAILY,DAILY,279589
57,2025-03-03,2025-03-31,DAILY,MONTHLY,1669
58,2025-03-03,2025-03-31,DAILY,WEEKLY,31796
59,2025-03-03,2025-03-31,MONTHLY,BI_WEEKLY,171199
60,2025-03-03,2025-03-31,MONTHLY,DAILY,4982
61,2025-03-03,2025-03-31,MONTHLY,MONTHLY,391421
62,2025-03-03,2025-03-31,MONTHLY,RARE_NEED,276384
63,2025-03-03,2025-03-31,MONTHLY,WEEKLY,10906
64,2025-03-03,2025-03-31,RARE_NEED,BI_WEEKLY,54151
65,2025-03-03,2025-03-31,RARE_NEED,DAILY,471
66,2025-03-03,2025-03-31,RARE_NEED,MONTHLY,175415
67,2025-03-03,2025-03-31,RARE_NEED,RARE_NEED,2535722
68,2025-03-03,2025-03-31,RARE_NEED,WEEKLY,181
69,2025-03-03,2025-03-31,WEEKLY,BI_WEEKLY,139302
70,2025-03-03,2025-03-31,WEEKLY,DAILY,43704
71,2025-03-03,2025-03-31,WEEKLY,MONTHLY,4251
72,2025-03-03,2025-03-31,WEEKLY,WEEKLY,501196
73,2025-03-03,2025-04-07,BI_WEEKLY,BI_WEEKLY,428866
74,2025-03-03,2025-04-07,BI_WEEKLY,DAILY,27004
75,2025-03-03,2025-04-07,BI_WEEKLY,MONTHLY,241981
76,2025-03-03,2025-04-07,BI_WEEKLY,RARE_NEED,60232
77,2025-03-03,2025-04-07,BI_WEEKLY,WEEKLY,175588
78,2025-03-03,2025-04-07,DAILY,BI_WEEKLY,17961
79,2025-03-03,2025-04-07,DAILY,DAILY,273912
80,2025-03-03,2025-04-07,DAILY,MONTHLY,4101
81,2025-03-03,2025-04-07,DAILY,WEEKLY,33769
82,2025-03-03,2025-04-07,MONTHLY,BI_WEEKLY,171539
83,2025-03-03,2025-04-07,MONTHLY,DAILY,6361
84,2025-03-03,2025-04-07,MONTHLY,MONTHLY,347986
85,2025-03-03,2025-04-07,MONTHLY,RARE_NEED,303686
86,2025-03-03,2025-04-07,MONTHLY,WEEKLY,20880
87,2025-03-03,2025-04-07,RARE_NEED,BI_WEEKLY,68713
88,2025-03-03,2025-04-07,RARE_NEED,DAILY,1884
89,2025-03-03,2025-04-07,RARE_NEED,MONTHLY,194300
90,2025-03-03,2025-04-07,RARE_NEED,RARE_NEED,2489196
91,2025-03-03,2025-04-07,RARE_NEED,WEEKLY,2253
92,2025-03-03,2025-04-07,WEEKLY,BI_WEEKLY,149228
93,2025-03-03,2025-04-07,WEEKLY,DAILY,53295
94,2025-03-03,2025-04-07,WEEKLY,MONTHLY,14176
95,2025-03-03,2025-04-07,WEEKLY,WEEKLY,470838
96,2025-03-03,2025-04-14,BI_WEEKLY,BI_WEEKLY,393132
97,2025-03-03,2025-04-14,BI_WEEKLY,DAILY,28978
98,2025-03-03,2025-04-14,BI_WEEKLY,MONTHLY,230501
99,2025-03-03,2025-04-14,BI_WEEKLY,RARE_NEED,88077
100,2025-03-03,2025-04-14,BI_WEEKLY,WEEKLY,188560
101,2025-03-03,2025-04-14,DAILY,BI_WEEKLY,19365
102,2025-03-03,2025-04-14,DAILY,DAILY,264704
103,2025-03-03,2025-04-14,DAILY,MONTHLY,5590
104,2025-03-03,2025-04-14,DAILY,RARE_NEED,1122
105,2025-03-03,2025-04-14,DAILY,WEEKLY,37313
106,2025-03-03,2025-04-14,MONTHLY,BI_WEEKLY,174481
107,2025-03-03,2025-04-14,MONTHLY,DAILY,7677
108,2025-03-03,2025-04-14,MONTHLY,MONTHLY,310601
109,2025-03-03,2025-04-14,MONTHLY,RARE_NEED,320948
110,2025-03-03,2025-04-14,MONTHLY,WEEKLY,31989
111,2025-03-03,2025-04-14,RARE_NEED,BI_WEEKLY,85507
112,2025-03-03,2025-04-14,RARE_NEED,DAILY,3339
113,2025-03-03,2025-04-14,RARE_NEED,MONTHLY,214276
114,2025-03-03,2025-04-14,RARE_NEED,RARE_NEED,2436068
115,2025-03-03,2025-04-14,RARE_NEED,WEEKLY,6162
116,2025-03-03,2025-04-14,WEEKLY,BI_WEEKLY,152543
117,2025-03-03,2025-04-14,WEEKLY,DAILY,61283
118,2025-03-03,2025-04-14,WEEKLY,MONTHLY,25273
119,2025-03-03,2025-04-14,WEEKLY,RARE_NEED,1225
120,2025-03-03,2025-04-14,WEEKLY,WEEKLY,444365
121,2025-03-03,2025-04-21,BI_WEEKLY,BI_WEEKLY,359376
122,2025-03-03,2025-04-21,BI_WEEKLY,DAILY,31295
123,2025-03-03,2025-04-21,BI_WEEKLY,MONTHLY,223249
124,2025-03-03,2025-04-21,BI_WEEKLY,RARE_NEED,112399
125,2025-03-03,2025-04-21,BI_WEEKLY,WEEKLY,199332
126,2025-03-03,2025-04-21,DAILY,BI_WEEKLY,20407
127,2025-03-03,2025-04-21,DAILY,DAILY,256344
128,2025-03-03,2025-04-21,DAILY,MONTHLY,6814
129,2025-03-03,2025-04-21,DAILY,RARE_NEED,2813
130,2025-03-03,2025-04-21,DAILY,WEEKLY,40758
131,2025-03-03,2025-04-21,MONTHLY,BI_WEEKLY,183350
132,2025-03-03,2025-04-21,MONTHLY,DAILY,8811
133,2025-03-03,2025-04-21,MONTHLY,MONTHLY,274487
134,2025-03-03,2025-04-21,MONTHLY,RARE_NEED,334346
135,2025-03-03,2025-04-21,MONTHLY,WEEKLY,40173
136,2025-03-03,2025-04-21,RARE_NEED,BI_WEEKLY,102099
137,2025-03-03,2025-04-21,RARE_NEED,DAILY,5000
138,2025-03-03,2025-04-21,RARE_NEED,MONTHLY,230216
139,2025-03-03,2025-04-21,RARE_NEED,RARE_NEED,2386361
140,2025-03-03,2025-04-21,RARE_NEED,WEEKLY,11470
141,2025-03-03,2025-04-21,WEEKLY,BI_WEEKLY,152578
142,2025-03-03,2025-04-21,WEEKLY,DAILY,68478
143,2025-03-03,2025-04-21,WEEKLY,MONTHLY,35127
144,2025-03-03,2025-04-21,WEEKLY,RARE_NEED,4881
145,2025-03-03,2025-04-21,WEEKLY,WEEKLY,421449
146,2025-03-03,2025-04-28,BI_WEEKLY,BI_WEEKLY,331904
147,2025-03-03,2025-04-28,BI_WEEKLY,DAILY,33506
148,2025-03-03,2025-04-28,BI_WEEKLY,MONTHLY,213533
149,2025-03-03,2025-04-28,BI_WEEKLY,RARE_NEED,141377
150,2025-03-03,2025-04-28,BI_WEEKLY,WEEKLY,202825
151,2025-03-03,2025-04-28,DAILY,BI_WEEKLY,21567
152,2025-03-03,2025-04-28,DAILY,DAILY,249051
153,2025-03-03,2025-04-28,DAILY,MONTHLY,7930
154,2025-03-03,2025-04-28,DAILY,RARE_NEED,4786
155,2025-03-03,2025-04-28,DAILY,WEEKLY,44161
156,2025-03-03,2025-04-28,MONTHLY,BI_WEEKLY,185142
157,2025-03-03,2025-04-28,MONTHLY,DAILY,9874
158,2025-03-03,2025-04-28,MONTHLY,MONTHLY,247481
159,2025-03-03,2025-04-28,MONTHLY,RARE_NEED,347979
160,2025-03-03,2025-04-28,MONTHLY,WEEKLY,47511
161,2025-03-03,2025-04-28,RARE_NEED,BI_WEEKLY,114075
162,2025-03-03,2025-04-28,RARE_NEED,DAILY,6697
163,2025-03-03,2025-04-28,RARE_NEED,MONTHLY,240197
164,2025-03-03,2025-04-28,RARE_NEED,RARE_NEED,2348315
165,2025-03-03,2025-04-28,RARE_NEED,WEEKLY,17398
166,2025-03-03,2025-04-28,WEEKLY,BI_WEEKLY,153991
167,2025-03-03,2025-04-28,WEEKLY,DAILY,75302
168,2025-03-03,2025-04-28,WEEKLY,MONTHLY,44026
169,2025-03-03,2025-04-28,WEEKLY,RARE_NEED,11023
170,2025-03-03,2025-04-28,WEEKLY,WEEKLY,398093
171,2025-03-03,2025-05-05,BI_WEEKLY,BI_WEEKLY,311443
172,2025-03-03,2025-05-05,BI_WEEKLY,DAILY,35680
173,2025-03-03,2025-05-05,BI_WEEKLY,MONTHLY,202402
174,2025-03-03,2025-05-05,BI_WEEKLY,RARE_NEED,165425
175,2025-03-03,2025-05-05,BI_WEEKLY,WEEKLY,205677
176,2025-03-03,2025-05-05,DAILY,BI_WEEKLY,22335
177,2025-03-03,2025-05-05,DAILY,DAILY,241002
178,2025-03-03,2025-05-05,DAILY,MONTHLY,8785
179,2025-03-03,2025-05-05,DAILY,RARE_NEED,6973
180,2025-03-03,2025-05-05,DAILY,WEEKLY,47672
181,2025-03-03,2025-05-05,MONTHLY,BI_WEEKLY,185956
182,2025-03-03,2025-05-05,MONTHLY,DAILY,11064
183,2025-03-03,2025-05-05,MONTHLY,MONTHLY,227791
184,2025-03-03,2025-05-05,MONTHLY,RARE_NEED,354967
185,2025-03-03,2025-05-05,MONTHLY,WEEKLY,55302
186,2025-03-03,2025-05-05,RARE_NEED,BI_WEEKLY,127447
187,2025-03-03,2025-05-05,RARE_NEED,DAILY,8424
188,2025-03-03,2025-05-05,RARE_NEED,MONTHLY,247738
189,2025-03-03,2025-05-05,RARE_NEED,RARE_NEED,2310661
190,2025-03-03,2025-05-05,RARE_NEED,WEEKLY,24038
191,2025-03-03,2025-05-05,WEEKLY,BI_WEEKLY,152760
192,2025-03-03,2025-05-05,WEEKLY,DAILY,81182
193,2025-03-03,2025-05-05,WEEKLY,MONTHLY,50413
194,2025-03-03,2025-05-05,WEEKLY,RARE_NEED,18989
195,2025-03-03,2025-05-05,WEEKLY,WEEKLY,378100

In [28]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                                                customers  \
run_date_y                                                     2025-03-10
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   756971.0
                                     DAILY                         9220.0
                                     MONTHLY                     115954.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       77517.0
           DAILY                     BI_WEEKLY                     5320.0
                                     DAILY                       313881.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       14562.0
           MONTHLY                   BI_WEEKLY                   109612.0
                                     DAILY                            0.0
                                     MONTHLY                     660047.0
                                     RARE_NEED                   104682.0
                                     WEEKLY                           0.0
           RARE_NEED                 BI_WEEKLY                        0.0
                                     DAILY                            0.0
                                     MONTHLY                      82384.0
                                     RARE_NEED                  2716145.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                    68762.0
                                     DAILY                        18447.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      614960.0

                                                                           \
run_date_y                                                     2025-03-17
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   633212.0
                                     DAILY                        16382.0
                                     MONTHLY                     185302.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      113711.0
           DAILY                     BI_WEEKLY                     9866.0
                                     DAILY                       296106.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       23890.0
           MONTHLY                   BI_WEEKLY                   153905.0
                                     DAILY                            0.0
                                     MONTHLY                     527646.0
                                     RARE_NEED                   184614.0
                                     WEEKLY                           0.0
           RARE_NEED                 BI_WEEKLY                    16567.0
                                     DAILY                            0.0
                                     MONTHLY                     130372.0
                                     RARE_NEED                  2639717.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                    96637.0
                                     DAILY                        24967.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      571060.0

                                                                           \
run_date_y                                                     2025-03-24
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   542104.0
                                     DAILY                        22193.0
                                     MONTHLY                     226933.0
                                     RARE_NEED                     9814.0
                                     WEEKLY                      141911.0
           DAILY                     BI_WEEKLY                    13887.0
                                     DAILY                       288264.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       28972.0
           MONTHLY                   BI_WEEKLY                   170240.0
                                     DAILY                         2003.0
                                     MONTHLY                     445498.0
                                     RARE_NEED                   238855.0
                                     WEEKLY                        3668.0
           RARE_NEED                 BI_WEEKLY                    35906.0
                                     DAILY                            0.0
                                     MONTHLY                     156970.0
                                     RARE_NEED                  2583089.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                   118869.0
                                     DAILY                        35355.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      537038.0

                                                                           \
run_date_y                                                     2025-03-31
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   475335.0
                                     DAILY                        24604.0
                                     MONTHLY                     242370.0
                                     RARE_NEED                    32117.0
                                     WEEKLY                      163209.0
           DAILY                     BI_WEEKLY                    16326.0
                                     DAILY                       279589.0
                                     MONTHLY                       1669.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       31796.0
           MONTHLY                   BI_WEEKLY                   171199.0
                                     DAILY                         4982.0
                                     MONTHLY                     391421.0
                                     RARE_NEED                   276384.0
                                     WEEKLY                       10906.0
           RARE_NEED                 BI_WEEKLY                    54151.0
                                     DAILY                          471.0
                                     MONTHLY                     175415.0
                                     RARE_NEED                  2535722.0
                                     WEEKLY                         181.0
           WEEKLY                    BI_WEEKLY                   139302.0
                                     DAILY                        43704.0
                                     MONTHLY                       4251.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      501196.0

                                                                           \
run_date_y                                                     2025-04-07
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   428866.0
                                     DAILY                        27004.0
                                     MONTHLY                     241981.0
                                     RARE_NEED                    60232.0
                                     WEEKLY                      175588.0
           DAILY                     BI_WEEKLY                    17961.0
                                     DAILY                       273912.0
                                     MONTHLY                       4101.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       33769.0
           MONTHLY                   BI_WEEKLY                   171539.0
                                     DAILY                         6361.0
                                     MONTHLY                     347986.0
                                     RARE_NEED                   303686.0
                                     WEEKLY                       20880.0
           RARE_NEED                 BI_WEEKLY                    68713.0
                                     DAILY                         1884.0
                                     MONTHLY                     194300.0
                                     RARE_NEED                  2489196.0
                                     WEEKLY                        2253.0
           WEEKLY                    BI_WEEKLY                   149228.0
                                     DAILY                        53295.0
                                     MONTHLY                      14176.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      470838.0

                                                                           \
run_date_y                                                     2025-04-14
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   393132.0
                                     DAILY                        28978.0
                                     MONTHLY                     230501.0
                                     RARE_NEED                    88077.0
                                     WEEKLY                      188560.0
           DAILY                     BI_WEEKLY                    19365.0
                                     DAILY                       264704.0
                                     MONTHLY                       5590.0
                                     RARE_NEED                     1122.0
                                     WEEKLY                       37313.0
           MONTHLY                   BI_WEEKLY                   174481.0
                                     DAILY                         7677.0
                                     MONTHLY                     310601.0
                                     RARE_NEED                   320948.0
                                     WEEKLY                       31989.0
           RARE_NEED                 BI_WEEKLY                    85507.0
                                     DAILY                         3339.0
                                     MONTHLY                     214276.0
                                     RARE_NEED                  2436068.0
                                     WEEKLY                        6162.0
           WEEKLY                    BI_WEEKLY                   152543.0
                                     DAILY                        61283.0
                                     MONTHLY                      25273.0
                                     RARE_NEED                     1225.0
                                     WEEKLY                      444365.0

                                                                           \
run_date_y                                                     2025-04-21
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   359376.0
                                     DAILY                        31295.0
                                     MONTHLY                     223249.0
                                     RARE_NEED                   112399.0
                                     WEEKLY                      199332.0
           DAILY                     BI_WEEKLY                    20407.0
                                     DAILY                       256344.0
                                     MONTHLY                       6814.0
                                     RARE_NEED                     2813.0
                                     WEEKLY                       40758.0
           MONTHLY                   BI_WEEKLY                   183350.0
                                     DAILY                         8811.0
                                     MONTHLY                     274487.0
                                     RARE_NEED                   334346.0
                                     WEEKLY                       40173.0
           RARE_NEED                 BI_WEEKLY                   102099.0
                                     DAILY                         5000.0
                                     MONTHLY                     230216.0
                                     RARE_NEED                  2386361.0
                                     WEEKLY                       11470.0
           WEEKLY                    BI_WEEKLY                   152578.0
                                     DAILY                        68478.0
                                     MONTHLY                      35127.0
                                     RARE_NEED                     4881.0
                                     WEEKLY                      421449.0

                                                                           \
run_date_y                                                     2025-04-28
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   331904.0
                                     DAILY                        33506.0
                                     MONTHLY                     213533.0
                                     RARE_NEED                   141377.0
                                     WEEKLY                      202825.0
           DAILY                     BI_WEEKLY                    21567.0
                                     DAILY                       249051.0
                                     MONTHLY                       7930.0
                                     RARE_NEED                     4786.0
                                     WEEKLY                       44161.0
           MONTHLY                   BI_WEEKLY                   185142.0
                                     DAILY                         9874.0
                                     MONTHLY                     247481.0
                                     RARE_NEED                   347979.0
                                     WEEKLY                       47511.0
           RARE_NEED                 BI_WEEKLY                   114075.0
                                     DAILY                         6697.0
                                     MONTHLY                     240197.0
                                     RARE_NEED                  2348315.0
                                     WEEKLY                       17398.0
           WEEKLY                    BI_WEEKLY                   153991.0
                                     DAILY                        75302.0
                                     MONTHLY                      44026.0
                                     RARE_NEED                    11023.0
                                     WEEKLY                      398093.0


run_date_y                                                     2025-05-05
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   311443.0
                                     DAILY                        35680.0
                                     MONTHLY                     202402.0
                                     RARE_NEED                   165425.0
                                     WEEKLY                      205677.0
           DAILY                     BI_WEEKLY                    22335.0
                                     DAILY                       241002.0
                                     MONTHLY                       8785.0
                                     RARE_NEED                     6973.0
                                     WEEKLY                       47672.0
           MONTHLY                   BI_WEEKLY                   185956.0
                                     DAILY                        11064.0
                                     MONTHLY                     227791.0
                                     RARE_NEED                   354967.0
                                     WEEKLY                       55302.0
           RARE_NEED                 BI_WEEKLY                   127447.0
                                     DAILY                         8424.0
                                     MONTHLY                     247738.0
                                     RARE_NEED                  2310661.0
                                     WEEKLY                       24038.0
           WEEKLY                    BI_WEEKLY                   152760.0
                                     DAILY                        81182.0
                                     MONTHLY                      50413.0
                                     RARE_NEED                    18989.0
                                     WEEKLY                      378100.0

In [91]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0).to_clipboard(index=False)

In [30]:
df_base_prev.groupby(['run_date', 'taxi_regularity_segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date taxi_regularity_segment  customers
0  2025-03-03               BI_WEEKLY     974871
1  2025-03-03                   DAILY     340655
2  2025-03-03                 MONTHLY     884696
3  2025-03-03               RARE_NEED    2812984
4  2025-03-03                  WEEKLY     716785

### FE Regularity

In [31]:
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [37]:
def get_previous_segment_customer_base(run_date):
    
    base_query = f"""
    
    select 
        run_date, 
        customer_id, 
        -- taxi_regularity_segment
        taxi_fe_regularity_segment 
    from 
        datasets.iallocator_customer_segments 
    where 
        run_date = date_format(date('{run_date}'), '%Y-%m-%d')
        and taxi_lifetime_last_ride_city = '{city_name}'
        and taxi_fe_regularity_segment != 'UNKNOWN' 
    """
    
    df_base_query = pd.read_sql(base_query, conn4)
    df_base_query['run_date'] = run_date
    print('executed - ', run_date)

    df_base_query.to_parquet(local_path + city + '/prev_segment2/prev_customer_base_{}.parquet'.format(run_date), index=False)

In [38]:
for i in run_date[3:]:
    
    print('starting - ', i)
    get_previous_segment_customer_base(i)

starting -  2025-03-24
executed -  2025-03-24
starting -  2025-03-31
executed -  2025-03-31
starting -  2025-04-07
executed -  2025-04-07
starting -  2025-04-14
executed -  2025-04-14
starting -  2025-04-21
executed -  2025-04-21
starting -  2025-04-28
executed -  2025-04-28
starting -  2025-05-05
executed -  2025-05-05

In [39]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/delhi/prev_segment2'

# Get all parquet files in the folder
prev_parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

# Read and concatenate all parquet files into a single DataFrame
df_previous_segment_concat = pd.concat([pd.read_parquet(file) for file in prev_parquet_files], ignore_index=True)

In [40]:
df_previous_segment_concat.head(1)

     run_date               customer_id taxi_fe_regularity_segment
0  2025-03-31  66df535ad8b3ee466a1c6c4e                    MONTHLY

In [41]:
df_previous_segment_concat.shape

(45518135, 3)

### Stability

In [42]:
df_previous_segment_concat.run_date.unique()

array(['2025-03-31', '2025-03-17', '2025-04-14', '2025-04-28',
       '2025-04-07', '2025-04-21', '2025-03-10', '2025-05-05',
       '2025-03-03', '2025-03-24'], dtype=object)

In [43]:
df_base_prev = df_previous_segment_concat[df_previous_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base_prev

           run_date               customer_id taxi_fe_regularity_segment
0        2025-03-03  6612d04a4f976baed5b6ed89                    MONTHLY
1        2025-03-03  65d40897c48581191d416f97                  RARE_NEED
2        2025-03-03  63e9085f2217a7dbecd70b3b                      DAILY
3        2025-03-03  652bb8803246660a488d28fc                  BI_WEEKLY
4        2025-03-03  657b412344fc61de29b74089                  RARE_NEED
...             ...                       ...                        ...
4325313  2025-03-03  6266621e1d2d6f55e5582342                    MONTHLY
4325314  2025-03-03  646850739dbf7d77a8841279                  RARE_NEED
4325315  2025-03-03  63ea2413ae330d6058148d4e                  BI_WEEKLY
4325316  2025-03-03  63c25a1a1438dfac9d0f80e9                     WEEKLY
4325317  2025-03-03  663df36f802b4ef8fd320bac                  RARE_NEED

[4325318 rows x 3 columns]

In [44]:
df_stability_window_prev = df_previous_segment_concat[~df_previous_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window_prev

            run_date               customer_id taxi_fe_regularity_segment
0         2025-03-10  661d53e646c9a416e9faab21                  BI_WEEKLY
1         2025-03-10  6695d262d426be574760308b                  BI_WEEKLY
2         2025-03-10  650977c81213a91b0b84f758                     WEEKLY
3         2025-03-10  5fd0821b0141471976127cbb                  BI_WEEKLY
4         2025-03-10  66445bb0510947f10864bfaf                  BI_WEEKLY
...              ...                       ...                        ...
41192812  2025-05-05  67cd0756cff2e363a50aff22                  BI_WEEKLY
41192813  2025-05-05  64d4a896da3d2b05c1825b3d                    MONTHLY
41192814  2025-05-05  665ca8d399dbb5fe9719b4da                  RARE_NEED
41192815  2025-05-05  67a09514197b899daab6fa8b                    MONTHLY
41192816  2025-05-05  67c7e7370d61441f62732cf4                  RARE_NEED

[41192817 rows x 3 columns]

In [45]:
df_stability_window_prev.run_date.unique()

array(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
       '2025-04-07', '2025-04-14', '2025-04-21', '2025-04-28',
       '2025-05-05'], dtype=object)

In [46]:
df_merge_prev = pd.merge(df_base_prev, df_stability_window_prev, how='left', on='customer_id')
df_merge_prev

,run_date_x,customer_id,taxi_fe_regularity_segment_x,run_date_y,taxi_fe_regularity_segment_y
0,2025-03-03,6612d04a4f976baed5b6ed89,MONTHLY,2025-03-10,MONTHLY
1,2025-03-03,6612d04a4f976baed5b6ed89,MONTHLY,2025-03-17,MONTHLY
2,2025-03-03,6612d04a4f976baed5b6ed89,MONTHLY,2025-03-24,MONTHLY
3,2025-03-03,6612d04a4f976baed5b6ed89,MONTHLY,2025-03-31,MONTHLY
4,2025-03-03,6612d04a4f976baed5b6ed89,MONTHLY,2025-04-07,MONTHLY
...,...,...,...,...,...
32822619,2025-03-03,63c25a1a1438dfac9d0f80e9,WEEKLY,2025-05-05,BI_WEEKLY
32822620,2025-03-03,663df36f802b4ef8fd320bac,RARE_NEED,2025-03-10,RARE_NEED
32822621,2025-03-03,663df36f802b4ef8fd320bac,RARE_NEED,2025-03-17,RARE_NEED
32822622,2025-03-03,663df36f802b4ef8fd320bac,RARE_NEED,2025-03-24,RARE_NEED
32822623,2025-03-03,663df36f802b4ef8fd320bac,RARE_NEED,2025-03-31,RARE_NEED

In [47]:
df_merge_pivot_prev = df_merge_prev.groupby(['run_date_x', 'run_date_y', 'taxi_fe_regularity_segment_x', 'taxi_fe_regularity_segment_y']).agg(customers=('customer_id','nunique')).reset_index()
df_merge_pivot_prev

,run_date_x,run_date_y,taxi_fe_regularity_segment_x,taxi_fe_regularity_segment_y,customers
0,2025-03-03,2025-03-10,BI_WEEKLY,BI_WEEKLY,1025982
1,2025-03-03,2025-03-10,BI_WEEKLY,DAILY,14281
2,2025-03-03,2025-03-10,BI_WEEKLY,MONTHLY,140612
3,2025-03-03,2025-03-10,BI_WEEKLY,WEEKLY,68539
4,2025-03-03,2025-03-10,DAILY,BI_WEEKLY,9005
5,2025-03-03,2025-03-10,DAILY,DAILY,377031
6,2025-03-03,2025-03-10,DAILY,WEEKLY,16199
7,2025-03-03,2025-03-10,MONTHLY,BI_WEEKLY,157631
8,2025-03-03,2025-03-10,MONTHLY,MONTHLY,1009967
9,2025-03-03,2025-03-10,MONTHLY,RARE_NEED,128907
10,2025-03-03,2025-03-10,RARE_NEED,MONTHLY,93600
11,2025-03-03,2025-03-10,RARE_NEED,RARE_NEED,572515
12,2025-03-03,2025-03-10,WEEKLY,BI_WEEKLY,61746
13,2025-03-03,2025-03-10,WEEKLY,DAILY,18657
14,2025-03-03,2025-03-10,WEEKLY,WEEKLY,428454
15,2025-03-03,2025-03-17,BI_WEEKLY,BI_WEEKLY,895585
16,2025-03-03,2025-03-17,BI_WEEKLY,DAILY,24925
17,2025-03-03,2025-03-17,BI_WEEKLY,MONTHLY,212885
18,2025-03-03,2025-03-17,BI_WEEKLY,WEEKLY,102870
19,2025-03-03,2025-03-17,DAILY,BI_WEEKLY,16101
20,2025-03-03,2025-03-17,DAILY,DAILY,355258
21,2025-03-03,2025-03-17,DAILY,WEEKLY,25998
22,2025-03-03,2025-03-17,MONTHLY,BI_WEEKLY,242861
23,2025-03-03,2025-03-17,MONTHLY,MONTHLY,797401
24,2025-03-03,2025-03-17,MONTHLY,RARE_NEED,199202
25,2025-03-03,2025-03-17,RARE_NEED,BI_WEEKLY,734
26,2025-03-03,2025-03-17,RARE_NEED,MONTHLY,136571
27,2025-03-03,2025-03-17,RARE_NEED,RARE_NEED,438911
28,2025-03-03,2025-03-17,WEEKLY,BI_WEEKLY,89947
29,2025-03-03,2025-03-17,WEEKLY,DAILY,25161
30,2025-03-03,2025-03-17,WEEKLY,WEEKLY,387571
31,2025-03-03,2025-03-24,BI_WEEKLY,BI_WEEKLY,785967
32,2025-03-03,2025-03-24,BI_WEEKLY,DAILY,37248
33,2025-03-03,2025-03-24,BI_WEEKLY,MONTHLY,267148
34,2025-03-03,2025-03-24,BI_WEEKLY,RARE_NEED,3011
35,2025-03-03,2025-03-24,BI_WEEKLY,WEEKLY,135274
36,2025-03-03,2025-03-24,DAILY,BI_WEEKLY,22789
37,2025-03-03,2025-03-24,DAILY,DAILY,344683
38,2025-03-03,2025-03-24,DAILY,WEEKLY,31210
39,2025-03-03,2025-03-24,MONTHLY,BI_WEEKLY,287403
40,2025-03-03,2025-03-24,MONTHLY,MONTHLY,658658
41,2025-03-03,2025-03-24,MONTHLY,RARE_NEED,239843
42,2025-03-03,2025-03-24,MONTHLY,WEEKLY,1
43,2025-03-03,2025-03-24,RARE_NEED,BI_WEEKLY,17575
44,2025-03-03,2025-03-24,RARE_NEED,MONTHLY,141069
45,2025-03-03,2025-03-24,RARE_NEED,RARE_NEED,363920
46,2025-03-03,2025-03-24,WEEKLY,BI_WEEKLY,110657
47,2025-03-03,2025-03-24,WEEKLY,DAILY,35356
48,2025-03-03,2025-03-24,WEEKLY,WEEKLY,355854
49,2025-03-03,2025-03-31,BI_WEEKLY,BI_WEEKLY,694801
50,2025-03-03,2025-03-31,BI_WEEKLY,DAILY,41261
51,2025-03-03,2025-03-31,BI_WEEKLY,MONTHLY,309879
52,2025-03-03,2025-03-31,BI_WEEKLY,RARE_NEED,20562
53,2025-03-03,2025-03-31,BI_WEEKLY,WEEKLY,151644
54,2025-03-03,2025-03-31,DAILY,BI_WEEKLY,28480
55,2025-03-03,2025-03-31,DAILY,DAILY,330636
56,2025-03-03,2025-03-31,DAILY,MONTHLY,1782
57,2025-03-03,2025-03-31,DAILY,WEEKLY,35846
58,2025-03-03,2025-03-31,MONTHLY,BI_WEEKLY,294881
59,2025-03-03,2025-03-31,MONTHLY,DAILY,5367
60,2025-03-03,2025-03-31,MONTHLY,MONTHLY,565588
61,2025-03-03,2025-03-31,MONTHLY,RARE_NEED,248255
62,2025-03-03,2025-03-31,MONTHLY,WEEKLY,6500
63,2025-03-03,2025-03-31,RARE_NEED,BI_WEEKLY,31346
64,2025-03-03,2025-03-31,RARE_NEED,MONTHLY,134436
65,2025-03-03,2025-03-31,RARE_NEED,RARE_NEED,309701
66,2025-03-03,2025-03-31,WEEKLY,BI_WEEKLY,134154
67,2025-03-03,2025-03-31,WEEKLY,DAILY,39586
68,2025-03-03,2025-03-31,WEEKLY,MONTHLY,2186
69,2025-03-03,2025-03-31,WEEKLY,WEEKLY,323996
70,2025-03-03,2025-04-07,BI_WEEKLY,BI_WEEKLY,623003
71,2025-03-03,2025-04-07,BI_WEEKLY,DAILY,45287
72,2025-03-03,2025-04-07,BI_WEEKLY,MONTHLY,327088
73,2025-03-03,2025-04-07,BI_WEEKLY,RARE_NEED,44237
74,2025-03-03,2025-04-07,BI_WEEKLY,WEEKLY,164903
75,2025-03-03,2025-04-07,DAILY,BI_WEEKLY,33090
76,2025-03-03,2025-04-07,DAILY,DAILY,320858
77,2025-03-03,2025-04-07,DAILY,MONTHLY,4751
78,2025-03-03,2025-04-07,DAILY,WEEKLY,38460
79,2025-03-03,2025-04-07,MONTHLY,BI_WEEKLY,288135
80,2025-03-03,2025-04-07,MONTHLY,DAILY,11690
81,2025-03-03,2025-04-07,MONTHLY,MONTHLY,499543
82,2025-03-03,2025-04-07,MONTHLY,RARE_NEED,245870
83,2025-03-03,2025-04-07,MONTHLY,WEEKLY,15910
84,2025-03-03,2025-04-07,RARE_NEED,BI_WEEKLY,43491
85,2025-03-03,2025-04-07,RARE_NEED,MONTHLY,131273
86,2025-03-03,2025-04-07,RARE_NEED,RARE_NEED,265656
87,2025-03-03,2025-04-07,WEEKLY,BI_WEEKLY,150740
88,2025-03-03,2025-04-07,WEEKLY,DAILY,45654
89,2025-03-03,2025-04-07,WEEKLY,MONTHLY,9468
90,2025-03-03,2025-04-07,WEEKLY,WEEKLY,293477
91,2025-03-03,2025-04-14,BI_WEEKLY,BI_WEEKLY,569439
92,2025-03-03,2025-04-14,BI_WEEKLY,DAILY,47289
93,2025-03-03,2025-04-14,BI_WEEKLY,MONTHLY,322989
94,2025-03-03,2025-04-14,BI_WEEKLY,RARE_NEED,67807
95,2025-03-03,2025-04-14,BI_WEEKLY,WEEKLY,176049
96,2025-03-03,2025-04-14,DAILY,BI_WEEKLY,36504
97,2025-03-03,2025-04-14,DAILY,DAILY,307358
98,2025-03-03,2025-04-14,DAILY,MONTHLY,8259
99,2025-03-03,2025-04-14,DAILY,WEEKLY,43168
100,2025-03-03,2025-04-14,MONTHLY,BI_WEEKLY,288718
101,2025-03-03,2025-04-14,MONTHLY,DAILY,14112
102,2025-03-03,2025-04-14,MONTHLY,MONTHLY,449765
103,2025-03-03,2025-04-14,MONTHLY,RARE_NEED,233550
104,2025-03-03,2025-04-14,MONTHLY,WEEKLY,25180
105,2025-03-03,2025-04-14,RARE_NEED,BI_WEEKLY,50109
106,2025-03-03,2025-04-14,RARE_NEED,DAILY,2835
107,2025-03-03,2025-04-14,RARE_NEED,MONTHLY,130859
108,2025-03-03,2025-04-14,RARE_NEED,RARE_NEED,228367
109,2025-03-03,2025-04-14,RARE_NEED,WEEKLY,1993
110,2025-03-03,2025-04-14,WEEKLY,BI_WEEKLY,156761
111,2025-03-03,2025-04-14,WEEKLY,DAILY,48649
112,2025-03-03,2025-04-14,WEEKLY,MONTHLY,19351
113,2025-03-03,2025-04-14,WEEKLY,WEEKLY,272663
114,2025-03-03,2025-04-21,BI_WEEKLY,BI_WEEKLY,527058
115,2025-03-03,2025-04-21,BI_WEEKLY,DAILY,51671
116,2025-03-03,2025-04-21,BI_WEEKLY,MONTHLY,309423
117,2025-03-03,2025-04-21,BI_WEEKLY,RARE_NEED,83492
118,2025-03-03,2025-04-21,BI_WEEKLY,WEEKLY,185799
119,2025-03-03,2025-04-21,DAILY,BI_WEEKLY,38716
120,2025-03-03,2025-04-21,DAILY,DAILY,297572
121,2025-03-03,2025-04-21,DAILY,MONTHLY,10719
122,2025-03-03,2025-04-21,DAILY,RARE_NEED,1299
123,2025-03-03,2025-04-21,DAILY,WEEKLY,45861
124,2025-03-03,2025-04-21,MONTHLY,BI_WEEKLY,293460
125,2025-03-03,2025-04-21,MONTHLY,DAILY,16527
126,2025-03-03,2025-04-21,MONTHLY,MONTHLY,408965
127,2025-03-03,2025-04-21,MONTHLY,RARE_NEED,214292
128,2025-03-03,2025-04-21,MONTHLY,WEEKLY,35959
129,2025-03-03,2025-04-21,RARE_NEED,BI_WEEKLY,57014
130,2025-03-03,2025-04-21,RARE_NEED,DAILY,4809
131,2025-03-03,2025-04-21,RARE_NEED,MONTHLY,129875
132,2025-03-03,2025-04-21,RARE_NEED,RARE_NEED,195383
133,2025-03-03,2025-04-21,RARE_NEED,WEEKLY,4456
134,2025-03-03,2025-04-21,WEEKLY,BI_WEEKLY,157277
135,2025-03-03,2025-04-21,WEEKLY,DAILY,55251
136,2025-03-03,2025-04-21,WEEKLY,MONTHLY,28374
137,2025-03-03,2025-04-21,WEEKLY,RARE_NEED,1186
138,2025-03-03,2025-04-21,WEEKLY,WEEKLY,253677
139,2025-03-03,2025-04-28,BI_WEEKLY,BI_WEEKLY,491675
140,2025-03-03,2025-04-28,BI_WEEKLY,DAILY,56240
141,2025-03-03,2025-04-28,BI_WEEKLY,MONTHLY,298387
142,2025-03-03,2025-04-28,BI_WEEKLY,RARE_NEED,93820
143,2025-03-03,2025-04-28,BI_WEEKLY,WEEKLY,188944
144,2025-03-03,2025-04-28,DAILY,BI_WEEKLY,40470
145,2025-03-03,2025-04-28,DAILY,DAILY,289084
146,2025-03-03,2025-04-28,DAILY,MONTHLY,12861
147,2025-03-03,2025-04-28,DAILY,RARE_NEED,3376
148,2025-03-03,2025-04-28,DAILY,WEEKLY,48641
149,2025-03-03,2025-04-28,MONTHLY,BI_WEEKLY,289031
150,2025-03-03,2025-04-28,MONTHLY,DAILY,18833
151,2025-03-03,2025-04-28,MONTHLY,MONTHLY,376037
152,2025-03-03,2025-04-28,MONTHLY,RARE_NEED,203297
153,2025-03-03,2025-04-28,MONTHLY,WEEKLY,45237
154,2025-03-03,2025-04-28,RARE_NEED,BI_WEEKLY,63275
155,2025-03-03,2025-04-28,RARE_NEED,DAILY,5604
156,2025-03-03,2025-04-28,RARE_NEED,MONTHLY,127301
157,2025-03-03,2025-04-28,RARE_NEED,RARE_NEED,169616
158,2025-03-03,2025-04-28,RARE_NEED,WEEKLY,6056
159,2025-03-03,2025-04-28,WEEKLY,BI_WEEKLY,157479
160,2025-03-03,2025-04-28,WEEKLY,DAILY,61615
161,2025-03-03,2025-04-28,WEEKLY,MONTHLY,36475
162,2025-03-03,2025-04-28,WEEKLY,RARE_NEED,4353
163,2025-03-03,2025-04-28,WEEKLY,WEEKLY,235234
164,2025-03-03,2025-05-05,BI_WEEKLY,BI_WEEKLY,463833
165,2025-03-03,2025-05-05,BI_WEEKLY,DAILY,59968
166,2025-03-03,2025-05-05,BI_WEEKLY,MONTHLY,285585
167,2025-03-03,2025-05-05,BI_WEEKLY,RARE_NEED,97809
168,2025-03-03,2025-05-05,BI_WEEKLY,WEEKLY,192053
169,2025-03-03,2025-05-05,DAILY,BI_WEEKLY,42050
170,2025-03-03,2025-05-05,DAILY,DAILY,280356
171,2025-03-03,2025-05-05,DAILY,MONTHLY,14075
172,2025-03-03,2025-05-05,DAILY,RARE_NEED,5278
173,2025-03-03,2025-05-05,DAILY,WEEKLY,51224
174,2025-03-03,2025-05-05,MONTHLY,BI_WEEKLY,287661
175,2025-03-03,2025-05-05,MONTHLY,DAILY,20733
176,2025-03-03,2025-05-05,MONTHLY,MONTHLY,349465
177,2025-03-03,2025-05-05,MONTHLY,RARE_NEED,188333
178,2025-03-03,2025-05-05,MONTHLY,WEEKLY,53658
179,2025-03-03,2025-05-05,RARE_NEED,BI_WEEKLY,68472
180,2025-03-03,2025-05-05,RARE_NEED,DAILY,6451
181,2025-03-03,2025-05-05,RARE_NEED,MONTHLY,124144
182,2025-03-03,2025-05-05,RARE_NEED,RARE_NEED,147108
183,2025-03-03,2025-05-05,RARE_NEED,WEEKLY,8831
184,2025-03-03,2025-05-05,WEEKLY,BI_WEEKLY,155761
185,2025-03-03,2025-05-05,WEEKLY,DAILY,66764
186,2025-03-03,2025-05-05,WEEKLY,MONTHLY,41541
187,2025-03-03,2025-05-05,WEEKLY,RARE_NEED,8409
188,2025-03-03,2025-05-05,WEEKLY,WEEKLY,220425

In [48]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_fe_regularity_segment_x', 'taxi_fe_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                                                      customers  \
run_date_y                                                           2025-03-10
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                     1025982.0
                                        DAILY                           14281.0
                                        MONTHLY                        140612.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          68539.0
           DAILY                        BI_WEEKLY                        9005.0
                                        DAILY                          377031.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          16199.0
           MONTHLY                      BI_WEEKLY                      157631.0
                                        DAILY                               0.0
                                        MONTHLY                       1009967.0
                                        RARE_NEED                      128907.0
                                        WEEKLY                              0.0
           RARE_NEED                    BI_WEEKLY                           0.0
                                        DAILY                               0.0
                                        MONTHLY                         93600.0
                                        RARE_NEED                      572515.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                       61746.0
                                        DAILY                           18657.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         428454.0

                                                                                 \
run_date_y                                                           2025-03-17
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      895585.0
                                        DAILY                           24925.0
                                        MONTHLY                        212885.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         102870.0
           DAILY                        BI_WEEKLY                       16101.0
                                        DAILY                          355258.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          25998.0
           MONTHLY                      BI_WEEKLY                      242861.0
                                        DAILY                               0.0
                                        MONTHLY                        797401.0
                                        RARE_NEED                      199202.0
                                        WEEKLY                              0.0
           RARE_NEED                    BI_WEEKLY                         734.0
                                        DAILY                               0.0
                                        MONTHLY                        136571.0
                                        RARE_NEED                      438911.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                       89947.0
                                        DAILY                           25161.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         387571.0

                                                                                 \
run_date_y                                                           2025-03-24
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      785967.0
                                        DAILY                           37248.0
                                        MONTHLY                        267148.0
                                        RARE_NEED                        3011.0
                                        WEEKLY                         135274.0
           DAILY                        BI_WEEKLY                       22789.0
                                        DAILY                          344683.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          31210.0
           MONTHLY                      BI_WEEKLY                      287403.0
                                        DAILY                               0.0
                                        MONTHLY                        658658.0
                                        RARE_NEED                      239843.0
                                        WEEKLY                              1.0
           RARE_NEED                    BI_WEEKLY                       17575.0
                                        DAILY                               0.0
                                        MONTHLY                        141069.0
                                        RARE_NEED                      363920.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                      110657.0
                                        DAILY                           35356.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         355854.0

                                                                                 \
run_date_y                                                           2025-03-31
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      694801.0
                                        DAILY                           41261.0
                                        MONTHLY                        309879.0
                                        RARE_NEED                       20562.0
                                        WEEKLY                         151644.0
           DAILY                        BI_WEEKLY                       28480.0
                                        DAILY                          330636.0
                                        MONTHLY                          1782.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          35846.0
           MONTHLY                      BI_WEEKLY                      294881.0
                                        DAILY                            5367.0
                                        MONTHLY                        565588.0
                                        RARE_NEED                      248255.0
                                        WEEKLY                           6500.0
           RARE_NEED                    BI_WEEKLY                       31346.0
                                        DAILY                               0.0
                                        MONTHLY                        134436.0
                                        RARE_NEED                      309701.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                      134154.0
                                        DAILY                           39586.0
                                        MONTHLY                          2186.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         323996.0

                                                                                 \
run_date_y                                                           2025-04-07
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      623003.0
                                        DAILY                           45287.0
                                        MONTHLY                        327088.0
                                        RARE_NEED                       44237.0
                                        WEEKLY                         164903.0
           DAILY                        BI_WEEKLY                       33090.0
                                        DAILY                          320858.0
                                        MONTHLY                          4751.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          38460.0
           MONTHLY                      BI_WEEKLY                      288135.0
                                        DAILY                           11690.0
                                        MONTHLY                        499543.0
                                        RARE_NEED                      245870.0
                                        WEEKLY                          15910.0
           RARE_NEED                    BI_WEEKLY                       43491.0
                                        DAILY                               0.0
                                        MONTHLY                        131273.0
                                        RARE_NEED                      265656.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                      150740.0
                                        DAILY                           45654.0
                                        MONTHLY                          9468.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         293477.0

                                                                                 \
run_date_y                                                           2025-04-14
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      569439.0
                                        DAILY                           47289.0
                                        MONTHLY                        322989.0
                                        RARE_NEED                       67807.0
                                        WEEKLY                         176049.0
           DAILY                        BI_WEEKLY                       36504.0
                                        DAILY                          307358.0
                                        MONTHLY                          8259.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          43168.0
           MONTHLY                      BI_WEEKLY                      288718.0
                                        DAILY                           14112.0
                                        MONTHLY                        449765.0
                                        RARE_NEED                      233550.0
                                        WEEKLY                          25180.0
           RARE_NEED                    BI_WEEKLY                       50109.0
                                        DAILY                            2835.0
                                        MONTHLY                        130859.0
                                        RARE_NEED                      228367.0
                                        WEEKLY                           1993.0
           WEEKLY                       BI_WEEKLY                      156761.0
                                        DAILY                           48649.0
                                        MONTHLY                         19351.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         272663.0

                                                                                 \
run_date_y                                                           2025-04-21
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      527058.0
                                        DAILY                           51671.0
                                        MONTHLY                        309423.0
                                        RARE_NEED                       83492.0
                                        WEEKLY                         185799.0
           DAILY                        BI_WEEKLY                       38716.0
                                        DAILY                          297572.0
                                        MONTHLY                         10719.0
                                        RARE_NEED                        1299.0
                                        WEEKLY                          45861.0
           MONTHLY                      BI_WEEKLY                      293460.0
                                        DAILY                           16527.0
                                        MONTHLY                        408965.0
                                        RARE_NEED                      214292.0
                                        WEEKLY                          35959.0
           RARE_NEED                    BI_WEEKLY                       57014.0
                                        DAILY                            4809.0
                                        MONTHLY                        129875.0
                                        RARE_NEED                      195383.0
                                        WEEKLY                           4456.0
           WEEKLY                       BI_WEEKLY                      157277.0
                                        DAILY                           55251.0
                                        MONTHLY                         28374.0
                                        RARE_NEED                        1186.0
                                        WEEKLY                         253677.0

                                                                                 \
run_date_y                                                           2025-04-28
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      491675.0
                                        DAILY                           56240.0
                                        MONTHLY                        298387.0
                                        RARE_NEED                       93820.0
                                        WEEKLY                         188944.0
           DAILY                        BI_WEEKLY                       40470.0
                                        DAILY                          289084.0
                                        MONTHLY                         12861.0
                                        RARE_NEED                        3376.0
                                        WEEKLY                          48641.0
           MONTHLY                      BI_WEEKLY                      289031.0
                                        DAILY                           18833.0
                                        MONTHLY                        376037.0
                                        RARE_NEED                      203297.0
                                        WEEKLY                          45237.0
           RARE_NEED                    BI_WEEKLY                       63275.0
                                        DAILY                            5604.0
                                        MONTHLY                        127301.0
                                        RARE_NEED                      169616.0
                                        WEEKLY                           6056.0
           WEEKLY                       BI_WEEKLY                      157479.0
                                        DAILY                           61615.0
                                        MONTHLY                         36475.0
                                        RARE_NEED                        4353.0
                                        WEEKLY                         235234.0


run_date_y                                                           2025-05-05
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      463833.0
                                        DAILY                           59968.0
                                        MONTHLY                        285585.0
                                        RARE_NEED                       97809.0
                                        WEEKLY                         192053.0
           DAILY                        BI_WEEKLY                       42050.0
                                        DAILY                          280356.0
                                        MONTHLY                         14075.0
                                        RARE_NEED                        5278.0
                                        WEEKLY                          51224.0
           MONTHLY                      BI_WEEKLY                      287661.0
                                        DAILY                           20733.0
                                        MONTHLY                        349465.0
                                        RARE_NEED                      188333.0
                                        WEEKLY                          53658.0
           RARE_NEED                    BI_WEEKLY                       68472.0
                                        DAILY                            6451.0
                                        MONTHLY                        124144.0
                                        RARE_NEED                      147108.0
                                        WEEKLY                           8831.0
           WEEKLY                       BI_WEEKLY                      155761.0
                                        DAILY                           66764.0
                                        MONTHLY                         41541.0
                                        RARE_NEED                        8409.0

In [49]:
df_base_prev.groupby(['run_date', 'taxi_fe_regularity_segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date taxi_fe_regularity_segment  customers
0  2025-03-03                  BI_WEEKLY    1267511
1  2025-03-03                      DAILY     410518
2  2025-03-03                    MONTHLY    1345532
3  2025-03-03                  RARE_NEED     783225
4  2025-03-03                     WEEKLY     518532